### ISSUE TITLE
Weird error in when configuring Vault provider

### ISSUE THREAD

**Issue by jeroenjacobs79** [external-secrets/external-secrets#1024]
I have the following secretStore config:

```
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  labels:
    app.kubernetes.io/instance: dev-operators-secretstore
  name: vault-secret-store
  namespace: dev-operators
spec:
  provider:
    vault:
      auth:
        kubernetes:
          mountPath: kubernetes
          role: dev-operators
          serviceAccountRef:
            name: secret-store
      caProvider:
        key: ca-bundle.crt
        name: vault-ca-bundle
        type: ConfigMap
      path: dev-operators
      server: 'https://myvault:8200'
      version: v2
```

However, This results in the following error in the events of the resource:

```
cannot set Vault CA certificate: an empty namespace may not be set when a resource name is provided
```

I'm at a total loss here... Not only are Vault namespaces an enterprise feature, so I don't see why I should specify it since I'm on the OSS version, but I totally don't understand what it has to do with the certficate config.

And yes, I verified the referenced configmap exists, same for the service account.

**Comment by gusfcarvalho** [comment]
The issue is not with the vault namespace, but rather with the `caProvider` bit of it. Can you try the following SecretStore definition?
```
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  labels:
    app.kubernetes.io/instance: dev-operators-secretstore
  name: vault-secret-store
  namespace: dev-operators
spec:
  provider:
    vault:
      auth:
        kubernetes:
          mountPath: kubernetes
          role: dev-operators
          serviceAccountRef:
            name: secret-store
      caProvider:
        key: ca-bundle.crt
        name: vault-ca-bundle
        type: ConfigMap
        namespace: dev-operators
      path: dev-operators
      server: 'https://myvault:8200'
      version: v2
```

In any case this UX does feel different from what we are trying to achieve... I would expect in this case to ESO use the namespace of the Secret Store, and not complain about the namespace for a namespaced resource.
