### ISSUE TITLE
ArgoCD Helm rollout results with infinite sync-loop

### ISSUE THREAD

**Issue by hijmen** [external-secrets/external-secrets#1026]
When creating ExternalSecrets application in ArgoCD using the Helm Chart on auto-sync, it results in an infinite sync loop.

I am using the following chart configuration:
```yaml
installCRDs: true
```

![external-secrets-issue](https://user-images.githubusercontent.com/1532024/164195028-29364cbb-7176-470c-976e-d7e564b215db.png)

If anyone else faces this issue, I have a temporarily workaround using IgnoreDifferences in ArgoCD:

```yaml
- group: apiextensions.k8s.io
  kind: CustomResourceDefinition
  name: secretstores.external-secrets.io
  jqPathExpressions:
    - .spec.conversion.webhook.clientConfig
- group: apiextensions.k8s.io
  kind: CustomResourceDefinition
  name: externalsecrets.external-secrets.io
  jqPathExpressions:
    - .spec.conversion.webhook.clientConfig
- group: apiextensions.k8s.io
  kind: CustomResourceDefinition
  name: clustersecretstores.external-secrets.io
  jqPathExpressions:
    - .spec.conversion.webhook.clientConfig
- group: admissionregistration.k8s.io
  kind: ValidatingWebhookConfiguration
  name: secretstore-validate
  jqPathExpressions:
    - .webhooks[].clientConfig
- group: admissionregistration.k8s.io
  kind: ValidatingWebhookConfiguration
  name: externalsecret-validate
  jqPathExpressions:
    - .webhooks[].clientConfig
```
