### ISSUE TITLE
Converting webhook from v1alpha1 to v1beta1 leads to diff syncs in ArgoCD.

### ISSUE THREAD

**Issue by gusfcarvalho** [external-secrets/external-secrets#1031]
More context in #1028.

To simulate it, create the following manifests using any ArgoCD deployment:

```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: works
  namespace: default
spec:
  refreshInterval: 1m
  target:
   name: foobar
  secretStoreRef:
    name: secretstore-sample
    kind: SecretStore
  data:
    - secretKey: mysecret
      remoteRef:
        key: /foo/bar
---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: breaks
  namespace: default
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: secretstore-sample
    kind: SecretStore
  target:
    name: foobar2
  data:
    - secretKey: mysecret
      remoteRef:
        key: /foo/bar
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secretstore-sample
spec:
  provider:
    fake:
      data:
      - key: "/foo/bar"
        value: 'yadayada'
      - key: "/foo/broken"
        value: "HELLO"
      - key: "/foo/test"
        value: "f"
      - key: "/foo/baz"
        valueMap:
          foo: example
          other: thing
```
`works` ES will sync, while `breaks` ES will be degraded.
