### ISSUE TITLE
Ability to create initial ClusterSecretStore using values.yaml file

### ISSUE THREAD

**Issue by jprecuch** [external-secrets/external-secrets#1032]
**Describe the solution you'd like**
Ability to create initial ClusterSecretStore using values.yaml file options directly in external-secrets chart

**What is the added value?**
We are deploying multiple charts which are using external-secrets. The problem appears when we are dealing with dependency. 
1. We deploy external-secrets
2. Chart 2 requires CSS deployed but we can't have this one deploy it
3. Chart 3 has major code and will create CSS

In this scenario we are not able to proceed because chart2 requires CSS which is however deployed after it. The dependencies are not possible to be changed.

By having possibility to deploy initial clusterSecretStore when install external-secrets chart happens would solve this

**Give us examples of the outcome**
Something like this to enable it
```
clusterSecretStore:
    create: false
    clusterSecretStoreName: "main-cluster-secret-store"
    serviceAccountName: external-secrets
    serviceAccountNamespace: external-secrets
    serviceAccountSecretName: external-secrets-sa
    gcpProjectID: project
    gcpClusterLocation: region
    gcpClusterName: cvs-gke-name
    gcpWorkloadIdentity: true
    gcpServiceAccountCredentials: "BASE64-ENCODED-CREDS-WHEN-NOT-USING-INDENTITY"
...
```
And some code:
```
{{- if .Values.clusterSecretStore.create  }}
{{- if .Values.clusterSecretStore.gcpWorkloadIdentity }}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.clusterSecretStore.clusterSecretStoreName }}
  annotations:
    "helm.sh/hook-weight": "1"
spec:
  provider:
      gcpsm:
        projectID:  {{ .Values.clusterSecretStore.gcpProjectID }}
        auth:
          workloadIdentity:
            clusterLocation: {{ .Values.clusterSecretStore.gcpClusterLocation }}
            clusterName: {{ .Values.clusterSecretStore.gcpClusterName }}
            serviceAccountRef:
              name: {{ .Values.clusterSecretStore.serviceAccountName }}
              namespace: {{ .Values.clusterSecretStore.serviceAccountNamespace }}
{{- else if not .Values.clusterSecretStore.gcpWorkloadIdentity }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.clusterSecretStore.serviceAccountSecretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    type: gcpsm
  annotations:
    "helm.sh/hook-weight": "1"
type: Opaque
data:
  # Needs to be base64 encoded GCP service account key
  externalSecretsSaKey: {{ .Values.clusterSecretStore.gcpServiceAccountCredentials }}
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.clusterSecretStore.clusterSecretStoreName }}
  annotations:
    "helm.sh/hook-weight": "1"
spec:
  provider:
    gcpsm:
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: {{ .Values.clusterSecretStore.serviceAccountSecretName }}
            key: externalSecretsSaKey
            namespace: {{ .Release.Namespace }}
      projectID: {{ .Values.clusterSecretStore.gcpProjectID }}
{{- end }}
{{- end }}
```
**Observations (Constraints, Context, etc):**
This won't cause any harm to external-secrets chart and will give us very simple way how to have most critical secret available for other charts on the deployment of external-secrets.
