### ISSUE TITLE
Support using the version id for secrets manager secrets

### ISSUE THREAD

**Issue by matt-demers** [external-secrets/external-secrets#1036]
**Describe the solution you'd like**
Setting the `data.remoteRef.version` key in an ExternalSecret resource, which refers to a Secrets Manager secrets store, will only use the version as the [VersionStage](https://github.com/external-secrets/external-secrets/blob/main/pkg/provider/aws/secretsmanager/secretsmanager.go#L82) in the GetSecretValue api call. If you needed to get a version of the secret that is not AWSPREVIOUS or AWSCURRENT, there is no way to retrieve the secret through the ESO.

**What is the added value?**
Secrets that are more than one version old will be retrievable from the external secrets operator. Also, users will be able to specify an explicit secret version id, and that secret version will be immutable.

**Give us examples of the outcome**

On the ExternalSecret resource, I should be able to specify the secret version as either the version stage, or the version id. For instance, I could have the secret data spec look like both

```yaml
data:
  - secretKey: secret-key-to-be-managed
    remoteRef:
      key: my-aws-secret
      version: "123456-abcd-efgh-abcd-654321"
```

or

```yaml
data:
  - secretKey: secret-key-to-be-managed
    remoteRef:
      key: my-aws-secret
      version: "AWSPREVIOUS"
```

**Comment by gusfcarvalho** [comment]
hi @matt-demers ! It seems to me that it is possible to create some custom "VersionStages" to your secret during update and/or create as per [here](https://docs.aws.amazon.com/secretsmanager/latest/apireference/API_PutSecretValue.html) This would allow the user to have more control about the secret Version itself, and possibly be a little bit more versatile than just the version of the secret.

For your use case, do you believe customizing VersionStages could be a valid approach?

**Comment by gusfcarvalho** [comment]
In any case I think we can do some logic to get something like this as a way to be compatible with possible edge cases (like if someone decides to create a VersionStage called `123456-abcd-efgh-abcd-654321` :smile: ):
```
data:
  - secretKey: secret-key-to-be-managed
    remoteRef:
      key: my-aws-secret
      version: "AWSPREVIOUS"
  - secretKey: secret-key-to-be-managed
    remoteRef:
      key: my-aws-secret
      version: "uuid/123456-abcd-efgh-abcd-654321"
  
```
