### ISSUE TITLE
Support google workload identity federation

### ISSUE THREAD

**Issue by tetwatan** [external-secrets/external-secrets#1038]
Support for workload identity federation using credential configuration files.

Currently, if the credential configuration files is specified as secretAccessKeySecretRef, the following error will occur.

```
failed to create GCP secretmanager client: failed to process the provided JSON credentials: google: read JWT from JSON credentials: 'type' field is "external_account" (expected "service_account")
```

**Comment by nikotih** [comment]
we have similar setup:

- manually created workload identity federation pool (with expected audience)
- attach connected service account
- generate service account credentials (without secret)

sample:
```
{
  "type": "external_account",
  "audience": "//iam.googleapis.com/projects/<projectID>/locations/global/workloadIdentityPools/<poolName>/providers/<providerName>",
  "subject_token_type": "urn:ietf:params:oauth:token-type:jwt",
  "token_url": "https://sts.googleapis.com/v1/token",
  "service_account_impersonation_url": "https://iamcredentials.googleapis.com/v1/projects/-/serviceAccounts/<serviceAccountName>@<projectID>.iam.gserviceaccount.com:generateAccessToken",
  "credential_source": {
    "file": "/var/run/secrets/tokens/psat",
    "format": {
      "type": "text"
    }
  }
}
```

So need to exchange this credentials + SA token (see credential_source) for GCP token.

CRD might look something like:

```

apiVersion: generators.external-secrets.io/v1alpha1
kind: GCRAccessToken
metadata:
  name: gcr-gen
spec:
  projectID: "my-project"
  auth:
    jwt:
        workloadIdentityPool: foo
        provider: bar
	    serviceAccountRef:
	        name: service-account-token-to-use
	    	audience:
	    	  - foo
	    	  - bar
```

**Comment by moolen** [comment]
Let me reopen it, seems there is interest and this is a good opportunity to contribute :)

**Comment by tetsuya28** [comment]
Any plans to support Workload Identity Federation?

**Comment by nerahou** [comment]
Any updates on the matter? 
It would be highly useful to let applications running on-premises or on other cloud providers use workload identity federation to authenticate to GCP secret Manager. (Also applies for GCRAccessToken generator)

**Comment by MariusSchiffer** [comment]
I would also like to see support for this for similar reasons, but I think there are two different use cases here:

1. Use workload identity federation strictly to access secrets. For this I would propose a CRD extension. ESO should request a token using the K8s TokenRequest API for the specified k8s service account. 
With this it is possible to specify the namespace of the service account in the principal.
Example:
```yaml
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-store
  namespace: external-secrets
spec:
  provider:
    gcpsm:     
      projectID: project-id
      workloadIdentityFederation:
        serviceAccountRef:
          name: team-a
          namespace: team-a-ns # only for cluster stores
```

 (Alternatively we could add a `federated` flag and still use the existing `workloadIdentity`).

This would mean we have to generate the `GOOGLE_APPLICATION_CREDENTIALS` ourselves, similar to https://github.com/external-secrets/external-secrets/issues/1946#issuecomment-1667630229

2. Add something that actually generates GCP tokens (i.e. does the token exchange) and provides it in a secret, so it can be used for applications that cannot be used with workload identity federation.  
Sounds like an interesting idea, but feels a bit out-of-scope for ESO. I also have no idea how to do this token exchange.
