### ISSUE TITLE
ExternalSecret pointing out to non-existent SecretStore key is shown as synced

### ISSUE THREAD

**Issue by magmax** [external-secrets/external-secrets#1049]
**Describe the solution you'd like**

Two scenarios:
- Scenario A: A new ExternalSecret is created using a SecretStore key that doesn't exist. Currently, the secret is created without the key and the ExternalSecret shows a `SecretSynced` status.
- Scenario B: to remove an existing key from a `SecretStore` what is still in use by an `ExternalSecret`. Currently, the key is removed from the secret and the ExternalSecret shows a `SecretSynced` status.

In both cases, it might cause any Pod mounting the secret to fail if restarted, so the `ExternalSecret` should show the real status like `NotFoundRef`, or other representative status, allowing to create alerts under that circumstance.

**What is the added value?**

`ExternalSecret` showing the real status when keys are not found.

**Give us examples of the outcome**

Files:
- `secretstore.yaml`
```
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: fake-secrets
spec:
  provider:
    fake:
      data:
      - key: "foo"
        value: "FOO"
        version: "v1"
      - key: "bar"
        value: "BAR"
        version: "v1"
```

- `secretstore2.yaml`
```
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: fake-secrets
spec:
  provider:
    fake:
      data:
      - key: "bar"
        value: "BAR"
        version: "v1"
```

- `externalsecret.yaml`:
```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example
spec:
  refreshInterval: 2m
  secretStoreRef:
    name: fake-secrets
    kind: SecretStore
  target:
    deletionPolicy: Delete
    name: secret
  data:
  - secretKey: foo
    remoteRef:
      key: foo
      version: v1
  - secretKey: bar
    remoteRef:
      key: bar
      version: v1
```

- `deploy.yaml`:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        env:
          - name: SECRET
            valueFrom:
              secretKeyRef:
                name: secret
                key: "foo"
```

Scenario A:
- load files `secretstore2.yaml` and `externalsecret.yaml`, then `deploy.yaml`. 
- Secret will be created just with key `bar` and the pod will remain in `CreateContainerConfigError` status.

Scenario B:
- load files `secretstore.yaml` and `externalsecret.yaml`, then `deploy.yaml`. 
- when pod becomes ready, load file `secretstore2.yaml`, what will remove the `foo` key from the secret in 2 mins.
- kill the pod or try to scale it out. New pods will be in `CreateContainerConfigError` status because they do not find the secret.

**Observations (Constraints, Context, etc):**

Give here all extra information that could be interesting. Such as Golang version and Kubernetes version if you are reporting a bug/problem. You can also foresee technical constrains like "this could only be implementing using this specific technology or approach, because of this and that".

- kubernetes 1.20
- external-secrets operator 0.5.1, installed via helm chart 0.5.1
