### ISSUE TITLE
Unable to create secret if template variables contains a `-`

### ISSUE THREAD

**Issue by hlmuludiang** [external-secrets/external-secrets#1053]
**Describe the solution you'd like**
We should be able to create a secret, when the secretKey contains a `-`

**What is the added value?**
Secrets created with or without `-` in secretKey name

**Give us examples of the outcome**

**Observations (Constraints, Context, etc):**

Kubernetes 1.21
External Secrets Operator 0.5.1

Broken example:

```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dk-cfg-example
  namespace: qa1
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secret-store 
    kind: ClusterSecretStore
  target:
    name: secret-to-be-created
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ .my-secret | toString }}"
    name: secret-to-be-created
    creationPolicy: Owner
  data:
  - secretKey: my-secret
    remoteRef:
      key: lle/docker/credentials
```
Returns `SecretSyncedError` status

However, this works:

```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dk-cfg-example
  namespace: qa1
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secret-store 
    kind: ClusterSecretStore
  target:
    name: secret-to-be-created
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ .mysecret | toString }}"
    name: secret-to-be-created
    creationPolicy: Owner
  data:
  - secretKey: mysecret
    remoteRef:
      key: lle/docker/credentials
```
spec.data[0].secretKey does not contain a `-`

**Comment by gusfcarvalho** [comment]
Hi @hlmuludiang ! I see you are using templating as a way to generate your desired secrets. Indeed "middle" variables used in templating does not support a set of illegal characters, `-` included.

However, this is only the behavior for middle variables. It is possible to create secret with dashed keys both with and without templating:
Producing `-` keys with templating:
```
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secretstore-sample
spec:
  provider:
    fake:
      data:
      - key: "/foo/bar"
        value: 'yada'
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: docker-registry
  namespace: default
spec:
  refreshInterval: 1m
  target:
   name: foobar
   template:
    engineVersion: v2
    data:
      foo-bar: "{{ .mysecret }}"
  secretStoreRef:
    name: secretstore-sample
    kind: SecretStore
  data:
    - secretKey: mysecret
      remoteRef:
        key: /foo/bar
```
Producing `-` keys without templating:
```
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secretstore-sample
spec:
  provider:
    fake:
      data:
      - key: "/foo/bar"
        value: 'yada'
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: docker-registry
  namespace: default
spec:
  refreshInterval: 1m
  target:
   name: foobar
  secretStoreRef:
    name: secretstore-sample
    kind: SecretStore
  data:
    - secretKey: my-secret
      remoteRef:
        key: /foo/bar
```

Does your use-case specifically requires the variable assigned to the template to have a dash? If yes, can you detail it a little bit further what the use case is?
