### ISSUE TITLE
do not include the path in the variable name injected into a template when using AWS SSM Parameter Store

### ISSUE THREAD

**Issue by mmerickel** [external-secrets/external-secrets#1067]
**Describe the solution you'd like**

When using a `find` operator from a `dataFrom` with a `path` option, the variable generated context variable is unwieldy. Please provide a second version of the variable in the template context with the path prefix removed.

**What is the added value?**

1. It's not easy to predict the resulting name of a parameter due to path munging that occurs, replacing `/` with `_`, etc.
2. Currently a `-` is not munged, so the variables aren't even valid go values so the `index` must be used to access them which is just an extra annoyance.

**Give us examples of the outcome**

For a given `dataFrom`:

```yaml
dataFrom:
  - find:
      path: /argocd/repositories/michael-test
      name:
        regexp: '.*'
```

The current lookup is:

```yaml
target:
  template:
    username: '{{ index . "_argocd_repositories_michael-test_username" }}'
    password: '{{ index . "_argocd_repositories_michael-test_password" }}'
```

But I'd love to see simply:

```yaml
target:
  template:
    username: '{{ .username }}'
    password: '{{ .password }}'
```

**Observations (Constraints, Context, etc):**

Maybe something about using multiple finds that conflict, where they would overwrite the username? This doesn't seem like an actual problem given that there are plenty of ways to work around it. You could always leave the existing munged path version available for bw-compat and for disambiguating when querying multiple remotes that both define the same key.
