### ISSUE TITLE
It takes up to 5 minutes to see a new secret synced after creation

### ISSUE THREAD

**Issue by nausicaaonacids** [external-secrets/external-secrets#1076]
**Describe the solution you'd like**
It takes up to 5 minutes to see a new secret synced after creation. It also takes longer than the set 60s (for example) to sync existing secrets.

**What is the added value?**
Immediate availability of the secrets

**Give us examples of the outcome**

**Observations (Constraints, Context, etc):**

ESO installed with Helm chart version 0.4.3, K8s version 1.21.9. Issue exists regardless of which secret store is used, in this example we have Vault running on a separate AWS account.

Example secret template:

```yaml
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: nexus-testl
  namespace: default
spec:
  refreshInterval: "60s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: nexus-credential
    template:
      type: kubernetes.io/dockerconfigjson
  data:
  - secretKey: .dockerconfigjson
    remoteRef:
      key: k8s-management/nexus
      property: nexus-credential
```

Manifest applied to the cluster at 12:41 but secret only synced at 12:46. No sync_call errors seen on the pod, after around 5 minutes the container just shows secret is created:

```bash
kubectl logs external-secrets-77b4b66f75-lptxn -n external-secrets 
{"level":"info","ts":1651578279.372186,"logger":"controllers.ExternalSecret","msg":"reconciled secret","ExternalSecret":"default/my-secret","SecretStore":"/vault-backend"}
{"level":"debug","ts":1651578279.3722456,"logger":"events","msg":"Normal","object":{"kind":"ExternalSecret","namespace":"default","name":"my-secret","uid":"adfec3be-85f7-41f8-beec-9f16dbd54aff","apiVersion":"external-secrets.io/v1alpha1","resourceVersion":"331853"},"reason":"Updated","message":"Updated Secret"}

kubectl get externalsecrets.external-secrets.io
NAME        STORE           REFRESH INTERVAL   STATUS
my-secret   vault-backend   60s

➜  ~ kubectl get externalsecrets.external-secrets.io
NAME        STORE           REFRESH INTERVAL   STATUS
my-secret   vault-backend   60s                SecretSynced
```

Any indication of why it is taking several minutes to create the secrets?

**Comment by gusfcarvalho** [comment]
Hi @nausicaaonacids ! Can you share your ClusterSecretStore definition as well?

**Comment by nausicaaonacids** [comment]
Hi @gusfcarvalho, please see below:

```yaml
apiVersion: external-secrets.io/v1alpha1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      caBundle: "###"
      server: $VAULT_ADDR
      path: 'kv'
      version: 'v2'
      auth:
        # VaultAppRole authenticates with Vault using the
        # App Role auth mechanism
        # https://www.vaultproject.io/docs/auth/approle
        appRole:
          # Path where the App Role authentication backend is mounted
          path: 'approle'
          # RoleID configured in the App Role authentication backend
          roleId: $EXT_SECRETS_VAULT_ROLE_ID
          # Reference to a key in a K8 Secret that contains the App Role SecretId
          secretRef:
            name: 'external-secrets-approle'
            key: 'secret-id'
            namespace: $VAULT_SECRETS_OPERATOR_NAMESPACE
```
