### ISSUE TITLE
Certificate error when applying SecretStore

### ISSUE THREAD

**Issue by LG95** [external-secrets/external-secrets#1078]
**Describe the solution you'd like**
Using v0.5.2, I get a certificate error when applying a SecretStore manifest. With v0.5.1, the same manifest works fine.

**What is the added value?**
The ability to apply SecretStore manifests successfully.

**Give us examples of the outcome**
The certificate error message is 
```
Error from server (InternalError): error when creating "/tmp/manifest.yaml": Internal error occurred: failed calling webhook "validate.secretstore.external-secrets.io": Post "https://external-secrets-webhook.external-secrets.svc:443/validate-external-secrets-io-v1beta1-secretstore?timeout=5s": x509: certificate is valid for ip-<ipv4>.<region>.compute.internal, not external-secrets-webhook.external-secrets.svc
```

The manifest basically is
```yaml
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: test
spec:
  provider:
    aws:
      auth:
        jwt:
          serviceAccountRef:
            name: <account>
      region: <region>
      service: SecretsManager
```

**Observations (Constraints, Context, etc):**
The cluster is on AWS EKS with Kubernetes v1.21 and Fargate nodes.
I am installing with the following commands
```bash
helm repo add external-secrets https://charts.external-secrets.io
helm install external-secrets external-secrets/external-secrets -n external-secrets --set installCRDs=true
```
