### ISSUE TITLE
[2] PushSecret: Platform Engineers can install ESO via helm

### ISSUE THREAD

**Issue by ladeoshodi** [external-secrets/external-secrets#1090]
Epic: https://github.com/external-secrets/external-secrets/issues/976

### Acceptance Criteria
**Scenario**: A platform engineer can install ESO via helm
**Given** a platform engineer is getting started with ESO
**When** the platform engineer runs the [helm command to install ESO](https://external-secrets.io/v0.5.1/guides-getting-started/) 
**Then** the platform engineer is able to confirm that ESO is installed and the CRD contains Write configuration by running `kubectl apply -f some yaml file`

#### Notes
* Add SecretSink CRD

* YAML File to test:
```
apiVersion: external-secrets.io/v1alpha1
kind: SecretSink
metadata:
  name: "hello-world"
  namespace: default
spec:
  secretStoreRefs:
  - name: secret-store
    kind: SecretStore
  - name: secret-store-2
    kind: SecretStore
  - name: cluster-secret-store
    kind: ClusterSecretStore
  selector:
    secret:
      name: foobar
  data:
  - match:
     - secretKey: foobar
       remoteRefs:
       - remoteKey: my/path/foobar 
```
