### ISSUE TITLE
Webhook Provider: Allow for webhook SecretStores that fulfill .data[] and .dataFrom[].extract

### ISSUE THREAD

**Issue by nstogner** [external-secrets/external-secrets#1132]
**Describe the solution you'd like**

I don't currently see a way of implementing a single SecretStore with the webhook provider that can fulfill a request for the following cases:

1. ExternalSecret with `.data[]` (i.e. `GetSecret()`)
2. ExternalSecret with `.dataFrom[].extract` (i.e. `GetSecretMap()`)

The issue being that GetSecretMap() expects an object (map[string]string) and GetSecret() expects a string. They both utilize the same `.url` and `.result.jsonPath` so they both look at the exact same data returned by the webhook.

**What is the added value?**

Users wont need to know what SecretStore to use when they specify `.data` / `.dataFrom[].extract`.

**Give us examples of the outcome**

The options I see:

1. [Workaround - today] Utilize separate SecretStores for each usecase that specify different webhook URLs / paths.
2. Add the ability to specify a different url/path based on the usecase.
3. Add a template variable (i.e. `.mode = "extract"` OR `.extract = true`) that can be used to conditionally set a header/url/etc.
4. Allow for a different `.result.jsonPath` to be used for the different cases.

**Comment by gusfcarvalho** [comment]
Hi @nstogner ! I believe you can actually set multiple paths dynamically via the webhook Store. for instance:

```
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: webhook-backend
spec:
  provider:
    webhook:
      url: "http://example.com/mysecrets/{{ .remoteRef.key }}"
      result:
        jsonPath: "$.args.parameter"
      headers:
        Content-Type: application/json
        Authorization: Basic {{ print .auth.username ":" .auth.password | b64enc }}
      secrets:
      - name: auth
        secretRef:
          name: webhook-credentials
---
apiVersion: v1
kind: Secret
metadata:
  name: webhook-credentials
data:
  username: dGVzdA== # "test"
  password: dGVzdA== # "test"
```

would allow a `data` and a `dataFrom` to reach different endpoints in the same URL (of course, if the remoteKey is different), since the `url` field is actually template-able.

I belive this would cover case number 2. Please correct me if I misunderstood it :smile:

**Comment by nstogner** [comment]
Assuming that the `.remoteRef.key` field references a given secret on an external system, I would think the key would be the same for `.data` and `.dataFrom` (see below). The difference would be that `.data` would be fetching a single field out of that secret references by `.key` and `.dataFrom[].extract` would be requesting all fields from the secret referenced by `.key`. Is that the correct interpretation?

```yaml
  # Data defines the connection between the Kubernetes Secret keys and the Provider data
  data:
    - secretKey: secret-key-to-be-managed
      remoteRef:
        key: provider-key # <----
        version: provider-key-version
        property: provider-key-property

  # Used to fetch all properties from the Provider key
  # If multiple dataFrom are specified, secrets are merged in the specified order
  dataFrom:
  - extract:
      key: provider-key # <----
      version: provider-key-version
      property: provider-key-property
      conversionStrategy: Default
```
