### ISSUE TITLE
Upgrading from v1alpha1 to v1beta1 via Flux Kustomization causes dry-run failure warnings

### ISSUE THREAD

**Issue by artem-nefedov** [external-secrets/external-secrets#1136]
Upgrading ExternalSecrets of apiVersion v1alpha1 into v1beta1 via flux2 Kustomization object would cause repeating warnings reported by Flux kustomization controller, which also cause Kustomization reconciliation to randomly fail:

`
  Warning  ReconciliationFailed     5m16s (x14 over 85m)  kustomize-controller  ExternalSecret/some-namespace/some-name dry-run failed, error: failed to prune fields: failed add back owned items: failed to convert pruned object at version external-secrets.io/v1beta1: conversion webhook for external-secrets.io/v1alpha1, Kind=ExternalSecret returned invalid metadata: invalid metadata of type <nil> in input object
`

If you wait long enough, Kustomization reconciliation will eventually succeed, and ExternalSecret objects will be upgraded to v1beta1, but Kustomization object will still keep to get those warnings endlessly, and Kustomization will randomly become degraded because of that.

If v1beta1 ExternalSecret is deployed from scratch, there are no problems.

**Reproduction steps:**

1. Deploy external-secrets v0.3.10
2. Deploy ExternalSecret object with apiVersion v1alpha1 using Flux2 Kustomization (must contain `wait: true` field in spec to enable health checks)
3. Upgrade external-secrets to v0.5.3
4. Change ExternalSecret object manifest in Flux source to v1beta1
5. Wait for some time (exact time may vary) and check events of Kustomization object

**Observations (Constraints, Context, etc):**

Kubernetes 1.22 (EKS)
external-secrets v0.5.3
flux2 v0.30.2

Note: Flux2 kustomize-controller performs server-side apply when handling objects.

**Comment by gusfcarvalho** [comment]
Hi @artem-nefedov ! can you provide a sample ExternalSecrets manifest?

**Comment by artem-nefedov** [comment]
@gusfcarvalho sure

```yaml
---
apiVersion: external-secrets.io/v1alpha1
kind: ClusterSecretStore
metadata:
  name: aws-secrets-manager
spec:
  provider:
    aws:
      region: us-west-2
      service: SecretsManager
---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: example
spec:
  data:
  - remoteRef:
      key: secret-name
      property: foo
      version: AWSCURRENT
    secretKey: foo
  - remoteRef:
      key: secret-name
      property: bar
      version: AWSCURRENT
    secretKey: bar
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    creationPolicy: Owner
    name: example
```

For upgrade, just change apiVersion to v1beta1 and nothing else.
