### ISSUE TITLE
Add support for Hashicorp Vault mTLS

### ISSUE THREAD

**Issue by ambis** [external-secrets/external-secrets#1139]
**Describe the solution you'd like**
My Vault needs a client certificate & key to be presented when communicating with it (vault cli envs `VAULT_CLIENT_CERT` and `VAULT_CLIENT_KEY`, vault server config `tls_require_and_verify_client_cert` and `tls_client_ca_file`). 

Looking at the API reference documentation, it seems that the ESO does not provide a way to supply these client certificates.

**What is the added value?**
I keep my publicly visible Vault extra protected via mTLS.

**Give us examples of the outcome**

SecretRefs for client cert+key, just like for so many other secretRefs in the config already. 

Thanks.

**Comment by moolen** [comment]
Vault has cert auth: 

https://external-secrets.io/v0.5.3/spec/#external-secrets.io/v1beta1.VaultCertAuth

Does that work for you?

I realized this is missing on the provider docs

**Comment by ambis** [comment]
@moolen Thanks, but that is a completely different thing to mTLS.

mTLS requires you to have a key+cert present for ALL requests to Vault. They do not provide any identity (altough they can, but Vault does not support that), only the possibility to even talk to the Vault.

mTLS is not Vault spesific technology, it is basic mutual-TLS feature supported by pretty much any server (nginx, haproxy etc).

You can read more about it here: https://www.cloudflare.com/learning/access-management/what-is-mutual-tls/

**Comment by gusfcarvalho** [comment]
Hi @ambis ! What is your current way to authenticate to vault right now?

**Comment by ambis** [comment]
For authentication I use OIDC (personal login), AppRole, JWT (gitlab $CI_JOB_JWT) and also the Kubernetes backend for Kubernetes auth. 

Altough I fail to see the relevance of my auth methods with the simple fact, that I cannot even query `vault status` without providing mTLS cert+key.

I run Vault behind Cloudflare, which provides the mTLS cert+key and their CA cert. It is the first place they are verified, but they are also passed to my Vault backend where Vault will revalidate them. 

This is my Vault listener config:

```hcl
listener "tcp" {
  address = "0.0.0.0:8443"
  tls_cert_file = "xx/cf_origin_tls.crt"
  tls_key_file = "xx/cf_origin_tls.key"
  tls_client_ca_file = "xx/cf_ca.crt"
  tls_require_and_verify_client_cert = true
}
```

Which means, that **no connection** that does not provide cert+key signed by the `tls_client_ca_file` will even end up in the Vault's API. 

Maybe you are familiar with the Vault's helm chart and it's csi, which I have configured like so:

```yaml
csi:
  image:
    tag: "1.1.0"
  enabled: true
  extraArgs:
    - -vault-addr=https://my.vault.address.example.com
    - -vault-mount=path-to-my-kube-mount
    **- -vault-tls-client-key=/vault/tls/client.key**
    **- -vault-tls-client-cert=/vault/tls/client.crt**
  volumes:
    - name: tls
      secret:
        **secretName: vault-tls-client**
  volumeMounts:
    - name: tls
      mountPath: "/vault/tls"
      readOnly: true
```

Here's another example:

No client cert+key provided for vault, the error code, 1020 is Cloudflare's error code to tell that the client certificate is missing.
```sh
~ $ VAULT_ADDR=https://my.vault.address.example.com vault status
Error checking seal status: Error making API request.

URL: GET https://vault.mpnsvc.com/v1/sys/seal-status
Code: 403. Raw Message:

error code: 1020
exit 1
```

Here I provide the client cert+key:

```sh
~ $ VAULT_CLIENT_CERT=/some/path/tls.crt VAULT_CLIENT_KEY=/some/path/tls.key VAULT_ADDR=https://my.vault.address.example.com vault status
Key                      Value
---                      -----
Recovery Seal Type       shamir
Initialized              true
Sealed                   false
Total Recovery Shares    1
Threshold                1
Version                  1.10.3
Storage Type             raft
Cluster Name             vault
Cluster ID               4ef3f670-873c-9f88-xx
HA Enabled               true
HA Cluster               https://10.0.0.10:8201
HA Mode                  active
Active Since             2022-05-15T10:36:49.04326185Z
Raft Committed Index     13856
Raft Applied Index       13856
```

Would this be enough information to make it clear that we are not talking about Vault's mTLS auth method?
