### ISSUE TITLE
Can we check if this affects us? Codecov Bash Uploader Security Problem

### ISSUE THREAD

**Issue by knelasevero** [external-secrets/external-secrets#115]
I did not look into it in detail, but maybe we need to rotate all our secrets on the repo:

https://about.codecov.io/security-update/?utm_medium=email&utm_source=marketo&ajs_uid=2641171&ajs_event=Clicked%20Email&mkt_tok=MzMyLUxWWC03NDEAAAF8dJvA-xZxt2j33aipJ7hxMDse40UaW6Hntt6vbcITlfxojzi3S8ptsQJH4e9YLSa3_YS4XoT0ibSG6dilmVVQ_ppjMRoK6Dt3Q-fHCqUn

**Comment by knelasevero** [comment]
@riccardomc got an email about our original CS solution, and I am rotating our secrets there. Not sure why we were not affected here.

**Comment by moolen** [comment]
I think we shouldn't be affected when looking at the pipeline:

```yaml
      - name: Publish Unit Test Coverage
        uses: codecov/codecov-action@v1
        with:
          flags: unittests
          file: ./cover.out
```

From the blog post:

> * (1) Any credentials, tokens, or keys that our customers were passing through their CI runner that would be accessible **when the Bash Uploader script was executed**.
> * (1b) Any services, datastores, and application code that could be accessed **with these credentials**, tokens, or keys.
> * (2) The git remote information of repositories using the Bash Uploaders to upload coverage to Codecov in CI.

We don't pass any secret/environment variables into it, so 1 and 1b does not apply, 2 is public information anyway. 

Rotating credentials regularly isn't a bad idea anyway ;)
