### ISSUE TITLE
Advanced Templating Results in bad character U+002D '-'

### ISSUE THREAD

**Issue by KrisJohnstone** [external-secrets/external-secrets#1154]
**Error Description**
When attempting to use the advanced templating functionality I'm getting a parsing error, I've tried both methods as described here:
https://external-secrets.io/v0.5.3/guides-templating/

**Outcome**
_Error Message:_
could not apply template: could not execute template: unable to execute template at key config.yaml: unable to parse template at key config.yaml: templa │
│ te: config.yaml:4: bad character U+002D '-'

**Expected Outcome**
Secret created.

**Observations (Constraints, Context, etc):**
_Kuberenetes Version:_ EKS (v1.22)
_ESO Version:_ 0.5.3

_External Secret:_
```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rds-exporter-config
  namespace: xxxx-monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secretstore-aws-sm
    kind: ClusterSecretStore
  target:
    name: rds-exporter-config
    template:
      type: Opaque
      engineVersion: v2
      data:
        config.yaml: |
          instances:
            - region: ap-southeast-2
              instance: xxxx-engine
              aws_access_key: "{{ .access-key }}"
              aws_secret_key: "{{ .secret-key }}" 
              disable_basic_metrics: false
              disable_enhanced_metrics: false
  data:
    - secretKey: access-key
      remoteRef:
        key: cluster-prod-xxxx-rds-exporter
        property: accessKey
    - secretKey: secret-key
      remoteRef:
        key: cluster-prod-xxxx-rds-exporter
        property: secretKey
```

**Comment by Jojoooo1** [comment]
Same problem here.

**Comment by moolen** [comment]
This is a limitation of the go template language. You can not use "-" in variable names, see this thread for related info and fixes: https://github.com/helm/helm/issues/2192

**Comment by moolen** [comment]
@Jojoooo1 @KrisJohnstone For the given example above, would the following work for you:

```yaml
aws_access_key: "{{ index . "access-key" }}"
```

**Comment by KrisJohnstone** [comment]
duh ofc. yes that would be more then fine, ill just swap to using camelCase :)

**Comment by Jojoooo1** [comment]
Also swaped to camelCase :)

**Comment by moolen** [comment]
Thanks for your response, closing then. Feel free to reopen if you have further questions.

**Comment by hlascelles** [comment]
@moolen has the right solution I would say. The convention for key names in k8s is lowercase kebab strings, like subdomains. I'd stick with those.

**Comment by mrclrchtr** [comment]
In case someone gets lost here like me.

For me, this one was not working:
> @Jojoooo1 @KrisJohnstone For the given example above, would the following work for you:
> 
> ```yaml
> aws_access_key: "{{ index . "access-key" }}"
> ```

But this one:

```
mariadb-root-password: "{{ index . `mariadb-root-password` | b64enc }}"
```

**Comment by amine7777** [comment]
This is super silly, you need to create a secretKey that doesn't have a hyphen '-'

```
spec:
  data:
    - remoteRef:
        key: rabbitmq-password
      secretKey: rabbitmqpassword
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: rabbitmq
  target:
    creationPolicy: Owner
    name: rabbitmq-load-definition
    template:
      data:
        load_definition.json: |
          {
            "password": "{{  .rabbitmqpassword  }}"
          }
      engineVersion: v2
      mergePolicy: Replace 
```
