### ISSUE TITLE
ClusterExternalSecret - namespaceSelector + matchExpression + In operator + multiple values = broken

### ISSUE THREAD

**Issue by nicolas-vivot** [external-secrets/external-secrets#1155]
**Context**

I'm trying to deploy CES, targetting multiple namespaces.
The creation of the CES itself is working fine, and i'm using the following namespace selector:
`  namespaceSelector:
    matchExpressions:
      - {key: kubernetes.io/metadata.name, operator: In, values: [gol,core,transversal,authentication]}
`
But the ExternalSecret objects are not created into the targetted namespaces.
On the operator logs we found this error, coming from the reconcile operation:

`"ClusterExternalSecret","name":"go-configurations","namespace":"","error":"operator \"In\" without a single value cannot be converted into the old label selector format"`

**Code issue location**

On the ESO side, it seems that the code generating this error is [that reconcile function](https://github.com/external-secrets/external-secrets/blob/main/pkg/controllers/clusterexternalsecret/clusterexternalsecret_controller.go#L79).

It's using the **LabelSelectorAsMap** function on machinery, and this function is returning the given error.
On the machinery code [located here](https://github.com/kubernetes/apimachinery/blob/master/pkg/apis/meta/v1/helpers.go#L88-L93), we clearly see there is a strict check on size 1 is done, while we are providing multiple values, therefore we get the error.

**Remarks / improvements**

The machinery code does not seems to be in cause here, but more how it is used in ESO. 

**The reconcile function is using LabelSelectorAsMap and then SelectorFromSet if it passes the first one.
Why not calling LabelSelectorAsSelector in place of LabelSelectorAsMap ?** 

Can someone have a look at it please ?

**Comment by pa250194** [comment]
Hey @nicolas-vivot I ran into the same issue. One way I was able to get it to work is by doing as a workaround.

```
namespaceSelector:
    matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: In
        values:
          - "gol"
      - key: kubernetes.io/metadata.name
        operator: In
        values:
          - "core"
      - key: kubernetes.io/metadata.name
        operator: In
        values:
          - "transversal"
```
