### ISSUE TITLE
Client unable to fetch identitybindingtoken when accessing Google Secrets Manager

### ISSUE THREAD

**Issue by dsvua** [external-secrets/external-secrets#1156]
I deployed external secrets 0.5.2 and then upgraded to 0.5.3. Both versions have exactly the same issue.

Service account `external-secrets` is created in IAM and those roles are attached: `Secret Manager Secret Accessor`, `Service Account Token Creator` and `Workload Identity User`.

GKE cluster has Workload Identity = true.

GKE service account definition:
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: global-external-secrets
  namespace: external-secrets
  annotations:
    iam.gke.io/gcp-service-account: external-secrets@********.iam.gserviceaccount.com
```
ClusterSecretStore
```yaml
apiVersion: external-secrets.io/v1alpha1
kind: ClusterSecretStore
metadata:
  name: clustersecretstore-jackpocket
spec:

  # Used to select the correct ESO controller (think: ingress.ingressClassName)
  # The ESO controller is instantiated with a specific controller name
  # and filters ES based on this property
  # Optional
  # controller: dev

  # provider field contains the configuration to access the provider
  # which contains the secret exactly one provider must be configured.
  provider:
    # GCP Secret Manager
    gcpsm:
      # Auth defines the information necessary to authenticate against GCP by getting
      # the credentials from an already created Kubernetes Secret.
      projectID: Jackpocket
      auth:
        workloadIdentity:
          # name of the cluster region
          clusterLocation: us-central1-c
          # name of the GKE cluster
          clusterName: *****-production
          # reference the sa from above
          serviceAccountRef:
            name: global-external-secrets
            namespace: external-secrets
```
however, I still see error messages like this:
```
"could not get provider client: failed to create GCP secretmanager client: unable to fetch identitybindingtoken: could not get idbindtoken token, status: 404"
```

As end result, secret is not created and application's containers does not start.

**Comment by gusfcarvalho** [comment]
Hi @dsvua ! Is this a regional (multi zonal) cluster or a single zone? If you have a multi zone you need to specify the region, not the zone. This might be the issue here

**Comment by dsvua** [comment]
Changed from `us-central1-c` to `us-central1` - still the same

**Comment by knowhoper** [comment]
I am seeing exactly the same behaviour.

> {"level":"error","ts":1652943931.4031851,"logger":"controller.secretstore","msg":"Reconciler error","reconciler group":"external-secrets.io","reconciler kind":"SecretStore","name":"cluster-secret-store-gcp-dev","namespace":"external-secrets","error":"could not get provider client: failed to create GCP secretmanager client: missing SecretAccessKey","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:227"}



yaml:

```
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: cluster-secret-store-gcp-dev
spec:
  provider:
    gcpsm:
      projectID: acme-dev-tooling
      auth:
        workloadIdentity:
          clusterLocation: "australia-southeast-1a"
          clusterName: "dev-gke-aus-se1a"
          clusterProjectID: "acme-development"
          serviceAccountRef:
            name: "acme-secrets-reader"
            namespace: "external-secrets"
```
