### ISSUE TITLE
External Secret default fields do not work as described in documentation

### ISSUE THREAD

**Issue by cnmcavoy** [external-secrets/external-secrets#117]
**Describe the solution you'd like**
Default fields should not be required to be explicitly supplied by users creating resources.

**Observations (Constraints, Context, etc):**

For example:
```
$ kubectl explain secretstore.spec.provider.vault

FIELDS:
...
   path <string> -required-
     Path is the mount path of the Vault KV backend endpoint, e.g: "secret". The
     v2 KV secret engine version specific "/data" path suffix for fetching
     secrets from Vault is optional and will be appended if not present in
     specified path.
...
   version	<string> -required-
     Version is the Vault KV secret engine version. This can be either "v1" or
     "v2". Version defaults to "v2".
```

But when creating a secret store resource, without specifying the vault version or secret path mount :
```
apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: example-secretstore
spec:
  provider:
    vault:
      server: "https://vault.example.com"
#      version: v2
#      path: secret
      auth:
        kubernetes:
          mountPath: "kubernetes/example-cluster"
          serviceAccountRef:
            name: "default"
          role: "default"
 ```
 kubectl prevents creating this resource:
 ```
 $ kubectl apply -f /tmp/ss.yaml
 
error: error validating "/tmp/ss.yaml": error validating data: [ValidationError(SecretStore.spec.provider.vault): missing required field "path" in io.external-secrets.v1alpha1.SecretStore.spec.provider.vault, ValidationError(SecretStore.spec.provider.vault): missing required field "version" in io.external-secrets.v1alpha1.SecretStore.spec.provider.vault]; if you choose to ignore these errors, turn validation off with --validate=false
 ```
