### ISSUE TITLE
AWS EKS + IRSA - ESO assuming correct role for one secret, and wrong role for another

### ISSUE THREAD

**Issue by zen** [external-secrets/external-secrets#1175]
**Describe the solution you'd like**

ESO v0.5.3, helm deployed

It's probably a bug. I'm using ESO in many cases on the same cluster, with the same configuration and it works correctly. Just this one case is pretty cryptic.
The only difference in this case is that I'm attempting to use 2 secrets generated from ESO in one deployment, one mapped as env vars (env.valueFrom.secretKeyRef) and and second by volume (volumes.secret.secretName). It worked perfectly until migration to this ExternalSecrets from GoDaddy old implementation. We've also added JWT auth for ESO per namespace / ServiceAccount. Really scratching my head to figure out what's happening.

Both secrets in the same namespace. I have many more ExternalSecrets in the same NS working fine.

Essentially one secret is generated, the second one fails with:

```
AccessDeniedException: User: arn:aws:sts::xxxxx:assumed-role/k8s-ui-apps/external-secrets-provider-aws is not authorized to perform: secretsmanager:GetSecretValue on resource: my_app2/prod/user because no identity-based policy allows the secretsmanager:GetSecretValue action status code: 400,
```

For some reason ESO is assuming some default role from here: https://github.com/external-secrets/external-secrets/blob/main/pkg/provider/aws/auth/auth.go#L227

Everything is managed by Argo

I have a SecretStore with following configuration:

```yaml
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: ui-apps
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-southeast-1
      auth:
        jwt:
          serviceAccountRef:
            name: ui-apps-sa-prod
```

Service account `ui-apps-sa-prod` has policy attached and role defined as per IRSA configuration (i'm using it in many other places). The policy allows reading all secrets mentioned below.

Secrets:

```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ui-apps-1-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: ui-apps
    kind: SecretStore
  target:
    name: secrets1
    creationPolicy: Owner
  dataFrom:
    - extract:
      key: tool/prod/app1
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ui-apps-2-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: ui-apps
    kind: SecretStore
  target:
    name: secrets2
    creationPolicy: Owner
  dataFrom:
    - extract:
      key: othertool/prod/secrets
```

Not sure where could I look for answers.
