### ISSUE TITLE
Hashicorp Vault: Support Databases PostgreSQL Secrets Engine

### ISSUE THREAD

**Issue by James-Quigley** [external-secrets/external-secrets#1199]
**Describe the solution you'd like**
Support injecting dynamic secrets from the Postgres secrets engine in Hashicorp Vault: https://www.vaultproject.io/docs/secrets/databases/postgresql. Documentation says that only the KV Secrets engine is supported

**What is the added value?**
This would allow applications to have dynamic credentials to a Postgres database available to them without needing to utilize vault client libraries

**Give us examples of the outcome**

Dynamic database credentials exist in native Kubernetes Secrets, injected from Hashicorp Vault

**Comment by diequeiroz** [comment]
I thought about this. We are close to achieving this by using database path in SecretStore:

```yaml
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend-db
spec:
  provider:
    vault:
      server: "http://vault.vault:8200"
      path: "database"
      version: "v1"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "demo-role"
```

The only thing keeping us from getting database credentials is the fact that the provider revokes itself after getting the secret: #381 

It would be nice to have: 
- An option to prevent token revocation
- Skipping sync if current lease is still valid
- Store lease id in secrets metadata so we can renew the lease while the application is connected to database
