### ISSUE TITLE
1Password: SecretStore and ExternalSecret handle vaults differently?

### ISSUE THREAD

**Issue by WesleyKlop** [external-secrets/external-secrets#1202]
**A bit of context**

 - External secrets version: `0.5.3`
 - 1password connect version: `1.7.1`

I already had 1password connect operator running on my cluster so I tried to add external-secrets because I'm excited about this project :)

I got external-secrets as far that it would reuse the connect-token and connect to 1password connect. See `ClusterSecretStore` definition: https://github.com/WesleyKlop/infrastructure/blob/387f1082c463925c9237a13ff371b534b3d0e79c/apps/external-secrets/idris/templates/1password-secret-store.yaml

**The issue**

But when I use the vault **title** the store has the following status:
```yaml
status:
  conditions:
    - lastTransitionTime: '1337-13-37T137:37:42Z'
      message: unable to validate store
      reason: ValidationFailed
      status: 'False'
      type: Ready
```
The related event message is `status 400: Invalid Vault UUID`

But when I use the vault **id** the store validates properly and becomes ready! But that gives the next issue: creating an ExternalSecret using the declared store will fail to create the secret, having the following status:
```yaml
status:
  conditions:
    - lastTransitionTime: '1337-13-37T137:37:42Z'
      message: could not get secret data from provider
      reason: SecretSyncedError
      status: 'False'
      type: Ready
```
The related event message is `expected one 1Password Vault matching 'thevaultuuidthatiuse', got 0`

I've also tried referring to the ExternalSecret remoteKey.{key,property} by uuid but that (obviously?) doesn't help either. 
Might this be because I'm using a newer 1password connect version than is supported? Or is this fixed by #1173 ?

**Thanks**

If there is any way I can help or test just let me know and thanks for maintaining this cool project! :)
