### ISSUE TITLE
ESO v0.5.5, ClusterSecretStore, k8s auth (service account) in Hashicorp Vault not working

### ISSUE THREAD

**Issue by spirkaa** [external-secrets/external-secrets#1220]
No changes in any configs and difinitions other than chart version. ESO in own namespace, service account in "vault" namespace.

0.5.3 working fine, 0.5.5 failing with these logs:

`{"level":"error","ts":1654068207.142485,"logger":"controllers.ClusterSecretStore","msg":"unable to validate store","clustersecretstore":"/vault-backend","error":"could not validate provider: invalid vault credentials: Error making API request.\n\nURL: GET http://vault.vault:8200/v1/auth/token/lookup-self\nCode: 403. Errors:\n\n* permission denied","stacktrace":"github.com/external-secrets/external-secrets/pkg/controllers/secretstore.(*ClusterStoreReconciler).Reconcile\n\t/home/runner/work/external-secrets/external-secrets/pkg/controllers/secretstore/clustersecretstore_controller.go:55\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:114\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:311\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:227"}`

`{"level":"error","ts":1654068207.1514857,"logger":"controller.clustersecretstore","msg":"Reconciler error","reconciler group":"external-secrets.io","reconciler kind":"ClusterSecretStore","name":"vault-backend","namespace":"","error":"could not validate provider: invalid vault credentials: Error making API request.\n\nURL: GET http://vault.vault:8200/v1/auth/token/lookup-self\nCode: 403. Errors:\n\n* permission denied","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:227"}`

**ClusterSecretStore definition**
```yaml
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: http://vault.vault:8200
      path: secret
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: vault-external-secrets
          serviceAccountRef:
            name: vault-external-secrets
            namespace: vault
```

**Comment by aaronchar** [comment]
Okay so I have been thinking this was just me.  I am having the exact same issue.

**Comment by gusfcarvalho** [comment]
Thank you for your investigation @aaronchar. I'm looking into it right now

**Comment by aaronchar** [comment]
@gusfcarvalho  - I actually just grabbed the new version. I am still using the 0.5.5 operator but updating the tag

I am still seeing the same error

```
{"level":"error","ts":1654102578.1161554,"logger":"controllers.ClusterSecretStore","msg":"unable to validate store","clustersecretstore":"/example","error":"could not validate provider: invalid vault credentials: Error making API request.\n\nURL: GET https://<my host>/v1/auth/token/lookup-self\nCode: 400. Errors:\n\n* missing client token","stacktrace":"github.com/external-secrets/external-secrets/pkg/controllers/secretstore.(*ClusterStoreReconciler).Reconcile\n\t/home/runner/work/external-secrets/external-secrets/pkg/controllers/secretstore/clustersecretstore_controller.go:55\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:114\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:311\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:227"}
{"level":"error","ts":1654102578.1254807,"logger":"controller.clustersecretstore","msg":"Reconciler error","reconciler group":"external-secrets.io","reconciler kind":"ClusterSecretStore","name":"telco-cloud-active-directory","namespace":"","error":"could not validate provider: invalid vault credentials: Error making API request.\n\nURL: GET https://<my host>/v1/auth/token/lookup-self\nCode: 400. Errors:\n\n* missing client token","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:227"}
```

```
    spec:
      containers:
      - args:
        - --controller-class=<class name>
        - --concurrent=5
        image: ghcr.io/external-secrets/external-secrets:v0.5.6
        imagePullPolicy: IfNotPresent
        name: external-secrets
````

**Comment by gusfcarvalho** [comment]
I reran some tests locally and I can confirm the issue with the current code base should be fixed already... Maybe worth the shot to try to update again to 0.5.6?

**Comment by gusfcarvalho** [comment]
The tests manifests I used, for reference:

NonReferent ClusterSecretStore

```
apiVersion: external-secrets.io/v1beta1 
kind: ClusterSecretStore
metadata: 
  name: vault-backend2 
spec:                
  provider:
    vault:        
      server: http://vault.vault:8200
      path: kv               
      version: v2
      auth:             
        kubernetes:
          mountPath: kubernetes
          role: demo-role
          serviceAccountRef: 
            name: external-secrets
---
 apiVersion: external-secrets.io/v1beta1
 kind: ExternalSecret
 metadata:
   name: vault-example2
   namespace: es     
 spec:
   secretStoreRef:
     name: vault-backend2
     kind: ClusterSecretStore
   target:
     name: example-sync2
   data:
   - secretKey: foobar
     remoteRef:
       key: path/to/my/secret
       property: password
```
Referent ClusterSecretStore

```
apiVersion: external-secrets.io/v1beta1 
kind: ClusterSecretStore
metadata: 
  name: vault-backend  
spec:                
  provider:       
    vault:              
      server: http://vault.vault:8200
      path: kv               
      version: v2       
      auth:             
        kubernetes:   
          mountPath: kubernetes
          role: demo-role    
          serviceAccountRef: 
            name: external-secrets
            namespace: es
---
 apiVersion: external-secrets.io/v1beta1
 kind: ExternalSecret   
 metadata:
   name: vault-example1
   namespace: default
 spec:               
   secretStoreRef:
     name: vault-backend
     kind: ClusterSecretStore      
   target:                   
     name: example-sync1
   data:                
   - secretKey: foobar
     remoteRef:                
       key: path/to/my/secret
       property: password    

```

**Comment by aaronchar** [comment]
@gusfcarvalho - Okay it works, not sure what happened the first time but i forcefully removed everything and brought it up with 5.6 and everything is back to working.

Sorry about that.

**Comment by gusfcarvalho** [comment]
No worries! Glad to know it worked!

**Comment by noroutine** [comment]
Hi @gusfcarvalho, @aaronchar 

Found this fresh discussion

I observe same errors after upgrading from v0.5.4 to v0.5.6

Seemingly valid setup stopped to work with exact same validation errors. Samples below

```
{"level":"error","ts":1654113983.9709027,"logger":"controller.externalsecret","msg":"Reconciler error","reconciler group":"external-secrets.io","reconciler kind":"ExternalSecret","name":"cpi-global-secret","namespace":"kube-system","error":"the desired SecretStore bo01-vault is not ready","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:227"}
```
```
{"level":"error","ts":1654114997.107671,"logger":"controller.clustersecretstore","msg":"Reconciler error","reconciler group":"external-secrets.io","reconciler kind":"ClusterSecretStore","name":"bo01-vault","namespace":"","error":"could not validate provider: invalid vault credentials: Error making API request.\n\nURL: GET https://REDACTED/v1/auth/token/lookup-self\nCode: 403. Raw Message:\n\nForbidden","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:227"}
```

My manifests are below

```
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: bo01-vault
spec:
  provider:
    vault:
      server: https://REDACTED
      path: secret
      version: v2
      auth:
        tokenSecretRef:
          name: bo01-secrets-reader-token
          key: token
          namespace: argocd-system

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cpi-global-secret
  namespace: kube-system
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: bo01-vault
    kind: ClusterSecretStore
  target:
    name: cpi-global-secret
  dataFrom:
    - extract:
        key: REDACTED
```

had to rollback for now, didn't really test 0.5.5, but 0.5.4 works fine, 0.5.6 fails

**Comment by moolen** [comment]
based on @gusfcarvalho comment above i tried it with a similar configuration like yours @noroutine. 
Unfortunately i can't reproduce the issue you're having. Could you please double-check the images/resources used?

This is roughly what i did (used v0.5.6)
```
$ helm install vault hashicorp/vault \
    --set "server.dev.enabled=true" --set injector.enabled=false
$ vault secrets enable -path=kv -version=2 kv
$ vault kv put kv/foobar password=1234
```

manifests:
```yaml
apiVersion: v1
data:
  token: cm9vdA== # root
kind: Secret
metadata:
  name: vault-token
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: http://localhost:8200
      path: kv
      version: v2
      auth:
        tokenSecretRef:
          name: vault-token
          namespace: default
          key: token
---
 apiVersion: external-secrets.io/v1beta1
 kind: ExternalSecret
 metadata:
   name: vault-example1
   namespace: default
 spec:
   secretStoreRef:
     name: vault-backend
     kind: ClusterSecretStore
   target:
     name: example-sync1
   data:
   - secretKey: foobar
     remoteRef:
       key: foobar
       property: password

```

ClusterSecretStore status
```
$ k describe css vault-backend
[...]
Status:
  Conditions:
    Last Transition Time:  2022-06-02T05:50:05Z
    Message:               store validated
    Reason:                Valid
    Status:                True
    Type:                  Ready
Events:
  Type    Reason  Age                    From                  Message
  ----    ------  ----                   ----                  -------
  Normal  Valid   2m32s (x2 over 2m32s)  cluster-secret-store  store validated
```


ExternalSecret status
```
$ k describe es vault-example1
Status:
  Conditions:
    Last Transition Time:   2022-06-02T05:50:05Z
    Message:                Secret was synced
    Reason:                 SecretSynced
    Status:                 True
    Type:                   Ready
  Refresh Time:             2022-06-02T05:50:05Z
  Synced Resource Version:  1-5be03f38754b4067c411c393c79a6fbf
Events:
  Type     Reason            Age   From              Message
  ----     ------            ----  ----              -------
  Warning  UnavailableStore  3m9s  external-secrets  the desired SecretStore vault-backend is not ready
  Normal   Updated           3m9s  external-secrets  Updated Secret
```

**Comment by aaronchar** [comment]
@gusfcarvalho @moolen 
It's actually interesting.

 I have had this working multiple times yesterday and even this morning but I just re-deployed without specifying an image tag and allowing the `0.5.6` version to be installed via OLM and I am back to a failing state with the exact same error  I was previously seeing. 

 Yet it's clearly running `0.5.6`

<img width="1285" alt="image" src="https://user-images.githubusercontent.com/4359735/171719550-df0a1c3e-3342-4b33-97c8-545bde0dfd5a.png">


```yaml
spec:
      containers:
      - args:
        - --controller-class=telco-cloud
        - --concurrent=5
        image: ghcr.io/external-secrets/external-secrets:v0.5.6
        imagePullPolicy: IfNotPresent
        name: external-secrets
        ports:
        - containerPort: 8080
          name: metrics
          protocol: TCP
        resources: {}
 ```
```
{"level":"error","ts":1654197119.4901395,"logger":"controllers.ClusterSecretStore","msg":"unable to validate store","clustersecretstore":"/<redacted>","error":"could not get provider client: unable to log in to auth method: unable to log in with Kubernetes auth: Error making API request.\n\nURL: PUT https://<redacted>/v1/auth/dev_regn10_ocp2/login\nCode: 400. Errors:\n\n* missing client token","stacktrace":"github.com/external-secrets/external-secrets/pkg/controllers/secretstore.(*ClusterStoreReconciler).Reconcile\n\t/home/runner/work/external-secrets/external-secrets/pkg/controllers/secretstore/clustersecretstore_controller.go:55\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:114\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:311\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:227"}
{"level":"error","ts":1654197119.5062692,"logger":"controller.clustersecretstore","msg":"Reconciler error","reconciler group":"external-secrets.io","reconciler kind":"ClusterSecretStore","name":"<redacted>","namespace":"","error":"could not get provider client: unable to log in to auth method: unable to log in with Kubernetes auth: Error making API request.\n\nURL: PUT https://<redacted>/v1/auth/dev_regn10_ocp2/login\nCode: 400. Errors:\n\n* missing client token","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:227"}
```
It's just very very strange. I am going to re-deploy with the tags explicitly configured not that it should make a difference.
