### ISSUE TITLE
[Feature Request] - Hashicorp Vault: Active Directory

### ISSUE THREAD

**Issue by aaronchar** [external-secrets/external-secrets#1222]
**Describe the solution you'd like**
I would like to see the [Active directory engine](https://www.vaultproject.io/docs/secrets/ad) added in as a supported option. 

**What is the added value?**
My use case for this is provisioning  OpenShift secrets that contain active directory accounts, for example LDAP authentication , group syncing etc. Instead of creating a non-expiring AD account we can simply have Vault rotate the account every hour / day etc and ESO will be able to re-provision those changes to the secrets in the cluster. 

**Observations (Constraints, Context, etc):**

The AD secrets engine does **actually** work within ESO but not really through a supported mechanism . For example

```yaml
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: example
spec:
  controller: example
  provider:
    vault:
      auth:
        kubernetes:
          mountPath: kubernetes
          role: test
          serviceAccountRef:
            name: vault
            namespace: default
      path: ad
      server: <server>
      version: v1
```

and the secret spec simply makes reference to `key: ad/creds/<some key>`

This only works because the `v1` kv engine doesn't modify the URL when generating the request. So we end up with a valid request to  `https://<server>/v1/ad/creds/<some_key>`
