### ISSUE TITLE
ClusterSecretStore using Kubernetes Provider not working after upgrade from v0.5.1 to higher versions

### ISSUE THREAD

**Issue by kolorful** [external-secrets/external-secrets#1232]
After migrating external-secrets from `v0.5.1` to `v0.5.3` (tried `v0.5.6` as well), we start to see error like this: 
No change in any configs other than chart version, rolling back to `v0.5.1` fixed the issue. 

```
{
   "level":"error",
   "ts":1654209292.0269632,
   "logger":"controllers.ClusterSecretStore",
   "msg":"unable to validate store",
   "clustersecretstore":"/stuff",
   "error":"could not validate provider: client is not allowed to get secrets",
   "stacktrace":"github.com/external-secrets/external-secrets/pkg/controllers/secretstore.(*ClusterStoreReconciler).Reconcile\n\t/home/runner/work/external-secrets/external-secrets/pkg/controllers/secretstore/clustersecretstore_controller.go:55\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:114\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:311\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:227"
}
```

We are using Kubernetes cluster as our provider and here is the example yaml we use.
```
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: some-cluster-secrets
spec:
  provider:
    kubernetes:
      auth:
        token:
          bearerToken:
            key: token
            name: some-service-account-token
            namespace: xyz
      remoteNamespace: xyz
      server:
        caProvider:
          key: ca.crt
          name: some-service-account-token
          namespace: xyz
          type: Secret
        url: kubernetes.default
```

**Comment by gusfcarvalho** [comment]
As stated in the provider docs, you need to give SelfSubjectAccessReview permission to your Client!

**Comment by gusfcarvalho** [comment]
See the note here: https://external-secrets.io/v0.5.6/provider-kubernetes/

**Comment by kolorful** [comment]
huh, was it not enforced in `v0.5.1`?

**Comment by gusfcarvalho** [comment]
No, it was added afterwards. IIRC 0.5.1 we had no validation for the kubernetes provider.

**Comment by gusfcarvalho** [comment]
Or more precisely, not the validation itself, but controlling ES behavior using flood gate.

**Comment by gusfcarvalho** [comment]
Probably what you’re missing is setting get secret to your service account. See the validation error message here: https://github.com/external-secrets/external-secrets/blob/main/pkg/provider/kubernetes/kubernetes.go#L262

**Comment by kolorful** [comment]
Thanks. I currently have:

```
rules:
  - apiGroups:
      - ''
    resources:
      - secrets
    verbs:
      - get
    resourceNames:
      - xyz
 ```

I think I'll try adding `selfsubjectaccessreviews`

**Comment by kolorful** [comment]
@gusfcarvalho Adding 
```
- apiGroups:
  - authorization.k8s.io
  resources:
  - selfsubjectaccessreviews
  verbs:
  - create
```
doesn't seem to help, would you know if it is the right RBAC I should add?
