### ISSUE TITLE
ExternalSecret without target field creates a Secret and deletes it

### ISSUE THREAD

**Issue by cod-r** [external-secrets/external-secrets#1233]
Hi,

Creating a new ExternalSecret without the `target` field creates the Kubernetes secret and deletes it immediately and no errors are shown.

This is my yaml:
```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test-postgres
  namespace: test
spec:
  secretStoreRef:
    name: vault-test-backend
    kind: ClusterSecretStore
  refreshInterval: "1h"
  dataFrom:
    - extract:
        key: kv/test/test-secret
```
Using `--watch` I can see the k8s Secret being created and deleted immediately.

The workaround is to add an empty `target: {}` object like:
```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test-postgres
  namespace: test
spec:
  secretStoreRef:
    name: vault-test-backend
    kind: ClusterSecretStore
  refreshInterval: "1h"
  target: {}
  dataFrom:
    - extract:
        key: kv/test/test-secret
```

Tested with version 0.5.3 and 0.5.6
