### ISSUE TITLE
External Secrets w/templated keys are overwritten by remote keys of the same name

### ISSUE THREAD

**Issue by cnmcavoy** [external-secrets/external-secrets#124]
**Describe the solution you'd like**
External Secret resources that reference remote keys (e.g data or dataFrom) and then also define explicit template key-value pairs in the target secret are not templated. The remote keys replace the templated key contents. External Secrets can not contain templated keys that collide with remote keys, because the remote keys always win the merge.

**What is the added value?**
External Secrets can support materializing secrets with keys that contain templates with keys that exactly match the names of remote keys.

**Give us examples of the outcome**

```
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: foo-es
spec:
  data:
  - remoteRef:
      key: "projects/foo-project/conf"
      property: foo
    secretKey: foo
  refreshInterval: 4h
  secretStoreRef:
    kind: ClusterSecretStore
    name: foo-store
  target:
    name: foo-secret
    template:
      type: "Opaque"
      data:
        foo: aGVsbG8gd29ybGQhCg== ## 'hello world!'
```

I would expect a secret `foo-secret` resource with a single key, `foo` would be created, with the base64 decoded value "hello world!. Instead `foo-secret` exists, with the single key, `foo`, containing the contents of the secret from the cluster secret store. I would expect the template contents to overwrite the remote value in the final resource output.

**Observations (Constraints, Context, etc):**

This is trivial to work around when using `data` as you can rename keys, but `dataFrom` is less flexible, as it imports the contents of all the key-values under the path. Users that update their vault (or whatever backend) with new secret keys that collide with external secret templates will discover they have clobbered their templated secrets.
