### ISSUE TITLE
Example for getting value to secret from ssm parameter store

### ISSUE THREAD

**Issue by igor-sidorov** [external-secrets/external-secrets#1252]
Could you please write an example how to create ExternalSecret for ssm parameter store. 

For example, I have value that have path /my/full_path/to/value

MY EXAMPLE:
```
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-ssm-paramstore
  namespace: ns_name
spec:
  provider:
    aws:
      service: ParameterStore
      # define a specific role to limit access
      # to certain secrets
      role: arn:aws:iam::{aws_account_id}:role/{role_name}
      region: us-east-1
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  namespace: ns_name
  name: external_secret_name
spec:
  data:
  - key: /my/full_path/to/value
  target:
    name: k8s_secret_name
  secretStoreRef:
    kind: SecretStore
    name: aws-ssm-paramstore

```
