### ISSUE TITLE
External Secrets can have surprising template behavior

### ISSUE THREAD

**Issue by cnmcavoy** [external-secrets/external-secrets#126]
**Describe the solution you'd like**
External Secrets templates do not handle edge cases well. For example, if the template `{{ . | toString }}` is supplied for any key, the resulting secret resource has that key, with the value of the template, unrendered.

Other invalid templates, for example `{{ .nonexistent_key | toString }}`, produce a different result. The secret is created, and the key for the template has a value of `Error: provided key not found in secret` after base64 decoding.

**What is the added value?**
Template errors should be visible on the status of the external secret, and the logs of the controller. I saw no error with this particular edge case in any of the controller logs or status fields.

**Give us examples of the outcome**
```
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: foo-es
spec:
  data:
  - remoteRef:
      key: "projects/foo-project/conf"
      property: foo
    secretKey: foo
  refreshInterval: 4h
  secretStoreRef:
    kind: ClusterSecretStore
    name: foo-store
  target:
    name: foo-secret
    template:
      type: "Opaque"
      data:
        bar: e3sgLiB8IHRvU3RyaW5nIH19Cg== ## '{{ . | toString }}'
 ```
 
Produced the following secret:

```
apiVersion: v1
data:
  foo: Zm9vCg==
  bar: e3sgLiB8IHRvU3RyaW5nIH19Cg==
kind: Secret
metadata:
  creationTimestamp: "2021-04-28T17:17:30Z"
  name: foo-secret
  ownerReferences:
  - apiVersion: external-secrets.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: ExternalSecret
    name: test
    uid: 44246fa1-e28b-4ecc-a76e-b39212d387ec
  resourceVersion: "131974233"
  uid: 3ffa418e-3d3b-4bfc-a184-32c097207210
type: Opaque
```

**Observations (Constraints, Context, etc):**

No errors in the controller were logged. The sync status on the external secret resource was "SyncSuccess".

 I'm aware that the template `{{ .foo | toString }}` would correctly render the secret contents, but I was surprised by the behavior with this example. I would have expected garbage secret data, or an error, or anything else except exposing the template contents unrendered.
