### ISSUE TITLE
Extract Key and Certificate from Azure Key Vault

### ISSUE THREAD

**Issue by mezzofix** [external-secrets/external-secrets#1265]
**Describe the solution you'd like**
Help with extracting key and certificate from AKV.

**Observations (Constraints, Context, etc):**

Hi, I'm unable to get logic right to extract data from my certificate uploaded to Azure Key Vault. 

1. Created TLS certificate 
```
export CERT_NAME=aks-ingress-cert
openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
    -out webapp.crt \
    -keyout webapp.key \
    -subj "/CN=webapp.com/O=aks-ingress-tls"
```
2. Import certificate to AKV

`openssl pkcs12 -export -in webapp.crt -inkey webapp.key  -out webapp.pfx
`# skipped password prompt

`az keyvault certificate import --vault-name $AKV_NAME -n webapp -f webapp.pfx
`
3. I can reeturn the raw value using the following ExternalSecret
```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example-external-secret3
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: example
  target:
    name: secret-to-be-created
    creationPolicy: Owner
  data:
  - secretKey: xxx
    remoteRef:
      key: cert/newapp
```
  4. The following data is returned 
 ```
 k get secret
  secret-to-be-created   Opaque                                1      9s
```
```
k describe secret secret-to-be-created
Name:         secret-to-be-created
Namespace:    newapp
Labels:       <none>
Annotations:  reconcile.external-secrets.io/data-hash: 2b339768488afd35604631d8f986f769

Type:  Opaque

Data
====
xxx:  835 bytes
```
```
k get externalsecret
NAME                       STORE     REFRESH INTERVAL   STATUS
example-external-secret3   example   1h                 SecretSynced
```

I've tried various combinations such as

```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example-external-secret3
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: example
  target:
    name: secret-to-be-created
    creationPolicy: Owner
  data:
  - secretKey: xxx
    remoteRef:
      key: cert/newapp
  target:
    template:
      type: kubernetes.io/tls
      engineVersion: v2
      data:
        tls.crt: "{{ .xxx | pkcs12cert }}"
        tls.key: "{{ .xxx | pkcs12key }}"
```
Error:
```

Status:
  Conditions:
    Last Transition Time:  2022-06-13T15:46:12Z
    Message:               could not update Secret
    Reason:                SecretSyncedError
    Status:                False
    Type:                  Ready
Events:
  Type     Reason           Age                   From              Message
  ----     ------           ----                  ----              -------
  Warning  InvalidStoreRef  88s (x15 over 2m50s)  external-secrets  could not get ClusterSecretStore "example", ClusterSecretStore.external-secrets.io "example" not found
  Warning  UpdateFailed     5s                    external-secrets  could not apply template: could not execute template: unable to execute template at key tls.key: unable to execute template at key tls.key: template: tls.key:1:10: executing "tls.key" at <pkcs12key>: error calling pkcs12key: unable to decode pkcs12 with password: pkcs12: error reading P12 data: asn1: structure error: tags don't match (2 vs {class:0 tag:16 length:551 isCompound:true}) {optional:false explicit:false application:false private:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false} int @4
  Warning  UpdateFailed     5s                    external-secrets  could not apply template: could not execute template: unable to execute template at key tls.crt: unable to execute template at key tls.crt: template: tls.crt:1:10: executing "tls.crt" at <pkcs12cert>: error calling pkcs12cert: unable to decode pkcs12 certificate with password: pkcs12: error reading P12 data: asn1: structure error: tags don't match (2 vs {class:0 tag:16 length:551 isCompound:true}) {optional:false explicit:false application:false private:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false} int @4
```
I'm sure the syntax I'm using is not ok, but can't figure it out even when following [Extract Keys and Certificates from PKCS#12 Archive
](https://external-secrets.io/v0.5.5/guides-templating/#extract-keys-and-certificates-from-pkcs12-archive)

Could someone **please** give me a helping hand with this ?

**Comment by moolen** [comment]
hey @mezzofix i got it to work with this, could you try this out?

```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: example-secret-store
    kind: SecretStore
  target:
    template:
      type: kubernetes.io/tls
      engineVersion: v2
      data:
        tls.crt: "{{ .xxx | b64dec | pkcs12cert }}"
        tls.key: "{{ .xxx | b64dec | pkcs12key }}"

  data:
  - secretKey: xxx
    remoteRef:
      key: secret/webapp # <-- note: secret/...
```

**Comment by moolen** [comment]
Hey @alexander-rondon, when using an ExternalSecret in a helm chart you must escape the template functions!

The above example would look like this when used in a helm chart:
```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: example-secret-store
    kind: SecretStore
  target:
    template:
      type: kubernetes.io/tls
      engineVersion: v2
      data:
        tls.crt: "{{ `{{ .xxx | b64dec | pkcs12cert }}` }}"
        tls.key: "{{ `{{ .xxx | b64dec | pkcs12key }}` }}"

  data:
  - secretKey: xxx
    remoteRef:
      key: secret/webapp # <-- note: secret/...

```
There are different ways to escape it, this issue will help you: https://github.com/helm/helm/issues/2798

**Comment by alexander-rondon** [comment]
Thank you @moolen, I see Helm is not providing the functions, but the ESO.

**Comment by lenisha** [comment]
@moolen  is there a way store pfx in  AKV certificate not secret?
 
data:
  - secretKey: xxx
    remoteRef:
      key: secret/webapp # <-- note: secret/...

if it has to be secret would it be with encoding

az keyvault secret set --vault-name $AKV_NAME -n webapp -f webapp.pfx --encoding base64

**Comment by sreejithsoman-mc** [comment]
Hello Everyone,
I am still struggling. I get the below error. Could anyone helped? 
`Warning  UpdateFailed  6s (x6 over 7s)  external-secrets  could not apply template: could not execute template: unable to execute template at key tls.key: unable to execute template at key tls.key: template: tls.key:1:24: executing "tls.key" at <pkcs12key>: error calling pkcs12key: unable to decode pkcs12 with password: pkcs12: error reading P12 data: asn1: structure error: tags don't match (16 vs {class:1 tag:9 length:108 isCompound:true}) {optional:false explicit:false application:false private:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false} pfxPdu @2
  Warning  UpdateFailed  1s (x5 over 7s)  external-secrets  could not apply template: could not execute template: unable to execute template at key tls.crt: unable to execute template at key tls.crt: template: tls.crt:1:24: executing "tls.crt" at <pkcs12cert>: error calling pkcs12cert: unable to decode pkcs12 certificate with password: pkcs12: error reading P12 data: asn1: structure error: tags don't match (16 vs {class:1 tag:9 length:108 isCompound:true}) {optional:false explicit:false application:false private:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false} pfxPdu @2`
  
  `apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: 5mo6k6-az-***-net-tls
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: xx-xxxx--xxxxx-xxxxx
  target:
    name: 5mo6k6-az-xxxx-net-tls
    template:
      type: kubernetes.io/tls
      engineVersion: v2
      data:
        tls.crt: '{{ .mysecret | b64dec | pkcs12cert }}'
        tls.key: '{{ .mysecret | b64dec | pkcs12key }}'
  data:
  - secretKey: mysecret
    remoteRef:
      key: cert/5mo6k6-az-ista-net`

**Comment by gusfcarvalho** [comment]
hi @KrishnaKumar-Thulasidas! This is not related to external-secrets at all.  **You need to have secret permissions in order to download the certificate with the private key from keyvault**. This requirement is extended to external-secrets in the form of getting the `secret` endpoint, just like the azure portal does when you click to `download  PFX/PEM`

**Comment by gusfcarvalho** [comment]
you simply can't refer to the `cert` object if you don't have the appropriate permissions. this is more related to how keyvault works when storing `certificate` objects, than to how external-secrets expose it.

**Comment by gusfcarvalho** [comment]
Please note that when you generate / import a certificate, a `secret` and a `key` objects will be created bound to that certificate. They won't be visible in azure portal as they are managed by the certificate object.

**Comment by KrishnaKumar-Thulasidas** [comment]
@gusfcarvalho , 

Thanks for the reply, 

What we were trying to do is to create a  **kubernetes.io/tls** certificate using external-secrets. 

We had imported the certificate to Azure keyvault as a certificate and as a secret. 

Currently, we are creating the certificate using 

```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ext-test-certificate
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: test-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: test-certificate-secret
    template:
      type: kubernetes.io/tls
      data:
        tls.crt: "{{ .mysecret | pkcs12cert | pemCertificate }}"
        tls.key: "{{ .mysecret | pkcs12key | pemPrivateKey }}"

  data:
  - secretKey: mysecret
    remoteRef:
      key: secret/test-certificate
```
This is working as expected but instead of this we need to use 

```
  - secretKey: mysecret
    remoteRef:
      **key: cert/test-certificate**
```

Is that possible?
