### ISSUE TITLE
[question] about certificate controller and wehbook

### ISSUE THREAD

**Issue by yongzhang** [external-secrets/external-secrets#1270]
Hi, team

I'm trying to migrate from [kubernetes-external-secrets](https://github.com/external-secrets/kubernetes-external-secrets), when I looked into the docs and kubernetes manifests, the new one looks much more complex.

I'm not quite sure if certificate controller and webhook component should be enabled, I just want the service to pull secrets from AWS Secrets Manager and create relevant kubernetes secrets as simple as what `kubernetes-external-secrets` did.

**Comment by gusfcarvalho** [comment]
Hi @yongzhang! Please see https://github.com/external-secrets/external-secrets/issues/885. It explains why you need both.


Im not sure if Im following you, though. CertController and Webhook are not managed by your team at all (there is no interaction with secrets). From an user perspective, the only change is regarding the SecretStore concept, which has been here since forever.

Só, to answer your question: you need them if you plan to do “a simple install” like you’re mentioning.

**Comment by yongzhang** [comment]
> Hi @yongzhang! Please see #885. It explains why you need both.
> 
> Im not sure if Im following you, though. CertController and Webhook are not managed by your team at all (there is no interaction with secrets). From an user perspective, the only change is regarding the SecretStore concept, which has been here since forever.
> 
> So, to answer your question: you need them if you plan to do “a simple install” like you’re mentioning.

Thanks for the explanation, this is useful. So if I understand it correctly, in AWS EKS, IRSA should only be added to deployment `external-secrets` right (with manifest below)?

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-secrets
  namespace: "default"
  labels:
    helm.sh/chart: external-secrets-0.5.6
    app.kubernetes.io/name: kube-system
    app.kubernetes.io/instance: external-secrets
    app.kubernetes.io/version: "v0.5.6"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-system
      app.kubernetes.io/instance: external-secrets
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kube-system
        app.kubernetes.io/instance: external-secrets
    spec:
      serviceAccountName: external-secrets
      containers:
        - name: external-secrets
          image: "ghcr.io/external-secrets/external-secrets:v0.5.6"
          imagePullPolicy: IfNotPresent
          args:
          - --concurrent=1
          ports:
            - containerPort: 8080
              protocol: TCP
              name: metrics
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
```
