### ISSUE TITLE
Hashicorp Vault: SecretStore can use a ConfigMap from another namespace but not a Secret

### ISSUE THREAD

**Issue by Da-Juan** [external-secrets/external-secrets#1280]
**Describe the solution you'd like**
On a cluster with multiple tenants, I'm currently setting up ESO as a service.
I would like to provide some common resources in a specific namespace and one of these resources would be our Vault CA certificate.

When I create a `SecretStore` using a Secret as caProvider ESO tries to fetch it in the same namespace as my SecretStore, it doesn't look in the configured namespace due to [this condition](https://github.com/external-secrets/external-secrets/blob/15d39cda948a5ba88f8e383cc48aca060aecf483/pkg/provider/vault/vault.go#L951) (I think).
I get the following message: `Warning  InvalidProviderConfig  secret-store  cannot set Vault CA certificate: cannot get Kubernetes secret "ca-example.org": secrets "ca-example.org" not found`
If I use a ConfigMap I don't have any problem.

[This comment](https://github.com/external-secrets/external-secrets/blob/main/docs/snippets/full-cluster-secret-store.yaml#L58) in the doc is quite confusing too, why using a namespace would be irrelevant for a SecretStore?

Expected behavior : using Secret or ConfigMap as caProvider should work the same way.

**Observations (Constraints, Context, etc):**

Kubernetes version: 1.22.2
ESO version: 0.5.6

This manifest doesn't work:
```yaml
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: my-ns
spec:
  provider:
    vault:
      server: "https://vault.example.org/"
      path: "secrets"
      version: "v2"
      caProvider:
        type: Secret
        name: ca-example.org
        key: ca.crt
        namespace: common-ns
    [...]
```

This one works:
```yaml
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: my-ns
spec:
  provider:
    vault:
      server: "https://vault.example.org/"
      path: "secrets"
      version: "v2"
      caProvider:
        type: ConfigMap
        name: ca-example.org
        key: ca.crt
        namespace: common-ns
    [...]
```
