### ISSUE TITLE
Trying to set a non default refreshInterval fails validation

### ISSUE THREAD

**Issue by ArikShifer** [external-secrets/external-secrets#1301]
**Describe the solution you'd like**
Describe the end goal of this proposal. What is this new functionality or the new behaviour (or what problem does it fix)? 

I'm trying to set a 2 minutes refresh interval for pulling a secret from IBM Cloud Secrets Manager 
It fails validation:

```
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: ibmcloud-secrets-manager-example
spec:
  refreshInterval: 2m
  provider:
    ibm:
      serviceUrl: <endpoint_url>
      auth:
        secretRef:
          secretApiKeySecretRef:
            name: secret-api-key
            key: apikey
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ibmcloud-secrets-manager-example
spec:
  secretStoreRef:
    name: ibmcloud-secrets-manager-example
    kind: SecretStore
  target:
    name: ibmcloud-secrets-manager-example
  data:
  - secretKey: username
    remoteRef:
      property: username
      key: username_password/<SECRET_ID>
  - secretKey: password
    remoteRef:
      property: password
      key: username_password/<SECRET_ID>
```

**Give us examples of the outcome**
```
kubectl apply -f external-secrets-example.yml                 
externalsecret.external-secrets.io/ibmcloud-secrets-manager-example configured
The SecretStore "ibmcloud-secrets-manager-example" is invalid: spec.refreshInterval: Invalid value: "number": spec.refreshInterval in body must be of type integer: "number"
```

**Observations (Constraints, Context, etc):**

Give here all extra information that could be interesting. Such as Golang version and Kubernetes version if you are reporting a bug/problem. You can also foresee technical constrains like "this could only be implementing using this specific technology or approach, because of this and that".

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:41:58Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.8+f34b40c", GitCommit:"496de02aacae03fbbd977e802b08b71ca76f390a", GitTreeState:"clean", BuildDate:"2022-05-18T18:53:42Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
```

```
oc version
Client Version: v4.2.0-alpha.0-1420-gf1f09a3
Kubernetes Version: v1.22.8+f34b40c
```
