### ISSUE TITLE
Webhook certificate error on AWS EKS with Fargate

### ISSUE THREAD

**Issue by Andreashej** [external-secrets/external-secrets#1306]
I am trying to deploy external-secrets on AWS EKS using Fargate only. All seems pods and services start up as expected, but when trying to deploy a ClusterSecretStore, it fails with the following error:
``Error from server (InternalError): error when creating "deployment/external-secret.yaml": Internal error occurred: failed calling webhook "validate.externalsecret.external-secrets.io": Post "https://external-secrets-webhook.external-secrets.svc:443/validate-external-secrets-io-v1beta1-externalsecret?timeout=5s": x509: certificate is valid for **##fargate-node-dns##**, not external-secrets-webhook.external-secrets.svc``

My ClusterSecretStore has the following manifest:
```
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: secretstore
  namespace: external-secrets
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-west-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: awssm-secret
            key: access-key
          secretAccessKeySecretRef:
            name: awssm-secret
            key: secret-access-key
```

What could be the cause of this issue? Is there a configuration option somewhere to override the DNS-name of the certificate?
