### ISSUE TITLE
feature: set secret prefix per secretstore

### ISSUE THREAD

**Issue by githubcdr** [external-secrets/external-secrets#1308]
**Describe the solution you'd like**

I like to create a prefix per environment/secretstore, so that I can refer to a secret without having to worry about the path of the secret.

**What is the added value?**

I maintain various environments, currently patching using kustomize per env, this becomes cluttered very quick.

```
- target:
    kind: ExternalSecret
    name: podinfo-service
  patch: |-
    - op: replace
      path: /spec/dataFrom/0/extract/key
      value: io-whitelabel/acceptance/podinfo-service
```

Instead I would like to be able to just use the secret name and let secrectstore know the full path.

```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: podinfo-service
spec:
  dataFrom:
  - extract:
      key: podinfo-service (where the full path is io-whitelabel/testing/podinf-service)
```

If external secret operator would support a prefix per secretstore I could just refer to a secret by it's name and not the full secret's path.

**Comment by gusfcarvalho** [comment]
Hi @githubcdr ! What is the provider that you’re using?

**Comment by gusfcarvalho** [comment]
For instance:
```
    vault:
      server: "http://my.vault.server:8200"
      path: "secret/data/path/common"
      version: "v2"
---
```
will use the v2 `secret/path/common/` prefix

**Comment by gusfcarvalho** [comment]
The data part comes from vault kv spec. Glad that it worked out! 😁

**Comment by bauerjs1** [comment]
Thanks for this hint, that was exactly what I was trying to achieve, as well.

I am using KV engine v2 in Vault, but to make this work, I need to "fool" the SecretStore to use v1, because otherwise it could not determine where to put the `/data` segment in the path and would always append that.

Then in turn, I end up with Secrets that contain fields `metadata` and `data`, where the latter wraps the actual secret fields, so I have to extract that in the ExternalSecret as another workaround like so:
```yaml
kind: ExternalSecret
# ...
spec:
  dataFrom:
  - extract:
      key: relative/path/to/secret
      property: data
```

While this works fine, it seems kinda hacky to me and is a little confusing to developers who are making use of our SecretStores. Is there anything planned to support this natively? E.g. there could be an additional field in the SecretStore spec, such as `subPath`:
```yaml
kind: SecretStore
# ...
spec:
  provider:
    vault:
      server: https://vault.example.org
      # mount path of the secret store
      path: k8s
      # narrow down this SecretStore to a specific sub-path within the KV engine
      subPath: cluster1/dev-namespace
      version: v2
      auth:
        # ...
```
which would then be resolved to the API path `k8s/data/cluster1/dev-namespace`
