### ISSUE TITLE
ExternalSecret with Vault by Kubernetes return Secret not found

### ISSUE THREAD

**Issue by gawsoftpl** [external-secrets/external-secrets#1332]
When I create ExternalSecret **I received error: secret not found**

But secret from vault secret agent are inject without any errors 

My configuration:
1. Vault with valid SSL
2. Auth by kubernetes  (https://external-secrets.io/v0.5.7/provider-hashicorp-vault/#kubernetes-authentication)

**THIS WORKING:**
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: devwebapp-with-annotations
  labels:
    app: devwebapp-with-annotations
  annotations:
    vault.hashicorp.com/agent-inject: 'true'
    vault.hashicorp.com/role: 'webshotapi'
    vault.hashicorp.com/agent-inject-secret-credentials.txt: 'test/dashboard'
spec:
  containers:
    - name: app
      image: burtlo/devwebapp-ruby:k8s
```

**BELOW NOT WORKING**
```
external-secrets k get sa                                             
NAME                   SECRETS   AGE
default                1         26h
mycluster-sidecar-sa   1         20h
vault                  1         68m
vault-agent-injector   1         68m
```

```
 external-secrets k get secrets                                        
NAME                               TYPE                                  DATA   AGE
default-token-rzrkz                kubernetes.io/service-account-token   3      26h
letsencrypt-production             Opaque                                1      10h
letsencrypt-staging                Opaque                                1      10h
mycluster-backup                   Opaque                                2      20h
mycluster-privsecrets              Opaque                                2      20h
mycluster-router                   Opaque                                2      20h
mycluster-sidecar-sa-token-fmfnk   kubernetes.io/service-account-token   3      20h
mypwds                             Opaque                                3      20h
sh.helm.release.v1.vault.v1        helm.sh/release.v1                    1      69m
vault-agent-injector-token-9tl8v   kubernetes.io/service-account-token   3      69m
vault-token-jrzvq                  kubernetes.io/service-account-token   3      69m
```

```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-example
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: example-sync
  data:
  - secretKey: foobar
    remoteRef:
      key: test/dashboard
  

```
```yaml
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "https://<my-endpoint>:8200"
      path: "secret"
      version: "v2"
      auth:
        # Authenticate against Vault using a Kubernetes ServiceAccount
        # token stored in a Secret.
        # https://www.vaultproject.io/docs/auth/kubernetes
        kubernetes:
          # Path where the Kubernetes authentication backend is mounted in Vault
          mountPath: "kubernetes"
          # A required field containing the Vault Role to assume.
          role: "webshotapi"
          # Optional service account field containing the name
          # of a kubernetes ServiceAccount
          serviceAccountRef:
            name: "default"
```

```
k describe externalsecret vault-example
Status:
  Conditions:
    Last Transition Time:  2022-07-06T23:11:50Z
    Message:               could not get secret data from provider
    Reason:                SecretSyncedError
    Status:                False
    Type:                  Ready
Events:
  Type     Reason        Age                 From              Message
  ----     ------        ----                ----              -------
  Warning  UpdateFailed  23s (x5 over 109s)  external-secrets  secret not found
```

**Comment by gawsoftpl** [comment]
**I found SOLUTION!**

I think that problem is with vault kv api v1 and v2. 

In SecretStore you have to add 
blank path attribute 
```yaml
    vault:
      server: "https://<endpoint>:8200"
      path: "" # FIX HERE
      version: "v2"
```

and to remoteref full path: "test/data/dashboard"
```yaml
  - secretKey: foobar
    remoteRef:
      key: test/data/dashboard # FIX HERE
```

After that secrets are synced

**Full example**
```yaml
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "https://<endpoint>:8200"
      path: "" # FIX HERE
      version: "v2"
      auth:
        # Authenticate against Vault using a Kubernetes ServiceAccount
        # token stored in a Secret.
        # https://www.vaultproject.io/docs/auth/kubernetes
        kubernetes:
          # Path where the Kubernetes authentication backend is mounted in Vault
          mountPath: "kubernetes"
          # A required field containing the Vault Role to assume.
          role: "<my-role>"
          # Optional service account field containing the name
          # of a kubernetes ServiceAccount
          serviceAccountRef:
            name: "default"

```

```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-example
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: example-sync
  data:
  - secretKey: foobar
    remoteRef:
      key: test/data/dashboard # FIX HERE
```

**Comment by gusfcarvalho** [comment]
in your case, your secrets engine is called `test`. Another way to do it is by having the following secretstore:

```
spec:
  provider:
    vault:
      path: "test" # FIX HERE
      version: "v2"
 ```
     
     and then refer your secrets in your external-secrets as this:
     
  ```
    data:
  - secretKey: foobar
    remoteRef:
      key: dashboard # FIX HERE
  ```
