### ISSUE TITLE
ClusterExternalSecret doesn't work

### ISSUE THREAD

**Issue by Skyere** [external-secrets/external-secrets#1337]
I'm trying to create ClusterExternalSecret but get the error.
(Just ExternalSecret works)
```Status:
  Conditions:
    Message:  one or more namespaces failed
    Status:   True
    Type:     NotReady
    Status:   True
    Type:     Ready
  Failed Namespaces:
    Namespace:  test
    Reason:     could not create or update ExternalSecret
  Provisioned Namespaces:
    test
```
   
My manifest
```yml
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: "hello-world"
spec:
  externalSecretName: "hello-world-es"
  namespaceSelector:
    matchLabels: 
      kubernetes.io/metadata.name: test

  refreshTime: "1m"

  externalSecretSpec:
    secretStoreRef:
      name: cluster-secret-store
      kind: ClusterSecretStore

    data:
    - secretKey: AZURE-CONTAINER-NAME
      remoteRef:
        key: AZURE-CONTAINER-NAME
```

Thank in advance)
