### ISSUE TITLE
Cluster scoped ExternalSecret for creating secrets in multiple namespaces

### ISSUE THREAD

**Issue by gokulkrishnank** [external-secrets/external-secrets#134]
**Describe the solution you'd like**

Imagine a cluster with 50+ or even more namespaces where we have to create a secret(eg. image pull secret ) using ExternalSecret. We will have to create **same**  ExternalSecret in each namespaces. Currently we have 50+ external secrets for the same secret. 

Adding a **cluster scoped externalsecret** with a field `spec.namespaces` which will accept a list of namespaces will solve this type of scenarios. One ExternalSecret create secret in all the listed namespaces. 

**What is the added value?**
This will eliminate the need of creating ExternalSecrets in all namespaces for same secret. 

**Give us examples of the outcome**

Example of **ClusterExternalSecret**
```yaml
apiVersion: kubernetes-client.io/v1
kind: ClusterExternalSecret
metadata:
  name: docker-registry-internal
spec:
  backendType: secretsManager
  data:
  - key: arn:aws:secretsmanager:eu-central-1:75XXXXXXXX61:secret:secrets/nonprod-eu/docker-secret-internal
    name: .dockerconfigjson
  template:
    type: kubernetes.io/dockerconfigjson
  namespaces:
  - sandbox-app1
  - sandbox-app2
  - sandbox-app3
  - integration
  - demo
```

**Comment by moolen** [comment]
Yes, that's a good suggestion! I would favor label matches rather than having explicit namespace binding and also have a way to extend the namespace selection similar to [NetworkPolicy](https://kubernetes.io/docs/concepts/services-networking/network-policies/#networkpolicy-resource) (e.g. with `matchExpressions`).

```yaml
spec:
  ...
  namespaceSelector:
  - matchLabels:
      project: frontend

```
