### ISSUE TITLE
decoding strategy  is not supported - SecretSyncedError after upgrade to v0.5.8

### ISSUE THREAD

**Issue by mycrEEpy** [external-secrets/external-secrets#1354]
**Describe the solution you'd like**
After upgrading to v0.5.8, secrets which have been created before (for example with v0.5.6) will have SecretSyncedErrors:

```
Warning  UpdateFailed  8m2s (x280 over 148m)  external-secrets  could not apply decoding strategy to spec.dataFrom[0[]: failure decoding key test: decoding strategy  is not supported
```

Manifest:

```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: smoke-test-secret
  namespace: example
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secrets-manager
    kind: ClusterSecretStore
  target:
    name: smoke-test-secret-eso
  dataFrom:
    - extract:
        key: smoke-test-secret
```

Secret in AWS Secrets Manager:

```json
{"test":"example-1"}
```

**What is the added value?**
Decoding strategy should be automatically set to None for already existing secrets. In this case it's currently unset and therefore an empty string.

**Observations (Constraints, Context, etc):**

Kubernetes: v1.22.9-eks-a64ea69
ESO: v0.5.8
