### ISSUE TITLE
Unable to extract key and certificate from PKCS#12 certificate from Azure Key Vault

### ISSUE THREAD

**Issue by carlosbustillordguez** [external-secrets/external-secrets#1358]
I am facing issues when I try to extract the key and certificate from PKCS#12 certificate from Azure Key Vault. I have followed the steps in [Extract Keys and Certificates from PKCS#12 Archive](https://external-secrets.io/v0.5.8/guides-templating/#extract-keys-and-certificates-from-pkcs12-archive). 

When I use the following manifest:

```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kv-certs-dev
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: kv-certs-dev

  target:
    template:
      type: kubernetes.io/tls
      engineVersion: v2
      data:
        tls.crt: "{{ .wildcard | pkcs12cert }}"
        tls.key: "{{ .wildcard | pkcs12key }}"

  data:
  - secretKey: wildcard
    remoteRef:
      # type/name of certificate in the Azure KV
      key: cert/Wildcard
```

I get from the controller Pod:

```json
{"level":"error","ts":1657817762.8494573,"logger":"controller.externalsecret","msg":"Reconciler error","reconciler group":"external-secrets.io","reconciler kind":"ExternalSecret","name":"kv-certs-dev","namespace":"ingress-nginx","error":"could not apply template: could not execute template: unable to execute template at key tls.crt: unable to execute template at key tls.crt: template: tls.crt:1:20: executing \"tls.crt\" at <pkcs12cert>: error calling pkcs12cert: unable to decode pkcs12 certificate with password: pkcs12: error reading P12 data: asn1: structure error: tags don't match (2 vs {class:0 tag:16 length:1615 isCompound:true}) {optional:false explicit:false application:false private:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false} int @4","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:227"}
```

But if I add the function to unlock the certificate:

```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kv-certs-dev
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: kv-certs-dev

  target:
    template:
      type: kubernetes.io/tls
      engineVersion: v2
      data:
        # if needed unlock the pkcs12 with the password
        tls.crt: '{{ .wildcard | pkcs12certPass "secret2022" }}'
        tls.key: '{{ .wildcard | pkcs12keyPass "secret2022" }}'

  data:
  - secretKey: wildcard
    remoteRef:
      # type/name of certificate in the Azure KV
      key: cert/Wildcard
``` 

I get from the controller Pod:

```json
{"level":"error","ts":1657822034.8464136,"logger":"controller.externalsecret","msg":"Reconciler error","reconciler group":"external-secrets.io","reconciler kind":"ExternalSecret","name":"kv-certs-dev","namespace":"ingress-nginx","error":"could not apply template: could not execute template: unable to execute template at key tls.crt: unable to execute template at key tls.crt: template: tls.crt:1:20: executing \"tls.crt\" at <pkcs12certPass \"secret2022\">: error calling pkcs12certPass: unable to decode pkcs12 certificate with password: pkcs12: error reading P12 data: asn1: structure error: tags don't match (2 vs {class:0 tag:16 length:511 isCompound:true}) {optional:false explicit:false application:false private:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false} int @4","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:227"}
```

Could I missing something? 

From the [Azure Key Vault documentation](https://docs.microsoft.com/en-us/azure/key-vault/certificates/how-to-export-certificate?tabs=azure-cli#export-stored-certificates) we can see:

> Only require a certificate password when you import the certificate in the key vault. Key Vault doesn't save the associated password. When you export the certificate, the password is blank.

Can we use a similar approach to get the certificate and key from a PKCS#12 certificate on Azure Key Vault?

As an interesting point when I use the following manifest:

```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kv-certs-dev
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: kv-certs-dev

  target:
    name: raw-cert
    creationPolicy: Owner

  data:
  - secretKey: raw
    remoteRef:
      key: cert/Wildcard
```

The `raw-cert` secret (`Opaque` type) is created with the RAW PKCS#12 certificate, which is expected but I would like to get the certificate in a secret of type `kubernetes.io/tls`.

**Comment by gusfcarvalho** [comment]
Hi @carlosbustillordguez ! This is related to how Keyvault works. In order to get the key of a certificate you need to get the information from its `secret` path (not `cert`). Im not 100% sure if you would need to specify a password as well, but this manifest should be the working one (try with or without passwords):

```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kv-certs-dev
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: kv-certs-dev

  target:
    template:
      type: kubernetes.io/tls
      engineVersion: v2
      data:
        tls.crt: '{{ .wildcard | pkcs12cert "secret2022" }}'
        tls.key: '{{ .wildcard | pkcs12key  "secret2022" }}'

  data:
  - secretKey: wildcard
    remoteRef:
      # type/name of certificate in the Azure KV
      key: secret/Wildcard  # AZ Keyvault ways of working
 ```

**Comment by carlosbustillordguez** [comment]
Hi @gusfcarvalho! Thank you for your reply. I followed your instructions (with and without password), but I am getting the same error:

```json
{"level":"error","ts":1658050605.4065244,"logger":"controller.externalsecret","msg":"Reconciler error","reconciler group":"external-secrets.io","reconciler kind":"ExternalSecret","name":"kv-certs-dev","namespace":"default","error":"could not apply template: could not execute template: unable to execute template at key tls.crt: unable to execute template at key tls.crt: template: tls.crt:1:15: executing \"tls.crt\" at <pkcs12certPass \"secret2022\">: error calling pkcs12certPass: unable to decode pkcs12 certificate with password: pkcs12: error reading P12 data: asn1: structure error: tags don't match (16 vs {class:1 tag:13 length:73 isCompound:false}) {optional:false explicit:false application:false private:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false} pfxPdu @2","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:227"}
```

I created a self-signed certificate in Azure Key Vault (this does not need a password) to see if it makes a difference, but I got the same error:

```json
{"level":"error","ts":1658050909.5778883,"logger":"controller.externalsecret","msg":"Reconciler error","reconciler group":"external-secrets.io","reconciler kind":"ExternalSecret","name":"kv-certs-dev","namespace":"default","error":"could not apply template: could not execute template: unable to execute template at key tls.crt: unable to execute template at key tls.crt: template: tls.crt:1:15: executing \"tls.crt\" at <pkcs12cert>: error calling pkcs12cert: unable to decode pkcs12 certificate with password: pkcs12: error reading P12 data: asn1: structure error: tags don't match (16 vs {class:1 tag:13 length:73 isCompound:false}) {optional:false explicit:false application:false private:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false} pfxPdu @2","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:227"}
```

**Comment by moolen** [comment]
Maybe try this: https://github.com/external-secrets/external-secrets/issues/1265#issuecomment-1155622342

It's weird how AZKV stores certificate containers :shrug:

**Comment by carlosbustillordguez** [comment]
Hello @moolen!! Thank you for your reply Now is working!! Which did the trick was decoding the key/cert before getting it.

I used the following manifest (following your hint and from @gusfcarvalho) to sync the PKSC#12 certificate in Azure Key Vault:

```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-dev
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: certs-aks-test-2022
  target:
    template:
      type: kubernetes.io/tls
      engineVersion: v2
      data:
        tls.crt: "{{ `{{ .mycert| b64dec | pkcs12cert }}` }}"
        tls.key: "{{ `{{ .mycert | b64dec | pkcs12key }}` }}"
  data:
  - secretKey: mycert
    remoteRef:
      # type/name of certificate in the Azure KV
      key: secret/mycert
```

> It's weird how AZKV stores certificate containers 🤷
Totally agree with you... :)

Would be nice to add a clear example to the documentation, for instance [here](https://external-secrets.io/v0.5.8/provider-azure-key-vault/#creating-external-secret) or [here](https://external-secrets.io/v0.5.8/guides-templating/#extract-keys-and-certificates-from-pkcs12-archive). I can do that, let me know your thoughts and the right place to add it.
