### ISSUE TITLE
Merge template data

### ISSUE THREAD

**Issue by mosheavni** [external-secrets/external-secrets#1362]
**Describe the solution you'd like**
On previous version of external-secrets, when a template is defined, it would merge the template with the secret keys.
For example, I'm using external-secrets to create my argocd secret:
```yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  labels:
    argocd.argoproj.io/instance: argocd
  name: repo-k8s-conf
  namespace: argocd
spec:
  backendType: systemManager
  data:
  - key: /prod/devops/github/api_token
    name: password
  - key: /prod/devops/github/api_user
    name: username
  template:
    metadata:
      annotations:
        managed-by: argocd.argoproj.io
      labels:
        argocd.argoproj.io/secret-type: repository
    stringData:
      type: git
      url: https://github.com/bla/k8s-conf.git
```

This results this secret:

```yaml
apiVersion: v1
data:
  password: base64=======
  type: Z2l0
  url: base64=======
  username: base64=======
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  name: repo-k8s-conf
  namespace: argocd
type: Opaque
```

notice how `type` and `url` defined in the template are merged with `username` and `password` which are the secret keys.
Is there a way to achieve the same on this external-secrets without hard-coding the `username` and `password` to the template like so?:
```yaml
password: '{{ .password }}'
username: '{{ .username }}'
```

Because I may have 30 secret keys and only 2 keys I wanna keep in plain text

**What is the added value?**
Match the behaviour of old external-secrets

**Give us examples of the outcome**
I would like to define something like this:

```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
...
spec:
  ...
  target:
    template:
      strategy: merge # <-- This is a new suggested field
      data:
        # plaintext keys and values here #
  data:
    # secrets here #
```
Notice the `strategy: merge` that hopefully tells the controller to not just take the template as is, but to merge it to the secrets defined in `spec.data`

**Comment by vikas027** [comment]
I have too stumbled on the exact use case, my workaround for now is to store the extra fields too in secrets.

**Comment by kristinWalker1991** [comment]
1. https://github.com/external-secrets/external-secrets/issues/1362#issue-1307057829

**Comment by EvertonSA** [comment]
this is the best feature, will unlock output from helm dependencies can be injected into externalsecrets without having to create new secret

**Comment by kalihman** [comment]
How is this feature implementation going on? This is an important feature that is missing in external secrets operator. Can I contribute if I am allowed?

**Comment by gusfcarvalho** [comment]
I don't think we have anyone working on it (that I'm aware of :D) I will assign it to you @kalihman then :) If you need any help, please let one of me, @moolen or @knelasevero know and we can help you out :)

**Comment by kalihman** [comment]
Any suggestion for the name and type of template strategy? Seems 'merge' is good, but what should I name the current default behavior(requires full template description)? @mosheavni

**Comment by mosheavni** [comment]
> 
```
strategy: template
```
to templatize the entire created resource

```
strategy: merge
```

to merge

**Comment by PeteMac88** [comment]
Any news here? I have a similar use case where I want to use a template to combine multiple values from the external provider and additionally want to have the single values in the resulting secret

```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret
spec:
  secretStoreRef:
    name: secret-store
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: external-provider-key
  target:
    template:
      data:
        dsn: "postgres://\
          {{ .dbuser | urlquery }}\
          :\
          {{ .dbpassword | urlquery }}\
          @\
          {{ .dbhost }}\
          :\
          {{ .dbport }}\
          /\
          {{ .dbname }}"
```

The secret in the external provider includes additionally the fields `cookieSecret` and many others so I want these in the secret to:

```
apiVersion: v1
data:
  dsn: **********
  dbhost:  ***********
  dbname: ***********
  dbpassword: ***********
  dbport: ***********
  dbuser: ***********
  cookieSecret: ***********
  ......
kind: Secret
```
With the old external-secrets implementation this was possible. Can anyone help here or is this not implemented yet?

**Comment by moolen** [comment]
This isn't implemented yet. 

My 5ct on the strategy/naming question: i guess `strategy=Merge` merges the template with the data. With `strategy=Override` (which is the default) the template will take precedence over the the data from `.spec.data` and `.spec.dataFrom`

**Comment by gusfcarvalho** [comment]
hey @kalihman ! are you still working on this? I'm starting to work on a templating series of issues, and would like to take that as well, if it's not implemented yet

**Comment by PeteMac88** [comment]
@moolen Any update here?

**Comment by moolen** [comment]
Hey! I'm not aware of any. Free for grabs unless @gusfcarvalho has something

**Comment by prahaladramji** [comment]
currently I'm using a very ugly workaround which does the job if only dealing with a json string object in the secret. This works well, keep in mind i'm using the template function defined by this operator. 

> The main and annoying issue with this approach is that, large numbers get converted to scientific notation,
> `githubAppInstallationID: 1.2345678e+0` when rendered into the secret. It's fine if we define it as string. Not all template functions seem to work.

The [default go template behaviour](https://go.dev/play/p/MReMklvNtGu) doesn't work either `{{ index . "github-app" "githubAppInstallationID" }}`

* the secret stored in the key `argo/github-app`
```json
{
  "githubAppID": 123456,
  "githubAppInstallationID": 12345678,
  "githubAppPrivateKey": "-----BEGIN RSA PRIVATE KEY-----\nMIIEogI...A=\n-----END RSA PRIVATE KEY-----"
}
```

* External secret manifest
```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  labels:
    name: argocd-github-app-test
  name: argocd-github-app-test
  namespace: argocd
spec:
  data:
    - remoteRef:
        key: argo/github-app
      secretKey: github-app
  secretStoreRef:
    kind: SecretStore
    name: argo
  target:
    name: argocd-github-app-test
    template:
      data:
        githubAppID: '{{ (index . "github-app" | fromYaml ).githubAppID }}'
        githubAppInstallationID: '{{ (index . "github-app" | fromYaml ).githubAppInstallationID }}'
        githubAppPrivateKey: '{{ (index . "github-app" | fromYaml ).githubAppPrivateKey }}'
        type: git
        url: https://github.com/test
      engineVersion: v2
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repo-creds
```
