### ISSUE TITLE
[Hashicorp] Error: Secret not found

### ISSUE THREAD

**Issue by dacamposol** [external-secrets/external-secrets#1379]
## Context

I'm having issues at the time of retrieving Secrets from Hashicorp Vault, even though all the configuration seems correct.

### External Secrets

Installed by Helm

```yaml
dependencies:
- name: external-secrets
  repository: https://charts.external-secrets.io/
  version: 0.5.8
digest: sha256:fdc8ca43cea816ce3c0af69d40e3ec55f18392fe2e6384e4120049ec45705b4d
generated: "2022-07-22T09:25:58.168767+02:00"
```

### Vault

- [Vault 1.9.7+ent](https://www.github.com/hashicorp/vault/blob/main/CHANGELOG.md#197)

#### Policies

**d2eu1**
```hcl
path "common/data/*" {
    capabilities = ["read", "list"]
}
path "d2eu1/data/*" {
    capabilities = ["create", "update", "read", "list"]
}
```

**default**
```hcl
path "auth/token/lookup-self" {
    capabilities = ["read"]
}
path "auth/token/renew-self" {
    capabilities = ["update"]
}
path "auth/token/revoke-self" {
    capabilities = ["update"]
}
```

#### Kubernetes Auth

| Mount Path | Role | Policies |
| --- | --- | --- |
| d2eu1 | sa-role | default, d2eu1|

#### Secret Data

| Namespace | KV Engine | Secret Name | Keys |
| --- | --- | --- | --- |
| demo/clusters | d2eu1 | artifactory | user, password |
 
#### ClusterSecretStore

```yaml
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: cluster-store
spec:
  provider:
    vault:
      auth:
        kubernetes:
          mountPath: d2eu1
          role: sa-role
      namespace: demo/clusters
      path: d2eu1
      server: https://vault.tools.sap
      version: v2
status:
  conditions:
  - lastTransitionTime: "2022-07-22T14:37:18Z"
    message: store validated
    reason: Valid
    status: "True"
    type: Ready
```

#### ExternalSecret

```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dacamposol-demo
  namespace: secrets-system
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: artifactory
    secretKey: credentials
  refreshInterval: 15s
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: dacamposol-demo-secret
status:
  conditions:
  - lastTransitionTime: "2022-07-22T15:20:14Z"
    message: could not get provider client
    reason: SecretSyncedError
    status: "False"
    type: Ready
```

#### Event

```yaml
  apiVersion: v1
  count: 29
  eventTime: null
  firstTimestamp: "2022-07-22T15:20:14Z"
  involvedObject:
    apiVersion: external-secrets.io/v1beta1
    kind: ExternalSecret
    name: dacamposol-demo
    namespace: secrets-system
    resourceVersion: "64700981"
    uid: 6db49216-5157-428e-ad87-8908e4f60e60
  kind: Event
  lastTimestamp: "2022-07-22T15:35:29Z"
  message: secret not found
  metadata:
    creationTimestamp: "2022-07-22T15:20:14Z"
    name: dacamposol-demo.17042fe2d7cdbef6
    namespace: secrets-system
    resourceVersion: "1084979"
    uid: 933bc15f-1faf-45f2-9b4b-35c59828636a
  reason: UpdateFailed
  reportingComponent: ""
  reportingInstance: ""
  source:
    component: external-secrets
  type: Warning
```
