### ISSUE TITLE
Issue with storing plain text in a secret, was possible with the deprecated external-secrets

### ISSUE THREAD

**Issue by lrobles-iterable** [external-secrets/external-secrets#1388]
**Describe the solution you'd like**
Describe the end goal of this proposal. What is this new functionality or the new behavior (or what problem does it fix)? 

In the (now deprecated) version of external secrets, it was possible to store plain text as a value in a secret alongside secrets pulled from another source

example code from previous version of external-secrets:

```
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: my_secret
  namespace: some_namespace
spec:
  backendType: vault
  data:
    - key: kv-v2/data/some/path/to/a/secret
      name: api-key
      property: api-key
    - key: kv-v2/data/some/path/to/a/secret
      name: app-key
      property: app-key
  template:
    metadata:
      namespace: some_namespace
    stringData:
      address: https://api.some_plain_text.com
```
I cannot find an example in the docs for how to achieve this similar feature
