### ISSUE TITLE
malformed json indentation when using multiline string templating 

### ISSUE THREAD

**Issue by dllegru** [external-secrets/external-secrets#1402]
**Describe the solution you'd like**
Retrieving an external stored json secret value via multiline string templating creates a malformed indentation json value in the kubernetes secret.

**Give us examples of the outcome**

- Stored GCP Secret Manager value to retrieve "my-sa-creds":
```
{
  "type": "service_account",
  "project_id": "project-0123e456",
  "private_key_id": "abc0123abc",
  "private_key": "-----BEGIN PRIVATE KEY-----\value",
  "client_email": "service@testing-0123e456.iam.gserviceaccount.com",
  "client_id": "000000",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/iam.gserviceaccount.com"
}
```

- ExternalSecret object used:
```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: thanos-spike
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-manager

  refreshInterval: 24h

  target:
    name: thanos-spike
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      type: Opaque
      data:
        thanos-store.yaml: |
          type: GCS
          config:
            bucket: thanos-testing-123a123
            service_account: |-
              {{ .sacreds }}

  data:
    - secretKey: sacreds
      # GCP secret details
      remoteRef:
        key: my-sa-creds
```

- Afterwards k8s secret is generated, the resulting decoded b64 value:
```
type: GCS
config:
  bucket: thanos-testing-123a123
  service_account: |-
    {
  "type": "service_account",
  "project_id": "testing-0123e456",
  "private_key_id": "abc0123abc",
  "private_key": "-----BEGIN PRIVATE KEY-----\value",
  "client_email": "service@testing-0123e456.iam.gserviceaccount.com",
  "client_id": "000000",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/iam.gserviceaccount.com"
}
```

See how **service_account**  json value gets wrongly indented, thus my end-service fails to parse/read it so it can't use this secret.

This is how it should correctly look like:

```
type: GCS
config:
  bucket: thanos-testing-123a123
  service_account: |-
    {
      "type": "service_account",
      "project_id": "testing-0123e456",
      "private_key_id": "abc0123abc",
      "private_key": "-----BEGIN PRIVATE KEY-----\value",
      "client_email": "service@testing-0123e456.iam.gserviceaccount.com",
      "client_id": "000000",
      "auth_uri": "https://accounts.google.com/o/oauth2/auth",
      "token_uri": "https://oauth2.googleapis.com/token",
      "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
      "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/iam.gserviceaccount.com"
    }
```

**Observations (Constraints, Context, etc):**

I've tested to retrieve the same secret without multiline templating and recover it as a k/v , in this case the json doesn't get malformed and is correctly retrieved.

```
  target:
    name: thanos-spike 
    template:
      engineVersion: v2
      type: Opaque
      data:
        bucket: thanos-testing-123a123
        service_account: "{{ .sacreds }}"
```

**Comment by gusfcarvalho** [comment]
Hi @dllegru ! Have you tried using `nident` function?

like this?
```
        thanos-store.yaml: |
          type: GCS
          config:
            bucket: thanos-testing-123a123
            service_account: |-
              {{ .sacreds | nident 8}}
```

**Comment by dllegru** [comment]
Hi @gusfcarvalho! Thank you for the hint! 😄 

I managed to get it working with the following:

```
        thanos-store.yaml: |
          type: GCS
          config:
            bucket: thanos-testing-123a123
            service_account: |-
          {{ .sacreds | indent 4}}
```

Now It is generating the correct indented output in the secret  🎉 

I've used `indent` instead of `nindent` to remove the newline at the beginning, also had to place the `{{ .sacreds | indent 4}}` bit indented left so the first line of the generated json value also gets correclty placed.

Thanks again for your help! 👍
