### ISSUE TITLE
Errors in controller logs "connect: connection refused"

### ISSUE THREAD

**Issue by hammadzz** [external-secrets/external-secrets#1410]
### Description
Deployed external-secrets controller v0.5.8 is experiencing intermittent connection issues. Unable to figure out if this is cluster related or service related. Any ideas what it could be?

### Resource Manifest
```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: my-secret
  namespace: staging
  labels:
    app: my-app
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: my-app
    meta.helm.sh/release-namespace: staging
spec:
  secretStoreRef:
    name: clustersecretstore
    kind: ClusterSecretStore
  refreshInterval: "30s"
  target:
    deletionPolicy: "Retain"
  dataFrom:
  - extract:
      key: k8s-secrets-staging-my-app
      version: latest
```
### Logs
```
{"ExternalSecret":"staging/my-secret", "SecretStore":"/clustersecretstore", "error":"Get "https://10.0.0.1:443/api/v1/namespaces/staging/secrets/my-secret": dial tcp 10.0.0.1:443: connect: connection refused", "level":"error", "logger":"controllers.ExternalSecret", "msg":"could not get existing secret: %w", "stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:114
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:311
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:227", "ts":1.6590694800077114E9}
	
{"ExternalSecret":"staging/my-secret", "SecretStore":"/clustersecretstore", "error":"failed to create GCP secretmanager client: unable to fetch pod token: Post "https://10.0.0.1:443/api/v1/namespaces/external-secrets/serviceaccounts/cluster-secret-store/token": dial tcp 10.0.0.1:443: connect: connection refused", "level":"error", "logger":"controllers.ExternalSecret", "msg":"could not get provider client", "stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:114
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:311
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:227", "ts":1.6590694800102541E9}
	
"ExternalSecret":"staging/my-secret", "SecretStore":"/clustersecretstore", "error":"Patch "https://10.0.0.1:443/apis/external-secrets.io/v1beta1/namespaces/staging/externalsecrets/my-secret/status": dial tcp 10.0.0.1:443: connect: connection refused", "level":"error", "logger":"controllers.ExternalSecret", "msg":"unable to patch status", "stacktrace":"github.com/external-secrets/external-secrets/pkg/controllers/externalsecret.(*Reconciler).Reconcile
	/home/runner/work/external-secrets/external-secrets/pkg/controllers/externalsecret/externalsecret_controller.go:215
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:114
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:311
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:227", "ts":1.6590694800127802E9}
```
