### ISSUE TITLE
0.5.8 seemingly breaks existing secrets due to decodingStrategy functionality

### ISSUE THREAD

**Issue by jbilliau-rcd** [external-secrets/external-secrets#1428]
We are using ESO 0.5.6 and secrets come in fine using this `ExternalSecret` spec:

```
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      key: /test/302040/RDS_PASSWORD
    secretKey: RDS_PASSWORD
  - remoteRef:
      conversionStrategy: Default
      key: /test/302040/RDS_USER
    secretKey: RDS_USER
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: test-whale-aws-secretsmanager-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: test-whale-aws-secrets-eso
```

Upgraded to 0.5.8, seeing this now in controller logs:

`{"level":"error","ts":1659544532.7462354,"logger":"controllers.ExternalSecret","msg":"could not get secret data from provider","ExternalSecret":"test-whale/test-whale-aws-secrets-eso","SecretStore":"test-whale/test-whale-aws-secretsmanager-secret-store","error":"could not apply decoding strategy to spec.data[0]: decoding strategy is not supported","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:114\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:311\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:227"}`

Does 0.5.8 require some spec update I'm not seeing? it looks like PR #1294  defaults it to "None", which should replicate existing 0.5.6 behavior.
