### ISSUE TITLE
Applying a template to an existing ExternalSecret resource causes the template data to be merged instead of overwritten.

### ISSUE THREAD

**Issue by gusfcarvalho** [external-secrets/external-secrets#1429]
relates to https://github.com/external-secrets/external-secrets/issues/1362

When applying a template data for an existing ExternalSecret, instead of applying only the existing keys of the template. ESO merges the Secrets' existing content with the template output.

Steps to reproduce:
Create an existing ExternalSecret / SecretStore:
```
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: fake-backend
spec:
  provider:
    fake:
      data:
      - key: "/foo"
        value: "bar"
---
apiVersion: external-secrets.io/v1beta1 
kind: ExternalSecret
metadata:
  name: template-bug
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: fake-backend
    kind: SecretStore
  target:
    name: secret-to-be-created
  data:
  - secretKey: foo
    remoteRef:
      key: "/foo"
```
resulting secret:
```
Data
====
foo:  3 bytes
```

Update ExternalSecret to use Template:
```
apiVersion: external-secrets.io/v1beta1 
kind: ExternalSecret
metadata:
  name: template-bug
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: fake-backend
    kind: SecretStore
  target:
    name: secret-to-be-created
    template:
      data:
        newFoo: "{{ .foo }}"
  data:
  - secretKey: foo
    remoteRef:
      key: "/foo"
```

Check the secret outcome:
```
Data
====
newFoo:  3 bytes 
foo:     3 bytes # Not expected
```
