### ISSUE TITLE
Secrets get not renewed when referenced ConfigMap changes

### ISSUE THREAD

**Issue by mhoyer** [external-secrets/external-secrets#1430]
**Describe the solution you'd like**

I am referring to the `templateFrom` approach of referencing existing ConfigMaps: https://external-secrets.io/v0.5.8/guides-templating/#templatefrom

When updating a referenced `ConfigMap` I would like to see the previously "rendered" secret to be updated accordingly with new `ConfigMap` contents through external secrets.

Given this setup:

```
ConfigMap  <--[references]--  ExternalSecret --[creates]--> Secret
```

... and the example resources from https://external-secrets.io/v0.5.8/guides-templating/#templatefrom

```yaml
# define your template in a config map
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config-tpl
data:
  config.yaml: |
    datasources:
      - name: Graphite
        type: graphite
        access: proxy
        url: http://localhost:8080
        password: "{{ .password }}"
        user: "{{ .user }}"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: my-template-example
spec:
  # ...
  target:
    name: secret-to-be-created
    template:
      engineVersion: v2
      templateFrom:
      - configMap:
          # name of the configmap to pull in
          name: grafana-config-tpl
          # here you define the keys that should be used as template
          items:
          - key: config.yaml
  data:
  - secretKey: user
    remoteRef:
      key: /grafana/user
  - secretKey: password
    remoteRef:
      key: /grafana/password
```

When modifying the `grafana-config-tpl` ConfigMap, I would expect to see the `secret-to-be-created` Secret to be updated accordingly.

**What is the added value?**

No need to manually delete the `Secret` resource to let `ExternalSecret` re-create it using the correct `ConfigMap` as template.

**Observations (Constraints, Context, etc):**

- ExternalSecrets version `0.5.8` is in use
- We are also doing GitOps via ArgoCD which should not require anyone to manually delete or modify things on the clusters
- I also asked in the kubernetes slack channel, but got no advice for alternative solutions: https://kubernetes.slack.com/archives/C017BF84G2Y/p1658328831279609

**Comment by gusfcarvalho** [comment]
Hi @mhoyer ! Sorry for the delay.

I wanted to check if I understood correctly. Once you create an ExternalSecret which references a configMap, the ExternalSecret does not automatically refreshes when the configMap changes, and rather you need to wait for the `refreshInterval` to see the changes. Is that it?

**Comment by gusfcarvalho** [comment]
I just applied this manifest combo:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config-tpl
data:
  config.yaml: |
    datasources:
      - name: Graphite
        type: graphite
        access: proxy
        url: http://localhost:8080
        password: "{{ .password }}"
        user: "{{ .user }}"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: my-template-example
spec:
  refreshInterval: 10s
  secretStoreRef:
    name: secretstore-sample
    kind: SecretStore
  target:
    name: secret-to-be-created
    template:
      engineVersion: v2
      templateFrom:
      - configMap:
          # name of the configmap to pull in
          name: grafana-config-tpl
          # here you define the keys that should be used as template
          items:
          - key: config.yaml
  data:
  - secretKey: user
    remoteRef:
      key: /foo/user
  - secretKey: password
    remoteRef:
      key: /foo/pass
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secretstore-sample
spec:
  provider:
    fake:
      data:
      - key: "/foo/user"
        value: "user"
      - key: "/foo/pass"
        value: "passw0rd"
 ```
 and got this secret result:
 ```
 datasources:
  - name: Graphite
    type: graphite
    access: proxy
    url: http://localhost:8080
    password: "passw0rd"
    user: "user"
```

after updating the configmap to:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config-tpl
data:
  config.yaml: |
    datasources:
      - name: Graphite
        type: graphite
        access: proxy
        url: http://localhost:8080
        password: "{{ .password }}"
        user: "{{ .user }}"
        newField: "{{ .user }} and {{ .password }}"
```
I got the updated secret as expected:
```
datasources:
  - name: Graphite
    type: graphite
    access: proxy
    url: http://localhost:8080
    password: "passw0rd"
    user: "user"
    newField: "user and passw0rd"
```
