### ISSUE TITLE
Getting multiple secrets by using tags doesn't seem to work

### ISSUE THREAD

**Issue by goodbsw** [external-secrets/external-secrets#1443]
I am trying to pull multiple secrets by using tags with v0.5.8 and I keep getting synced error.

Here's my manifest:
```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test-secret
  namespace: test
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secretstore-main
    kind: ClusterSecretStore
  target:
    name: test-secret
  dataFrom:
  - find:
      tags:
        application: secret-mgmt
```

I confirmed that the service account that is being referenced has access to AWS secret manager by using data spec. Is there anything that needs to be added?

**Comment by gusfcarvalho** [comment]
Hi @goodbsw ! What is the output of kubectl describe es?

**Comment by goodbsw** [comment]
@gusfcarvalho Here's the output
```
status:
  conditions:
  - lastTransitionTime: "2022-08-09T16:49:28Z"
    message: could not get secret data from provider
    reason: SecretSyncedError
    status: "False"
    type: Ready
```

FYI, here's the tag 
<img width="1605" alt="image" src="https://user-images.githubusercontent.com/37948897/183710793-01af2ce0-a996-4df4-bdf2-19450a5ca971.png">
