### ISSUE TITLE
The ability to generate SealedSecrets

### ISSUE THREAD

**Issue by ianpurton** [external-secrets/external-secrets#1444]
**Describe the solution you'd like**

The ability to generate sealed secrets. https://github.com/bitnami-labs/sealed-secrets. A sealed secret looks the same as a secret however the data is encrypted.

```yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mysecret
  namespace: mynamespace
spec:
  encryptedData:
    foo: AgBy3i4OJSWK+PiTySYZZA9rO43cGDEq.....
```

**What is the added value?**

This will allow secrets to be end to end encrypted with a private key that exists in the cluster. I'm currently trying to integrate https://cloak.software using the web hook. 

The API only returns encrypted secrets so a decrypt step would be necessary which can use existing tools if I'm able to create a `SealedSecret`.

**Give us examples of the outcome**

Perhaps this is already possible as ESO supports templating, but will it allow me to add the following header?

```yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
```

instead of

```
apiVersion: v1
kind: Secret
```

Thanks
