### ISSUE TITLE
ES templateFrom seems to have trouble with prometheus yml template

### ISSUE THREAD

**Issue by jprecuch** [external-secrets/external-secrets#1445]
**Describe the solution you'd like**
External-secrets seems to not accept configmap with function toUpper/index inside of template.
It would be good if it somehow can accept it because it is normal to be used in Prometheus world.

**What is the added value?**
Support for more functions (especially for prometheus)

**Give us examples of the outcome**

**Observations (Constraints, Context, etc):**
Details how to reproduce this:
Configmap:
```
apiVersion: v1
data:
  alertmanager.yml: |-
    receivers:
    - name: slack-critical
      slack_configs:
      - api_url: "{{ .eswebhook }}"
        channel: "#slack"
        username: USER
        icon_emoji: '{{ if eq .Status "firing" }}:exclamation:{{ else }}:green_heart:{{ end }}'
        color: '{{ if eq .Status "firing" }}danger{{ else }}good{{ end }}'
        send_resolved: true
        title: |-
          [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }}
        text: >-
          {{ range .Alerts -}}
            *Alert:* {{ if .Labels.severity }} `{{ .Labels.severity | toUpper }}` - {{ .Annotations.summary }}{{ end }}
          *Description:* {{ .Annotations.description }}

          *Details:*
            {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
            {{ end }}
          {{ end }}
        footer: >-
          {{ with index .Alerts 0 -}}
            :notebook: "test"
          {{ end }}
kind: ConfigMap
metadata:
  name: test-prometheus
  namespace: default
```
ES:
```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "test-prometheus"
  namespace: default
spec:
  secretStoreRef:
    name: main-cluster-secret-store
    kind: ClusterSecretStore
  refreshInterval: "1h"

  target:
    name: test-prometheus
    creationPolicy: 'Owner'
    deletionPolicy: "Retain"

    template:
      templateFrom:
      - configMap:
          name: alertmanager
          items:
          - key: alertmanager.yml

  # Data defines the connection between the Kubernetes Secret keys and the Provider data
  data:
    - secretKey: webhook
      remoteRef:
        key: cvs-tst-us-east4-webhook
```
Error we will get:
```
Status:
  Conditions:
    Last Transition Time:  2022-08-11T07:09:56Z
    Message:               could not update Secret
    Reason:                SecretSyncedError
    Status:                False
    Type:                  Ready
Events:
  Type     Reason        Age              From              Message
  ----     ------        ----             ----              -------
  Warning  UpdateFailed  1s (x9 over 2s)  external-secrets  could not apply template: could not execute template: unable to execute template at key alertmanager.yml: unable to parse template at key alertmanager.yml: template: alertmanager.yml:11: function "toUpper" not defined
```
If I remove this function it does not like index afterwards
```
Status:
  Conditions:
    Last Transition Time:  2022-08-11T07:19:09Z
    Message:               could not update Secret
    Reason:                SecretSyncedError
    Status:                False
    Type:                  Ready
Events:
  Type     Reason        Age              From              Message
  ----     ------        ----             ----              -------
  Warning  UpdateFailed  0s (x9 over 2s)  external-secrets  could not apply template: could not execute template: unable to execute template at key alertmanager.yml: unable to execute template at key alertmanager.yml: template: alertmanager.yml:22:14: executing "alertmanager.yml" at <index .Alerts 0>: error calling index: index of untyped nil
```
Is there some way how to prevent/fix this without escaping everything? (it might break prometheus side)

**Comment by gusfcarvalho** [comment]
Hi @jprecuch ! The issue is that you are trying to pass templates to prometheus itself, but you are not escaping it on ESO level. This is causing ESO to try to interpret such files.

what you can do is escape the values that you don't want ESO to handle:
```
    receivers:
    - name: slack-critical
      slack_configs:
      - api_url: "{{ .eswebhook }}" # you want to keep this one as this will be parsed by eso
        channel: "#slack"
        username: USER
        icon_emoji: '{{ "{{" }} if eq .Status "firing" {{ "}}" }}:exclamation:{{ "{{" }} else {{ "}}" }}:green_heart:{{ "{{" }} end {{ "}}" }}' # you want eso to ignore these ones
```
