### ISSUE TITLE
Removing common path with regexp rewrite is not working as documented

### ISSUE THREAD

**Issue by Shiehand** [external-secrets/external-secrets#1447]
**Describe the solution you'd like**
I am trying to use dataFrom.find to get multiple secrets from AWS Parameter Store, trying to remove the common path by following the documentation https://external-secrets.io/v0.5.9/guides-datafrom-rewrite/

```
    - regexp:
        source: "path/to/my/secrets/(.*)"
        target: "$1"
```
Using this regexp didn't do anything to the generated secret keys:
For secrets:
```
path/to/my/secrets/username
path/to/my/secrets/password
```
Generated keys:
```
apiVersion: v1
kind: Secret
type: Opaque
data:
   _path_to_my_secrets_username: ...
   _path_to_my_secrets_password: ...
```
However, using this regexp:
```
    - regexp:
        source: "_path_to_my_secrets_(.*)"
        target: "$1"
```
Does output only the last path as expected:
```
apiVersion: v1
kind: Secret
type: Opaque
data:
   username: ...
   password: ...
```

**What is the added value?**
The feature works with the regexp with underscores (instead of slashes), but I would like a confirmation on whether this is a documentation mistake or an actual bug. Thank you for your help!

**Comment by gusfcarvalho** [comment]
Hi @Shiehand ! It is a bug indeed! We are deprecating ConvertKeys method, but it seems AWS provider calls the method directly at [line 112](https://github.com/external-secrets/external-secrets/blob/main/pkg/provider/aws/parameterstore/parameterstore.go#L112) and [line 155](https://github.com/external-secrets/external-secrets/blob/main/pkg/provider/aws/parameterstore/parameterstore.go#L155). The bug should be pretty straightforward to fix (if you want to give it a try :smile:)

**Comment by gusfcarvalho** [comment]
We also need to change this behavior in SecretsManager calls!

**Comment by yuliyantsvetkov** [comment]
/reopen

This seems it is not fixed in general as I follow the article here for Parameter store and I always end up with the _common_path in the secret.

https://external-secrets.io/latest/guides/datafrom-rewrite/

Here is my manifest definition:

```
  dataFrom:
  - find:
      path: /development/env
      name: 
        regexp: service-one-is-here
  - rewrite:
    - regexp:
        source: "development/env/service-one-is-here/(.*)"
        target: "$1"
```
        
And the secret value is:

`_development_env_service-one-is-here_key`

**Comment by moolen** [comment]
You're specifying two array elements, you shouldn't! The `find` and `rewrite` should be in the same array element


```yaml
  dataFrom:
  - find:
      path: /development/env
      name: 
        regexp: service-one-is-here
    rewrite:
    - regexp:
        source: "development/env/service-one-is-here/(.*)"
        target: "$1"
```
        
And the secret value is:

`_development_env_service-one-is-here_key`
