### ISSUE TITLE
AWS Secrets Manager: getting key (ExternalSecrets "property") *starting* with a period fails

### ISSUE THREAD

**Issue by stephen-dexda** [external-secrets/external-secrets#1448]
external-secrets 0.5.9.

Sample ExternalSecret config.:

```
  data:
  - secretKey: foo
    remoteRef:
      key: bar/baz
      property: .foo
```

Error message from `describe externalsecret ...`:

```
key .foo does not exist in secret bar/baz
```

This is very similar to https://github.com/external-secrets/external-secrets/issues/963, but the issue now seems to be limited to cases where the dot is at the beginning of the AWS Secret's key.
