### ISSUE TITLE
aws secret manager tls base64 encoded but unable to view

### ISSUE THREAD

**Issue by trevorndodds** [external-secrets/external-secrets#1476]
I put tls keys into AWS Secret manager base64 encoded due to line break issues (https://ritesh-yadav.github.io/tech/format-certificate-from-aws-sercet-manager/) however when calling with the below code I get illegal base64 data at input byte 76
Is there something I am missing? 
If I do not use the template v2, then the value comes through but its double encoded. 

```
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: api-cert
        property: tls.crt
      secretKey: tlscrt
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: api-cert
        property: tls.key
      secretKey: tlskey
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secret
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: api-custom-cert
    template:
      data:
        tls.crt: '{{ .tlscrt | b64dec }}'
        tls.key: '{{ .tlskey | b64dec }}'
      engineVersion: v2
      metadata: {}
      type: kubernetes.io/tls
```
