### ISSUE TITLE
Issue with decodingStrategy Base64

### ISSUE THREAD

**Issue by jholowaty** [external-secrets/external-secrets#1486]
Hi! I am using the External-Secrets Operator and the secret brings it to me ok but… I need it to decode it in base64 since I need the flat values ​​as they are in the Secret Manager in GCP!
I updated the ESO helm to version 0.5.9 and I am trying the following:

```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-auth
  namespace: external-dns
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: secret-store
  target:
    name: cloudflare-auth
    creationPolicy: Owner
  data:
    - secretKey: cloudflare-auth
      remoteRef:
        key: cloudflare-auth
        decodingStrategy: Base64
```

If I load it like this, the state of the ExternalSecret is as follows:

```
NAME              STORE          REFRESH INTERVAL   STATUS              READY
cloudflare-auth   secret-store   1h                 SecretSyncedError   False
```

And the message inside is:
message: could not get secret data from provider

Now… if I load it by changing the Base64 to Auto (https://external-secrets.io/v0.5.9/api-externalsecret/ - decodingStrategy: None # can be None, Base64, Base64URL or Auto) there it synchronizes OK the secret but if I see the secret it is encrypted and I need it to be brought to me as if I were loading a secret opaque by hand:

```
apiVersion: v1
data:
  mail: valor
  key: valor
kind: Secret
metadata:
  creationTimestamp: "2022-08-22T20:11:55Z"
  name: mysecret
  namespace: external-dns
  resourceVersion: "3338212"
  uid: 5a8b3ca6-7413-4e5b-9fdc-c46df2867cd6
type: Opaque
```
Am I missing something in the ExternalSecret that can't bring me the secret in plain text?

Thank a lot to everyone!!!!!
