### ISSUE TITLE
AWS SSM Parameter store with multiple k-v

### ISSUE THREAD

**Issue by Wilderone** [external-secrets/external-secrets#1490]
Right now we are migrating from KES to ESO and faced problem with formation of secrets, fetched from AWS SSM Parameter store.
We want to fill kind=secret with multiple key-values, which are stored in aws ssm parameter store as single parameter with multiple keys.
Currently our secrets being stored in ssm in valid YAML format, and we want to access data from this YAML in externalSecret, but seems like it's impossible, because of any data, fetched from parameter store presented as string, so we can't access to any keys in it.

**Describe the solution you'd like**
Being able to pass each key from AWS SSM parameter to separate keys of template.data 

**What is the added value?**
More flexible formation of kind=secret

**Give us examples of the outcome**
Data in parameter store be like:
```
someKey: someVal
someList:
  - someListVal
  -  someListVal2
additionalKey: additionalVal
```
And ExternalSecret with KES was like this:
```
spec:
  backendType: systemManager
  data:
    - key: /path/to/secret-values-yaml
      name: values.yaml
  template:
    stringData:
      some-key: <%= yaml.load(data["values.yaml"])["someKey"] %>
      some-list: <%= yaml.load(data["values.yaml"])["someList"] %>
      additionalKey-key: <%= yaml.load(data["values.yaml"])["additionalKey"] %>
```

Is there any way to form secrets with ESO like we does it with KES?

**Comment by eTopchik** [comment]
Got the same issue , also with Json format stored is SSM

**Comment by moolen** [comment]
Hey, you should be able to use `toYaml` / `fromYaml` template functions, [see docs](https://external-secrets.io/v0.5.9/guides-templating/#helper-functions). This allows you to decode the yaml string into a `map[string]interface{}` and then you can access the fields with the usual methods.

Does that help?

**Comment by Wilderone** [comment]
@moolen Hi, thanks for your answer, can you give me a little bit more details, where should i use it? To access keys in .template.data i already should have map in .values. Any way to transform string to yaml and access any key in single template block?

**Comment by moolen** [comment]
Hey, here's a full example:

```yaml
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: fake
spec:
  provider:
    fake:
      data:
      - key: "/foo/bar"
        value: |
          foo: bar
          baz: bang
          bazing:
            bong: shring
        version: "v1"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: fake
    kind: ClusterSecretStore
  target:
    name: secret-to-be-created
    template:
      data:
        bazingbong: |
          {{- $myvar := .example | fromYaml -}}
          {{ $myvar.bazing.bong }}
  data:
  - secretKey: example
    remoteRef:
      key: /foo/bar
      version: v1

```

that'll give you:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: secret-to-be-created
data:
  bazingbong: c2hyaW5nCg==
type: Opaque

```

Does that help?
