### ISSUE TITLE
Mutiple Secrets Creation

### ISSUE THREAD

**Issue by jynolen** [external-secrets/external-secrets#1509]
**Describe the solution you'd like**

Given a path that contains mutiple secrets give the possibility for an externalsecret template to create multiple K8S Secret.
Use case example: 
using a CICD we provision cluster access for a ArgoCD server in a well known path /secret/cluster/*cluster-fqdn*
We would like to create a secret in the ArgoCD cluster one for each cluster.

**Comment by jynolen** [comment]
Full Example

`/secret/cluster/lab.cluster.internal.example.com`
```
{
	"endpoint":"https://lab.cluster.internal.example.com",
	"name":"lab",
	"bearerToken": "example_bearer_token_lab",
}
```

`/secret/cluster/staging.cluster.internal.example.com`
```
{
	"endpoint":"https://staging.cluster.internal.example.com",
	"name":"staging",
	"bearerToken": "example_bearer_token_staging",
}
```


`/secret/cluster/prod.cluster.internal.example.com`
```
{
	"endpoint":"https://prod.cluster.internal.example.com",
	"name":"prod",
	"bearerToken": "example_bearer_token_prod",
}
```

With something like this templates

```yaml
apiVersion: external-secrets.io/v1beta1 
kind: ExternalSecret
metadata:
  name: cluster-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secretstore-sample
    kind: SecretStore
      target:
      template:
        name: cluster-{{.name}}
        type: Opaque
        data:
          name: {{.name}}
          server: {{.endpoint}}
          config: |
    {
      "bearerToken": "{{.bearerToken}}",
    }
          connection: '{{ .dburl | replace "postgres://" "postgresql://" }}'
  dataFrom:
  - find:
      name:
        regexp: /secret/cluster
```

To create following secrets

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: cluster-staging
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: staging
  server: https://staging.cluster.internal.example.com
  config: |
    {
      "bearerToken": "example_bearer_token_staging",
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-lab
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: lab
  server: https://lab.cluster.internal.example.com
  config: |
    {
      "bearerToken": "example_bearer_token_lab",
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-prod
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: prod
  server: https://prod.cluster.internal.example.com
  config: |
    {
      "bearerToken": "example_bearer_token_prod",
    }
```
