### ISSUE TITLE
Ibm Cloud Secrets Manager unable to sync PKCS12 Keystore

### ISSUE THREAD

**Issue by AlexanderKern** [external-secrets/external-secrets#1528]
Hello all,

I am trying to synchronize from IBM Cloud Secrets Manager a PKSC Keystore into a cluster as a Secret.

Unfortunately there is a problem when converting the octet stream

```
spec:
  secretStoreRef:
    name: test
    kind: ClusterSecretStore
  target:
    name: keystore-test
  data:
    - secretKey: keystore.jks
      remoteRef:
        key: arbitrary/xxxxx
```

By decoding the secret on the cluster i got the following:

```kubectl get secret keystore-test -o jsonpath="{.data['keystore\.jks']}" | base64 -d```

```data:application/octet-stream;base64,MIIKbwIBAzC........```

Is there a way to convert the stream? So that I get the raw base64 encoded file

Do you have any idea here?

Thanks for help.
