### ISSUE TITLE
[ Hash Corp - Vault ] - Secret not created, secret not found

### ISSUE THREAD

**Issue by jader-sciensano** [external-secrets/external-secrets#1534]
**Expected Output**

Should be pretty simple, after applying the ExternalSecret normally they should create a Secret based on your data.

**Below are all my configuration used**

This is the YAML file with basic configuration to test with Hash Corp Vault. NOTE. I'm using it to connect to my vault, root.

```
apiVersion: v1
kind: Secret
metadata:
  name: vault-token  
data:
  token: c2UuamlpaGloZndoZWZmdzMyCg==
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend  
spec:
  provider:
    vault:
      server: "http://10.100.128.5:8200"
      path: "secret"
      version: "v2"
      auth:        
        tokenSecretRef:
          name: "vault-token"
          key: "token"          
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-example  
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: example-sync
  data:
  - secretKey: foobar
    remoteRef:
      key: secret/foo
      property: my-value
```

Here is the vault kv output.

```
root@434e7d12d652:/# vault read secret/foo
Key                 Value
---                 -----
refresh_interval    768h
my-value            s3cr3t

```
**Give us examples of the outcome**

Here is the controller.
```
bash-5.1# k get all -n external-secrets
NAME                                                    READY   STATUS    RESTARTS   AGE
pod/external-secrets-7886b578b4-bnrx5                   1/1     Running   0          6d3h
pod/external-secrets-cert-controller-5578bf565f-25nsl   1/1     Running   0          6d3h
pod/external-secrets-webhook-69c58546c6-2v9cp           1/1     Running   0          6d3h

NAME                               TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)   AGE
service/external-secrets-webhook   ClusterIP   10.0.124.123   <none>        443/TCP   23d

NAME                                               READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/external-secrets                   1/1     1            1           23d
deployment.apps/external-secrets-cert-controller   1/1     1            1           23d
deployment.apps/external-secrets-webhook           1/1     1            1           23d

NAME                                                          DESIRED   CURRENT   READY   AGE
replicaset.apps/external-secrets-7886b578b4                   1         1         1       23d
replicaset.apps/external-secrets-cert-controller-5578bf565f   1         1         1       23d
replicaset.apps/external-secrets-webhook-69c58546c6           1         1         1       23d
```

Here is the ClusterSecretStore
```
bash-5.1# k get clustersecretstore 
NAME            AGE     STATUS   READY
vault-backend   3h56m   Valid    True
```

Here is the externalsecret.
```
bash-5.1# k get externalsecret
NAME            STORE           REFRESH INTERVAL   STATUS              READY
vault-example   vault-backend   15s                SecretSyncedError   False
Events:
  Type     Reason        Age                      From              Message
  ----     ------        ----                     ----              -------
  Warning  UpdateFailed  3m57s (x472 over 3h59m)  external-secrets  secret not found
```

**Observations**

Can someone explain to me what is wrong I am following the steps and using the exactly same way on the documentation but it's not working?

**Comment by moolen** [comment]
Remove the `secret/` prefix in `remoteRef.key`, that should do it. You have the mount path already specified in the SecretStore spec.

**Comment by jader-sciensano** [comment]
> Remove the `secret/` prefix in `remoteRef.key`, that should do it. You have the mount path already specified in the SecretStore spec. That gives you now `secret/secret/foo`

Hello, Moritz. First thanks for the time to look at my question.
But look at the output below. NOTE. I made the change you point, as you can see below.
```
data:
  - secretKey: foobar
    remoteRef:
      key: foo
      property: my-value
```

The same Message.
````
Status:
  Conditions:
    Last Transition Time:  2022-09-08T11:10:39Z
    Message:               could not get secret data from provider
    Reason:                SecretSyncedError
    Status:                False
    Type:                  Ready
Events:
  Type     Reason        Age              From              Message
  ----     ------        ----             ----              -------
  Warning  UpdateFailed  4s (x2 over 4s)  external-secrets  secret not found
```
