### ISSUE TITLE
Use Azure KeyVault Certificate in CER format

### ISSUE THREAD

**Issue by sgrzemski** [external-secrets/external-secrets#1549]
**Describe the solution you'd like**

Currently if I want to pull certificates from Azure KeyVault I need to set them as regular Azure KeyVault Secrets, not using the features from Certificates. I know I can pull the certificates using `cert/` prefix, but External Secrets pull those in CER format. The CER format is not compatible with `pkcs12cert` and `pkcs12key` functions, as the format differs. I would like to be able to transform CER content to PEM format, to use it inside my applications. Azure requires it's specific format, but I need to have it converted to PEMs.

**What is the added value?**
I can use certificates generated in Azure KeyVault, get them auto rotated and use all the other features of KeyVault etc.

**Give us examples of the outcome**

```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: my-super-secret
  namespace: secret-namespace
spec:
  data:
    - remoteRef:
        key: cert/my-super-secret
      secretKey: certificate
  refreshInterval: 30m
  secretStoreRef:
    kind: ClusterSecretStore
    name: my-super-secret-store
  target:
    name: my-super-secret
    template:
      data:
        tls.crt: '{{ .certificate  | pkcs12cert }}'
      type: kubernetes.io/tls
      engineVersion: v2
```

**Observations (Constraints, Context, etc):**
N/A
