### ISSUE TITLE
AWS EKS OIDC - could not get secret data from provider

### ISSUE THREAD

**Issue by shllg** [external-secrets/external-secrets#1555]
**Issue**

Although controller authenticates via ServiceAccount / OIDC, fetching secrets always ends up in "could not get secret data from provider" error message. 

```
{"level":"error","ts":1663325349.8799698,"logger":"controllers.ExternalSecret","msg":"could not get secret data from provider","ExternalSecret":"[NAMESPACE]/[SECRET-NAME]","SecretStore":"/aws-secret-store","error":"RequestError: send request failed\ncaused by: Post \"https://secretsmanager.eu-central-1.amazonaws.com/\": dial tcp XXX.XXX.XXX.XXX:443: i/o timeout","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:121\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:320\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:234"}
```

**Setup**

EKS Cluster with connected OIDC provider is configured.

*IAM Policy*

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "secretsmanager:GetResourcePolicy",
                "secretsmanager:GetSecretValue",
                "secretsmanager:DescribeSecret",
                "secretsmanager:ListSecretVersionIds"
            ],
            "Resource": "arn:aws:secretsmanager:eu-central-1:[ACCOUNT-ID]:secret:some-prefix/*"
        }
    ]
}
```

*IAM Role*

Policy is assigned to an IAM Role called below `IAM_ROLE_ARN`.

Trust relationships of `IAM_ROLE_ARN`:

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "Federated": "arn:aws:iam::[ACCOUNT-ID]:oidc-provider/oidc.eks.eu-central-1.amazonaws.com/id/[OIDC-PROVIDER-ID]"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "StringLike": {
                    "oidc.eks.eu-central-1.amazonaws.com/id/[OIDC-PROVIDER-ID]:sub": "system:serviceaccount:external-dns:external-dns",
                    "oidc.eks.eu-central-1.amazonaws.com/id/[OIDC-PROVIDER-ID]:aud": "sts.amazonaws.com"
                }
            }
        }
    ]
}
```

*K8s ServiceAccount* 

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: external-secrets
  annotations:
    eks.amazonaws.com/role-arn: [IAM_ROLE_ARN]
```

*K8s ClusterSecretStore*

```yaml
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secret-store
  namespace: external-secrets
spec:
  provider:
    aws:
      service: SecretsManager
      region: ${AWS_REGION}
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
```

*K8s Test Secret* 

```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret-test
  namespace: hello-kubernetes
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store
    kind: ClusterSecretStore
  target:
    name: test-secret
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: some-prefix/test-secret
```

---

**Observations**

- The OIDC token is issued which means the role assumption works. Changing something inside the IAM Role trust relationship which is not correct leads to an STS assumption error - as cross check.
- Changing the policy to `"Resource": "*"` does not help (do we need to fetch a new token on policy change?)
- Changing the trust relationships to `"oidc.eks.eu-central-1.amazonaws.com/id/[OIDC-PROVIDER-ID]:sub": "system:serviceaccount:*:*"` does not help (again I think that it's not an OIDC assumption issue)
- Security Groups allow all outbound traffic

---

Can somebody help me out with that issue? I don't know how to debug further. The setup looks fine up to the actual secret fetching. 

Thanks in advance :-)
