### ISSUE TITLE
kubectl get externalsecret is returning no results

### ISSUE THREAD

**Issue by lukonjun** [external-secrets/external-secrets#1576]
Hi just trying out external-secrets, configured it for AWS Secrets Manager and I can create/retrieve a secret with the following code. 
```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-secret
  namespace: app
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: global-secret-store
    kind: ClusterSecretStore
  target:
    name: app-secret
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: secret
```
I am using `external-secrets-0.5.9`

running into the following confusing thing
```
kubectl -n app apply -f app-secret.yaml 
externalsecret.external-secrets.io/app-secret configured
```
when i now try to see the created resource it is not displayed, would have expected to see the externalsecret resource here, verified I am in the right namepsace app
```
kubectl get externalsecret -n app
No resources found in app namespace.
```
Running the command for all namespaces also returns no results
```
kubectl get ExternalSecret -A                
No resources found
```
The Secret however is successfully created
```
kubectl get secrets -n app
NAME                  TYPE                                  DATA   AGE
app-secret            Opaque                                1      29m
```
