### ISSUE TITLE
IAM Roles Anywhere support in ESO

### ISSUE THREAD

**Issue by sanooprajps** [external-secrets/external-secrets#1585]
ESO should support IAM Roles Anywhere as the authentication mechanism. This will enable secure authentication in datacenter clusters .

**Comment by moolen** [comment]
I'm working on this, got a PoC running.

**Comment by moolen** [comment]
Updated current status in slack: https://kubernetes.slack.com/archives/C017BF84G2Y/p1691681814406959?thread_ts=1691681814.406959&cid=C017BF84G2Y

It is a working implementation IIRC (at least partially, i did some manual testing with it to verify its behaviour). I think i linked a commit/branch in that issue (see above). The "only" thing that's missing is e2e tests, which will take a bit of time to implement. 

I stopped finishing the implementation due to the lack of resources and the need on our end. 

If someone here has a need for it, i'd be happy to provide guidance/review where needed. Unfortunately this isn't on the top of my priority list right now.

**Comment by BeyondEvil** [comment]
Any updates here?

I'm happy to contribute if needed to get this GA.

**Comment by moolen** [comment]
Hey @BeyondEvil, i'm happy to hear that! I've opened a PR from a very old commit of mine, see #4224. I don't yet have plans to take this over the finish line. If you want feel free to take it over, happy to chat of you have questions.

AFAICT @qlemaire-dvt may also have interest in this.

**Comment by BeyondEvil** [comment]
Hey @moolen 

That’s awesome! I’ll need some guidance as this would be my first contribution to ESO.

Should I do the work on your branch or checkout a new one based on yours?

**Comment by moolen** [comment]
Hey @BeyondEvil, please fork the repo and create a new branch on your fork. We have a [devguide here](https://external-secrets.io/latest/contributing/devguide/), which should get you set up.

Maybe you should start from scratch, just looked at the code again. It's just PoC-level :hankey:.

**Comment by BeyondEvil** [comment]
@moolen Should I/we start with a PR "just" bumping aws-sdk-go to v2? 🤔

**Comment by moolen** [comment]
"just" :smile: I thought about that, too. But i think this is quite a lot of effort for this feature.

I haven't looked into the differences of v1 and v2 - specially for the `anywhere` pkg and auth in general. I'm open to get the `anywhere` feature without bumping SDKs and do the bump later on.

**Comment by qlemaire-dvt** [comment]
I'm not too much of a developer, but since I have a use case for it I can always help for testing !

**Comment by BeyondEvil** [comment]
> "just" 😄 I thought about that, too. But i think this is quite a lot of effort for this feature.
> 
> I haven't looked into the differences of v1 and v2 - specially for the `anywhere` pkg and auth in general. I'm open to get the `anywhere` feature without bumping SDKs and do the bump later on.

Given that v1 is EOL in like 6 months, it needs to be done regardless. Especially given the relatively sensitive nature of ESO's domain (secrets).

The migration docs seem to be pretty straightforward, so I'm fairly confident that between myself and Chat Gippity, we can fix this. 😊 

I'll timebox it to 2 days worth of work.

Cool? @moolen

**Comment by moolen** [comment]
SGTM! Thank you for looking into this!

**Comment by BeyondEvil** [comment]
> SGTM! Thank you for looking into this!

Hey, sorry for dragging my feet on this.

I spent about a day during the holidays and barely did a dent to upgrading to V2 of the AWS SDK. :(

On top of that, we decided to take another route (essentially running the credentials helper as a side car), so I don't have the bandwidth to take this on.

Again, sorry for the delay in communication. 🙇

**Comment by Skarlso** [comment]
Yeah, don't worry about it. Upgrading to v2 is a _massive_ undertaking. I don't even have a migration path honestly. Looking at the code, I can see it's basically a complete rewrite. :/ Config, authentication, region checks, service interfaces, tests... Then e2e tests... It's insane how much work that is. :( I don't even know when and how this would happen. I would have to take a week off just to work on this.

**Comment by BeyondEvil** [comment]
> Yeah, don't worry about it. Upgrading to v2 is a _massive_ undertaking. I don't even have a migration path honestly. Looking at the code, I can see it's basically a complete rewrite. :/ Config, authentication, region checks, service interfaces, tests... Then e2e tests... It's insane how much work that is. :( I don't even know when and how this would happen. I would have to take a week off just to work on this.

Yeah, that was my estimation as well. 😅 

And since I don't have any prior experience with this code base, it became too overwhelming. 😬 

Happy to assist as rubber duck if you want tho. 😊

**Comment by Skarlso** [comment]
I know that this _has_ to be done at one point, especially because of issues like #4306.

**Comment by gusfcarvalho** [comment]
we will likely bounty #4310. Anyone interested please manifest over #external-secrets-dev Kubernetes Slack Channel 😄

**Comment by shay1197** [comment]
Hi,
Can someone update what is the status? please :)

**Comment by moolen** [comment]
@shay1197 
aws sdk has been upgraded to v2 which paves the way for this feature to be delivered. AFAIK there's no progress on it.

**Comment by jamesreprise** [comment]
We've been able to make use of IAM Roles Anywhere in the already released external-secrets v0.19.2 using an IAMRA sidecar container as described in the [official AWS docs](https://aws.amazon.com/blogs/security/connect-your-on-premises-kubernetes-cluster-to-aws-apis-using-iam-roles-anywhere/) and setting environment variable `AWS_EC2_METADATA_SERVICE_ENDPOINT=http://127.0.0.1:9911/` for external-secrets itself. This is all that is needed for the underlying AWS SDK to authenticate.

Official support would be nice, but be aware that it is not necessary.

**Comment by moolen** [comment]
Yo @jamesreprise this is highly  appreciated, thanks for sharing this :heart:, really appreciated

**Comment by BeyondEvil** [comment]
Here's what the IAMRA sidecar actually looks like:

`values.yaml`:

```yaml
env:
  - name: AWS_EC2_METADATA_SERVICE_ENDPOINT
    value: 'http://127.0.0.1:9911/'

extraVolumes:
  - name: credentials
    secret:
      secretName: external-dns-iamra-cert

extraContainers:
  - name: iamra
    image: ghcr.io/company/aws-signing-helper:sha-423403a
    command: ['aws_signing_helper']
    args:
      - 'serve'
      - '--certificate'
      - '/mnt/credentials/tls.crt'
      - '--private-key'
      - '/mnt/credentials/tls.key'
      - '--trust-anchor-arn'
      - '$(TRUST_ANCHOR_ARN)'
      - '--profile-arn'
      - '$(PROFILE_ARN)'
      - '--role-arn'
      - '$(ROLE_ARN)'
    env:
      - name: TRUST_ANCHOR_ARN
        valueFrom:
          configMapKeyRef:
            key: IAMRA_TRUST_ANCHOR_ARN
            name: external-dns-iamra
      - name: PROFILE_ARN
        valueFrom:
          configMapKeyRef:
            key: IAMRA_PROFILE_ARN
            name: external-dns-iamra
      - name: ROLE_ARN
        valueFrom:
          configMapKeyRef:
            key: IAMRA_ROLE_ARN
            name: external-dns-iamra
    volumeMounts:
      - mountPath: /mnt/credentials
        name: credentials
    resources:
      requests:
        memory: 64Mi
        cpu: 10m
      limits:
        memory: 128Mi
    imagePullPolicy: IfNotPresent
```

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: external-dns-iamra
  namespace: external-dns
data:
  IAMRA_PROFILE_ARN: arn:aws:rolesanywhere:eu-north-1:<account>:profile/65aab928-43a0-4565-aba6-4ee6e3750d84
  IAMRA_ROLE_ARN: arn:aws:iam::<account>:role/company-stage-eu-north-1-k8s-external-dns
  IAMRA_TRUST_ANCHOR_ARN: arn:aws:rolesanywhere:eu-north-1:<account>:trust-anchor/beef42e9-d7f5-4633-b9bd-660a83ffbd8a
```

When we created this, there was no official Docker image for the signing helper, so we roll our own:

```Dockerfile
FROM ubuntu@sha256:72297848456d5d37d1262630108ab308d3e9ec7ed1c3286a32fe09856619a782

RUN apt-get update && \
  apt-get install -y curl

WORKDIR /usr/local/bin
ARG HELPER_VERSION=1.4.0
RUN curl -O https://rolesanywhere.amazonaws.com/releases/${HELPER_VERSION}/X86_64/Linux/aws_signing_helper
RUN chmod a+x aws_signing_helper

USER 1000
```

But I do believe there's an official one now: https://github.com/aws/rolesanywhere-credential-helper/issues/100
