### ISSUE TITLE
unable to unmarshal secret (Oracle Provider)

### ISSUE THREAD

**Issue by mezoology** [external-secrets/external-secrets#1605]
External Secret not syncing with the error: could not get secret data from provider.

`kubectl describe externalsecret.external-secrets.io/example` output:

```
Name:         example
Namespace:    default
Labels:       <none>
Annotations:  <none>
API Version:  external-secrets.io/v1beta1
Kind:         ExternalSecret
Metadata:
  Creation Timestamp:  2022-10-04T16:49:22Z
  Generation:          1
  Managed Fields:
    API Version:  external-secrets.io/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:dataFrom:
        f:refreshInterval:
        f:secretStoreRef:
          .:
          f:kind:
          f:name:
        f:target:
          .:
          f:creationPolicy:
          f:deletionPolicy:
          f:name:
    Manager:      kubectl-client-side-apply
    Operation:    Update
    Time:         2022-10-04T16:49:22Z
    API Version:  external-secrets.io/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        .:
        f:conditions:
    Manager:         external-secrets
    Operation:       Update
    Subresource:     status
    Time:            2022-10-04T16:49:23Z
  Resource Version:  931043
  UID:               aaf572aa-112b-48aa-a4d8-77d05301f0d9
Spec:
  Data From:
    Extract:
      Conversion Strategy:  Default
      Decoding Strategy:    None
      Key:                  try2
  Refresh Interval:         0.03m
  Secret Store Ref:
    Kind:  SecretStore
    Name:  oracle-auth
  Target:
    Creation Policy:  Owner
    Deletion Policy:  Retain
    Name:             secret-to-be-created
Status:
  Conditions:
    Last Transition Time:  2022-10-04T16:49:23Z
    Message:               could not get secret data from provider
    Reason:                SecretSyncedError
    Status:                False
    Type:                  Ready
Events:
  Type     Reason        Age              From              Message
  ----     ------        ----             ----              -------
  Warning  UpdateFailed  2s (x2 over 2s)  external-secrets  unable to unmarshal secret: invalid character 'k' looking for beginning of value
```

the `ExternalSecret` yaml
```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example
spec:
  refreshInterval: 0.03m
  secretStoreRef:
    kind: SecretStore
    name: oracle-auth  # Must match SecretStore on the cluster
  target:
    name: secret-to-be-created # Name for the secret on the cluster
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: try2
```

on Oracle logs, the API call is successful. i think the issue is the response format ?
on the Events. the 'K' letter is actually the first letter of the value
any idea how to solve this issue would be great.

**Comment by gusfcarvalho** [comment]
as stated in the docs, `dataFrom` is expecting a JSON as a secret. If you want to bring up text values, you should use `data`:

```
data:
- secretKey: my-k8s-secret-key
   remoteRef:
     key: try2
 ```

the difference is that, if `try2` contains a JSON, `data` will load the entire JSON in `my-k8s-secret-key`. Alternatively, `dataFrom` will parse the JSON and create multiple k8s keys (as if the whole JSON was the k8s secret definition)
