### ISSUE TITLE
scope access per namespace

### ISSUE THREAD

**Issue by moolen** [external-secrets/external-secrets#163]
kes docs: https://github.com/external-secrets/kubernetes-external-secrets#scoping-access
eso docs: https://external-secrets.io/guides-multi-tenancy/

This feature is documented but not implemented.
Basicially: with the following annotation you can limit access to certain keys.

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: team-a
  annotations:
    # annotation that defines which keys can be read
    # the annotation value is a regular expression
    external-secrets.io/permitted-key-name: "a/development/*"
```

It this a footgun? maybe.
In a perfect world you would have one SecretStore per team with a `role` that restricts access to particular secrets. But managing one SecretStore per team or namespace in big clusters is a PITA. This would make maintenance way simpler. just set a annotation instead of managing IAM roles and SecretStores. The target audience would be no-ops or low-ops teams/orgs that just want simple secret sync without the overhead of managing infra around that.

Implementing this is a low-hanging fruit:
1. get ns
2. compare regexp
3. proceed or return err

WDYT?

**Comment by knelasevero** [comment]
I actually like this. But I understand that it could be a footgun. At least for "encouraging" this. What downsides do you see around it?

**Comment by mcavoyk** [comment]
Another potential method is `ClusterSecretStore` could support a `namespaceSelector` field which could match namespaces by name, label selector, regex or other methods. This would allow a cluster administrator to setup ClusterSecretStore(s) with the necessary permissions and grant certain namespaces permission to use this Secret provider.

**Comment by moolen** [comment]
Hmm, after thinking a bit about it I feel like eso should not do access control. It should be done (1) on the provider integration side (managing roles and permissions on the provider side) and (2) via RBAC (who is allowed to create an ES) including tools that allow more fine-grained control like kyverno and OPA. Maybe it's enough to add more documentation and examples on how to use these tools for fine-grained policing.

I think i'm gonna remove the above annotation from the docs :sweat_smile:

+1 for the `namespaceSelector`, this could be along the lines of the [NetworkPolicy](https://kubernetes.io/docs/concepts/services-networking/network-policies/#networkpolicy-resource) resource - tho that might be hard to understand due to the two-way binding.

**Comment by knelasevero** [comment]
This makes me remember this comment: https://github.com/external-secrets/external-secrets/issues/19#issuecomment-756857827

**Comment by moolen** [comment]
Maybe we can implement something like this for the first iteration and add regex or other matches afterwards

```yaml
apiVersion: external-secrets.io/v1alpha1
kind: ClusterSecretStore
metadata:
  name: example
spec:
  controller: dev
  provider: {} # [...]
  
  # only valid for ClusterSecretStore
  # this is a list of conditions.
  # At least one condition MUST be true for the controller to process a ExternalSecret (logical OR)
  # When the list is empty a controller MUST process a ExternalSecret
  # When multiple fields within a single condition are set ALL of them must be true (logical AND)
  conditions:
  - namespaceSelector:
      matchLabels:
        team: frontend
```
