### ISSUE TITLE
unable to access oracle vault

### ISSUE THREAD

**Issue by mehdibenfeguir** [external-secrets/external-secrets#1632]
Hello everybody
I'm using instance_principals I already added  dynamic group and added policy
I installed the operator successfully
I added the secret store as following
and it was successfully created with status valid

```
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: companyvault
  namespace: external-secrets
spec:
  provider:
    oracle:
      vault: ocid1.vault.oc1.me-jeddah-1.xxxxx
      region: me-jeddah-1
```

I also added external secret and I'm sure it is containing the same naming secret in the vault

```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oci-secret
  namespace: external-secrets
spec:
  refreshInterval: 0.03m
  secretStoreRef:
    kind: SecretStore
    name: companyvault
  target:
    name: oci_gateway_url
    creationPolicy: Owner
  data:
  - secretKey: key
    remoteRef:
      key: oci_gateway_url
```

but it is saying 
> Service error:NotAuthorizedOrNotFound. Authorization failed or requested resource not found.. http status code: 404. Opc

Also please note that 
- The defined vault ocid is accesible on k8s cluster using oci cli command

And please  let me know 
- what is the default compartment in which your operator searches the vault if I have multiple compartment in OCI
- why there is no way to define the compartment in which our vault is created
