### ISSUE TITLE
Limitations implementing Multi Tenancy in GKE using Workload Identity

### ISSUE THREAD

**Issue by marandalucas** [external-secrets/external-secrets#1634]
Hi everyone! Thank you so much for this useful tool.

We already have the ESO working properly with Workload Identity in our environment based in GKE/GCE. We were reading the following documentation (https://external-secrets.io/v0.6.0/api/secretstore/) in order to create a SecretStore for each namespace and use role configuration, but unfortunately, We couldn't find it in the documentation for GCP.

Our idea is to have different IAM Service Accounts for each namespace to only retrieve a set of secrets.

For now, we only found other solutions creating "ClusterSecretStore" and applying policies with Kyvernmo or Open Policy Agent.

The security threat that we are taking into consideration is that the ESO POD can read all the secrets without any restriction... So, any ExternalSecret can retrieve any secrets in our project.

There is a limitation for GCP? Any suggestion?

Thank you so much

**Comment by marandalucas** [comment]
We are trying to find the same implementation as AWS has, but unfortunately for GCP, it's not clear at all in the documentation we can't use SecretStore with roles.

https://external-secrets.io/v0.6.0/provider/aws-secrets-manager/

![image](https://user-images.githubusercontent.com/19186306/195571924-8ff00fdf-f614-40c5-bd44-d5cbd3326055.png)

**Comment by moolen** [comment]
You can simply use GCP WorkloadIdentity (see [GCP docs](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity#authenticating_to)). But you need to create a GCP IAM Role and GCP Service Account per tenant and allow service accounts to use that role.
In a `SecretStore` you just point to a Kubernetes `ServiceAccount` in the tenants namespace. ESO will use that service account to authenticate with GCP and will just have access to a subset of secrets.

for each namespace:
* create a GCP Role that allows access to a particular area in SM
* create GCP Service Account that uses :point_up_2: role and allows using workloadIdentity
* create kubernetes service account with the well-known annotation
* create SecretStore that points to the new service account

Here's an example:
```yaml
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: example
  namespace: tenant-a
spec:
  provider:
    gcpsm:
      projectID: example
      auth:
        workloadIdentity:
          # ...
          serviceAccountRef:
            name: tenant-a
            namespace: tenant-a
```

I hope that helps.
