### ISSUE TITLE
SecretStore Workload Identity doesn't work with Google Anthos Clusters

### ISSUE THREAD

**Issue by Jumwah** [external-secrets/external-secrets#1641]
Google Anthos clusters do no have the same location pattern as traditional GKE on GCP clusters.  The SecretStore GCPSM provider allows Workload Identity for access to [GSM via service accounts](https://external-secrets.io/v0.6.0/provider/google-secrets-manager/#using-service-accounts-directly), however the structure assumes specific values are required to construct the fixed cluster location - as then used in the code: https://github.com/external-secrets/external-secrets/blob/c6d09b004cc703a7ac37a515b102e755c82a81cb/pkg/provider/gcp/secretmanager/workload_identity.go#L121-L124

However, this is not at all structured the same for Anthos cluster.  e.g. for Anthos on AWS the location looks like this:
```
projects/<id>/locations/<region>/awsClusters/<cluster_name>
```
The workload identify config looks like the following:
```
workloadIdentityConfig:
  identityProvider: //gkemulticloud.googleapis.com/projects/<id>/locations/<region>/awsClusters/<cluster_name>
  issuerUri: https://<region>-gkemulticloud.googleapis.com/v1/projects/<id>/locations/<region>/awsClusters/<cluster_name>
  workloadPool: <gcp_project_name>.svc.id.goog
````
The only currently work around is to use the pre-generated [service account JSON](https://external-secrets.io/v0.6.0/provider/google-secrets-manager/#gcp-service-account-authentication) key which is far from ideal.
