### ISSUE TITLE
Failure to retrieve secrets from Oracle Cloud vault

### ISSUE THREAD

**Issue by alexdyas** [external-secrets/external-secrets#1648]
Hello,

External Secrets version:

```
NAME                    NAMESPACE               REVISION        UPDATED                                         STATUS          CHART                   APP VERSION
external-secrets        external-secrets        1               2022-10-18 16:35:04.564335068 +0200 CEST        deployed        external-secrets-0.6.0  v0.6.0
```

Error seen in External secrets controller log:

`{"level":"error","ts":1666168678.7488923,"logger":"controllers.ExternalSecret","msg":"could not get secret data from provider","ExternalSecret":"external-secrets/example","SecretStore":"external-secrets/example","error":"Service error:NotAuthorizedOrNotFound. Authorization failed or requested resource not found.. http status code: 404. Opc ","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:121\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:320\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:234"}`

Installation steps:

`helm install external-secrets external-secrets/external-secrets -n external-secrets --create-namespace`

Kubernetes YAML:

```
apiVersion: v1
kind: Secret
metadata:
  name: oracle-secret
  labels:
    type: oracle
type: Opaque
stringData:
  privateKey: |
    -----BEGIN PRIVATE KEY-----
      <redacted private key taken from OCI API key>
    -----END PRIVATE KEY-----
  fingerprint: <redacted fingerprint taken from OCI API key>
```

```
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: example
spec:
  provider:
    oracle:
      vault: <redacted ocid of vault containing secret>
      region: <redacted string name of OCI region>
      auth:
        user: <redacted ocid of OCI user>
        tenancy: <redacted ocid of OCI tenancy>
        secretRef:
          privatekey:
            name: oracle-secret
            key: privateKey
          fingerprint:
            name: oracle-secret
            key: fingerprint
```

```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example
spec:
  refreshInterval: 0.03m
  secretStoreRef:
    kind: SecretStore
    name: example
  target:
    name: TestSecret02                                       # <- ? Name of secret to create in K8s cluster?
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: <redacted ocid of secret to fetch from vault>   # <- ? Not clear what this should be?
```

As you can see I am not entirely clear on all the fields, this is probably the source of the problem.

Is there a specific policy that needs to be added to OCI to allow reading of secrets through the API? My user can read and write secrets in the compartment I'm working in.

Any advice gratefully received, thanks.

[Edit - additional]

Additional note - configuring the same authentication details in my `~/.oci/config` and executing the following oci cli command _does_ give me the contents of the secret :

`oci secrets secret-bundle get --profile alex --raw-output --secret-id <redacted ocid of secret to fetch from vault> --query "data.\"secret-bundle-content\".content" | base64 -`

**Comment by moolen** [comment]
I would suggest double checking the secret-name, vault id and tenancy and trying to start with `spec.data[]` to fetch a secret.

```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: example
  target:
    name: example-test-secret
    creationPolicy: Owner
  data:
    - secretKey: example
      remoteRef:
        # should be the same from:
        # oci secrets secret-bundle get --secret-name {this} 
        key: <user-friendly name of secret>
        version: LATEST # or CURRENT, PENDING, PREVIOUS, DEPRECATED
```

**Comment by alexdyas** [comment]
Hi @moolen,

Thanks for the quick reply and the suggestions.

I now have it working with the following:

```yaml
apiVersion: external-secrets.io/v1beta1                         
kind: ExternalSecret                                            
metadata:                                                       
  name: example                                                 
spec:                                                           
  refreshInterval: 0.03m               
  secretStoreRef:                                               
    kind: SecretStore                                           
    name: example 
  target:                                                       
    name: testsecret03            # <- Fixed to k8s compatible name
    creationPolicy: Owner                                       
  data:                                                         
    - secretKey: example                                        
      remoteRef:                                                
        key: testsecret03         # <- String name of secret stored in OCI                              
        version: LATEST                                         
```
Cheers!

Issue can be closed.
