### ISSUE TITLE
Advanced Template with GCP Provider the value always is empty (HELM ISSUE! Scape brackets {{ }} )

### ISSUE THREAD

**Issue by marandalucas** [external-secrets/external-secrets#1664]
**Describe the solution you'd like**
Hi folks! We are trying to use Advanced templating, following the next links:

- https://external-secrets.io/v0.6.0/guides/templating/
- https://github.com/external-secrets/external-secrets/issues/1402
 
Our version of External secrets is v0.6.0. 
We have tried using Injection directly and also "templateFrom". Unfortunately, we couldn't create the secret from the GCP Secret Value. When the external secret tool creates a new secret, this one the password value that should be injected is empty.

We couldn't see anything in the traces/logs apparently everything it's working properly...
Is there something that we are missing?

**Give us examples of the outcome**
Following the example of @dllegru in the issue 1402 we are going to use the same manifests to avoid any misconfiguration or something like that.

**- Stored GCP Secret Manager value to retrieve "my-sa-creds":**
```
{
  "type": "service_account",
  "project_id": "project-0123e456",
  "private_key_id": "abc0123abc",
  "private_key": "-----BEGIN PRIVATE KEY-----\value",
  "client_email": "service@testing-0123e456.iam.gserviceaccount.com",
  "client_id": "000000",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/iam.gserviceaccount.com"
}
```

**- ExternalSecret object used:**
```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: thanos-spike
  namespace: monitoring
spec:
  secretStoreRef:
    kind: SecretStore
    name: gcp-secret-manager

  refreshInterval: 24h

  target:
    name: thanos-spike
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      type: Opaque
      data:
        thanos-store.yaml: |
          type: GCS
          config:
            bucket: thanos-testing-123a123
            service_account: |-
              {{ .sacreds }}

  data:
    - secretKey: sacreds
      # GCP secret details
      remoteRef:
        key: my-sa-creds
```

**- Afterwards k8s secret is generated, and the resulting value is empty...**
`{"level":"info","ts":1666687342.250567,"logger":"controllers.ExternalSecret","msg":"reconciled secret","ExternalSecret":"monitoring/thanos-spike","SecretStore":"monitoring/gcp-secret-manager"}`

```
kubectl get secret thanos-spike -o yaml                                     
apiVersion: v1
data:
  thanos-store.yaml: dHlwZTogR0NTCmNvbmZpZzoKICBidWNrZXQ6IHRoYW5vcy10ZXN0aW5nLTEyM2ExMjMKICBzZXJ2aWNlX2FjY291bnQ6IHwtCiAgICAK
```

```
echo -n "dHlwZTogR0NTCmNvbmZpZzoKICBidWNrZXQ6IHRoYW5vcy10ZXN0aW5nLTEyM2ExMjMKICBzZXJ2aWNlX2FjY291bnQ6IHwtCiAgICAK" |base64 -d
type: GCS
config:
  bucket: thanos-testing-123a123
  service_account: |-
```

**Observations (Constraints, Context, etc):**
We are trying to figure out what's going on...
Does anyone know?

**Comment by gusfcarvalho** [comment]
hi @marandalucas ! The first thing that I would try to do is to check if the `sacreds` alone can be fetched. the other thing that I would like you to try is to set `deletionPolicy: Retain`, and see what happens there.

**Comment by marandalucas** [comment]
@gusfcarvalho Thank you so much for your fast response!

- Firstly, I have tried to retrieve the `sacreds` alone and works properly, the secret has been fetched with the proper value.
- Secondly, I have changed the deletionPolicy to Retain following your recommendations, and now works well.

```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: thanos-spike
  namespace: monitoring
spec:
  secretStoreRef:
    kind: SecretStore
    name: gcp-secret-manager

  refreshInterval: 24h

  target:
    name: thanos-spike
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      type: Opaque
      data:
        thanos-store.yaml: |
          type: GCS
          config:
            bucket: thanos-testing-123a123
            service_account: |-
              {{ .sacreds }}

  data:
    - secretKey: sacreds
      # GCP secret details
      remoteRef:
        key: my-sa-creds
```



```
echo -n "dHlwZTogR0NTCmNvbmZpZzoKICBidWNrZXQ6IHRoYW5vcy10ZXN0aW5nLTEyM2ExMjMKICBzZXJ2aWNlX2FjY291bnQ6IHwtCiAgICB7CiAgInR5cGUiOiAic2VydmljZV9hY2NvdW50IiwKICAicHJvamVjdF9pZCI6ICJwcm9qZWN0LTAxMjNlNDU2IiwKICAicHJpdmF0ZV9rZXlfaWQiOiAiYWJjMDEyM2FiYyIsCiAgInByaXZhdGVfa2V5IjogIi0tLS0tQkVHSU4gUFJJVkFURSBLRVktLS0tLVx2YWx1ZSIsCiAgImNsaWVudF9lbWFpbCI6ICJzZXJ2aWNlQHRlc3RpbmctMDEyM2U0NTYuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLAogICJjbGllbnRfaWQiOiAiMDAwMDAwIiwKICAiYXV0aF91cmkiOiAiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tL28vb2F1dGgyL2F1dGgiLAogICJ0b2tlbl91cmkiOiAiaHR0cHM6Ly9vYXV0aDIuZ29vZ2xlYXBpcy5jb20vdG9rZW4iLAogICJhdXRoX3Byb3ZpZGVyX3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vb2F1dGgyL3YxL2NlcnRzIiwKICAiY2xpZW50X3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vcm9ib3QvdjEvbWV0YWRhdGEveDUwOS9pYW0uZ3NlcnZpY2VhY2NvdW50LmNvbSIKfQo=" |base64 -d

type: GCS
config:
  bucket: thanos-testing-123a123
  service_account: |-
    {
  "type": "service_account",
  "project_id": "project-0123e456",
  "private_key_id": "abc0123abc",
  "private_key": "-----BEGIN PRIVATE KEY-----\value",
  "client_email": "service@testing-0123e456.iam.gserviceaccount.com",
  "client_id": "000000",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/iam.gserviceaccount.com"
}

```
