### ISSUE TITLE
function "pkcs12cert" not defined

### ISSUE THREAD

**Issue by gnubibi33** [external-secrets/external-secrets#1666]
Hello,

I have followed your doc about adding TLS in secrets https://external-secrets.io/v0.5.9/guides-templating/ (Extract Keys and Certificates from PKCS#12 Archive) but I am getting a "function "**pkcs12cert" not defined**" when templating Helm Chart.

Looks like I am not alone to have this issue : https://stackoverflow.com/questions/73805122/function-pkcs12cert-not-defined-for-externsecrets-in-helm-chart

Any idea about what to do ?

Thx

**Comment by moolen** [comment]
Do you use helm to create ExternalSecret resources? In this case you would need to escape the template literals so the resource gets created correctly.
Where do you see the error, what command do you execute?

**Comment by gnubibi33** [comment]
Yes helm is used (in fact argocd)  to deploy app/ressources

My helm file : 

```
{{- if .Values.externalsecret_tls.enabled -}}
{{- $fullName := include "retailer-front.fullname" . -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $fullName }}-tls
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcpsm-secret
  target:
    name: {{ $fullName }}-tls
    # this is how the Kind=Secret will look like
    template:
      type: kubernetes.io/tls
      engineVersion: v2
      data:
        tls.crt: "{{ .Values.externalsecret_tls.name  | pkcs12cert }}"
        tls.key: "{{ .Values.externalsecret_tls.name  | pkcs12key }}"

  data:
  # this is a pkcs12 archive that contains
  # a cert and a private key
  - secretKey: {{ .Values.externalsecret_tls.name }}
    remoteRef:
      key: {{ .Values.externalsecret_tls.key }}
{{- end }}
```
Helm template . -f values.yaml is returning function "pkcs12cert" not defined


With this one, noe error, but it's not doing what I want :)

```
        tls.crt: "{{ .Values.externalsecret_tls.name }} | {{`pkcs12cert`}}"
        tls.key: "{{ .Values.externalsecret_tls.name }} | {{`pkcs12key`}}"
```
