### ISSUE TITLE
Find and extract on one secret

### ISSUE THREAD

**Issue by EnriqueLop** [external-secrets/external-secrets#1673]
**Describe the solution you'd like**
I would like to be able to use [ExternalSecretFind](https://external-secrets.io/v0.6.0/spec/#external-secrets.io/v1beta1.ExternalSecretFind) parameters and extract json values the same way as [ExternalSecretDataRemoteRef](https://external-secrets.io/v0.6.0/spec/#external-secrets.io/v1beta1.ExternalSecretDataRemoteRef) does.

I would like to get secret based on secret name and tags.

**Context**
We would like to use [multi-tenancy](https://external-secrets.io/v0.6.0/guides/multi-tenancy/) approach with one IAM user per cluster to read secrets. Documentation propose to use kyverno to control naming convenction to fetch secrets. 
The approach was using this naming convention for secrets: `clusterName-namespaceName-secretName`. 
Using only secrets name to filter secrets could provoke into security vulnerabilities if namespace and secrets name collide. 

Here it is and example where namespace and secret name are different but external secret name matches and kyverno policy will allow the creation of this secrets:
|                          | Example 1               | Example 2               |
|--------------------------|-------------------------|-------------------------|
| Namespace Name           | ns1                     | ns1-foo                 |
| SecretName               | foo-bar                 | bar                     |
| External secret to fetch | clusterName-ns1-foo-bar | clusterName-ns1-foo-bar |

Adding tag filtering to get externalSecrets provides another security mechanism but I have not been able to extract values from the secret. 

**What is the added value?**
This functionality merges ExternalSecretFind search capability allowing the external-secret to be extracted into k8s-secret.

**Give us examples of the outcome**
Input
```
dataFrom:
- findExtract: # This parameter is invented.
    name:
      regexp: "^clusterName-ns1-foo-bar"
    tags:
      namespace: ns1
      secret-name: foo-bar
```
Describe secret output:
```
Name:         foo-bar
Namespace:    ns1
Type:  Opaque

Data
====
password:  15 bytes
username:  7 bytes
```
As you can see the only difference is that the secret properties are extracted into `data.password` and `data.username` instead of `data.clusterName-ns1-foo-bar` (using find)

**Observations:**
There may be a way to fix this, but I haven't found it.

Thank you!

**Comment by gusfcarvalho** [comment]
hey @EnriqueLop ! Thanks for bringing this up! How would a collision in the json definition within the underlying secret values be handled? (i.e. two secrets being found with `username` and `password`)

**Comment by gusfcarvalho** [comment]
If it's a find one operation, why not just using `extract`? I'm not sure what the `regexp` would add value here, besides giving a lot of headache (unlikely mongoDB, we cannot guarantee that the first element of our `findOne` would always be the same).

**Comment by EnriqueLop** [comment]
I can use `extract` to get a secret based on its name but then I will find the problem shown above about delegating access management to a string. The best solution I have found is using "/" as separator. This character is not allowed to be used as k8s resource name and will allow me to use `extract` functionality.

I would like to get a secret using name and tags and be able to access to properties using .data.username. instead of .data.clusterName-ns1-foo-bar and then parse its value.

As you have mention in case #464  we would need dynamic keys. Using `extract` works for it, but when using `find` I get the name of the secret as secret property. 

In mongoDB `findOne` returns the first one that matches the criteria and it is developers responsibility to control it.

Related to using other formats apart from json I think GetSecretMap only works for json (at least in AWS)
https://github.com/external-secrets/external-secrets/blob/8cce1ad284a8b4ac018cf17f6c2dd9c3eb9fcf67/pkg/provider/aws/secretsmanager/secretsmanager.go#L273-L280

I will try to develop a POC to show you my approach.

Thank you!

**Comment by gusfcarvalho** [comment]
> I can use extract to get a secret based on its name but then I will find the problem shown above about delegating access management to a string. The best solution I have found is using "/" as separator. This character is not allowed to be used as k8s resource name and will allow me to use extract functionality.

Regular expressions are available in kyverno since 1.3.6... what's exactly your issue in trying to scope down to the string? Also, have you considered Gatekeeper instead of kyverno? You would have more flexibility to create a dynamic validation based on the name...


> I would like to get a secret using name and tags and be able to access to properties using .data.username. instead of .data.clusterName-ns1-foo-bar and then parse its value.
> As you have mention in case https://github.com/external-secrets/external-secrets/issues/464 we would need dynamic keys. Using extract works for it, but when using find I get the name of the secret as secret property.

There is a misunderstanding here around the feature itself. `dataFrom.find` will search for `names` OR `tags`, in that order. It's not an `anded` operation. It will return multiple secrets with no schema guaranteed (unlike GetSecretMap).


If it's an access control issue and you cannot change to gatekeeper, you can get get the information from the secret (if you know it's going to be one) like this:

```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: change-me
    kind: SecretStore
  target:
    name: my-secret-using-find
    template:
        data:
          username: {{ (.temp | fromJson).username }}
          password: {{ (.temp | fromJson).password}}
  dataFrom:
  - find:
      name:
        regexp: "my/well/known/path/to/my/secret/with/slashes"
    rewrite:
    - regexp:
        source: "my/well/known/path/to/my/secret/with/slashes"
        target: temp
```

this will find any number of external secrets you have and replace it with the content from the well known name that you have. (and will overwrite any collisions).


> In mongoDB findOne returns the first one that matches the criteria and it is developers responsibility to control it.

we cannot guarantee that the first secret returned in the first provider call to be equal to the first secret returned in the next provider call. The developer won't be able to do anything about it - the information will just keep changing between the possible results list.
