### ISSUE TITLE
Use golang template to extract fields from Base64 encoded YAML

### ISSUE THREAD

**Issue by akafazov2** [external-secrets/external-secrets#1674]
**Describe the solution you'd like**
I have ExternalSecret with target Kubeconfig secret which contains the kubeconfig (YAML) in Base64. I want to create a target secret, which contains only one of the sub-fields from the source YAML. Is there way to do this using golang templates?

**Comment by moolen** [comment]
for the sake of this example let's use the following yaml (this would be your kubeconfig)

```yaml
foo: bar
baz:
  bang:
    boo: nested
```

```yaml
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: fake
spec:
  provider:
    fake:
      data:
      - key: "/foo/bar"
        # this is the base64 encoded yaml file from above
        value: "Zm9vOiBiYXIKYmF6OgogIGJhbmc6CiAgICBib286IG5lc3RlZA=="
        version: "v1"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example
spec:
  refreshInterval: "10s"
  secretStoreRef:
    name: fake
    kind: ClusterSecretStore
  target:
    name: "fart"
    template:
      data:
        my_nested_val: |
          {{ $obj := .foo_bar_v1 | b64dec | fromYaml -}}
          {{ $obj.baz.bang.boo }}
  data:
  - secretKey: foo_bar_v1
    remoteRef:
      key: /foo/bar
      version: v1
```

When applying above i expect the es to be ready:
```
$ kubectl get es
NAME      STORE   REFRESH INTERVAL   STATUS         READY
example   fake    10s                SecretSynced   True
```
...and the secret should contain a value
```
$ kubectl get secret fart -o yaml | grep my_nested -C 2
apiVersion: v1
data:
  my_nested_val: bmVzdGVkCg==
immutable: false
kind: Secret
```
...and that value is from the nested field.
```
$ echo bmVzdGVkCg== | base64 -d
nested
```

I hope that helps.
