### ISSUE TITLE
External Secrets is unable to assume a AWS role in an K8s EC2 cluster

### ISSUE THREAD

**Issue by steve-fraser** [external-secrets/external-secrets#1691]
Currently external secrets is unable to assume an AWS role

role 1 is a InstanceProfile -> role 2 is a role with a trust policy allowing role 1

Role 1 permission
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "",
            "Effect": "Allow",
            "Action": "sts:*",
            "Resource": "arn:aws:iam::<>:role/ec2-test-cluster-external-secrets"
        }
    ]
}
```

Role 1 trust policy
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "",
            "Effect": "Allow",
            "Principal": {
                "Service": "ec2.amazonaws.com"
            },
            "Action": [
                "sts:AssumeRole",
                "sts:TagSession",
                "sts:SetSourceIdentity"
            ]
        }
    ]
}
```
Role 2 trust policy
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::<>:role/capa-prod-eu-corp-mgmt-eks"
            },
            "Action": "sts:AssumeRole"
        }
    ]
}
```

```
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  generation: 2
  name: profiles-aws-secrets-manager
  provider:
    aws:
      region: eu-west-2
      role: arn:aws:iam::<id>:role/ec2-test-cluster-external-secrets
      service: SecretsManager
status:
  conditions:
  - lastTransitionTime: "2022-11-01T18:28:26Z"
    message: unable to validate store
    reason: ValidationFailed
    status: "False"
    type: Ready
```

```
AccessDenied: User │
│ : arn:aws:sts::<>:assumed-role/capa-node-prod-eu-corp-mgmt-eks/i-035b3e87c775bc47e is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::<>:role/ec2-test-cluster-external-secrets  
```
