### ISSUE TITLE
TLS secret from webhook JSON

### ISSUE THREAD

**Issue by EutiziStefano** [external-secrets/external-secrets#1697]
**Describe the solution you'd like**
I would like to sync secrets of kind tls from a webook secret store, the api return a json with crt and key fields

**Give us examples of the outcome**

These are the configurations:

API JSON output:
```
{
  "cert": {
    "crt": "-----BEGIN CERTIFICATE----- ..... -----END CERTIFICATE-----\n",
    "key": "-----BEGIN PRIVATE KEY----- ....-----END PRIVATE KEY-----\n"
   },
  "diff_ore": "8759",
  "esito": "Certificato esistente"
}
```

Cluster Secret Store:
```
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: webhook-ca-api
spec:
  provider:
    webhook:
      url: "http://10.150.12.212:3000/api/getCertificate?fqdn={{ .remoteRef.key }}"
      result:
        jsonPath: "$.cert"
      headers:
        Content-Type: application/json  
```

External Secret:
```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret-example.com
spec:
  refreshInterval: "5m"
  secretStoreRef:
    name: webhook-ca-api
    kind: ClusterSecretStore
  target:
    name: tls-example.com
    template:
      type: kubernetes.io/tls
      data:
        tls.crt: "{{ .cert.crt }}"
        tls.key: "{{ .cert.key }}"
  data:
  - secretKey: cert
    remoteRef:
      key: example.com
```  
  

Output:
```
{"level":"error","ts":1667425694.8525326,"logger":"controllers.ExternalSecret","msg":"could not get secret data from provider","ExternalSecret":"default/external-secret-testacme.actalis-ca.it","SecretStore":"/webhook-ca-api-actalis","error":"failed to get response (wrong type: map[string]interface {})","stacktrace":"github.com/external-secrets/external-secrets/pkg/controllers/externalsecret.(*Reconciler).Reconcile\n\t/home/runner/work/external-secrets/external-secrets/pkg/controllers/externalsecret/externalsecret_controller.go:261\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:121\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:320\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:234"}
```

**Observations (Constraints, Context, etc):**

Maybe I made some errors in the configuration, is it possible to do what I ask?

**Comment by gusfcarvalho** [comment]
Yes, it should be possible to get it. And yes, you do have a configuration error!

If you want to download a set of keys with webhook provider, you need to use `dataFrom` structure:
```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret-example.com
spec:
  refreshInterval: "5m"
  secretStoreRef:
    name: webhook-ca-api
    kind: ClusterSecretStore
  target:
    name: tls-example.com
    template:
      type: kubernetes.io/tls
      data:
        tls.crt: "{{ .crt}}"
        tls.key: "{{ .key }}"
  dataFrom:
  - extract:
       key: example.com
```

That should make it work :)
