### ISSUE TITLE
[GITLAB] 

### ISSUE THREAD

**Issue by allanian** [external-secrets/external-secrets#1706]
Hello, can you help me with this issue, was trying to use external secrets with gitlab provider.
Getting this error, when use dataFrom:
```
kubectl -n default describe externalsecret
Events:
  Type     Reason        Age                   From              Message
  ----     ------        ----                  ----              -------
  Warning  UpdateFailed  21s (x18 over 8m14s)  external-secrets  unable to unmarshal secret: invalid character '\'' looking for beginning of value
```
my variables "TEST" in gitlab:
{
  "username": "test",
  "password": "test12",
  "TELEMETRY": "false",
}

k8s manifests:
```
---
apiVersion: v1
kind: Secret
metadata:
  name: 'es-gitlab-secret'
  namespace: "default"
  labels: 
    type: gitlab
type: Opaque 
stringData:
  token: "xxxxxxxxxxxxxxxxx"
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: 'es-gitlab-secretstore'
  namespace: "default"
spec:
  provider:
    gitlab:
      url: https://test.gitlab.net/ 
      auth:
        SecretRef:
          accessToken:
            name: 'es-gitlab-secret'
            key: token
      projectID: "52"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: 'es-gitlab-es'
  namespace: "default"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: 'es-gitlab-secretstore'
  target:
    name: 'es-gitlab-env'
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: TEST
```
