### ISSUE TITLE
Rewriting Keys does not work properly

### ISSUE THREAD

**Issue by giniman0711** [external-secrets/external-secrets#1713]
**Describe the solution you'd like**
I would like to import secrets with the same JSON key into a Kubernets secret without conflicts. However, there seems to be a problem setting the target key.

**What is the added value?**
```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-mattermost-urls
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azurekeyvault
    kind: ClusterSecretStore
  target:
    name: {{ .Release.Name }}-mattermost-urls
  dataFrom:
  - extract:
      key: secret-monitor-mattermost-webhookurl
    rewrite:
    - regexp:
        source: "(.*)"
        target: "$1_MONITOR"
```

- **$1_** at the beginning results in an error
- **$1-** works
- **TEXT_$1** works
- **TEXT_$1_** results in **TEXT_**

**Give us examples of the outcome**
` Warning  UpdateFailed  13s (x246 over 2d2h)  external-secrets  Secret "av-monitor-mattermost-urls" is invalid: data[]: Invalid value: "": a valid config key must consist of alphanumeric characters, '-',  ││ '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+') `

It looks like the underscore right after the $1 doesn't work.
