### ISSUE TITLE
Where to find static deployment manifests'?

### ISSUE THREAD

**Issue by MousaZeidBaker** [external-secrets/external-secrets#1715]
The [docs](https://github.com/external-secrets/external-secrets/tree/main/deploy/manifests) says 

> manifests will be automatically generated and published as an asset attached to the GitHub release

but I can't seem to find them. I can however generate them myself with `make manifests`.

I want to deploy `external-secrets` in a dev env (without helm) using static manifests in a kustomize file similar to the following:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-secrets
resources:
  - https://github.com/external-secrets/external-secrets/releases/download/v0.6.1/external-secrets.yaml
```
