### ISSUE TITLE
Deleting a key from the external secret manifest is not propagated into the k8s secret

### ISSUE THREAD

**Issue by yousef-salman** [external-secrets/external-secrets#1721]
When a key is deleted from the external secret manifest, the only way to have this change propagated into the k8s secret is to delete the secret and let the external secret create it again. Whereas, adding a key works perfectly.

Whenever the external secret manifest is modified, the user then intended to have this change. Implementing this would keep the external secret and the secret it generates consistent.

Deploying this manifest (after having the AWS secret manager keys in place):
```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: my-external-secret
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /aws/my-key-1
      secretKey: MY_KEY_1
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /aws/my-key-2
      secretKey: MY_KEY_2
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: secret-manager
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      data:
        MY_KEY_1: '{{ .MY_KEY_1 }}'
        MY_KEY_2: '{{ .MY_KEY_2 }}'
      engineVersion: v2
```

and then editing the manifest by deleting any of the keys as in here:
```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: my-external-secret
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /aws/my-key-1
      secretKey: MY_KEY_1
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: secret-manager
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      data:
        MY_KEY_1: '{{ .MY_KEY_1 }}'
      engineVersion: v2
```

would change nothing in the secret key (would still have MY_KEY_1 & MY_KEY_2) unless the secret is deleted, only then, the newly created secret will have the right data (MY_KEY_1 only).

I tested this with version 0.5.8 and version 0.6.1 and both showed the same behaviour.

**Comment by gusfcarvalho** [comment]
hey @yousef-salman ! Is this issue only when using templates?

**Comment by yousef-salman** [comment]
Yes, correct. Removing
```
data:
        MY_KEY_1: '{{ .MY_KEY_1 }}'
        MY_KEY_2: '{{ .MY_KEY_2 }}'
```
from the above, the deletion of a "remoteRef" element gets propagated automatically into the k8s secret

**Comment by daftping** [comment]
Just want to piggyback on this issue with a similar use case
Renamed secret key gets merged with the existing secret instead of replaced
```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
...
spec:
  target:
    name: test
    template:
      data:
        foo: >-
          foo: foo
 ...
```
```
kubectl get secrets test -o  json | jq .data
{
  "foo": "Zm9vOiBmb28="
}
````

```
...
    template:
      data:
        bar: >-
          bar: bar
...
```
```
kubectl get secrets test -o  json | jq .data
{
  "bar": "YmFyOiBiYXI=",
  "foo": "Zm9vOiBmb28="
}
```

**Comment by gaeljw** [comment]
I've got same issue but without using templates.

```yaml
# ExternalSecret
spec:                                                                                                                                                                                                                                     
   data: []                                                                                                                                                                                                                                
   refreshInterval: 1h                                                                                                                                                                                                                     
   secretStoreRef:                                                                                                                                                                                                                         
     kind: ClusterSecretStore                                                                                                                                                                                                              
     name: ccc                                                                                                                                                                                                         
   target:                                                                                                                                                                                                                                 
     creationPolicy: Owner                                                                                                                                                                                                                 
     deletionPolicy: Retain                                                                                                                                                                                                                
     name: xxx-secrets 
```

But the actual secret still contains some keys:

```yaml
apiVersion: v1
data:
  OLD_KEY: ...
immutable: false
kind: Secret
metadata:
  name: xxx-secrets
  ownerReferences:
  - apiVersion: external-secrets.io/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: ExternalSecret
    name: xxx-secrets-ref
type: Opaque
```
