### ISSUE TITLE
[Documentation] - Include `audience` field as part of Hashicorp Vault Kubernetes Auth

### ISSUE THREAD

**Issue by luis-garza** [external-secrets/external-secrets#1723]
**Describe the solution you'd like**

There are scenarios where using Hashicorp Vault [Kubernetes Auth](https://external-secrets.io/v0.6.1/provider/hashicorp-vault/#kubernetes-authentication), one needs to use a JWT with custom audience.
Right now one only can define a JWT through a static secret which could not be used in a GitOps deployment, or through service account name which can't customize JWT

**What is the added value?**

Enabling TokenRequest API to fetch service account tokens in Hashipotp Vault Kubernetes Auth will increase the scenarios where this  secure auth method could be used.

**Observations (Constraints, Context, etc):**

The TokenRequest API it's being used alredy in Hashicorp Vault [JWT/OIDC Auth]( https://external-secrets.io/v0.6.1/provider/hashicorp-vault/#jwtoidc-authentication), see field `kubernetesServiceAccountToken`.

**Comment by gusfcarvalho** [comment]
Hi @luis-garza ! What eso version are you using? From 0.5.9 eso by default used token Request API when you provide a service account configuration

**Comment by luis-garza** [comment]
Hi @gusfcarvalho,
thanks for the quick response.

I'm using v0.6.1, and following the current documentation, using [Kubernetes Auth](https://external-secrets.io/v0.6.1/provider/hashicorp-vault/#kubernetes-authentication) one can't change the audience for service account JWT.

Or it is possible? Do I missing sometihng? :thinking:

**Comment by luis-garza** [comment]
Oh wait!
Even is not defined in the documentation nor API, I've played adding `audience` field and it worked! :open_mouth: 

```
...
      auth:
        kubernetes:
          mountPath: kubernetes/my-cluster
          role: my-role
          serviceAccountRef:
            name: my-service-account
            audiences:
              - vault
```

Please, would be nice if you can update the documentation to help other users.
