### ISSUE TITLE
Add sessionTokenSecretRef back to CRD for temp creds usage

### ISSUE THREAD

**Issue by jmmclean** [external-secrets/external-secrets#1724]
**Describe the solution you'd like**
Allow the usage of provider SecretsManager and ParameterStore from AWS with temporary credentials; I have been unable to create a solution for leveraging Minikube with ExternalSecrets when AWS SSO is required as I need to pass in the `source_profile` used with my local AWS credentials

More info: https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sso.html

We can ignore all the above if I do the heavy lifting to generate temporary credentials, then configure Externals secrets to use that via something like the below
```
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: cluster-secret-store-ssm
spec:
  provider:
    aws:
      region: us-east-1
      service: ParameterStore
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-ssm
            key: accessKeyId
            namespace: external-secrets
          secretAccessKeySecretRef:
            name: aws-ssm
            key: secretAccessKey
            namespace: external-secrets
          sessionTokenSecretRef:  # <----------- This was removed at some point 
            name: aws-ssm
            key: sessionToken
            namespace: external-secrets
```

**What is the added value?**
Allows a user to authenticate with AWS, create access off of credentials that expire after some elapsed time.

**Give us examples of the outcome**
Allow users to leverage tools like minikube with Tilt to perform local development for external secrets consumption

**Observations (Constraints, Context, etc):**
The `sessionTokenSecretRef` appears to have been removed at some point, which removes our ability to leverage temporary credentials. 

A discussion was opened a week ago with no responses - https://github.com/external-secrets/external-secrets/discussions/1707
