### ISSUE TITLE
[Bug] wrong refreshInterval notation External Secret with template

### ISSUE THREAD

**Issue by bastiaanv** [external-secrets/external-secrets#1750]
**Describe the solution you'd like**

When making a ExternalSecret with the template engine, it generates a Kubernetes object which does not follow the refresh interval unit.

Example:

```yaml
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: supabase-kong-secret
  namespace: '{{ .Release.Namespace }}'
spec:
  refreshInterval: 2h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: supabase-kong
    template:
      engineVersion: v2
      templateFrom:
        - configMap:
            name: supabase-kong-tpl
            items:
              - key: kong.yml
  data:
    - secretKey: anno_key
      remoteRef:
        key: supabase
        property: ANNO_KEY
    - secretKey: service_key
      remoteRef:
        key: supabase
        property: SERVICE_KEY
```

Will generate a object with the following time interval:
<img width="894" alt="Screenshot 2022-11-25 at 21 17 04" src="https://user-images.githubusercontent.com/3987804/204051708-14df18ce-6cf1-41c9-a88a-4f52f849e7e8.png">

The difference is that the time interval has the minute and second units. This is not breaking for most, but it forces ArgoCD to be stuck in a sync loop, since it detects a difference (left object in cluster, right template):

<img width="1143" alt="Screenshot 2022-11-25 at 21 11 34" src="https://user-images.githubusercontent.com/3987804/204051283-47c03287-576d-47d2-916b-c291c580ddd6.png">

**Give us examples of the outcome**

The expected outcome would be to have the Kubernetes object follow the template exactly, just like with the other external secrets without a template. Example:

```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: supabase
  namespace: '{{ .Release.Namespace }}'
spec:
  refreshInterval: 2h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: supabase
  dataFrom:
    - extract:
        key: supabase
```

Generates the following:

<img width="884" alt="Screenshot 2022-11-25 at 21 20 40" src="https://user-images.githubusercontent.com/3987804/204051977-4f4bce8c-0e4d-44b2-aad2-d2cd2e7b316d.png">
