### ISSUE TITLE
cert-controller doesn't pass readiness probe

### ISSUE THREAD

**Issue by ArsenyBelorukov** [external-secrets/external-secrets#1766]
I deployed external-secrets without Cluser* CRDs:
```
crds:
  # -- If true, create CRDs for Cluster External Secret.
  createClusterExternalSecret: false
  # -- If true, create CRDs for Cluster Secret Store.
  createClusterSecretStore: false
```
but in this case, the cert-controller doesn't pass a readiness probe:
```
[-]crd-inject failed: reason withheld
[+]validation-webhook-inject ok
healthz check failed
```
because:
```
{"level":"debug","ts":1669762555.7181904,"logger":"controller-runtime.healthz","msg":"healthz check failed","checker":"crd-inject","error":"resource not ready: clustersecretstores.external-secrets.io"}
```

As I understand the cert-controller wants to reconcile CRD clustersecretstores:
https://github.com/external-secrets/external-secrets/blob/main/cmd/certcontroller.go#L74
but it doesn't exist

**Describe the solution you'd like**
Have a cert-controller with a successful readiness probe
