### ISSUE TITLE
Enable static session name in assume-role for AWS

### ISSUE THREAD

**Issue by vadim-a-nesterov** [external-secrets/external-secrets#1794]
External-secrets configuration:

external-secrets is running in AWS EKS  multi-tenant cluster (every dev team has its namespace or several), using IRSA for service account. 
AWS account which hosts EKS cluster is 6470706619xx

Task: 
every dev team needs to reach Secrets Manager or Parameter Store in THEIR dev account, not where EKS cluster is running.

Assumption is that we create in every namespace    

apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secretsmanager
  namespace: dev-team
spec:
  provider:
    aws:
      region: us-east-1
      role: arn:aws:iam::0352427011xx:role/eso-meks-test-us
      service: SecretsManager

but different account number in role. 

And this is not working as we get error
error":"could not validate provider: 
AccessDenied: User: arn:aws:sts::6470706619xx:assumed-role/eso-test-irsa-us/1670520670204031110 is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::0352427011xx:role/eso-meks-test-us\n\tstatus code: 403

because it is role session and number here /1670520670204031110 changes for every new try to initiate a session.

And in trust policy it is not allowed to use wildcards for session name. 
``` json
 {
            "Sid": "Statement1",
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:sts::6470706619xx:assumed-role/eso-test-irsa-us/*" <-- not allowed 
            },
            "Action": "sts:AssumeRole"
 }

```

I tried variant which works, but it is uses ClusterSecretStore, which does not satisfy our needs.
``` yaml
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: secretsmanager
spec:
  provider:
    aws:
      region: us-east-1
      role: arn:aws:iam::0352427011xx:role/eso-meks-test-us
      service: SecretsManager
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: platform
```

And for this case it was possible to make trust policy
``` json
 {
            "Sid": "Statement1",
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:sts::6470706619xx:assumed-role/eso-test-irsa-us/external-secrets-provider-aws"
            },
            "Action": "sts:AssumeRole"
}
```

as now external-secrets name session external-secrets-provider-aws
by this code
	```
return stscreds.NewWebIdentityRoleProviderWithOptions(
		sts.New(sess), roleArn, "external-secrets-provider-aws", tokenFetcher), nil
```

We need to have named sessions in first variant.
