### ISSUE TITLE
Creating two ClusterSecretStore pointing to different regions in the same cluster 

### ISSUE THREAD

**Issue by rajharini** [external-secrets/external-secrets#1812]
Is there a possibility for creating two ClusterSecretStore in the same cluster where each refers to a different region of the same account? Both ClusterSecretStores will be referred to pull values for a single ExternalSecret. This will be helpful in case of a disaster. When failed over, the AWS Secrets Manager or Azure Key vaults go into read-only mode. But if we have to change the values, it would be helpful if we could refer to a region where the write permissions are also enabled.

**Comment by moolen** [comment]
Hey, yeah there is a region field in the provider spec, that should do it. 

There is a example yaml spec at the top of the page here: https://external-secrets.io/v0.7.0/provider/aws-secrets-manager/

**Comment by rajharini** [comment]
Thanks for the quick reply!
This is how it is present in the cluster with a single ClusterSecretStore
`
spec:
    secretStoreRef:
        name: secretstore-aws
        kind: ClusterSecretStore
    data:
    - secretKey: <key 1>
      remoteRef:
          key: <secret name 1>
          property: <key 1>
    - secretKey: <key 2 >
       remoteRef:
          key: <secret name 2>
          property: <key 2>
`
I'm referring to two different secrets present in the same region. Say, I need the secret name 2 from a different region, how should the ExternalSecret definition be changed to refer to the secondary region?

**Comment by moolen** [comment]
The straight-forward solution would be to have the secrets with the same name in both regions:

| eu-central-1      | eu-west-1 |
| ----------- | ----------- |
| secret1      | secret1       |
| secret2   | secret2        |


With that you just need to swap out the cluster-secret-store reference:

```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "database-credentials"
spec:
  secretStoreRef:
    name: aws-sm-eu-central-1 # swap this out with a css pointing to the different region
    kind: ClusterSecretStore
```

Hope that makes sense.
