### ISSUE TITLE
PushSecret to AWS Secrets Manager: Define KMS key to use to encrypt secret

### ISSUE THREAD

**Issue by tabnul** [external-secrets/external-secrets#1817]
**Describe the solution you'd like**

At the moment it does not seem possible to define a customer managed  KMS key which should be used to encrypt a secret at rest. Is it possible to add this?

**Comment by gusfcarvalho** [comment]
I reckon this is something that would need to go to the SecretStore spec. @moolen thoughts?

**Comment by moolen** [comment]
From the [initial design](https://github.com/external-secrets/external-secrets/blob/main/design/002-pushsecret.md) we envisioned it roughly like this: 

```yaml
apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: example
  namespace: example-ns
spec:
  provider:
    aws:
      service: SecretsManager
      role: iam-role
      region: eu-central-1
      encryptionConfig: {} # Specific config for Creating Secrets on AWS
      auth: {} # ...
```

I guess it makes sense to add that there so a user is able to point to a customer managed key.

Then we just need to pass it to the `CreateSecret()` call ([docs](https://docs.aws.amazon.com/sdk-for-go/api/service/secretsmanager/#CreateSecretInput)).


```
    // The ARN, key ID, or alias of the KMS key that Secrets Manager uses to encrypt
    // the secret value in the secret. An alias is always prefixed by alias/, for
    // example alias/aws/secretsmanager. For more information, see About aliases
    // (https://docs.aws.amazon.com/kms/latest/developerguide/alias-about.html).
    //
    // To use a KMS key in a different account, use the key ARN or the alias ARN.
    //
    // If you don't specify this value, then Secrets Manager uses the key aws/secretsmanager.
    // If that key doesn't yet exist, then Secrets Manager creates it for you automatically
    // the first time it encrypts the secret value.
    //
    // If the secret is in a different Amazon Web Services account from the credentials
    // calling the API, then you can't use aws/secretsmanager to encrypt the secret,
    // and you must create and use a customer managed KMS key.
    KmsKeyId *string `type:"string"`

```
