### ISSUE TITLE
Implement PushSecrets for Kubernetes Provider

### ISSUE THREAD

**Issue by ron1** [external-secrets/external-secrets#1823]
**Describe the solution you'd like**
PushSecrets are available for Kubernetes Provider to allow pushing secrets from one cluster to other clusters. This capability provides a more flexible solution for copying secrets between clusters than the one offered by another popular project, https://github.com/kubeops/config-syncer.

**Comment by gusfcarvalho** [comment]
hi @ron1 ! are you able to run your use case with the ExternalSecrets combined with Kubernetes provider? I'm asking this because the first interaction of PushSecret will most likely be a `data` call, where I believe you would like to have a `dataFrom` in order for this feature to fully copy secrets.

**Comment by ron1** [comment]
Hi @gusfcarvalho, I'm trying to push secrets from a mgmt cluster with ESO installed to multiple downstream clusters that do not have ESO installed. I'm not sure how I could accomplish using ExternalSecrets and a Kubernetes Provider on the mgmt cluster only. 

Yes, a PushSecret `dataFrom` call would be ideal but I think I could get away with just a `data` call initially.

**Comment by sdischer-sap** [comment]
Hi everybody, 

My team and I are in need of the same capabilities and I would be willing to contribute on this. 

While investigating the code and CRD structure I found that the chosen abstraction only allows to pass the value of a secret property and a remoteKey to the client implementation. Is there are particular reason why no property name can be passed here like implemented for the ExternalSecret? As I understand e.g. in the AWS SecretManager you can pull single secret properties to k8s secret properties, but only push k8s secret properties as binary objects. 

My suggestion would be to add property as another optional attribute in remoteRef, so that by setting it you could distinguish between transfering as binary (as is) or injecting single properties in secrets. This would also align the model a bit with the ExternalSecret kind. To support namespaces we could have an optional namespace attribute in the selector (defaulting to default). 
In the azure implementation I found usage of some conventional prefixing like `key/` to change uploading behaviour based on format. We could do something similar to allow injecting a namespace for the target secret to avoid cluttering the CRD with kubernetes specifics. 

Let me put my thoughts together in an example to illustrate what I have in mind:
```
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: aws-pushed-secret
spec:
  refreshInterval: 10s
  secretStoreRefs:
    - name: secretstore-aws
      kind: SecretStore
  selector:
    secret:
      name: local-secret            # name of local secret
      namespace: local-namespace    # add namespace here for more control, default if omitted
  data:
  - match:
      secretKey: username           # property in local secret data
      remoteRef:      
        remoteKey: ext-namespace/external-secret  # reference to external secret / format in case of k8s: <namespace>/<secret-name>
        property: external-username               # optional property in the secret to fill with value / omitted when written as binary
``` 


@gusfcarvalho let me know what you think. Maybe I am missing something here.
