### ISSUE TITLE
annotations and labels not copied over to Secret from ExternalSecret

### ISSUE THREAD

**Issue by shanproofpoint** [external-secrets/external-secrets#1836]
**Describe the solution you'd like**
```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: my-test-secret
  #annotations and labels will be copied to target secret
  annotations:
    kubed.appscode.com/sync: myfunny=sunny
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: external-secrets-cluster-store
    kind: ClusterSecretStore
  target:
    name:my-test-secret
    # this is how the Kind=Secret will look like
    template:
      type: Opaque
      data:
        tls.crt: "{{ .the_Certificate }}"
        tls.key: "{{ .the_PrivateKey }}"
        ...
        ...
````

The resulting Secret does not contain the annotation:
```
annotations:
    kubed.appscode.com/sync: myfunny=sunny
```

using :
```
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: v0.7.0
```
