### ISSUE TITLE
PushSecret [Vault provider] - Multiple keys into one secret? (property, dataFrom)

### ISSUE THREAD

**Issue by Ampler92** [external-secrets/external-secrets#1840]
Hello,

I am a bit confused with the way of specifying **RemoteRef**  for **PushSecret**.

In documentation there is **RemoteRefs** [array] which expect list of **RemoteKey**

But in CRD the schema contains just **RemoteRef** [object]...

Also there is no way how to enter the property same as in **ExternalSecret**. How I can then add multiple keys into one **HashiCorp Vault** secret?

Tried the following code but it creates two separate secrets instead of two keys in one ("credentials") secret.

```
  selector:
    secret:
      name: credentials # Source Kubernetes secret to be pushed
  data:
  - match:
        secretKey: password1 # Source Kubernetes secret key to be pushed
        remoteRef:
          remoteKey: kv/data/credentials/password1 # Remote reference (where the secret is going to be pushed)
  - match:
        secretKey: password2 # Source Kubernetes secret key to be pushed
        remoteRef:
          remoteKey: kv/data/credentials/password2 # Remote reference (where the secret is going to be pushed) 

```
          
Also without the property, the whole **remoteKey** path is then added as the key:

![image](https://user-images.githubusercontent.com/71883401/209327576-34d5b727-91c0-4bac-bc91-15b1d76740af.png)

 Its probably doable with adding base path into the **SecretStore**, but then it limits the **SecretStore** for only one destination...

And last but not least, is it planned to add **dataFrom** so I can extract all the keys?

Many Thanks!
