### ISSUE TITLE
Advanced Templating with multiple Env Vars does not work

### ISSUE THREAD

**Issue by joshua-baron** [external-secrets/external-secrets#1856]
At the moment when presented with an AWS secret containing numerous key/value pairs in YAML format, to use one external secret to pull required secrets out you use advanced templating: 

    template:
      engineVersion: v2
      data:
        config: |
         {{- $secret := .contents | fromYaml}}
            PASSWORD={{ $secret.password | toYaml }}
            USERNAME={{ $secreet.username | toYaml }}
  data:
    - secretKey: contents
      remoteRef:
        key: remoteRefToSecret
        
This created a secret but with
config: |                                                                                                                                                              │

   PASSWORD=mypassword         
   USERNAME=myusername  

Is there a way to use the advanced templating like above but without the indentation, and config: | declaration, currently it does not seem possible.

**Comment by moolen** [comment]
What is the desired outcome or what is the problem you're trying to solve? Do you want separate keys for `username` and `password`?

**Comment by joshua-baron** [comment]
The scenario is that i have a AWS secret manager secret that contains a YAML inside, this YAML is in the format:

```
databases:
  storage:
    azure:
      connectionString: "connectionstring"
  mysql:
    host: "mysqlhost"
    password: "password"
    username: "username"
  mysqlsecond:
    host: "mysqlhost"
    password: "password"
    username: "username"
  mongodb:
    host: "mongohost"
    password: "mongopassword"
    username: "mongousername"
```
    
    I then have an external secret that is choosing for appA mysql and mongodb parameters and for appB mysqlsecond and azure. To then do this i am using the advanced templating, such that appA externalsecret would look like:
    
```
    apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret
  labels:
    helm.sh/chart: chart-0.1
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: external-secret-store
    kind: ClusterSecretStore
  target:
    name: secret
    template:
      engineVersion: v2
      data:
        config: |
          {{- $secret := .contents | fromYaml}}
            MYSQL_HOST : {{ $secret.database.mysql.host | toYaml }}
            MONGODB_HOST: {{ $secret.database.mongodb.host | toYaml }}
  data:
    - secretKey: contents
      remoteRef:
        key: local
```

however, the secret that is created looks like: 

```
config: |2                                                                                                                                                                                 
                                                                                                                                                                                             
    MYSQL_HOST=mysqlhost                                                                                                                
    MONGODB_HOST=mongohost
```

Because of this, the application using it does not see the environment variables because they are being indented inside the pod, due to the config: | which is mandatory to use "{{- $secret := .contents | fromYaml}}" which is needed to cherry pick what secrets are required from the YAML

**Comment by moolen** [comment]
Hey, if indentation is the issue you can just remove the indentation from your config.

Here's a example with the fake provider:

```yaml
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: fake
spec:
  provider:
    fake:
      data:
      - key: "appconfig"
        value: "ZGF0YWJhc2VzOgogIHN0b3JhZ2U6CiAgICBhenVyZToKICAgICAgY29ubmVjdGlvblN0cmluZzogImNvbm5lY3Rpb25zdHJpbmciCiAgbXlzcWw6CiAgICBob3N0OiAibXlzcWxob3N0IgogICAgcGFzc3dvcmQ6ICJwYXNzd29yZCIKICAgIHVzZXJuYW1lOiAidXNlcm5hbWUiCiAgbXlzcWxzZWNvbmQ6CiAgICBob3N0OiAibXlzcWxob3N0IgogICAgcGFzc3dvcmQ6ICJwYXNzd29yZCIKICAgIHVzZXJuYW1lOiAidXNlcm5hbWUiCiAgbW9uZ29kYjoKICAgIGhvc3Q6ICJtb25nb2hvc3QiCiAgICBwYXNzd29yZDogIm1vbmdvcGFzc3dvcmQiCiAgICB1c2VybmFtZTogIm1vbmdvdXNlcm5hbWUiCgo="
        version: "v1"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example
spec:
  refreshInterval: "10s"
  secretStoreRef:
    name: fake
    kind: ClusterSecretStore
  target:
    name: "app-config"
    template:
      data:
        # note: there's an additional b64dec step which is needed just to store
        # the yaml in the fake provider.
        config: |
          {{- $secret := .contents | b64dec | fromYaml -}}
          MYSQL_HOST={{ $secret.databases.mysql.host }}
          MONGODB_HOST={{ $secret.databases.mongodb.host }}
  data:
  - secretKey: contents
    remoteRef:
      key: appconfig
      version: v1
---
```

```
kubectl get secret app-config -o yaml | yq .data.config | base64 -d
MYSQL_HOST=mysqlhost
MONGODB_HOST=mongohost
```
