### ISSUE TITLE
EKS 1.24 + ESO 0.7.0 + IRSA cant assume role 

### ISSUE THREAD

**Issue by noamgreen** [external-secrets/external-secrets#1860]
Hi 
i have new cluster eks 1.24 and i install eso 0.7.0 from helm , 

```yaml
certController:
  create: false
webhook:
  create: false
serviceAccount:
  create: true
  name: vu-prod-secret-manager-operator
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::XXXXXXXXXXX:role/vu-prod-secret-manager-operator
serviceMonitor:
  enabled: false
extraArgs:
  loglevel: info
```

we are using ODIC + IRSA The IAM role is config like this 
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "",
            "Effect": "Allow",
            "Principal": {
                "Federated": "arn:aws:iam::XXXXXXXXX:oidc-provider/oidc.eks.us-east-1.amazonaws.com/id/XXXXXXXCXCXCXCXCX"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "StringEquals": {
                    "oidc.eks.us-east-1.amazonaws.com/id/XXXXXXXCXCXCXCXCX:sub": "system:serviceaccount:*:*"
                }
            }
        }
    ]
}
```

and i created "ClusterSecretStore" 
```yaml
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: cluster-secret-store
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      role: arn:aws:iam::XXXXXXXXXXX:role/vu-prod-secret-manager-operator

```

this setup is working in eks 1.22 and EOS 0.5.6
after i upgraded to new eks 1.24 i am getting  error about assume  
"could not validate provider: WebIdentityErr: failed to retrieve credentials\ncaused by: AccessDenied: Not authorized to perform sts:AssumeRoleWithWebIdentity" 

```
{"level":"error","ts":1672823804.0083609,"msg":"Reconciler error","controller":"clustersecretstore","controllerGroup":"external-secrets.io","controllerKind":"ClusterSecretStore","ClusterSecretStore":{"name":"cluster-secret-store"},"namespace":"","name":"cluster-secret-store","reconcileID":"fe380224-1627-4a08-a212-51623906989d","error":"could not validate provider: WebIdentityErr: failed to retrieve credentials\ncaused by: AccessDenied: Not authorized to perform sts:AssumeRoleWithWebIdentity\n\tstatus code: 403, request id: 4bc346ed-884f-4a1e-932c-352e6ed1b35d","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:326\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:234"}
{"level":"info","ts":1672823885.9289026,"logger":"provider.aws","msg":"using aws session","region":"us-east-1","credentials":null}

{"level":"error","ts":1672823723.199175,"msg":"Reconciler error","controller":"clustersecretstore","controllerGroup":"external-secrets.io","controllerKind":"ClusterSecretStore","ClusterSecretStore":{"name":"cluster-secret-store"},"namespace":"","name":"cluster-secret-store","reconcileID":"ab0b975c-ee60-4b0c-a108-3c5f442c100d","error":"could not validate provider: WebIdentityErr: failed to retrieve credentials\ncaused by: AccessDenied: Not authorized to perform sts:AssumeRoleWithWebIdentity\n\tstatus code: 403, request id: 52cb0f4d-c6ef-458d-a5ed-c8834efdf997","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:326\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:234"}

{"level":"error","ts":1672823886.0788324,"logger":"controllers.ClusterSecretStore","msg":"unable to validate store","clustersecretstore":"/cluster-secret-store","error":"could not validate provider: WebIdentityErr: failed to retrieve credentials\ncaused by: AccessDenied: Not authorized to perform sts:AssumeRoleWithWebIdentity\n\tstatus code: 403, request id: b7952055-108d-4f47-b882-6901f9f53332","stacktrace":"github.com/external-secrets/external-secrets/pkg/controllers/secretstore.reconcile\n\t/home/runner/work/external-secrets/external-secrets/pkg/controllers/secretstore/common.go:67\ngithub.com/external-secrets/external-secrets/pkg/controllers/secretstore.(*ClusterStoreReconciler).Reconcile\n\t/home/runner/work/external-secrets/external-secrets/pkg/controllers/secretstore/clustersecretstore_controller.go:54\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:121\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:320\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:234"}
```
the configuration is not changed and i can see the service didn't create "secrets"  as it was in the eks 1.22 i think the is du to a change in the eks 1.24 in Service account ... 

i am not sure if this a bug in the EOS but i cant get any secrets 
as part of the test i add new ubuntu pods and assume the role 
```

aws sts get-caller-identity

aws sts assume-role-with-web-identity  --role-arn arn:aws:iam::xxxxxxxxxxx:role/vu-prod-secret-manager-operator  --role-session-name noam --web-identity-token $(cat /run/secrets/eks.amazonaws.com/serviceaccount/token ) --region us-east-1
```

and i can get a valid aws access 

any one have any idea what is this issue ? 

Thanks

**Comment by noamgreen** [comment]
SO after full testing i think i fount a solution, 

```yaml
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "",
            "Effect": "Allow",
            "Principal": {
                "Federated": "arn:aws:iam::XXXXXXXXXX:oidc-provider/oidc.eks.us-east-1.amazonaws.com/id/CCCCCCCCCCC"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "StringLike": {
                    "oidc.eks.us-east-1.amazonaws.com/id/XXXXXXXXXXXXXXX:sub": "system:serviceaccount:*:*"
                }
            }
        },
        {
            "Effect": "Allow",
            "Principal": {
                "AWS": "*"
            },
            "Action": "sts:AssumeRole"
        }
    ]
}
```yaml


i am not sure why its working like this and you need to add explisit "sts:AssumeRole" as the main point when you use IRSA is to use "sts:AssumeRoleWithWebIdentity" ... i think its bug ? or wrong use ?

**Comment by moolen** [comment]
StringEquals does exact case-sensitive matching. The second example uses StringLike, that's probably the issue here i suppose

**Comment by noamgreen** [comment]
@moolen HI 
so long story short i try the "StringEquals" and "StringLike" and the issues is same ... i can recreate eks 1.24 + ESO 0.7.0 and use the 
                "StringLike": {
                    "oidc.eks.us-east-1.amazonaws.com/id/xxxxxxxxxx:sub": "system:serviceaccount:*:*"

it will not work i think in the code ( i didn't check ) its not use the "sts:AssumeRoleWithWebIdentity" token and we get this error 
if you like i can try to reproduces it

**Comment by moolen** [comment]
You configure the external-secrets controller in the following way:
* you assign the pod a role using IRSA by setting an annotation on the Kubernetes Service Account `eks.amazonaws.com/role-arn: arn:aws:iam::XXXXXXXXXXX:role/vu-prod-secret-manager-operator`
* in your  ClusterSecretStore you let the controller assume the very same role

What happens is:
1. the controller fetches temporary credentials using the Kubernetes Service account
2. when using this ClusterSecretStore the controller does a `AssumeRole` call with these :point_up_2: credentials to assume the very same role (which is unneeded)

I suggest you:
1. run the controller completely without AWS credentials (no service account annotation)
2. create a new service account with IRSA annotation and point your service account to it. This service doesn't need to be mounted anywhere.

That should solve this issue. The details can be found here: https://external-secrets.io/v0.7.0/provider/aws-secrets-manager/#eks-service-account-credentials. Please let me know if that helps.

**Comment by noamgreen** [comment]
Hi 
i use eks 1.24 , ESO 0.7.1 
the fooling config 

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "",
            "Effect": "Allow",
            "Principal": {
                "Federated": "arn:aws:iam::xxxxxx:oidc-provider/oidc.eks.us-east-1.amazonaws.com/id/xxxxxxx"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "StringEquals": {
                    "oidc.eks.us-east-1.amazonaws.com/id/xxxxxxxx": "system:serviceaccount:kube-system:vu-prod-secret-manager-operator"
                }
            }
        }
    ]
}
```
ESO config 
```yaml 
certController:
  create: false
webhook:
  create: false
serviceMonitor:
  enabled: false
extraArgs:
  loglevel: debug
```

ESO ClusterSecretStore

```yaml 
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::xxxxxx:role/vu-prod-secret-manager-operator
  name: vu-prod-secret-manager-operator
  namespace: kube-system

---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: secret-store
spec:
  provider:
    aws:
      service: SecretsManager
      role: arn:aws:iam::xxxxxxxx:role/vu-prod-secret-manager-operator
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: vu-prod-secret-manager-operator
            namespace: "kube-system"
```
i get this erros 

```

external-secrets-546d6b7948-zs2cq external-secrets {"level":"debug","ts":1672998866.7665577,"logger":"controllers.ClusterSecretStore","msg":"validating","clustersecretstore":"/secret-store"}
external-secrets-546d6b7948-zs2cq external-secrets {"level":"debug","ts":1672998866.7666209,"logger":"clientmanager","msg":"creating new client","provider":"*aws.Provider","store":"/secret-store"}
external-secrets-546d6b7948-zs2cq external-secrets {"level":"debug","ts":1672998866.7669966,"logger":"provider.aws","msg":"using credentials via service account","role":"arn:aws:iam::xxxxxxx:role/vu-prod-secret-manager-operator","region":"us-east-1"}
external-secrets-546d6b7948-zs2cq external-secrets {"level":"info","ts":1672998866.7670486,"logger":"provider.aws","msg":"using aws session","region":"us-east-1","credentials":{}}
external-secrets-546d6b7948-zs2cq external-secrets {"level":"debug","ts":1672998866.7672124,"logger":"provider.aws","msg":"fetching token","ns":"kube-system","sa":"vu-prod-secret-manager-operator"}
external-secrets-546d6b7948-zs2cq external-secrets {"level":"error","ts":1672998866.8102505,"logger":"controllers.ClusterSecretStore","msg":"unable to validate store","clustersecretstore":"/secret-store","error":"could not validate provider: AccessDenied: User: arn:aws:sts::xxxxxxxx:assumed-role/vu-prod-secret-manager-operator/external-secrets-provider-aws is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::xxxxxx:role/vu-prod-secret-manager-operator\n\tstatus code: 403, request id: 3f9466c7-5ae2-4bf4-ba9a-c2e88f74e944","stacktrace":"github.com/external-secrets/external-secrets/pkg/controllers/secretstore.reconcile\n\t/home/runner/work/external-secrets/external-secrets/pkg/controllers/secretstore/common.go:67\ngithub.com/external-secrets/external-secrets/pkg/controllers/secretstore.(*ClusterStoreReconciler).Reconcile\n\t/home/runner/work/external-secrets/external-secrets/pkg/controllers/secretstore/clustersecretstore_controller.go:54\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:122\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:323\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:235"}
external-secrets-546d6b7948-zs2cq external-secrets {"level":"debug","ts":1672998866.8103285,"logger":"events","msg":"AccessDenied: User: arn:aws:sts::xxxxxxxxx:assumed-role/vu-prod-secret-manager-operator/external-secrets-provider-aws is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::xxxxxxxxx:role/vu-prod-secret-manager-operator\n\tstatus code: 403, request id: 3f9466c7-5ae2-4bf4-ba9a-c2e88f74e944","type":"Warning","object":{"kind":"ClusterSecretStore","name":"secret-store","uid":"67fcab16-9053-4fd6-9412-1949f608e41a","apiVersion":"external-secrets.io/v1beta1","resourceVersion":"175379"},"reason":"ValidationFailed"}
external-secrets-546d6b7948-zs2cq external-secrets {"level":"error","ts":1672998866.8257182,"msg":"Reconciler error","controller":"clustersecretstore","controllerGroup":"external-secrets.io","controllerKind":"ClusterSecretStore","ClusterSecretStore":{"name":"secret-store"},"namespace":"","name":"secret-store","reconcileID":"8e4afc6e-46f7-4c72-8298-f2bc91694711","error":"could not validate provider: AccessDenied: User: arn:aws:sts::xxxxxxxxx:assumed-role/vu-prod-secret-manager-operator/external-secrets-provider-aws is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::xxxxxxxx:role/vu-prod-secret-manager-operator\n\tstatus code: 403, request id: 3f9466c7-5ae2-4bf4-ba9a-c2e88f74e944","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:235"}
```
i think the issues is as you instruct me not to use 
"run the controller completely without AWS credentials (no service account annotation)" this will setup the default SA "external-secrets" its installed via helm ( by default ) i am not sure .... 

i try to 


```yaml
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "",
            "Effect": "Allow",
            "Principal": {
                "Federated": "arn:aws:iam::xxxxxx:oidc-provider/oidc.eks.us-east-1.amazonaws.com/id/xxxxxx"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "StringLike": {
                    "oidc.eks.us-east-1.amazonaws.com/id/xxxxxxxxx": "system:serviceaccount:*:*"
                }
            }
        }
    ]
}
```
same issue its just want STS  ....

**Comment by moolen** [comment]
Remove the spec.provider.aws.role, that should do it then.

**Comment by noamgreen** [comment]
HI 
i can confirm
```yaml 
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "",
            "Effect": "Allow",
            "Principal": {
                "Federated": "arn:aws:iam::xx:oidc-provider/oidc.eks.us-east-1.amazonaws.com/id/xxxx"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "StringEquals": {
                    "oidc.eks.us-east-1.amazonaws.com/id/xxxxx": "system:serviceaccount:kube-system:vu-prod-secret-manager-operator"
                }
            }
        }
    ]
}
```` 
```` yaml
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: cluster-secret-store
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: vu-prod-secret-manager-operator
            namespace: "kube-system"
````


This is working , i must say that i didnt understand from the docs that this is the way .... it will be nice to add some examples "using Irsa" 

in any case thanks !!! you helped me allot !
