### ISSUE TITLE
using Merge policy deletes secret entirely when using argocd

### ISSUE THREAD

**Issue by pdeva** [external-secrets/external-secrets#1885]
Steps to reproduce:

1. install argocd on your cluster.
2. create secret reesource manually using `kubectl` like this:

Here is the secret it is being applied to 

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret1
  namespace: default
  labels:
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
type: Opaque
data:
  admin.password: JDJhJDEwJHzzzzzzzzzzzzzzz
```

3. create an `ExternalSecret` resource like below with creationPolicy `Merge` and push it to your argo app for argocd to apply it.

```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "argocd-secret1"
  namespace: default
spec:
  secretStoreRef:
    name: aws-sm
    kind: ClusterSecretStore
  refreshInterval: "1h"
  target:
    creationPolicy: 'Merge'
  data:
    - secretKey: "api-key"
      remoteRef:
        key: "argocd/webhook/github"
        property: "webhook.github.secret"
```

### What should happen

The existing secret `argocd-secret1` should get a new property `"webhook.github.secret"`. 

### What actually happens

The entire secret resource `argocd-secret1` is gone from the cluster.
