### ISSUE TITLE
AKS - Kubernetes Provider ServiceAccount Auth Bug?

### ISSUE THREAD

**Issue by kayiplar** [external-secrets/external-secrets#1907]
**Describe the solution you'd like**
Get secrets from the local or a remote Kubernetes cluster.

**What is the added value?**
Verify Kubernetes Provider ServiceAccount auth is working.

**Observations (Constraints, Context, etc):**

It seems that I am missing something when using the Kubernetes Provider. Can someone help me or verify that is working (or not working) ?

I am using the exact example from the PR that was merged: https://github.com/external-secrets/external-secrets/pull/1201 

and getting the error "client is not allowed to get secrets".  Is the example outdated?

`ClusterSecretStore`:
````
Events:
  Type     Reason            Age                     From                  Message
  ----     ------            ----                    ----                  -------
  Warning  ValidationFailed  2m33s (x16 over 5m18s)  cluster-secret-store  client is not allowed to get secrets
````

`ExternalSecret`:

```
NAMESPACE   NAME                                                      STORE            REFRESH INTERVAL   STATUS              READY
default     externalsecret.external-secrets.io/example-kubernetes     kubernetes       1m                 SecretSyncedError   False
```

Versions:
Kubernetes: v1.23.8
ESO: v0.7.1

**Comment by gusfcarvalho** [comment]
Hi @kayiplar ! The provider is working. The error you’re getting means that your service account has no permissions to get secrets, causing the provider to error out .

**Comment by gusfcarvalho** [comment]
You can fix that by adding a role and a rolebinding to your service account

**Comment by kayiplar** [comment]
Hi, thanks for the feedback. As I've said, I used the example which includes the role and rolebinding. 

````
apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-store
  namespace: default
secrets:
- name: my-store-token-hdbt2
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: eso-store-role
  namespace: default
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - authorization.k8s.io
  resources:
  - selfsubjectaccessreviews
  - selfsubjectrulesreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: my-store
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: eso-store-role
subjects:
- kind: ServiceAccount
  name: my-store
  namespace: default
````

**Comment by kayiplar** [comment]
Can you somehow verify that its working or give me other example manifests that work ?

**Comment by gusfcarvalho** [comment]
You can find how to set it up in the documentations page: https://external-secrets.io/v0.7.1/provider/kubernetes/

A working example would be
```
apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
  namespace: default
stringData:
  username: foo
  password: bar
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: database-credentials
  namespace: my-ns
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: k8s-store-sa-auth             # name of the SecretStore (or kind specified)
  target:
    name: database-credentials  # name of the k8s Secret to be created
  data:
  - secretKey: username
    remoteRef:
      key: database-credentials
      property: username

  - secretKey: password
    remoteRef:
      key: database-credentials
      property: password
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-store
  namespace: my-ns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: my-ns
  name: eso-store-role
rules:
- apiGroups: [""]
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - authorization.k8s.io
  resources:
  - selfsubjectrulesreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: eso-store-role
rules:
- apiGroups: [""]
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - authorization.k8s.io
  resources:
  - selfsubjectrulesreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: default
  name: my-store-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: eso-store-role
subjects:
- kind: ServiceAccount
  name: my-store
  namespace: my-ns
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: k8s-store-sa-auth
  namespace: my-ns
spec:
  provider:
    kubernetes:
      remoteNamespace: default
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
      auth:
        serviceAccount:
          name: "my-store"
```

leading to:
```
[~/repos/external-secrets]$ kubectl get es -n my-ns 
NAME                   STORE               REFRESH INTERVAL   STATUS         READY
database-credentials   k8s-store-sa-auth   1h                 SecretSynced   True
```
and
```
kubectl get ss -n my-ns
NAME                AGE     STATUS   CAPABILITIES   READY
k8s-store-sa-auth   2m58s   Valid    ReadOnly       True
```
