### ISSUE TITLE
Invalid config key due to label containing a '/'

### ISSUE THREAD

**Issue by joggeli34** [external-secrets/external-secrets#1910]
I like to add a label to the generated secret containing a `/` in the name. This used to work before 0.7.1
No after the update, I get following error:
```
Secret "repo-git" is invalid: data[argocd.argoproj.io/secret-type]: Invalid value: "argocd.argoproj.io/secret-type": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name', or 'KEY_NAME', or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+')
```

having following configuration for the ExternalSecret:
```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  labels:
    app.kubernetes.io/instance: argocd
  name: repo-git
  namespace: argocd
spec:
  data:
    - remoteRef:
        key: git-username
      secretKey: username
    - remoteRef:
        key: git-password
      secretKey: password
  refreshInterval: 24h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: keyvault-cluster-secret-store
  target:
    name: repo-git
    template:
      data:
        name: Git Repo
        password: '{{ .password | toString }}'
        type: git
        url: 'https://the-git.git'
        username: '{{ .username | toString }}'
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
```

**Comment by moolen** [comment]
Your error message sounds like the indentation was wrong (`metadata` was under the `data` node).

Your example looks fine, though, that should work.

I made it work with this here:

```yaml
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: fake
spec:
  provider:
    fake:
      data:
      - key: "username"
        value: "hihihi"
        version: "v1"
      - key: "password"
        value: "123123123123"
        version: "v1"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example-2
spec:
  refreshInterval: "30s"
  secretStoreRef:
    name: fake
    kind: ClusterSecretStore
  target:
    name: repo-git
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        name: Git Repo
        password: '{{ .password | toString }}'
        type: git
        url: 'https://the-git.git'
        username: '{{ .username | toString }}'

  data:
  - secretKey: username
    remoteRef:
      key: username
      version: v1
  - secretKey: password
    remoteRef:
      key: password
      version: v1

```


which yields:

```yaml
apiVersion: v1
data:
  name: R2l0IFJlcG8=
  password: MTIzMTIzMTIzMTIz
  type: Z2l0
  url: aHR0cHM6Ly90aGUtZ2l0LmdpdA==
  username: aGloaWhp
immutable: false
kind: Secret
metadata:
  annotations:
    reconcile.external-secrets.io/data-hash: 11d01246d5008c9425667232c6dccbf8
  creationTimestamp: "2023-01-13T17:10:20Z"
  labels:
    argocd.argoproj.io/secret-type: repository
  name: repo-git
  namespace: default
type: Opaque
```
