### ISSUE TITLE
Feature Request: Helper for exposing TLS certificates as a java keystore

### ISSUE THREAD

**Issue by justinkillen** [external-secrets/external-secrets#1912]
**Describe the solution you'd like**
In secrets providers, it is common to store (m)TLS certificates.  I would like to be able to keep those as-is in the secrets provider, but have it exposed in k8s as a java keystore.

**What is the added value?**
Today, I have to maintain a separate secret in my provider separately, and this often gets out of sync.  Having it done at the ExternalSecrets layer would mean that it would never get out of sync.

**Give us examples of the outcome**
The 2 big use-cases would be:
1) Adding public certificates (no private key)
2) Adding private certificates (with a private key)

Syntax could be something like:
```
spec:
  target:
    template:
      data:
        keystore.jks: "{{ javakeystore .publiccert | javakeystore .privatecert .privatekey }}"
```

**Observations (Constraints, Context, etc):**
n/a
