### ISSUE TITLE
ClusterSecretStore auth via Temporary Credentials failing | invalid header field value for "X-Amz-Security-Token"

### ISSUE THREAD

**Issue by sanooprajps** [external-secrets/external-secrets#1933]
Hi,

I have the following scenario.

ESO Version: v0.7.2 

1. ClusterSecretStore auth is done through IAM Temporary Credentials
```
kind: ClusterSecretStore
metadata:
  name: sm-poc-clustersecretstore
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-west-2
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: awssm-secret
            key: access-key
          secretAccessKeySecretRef:
            name: awssm-secret
            key: secret-access-key
          sessionTokenSecretRef:
            name: awssm-secret
            key: session-token
```
2. When I try to create an ExternalSecret, it is failing with the following error
```
Status:
  Conditions:
    Last Transition Time:  2023-01-17T08:20:27Z
    Message:               could not get secret data from provider
    Reason:                SecretSyncedError
    Status:                False
    Type:                  Ready
Events:
  Type     Reason        Age                From              Message
  ----     ------        ----               ----              -------
  Warning  UpdateFailed  11s (x2 over 12s)  external-secrets  RequestError: send request failed
caused by: Post "https://secretsmanager.us-west-2.amazonaws.com/": net/http: invalid header field value for "X-Amz-Security-Token"
```

*ExternalSecret.yaml*
```
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: sm-poc-clusterexternalsecret
spec:
  externalSecretName: sm-poc-externalsecret
  namespaceSelector:
    matchLabels:
      name: external-secrets
  refreshTime: 1m
  externalSecretSpec:
    secretStoreRef:
      name: sm-poc-clustersecretstore
      kind: ClusterSecretStore
    target:
      name: sm-poc-testing
      creationPolicy: Owner
      template:
        engineVersion: v2
        type: Opaque
        data:
          FILE.cfg: |
            {{- range $key, $value := . -}}
            {{ $key }} = {{ $value }}
            {{end}}
    dataFrom:
      - extract:
          key: sm-poc-region
```

ERROR from pods:

```
{"level":"error","ts":1673951103.9571843,"logger":"controllers.ExternalSecret","msg":"could not get secret data from provider","ExternalSecret":"external-secrets/sm-poc-externalsecret","error":"RequestError: send request failed\ncaused by: Post \"https://secretsmanager.us-west-2.amazonaws.com/\": net/http: invalid header field value for \"X-Amz-Security-Token\"","stacktrace":"github.com/external-secrets/external-secrets/pkg/controllers/externalsecret.(*Reconciler).Reconcile\n\t/home/runner/work/external-secrets/external-secrets/pkg/controllers/externalsecret/externalsecret_controller.go:190\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:122\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:323\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:235"}

```

I am able to successfully use these credentials with AWS CLI commands. These credentials are created from instance metadata
```
curl http://169.254.169.254/latest/meta-data/iam/security-credentials/test-instance-profile
```
