### ISSUE TITLE
Help setting up cross account to read AWS Secretmanager of a different AWS Account

### ISSUE THREAD

**Issue by MansurEsm** [external-secrets/external-secrets#1936]
**Describe the solution you'd like**

We want to generate in say AWS "Account A" secrets which are fetched from AWS Secretsmanager of Account B

**What is the added value?**

In this way we are able to either centralize the secrets into one Management account, or use the secrets of Account B to feed our central ETL System (Apache Airflow) to be able to access Data (S3, DB, etc. with secrets managed there) which are stored in Account B

AWS Secretsmanager SecretValues of Account B as a Kubernetes Secret in the EKS Cluster of Account A.
No need to describe a k8 secret ...

**Observations (Constraints, Context, etc):**

What I have already figured out:
All I describe now is terraform code where possible.
You need 2 AWS Accounts. Account A with AWS EKS, Account B with AWS secretsmanager if you want to build it.

On Both accounts I install helm chart of external-secrets in the chart-version 0.7.2
```
resource "helm_release" "external_secrets" {
  name       = "external-secrets"
  repository = "https://charts.external-secrets.io"
  chart      = "external-secrets"
  version    = 0.7.2
  namespace  = var.namespace == "" ? "kube-system" : var.namespace
[... no dynamic values ...]
}
```

Account B:
Create a AWS Secretmanager Secret (And fill manually some secretvalues)
```
resource "aws_secretsmanager_secret" "secret" {
  name        = "myname"
  kms_key_id  = module.kms_sm.arn
}
``` 
Create a selfmanaged AWS KMS key in Account B and attach the following policy to it:
```
{
  "Version": "2012-10-17",
  "Id": "key-consolepolicy-3",
  "Statement": [
    {
      "Sid": "Enable IAM User Permissions",
      "Effect": "Allow",
      "Principal": {
        "AWS": "arn:aws:iam::***AccountB***:root"
      },
      "Action": "kms:*",
      "Resource": "*"
    },
    {
      "Sid": "Allow use of the key",
      "Effect": "Allow",
      "Principal": {
        "AWS": "[***ARN of Account A irsa Role (Look further down)***](arn:aws:iam::***Account A***:role/***ARN of Account A irsa Role (Look further down)***)"
      },
      "Action": [
        "kms:*" # Attention! This should cover only the needed rights. Its just for debugging
      ],
      "Resource": "*"
    }
  ]
}
```

Attach the following Policy in Account B secretmanager to the secret "myname":
```
{
  "Version" : "2012-10-17",
  "Statement" : [ {
    "Effect" : "Allow",
    "Principal" : {
      "AWS" : "arn:aws:iam::***Account A***:role/***ARN of Account A irsa Role (Look further down)***"
    },
    "Action" : "secretsmanager:Get*",
    "Resource" : "*"
  } ]
}
```

Not sure if I need this:
```
data "aws_iam_policy_document" "cross_account_assume_role_policy" {
  statement {
    effect = "Allow"

    principals {
      type        = "AWS"
      identifiers = [[local.gaia_shared__global_sa_irsa_arn](arn:aws:iam::***Account A***:role/***ARN of Account A irsa Role (Look further down)***)]
    }

    actions = ["sts:AssumeRole"]
  }
}

resource "aws_iam_role" "cross_account_assume_role" {
  name               = "my-irsa-role"
  assume_role_policy = data.aws_iam_policy_document.cross_account_assume_role_policy.json
}
```

In Account A - where I want to get the Secret of Account B I do so:
I create an IAM Policy with the following Policy:
```
data "aws_iam_policy_document" "secret" {

  statement {
    sid    = "secretstoreAccess"
    effect = "Allow"

    actions = [
      "secretsmanager:GetResourcePolicy",
      "secretsmanager:GetSecretValue",
      "secretsmanager:DescribeSecret",
      "secretsmanager:ListSecretVersionIds",
    ]

    resources = compact([
      "arn:aws:secretsmanager:eu-central-1:***AccountA***:secret:secretsinA-Account"
      "arn:aws:secretsmanager:eu-central-1:***AccountB***:secret:myname"
    ])
  }
}
```

I create an irsa which creates the serviceaccount and attaches the IAM policy to it.
```
[If code Manifest is needed I can deliver]
```

I create a ClusterSecretStote:
The clustersecretstore has access to the AWS secretsmanager of the same Account A, but seems like not to account B...

```
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: myclustersecretstore
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-central-1
      auth:
        jwt:
          serviceAccountRef:
            name: ***The above mentioned serviceaccount***
            namespace: kube-system
```

I create an ClusterExternalSecret which should also create the external secret:
```
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: "somename"
spec:
  externalSecretName: "sometargetexternalsecretname"
  namespaceSelector:
    matchLabels: 
      secret_something: true
  refreshTime: 1m
  externalSecretSpec:
    refreshInterval: 1h
    secretStoreRef:
      kind: ClusterSecretStore
      name: "myclustersecretstore"
    target:
      name: "WhatsThatAgain"
      creationPolicy: 'Owner'
    dataFrom:
    - extract:
        key: "myname"
        version: "AWSCURRENT"
```

The clustersecretstore gets created
The Clusterexternalsecret gets created
The log of the Pod of the external-secret controller logs no error, lists the secrets of Account A, but notiung about the secret of the account B and no Error 
```
[I can deliver Logs, but the say noting]
```

But no external-secret gets created.

I do not understand how external-secret understands that it shall look for the Secretmanager Secret "arn:aws:secretsmanager:eu-central-1:***AccountB***:secret:myname" in Account B.
Does it look on the Ressource section of the assigned policy of the serviceaccount?

It's difficult to debug because the external-secret Log says noting.
I can also not easyly test the access with the profile of account A because this is my User Account and not the irsa-Role.

Any suggestion?
- How does it work that external-secret knows to search in Account B secretsmanager?
- Any suggestion how to reasonably test the permission to access as the irsa User of Account A to Account B?
