### ISSUE TITLE
AWS SecretManager - PushSecret creates Secret with no value

### ISSUE THREAD

**Issue by tmarshall98** [external-secrets/external-secrets#1938]
Running ExternalSecrets 0.7.2

The following example results in the AWS SecretManager secret being created but without a Secret Value, instead just completely blank.
This is not an IAM issue either, as the PushSecret status does converge to `PushSecret synced successfully` and no errors are logged

```yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: example-secret
data:
  CLIENT_SECRET: U2VjcmV0RXhhbXBsZVRlc3Q=
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: "aws-secretstore-us-east-2"
spec:
  provider:
    aws:
      service: SecretsManager
      region: "us-east-2"
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: pushsecret-example
spec:
  deletionPolicy: Delete
  refreshInterval: 10s
  secretStoreRefs:
    - name: aws-secretstore-us-east-2
      kind: SecretStore
  selector:
    secret:
      name: example-secret
  data:
    - match:
        secretKey: 'CLIENT_SECRET' # Source Kubernetes secret key to be pushed
        remoteRef:
          remoteKey: client_secret
```
