### ISSUE TITLE
GCP SM does not support external_account type 

### ISSUE THREAD

**Issue by avinashmeda** [external-secrets/external-secrets#1946]
**Describe the solution you'd like**
GCP SM does not support external_account type which is required to support workload identity on baremetal Anthos cluster.

**What is the added value?**
required to support workload identity on baremetal Anthos cluster.

**Give us examples of the outcome**

In the pkg/provider/gcp/secretmanager/auth.go file changing the snippet in the function serviceAccountTokenSource
config, err := google.JWTConfigFromJSON(credentials, CloudPlatformRole)
	if err != nil {
		return nil, fmt.Errorf(errUnableProcessJSONCredentials, err)
	}
to 
Use google. tokenSource will add support to multiple such scenarios

**Comment by rob-whittle** [comment]
Hi I've also been trying to use workload identity with Anthos, but on VMWare.  I created a SecretStore as per the guide, using 'global' for the cluster location.  I also tried setting `serviceAccountRef.audiences` (based if some info from [here](https://cloud.google.com/anthos/fleet-management/docs/use-workload-identity#outside).  The error I am seeing is `failed to create GCP secretmanager client: unable to fetch identitybindingtoken: could not get idbindtoken token, status: 404`.

**Comment by rob-whittle** [comment]
FWIW I managed to get something to work with our Anthos on VMWare clusters by using the pod identity method on the ESO deployment.  Unfortunately this restricts usage to ClusterSecretStore which is not ideal for finely scoping access to specific secrets from specific namespaces.

Installing with Helm I configured the following values.yaml

```
extraEnv:
  - name: GOOGLE_APPLICATION_CREDENTIALS
    value: /var/run/secrets/tokens/gcp-ksa/google-application-credentials.json

extraVolumes:
  - name: gcp-ksa
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          path: token
          audience: <WORKLOAD_IDENTITY_POOL>
          expirationSeconds: 172800
      - configMap:
          name: google-application-credentials
          optional: false
          items:
            - key: "google-application-credentials.json"
              path: "google-application-credentials.json"

extraVolumeMounts:
  - name: gcp-ksa
    mountPath: /var/run/secrets/tokens/gcp-ksa
    readOnly: true

serviceAccount:
  annotations:
    iam.gke.io/gcp-service-account: <GCP_SERVICE_ACCOUNT_EMAIL_ADDRESS>
  automount: true
```

And then had to apply the `google-application-credentials` configmap as a separate step as couldn't find a way to deploy it through the Helm chart.  Looks like:

```
kind: ConfigMap
apiVersion: v1
metadata:
  namespace: external-secrets
  name: google-application-credentials
data:
  google-application-credentials.json: |
    {
      "type": "external_account",
      "audience": "identitynamespace:WORKLOAD_IDENTITY_POOL:IDENTITY_PROVIDER",
      "service_account_impersonation_url": "https://iamcredentials.googleapis.com/v1/projects/-/serviceAccounts/GSA_NAME@GSA_PROJECT_ID.iam.gserviceaccount.com:generateAccessToken",
      "subject_token_type": "urn:ietf:params:oauth:token-type:jwt",
      "token_url": "https://sts.googleapis.com/v1/token",
      "credential_source": {
        "file": "/var/run/secrets/tokens/gcp-ksa/token"
      }
    }
```

See https://cloud.google.com/anthos/fleet-management/docs/use-workload-identity for info on how to obtain audience value.
