### ISSUE TITLE
The security token included in the request is invalid error even though my token is valid

### ISSUE THREAD

**Issue by froy001** [external-secrets/external-secrets#1947]
I am using external-secrets version 0.7.2 with kubernetes 1.22.17 on a k3d cluster. 
I am trying to setup a ClusterSecretStore using tmp credentials. Shown below:
```yaml
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
    name: secretstore
spec:
    provider:
        aws:
            service: SecretsManager
            region: eu-west-1
            auth:
                secretRef:
                    accessKeyIDSecretRef:
                      name: awssm-secret
                      key: access-key
                      namespace: external-secrets
                    secretAccessKeySecretRef:
                      name: awssm-secret
                      key: secret-access-key
                      namespace: external-secrets
                    sessionTokenSecretRef:  
                      name: awssm-secret
                      key: session-token
                      namespace: external-secrets
```
When deploying external-secrets i get a :
```golang
{"level":"info","ts":1674477410.8171813,"logger":"provider.aws","msg":"using aws session","region":"eu-west-1","credentials":{}}
{"level":"info","ts":1674477410.8172092,"logger":"provider.aws.secretsmanager","msg":"fetching secret value","key":"dev-shared-environment-vault-secret","version":"AWSCURRENT"}
{"level":"error","ts":1674477411.3760185,"logger":"controllers.ExternalSecret","msg":"could not get secret data from provider","ExternalSecret":"qct-coverage/common-vault","error":"UnrecognizedClientException: The security token included in the request is invalid.\n\tstatus code: 400, ","stacktrace":"github.com/external-secrets/external-secrets/pkg/controllers/externalsecret.(*Reconciler).Reconcile\n\t/home/runner/work/external-secrets/external-secrets/pkg/controllers/externalsecret/externalsecret_controller.go:190\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:122\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:323\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:235"}
```
The thing is that the session token is valid, all the awssm-secret values and keys are correct and I have not a clue why my secrets are not deplyed to my namespace. Since I am all out of ides a am trying a hail mary here. Perhaps someone will be able to point me in the right direction.
