### ISSUE TITLE
1Password `decoding error response: invalid character 'p' after top-level value`

### ISSUE THREAD

**Issue by onedr0p** [external-secrets/external-secrets#1948]
**Describe the solution you'd like**

This was working but I recently updated to 1Password containers for 1.6.0, I also tried to rollback but no luck. I didn't change anything else with my config. I am using the latest version of ESO [v0.7.2](https://github.com/external-secrets/external-secrets/releases/tag/v0.7.2)

## Events
```
Status:
  Capabilities:  ReadOnly
  Conditions:
    Last Transition Time:  2023-01-23T17:44:17Z
    Message:               unable to validate store
    Reason:                ValidationFailed
    Status:                False
    Type:                  Ready
Events:
  Type     Reason            Age                 From                  Message
  ----     ------            ----                ----                  -------
  Warning  ValidationFailed  39m (x22 over 94m)  cluster-secret-store  decoding error response: invalid character 'p' after top-level value
  Warning  ValidationFailed  23m                 cluster-secret-store  Get "http://onepassword-connect:8080/v1/vaults?filter=title+eq+%22Kubernetes%22": dial tcp 10.43.228.133:8080: connect: operation not permitted
  Warning  ValidationFailed  23s (x20 over 12m)  cluster-secret-store  decoding error response: invalid character 'p' after top-level value
```

## ClusterSecretStore

```yaml
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: onepassword-connect
  namespace: kube-system
spec:
  provider:
    onepassword:
      connectHost: http://onepassword-connect:8080
      vaults:
        Kubernetes: 1
      auth:
        secretRef:
          connectTokenSecretRef:
            name: onepassword-connect-secret
            key: token
            namespace: kube-system
```

## OnePassword Container logs

```
✖ stern -n kube-system onepassword --exclude "/health" --exclude "/heartbeat"
+ onepassword-connect-779b994b5-g5bwc › sync
+ onepassword-connect-779b994b5-g5bwc › onepassword-connect
onepassword-connect-779b994b5-g5bwc sync {"log_message":"(I) disabling bus peer auto-discovery","timestamp":"2023-01-23T19:43:47.960903646Z","level":3}
onepassword-connect-779b994b5-g5bwc sync {"log_message":"(W) did not initialize bus connection to peer localhost:11220. If the peer is currently booting, it may initialize the connection while starting. Details: [grav] failed to transport.CreateConnection: [transport-websocket] failed to Dial endpoint: dial tcp [::1]:11220: connect: connection refused. ","timestamp":"2023-01-23T19:43:47.961474296Z","level":2}
onepassword-connect-779b994b5-g5bwc sync {"log_message":"(I) no existing database found, will initialize at /home/opuser/.op/data/1password.sqlite","timestamp":"2023-01-23T19:43:47.96190545Z","level":3}
onepassword-connect-779b994b5-g5bwc sync {"log_message":"(I) starting 1Password Connect Sync ...","timestamp":"2023-01-23T19:43:47.962036995Z","level":3}
onepassword-connect-779b994b5-g5bwc sync {"log_message":"(I) database initialization complete","timestamp":"2023-01-23T19:43:47.967845235Z","level":3}
onepassword-connect-779b994b5-g5bwc sync {"log_message":"(I) ### syncer credentials bootstrap ### ","timestamp":"2023-01-23T19:43:47.968275082Z","level":3}
onepassword-connect-779b994b5-g5bwc sync {"log_message":"(I) established incoming bus peer connection","timestamp":"2023-01-23T19:43:48.931151167Z","level":3}
onepassword-connect-779b994b5-g5bwc onepassword-connect {"log_message":"(I) no database found, will retry in 1s","timestamp":"2023-01-23T19:43:47.918795422Z","level":3}
onepassword-connect-779b994b5-g5bwc onepassword-connect {"log_message":"(I) disabling bus peer auto-discovery","timestamp":"2023-01-23T19:43:48.927102848Z","level":3}
onepassword-connect-779b994b5-g5bwc onepassword-connect {"log_message":"(I) connected to bus peer at localhost:11221","timestamp":"2023-01-23T19:43:48.931324013Z","level":3}
onepassword-connect-779b994b5-g5bwc onepassword-connect {"log_message":"(I) starting 1Password Connect API ...","timestamp":"2023-01-23T19:43:48.932473738Z","level":3}
```
