### ISSUE TITLE
Memory leak external-secrets-operator

### ISSUE THREAD

**Issue by SashaShcherbyna** [external-secrets/external-secrets#1968]
**Describe the solution you'd like**
external-secrets:v0.7.0
i can see memory leak  in external-secrets-operator
My configuration.
```
 resources:
    limits:
      cpu: 160m
      memory: 256Mi
    requests:
      cpu: 90m
      memory: 128Mi
```

**What is the added value?**
kill off memory leak

**Give us examples of the outcome**
when the container starts we have a memory use of approximately 32 Mb, after a some time  i can see that kubernetes starts restarting  the pod because pod has reached its memory usage limit.
<img width="522" alt="Screenshot 2023-01-31 at 17 35 25" src="https://user-images.githubusercontent.com/2994616/215807678-a4f0f26f-3ae5-4ad6-8871-798400732bc3.png">
<img width="509" alt="Screenshot 2023-01-31 at 17 35 41" src="https://user-images.githubusercontent.com/2994616/215807697-df8eec0c-2de7-4757-bd0c-02e947103d00.png">
<img width="522" alt="Screenshot 2023-01-31 at 17 36 12" src="https://user-images.githubusercontent.com/2994616/215807724-990eb70c-f032-4765-944d-092ffd8afb0c.png">

**Comment by gusfcarvalho** [comment]
hi @SashaShcherbyna ! Can you share more information? What provider are you using? What configuration?

**Comment by SashaShcherbyna** [comment]
of course.
 Google Cloud Secret Manager
``` 
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  labels:
    argocd.argoproj.io/instance: external-secrets-operator
  name: cluster-secretstore
spec:
  provider:
    gcpsm:
      auth:
        workloadIdentity:
          clusterLocation: us-east4
          clusterName: my-cluster-name
          serviceAccountRef:
            name: my-serviceaccount-name
            namespace: external-secrets-operator
      projectID: my-project-id
```
please ping me if you need more information
