### ISSUE TITLE
"skipping cluster secret store as it is disabled" message, no other useful information.

### ISSUE THREAD

**Issue by roberto-caylent** [external-secrets/external-secrets#1970]
Seems I'm the only one alone getting this message, there are no events in the ClusterSecretStore resource, and this is all the controller says. Is there a place where to get a useful error message?

```
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: eks-default
spec:
  controller: ""
  provider:
    aws:
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
      region: us-east-1
      role: arn:aws:iam::xxxxxxxxxxxx:role/dev-dev-external-secrets
      service: SecretsManager
  refreshInterval: 20
status:
  capabilities: ""
```
