### ISSUE TITLE
Metric relabeling capability in the helm chart

### ISSUE THREAD

**Issue by mikhailadvani** [external-secrets/external-secrets#1971]
**Describe the solution you'd like**

Ability to set further attributes of the servicemonitor resource

**What is the added value?**

While running in a multi-tenant setup, we can have multiple alertmanagerconfig resources (typically one per namespace) of the kube-prometheus-stack which has an implicit matcher on the namespace label. Given the namespace label in this case is always the namespace of the service monitor resource and the value of the namespace of external secret resource is under the exported_namespace label. 

**Give us examples of the outcome**

Desired endpoints block in servicemonitor spec:
```yaml
  endpoints:
  - interval: 30s
    port: metrics
    scrapeTimeout: 25s
    honorLabels: true
    metricRelabelings:
    - action: replace
      regex: (.*)
      replacement: $1
      sourceLabels:
      - exported_namespace
      targetLabel: namespace
```
**Observations (Constraints, Context, etc):**

Current scenario
<img width="1698" alt="Screenshot 2023-02-01 at 10 24 00" src="https://user-images.githubusercontent.com/2051423/216007249-1acac775-5670-4b34-9d6d-4dfeb3b6dd04.png">

Desired scenario
<img width="1702" alt="Screenshot 2023-02-01 at 10 34 05" src="https://user-images.githubusercontent.com/2051423/216007398-5b0f282d-9f6c-4127-bf13-c8136d18c452.png">
