### ISSUE TITLE
SecretSyncedError when Vault Secret is created via API

### ISSUE THREAD

**Issue by alexanghel23** [external-secrets/external-secrets#1995]
Hello,

I get this error whenever I create a secret using the Vault API:

```
status:
  conditions:
  - lastTransitionTime: "2023-02-08T16:54:55Z"
    message: could not get secret data from provider
    reason: SecretSyncedError
```

Creating the same secret using the Vault UI is working and syncing the external secret. 

Below the code for creating the secret using the API:

```
import requests
import json

# Token

headers = {'X-Vault-Token': 'xxxxx'}

# Connection to Vault

vaultapi = f'http://vault.prefect-orion-dev:8200'

# Create KV secret engine named prefect
payload_kv = {
  "type": "kv",
  "version": "2",
  "config": {
    "force_no_cache": True,
    "default_lease_ttl": 0,
    "max_lease_ttl": 0
  }
}
requests.post(f'{vaultapi}/v1/sys/mounts/prefect', headers=headers, json=payload_kv)

# Create secret for Google Cloud service account at prefect/gcp/sa path

payload_sa = {
  "type": "service_account",
  "project_id": "my-project",
  "private_key_id": "myprivatekeyid",
  "private_key": "-----BEGIN PRIVATE KEY-----xxxxxx-----END PRIVATE KEY-----\n",
  "client_email": "my-email@my-project.iam.gserviceaccount.com",
  "client_id": "000000000",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509"
}

requests.post(f'{vaultapi}/v1/prefect/gcp/sa', headers=headers, json=payload_sa)
```

**Comment by alexanghel23** [comment]
My Kubernetes resources:

```
apiVersion: v1
kind: Secret
metadata:
  name: vault-token
  namespace: prefect-orion-dev
type: Opaque
data:
  token: xxxxxxxxxx= 

---

 apiVersion: external-secrets.io/v1beta1
 kind: SecretStore
 metadata:
   name: vault-backend-prefect
   namespace: prefect-orion-dev
 spec:
   provider:
     vault:
       server: http://vault.prefect-orion-dev:8200
       path: prefect
       version: v2
       auth:
        tokenSecretRef:
          name: vault-token
          key: token

---

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: my-cool-secret-prefect
  namespace: prefect-orion-dev
spec:
  
  refreshInterval: "15s" 
  secretStoreRef:
    name: vault-backend-prefect
    kind: SecretStore
  target: 
    name: my-cool-new-secret-prefect 
    creationPolicy: Owner
  data:
    - secretKey: my-cool-new-secret-key
      remoteRef:
        key: gcp/sa
```
