### ISSUE TITLE
ESO does not work with Azure Keyvault Private Endpoints

### ISSUE THREAD

**Issue by dklbe** [external-secrets/external-secrets#1998]
Using a secret store configuration like:

```
 provider: 
    azurekv:
        authType: ManagedIdentity
        environmentType: PublicCloud
        identityId: xxx
        tenantId: xxxx
        vaultUrl: https://<keyvaultname>.privatelink.vaultcore.azure.net
```

I get the error message from external-secrets-operator pod:

`
Original Error: Get \"https://<keyvaultname>.privatelink.vaultcore.azure.net/secrets/<username>/?api-version=2016-10-01\":
x509: certificate is valid for vault.azure.net, *.vault.azure.net, *.vaultcore.azure.net,  not <keyvaultname>.privatelink.vaultcore.azure.net"
`
