### ISSUE TITLE
Can't use properties of secretKeys in custom template

### ISSUE THREAD

**Issue by johanvandeweerd** [external-secrets/external-secrets#1999]
Hi

When I try to use a property of the JSON value of a secret (using AWS Secrets Manager) in a custom template, the placeholders are empty instead of replaced with the actual value when the Secret is rendered.

**Input**
Given the following value for secret `my-secret` in AWS Secrets Manager
```json
{
  "username": "my-username",
  "password": "my-password",
  "host": "my-host",
  "port": 123,
}
```

and the following `ExternalSecret` manifest
```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: my-secret
spec:
  secretStoreRef:
    kind: SecretStore
    name: my-secret-store
  data:
    - secretKey: username
      remoteRef:
        key: my-secret
        property: username
    - secretKey: password
      remoteRef:
        key: my-secret
        property: password
    - secretKey: host
      remoteRef:
        key: my-secret
        property: host
    - secretKey: port
      remoteRef:
        key: my-secret
        property: port
  target:
    name: my-secret
    template:
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
        url: "jdbc://{{ .host }}:{{ .port }}"
```

**Expected Secret**

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
data:
  username: my-username
  password: my-password
  url: jdbc://my-host:123
```

**Actual Secret**

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
data:
  username: 
  password: 
  url: jdbc://
```

When I remove the template part, a Secret is generated with all the expected values (so I conclude that the issue is not with the SecretStore or the reference of the secerts).

Any help would be appreciated.
