### ISSUE TITLE
ACRAccessToken wrong tenantID

### ISSUE THREAD

**Issue by metalbahamut** [external-secrets/external-secrets#2007]
Hi,

I'm trying to create an ExternalSecret from a ACRAccessToken but it's like the generator is not using the tenantID to authenticate (it seems it's using the ClientID).

This is the error shown in the external-secrets Pod:

> {"level":"error","ts":1676298936.7215703,"logger":"controllers.ExternalSecret","msg":"could not get secret data from provider","ExternalSecret":"jsanchezmartinez/jsanchezmartinez.azurecr.io-dockerregistry-credentials","error":"could not generate [0]: ClientSecretCredential: unable to resolve an endpoint: http call(https://login.microsoftonline.com/4a05a99b-1417-4e0b-8212-278b20348e63/v2.0/.well-known/openid-configuration)(GET) error: reply status code was 400:\n{\"error\":\"invalid_tenant\",\"error_description\":\"AADSTS90002: Tenant 'YYYYYYYY-YYYY-YYYY-YYYY-278b20348e63' not found. Check to make sure you have the correct tenant ID and are signing into the correct cloud. Check with your subscription administrator, this may happen if there are no active subscriptions for the tenant.\\r\\nTrace ID: 639566f2-30a5-43dd-99cf-5feba5a91f00\\r\\nCorrelation ID: ec6934cb-00d6-4ed7-bc93-fb242bf4bb04\\r\\nTimestamp: 2023-02-13 14:35:36Z\",\"error_codes\":[90002],\"timestamp\":\"2023-02-13 14:35:36Z\",\"trace_id\":\"639566f2-30a5-43dd-99cf-5feba5a91f00\",\"correlation_id\":\"ec6934cb-00d6-4ed7-bc93-fb242bf4bb04\",\"error_uri\":\"https://login.microsoftonline.com/error?code=90002\"}","stacktrace":"github.com/external-secrets/external-secrets/pkg/controllers/externalsecret.(*Reconciler).Reconcile\n\t/home/runner/work/external-secrets/external-secrets/pkg/controllers/externalsecret/externalsecret_controller.go:190\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:122\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:323\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:235"}

And those are the yaml files I've created:
```
apiVersion: generators.external-secrets.io/v1alpha1
kind: ACRAccessToken
metadata:
  name: jsanchezmartinez.azurecr.io
  namespace: sandbox-registry
spec:
  auth:
    servicePrincipal:
      secretRef:
        clientId:
          key: azure_client_id
          name: azure-credentials
        clientSecret:
          key: azure_client_secret
          name: azure-credentials
  environmentType: PublicCloud
  registry: jsancnhezmartinez.azurecr.io
  tenantId: XXXXXXXX-XXXX-XXXX-XXXX-788b4c61840e
```
```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jsanchezmartinez.azurecr.io-dockerregistry-credentials
  namespace: sandbox-registry
spec:
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ACRAccessToken
          name: jsanchezmartinez.azurecr.io
  refreshInterval: 12h
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    immutable: false
    name: jsanchezmartinez.azurecr.io-dockerregistry-credentials
    template:
      type: kubernetes.io/dockerconfigjson
```
Am I doing something wrong? Any advice?

Regards,
