### ISSUE TITLE
Unable to pull more than one secrets from a GCPsm ExternalSecret

### ISSUE THREAD

**Issue by avbenavides** [external-secrets/external-secrets#201]
**Describe the solution you'd like**
Ability to pull more than one secret from GCPSM

**What is the added value?**
Expected behavior as per examples

**Give us examples of the outcome**
SecretStore
```yaml
apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: es-store
spec:
  provider:
      gcpsm:
        auth:
          secretRef:
            secretAccessKeySecretRef:
              name: gcpsm-secret
              key: secret-access-credentials
        projectID: {{ .Values.project }}
```

ExternalSecret
```yaml
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: minio-access-keys
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: trillian-es-store
  target:
    name:  minio-es
    creationPolicy: Owner
  data:
  - secretKey: secretkey
    remoteRef: 
      key: minio-sk
  - secretKey: accesskey
    remoteRef: 
      key: minio
```

Expected a secret with two data entries like this:
```yaml
apiVersion: v1
data:
  accesskey: whateverBase64=
  secretkey: whateverBase64=
kind: Secret
type: Opaque
metadata:
  name: minio-es
```

**Observations (Constraints, Context, etc):**
 K8s Rev: v1.18.17-gke.1900  
 ExternalSecrets: "v0.2.0"

** Error Message**
```
Message:               could not get secret data from provider: key "minio" from ExternalSecret "minio-access-keys": unable to access Secret from SecretManager Client: rpc error: code = Canceled desc = grpc: the client connection is closing
```
