### ISSUE TITLE
secretStore fails to create GCP secretmanager client using workloadidentity

### ISSUE THREAD

**Issue by mahsa2017** [external-secrets/external-secrets#2017]
Hi we have been using ESO with gcp secret manager so far we tested it with using service accounts directly
once we tried to upload key.json including service account in gcp shell in project and another time we used it with runtime service account secret and they both perfectly fine worked for us
this time we are trying workload identity and we have followed the eso docs and we still receive the error below

these two links we also applied manually but didn't help us 
https://external-secrets.io/v0.5.3/provider-google-secrets-manager/
https://medium.com/google-cloud/automated-sync-among-gcp-secrets-gke-workload-4797913576f2
https://issuehint.com/issue/external-secrets/external-secrets/1156

for some reasons I am not able to share the details of our code but the pattern is what is mentioned in this post by somebody else who was facing same exact error but their solution didn't help us 
our code is super similar to this https://issuehint.com/issue/external-secrets/external-secrets/1156

the error we get after we run kubectl describe secretStore gcp -n namespace 
 failed to create GCP secretmanager client: unable to fetch identitybindingtoken: could not get idbindtoken token, status: 404

**Comment by gusfcarvalho** [comment]
hi @mahsa2017 ! Unfortunately we cannot do much if you cannot share your manifests.

The issue you mentioned was a set of misconfiguration. I suggest you to double check if you have setup workload identity correctly, and properly configured the region/location and projectID.

**Comment by mahsa2017** [comment]
Ok I will make some changes to the code but leave the necessary parts so u can hopefully spot what is missing
this is service account
`apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.appName }}-service-account
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "template-version-label" . | indent 4}}
{{- if eq .Values.cloudProvider "gcp" }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Release.Namespace }}-runtime@{{ .Values.projectId }}.iam.gserviceaccount.com
{{- end }}
`

this is secretStore
`apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.externalSecret.secretStoreName }}
spec:
  provider:
      gcpsm:
        projectID: {{ .Values.projectId }}
        auth: 
          workloadIdentity:
            clusterName: "name-of-cluster"
            clusterLocation: "us-east1-d"
            serviceAccountRef:
              name: {{ .Values.appName }}-service-account
`

and I checked the clusterInfo is correct and also workloadidentity is enabled in that GKE cluster.@gusfcarvalho thanks

**Comment by mahsa2017** [comment]
Ok I will make some changes to the code but leave the necessary parts so u can hopefully spot what is missing
this is service account
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.appName }}-service-account
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "template-version-label" . | indent 4}}
{{- if eq .Values.cloudProvider "gcp" }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Release.Namespace }}-runtime@{{ .Values.projectId }}.iam.gserviceaccount.com
{{- end }}
```

and secretStore
```
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.externalSecret.secretStoreName }}
spec:
  provider:
      gcpsm:
        projectID: {{ .Values.projectId }}
        auth: 
          workloadIdentity:
            clusterName: "name-of-cluster"
            clusterLocation: "us-east1-d"
            serviceAccountRef:
              name: {{ .Values.appName }}-service-account
```

and I checked the clusterInfo is correct and also workloadidentity is enabled in that GKE cluster

@gusfcarvalho  Thanks
