### ISSUE TITLE
ExternalSecret keeps updating with CreationPolicy on Merge

### ISSUE THREAD

**Issue by esen-transporeon** [external-secrets/external-secrets#2033]
Hello,

we are using External Secrets with Vault and our problem is that External Secrets is spamming our Vault logs with access. I could track the excessive access back to only some of our `ExternalSecrets`. It looks like that when we use `ExternalSecrets` with the `CreationPolicy` on `Merge` to add Vault secrets to existing `Secrets` the `ExternalSecret` keeps updating excessively. 

I could view this by using: `kubectl describe ExternalSecret my-external-secret`
The event section shows a very high amount of Updates for the described `ExternalSecrets`, for example:
![image](https://user-images.githubusercontent.com/98518211/220155140-5f23a888-9254-4038-84ad-17b3f5e49416.png)

Since we are using the default `refreshTime` of one hour it should normally be a lot lower. For example the next Screenshot is the Event Section of an `ExternalSecret` which creates a new `Secret` in Kubernetes with the `CreationPolicy: owner`:
![image](https://user-images.githubusercontent.com/98518211/220155812-bb8ad222-9ddf-4c49-a761-f2db5c184672.png)

You can reproduce this issue in your cluster with following yaml:
```
apiVersion: v1
kind: Secret
metadata:
  name: test-secret
  namespace: testing
type: Opaque
stringData:
  test: testing
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test-external-secret
  namespace: testing
spec:
  secretStoreRef:
    name: your-vault-secret-store
    kind: ClusterSecretStore
  target:
    name: test-secret
    creationPolicy: 'Merge'
  data:
    - secretKey: test.key
      remoteRef:
        key: path/to/your/key
        property: key
```

I tested it with the External Secret version of 0.7.2 and Kubernetes version of 1.24.8. Our Kubernetes is running on-premise and is deployed with RKE2.

**Comment by moolen** [comment]
hey! @esen-transporeon thanks for reporting this!

I can't reproduce the issue right away in  a local setup. There may be more to it than just the merge policy.
Can you verify that this is working on your side: 

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: test-secret
type: Opaque
stringData:
  test: testing
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test-external-secret
spec:
  secretStoreRef:
    name: webhook-backend
    kind: SecretStore
  target:
    name: test-secret
    creationPolicy: 'Merge'
  data:
    - secretKey: test.key
      remoteRef:
        key: username

---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: webhook-backend
spec:
  provider:
    webhook:
      url: "http://httpbin.org/anything"
      result: {}
      headers:
        Content-Type: application/json
```

If it isn't i suspect it could be either related to latency (towards kube-apiserver or vault) or something different like eso controller deployed multiple times and they are fighting over the the secret :thinking: ?

**Comment by esen-transporeon** [comment]
![image](https://user-images.githubusercontent.com/98518211/220935692-d875f500-47e9-4254-814e-57f839966abc.png)
I got some timeouts, but other then that it worked, but I still had the same issues. The `ExternalSecret` from your example copied the content of the webhook page in to the Secret? Was that the expected behavior? Since on the website the X-Amzn-Trace-Id Field keeps changing and causes a refresh. I can't really tell if the same bug as with our `Secrets` occurred or if it just was the updating website. But still if switch your example to CreationPolicy: "Owner" and remove the initial secret it stops updating excessively.

I couldn't find any kind of second controller running. I also don't think that it is caused by latency since Kubernetes and Vault are running in the same datacenter. 

We are using rancher to manage our Cluster. Normally rancher shouldn't affect the secrets or the external secrets. 

In your [documentation](https://external-secrets.io/v0.7.2/api/externalsecret/#update-behavior) you are writing that also an update of the labels, annotations or the spec can cause an update of the secret. I think it could be related to this but when I analyze the behavior I can see that on the `ExternalSecret` the `metadata.ressourceVersion` and the `status.refreshTime` keeps changing. On the `Secret` the `metadata.ressourceVersion` keeps changing. Neither of this changes should cause an actual update.

**Comment by moolen** [comment]
> Since on the website the X-Amzn-Trace-Id Field keeps changing and causes a refresh

Can you elaborate on this a bit? Where can you see that? 

Can you post your SecretStore?

**Comment by Wikiwix** [comment]
We run into the same issue with the `argocd-secret` and HashiCorp Vault SecretStore (see bottom for both manifests)

I am investigating the problem for a while already and made the following observations:

* Problem is somewhat intermittent, We have it in (all) our three environments and I observed a time where the issue did not occur for some minutes, but came back some minutes later
* Easiest check is
  ```sh
  kubectl get secret argocd-secret --watch --watch-only
  ```
* Running ESO in single or multiple instances does not seem to make a difference
* It does not seem that there is a race condition with another tool (we disabled Argo CD for this `Secret` as part of debugging with no behavioral change
* The secret does contain other keys in `.data` and some `.metadata.labels`. If one removes all those, it reliably stops the constant refreshing. Probably because of these lines: https://github.com/external-secrets/external-secrets/blob/main/pkg/controllers/externalsecret/externalsecret_controller.go#L332-L334
* Your example works for me as expected (at least for the time being)

---

The `managedFields` for the different environments (which do not seem to matter… as at least `a` and `c` did not show the behaviour for some minutes)

```yaml
---
# kubectl get secret argocd-secret --show-managed-fields -o=jsonpath='{.metadata.managedFields}' -n=argocd --context=a | yq -P
- apiVersion: v1
  fieldsType: FieldsV1
  fieldsV1:
    f:data:
      f:admin.password: {}
      f:admin.passwordMtime: {}
      f:oidc.azure.clientId: {}
      f:oidc.azure.clientSecret: {}
    f:immutable: {}
    f:metadata:
      f:annotations:
        f:reconcile.external-secrets.io/data-hash: {}
  manager: externalsecrets.external-secrets.io/argocd-secret
  operation: Apply
  time: "2023-03-09T11:22:21Z"
- apiVersion: v1
  fieldsType: FieldsV1
  fieldsV1:
    f:data:
      .: {}
      f:admin.password: {}
      f:admin.passwordMtime: {}
      f:oidc.azure.clientId: {}
      f:oidc.azure.clientSecret: {}
      f:server.secretkey: {}
      f:tls.crt: {}
      f:tls.key: {}
    f:immutable: {}
    f:metadata:
      f:annotations:
        .: {}
        f:reconcile.external-secrets.io/data-hash: {}
    f:type: {}
  manager: kubectl-replace
  operation: Update
  time: "2023-03-08T12:50:45Z"
---
# kubectl get secret argocd-secret --show-managed-fields -o=jsonpath='{.metadata.managedFields}' -n=argocd --context=b | yq -P
- apiVersion: v1
  fieldsType: FieldsV1
  fieldsV1:
    f:data:
      f:admin.password: {}
      f:admin.passwordMtime: {}
      f:oidc.azure.clientId: {}
      f:oidc.azure.clientSecret: {}
    f:immutable: {}
    f:metadata:
      f:annotations:
        f:reconcile.external-secrets.io/data-hash: {}
  manager: externalsecrets.external-secrets.io/argocd-secret
  operation: Apply
  time: "2023-03-09T11:27:02Z"
- apiVersion: v1
  fieldsType: FieldsV1
  fieldsV1:
    f:metadata:
      f:annotations: {}
      f:labels:
        .: {}
        f:app.kubernetes.io/component: {}
        f:app.kubernetes.io/instance: {}
        f:app.kubernetes.io/managed-by: {}
        f:app.kubernetes.io/name: {}
        f:app.kubernetes.io/part-of: {}
        f:helm.sh/chart: {}
    f:type: {}
  manager: kubectl-client-side-apply
  operation: Update
  time: "2023-03-03T11:54:47Z"
- apiVersion: v1
  fieldsType: FieldsV1
  fieldsV1:
    f:metadata:
      f:annotations:
        f:kubectl.kubernetes.io/last-applied-configuration: {}
      f:labels:
        f:argocd.argoproj.io/instance: {}
  manager: argocd-controller
  operation: Update
  time: "2023-03-03T12:51:22Z"
- apiVersion: v1
  fieldsType: FieldsV1
  fieldsV1:
    f:data:
      .: {}
      f:server.secretkey: {}
      f:tls.crt: {}
      f:tls.key: {}
  manager: argocd-server
  operation: Update
  time: "2023-03-03T13:19:41Z"
---
# kubectl get secret argocd-secret --show-managed-fields -o=jsonpath='{.metadata.managedFields}' -n=argocd --context=c | yq -P
- apiVersion: v1
  fieldsType: FieldsV1
  fieldsV1:
    f:data:
      f:admin.password: {}
      f:admin.passwordMtime: {}
      f:oidc.azure.clientId: {}
      f:oidc.azure.clientSecret: {}
    f:immutable: {}
    f:metadata:
      f:annotations:
        f:a8r.io/description: {}
        f:reconcile.external-secrets.io/data-hash: {}
      f:labels:
        f:app.kubernetes.io/name: {}
        f:app.kubernetes.io/part-of: {}
  manager: externalsecrets.external-secrets.io/argocd-secret
  operation: Apply
  time: "2023-03-09T10:49:17Z"
- apiVersion: v1
  fieldsType: FieldsV1
  fieldsV1:
    f:metadata:
      f:annotations:
        .: {}
        f:kubectl.kubernetes.io/last-applied-configuration: {}
      f:labels:
        .: {}
        f:app.kubernetes.io/component: {}
        f:app.kubernetes.io/instance: {}
        f:app.kubernetes.io/managed-by: {}
        f:app.kubernetes.io/name: {}
        f:app.kubernetes.io/part-of: {}
        f:argocd.argoproj.io/instance: {}
        f:helm.sh/chart: {}
    f:type: {}
  manager: argocd-controller
  operation: Update
  time: "2023-02-28T16:36:12Z"
- apiVersion: v1
  fieldsType: FieldsV1
  fieldsV1:
    f:data:
      f:server.secretkey: {}
      f:tls.crt: {}
      f:tls.key: {}
  manager: argocd-server
  operation: Update
  time: "2023-02-28T16:38:27Z"
```

```yaml
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-secret
  namespace: argocd
  annotations:
    a8r.io/description: The secret for ArgoCD's integrated admin user and OIDC setup.
  labels:
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: cluster-management/argocd/argocd-secret
  target:
    # Argo CD dynamically extends the secret being created, so we have to allow changes to the secret
    # see https://external-secrets.io/v0.7.2/guides/ownership-deletion-policy/#merge
    creationPolicy: Merge
    template:
      data:
        admin.password: '{{ index . "admin.password" }}'
        admin.passwordMtime: '{{ index . "admin.passwordMtime" }}'
        oidc.azure.clientId: '{{ index . "oidc.azure.clientId" }}'
        oidc.azure.clientSecret: '{{ index . "oidc.azure.clientSecret" }}'
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: https://vault-1.prod.example.com
      path: kubernetes
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes-example
          role: example
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
```
