### ISSUE TITLE
"no endpoints available for service" error when following Getting started guide

### ISSUE THREAD

**Issue by jmart1** [external-secrets/external-secrets#2037]
**Describe the solution you'd like**
Describe the end goal of this proposal. What is this new functionality or the new behaviour (or what problem does it fix)? 

Go through the Getting Started guide.  Have the SecretStore and ExternalSecret objects created in my k8s cluster. 

**What is the added value?**
Explain the value that it adds. e.g. "Secret refreshing will make internal secrets up to date with external secrets".

I want to eventually have the secrets from my AWS SecretsManager available for my pods to use.  For example DB credentials.

**Give us examples of the outcome**

I was following the steps from this site: https://external-secrets.io/v0.7.2/introduction/getting-started/.

I encountered a failure on the step labeled "Create your first SecretStore".

```
kubectl apply -f SecretStore.yml
Error from server (InternalError): error when creating "SecretStore.yml": Internal error occurred: failed calling webhook "validate.secretstore.external-secrets.io": failed to call webhook: Po
```

install of External Secrets via helm.

```
jmart@MSI:~$ helm repo add external-secrets https://charts.external-secrets.io
"external-secrets" has been added to your repositories
jmart@MSI:~$
jmart@MSI:~$
jmart@MSI:~$ helm install external-secrets \
   external-secrets/external-secrets \
    -n external-secrets \
    --create-namespace \
    --set installCRDs=true
NAME: external-secrets
LAST DEPLOYED: Tue Feb 21 07:19:57 2023
NAMESPACE: external-secrets
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
external-secrets has been deployed successfully!

In order to begin using ExternalSecrets, you will need to set up a SecretStore
or ClusterSecretStore resource (for example, by creating a 'vault' SecretStore).

More information on the different types of SecretStores and how to configure them
can be found in our Github: https://github.com/external-secrets/external-secrets
jmart@MSI:~$
```

Outcome of previous steps from Getting Started guide.
```
jmart@MSI:~/ih-dev-va$ echo -n "$AWS_ACCESS_KEY_ID" > ./access-key
jmart@MSI:~/ih-dev-va$ echo -n "$AWS_SECRET_ACCESS_KEY" > ./secret-access-key
jmart@MSI:~/ih-dev-va$
jmart@MSI:~/ih-dev-va$ kubectl create secret generic ts-secrets --from-file=./access-key --from-file=./secret-access-key
```

Contents of the SecretStore.yml file.
```
jmart@MSI:~/ih-dev-va$ cat SecretStore.yml
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: ts-secret-store
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: ts-secrets
            key: access-key
          secretAccessKeySecretRef:
            name: ts-secrets
            key: secret-access-key


```

**Observations (Constraints, Context, etc):**

```
jmart@MSI:~/ih-dev-va$ kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.26.1
Kustomize Version: v4.5.7
Server Version: v1.24.8-eks-ffeb93d
WARNING: version difference between client (1.26) and server (1.24) exceeds the supported minor version skew of +/-1
jmart@MSI:~/ih-dev-va$
jmart@MSI:~/ih-dev-va$ helm version
version.BuildInfo{Version:"v3.11.1", GitCommit:"293b50c65d4d56187cd4e2f390f0ada46b4c4737", GitTreeState:"clean", GoVersion:"go1.18.10"}
```
