### ISSUE TITLE
Applying labels and annotations to secrets

### ISSUE THREAD

**Issue by bwhaley** [external-secrets/external-secrets#2041]
[This example](https://github.com/external-secrets/external-secrets/blob/main/docs/snippets/full-external-secret.yaml) includes the following regarding labels and annotations:

```
  # labels and annotations are copied over to the
  # secret that will be created
  labels:
    acme.org/owned-by: "q-team"
  annotations:
    acme.org/sha: 1234
```

I did not find this to be true. To have the annotation/label applied to the secret, I had to add it to the secret template metadata directly. Not sure if this is an error in the example or if I was doing something wrong.
