### ISSUE TITLE
Pulling all Secrets from Provider

### ISSUE THREAD

**Issue by hjeffries94** [external-secrets/external-secrets#2046]
This is just a question more than anything else, apologies if it's simple and I just haven't been able to find the answer.

Having tested pulling a single 'ExternalSecret', I would now like to be able to pull all secrets present within AWS secrets manager. I'm currently doing this for the single secret (in Terraform I might add):
```
resource "kubectl_manifest" "external_secrets" {
  yaml_body  = <<-EOF
    apiVersion: external-secrets.io/v1beta1
    kind: ExternalSecret
    metadata:
      name: eks-external-secret
    spec:
      refreshInterval: 1m
      secretStoreRef:
        name: cluster-store
        kind: ClusterSecretStore
      target:
        name: test
      data:
      - secretKey: testing-first-secret
        remoteRef:
          key: test
          property: test
          EOF
```

However, now that I've managed to do this successfully, I need to try and pull hundreds of secrets from secret manager. Is there a built in function that would allow me to do this, rather than basically duplicating what I've done above hundreds of times?

Cheers!

**Comment by moolen** [comment]
hey! You can use `find` by name/regexp or tags:

https://external-secrets.io/v0.7.2/guides/getallsecrets/#fetching-secrets-matching-a-given-name-pattern

**Comment by hjeffries94** [comment]
> hey! You can use `find` by name/regexp or tags:
> 
> https://external-secrets.io/v0.7.2/guides/getallsecrets/#fetching-secrets-matching-a-given-name-pattern

Hey moolen, thanks for that, that's pretty much exactly what I was looking for 😄 

This does pose another question though having just tested this; this is an example of a test I just ran:
```
kubectl get secret kubernetes-tagged-secrets -o yaml
apiVersion: v1
data:
  test: eyJ0ZXN0IjoidGVzdCIsInRlc3R0IjoidGVzdHQiLCJ0ZXN0dHQiOiJ0ZXN0dHQiLCJ0ZXN0dHR0IjoidGVzdHR0dCJ9
  test2: eyJ0ZXN0MiI6InRlc3QyIn0=
  test3: eyJ0ZXN0MyI6InRlc3QzIn0=
  test4: eyJ0ZXN0NCI6InRlc3Q0In0=
  test5: eyJ0ZXN0NSI6InRlc3Q1In0=
  test6: eyJ0ZXN0NiI6InRlc3Q2In0=
  test7: eyJ0ZXN0NyI6InRlc3Q3In0=
  test8: eyJ0ZXN0OCI6InRlc3Q4In0=
  test9: eyJ0ZXN0OSI6InRlc3Q5In0=
```
This is a good first step, however, I'd like to get them a bit better organised that this. For starters, under 'test', by adding additional key/values to the secret in question, it simply appends the additional keys and values in a list format rather than having them organised line-by-line, which would be more ideal to grab from an application perspective (and just neater in general).

Do you have any pointers as to how to best go about achieving this? I'm conscious this is kinda another issue in itself but it may be useful for future users to have both answers in one place.

Cheers!

**Comment by moolen** [comment]
Hey, you can take a look at this:
 https://external-secrets.io/v0.7.2/guides/datafrom-rewrite/

https://external-secrets.io/v0.7.2/guides/templating/

How do you want the resulting secret to look like?

**Comment by hjeffries94** [comment]
> Hey, you can take a look at this: https://external-secrets.io/v0.7.2/guides/datafrom-rewrite/
> 
> https://external-secrets.io/v0.7.2/guides/templating/
> 
> How do you want the resulting secret to look like?

That looks to be in the right direction, thank you!

How I imagine the secrets to look is something like the following (using the output from my previous response as reference):

```
test:
  test: eyJ0ZXN0Ijo
  testt: joidGV
  testtt: c3R0Ij
  testttt: GVzdHQiL
```

So I guess basically, it would be good to have the keys for each of the secret entries being non-encoded (as those aren't the sensitive values) but that's not a huge deal if that's not possible to do, but the way in which this is formatted is much more how I imagined it playing out having reviewed the documentation you send previously.

We could make it work how it is today, but it would require a significant per-application refactor. If you have any suggestions let me know, otherwise I'll start experimenting and see what I can come up with.

Thanks for all your help so far by the way!

**Comment by moolen** [comment]
Hey @hjeffries94 looking at your example `test=eyJ0ZXN0...` it looks like you want to extract information from structured json data. You can do that with `dataFrom[].extract`.

Given a secret `foo/bar/baz` with value:

```json
{
"test":"test",
"testt":"testt",
"testtt":"testtt",
"testttt":"testttt"
}
```

You can extract the information of this single secret

```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example
spec:
  # ...
  dataFrom:
  - extract:
      key: foo/bar/baz
```

That should give you the secret:

```yaml
kind: Secret
# ...
data:
  test: test
  testt: testt
  testtt: testtt
  testttt: testttt
```

Note:
* :warning: you need to know the secret name in advance, you can not use both `dataFrom[].find` and `dataFrom[].extract`
* :warning: when specifying multiple `dataFrom[].find` you may run into a key conflict, [please take a look at this guide](https://external-secrets.io/v0.7.2/guides/datafrom-rewrite/).

Your snippet above suggests you want to use nested data `test.test`, `test.testt` ... in a `Kind=Secret` - this is not possible, you can only define key/value pairs, [see docs](https://kubernetes.io/docs/concepts/configuration/secret/).

```
test:
  test: eyJ0ZXN0Ijo
  testt: joidGV
  testtt: c3R0Ij
  testttt: GVzdHQiL

```
