### ISSUE TITLE
Encrypt Parameter Store push secrets with a Customer Managed Key

### ISSUE THREAD

**Issue by caimez** [external-secrets/external-secrets#2047]
The goal of this new functionality would be to encrypt secrets pushed to parameter store as SecureString type with a specified Customer Managed KMS Key.

This feature will add security to the parameters stored in AWS as the parameters will require to be decrypted to be read.

We could simply specify in the pushsecrets descriptor the kmsKeyId of the key we want to use to encrypt the string:

`
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: pushsecret
spec:
  ...
  data:
    - match:
        secretKey: tls.crt
        remoteRef:
          remoteKey: /tls.crt
          **kmsKeyId: <Id of CMK>**
`

**Comment by caimez** [comment]
Please advise, this would be an amazing feature.

**Comment by moolen** [comment]
The KMS key id IMO should sit on the SecretStore, not the PushSecret as this is a provider-specific integration detail.

**Comment by moolen** [comment]
For context: we've envisioned the KMS encryption config to be defined on the SecretStore level: https://github.com/external-secrets/external-secrets/blob/main/design/002-pushsecret.md?plain=1#L57-L62. This hasn't been implemented yet, this is just a first design sketch. I'd be happy to discuss other approaches to configure encryption config for AWS/KMS.

We haven't yet come up with something detailed for the `encryptionConfig`. This should be reusable for both Parameter Store and Secrets Manager and both should (probably) be implemented in the same PR just to see if there are some specifics.

```yaml
apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: example
  namespace: example-ns
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-central-1
      encryptionConfig: {} # Specific config for Creating Secrets on AWS
```
