### ISSUE TITLE
ClusterExternalSecret + matchExpressions not detecting new namespaces

### ISSUE THREAD

**Issue by cod-r** [external-secrets/external-secrets#2055]
I want to create a secret containing the container registry credentials in every namespace. 
I used this `namespaceSelector` config:
```yaml
  namespaceSelector:
    matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: Exists
```
It works as expected, now all my namespaces have the docker registry credentials.

The problem is that if I create a new namespace it is not detected automatically.
The only way is to delete the ClusterExternalSecret and create it again.

Can we make the `ClusterExternalSecret` detect new namespaces?

**Comment by cod-r** [comment]
I found the problem, I had the `refreshTime` set to `1h`, I changed it to 1 minute and it works as expected.
Working example:
```yaml
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: test
spec:
  externalSecretName: test
  refreshTime: "1m"
  namespaceSelector:
    matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: Exists
  externalSecretSpec:
    secretStoreRef:
      name: vault-backend
      kind: ClusterSecretStore
    refreshInterval: "1h"
    target: {}
    dataFrom:
      - extract:
          key: my/vault/path
```
