### ISSUE TITLE
ExternalSecret needs service account in the same namespace, also I am using a ClusterSecretStore

### ISSUE THREAD

**Issue by RudolfVonKrugstein** [external-secrets/external-secrets#2065]
**Describe the solution you'd like**
In my Kubernetes cluster, I would like secrets to be managed (synced from AWS Secret Manager) from one workspace.
Especially the serviceaccount should only be available in that workspace, so that external-secrets is the only deployment having access to it.

I tried this:

1. Deploy the helm chart with `namespace=external-secrets`
2. Create a `ClusterSecretStore` (also in `namespace=external-secrets`)
  ```
apiVersion: "external-secrets.io/v1beta1"
kind: "ClusterSecretStore"
metadata:
  name: aws-secretsmanager-store
  namespace: external-secrets
spec:
  provider:
    aws:
      service: "SecretsManager"
      region: "eu-central-1"
      auth:
        jwt:
          serviceAccountRef:
            name: awssecretaccess
  ```
3. Create the service account (again in `namespace=external-secrets`)
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: awssecretaccess
  namespace: external-secrets
  annotations:
    "eks.amazonaws.com/role-arn": "<my-iam-role>"
```

Now, I want some secrets.

If I create an `ExternalSecret` in the same namespace (`namespace=external-secrets`) it works:

```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: externalsecret
  namespace: external-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager-store
  target: ...
  dataFrom: ...
```

The secret is synced successfully!

But if I create the `ExternalSecret` in another namespace:

```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: externalsecret
  namespace: other-namespace
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager-store
  target: ...
  dataFrom: ...
```

I get this error:

```
Warning  UpdateFailed  72s (x27 over 13m)  external-secrets  unable to create session: ServiceAccount "awssecretaccess" not found
```

How should I do this? Can I sync secrets to any namespace with only one ClusterSecretStore and one ServiceAccount?
