### ISSUE TITLE
does SecretStore support  aws-secretsmanager and parameterstore at same time

### ISSUE THREAD

**Issue by mafeifan** [external-secrets/external-secrets#2070]
I want to create a secret which both contain values come from AWS SecretsManager and  AWS Parameter Store

```yaml
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: kone-govplt-secret-store
spec:
  provider:
    aws:
      service: 
        -  SecretsManager
        -  ParameterStore
      region: cn-north-1
      auth:
        jwt:
          serviceAccountRef:
            name: govplt-deployment-sa
```

I got error: `error: error validating "demo1/1-secret-store.yaml": error validating data: ValidationError(SecretStore.spec.provider.aws.service): invalid type for io.external-secrets.v1beta1.SecretStore.spec.provider.aws.service: got "array", expected "string"; if you choose to ignore these errors, turn validation off with --validate=false`

**Comment by moolen** [comment]
Yeah, that doesn't work. A secret store always points to a single provider.
You can however reference two different `SecretStore`s in a single `ExternalSecret`:

```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "example"
spec:
  # ...
  data:
  - secretKey: "from-aws-secrets-manager"
    remoteRef:
      key: "example"
    sourceRef:
      storeRef:
        name: "aws-secrets-manager"
        kind: SecretStore
  - secretKey: "from-aws-parameter-store"
    remoteRef:
      key: "example"
    sourceRef:
      storeRef:
        name: "aws-parameter-store"
        kind: SecretStore
```

Could you please take a look at that and see if that suits your needs?

**Comment by mafeifan** [comment]
great, I tried  it's suit my needs thanks very much

paste my solution  hope that it will help others

1-parameter-store.yaml

```
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: kone-govplt-parameter-store
  namespace: government-cn
spec:
  provider:
    aws:
      service: ParameterStore
      region: cn-north-1
      auth:
        jwt:
          serviceAccountRef:
            name: govplt-deployment-sa
```

1-secret-store.yaml


```yaml
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: kone-govplt-secret-store
  namespace: government-cn
spec:
  provider:
    aws:
      service: SecretsManager
      region: cn-north-1
      auth:
        jwt:
          serviceAccountRef:
            name: govplt-deployment-sa
```

2-external-secret.yaml

```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kone-govplt-external-secret
  namespace: government-cn
spec:
  # refreshInterval: 1h
  secretStoreRef:
    name: kone-govplt-secret-store
    kind: SecretStore
  target:
    # the secret name of k8s
    name: kone-govplt-external-secret
    creationPolicy: Owner
  data:
    - secretKey: "rds_conn_str2"
      remoteRef:
        key: "/kone/govplt/auroramysql/connectionstr"
      sourceRef:
        storeRef:
          name: "kone-govplt-parameter-store"
          kind: SecretStore

  
   // read from secret manager
    - secretKey: rds_conn_str
      remoteRef:
        key: /kone/govplt/auroramysql/master/secret
        property: connStr
  
```
