### ISSUE TITLE
is it possible to generate dockerconfigjson from only username and password on AWS Secrtets Manager

### ISSUE THREAD

**Issue by RudolfVonKrugstein** [external-secrets/external-secrets#2076]
I have an AWS Secrets Manager secret in the structure:

```
{
  "username": "<username>",
  "password": "<password>",
  "remote_domain_dame": "<docker_url>"
}
```

Now with this secret, I would like the Create an `ExtrernalSecret` that can be used as a pull secret.

My humble attempt:

```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mysecret
spec:
  data:
    - secretKey: data
      remoteRef:
        key: "my-aws-secret"
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: mysecret
    template:
      engineVersion: v2
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "{{ `{{ (.data | fromYaml).registry_domain_name }}` }}": {
                "username": "{{ `{{ (.data | fromYaml).username }}` }}",
                "password": "{{ `{{ (.data | fromYaml).password }}` }}",
                "auth": "{{(.data.username : .data.password) | b64enc }}"
              }
            }
          }
```

Now, the part in the "auth" field does not work, because it needs several steps:

1. concat `.data.username`, ":" and `.data.password`
2. b64enc the result

But I do not know how to do the concat step.

Is this possible at all?

Thank you!

**Comment by RudolfVonKrugstein** [comment]
Now, I still don't if it is possible, but I noted that I do not need the auth part.

**Comment by moolen** [comment]
Hey! there's a `printf` function you can use: `printf "%s:%s" $username $password`

Roughly something like this:
```
        .dockerconfigjson: |
          $creds := .data | fromYaml
          {
            "auths": {
              "{{ `{{ $creds.registry_domain_name }}` }}": {
                "username": "{{ `{{ $creds.username }}` }}",
                "password": "{{ `{{ $creds.password }}` }}",
                "auth": "{{ printf "%s:%s" $creds.username $creds.password  | b64enc }}"
              }
            }
          }
```

**Comment by rafilkmp3** [comment]
@moolen can you share full example? my final secret its ending empty 

```
.dockerconfigjson: |
  {
    "auths": {
      "https://index.docker.io/v1/": {
        "username": "<no value>",
        "password": "<no value>"
      }
    }
  }
```

**Comment by moolen** [comment]
your `spec.data[].secretKey` conflicts, maybe try:

```yaml
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: dockerhub-credentials
spec:
  # ...
    data:
      - secretKey: username
        remoteRef:
          key: k8s/shared/dockerhub_credentials
          property: username
      - secretKey: pat
        remoteRef:
          key: k8s/shared/dockerhub_credentials
          property: pat

```
