### ISSUE TITLE
Mix in Template and Key reference

### ISSUE THREAD

**Issue by schmidtjohannes** [external-secrets/external-secrets#2080]
**Describe the solution you'd like**
At the moment setting up a template needs a key reference to be populated like described here https://external-secrets.io/v0.7.2/guides/templating/. If another key (which is not used in the template) needs to be mixed into the target secret it is ignored.
The secret generator should detect which key is used in the template and which not. All keys which are not used in the template should be added as usual to the secret.

**What is the added value?**
Using templating and simple keys in one config file would reduce maintenance and complexity in the final helm chart

**Give us examples of the outcome**
```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: template
spec:
  # ...
  target:
    template:
      engineVersion: v2
      data:
        name: admin
        password: "{{ .mysecret }}"                   # If you are using plain manifests or gitops tools
        # password: '{{ printf "{{ .mysecret }}" }}'  # If you are using templated tools like helm
  data:
  - secretKey: mysecret
    remoteRef:
      key: /credentials
     # secret which is not used in the template
  - secretKey: secretWhichIsNotUsedInTheTemplate
    remoteRef:
      key: /holygrail
```
