### ISSUE TITLE
Can we sync all the secrets from Secret Manager to K8s secret which has a certain prefix ?

### ISSUE THREAD

**Issue by bittracer** [external-secrets/external-secrets#2082]
**Describe the solution you'd like**
In a K8s Multi-tenancy (namespace) environment, is there a way to sync all the secrets if it either begins with certain prefix or ends with a certain suffix. I don't know if there any such way that already exist today.

For example, I had to specify an array of data that I want to sync.

```
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: "common-cluster-external-secret"
spec:
  externalSecretName: "externalsecret"
  namespaceSelector:
    matchLabels: 
      common-credentials: "true"

  refreshTime: "15s"
  externalSecretSpec:
    secretStoreRef:
      kind: ClusterSecretStore
      name: aws-secretsmanager-store
    refreshInterval: "15s"
    target:
      name: common
      creationPolicy: Owner
    data:
    - secretKey: .dockerconfigjson
      remoteRef:
        key: common/credential #AWS Secrets Manager secret name
        property: .dockerconfigjson #AWS Secrets Manager secret key
    - secretKey: temp-username
      remoteRef:
        key: hello-service/credentials #AWS Secrets Manager secret name
        property: username #AWS Secrets Manager secret key
    - secretKey: temp-password
      remoteRef:
        key: hello-service/credentials #AWS Secrets Manager secret name
        property: password #AWS Secrets Manager secret key
    - secretKey: test
      remoteRef:
        key: test/test/test #AWS Secrets Manager secret name
        property: test #AWS Secrets Manager secret key
```

Instead, Can we do something like below `common/*` and `*` where I provide a particular prefix and all the secrets having this prefix sync automatically?

```
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: "common-cluster-external-secret"
spec:
  externalSecretName: "externalsecret"
  namespaceSelector:
    matchLabels: 
      common-credentials: "true"

  refreshTime: "15s"
  externalSecretSpec:
    secretStoreRef:
      kind: ClusterSecretStore
      name: aws-secretsmanager-store
    refreshInterval: "15s"
    target:
      name: common
      creationPolicy: Owner
    data:
   - secretKey: .dockerconfigjson
      remoteRef:
        key: common/* #AWS Secrets Manager secret name
        property: * #AWS Secrets Manager secret key
```

**What is the added value?**

This way we don't have to modify the above yaml file all the time when there is new secret that we want to sync. We can just probably use the same prefix and the secret is automatically synchronized?

**Comment by moolen** [comment]
Yes, you can do that already with `dataFrom[].find`, please see here: https://external-secrets.io/v0.7.2/guides/getallsecrets/

You can either use a regexp prefix or use tags to identify secrets you'd like to sync. You may also want to take a look at [rewriting keys](https://external-secrets.io/v0.7.2/guides/datafrom-rewrite/) to apply a transformation on the secret keys (e.g. remove prefix).

**Comment by bittracer** [comment]
Thanks @moolen . After merging all the secrets (artifactory and other secrets...) under one secret in EKS Secrets `shared-secret`, I found it difficult to use the artifactory credentials from `shared-secret`. I am unable to directly specify following in the deployment because  the type of EKS secret is `Opaque` and not  `kubernetes.io/dockerconfigjson`:

```
  spec:
      imagePullSecrets:
        - name: shared-secret
```

Is there a way to basically access artifactory secrets in the deployment pod without changing the type?

**Comment by moolen** [comment]
Can you try to specify the `spec.target.template.type`? That should do it.
```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: shared-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: example
    kind: SecretStore
  target:
    template:
      type: kubernetes.io/dockerconfigjson # <--
```
