### ISSUE TITLE
Unable to load as envFrom in Pods | ESO generated secrets

### ISSUE THREAD

**Issue by sanooprajps** [external-secrets/external-secrets#2101]
Hi,

I have the following basic code to get the secrets from AWS SM.
```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test-es
  namespace: test
spec:
  dataFrom:
  - extract:
      key: test-kv-secrets-in-aws-sm
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: test-clustersecretstore
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    name: test-es-secrets
    template:
      data:
        test.cfg: |
          {{- range $key, $value := . }}
          {{ $key }}={{ $value }}
          {{- end }}
      engineVersion: v2
      type: Opaque
```
I need to get all the key:value generated by this `ExternalSecret` as environment variables in the pod using `envFrom` method in pod/deployment. Thats not happening because the secret data format in the Kubernetes is `Key : <secret key: secret value>`. When I export this Key `test.cfg` is exported into the pods and thats causing the problem. Is there a way to get Key/Value from AWS SM and export them into the pods without writing into a file.

Regards,
Sanoop

**Comment by moolen** [comment]
If you have structured json in `test-kv-secrets-in-aws-sm`

for example:
```json
{
  "FOO_VAR": "BAR",
  "BAZ_VAR": "BANG"
}
```

You don't need a template at all. All key/value pairs from :point_up_2: will be key/values pairs in the `Kind=Secret`. This should be enough:
```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test-es
  namespace: test
spec:
  dataFrom:
  - extract:
      key: test-kv-secrets-in-aws-sm
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: test-clustersecretstore
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    name: test-es-secrets
```

**Comment by sanooprajps** [comment]
Thanks @moolen. But I have my secrets for different applications in a `namespace` is stored in the single `AWS Secret`. For example, `test-kv-secrets-in-aws-sm` has the following kind of secrets and I use template to get secret for each application. Is there a way to get only key/value pairs when using template. (Other than writing to a file and sourcing it)
```
app1_namespace1_secret1
app1_namespace1_secret2
app2_namespace1_secret3
app2_namespace1_secret4
```
Also, can you please let me know why can't we use any delimiter other than `-, _` (hyphen and underscore) in templates. I see any special character provided in AWS SM Secret Key is getting converted as underscore in ExternalSecret template.

Thanks in advance.

**Comment by moolen** [comment]
Given a secret `test-kv-secrets-in-aws-sm` with the following contents:
```json
{
  "app1_namespace1_secret1": "1111",
  "app1_namespace1_secret2": "2222",
  "app2_namespace1_secret3": "3333",
  "app2_namespace1_secret4": "4444",
}
```

You can define one ExternalSecret per application which contains two secrets (i think this is what you're shooting for?)

```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app1-secrets
  namespace: test
spec:
  data:
    - secretKey: MY_APP1_SECRET1
      remoteRef:
        key: test-kv-secrets-in-aws-sm
        property: app1_namespace1_secret1
    - secretKey: MY_APP1_SECRET2
      remoteRef:
        key: test-kv-secrets-in-aws-sm
        property: app1_namespace1_secret2
```

That results in a secret with:

```yaml
data:
  MY_APP1_SECRET1: "1111"
  MY_APP1_SECRET2: "2222"
```
which then can be used with envFrom. For app2 it's a similar thing.
