### ISSUE TITLE
PushSecret - Order of textual encoding instances in PEM for Azure KeyVault

### ISSUE THREAD

**Issue by prejs** [external-secrets/external-secrets#2109]
**Describe the solution you'd like**
`PushSecret` can upload a PEM certificate to Azure KeyVault when order of textual encoding instances match the order from [example](https://external-secrets.io/v0.7.2/provider/azure-key-vault/#pushing-to-a-certificate):

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: source-certificate
stringData:
  certPem:  |
     -----BEGIN CERTIFICATE-----
     ...
     -----END CERTIFICATE-----
     -----BEGIN PRIVATE KEY-----
     ...
     -----END PRIVATEKEY-----
```

However, `cert-manager` combines certificate chain and private key in [different order](https://cert-manager.io/docs/reference/api-docs/#cert-manager.io/v1.CertificateOutputFormatType).

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: source-certificate
stringData:
  certPem:  |
     -----BEGIN PRIVATE KEY-----
     ...
     -----END PRIVATEKEY-----

     -----BEGIN CERTIFICATE-----
     ...
     -----END CERTIFICATE-----
```

Both formats can be uploaded to Azure KeyVault manually.
`PushSecret` doesn't handle the later one, and reports the error:

> set secret failed: could not write remote ref {{secretKey}} to target secretstore {{name}}: value from secret is not a valid certificate: x509: malformed tbs certificate

I would like `PushSecret` either to handle any order of textual encoding instances, or to support templating so that one could combine `tls.crt` and `tls.key` in accepted order.

**What is the added value?**

Certificates can be uploaded to Azure KeyVault as certificates. That way they can be used by managed resources (e.g., app service).

**Observations (Constraints, Context, etc):**

I am not sure if this incompatibility should be reported here or in `cert-manager` project. Since advanced templating allows for [extracting keys and certificates from pkcs12 archive](https://external-secrets.io/v0.7.2/guides/templating/#extract-keys-and-certificates-from-pkcs12-archive), I assumed it is reasonable to drag your attention to reverse action.
