### ISSUE TITLE
HashiCorp Vault provider is creating 2 identical requests for secret read

### ISSUE THREAD

**Issue by AdrianFarmadin** [external-secrets/external-secrets#2129]
**Describe the solution you'd like**

The HashiCorp Vault provider can be used to read the [database role credentials](https://developer.hashicorp.com/vault/docs/secrets/databases) with following setup.

Unfortunately the requests to Vault server are duplicated. For every credential refresh there are 2 identical requests for Vault server. This can lead to a problem with dynamic credentials where a new role is created for every request to read the credentials.

Another observed problem was with missing refresh requests. The secret was not refreshed in given interval.

SecretStore

```
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "<vault-url>"
      path: "db-mount"
      version: "v1"
      auth:
        tokenSecretRef:
          name: "vault-token"
          key: "token"
```

ExternalSecret

```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test
spec:
  dataFrom:
  - extract:
      conversionStrategy: Default
      decodingStrategy: None
      key: db-mount/creds/db-role
  refreshInterval: 4s
  secretStoreRef:
    kind: SecretStore
    name: vault-backend
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: test
```

External-secrets logs:

```
{"level":"debug","ts":1678789277.3875587,"logger":"clientmanager","msg":"creating new client","provider":"*vault.connector","store":"test/vault-backend"}
{"level":"debug","ts":1678789277.3900588,"logger":"provider.vault","msg":"Set token from secret"}
{"level":"debug","ts":1678789277.5563476,"logger":"controllers.ExternalSecret","msg":"reconciled secret","ExternalSecret":"test/test"}
{"level":"debug","ts":1678789277.5564568,"logger":"events","msg":"Updated Secret","type":"Normal","object":{"kind":"ExternalSecret","namespace":"test","name":"test","uid":"d3fbd31d-20db-45f9-b8fd-6e9a4d2d3f22","apiVersion":"external-secrets.io/v1beta1","resourceVersion":"12100599"},"reason":"Updated"}
{"level":"debug","ts":1678789277.5685766,"logger":"clientmanager","msg":"creating new client","provider":"*vault.connector","store":"test/vault-backend"}
{"level":"debug","ts":1678789277.5707588,"logger":"provider.vault","msg":"Set token from secret"}
{"level":"debug","ts":1678789277.740028,"logger":"controllers.ExternalSecret","msg":"reconciled secret","ExternalSecret":"test/test"}
{"level":"debug","ts":1678789277.7400913,"logger":"events","msg":"Updated Secret","type":"Normal","object":{"kind":"ExternalSecret","namespace":"test","name":"test","uid":"d3fbd31d-20db-45f9-b8fd-6e9a4d2d3f22","apiVersion":"external-secrets.io/v1beta1","resourceVersion":"12100599"},"reason":"Updated"}
{"level":"debug","ts":1678789277.7486742,"logger":"controllers.ExternalSecret","msg":"skipping refresh","ExternalSecret":"test/test","rv":"1-b29e30b8f8bc9afd8985cf232af50b48"}
```

**What is the added value?**
The fix will lower number of generated dynamic credentials and outgoing network traffic to Vault. 

**Give us examples of the outcome**

**Observations (Constraints, Context, etc):**
External-secrets: ghcr.io/external-secrets/external-secrets:v0.7.2

Helm chart: 0.7.2

K8s server: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.10-2+8627c559b36fc7", GitCommit:"8627c559b36fc796515dca10147058770a5bc380", GitTreeState:"clean", BuildDate:"2023-01-25T11:18:08Z", GoVersion:"go1.18.10", Compiler:"gc", Platform:"linux/amd64"}

Vault: 1.12.2
