### ISSUE TITLE
Problem when setting port for metrics' service

### ISSUE THREAD

**Issue by pantelis-karamolegkos** [external-secrets/external-secrets#2147]
I am using the following `values.yaml`

```yaml
  metrics:
    service:
      enabled: true
      port: 8080
  webhook:
      service:
      enabled: true
      port: 8080
  certController:
      service:
      enabled: true
      port: 8080
```

I then see the `webhook` pod erroring out as in:

```
{"level":"error","ts":1679322216.3408113,"logger":"setup","msg":"problem running manager","error":"listen tcp :8080: bind: address already in use","stacktrace":"github.com/external-secrets/external-secrets/cmd.glob..func3\n\t/home/runner/work/external-secrets/external-secrets/cmd/webhook.go:168\ngithub.com/spf13/cobra.(*Command).execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044\ngithub.com/spf13/cobra.(*Command).Execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968\ngithub.com/external-secrets/external-secrets/cmd.Execute\n\t/home/runner/work/external-secrets/external-secrets/cmd/root.go:225\nmain.main\n\t/home/runner/work/external-secrets/external-secrets/main.go:21\nruntime.main\n\t/opt/hostedtoolcache/go/1.19.4/x64/src/runtime/proc.go:250"}
```

Why is that? Is this port being used somewhere else?
