### ISSUE TITLE
High latency in secret creation via clusterexternalsecret in newly created namespaces

### ISSUE THREAD

**Issue by atilsensalduz** [external-secrets/external-secrets#2150]
I recently encountered a high latency issue when creating secrets via the clusterexternalsecret object in newly created namespaces. Despite creating the namespace and the corresponding clusterexternalsecret object, it took approximately 40 minutes for the secret to be created.

I was expecting the secret to be created immediately upon the creation of the namespace and clusterexternalsecret object. This delay has caused some issues in my workflow and I believe it would be beneficial to investigate this further. I use that secret as a dockerconfigjson and if it couldn't create immediately when new namespace created, my deployments wait until secret created.

Has anyone else experienced this issue? Is there any additional information I can provide to help diagnose the problem?

Thanks for your attention to this matter.

**Comment by gusfcarvalho** [comment]
hi @atilsensalduz ! We are not triggering a reconcile per namespace creation. The secrets are created based on your CES/ES `refreshInterval` definition. Can you share your manifests with us?

**Comment by atilsensalduz** [comment]
Hi @gusfcarvalho , here is my ClusterExternalSecret definition. I have experienced latency issue only a few namespaces. My development environment I create lots of namespace and remove them. I haven't experienced that latency before. When namespace created secret immediately created by external-secret-operator via ClusterExternalSecret.

```
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: {{ $clusterName }}-quay-pull-secret
spec:
  externalSecretName: quay-external-secret
  namespaceSelector:
    matchLabels: { }

  refreshTime: "1h"
  externalSecretSpec:
    secretStoreRef:
      name: {{ $clusterName }}-secret-store
      kind: ClusterSecretStore

    refreshInterval: 1h
    target:
      name: quay-pull-secret
      creationPolicy: Owner
      deletionPolicy: Delete

      template:
        type: kubernetes.io/dockerconfigjson
        metadata:
          annotations: { }
          labels: { }

    data:
      - secretKey: .dockerconfigjson
        remoteRef:
          key: quay-external-secret
          property: auth
          decodingStrategy: Base64
```

is there any metrics definitions to follow those kind of performance issues on external-secret-operator?
