### ISSUE TITLE
PushSecrets should implement the same templating options as ExternalSecrets

### ISSUE THREAD

**Issue by larsks** [external-secrets/external-secrets#2166]
**Describe the solution you'd like**

We want to be able to push non-JSON secrets into HashiCorp vault. That is, given a Secret like:

```
apiVersion: v1
kind: Secret
metadata:
  name: source-secret
  namespace: default
stringData:
  source-key: "this is a secret"
```

We want to push that into Vault, but that requires JSON-formatted data. Given the templating support that is [already implented](https://external-secrets.io/v0.8.1/guides/templating/) in this project, I was expecting to do something like this:

```
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: pushsecret-example
  namespace: default
spec:
  refreshInterval: 10s
  secretStoreRefs:
    - name: vault-secretstore
      kind: SecretStore
  selector:
    secret:
      name: source-secret # Source Kubernetes secret to be pushed
  data:
    - secretKey: key1
    - secretKey: key2
  remoteRef: vault/secret
  template:
    engineVersion: v2
    data:
      token: {{ key1.token }}
      color: {{ key2.color | replace "red" "blue" }}

```

That is, I want to use templating to support to take data from one or more Kubernetes Secrets and create a valid JSON document for storing into a single Vault secret.

**What is the added value?**

Currently, it's not possible to push a variety of secrets into remote secretstores. This would allow the PushSecrets feature to be more broadly useful by allow the administrator to form secrets as necessary.

This would also satisfy the "least surprise" principle by using largely identical syntax for both ExternalSecrets and PushSecrets.

**Comment by gusfcarvalho** [comment]
Generally I believe we should go for this model, but as well we should support loading a full kubernetes secret into a provider (which would make lives easier for anyone using hashivault 😄 )

**Comment by larsks** [comment]
> but as well we should support loading a full kubernetes secret into a provider

Right, that's in line with what I said about making the PullSecret API as similar as possible to the ExternalSecret API (viz. support for things like `extract`, `find`, etc).

**Comment by moolen** [comment]
One note on this:

```yaml
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: pushsecret-example
spec:
  # ...
  template:
    # how can we support nested data structures?
    # how do we handle serialization?
    data:
      token: {{ key1.token }}
      color: {{ key2.color | replace "red" "blue" }}
```

Provider APIs offer different data models for secrets which we need to take into consideration when designing this feature:
* support different object types like secret, key, certificate (Azure KeyVault)
* support nested data structures (Hashicorp Vault). I.e. how are we going to handle serialization
* support different metadata structures (labels + annotations in GCP SM, Tags in AWS...)

**Comment by taptodoc** [comment]
This feature would be very useful, pushing a TLS secret to a Secrets Manager or vault and syncing it back is very difficult as it works today, we will need to de-construct on push and re-construct on pull.

**Comment by lapwingcloud** [comment]
also a useful case is to push the TLS certificate secret from cert-manager directly to the hashi vault

Pulling certificate from hashi vault to k8s works great, but to push the certificate from k8s to hashi vault, I'd also expect I don't need to do any template , e.g.

I have a cert secret in k8s 

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: certificate
type: kubernetes.io/tls
data:
  tls.crt: ...
  tls.key: ...
```

```yaml
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: certificate
spec:
  refreshInterval: 10s
  secretStoreRefs:
    - name: vault-secretstore
      kind: SecretStore
  # instead referencing a single secret using selector
  # we use the same `dataFrom` syntax, but the source is k8s secret now
  dataFrom:
    - extract: 
        secret: certificate
  remoteRef: secret/certificate
```

now I expect a single vault secret to be created containing the `tls.crt` `tls.key` field 

```
vault kv get secret/certificate
===== Data =====
Key        Value
---        -----
tls.crt    -----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----
tls.key    -----BEGIN RSA PRIVATE KEY-----
-----END RSA PRIVATE KEY-----
```
