### ISSUE TITLE
Gitlab ExternalSecret partially filled values in Secret object

### ISSUE THREAD

**Issue by RytisBa** [external-secrets/external-secrets#2185]
**Describe the solution you'd like**

When using SecretStore with Gitlab provider, the ExternalSecret is properly syncing Secret objects.

**Observations (Constraints, Context, etc):**

I have installed ESO using Helm chart (tried 0.7.2 and 0.8.1 versions) into our EKS cluster (v1.24) with AWS SSM and Gitlab providers. The AWS SSM provider works great and we do not see any issues, however, the Gitlab provider is acting up. I have noticed that every secret created by the Gitlab provider ExternalSecret resource has partially filled secrets every --store-requeue-interval time (5 minutes by default) and it resolves itself within ~5 seconds (given that the secret is set to sync every 1 s). It wouldn't be a big issue, but pods that pick up partially filled secrets start to error out and essentially have a downtime until the secret is reconciled again.

To reproduce the issue:
1) Create a SecretStore
```
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gitlab-test
spec:
  provider:
    gitlab:
      auth:
        SecretRef:
          accessToken:
            name: gitlab-token
            key: gitlab-token
      projectID: test_project_id
```

2) Create an ExternalSecret
```
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitlab-test
spec:
  refreshInterval: 1s
  secretStoreRef:
    kind: SecretStore
    name: gitlab-test
  data:
    - secretKey: SECRET_1
      remoteRef:
        key: SECRET_1
    - secretKey: SECRET_2
      remoteRef:
        key: SECRET_2
    - secretKey: SECRET_3
      remoteRef:
        key: SECRET_3
    - secretKey: SECRET_4
      remoteRef:
        key: SECRET_4
    - secretKey: SECRET_5
      remoteRef:
        key: SECRET_5
```

 3) In terminal, you can execute this command `while true; do kubectl describe secret gitlab-test | grep " 0 bytes" && date && sleep 1; done` and watch it populate part of the secrets with 0 bytes every 5 minutes.

Example:
```
SECRET_1:               0 bytes
SECRET_2:               0 bytes
SECRET_3:               0 bytes
20:00:09 EEST
SECRET_1:               0 bytes
SECRET_2:               0 bytes
SECRET_3:               0 bytes
20:00:11 EEST
```

**Comment by StefanTUI** [comment]
This looks like a problem we also have.
About 3-5 times a day, the sync from Gitlab (self hosted instance) results in an empty secret with 0 bytes. 
This means that batch services with a short runtime and high frequency are very likely to pick up an empty secrets during the start of the pod and thus fail.

We did setup a monitor and queried Gitlab to see if we got any empty response back from the Gitlab API, but so far, we only have 100% success rates.

So somewhere inside the ESO Gitlab implementation, secrets values get lost. 

Are there options to turn on debug logging for Gitlab ES? So far the logging is no-existent for the whole Gitlab ES.

**Comment by moolen** [comment]
Hey, thanks for raising this. Unfortunately i don't have the time to dig deeply into this issue, maybe @Jabray5 @domizei385 can provide some help :pray: 

You can [change the loglevel to debug](https://external-secrets.io/v0.8.1/api/controller-options/) logs but i'm afraid that won't provide a lot more information from the provider.

Would you be able to share the ExternalSecret / SecretStore manifests? That would help debugging. Also: which version of ESO do you use, was it working prior to a specific version?

**Comment by domizei385** [comment]
Hi @RytisBa,

I ran your command today for like 10hours. Unfortunately I never got a "0 bytes" match. Though I have to admit we use no explicit secret key, but rather inject all secrets available into the container.

Is that an option you can test? Also could there be connection issue or an issue with gitlab handling the amount of requests?

@moolen: Am I right to assume that there will always be only a single job updating the credentials, irregardless of the specified refresh interval?

**Comment by moolen** [comment]
@domizei385 yes, that's right. However, it could be that there's ArgoCD or Flux interfering with the secret resource.

@RytisBa can you please check the audit logs to see who makes what modification to that secret resource? Do you run Flux, ArgoCD or some homegrown GitOps tool?

**Comment by RytisBa** [comment]
@moolen No, we do not have any GitOps tool installed, the only deployment tool we use is Helm.

Thank you @domizei385 for bulging me in the right direction, I believe the issue is related to Gitlab rate limits and the fact that ES is trying to reconcile all secret stores at once.

I created the test environment with minikube and installed ES using Helm chart. While trying to run the manifest (the one I provided the example of), oddly enough, I didn't experience any 0 bytes matches too (contrary to our production environment). After some time debugging and trying to recreate the issue in test environment I finally was able to consistently replicate it when I created 20 SecretStores for different Gitlab projects (I tried having 20 SecretStores pointing to the same Gitlab project, but that worked fine, I suppose there is some caching involved here?). After making these changes, now the test environment is also having the same issue with partially filled secrets every `--store-requeue-interval`.

**Comment by moolen** [comment]
Are you able to observe the HTTP responses from gitlab? 
This sounds to me pretty much like a bug in the provider; There are some `resp.StatusCode >= 400 && err != nil` checks [in the code](https://github.com/external-secrets/external-secrets/blob/main/pkg/provider/gitlab/gitlab.go). Maybe it doesn't get into that branch in case it hits a rate limit.

Do you host gitlab on-premises or do you use the SaaS solution? If you have a way to reproduce the issue locally for me i can take a look at it :pray:

**Comment by moolen** [comment]
@RytisBa can you please elevate my privileges to maintainer? I need access to Project / Group CI/CD Variables :pray:

**Comment by RytisBa** [comment]
@moolen Absolutely, thank you for taking a look at this issue.

**Comment by moolen** [comment]
So i reproduced the issue and it seems to be a race condition.
I can observe `HTTP 404 Not Found`, that is due to the provider **requesting project variables from the wrong project**.
It can be triggered easily with `--store-requeue-interval=1s` as you suggested above.

I didn't find the root cause yet. :hourglass_flowing_sand:

**Comment by moolen** [comment]
Found the bug, the issue is this section here. We're setting variables on `g` and return it. `g` is used as a "client" implementation and it's lifecycle is decoupled from the "provider".

Hence, if reconciliations happening concurrently this will go boom :boom: and we'll see that behaviour.  

https://github.com/external-secrets/external-secrets/blob/2cf9203142e5c56133c0f366413a0218b6a2739a/pkg/provider/gitlab/gitlab.go#L184-L193


To fix that we need to refactor the provider and do a correct split the implementation [along the interface definitions](https://github.com/external-secrets/external-secrets/blob/main/apis/externalsecrets/v1beta1/provider.go#L47-L88)  :broom:

**Comment by StefanTUI** [comment]
This is great news. I also did some testing on our end and even though you already found the issue, I will share some results anyway.

**Gitlab solution used** onPrem
**Version tested** v0.8.1
**Yamls deployed via** FluxCD

### Setup
I created one group with one project in gitlab where I set four CICD secrets
I then created two external secrets, one where all individual secrets are synced with regex 
```
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: default-gitlab-secrets
  namespace: eso-debug
spec:
  refreshInterval: 1m

  secretStoreRef:
    kind: SecretStore
    name: gitlab-secret-store

  target:
    name: default-gitlab-secrets
    creationPolicy: Owner

  dataFrom:
  - find:
      name:
        regexp: ".*"
```
and one where I specified each of the four secrets separatedly.
```---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: default-gitlab-secrets-one-by-one
  namespace: eso-debug
spec:
  refreshInterval: 1m

  secretStoreRef:
    kind: SecretStore
    name: gitlab-secret-store

  target:
    name: default-gitlab-secrets-one-by-one
    creationPolicy: Owner

  data:
    - secretKey: AM_I_EMPTY_1
      remoteRef:
        key: AM_I_EMPTY_1
    - secretKey: AM_I_EMPTY_2
      remoteRef:
        key: AM_I_EMPTY_2
    - secretKey: AM_I_EMPTY_3_VERY_LARGE_SECRET
      remoteRef:
        key: AM_I_EMPTY_3_VERY_LARGE_SECRET
    - secretKey: AM_I_EMPTY_4_AFTER_VERY_LARGE_SECRET
      remoteRef:
        key: AM_I_EMPTY_4_AFTER_VERY_LARGE_SECRET
```
Both use the same secret store
```
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gitlab-secret-store
  namespace: eso-debug
spec:
  provider:
    # provider type: gitlab
    gitlab:
      url: https://example.com/
      auth:
        SecretRef:
          accessToken:
            name: eso-gitlab-token-eso-debug-test
            key: token
      projectID: "1234"
```

### Testing
Based on @RytisBa's script, I deployed a container that tested both secrets every 10 seconds and printed out a line when there was a change in the size of the secret value.

This is what we found
```
Date,Message
"2023-04-25T10:24:19.399Z","Secret default-gitlab-secrets-one-by-one AM_I_EMPTY_4_AFTER_VERY_LARGE_SECRET changed back to size 4!"
"2023-04-25T10:24:19.399Z","Secret default-gitlab-secrets-one-by-one AM_I_EMPTY_3_VERY_LARGE_SECRET changed back to size 6580!"
"2023-04-25T10:24:19.399Z","Secret default-gitlab-secrets-one-by-one AM_I_EMPTY_2 changed back to size 28!"
"2023-04-25T10:23:19.261Z","Secret default-gitlab-secrets-one-by-one AM_I_EMPTY_4_AFTER_VERY_LARGE_SECRET just changed to size 0!"
"2023-04-25T10:23:19.261Z","Secret default-gitlab-secrets-one-by-one AM_I_EMPTY_3_VERY_LARGE_SECRET just changed to size 0!"
"2023-04-25T10:23:19.261Z","Secret default-gitlab-secrets-one-by-one AM_I_EMPTY_2 just changed to size 0!"
"2023-04-25T06:23:47.576Z","Secret default-gitlab-secrets-one-by-one AM_I_EMPTY_4_AFTER_VERY_LARGE_SECRET changed back to size 4!"
"2023-04-25T06:22:47.535Z","Secret default-gitlab-secrets-one-by-one AM_I_EMPTY_4_AFTER_VERY_LARGE_SECRET just changed to size 0!"
"2023-04-25T03:13:53.431Z","Secret default-gitlab-secrets-one-by-one AM_I_EMPTY_4_AFTER_VERY_LARGE_SECRET changed back to size 4!"
"2023-04-25T03:13:53.431Z","Secret default-gitlab-secrets-one-by-one AM_I_EMPTY_3_VERY_LARGE_SECRET changed back to size 6580!"
"2023-04-25T03:12:53.396Z","Secret default-gitlab-secrets-one-by-one AM_I_EMPTY_4_AFTER_VERY_LARGE_SECRET just changed to size 0!"
"2023-04-25T03:12:53.396Z","Secret default-gitlab-secrets-one-by-one AM_I_EMPTY_3_VERY_LARGE_SECRET just changed to size 0!"
"2023-04-24T23:33:36.142Z","Secret default-gitlab-secrets-one-by-one AM_I_EMPTY_4_AFTER_VERY_LARGE_SECRET changed back to size 4!"
"2023-04-24T23:32:36.108Z","Secret default-gitlab-secrets-one-by-one AM_I_EMPTY_4_AFTER_VERY_LARGE_SECRET just changed to size 0!"
"2023-04-24T19:33:38.062Z","Secret default-gitlab-secrets-one-by-one AM_I_EMPTY_4_AFTER_VERY_LARGE_SECRET changed back to size 4!"
"2023-04-24T19:33:38.062Z","Secret default-gitlab-secrets-one-by-one AM_I_EMPTY_3_VERY_LARGE_SECRET changed back to size 6580!"
"2023-04-24T19:32:37.028Z","Secret default-gitlab-secrets-one-by-one AM_I_EMPTY_4_AFTER_VERY_LARGE_SECRET just changed to size 0!"
"2023-04-24T19:32:37.028Z","Secret default-gitlab-secrets-one-by-one AM_I_EMPTY_3_VERY_LARGE_SECRET just changed to size 0!"
```

### Result
It looks like the error only occurs when the external secret is created with individual references to the CI/CD variables.
We never found any occurences for the external secret we created with the regex * statement.
