### ISSUE TITLE
Allow optional datafrom for external secrets

### ISSUE THREAD

**Issue by githubcdr** [external-secrets/external-secrets#2199]
Currently we have external secrets that use _datafrom_ for multiple secrets.

If one of the referenced secret is not available the sync status will be failed.

It would be a nice feature to be able to speficy a datafrom key as _optional_;

```yaml
spec:
  dataFrom:
  - extract:
      conversionStrategy: Default
      decodingStrategy: None
      key: shared/sendgrid/file
      property: data
  - extract:
      conversionStrategy: Default
      decodingStrategy: None
      key: podinfo-service/file
      property: data
      optional: true # <=== if true just ignore any errors
```

Thanks for creating this project, it's very useful!
