### ISSUE TITLE
Template an unknown number of keys/values

### ISSUE THREAD

**Issue by duncanwraight** [external-secrets/external-secrets#2202]
Hi folks

Is it currently possible - or would it be possible - to use a combination of `dataFrom - extract` and `template` to get an unknown number of key/value pairs and populate them in a single Secret key?

We have an AWS Secrets Manager secret containing a number of key/value pairs - usernames and passwords. This secret may have 1 pair, or 100+. It will change regularly. I'd like to take these and populate a single Secret property - a multiline string list of `username:password`.

Something like this:

```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: basic-auth-user-credentials
spec:
  refreshInterval: 2m
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: my-kubernetes-secret-name
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        credentials: |
          {{- range $key, $value := . }}
          $key:$value
          {{- end }}
  dataFrom:
    - extract:
        key: my-remote-secret-name
```

So that the decoded Secret ends up looking like this...

```yaml
credentials: |
  username1:password1
  username2:password2
  username3:password3
```

... which Nginx can read from for htpasswd basic authentication.

Thanks in advance!
