### ISSUE TITLE
Mounting secrets to the K8s deployment as key-value instead of json

### ISSUE THREAD

**Issue by bittracer** [external-secrets/external-secrets#2228]
**Describe the solution you'd like**

I have created a secret in Secret manager. 
For example `dev/common/dbuser` which has `key: key1` and `value: value1`

To sync this to k8s secret, I am using the following:

```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "external-secret"
  namespace: "test"
spec:
  secretStoreRef:
    name: secret-store
    kind: SecretStore
  refreshInterval: "10s"
  target:
    name: dev-secrets
  dataFrom:
  - find:
      name:
        regexp: "dev/common"
    rewrite:
    - regexp:
        source: "dev/common/(.*)"
        target: "$1"
```

Here's how I am mounting it:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-deployment
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox-app
  template:
    metadata:
      labels:
        app: busybox-app
    spec:
      containers:
        - name: busybox
          image: busybox
          envFrom:
          - secretRef:
              name: dev-secrets
```

The secrets are available to the pod as an environment variable in the following format:

`dbuser={"key1":"value1"}`

Instead I want the secret to be available in environment variable as below:

`key1:value1`

Is it possible to transform the secrets to the above format. Please note that I want the same behavior for all the secrets that is identified by the prefix `/dev/common/*`.

**Comment by bittracer** [comment]
@moolen wondering if this is doable currently?

**Comment by gusfcarvalho** [comment]
Hi @bittracer ! It is possible with templating. You can use `template.templateFromfromLiteral`, which allows you to template both keys and values for your secret output.

**Comment by bittracer** [comment]
Thanks for the reference @gusfcarvalho. I've tried few things but have not been able to achieve the desired result. Are there any example that can help me with this? 

fyi, I have used the following, but I do not want to specify all secrets one by one. Is there a regex pattern that can work for all secrets using templating?
```
dataFrom:
  - extract:
      key: "dev/common/dbuser"
  - extract:
      key: "dev/common/dbpass"
```

**Comment by moolen** [comment]
Here's a example with the fake provider.

It basically stores to secrets as a map.
It does a transformation of the secret Keys in the map (see: `| upper`).

```yaml
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: fake-template-01
spec:
  provider:
    fake:
      data:
      - key: "backend"
        valueMap:
          b1: BV1
          b2: BV2
      - key: "frontend"
        valueMap:
          f1: FV1
          f2: FV2
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: fake-template-01
spec:
  refreshInterval: "10s"
  secretStoreRef:
    name: fake-template-01
    kind: ClusterSecretStore
  target:
    name: "fake-template-01"
    template:
      engineVersion: v2
      templateFrom:
      - target: Data
        literal: |
          {{ range $key, $value := . }}
          {{$key | upper}}: ${{$value}}
          {{ end }}
  dataFrom:
    - extract:
        key: backend
    - extract:
        key: frontend
```

Please let me know if that helps.
We'll add more examples to the docs soon.

**Comment by strachg** [comment]
Adding my solution here to for others searching it out.

I'm using the latest Terraform AWS RDS module and the "manage_master_user_password" option, which creates a master credential object with username and password attributes. I used something like this to write those attributes into seperate keys.

I'd love to see a bit more about this type of notation **added to the documentation**. Yes, its in the above comment but it wasn't straight forward find this answer.

```
---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: idb-node-issue-cleanup-secretmanager
  annotations: {}
spec:
  refreshInterval: 5m0s
  secretStoreRef:
    name: secretsmanager
    kind: ClusterSecretStore
  target:
    creationPolicy: Owner
    name: app-secretmanager
    template:
      data:
        RHSSO_DB_USERNAME: '{{ $var := .db_secret | fromJson }}{{ $var.username }}'
        RHSSO_DB_PASSWORD: '{{ $var := .db_secret | fromJson }}{{ $var.password }}'
      engineVersion: v2
  data:
    - remoteRef:
        conversionStrategy: Default
        key: rds!db-[redacted]
      secretKey: db_secret
```
