### ISSUE TITLE
Behavior when `dataFrom.Find` doesn't match any entry?

### ISSUE THREAD

**Issue by wjf3121** [external-secrets/external-secrets#2232]
Hi external-secrets experts,

I have a quick question regarding the behavior when `dataFrom.Find` doesn't match any entry. I'm following the [`Getting multiple secrets`](https://external-secrets.io/v0.8.1/provider/hashicorp-vault/#getting-multiple-secrets) guide to retrieve multiple secrets from our Vault server into one K8S secret. Everything works fine except when the `dataFrom.Find` spec doesn't match any entry: 

I'm getting the following result when running `kubectl get externalsecret` to check the status of the corresponding `externalsecret`:

```
NAME                          STORE                  REFRESH INTERVAL   STATUS         READY
test-es                       test-store             15s
```
When there's no match, the `status` and `ready` column  will be empty. Even the log of the external secret pod doesn't show anything. Also there's no corresponding K8S secret generated.

My question is:
1. Should we have some information in the STATUS column when `dataFrom.Find` doesn't match anything?
2. In this case, should `externalsecret` create an empty K8S secret instead? 

Thanks in advance!

**Comment by gusfcarvalho** [comment]
Hi! i don't think that would be the default behavior. Can you share your manifests please?

**Comment by wjf3121** [comment]
Hi @gusfcarvalho,

Thanks for the response! Below is the `ExternalSecret` manifest I use:
```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test-es
  namespace: app
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: test-store
    kind: ClusterSecretStore
  target:
    name: test-secret
  dataFrom:
    - find:
        name:
          regexp: "^nonexsitentkey.*$"
```

And this is the corresponding `ClusterSecretStore` manifest:
```yaml
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore 
metadata:
  name: test-store
  namespace: app
spec:
  provider:
    vault:
      server: "${vault_url}"
      path: "${secret_path}"
      version: "v2"
      auth:
        appRole:
          path: "${auth_path}"
          roleId: "${role_id}"
          secretRef:
            name: "${k8s_secret_name}"
            namespace: "${namespace}"
            key: "${k8s_secret_key}"
```
