### ISSUE TITLE
vault and external secrets operator in differenet k8s cluster can access forbiden.

### ISSUE THREAD

**Issue by 13567436138** [external-secrets/external-secrets#2233]
**Describe the solution you'd like**
Describe the end goal of this proposal. What is this new functionality or the new behaviour (or what problem does it fix)? 
vault and external secrets operator in differenet k8s cluster can access forbiden.
**What is the added value?**
Explain the value that it adds. e.g. "Secret refreshing will make internal secrets up to date with external secrets".

**Give us examples of the outcome**

Provide templates if you are proposing changes in the CRD. Provide example workflows or code snippets if they make sense to present.

**Observations (Constraints, Context, etc):**

Give here all extra information that could be interesting. Such as Golang version and Kubernetes version if you are reporting a bug/problem. You can also foresee technical constrains like "this could only be implementing using this specific technology or approach, because of this and that".

**Comment by moolen** [comment]
Hey @13567436138 could you please elaborate a bit on the issue you're facing? e.g. what are you trying to do? Can you provide `yaml` manifests and share the error that you have observed?

**Comment by 13567436138** [comment]
secret/ap-project-clusterResourceWhitelist.yaml

kubectl apply -f ap-project-clusterResourceWhitelist.yaml -n argocd

```
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project
spec:
  clusterResourceWhitelist:
  - group: "*"
    kind: "*"
  sourceRepos:
    - https://gitee.com/hxpgit/argocd.git
  destinations:
    - server: https://192.168.229.153:6443
      namespace: demo
    - server: https://192.168.229.156:6443
      namespace: demo
```

secret/app-external-secret.yaml

kubectl apply -f app-external-secret.yaml -n argocd

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app
spec:
  destination:
    server: https://192.168.229.153:6443
    namespace: demo
  source:
    repoURL: https://gitee.com/hxpgit/argocd.git
    path: demo1/secretManager/external-secret
    targetRevision: HEAD
  project: project
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
```

### 
```
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: secretstore
  namespace: demo
spec:
  provider:
    vault:
      server: "http://192.168.229.148:31758"
      path: "kv"
      version: "v2"
      auth:
        kubernetes:
          # Path where the Kubernetes authentication backend is mounted in Vault
          mountPath: "kubernetes"
          # A required field containing the Vault Role to assume.
          role: "myapp"
          # Optional service account field containing the name
          # of a kubernetes ServiceAccount
          serviceAccountRef: 
            name: external-secrets
            namespace: external-secrets
```
```
[root@member1-153 ~]# kubectl get clustersecretstores.external-secrets.io -n demo secretstore -o yaml
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"external-secrets.io/v1beta1","kind":"ClusterSecretStore","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"app"},"name":"secretstore"},"spec":{"provider":{"vault":{"auth":{"kubernetes":{"mountPath":"kubernetes","role":"myapp","serviceAccountRef":{"name":"external-secrets","namespace":"external-secrets"}}},"path":"kv","server":"http://192.168.229.148:31758","version":"v2"}}}}
  creationTimestamp: "2023-04-17T14:43:04Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: app
  name: secretstore
  resourceVersion: "3811711"
  uid: 17b3ab64-db1f-412a-a017-0378398301b0
spec:
  provider:
    vault:
      auth:
        kubernetes:
          mountPath: kubernetes
          role: myapp
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
      path: kv
      server: http://192.168.229.148:31758
      version: v2
status:
  conditions:
  - lastTransitionTime: "2023-04-17T14:43:04Z"
    message: unable to create client
    reason: InvalidProviderConfig
    status: "False"
    type: Ready
```

```
{"level":"error","ts":1681742666.7798572,"msg":"Reconciler error","controller":"clustersecretstore","controllerGroup":"external-secrets.io","controllerKind":"ClusterSecretStore","ClusterSecretStore":{"name":"secretstore"},"namespace":"","name":"secretstore","reconcileID":"d50e801b-e327-48a8-a55e-0eef32de87e3","error":"could not get provider client: unable to log in to auth method: unable to log in with Kubernetes auth: Error making API request.\n\nURL: PUT http://192.168.229.148:31758/v1/auth/kubernetes/login\nCode: 403. Errors:\n\n* permission denied","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:235"}

```
```
kubectl exec -ti vault-0 -n vault /bin/sh 

vault policy write app app-policy.hcl

[root@mycompany secret]# cat app-policy.hcl 
path "kv/*" {
  capabilities = ["read"]
}

vault auth enable kubernetes

vault write auth/kubernetes/config \
   token_reviewer_jwt="$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" \
   kubernetes_host=https://${KUBERNETES_PORT_443_TCP_ADDR}:443 \
   kubernetes_ca_cert=@/var/run/secrets/kubernetes.io/serviceaccount/ca.crt


vault write auth/kubernetes/role/myapp \
   bound_service_account_names=default \
   bound_service_account_namespaces=demo \
   policies=app \
   ttl=1024h
   
   
vault kv put kv/vault-inject key=inject2
```
