### ISSUE TITLE
advanced templating concat dbconnectionString to dbpassword

### ISSUE THREAD

**Issue by mahsa2017** [external-secrets/external-secrets#2234]
**Describe the solution you'd like**
Hello, I am using helm and would like to get a google secret which is a dbpassword and concat it to a advanced template secret as i will share the code

**What is the added value?**
so that I can deploy my app with a full connectionString which can be dynamically generated 

**Give us examples of the outcome**

this is my current template which only returns a hardcode connectionString which i created in GCPSM 
``` apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret 
metadata: 
  name: foobardbconnectionstring 
spec: 
  refreshInterval: 1m 
  secretStoreRef: 
    kind: SecretStore 
    name: gcp  
  target: 
    template:
      engineVersion: v2
      data: 
        ConnectionStrings__randomapp: '{{  printf "{{ .randomappdbconnectionstringsecretkey }}" }}'    
    creationPolicy: Owner 
  data:                                                       
  - secretKey: randomappdbconnectionstringsecretkey 
    remoteRef:            
      key:  {{ $.Values.base.secretPrefix }}_{{ $.Values.base.environment }}_foobar_connectionstring
```
**Observations (Constraints, Context, etc):**

currently I am saving the full connectionString as google secret (bad practice as when dbpassword changes my app fail)
I need to make this more dynamic in a way that I retrieve dbpassword from google secret manager and in the template above I make it like a string concat with the google secret 

so I need my template.data.ConnectionStrings__randomapp includes this:
Server=pgsql.internal.test.randomname.cloud;Port=5432;User Id=random user id;Password=**.randomappdbconnectionstringsecretkey** ;Database=randomapp;Pooling=true;Timeout=15;Maximum Pool Size=10;Application Name=randomapp;

this way my connectionString gets built with hardcoded string and dynamic value when my dbpassword in google get rotated

so I need help with syntax of it 
I need a working version of the template below

``` 
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret 
metadata: 
  name: foobardbconnectionstring 
spec: 
  refreshInterval: 1m 
  secretStoreRef: 
    kind: SecretStore 
    name: gcp  
  target: 
    template:
      engineVersion: v2
      data: 
        ConnectionStrings__randomapp: '{{  printf "{{ Server=pgsql.internal.test.randomname.cloud;Port=5432;User Id=randomappuserid;Password=.randomappdbpasswordsecretkey ;Database=randomapp;Pooling=true;Timeout=15;Maximum Pool Size=10;Application Name=randomapp; }}" }}'  
    creationPolicy: Owner 
  data:                                                       
  - secretKey: randomappdbpasswordsecretkey 
    remoteRef:            
      key:  {{ $.Values.base.secretPrefix }}_{{ $.Values.base.environment }}_foobar_dbpassword
```

Please help me fixing this,  Thank you
