### ISSUE TITLE
scaleway configuration in ClusterSecretStore is broken if secret refs are used

### ISSUE THREAD

**Issue by iavael** [external-secrets/external-secrets#2246]
**Describe the solution you'd like**
ClusterSecretStore resources like this should work fine
```
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: scaleway-infra
spec:
  provider:
    scaleway:
      region: fr-par
      projectId: ee904d2d-d055-4077-bbc2-3e92d659b318
      accessKey:
        value: ACCESS_KEY_ID
      secretKey:
        secretRef:
          name: scaleway-api
          key: secretKey
          namespace: external-secrets
```
while now it doesn't pass validation because code expects empty namespace 

**What is the added value?**
It would be possible to use scaleway provider in ClusterSecretStore with secretRef and accessRef params

**Give us examples of the outcome**
-

**Observations (Constraints, Context, etc):**

external-secrets: 0.8.1
go: 1.19.7
k8s:
  dist: microk8s
  version: 1.26.3

**Comment by manhhavu** [comment]
I have the same issue when refers to secret refs in accessKey and secretKey

```yaml
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: scw-secret-store
spec:
  provider:
    scaleway:
      region: <region>
      projectId: <project-id>
      accessKey:
        secretRef:
          namespace: external-secrets
          name: scwsm-secret
          key: access-key
      secretKey:
        secretRef:
          namespace: external-secrets
          name: scwsm-secret
          key: secret-key
```

while executing 

```bash
kubectl describe clustersecretstore scw-secret-store
```

The error is **when using a ClusterSecretStore, namespaces must be explicitly set**.

![image](https://user-images.githubusercontent.com/4518211/233787950-c109c2ce-eace-4371-bfec-b1fb6e1a9d20.png)

I hope that your PR will fix it. Thank your for your hard work :)
