### ISSUE TITLE
pushsecrets crd error when disabled

### ISSUE THREAD

**Issue by razrd** [external-secrets/external-secrets#2257]
**Describe the solution you'd like**

component: external-secrets
helm chart version: 0.8.1

Issue:
pushsecrets crd when disabled throws exception followed by controller restarts, if leader election enabled the pod restarts goes on and on. There is no issue in reading secretsstore, externalsecrets.

Logging observed continuously from the deployment startup.
`
"level":"error","ts":1682453652.2495687,"logger":"controller-runtime.source","msg":"if kind is a CRD, it should be installed before calling Start","kind":"[PushSecret.external-secrets.io](http://pushsecret.external-secrets.io/)","error":"no matches for kind \"PushSecret\" in version \"[external-secrets.io/v1alpha1](http://external-secrets.io/v1alpha1)\"","stacktrace":"[sigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start](http://sigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start).
`

Number of restarts due to the above continuous logging.

NAME READY   STATUS    RESTARTS        AGE
pod/eso-controller-6468c67bc9-4rm2f   1/1     Running   `2` (42s ago)     8m21s
pod/eso-controller-6468c67bc9-rtr4z   1/1     Running   `1` (3m32s ago)   8m21s

due to leaderElection set to true the controller pods switches back and forth due to the error logging on pushsecrets v1alpha1.

**What is the added value?**
pushSecrets crd can be disabled properly either using `--set  crds.createPushSecret=false`  command line or using helm values boolean flag to false  and the controller pod doesn't get into a restart panic. 

When checking the generated yaml spec the crd/push-secrets.yaml is not present in the helm generated manifest which is expected behavior.

**Observations (Constraints, Context, etc):**

Use case:
Ability to read secrets manager using SecretsStore and ExternalSecrets, no requirement to push or write from SecretsStore to the secrets manager module of AWS.

Params disabled.
- crds.ClusterExternalSecret, crd.ClusterSecretStore, processClusterExternalSecret, processClusterStore, all the flags disabled i.e., false
- crds.createPushSecret: false

Modules disabled. (Not required due to use case.)
Webhook (SecretStore/ExternalSecrets use  apigroup/apiversion - external-secrets.io/v1beta1)
ServiceMonitor
CertManager

helm values file used for deployment

```
replicaCount: 2
revisionHistoryLimit: 10

image:
  repository: ghcr.io/external-secrets/external-secrets
  pullPolicy: IfNotPresent
  # -- The image tag to use. The default is the chart appVersion.
  # There are different image flavours available, like distroless and ubi.
  # Please see GitHub release notes for image tags for these flavors.
  # By default the distroless image is used.
  tag: "v0.8.1"

# -- If set, install and upgrade CRDs through helm chart.
installCRDs: true

crds:
  # -- If true, create CRDs for Cluster External Secret.
  createClusterExternalSecret: false
  # -- If true, create CRDs for Cluster Secret Store.
  createClusterSecretStore: false
  # -- If true, create CRDs for Push Secret.
  createPushSecret: false
  annotations: {}
  conversion:
    enabled: false

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "eso-controller"

# -- If true, external-secrets will perform leader election between instances to ensure no more
# than one instance of external-secrets operates at a time.
leaderElect: true

# -- If set external secrets will filter matching
# Secret Stores with the appropriate controller values.
controllerClass: "eso-custom"

# -- If set external secrets are only reconciled in the
# provided namespace
scopedNamespace: "eso-system"

# -- Must be used with scopedNamespace. If true, create scoped RBAC roles under the scoped namespace
# and implicitly disable cluster stores and cluster external secrets
scopedRBAC: true

# -- if true, the operator will process cluster external secret. Else, it will ignore them.
processClusterExternalSecret: false

# -- if true, the operator will process cluster store. Else, it will ignore them.
processClusterStore: false

# -- Specifies whether an external secret operator deployment be created.
createOperator: true

# -- Specifies the number of concurrent ExternalSecret Reconciles external-secret executes at
# a time.
concurrent: 1

serviceAccount:
  # -- Specifies whether a service account should be created.
  create: true
  # -- Automounts the service account token in all containers of the pod
  automount: true
  # -- Annotations to add to the service account.
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::123434543:role/Eso-Controller-Role"
  # -- Extra Labels to add to the service account.
  extraLabels: {}
  # -- The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template.
  name: "eso-service-account"

rbac:
  # -- Specifies whether role and rolebinding resources should be created.
  create: true

## -- Extra environment variables to add to container.
extraEnv: []

## -- Map of extra arguments to pass to container.
extraArgs: {}

## -- Extra volumes to pass to pod.
extraVolumes: []

## -- Extra volumes to mount to the container.
extraVolumeMounts: []

## -- Extra containers to add to the pod.
extraContainers: []

# -- Annotations to add to Deployment
deploymentAnnotations: {}

# -- Annotations to add to Pod
podAnnotations: {}

podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources:
  # requests:
  #   cpu: 10m
  #   memory: 32Mi
  limits:
    cpu: 10m
    memory: 32Mi

prometheus:
  # -- deprecated. will be removed with 0.7.0, use serviceMonitor instead.
  enabled: false
  service:
    # -- deprecated. will be removed with 0.7.0, use serviceMonitor instead.
    port: 8080

serviceMonitor:
  # -- Specifies whether to create a ServiceMonitor resource for collecting Prometheus metrics
  enabled: false

  # -- Additional labels
  additionalLabels: {}

  # --  Interval to scrape metrics
  interval: 30s

  # -- Timeout if metrics can't be retrieved in given time interval
  scrapeTimeout: 25s

  # -- Let prometheus add an exported_ prefix to conflicting labels
  honorLabels: false

  # -- Metric relabel configs to apply to samples before ingestion. [Metric Relabeling](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#metric_relabel_configs)
  metricRelabelings: []
  # - action: replace
  #   regex: (.*)
  #   replacement: $1
  #   sourceLabels:
  #   - exported_namespace
  #   targetLabel: namespace

  # -- Relabel configs to apply to samples before ingestion. [Relabeling](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config)
  relabelings: []
  # - sourceLabels: [__meta_kubernetes_pod_node_name]
  #   separator: ;
  #   regex: ^(.*)$
  #   targetLabel: nodename
  #   replacement: $1
  #   action: replace

metrics:
  service:
    # -- Enable if you use another monitoring tool than Prometheus to scrape the metrics
    enabled: false

    # -- Metrics service port to scrape
    port: 8080

    # -- Additional service annotations
    annotations: {}

nodeSelector: {module: "infra"}

tolerations: []

topologySpreadConstraints: []

affinity: {}

# -- Pod priority class name.
priorityClassName: ""

# -- Pod disruption budget - for more details see https://kubernetes.io/docs/concepts/workloads/pods/disruptions/
podDisruptionBudget:
  enabled: true
  # minAvailable: 1
  # maxUnavailable: 1

webhook:
  # -- Specifies whether a webhook deployment be created.
  create: false
  # -- Specifices the time to check if the cert is valid
  certCheckInterval: "5m"
  # -- Specifices the lookaheadInterval for certificate validity
  lookaheadInterval: ""
  replicaCount: 1

  # -- Specifies the amount of historic ReplicaSets k8s should keep (see https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#clean-up-policy)
  revisionHistoryLimit: 10

  certDir: /tmp/certs
  # -- Specifies whether validating webhooks should be created with failurePolicy: Fail or Ignore
  failurePolicy: Fail
  # -- Specifies if webhook pod should use hostNetwork or not.
  hostNetwork: false
  image:
    repository: ghcr.io/external-secrets/external-secrets
    pullPolicy: IfNotPresent
  # -- The image tag to use. The default is the chart appVersion.
    tag: ""
  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""
  # -- The port the webhook will listen to
  port: 10250
  rbac:
  # -- Specifies whether role and rolebinding resources should be created.
    create: true
  serviceAccount:
    # -- Specifies whether a service account should be created.
    create: true
    # -- Automounts the service account token in all containers of the pod
    automount: true
    # -- Annotations to add to the service account.
    annotations: {}
    # -- Extra Labels to add to the service account.
    extraLabels: {}
    # -- The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template.
    name: ""
  nodeSelector: {}

  tolerations: []

  affinity: {}

    # -- Pod priority class name.
  priorityClassName: ""

  # -- Pod disruption budget - for more details see https://kubernetes.io/docs/concepts/workloads/pods/disruptions/
  podDisruptionBudget:
    enabled: false
    minAvailable: 1
    # maxUnavailable: 1
  prometheus:
    # -- deprecated. will be removed with 0.7.0, use serviceMonitor instead
    enabled: false
    service:
      # -- deprecated. will be removed with 0.7.0, use serviceMonitor instead
      port: 8080

  serviceMonitor:
    # -- Specifies whether to create a ServiceMonitor resource for collecting Prometheus metrics
    enabled: false

    # -- Additional labels
    additionalLabels: {}

    # --  Interval to scrape metrics
    interval: 30s

    # -- Timeout if metrics can't be retrieved in given time interval
    scrapeTimeout: 25s

  metrics:
    service:
      # -- Enable if you use another monitoring tool than Prometheus to scrape the metrics
      enabled: false

      # -- Metrics service port to scrape
      port: 8080

      # -- Additional service annotations
      annotations: {}


  readinessProbe:
    # -- Address for readiness probe
    address: ""
    # -- ReadinessProbe port for kubelet
    port: 8081


    ## -- Extra environment variables to add to container.
  extraEnv: []

    ## -- Map of extra arguments to pass to container.
  extraArgs: {}

    ## -- Extra volumes to pass to pod.
  extraVolumes: []

    ## -- Extra volumes to mount to the container.
  extraVolumeMounts: []

    # -- Annotations to add to Secret
  secretAnnotations: {}

    # -- Annotations to add to Deployment
  deploymentAnnotations: {}

    # -- Annotations to add to Pod
  podAnnotations: {}

  podLabels: {}

  podSecurityContext: {}
      # fsGroup: 2000

  securityContext: {}
      # capabilities:
      #   drop:
      #   - ALL
      # readOnlyRootFilesystem: true
      # runAsNonRoot: true
      # runAsUser: 1000

  resources: {}
      # requests:
      #   cpu: 10m
      #   memory: 32Mi

certController:
  # -- Specifies whether a certificate controller deployment be created.
  create: false
  requeueInterval: "5m"
  replicaCount: 1

  # -- Specifies the amount of historic ReplicaSets k8s should keep (see https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#clean-up-policy)
  revisionHistoryLimit: 10

  image:
    repository: ghcr.io/external-secrets/external-secrets
    pullPolicy: IfNotPresent
    tag: ""
  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""
  rbac:
  # -- Specifies whether role and rolebinding resources should be created.
    create: true
  serviceAccount:
    # -- Specifies whether a service account should be created.
    create: true
    # -- Automounts the service account token in all containers of the pod
    automount: true
    # -- Annotations to add to the service account.
    annotations: {}
    # -- Extra Labels to add to the service account.
    extraLabels: {}
    # -- The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template.
    name: ""
  nodeSelector: {}

  tolerations: []

  affinity: {}

    # -- Pod priority class name.
  priorityClassName: ""

  # -- Pod disruption budget - for more details see https://kubernetes.io/docs/concepts/workloads/pods/disruptions/
  podDisruptionBudget:
    enabled: false
    minAvailable: 1
    # maxUnavailable: 1

  prometheus:
    # -- deprecated. will be removed with 0.7.0, use serviceMonitor instead
    enabled: false
    service:
      # -- deprecated. will be removed with 0.7.0, use serviceMonitor instead
      port: 8080

  serviceMonitor:
    # -- Specifies whether to create a ServiceMonitor resource for collecting Prometheus metrics
    enabled: false

    # -- Additional labels
    additionalLabels: {}

    # --  Interval to scrape metrics
    interval: 30s

    # -- Timeout if metrics can't be retrieved in given time interval
    scrapeTimeout: 25s

  metrics:
    service:
      # -- Enable if you use another monitoring tool than Prometheus to scrape the metrics
      enabled: false

      # -- Metrics service port to scrape
      port: 8080

      # -- Additional service annotations
      annotations: {}

    ## -- Extra environment variables to add to container.
  extraEnv: []

    ## -- Map of extra arguments to pass to container.
  extraArgs: {}


    ## -- Extra volumes to pass to pod.
  extraVolumes: []

    ## -- Extra volumes to mount to the container.
  extraVolumeMounts: []

    # -- Annotations to add to Deployment
  deploymentAnnotations: {}

    # -- Annotations to add to Pod
  podAnnotations: {}

  podLabels: {}

  podSecurityContext: {}
      # fsGroup: 2000

  securityContext: {}
      # capabilities:
      #   drop:
      #   - ALL
      # readOnlyRootFilesystem: true
      # runAsNonRoot: true
      # runAsUser: 1000

  resources: {}
      # requests:
      #   cpu: 10m
      #   memory: 32Mi

# -- Specifies `dnsOptions` to deployment
dnsConfig: {}
```
Tested command switch for helm (same as above)

```
helm template eso external-secrets/external-secrets \
--namespace=eso-system \
--set crds.createsClusterExternalSecret=false\
--set crds.createClusterSecretStore=false \
--set crds.createPushSecret=false \
--set crds.conversion.enabled=false \
--set leaderElect=true \
--set replicaCount=2 \
--set image.tag="v0.8.1" \
--set controllerClass="eso-custom" \
--set processClusterExternalSecret=false \
--set processClusterStore=false \
--set createOperator=true \
--set serviceAccount.create=true \
--set serviceAccount.name="eso-service-account" \
--set rbac.create=true \
--set serviceMonitor.enabled=false \
--set metrics.service.enabled=false \
--set webhook.create=false \
--set nodeSelector.module=infra
```

SecretStore tested
```
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: store-test
  namespace: external-secrets
spec:
  provider:
    aws:
      service: SecretsManager
      region: "us-east-1"
```

External secrets manifest tested
```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: api-test
  namespace: eso-system
spec:
  # ...
  refreshInterval: 60m
  secretStoreRef:
    name: store-test
    kind: SecretStore
  target:
    name: secrets-test
    # this is how the Kind=Secret will look like
  data:
  - secretKey: readme
    remoteRef:
      key: "preprod/esotest"
      property: readme
  - secretKey: dummy
    remoteRef:
      key: "preprod/esotest"
      property: value1
```
