### ISSUE TITLE
ClusterSecretStore example not complete for GCP

### ISSUE THREAD

**Issue by kamigerami** [external-secrets/external-secrets#226]
The clusterSecretStore example found [https://external-secrets.io/api-clustersecretstore](here) is of kind secretStore instead of a clusterSecretStore.

Also the gcpsm provider part is missing the namespace in secretAccessKeyRef.

Should be something like this.

```
apiVersion: external-secrets.io/v1alpha1
kind: ClusterSecretStore
metadata:
  name: example
  namespace: example
spec:
  provider:
      gcpsm:
        auth:
          secretRef:
            secretAccessKeySecretRef:
              name: gcpsm-secret
              key: secret-access-credentials
              namespace: example
        projectID: myProjectId
```
