### ISSUE TITLE
ExternalSecret.dataFrom.find broke after upgrading from 0.5.5 to 0.8.1

### ISSUE THREAD

**Issue by devonhk** [external-secrets/external-secrets#2270]
**Repro  steps**

I was using dataFrom to fetch all parameters from a path in parameterStore with this:

```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: my-secret
spec:
  dataFrom:
    - find:
        name:
          regexp: .*
        path: >-
          /my/base/path
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: my-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
```

Then I upgraded external-secrets to v0.8.1 which caused it to break.

**Expected behaviour**

ExternalSecrets can use `spec.dataFrom.find` to fetch secrets/parameters.

**Actual behaviour**

I get this error on the [externalSecret](https://github.com/external-secrets/external-secrets/blob/main/pkg/controllers/externalsecret/externalsecret_controller_secret.go#L217)

```
dataFrom[0].find.conversionStrategy=Default is deprecated and will be removed in further releases. Use dataFrom.rewrite instead
```

**Observations (Constraints, Context, etc):**

- The [API spec](https://external-secrets.io/v0.8.1/api/spec/#external-secrets.io/v1beta1.ExternalSecretFind) doesn't say this field was deprecated, I also didn't find anything in the release changelog indicating that it would be removed.
- It's not clear to me if the dataFrom.find or the find.conversionStrategy is supposed to be deprecated.
- I  didn't specify a `conversionStrategy` in my manifest, it gets applied by default which triggers this error.
- The error states that the `conversionStrategy` will be removed in future releases, therefore it should still work for now which is also not the case.
