### ISSUE TITLE
Service monitors not recognized by prometheus kube stak

### ISSUE THREAD

**Issue by jannotti-glaucio** [external-secrets/external-secrets#2280]
I'm trying to configure the external-secrets service-monitors to be exported to a prometheus server in a kube-prometheus-stack, but the targets are not recognized by prometheus server like service-monitors of others components that I have installed, like aws-load-balancer-controler, external-dns and cluster-autoscaller.

I'm using the external-secrets helm chart installation, version 0.7.2, in a Kubernets 1.23 cluster and the kube-promethes-stack version 45.10.1.

I'm setting only the serviceMonitor.enabled property of all the 3 components, all the other properties I'm leaving in the default values:
````
  serviceMonitor:
    enabled: true
  webhook:
    serviceMonitor:
      enabled: true
  certController:
    serviceMonitor:
      enabled: true
````

I tried to compare the service monitor created by the external-secrets and the monitors created by other external components that are working and the only difference I found between the external-secrets and all the others are the metrics endpoint path definition. On the external secrets monitor it is not defined:
````
Name:         external-secrets-metrics
Namespace:    external-secrets
Labels:       app.kubernetes.io/instance=external-secrets
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=external-secrets
              app.kubernetes.io/version=v0.7.2
              helm.sh/chart=external-secrets-0.7.2
Annotations:  meta.helm.sh/release-name: external-secrets
              meta.helm.sh/release-namespace: external-secrets
...
Spec:
  Endpoints:
    Interval:        10s
    Port:            metrics
    Scrape Timeout:  25s
  Namespace Selector:
    Match Names:
      external-secrets
  Selector:
    Match Labels:
      app.kubernetes.io/instance:  external-secrets
      app.kubernetes.io/name:      external-secrets

````
But in other components, like cluster-autoscaler, it's defined and works:
````
Name:         cluster-autoscaler
Namespace:    kube-prometheus-stack
Labels:       app.kubernetes.io/managed-by=Helm
              release=prometheus-operator
Annotations:  meta.helm.sh/release-name: cluster-autoscaler
              meta.helm.sh/release-namespace: kube-system
...
Spec:
  Endpoints:
    Interval:  10s
    Path:      /metrics
    Port:      http
  Namespace Selector:
    Match Names:
      kube-system
  Selector:
    Match Labels:
      app.kubernetes.io/instance:  cluster-autoscaler
      app.kubernetes.io/name:      aws-cluster-autoscaler
````

Has anyone successfully configured the service monitor using a kube prometheus stack installation and it worked ?

Thanks a lot !

**Comment by moolen** [comment]
Hey! It depends on how you deploy kube-prometheus-stack.

I think you're just missing the label `release=prometheus-operator` on the ServiceMonitor resources.

Try installing external secrets with:
* `--set serviceMonitor.additionalLabels.release=prometheus`
* `--set webhook.serviceMonitor.additionalLabels.release=prometheus`
* `--set certController.serviceMonitor.additionalLabels.release=prometheus`

**Comment by jannotti-glaucio** [comment]
No, the Prometheus server is not identifying the targets.

**Comment by moolen** [comment]
With the following commands i get a kube-prometheus-stack up and running together with eso:

```
$ helm install prometheus prometheus-community/kube-prometheus-stack

$ helm upgrade --install external-secrets \
   external-secrets/external-secrets \
   --set installCRDs=true \
   --set serviceMonitor.enabled=true \
   --set serviceMonitor.additionalLabels.release=prometheus \
   --set webhook.serviceMonitor.enabled=true \
   --set webhook.serviceMonitor.additionalLabels.release=prometheus \
   --set certController.serviceMonitor.enabled=true \
   --set certController.serviceMonitor.additionalLabels.release=prometheus

$ kubectl port-forward svc/prometheus-kube-prometheus-prometheus 9090:9090
```

With that :point_up_2: i can see the targets as expected. 

I'm running `quay.io/prometheus-operator/prometheus-operator:v0.63.0`

**Comment by moolen** [comment]
Do you run with a custom kube-prometheus-stack [namespaceSelector](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L2882)?

Can you post the full kube-prometheus-stack values so i can reproduce the issue?

**Comment by jannotti-glaucio** [comment]
No, I didn´t try to use a namespaceSelector. I will read to understand how 

I used this `values.yaml` on the kube-prometheus-stack creation:
```
prometheus:
prometheusSpec:
  serviceMonitorSelectorNilUsesHelmValues: false
  retention: 10d
  resources:
    requests:
      cpu: 300m
      memory: 1G
    limits:
      cpu: 400m
      memory: 2G
  storageSpec:
    volumeClaimTemplate:
      spec:
        storageClassName: "ebs-sc"
        resources:
          requests:
            storage: 10Gi

alertmanager:
alertmanagerSpec:
  retention: 72h
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: "ebs-sc"
        resources:
          requests:
            storage: 5Gi

grafana:
adminPassword: admin

persistence:
  storageClassName: "ebs-sc"
  size: 5Gi
```

I used this helm chart https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack, version 45.10.1

And used these commands to run the helm:
`helm upgrade -i --create-namespace -n kube-prometheus-stack-hml kube-prometheus-stack . -f values.yaml`

**Comment by moolen** [comment]
Is that indentation intentionally?

```yaml
prometheus:
prometheusSpec: # <--- here
  serviceMonitorSelectorNilUsesHelmValues: false
  retention: 10d
  resources:
    requests:
  # ...
```

With correct indentation i can see the scrape targets:

```yaml
# simplified version 
prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    retention: 10d

alertmanager:
  alertmanagerSpec:
    retention: 72h

grafana:
  adminPassword: admin
```
