### ISSUE TITLE
external-secrets-cert-controller pod can't start when port 8080 is used by another process

### ISSUE THREAD

**Issue by FilimonovEugene** [external-secrets/external-secrets#2292]
**Describe the solution you'd like**
external-secrets-cert-controller should not use 8080 port when metrics scraping is disabled (by default)

**What is the added value?**
external-secrets-cert-controller pods will start in host network with no errors even when node port 8080 is already taken.

**Observations (Constraints, Context, etc):**

This issue occurs when external-secrets-operator deployed with `hostNetwork: true` and port 8080 on the node is already in use by another process.

**Comment by moolen** [comment]
Hey, you can set the listen port for metrics with `--metrics-addr`. Further, you should also differentiate the `--healthz-addr`.

On the helm chart you can set it with `webhook.readinessProbe.port=28374`.

**Comment by isaachui** [comment]
Also ran into this, but we just set the port to something else as a workaround. Will make a PR when I have some time next week.

**Comment by venkatamutyala** [comment]
@isaachui can you provide an example of your values.yaml (assuming you are using the helm chart?). I tried setting it with webhook.port and i'm getting the 8080 error still. Not sure why but it seems like something is getting ignored.

**Comment by isaachui** [comment]
The values file should look something like this. We're running on EKS, so there are some adjustments:
```
webhook:
  hostNetwork: true # needed for EKS use with calico
  port: 10350 # default is 10250 which is what EKS kubelet is listening on
  prometheus:
    service:
      port: 10380
 ```
 Not sure if we needed the prometheus port set, but its set here. 
 
 Sorry never made the PR got swamped. Hopefully sometime soon.
