### ISSUE TITLE
Support 1Password Service Accounts

### ISSUE THREAD

**Issue by cschmatzler** [external-secrets/external-secrets#2312]
**Describe the solution you'd like**
Right now, syncing 1Password secrets is supported through 1Password Connect. This requires running the Connect service. 1Password recently introduced [Service Accounts](https://developer.1password.com/docs/service-accounts/get-started/), which alleviate the need to run something next to ESO.

**What is the added value?**
Hosting an additional service will no longer be required.

**Give us examples of the outcome**
I'd imagine setting up the 1Password provider like
```
onepassword:
      serviceAccountToken:
           secretRef: ...
      # connectHost: https://onepassword-connect-staging
```
would be nice.
