### ISSUE TITLE
SecretSynced error occurs even after getting credentials right

### ISSUE THREAD

**Issue by Jeremy4040** [external-secrets/external-secrets#2316]
Hi all. I used the following yaml files for secret-store and external-secret to integrate vault to external-secrets

```
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-store
spec:
  provider:
    vault:
      server: "http://74.220.18.197:30884/"
      path: "kv"
      version: "v2"
      auth:
        tokenSecretRef:
          name: "vault-token"
          key: "token"
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-token
data:
  token: <root-token>   #root token used for vault login

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-external
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-store
    kind: SecretStore
  target:
    name: vault-aws-secret
  data:
  - secretKey: access_key
    remoteRef:
      key: secret/provider-creds/aws-default
      property: access_key
  data:
  - secretKey: secret_key
    remoteRef:
      key: secret/provider-creds/aws-default
      property: secret_key
```

 
The secret-store works fine
```
NAME                 AGE   STATUS   CAPABILITIES   READY
vault-store          11m   Valid    ReadWrite      True
```

When I give kubectl describe command, it returns the following event
```
Events:
  Type     Reason        Age                From              Message
  ----     ------        ----               ----              -------
  Warning  UpdateFailed  9s (x14 over 53s)  external-secrets  Secret does not exist

```
I have checked the credentials and they are correct. Could you please suggest a solution?
