### ISSUE TITLE
PushSecret vault expecting a JSON (while AWS SM can take any type of data)

### ISSUE THREAD

**Issue by jordiprats** [external-secrets/external-secrets#2320]
**Describe the bug**
I've tried to push the same data (a string) using AWS Secret Manager and Vault. While I'm able to push the data to AWS Secret Manager, when trying to do the same to Vault it fails with an JSON encoding error:

```
status:
  conditions:
  - lastTransitionTime: "2023-05-12T13:28:05Z"
    message: 'set secret failed: could not write remote ref token to target secretstore
      vault-backend: failed to convert value to a valid JSON: invalid character ''e''
      in literal true (expecting ''r'')'
    reason: Errored
    status: "False"
    type: Ready
  syncedPushSecrets:
    SecretStore/vault-backend: {}
```

I've found [this PR that might have caused it](https://github.com/external-secrets/external-secrets/pull/1866/files)

**To Reproduce**
1. provide all relevant manifests

```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: get-token
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  data:
  - secretKey: hello
    remoteRef:
      key: secret/demo
      property: secret
```

2. provide the Kubernetes and ESO version

kubernetes v1.26.3
ESO: v0.8.1

**Expected behavior**

I would expect to be able to point to a different SecretStore to change where the secrets are going to be pushed: Same behavior across providers.

**Comment by moolen** [comment]
Vault can't handle simple strings: every secret is a json object. That's a small but important detail when using the vault provider.

We recently updated [the docs](https://external-secrets.io/v0.8.2/provider/hashicorp-vault/#pushsecret):

> Vault supports PushSecret features which allow you to sync a given kubernetes secret key into a hashicorp vault secret. In order to do so, it is expected that the secret key is a valid JSON object.

**Comment by gusfcarvalho** [comment]
hi @jordiprats ! the issue is that we cannot assume what is the value of the json key when transforming it.

Imagine a kubernetes Secret with values:
```
foo: bar
```

When calling push secret, only `bar` is sent to the provider.

**Comment by jordiprats** [comment]
Hi @gusfcarvalho, that's not exacly what I mean:

For a foo: bar Secret I would expect to be able to push "bar" into vault, not the entire secret. 

To be completely transparent, I have only tested this with AWS Secrets Manager: this creates a secret with the contents of the key:

```
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: set-token
spec:
  refreshInterval: 5s
  secretStoreRefs:
    - name: aws-sm
      kind: SecretStore
  selector:
    secret:
      name: test-sa-token
  data:
    - match:
        secretKey: token
        remoteRef:
          remoteKey: demo/test-sa-token
```

I would expect to be able to just by changing spec.secretStoreRefs to use a different backend.

**Comment by gusfcarvalho** [comment]
That’s the issue. Hashicorp vault does not allow a secret which is not a json. So you simply can’t upload `bar` in it

**Comment by jordiprats** [comment]
Besides, I think it make more sense to the user if the data is transformed into vault as a json like:

```
{"string"}
```

Rather than having to actually provide a json beforehand

**Comment by gusfcarvalho** [comment]
Your example is not a valid Json :)

**Comment by gusfcarvalho** [comment]
Having said all that, this is unfortunately not a bug, rather a limitation of the provider.

There is an underlying feature request here (dataFrom support for PushSecret), but that would still not be a bug 🐛. I’m removing the labels and adding kind/feature

**Comment by moolen** [comment]
I think this can be closed with #2361. Please let me know if something is missing.

**Comment by xoanmi** [comment]
I just tested version `0.9.4` of the operator and the value of the secret key for the PushSecret for Hashicorp Vault still needs to be a valid JSON. Otherwise, it returns an error when tries to unmarshal it:

`Warning  Errored  94s (x16 over 4m19s)  pushsecret  set secret failed: could not write remote ref foo to target secretstore test: error unmarshalling vault secret: invalid character 'b' looking for beginning of value`

The secret that works:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: source-secret
stringData:
  source-key: "{\"foo\":\"bar\"}"
```

The secret that doesn't work:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: source-secret
stringData:
  foo: "bar"
```

IMHO this issue should be reopened as otherwise this feature is mostly unuseful for most of the use cases where the secret is generated by a third party and we do not manage the content. For instance, when we use crossplane.

**Comment by xoanmi** [comment]
Just noticed that there is a hidden parameter (not documented) that allows add/update the secret in Vault from a raw string (not JSON).

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: source-secret
stringData:
  source-key: "{\"foo2\":\"bar2\"}"
  foo: bar3
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: pushsecret-example
spec:
  refreshInterval: 10s
  secretStoreRefs:
    - name: vault-backend
      kind: SecretStore
  selector:
    secret:
      name: source-secret
  data:
    - match:
        secretKey: foo 
        remoteRef:
          remoteKey: my-secret/secret
          property: foo # <-- this is an optional parameter not documented in the API reference
```
