### ISSUE TITLE
Merging error in while deleting PushSecret CR

### ISSUE THREAD

**Issue by sdischer-sap** [external-secrets/external-secrets#2323]
**Describe the bug**
While implementing #1823 I noticed an error log appearing when deleting a PushSecret CR. It looks like the controller is dropping the resources too early for some cleanup to finish. Here is where the error appears: https://github.com/external-secrets/external-secrets/blob/main/pkg/controllers/pushsecret/pushsecret_controller.go#L83
Reproduced it with a working AWS PushSecret CR on the main branch.

**To Reproduce**

1. Create a PushSecret CR with `deletionPolicy: Delete` (e.g. for the aws provider)
2. Apply it in your cluster and let it sync
3. Delete it from your cluster
4. Find the log 

**Expected behavior**
No error log to appear

**Additional context**

Here is my CR:
````
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: aws-pushed-secret
spec:
  refreshInterval: 10s
  deletionPolicy: Delete
  secretStoreRefs:
    - name: secretstore-aws
      kind: SecretStore
  selector:
    secret:
      name: secret-to-push 
  data:
  - match:
      secretKey: username 
      remoteRef:
        remoteKey: pushed-username 
```
