### ISSUE TITLE
VaultDynamicSecret does not work with `/auth/token/create` endpoint

### ISSUE THREAD

**Issue by norman-zon** [external-secrets/external-secrets#2324]
**Describe the bug**
When using to get a Vault Token from the `/auth/token/create` via `VaultDynamicSecret` nothing happens.

**To Reproduce**

1. manifests:

``` yaml
apiVersion: generators.external-secrets.io/v1alpha1
kind: VaultDynamicSecret
metadata:
  name: "vault-token"
spec:
  path: "/auth/token/create/"
  method: "POST"
  provider:
    server: "https://vault.mycompany.de"
    version: "v1"
    auth:
      kubernetes:
        mountPath: "main-cluster"
        role: "baseproject-project-x"
        serviceAccountRef:
          name: "baseproject"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "vault-token"
spec:
  refreshInterval: "5m"
  target:
    name: vault-token
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: VaultDynamicSecret
        name: "vault-token"
```

3.  versions:
 - kubernetes: 1.24.10-gke.2300
 - ESO: v0.8.1

**Expected behavior**
A Vault Token gets pulled from the endpoint and written to the secret.

**Additional context**
There are no logs for either the VaultDynamicSecret or the externalSecret in the ESO (loglevel debug) and the kubernetes manifests show `Events: <none>` for both.

**Comment by moolen** [comment]
FYI @norman-zon i found the issue and have a fix proposed in the PR :point_up_2:

**Comment by norman-zon** [comment]
Thanks for the quick fix.
Unfortunately I still see the same behaviour as before, after adding:

```
spec:
  path: "/auth/token/create"
  method: "POST"
  resultType: "Auth"
```

Still no relevant logs nor kubernetes Events
