### ISSUE TITLE
Gitlab Provider Error: 'unknown field "groupIDs"...'

### ISSUE THREAD

**Issue by J0N47H4N** [external-secrets/external-secrets#2327]
I am currently trying to deploy external-secrets for the gitlab provider. I have followed the instructions found [here](https://external-secrets.io/v0.8.1/provider/gitlab-variables/). However I am getting the below error. I would like to incorporate the ability to use variables from the group level of the project.

`
error validating data: ValidationError(SecretStore.spec.provider.gitlab): unknown field "groupIDs" in io.external-secrets.v1beta1.SecretStore.spec.provider.gitlab
`

1. Create and deploy the below `SecretStore`
```
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gitlab-secret-store
spec:
  provider:
    gitlab:
      url: https://gitlab.mycompany.com/
      auth:
        SecretRef:
          accessToken:
            name: gitlab-token
            key: token
      projectID: "51510"
      groupIDs:
        - "121491"
```
2. Using `Kubernetes 1.22.0` and `ESO 0.8.1`

**Expected behavior**
 I would like to incorporate the ability to use variables from the group level of the project.

**Screenshots**
<img width="716" alt="image" src="https://github.com/external-secrets/external-secrets/assets/5219189/4a17d3d8-7b4f-49a1-86f3-71e437e0f054">
