### ISSUE TITLE
Retrieving secret version isn't working with AWS Parameter Store

### ISSUE THREAD

**Issue by bbremerfullstaq** [external-secrets/external-secrets#2330]
**Describe the bug**
Currently it's not possible to retrieve a specific version of a secret from the AWS Parameter Store.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create secret within the parameter store with name /kubernetes/test:
``` json
{ "value": "Test 1" }
```
2. Create SecretStore and ExternalSecret with the following content (make sure the serviceaccount has access to the parameter store):
```yaml
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secretstore-test
spec:
  provider:
    aws:
      service: ParameterStore
      region: <YourRegion>
      auth:
        jwt:
          serviceAccountRef:
            name: test
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test
spec:
  refreshInterval: 30m
  secretStoreRef:
    kind: SecretStore
    name: secretstore-test
  target:
    name: test
  dataFrom:
    - extract:
        key: /kubernetes/test
        version: '1'
```
3. Check the value of the secret
```bash
kubectl get secret test -o yaml
```
4. Change secret value within the parameter store of secret with name /kubernetes/test to:
``` json
{ "value": "Test 2" }
```
5. Refresh secret and check the value of the secret.
```bash
kubectl get secret test -o yaml
```

**Expected behavior**
The secret value shouldn't change because the version defined in the external secret is version 1.

**Additional context**
We are using ExternalSecrets based on helm version 0.8.1
This is running on EKS version 1.25
Nodes are version 1.25.6
