### ISSUE TITLE
[OLM Operator] Pods do not start on OpenShift / OKD in 0.8.2 due to securityContext

### ISSUE THREAD

**Issue by marbindrakon** [external-secrets/external-secrets#2342]
**Describe the bug**
0.8.2 includes new securityContext defaults (see PR #2250). The new defaults include a static UID of 1000 which requires additional configuration on OpenShift or OKD clusters to allow arbitrary user IDs to be used. Because using a static UID doesn't comply with OpenShift's default "restricted" policy, the ESO pods fail to start. 

If ESO was already installed via OLM prior to 0.8.2, the old version will continue to run while the Deployment fails to roll out until the existing pods are killed for any reason.

**To Reproduce**
1. Run on an OpenShift or OKD cluster (tested with OpenShift 4.12 / Kube 1.25)
2. Install the External Secrets Operator operator via OLM
3. Create an OperatorConfig custom resource using the default settings
```apiVersion: operator.external-secrets.io/v1alpha1
kind: OperatorConfig
metadata:
  name: external-secrets-operator
  namespace: external-secrets-operator
spec:
  # this must be set to false when using olm
  installCRDs: false
  ```
4. Observe that no pods are created and error events are emitted from the ReplicaSet

**Expected behavior**
I would expect the change in defaults to be handled cleanly by the operator on upgrades and pods to start normally as they did in 0.8.1. 

**Screenshots**

**Additional context**
A workaround is to specify securityContext in the OperatorConfig CR and change the runAsUser to null:

```
apiVersion: operator.external-secrets.io/v1alpha1
kind: OperatorConfig
metadata:
  name: external-secrets-operator
  namespace: external-secrets-operator
spec:
  # this must be set to false when using olm
  installCRDs: false
  webhook:
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: null
      seccompProfile:
        type: RuntimeDefault
  certController:
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: null
      seccompProfile:
        type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: null
    seccompProfile:
      type: RuntimeDefault
  ```

**Comment by moolen** [comment]
Hey, thank you for reporting this. I think it's [SCCs](https://docs.okd.io/latest/authentication/managing-security-context-constraints.html) blocking the admission of ESO pods.

However, it is good practice to set runAsUser to a non-zero value. This is documented in the [PSS](https://kubernetes.io/docs/concepts/security/pod-security-standards/) and i don't want to change the defaults in the helm chart.

What can we do in that case? 
If we have to fall back to set it to `null` explicitly we need to find an overlay mechanism the the helm operator to override that specific value.

**Comment by moolen** [comment]
I want to specifically point out that it is our goal to not break our users, so if the installation worked out of the box in the past i don't want to force users into changing anything on their end when upgrading.

**Comment by SDBrett** [comment]
I came across this issue today in deploying external secret operator via OLM on OCP 4.10 and OCP 4.12

On OCP 4.10 I needed to also set `seccompProfile: null` though this was not needed for OCP 4.12.

On the balance between security and functionality I would go the route of `null` unless set by the user. 

Below is the minimum spec I used to get ESO deployed using OLM on OCP 4.12

```
apiVersion: operator.external-secrets.io/v1alpha1
kind: OperatorConfig
metadata:
  name: external-secrets-operator
  namespace: external-secrets-operator
spec:
  webhook:
    securityContext:
      runAsUser: null
  certController:
    securityContext:
      runAsUser: null
  securityContext:
    runAsUser: null
```



> I want to specifically point out that it is our goal to not break our users, so if the installation worked out of the box in the past i don't want to force users into changing anything on their end when upgrading.

The problem is that v0.8.1 is no longer available via OLM, I tried creating a subscription using manual upgrade and starting CSV 0.8.1 and it does not install.

**Comment by GijsvanDulmen** [comment]
We also ran into this issue installing 0.8.2 on OpenShift 4.11. The mentioned https://github.com/external-secrets/external-secrets/issues/2342#issue-1720772076 workaround works.

**Comment by moolen** [comment]
With overrideValues ([see docs](https://sdk.operatorframework.io/docs/building-operators/helm/reference/advanced_features/override_values/)) we can override the values in the `Kind=OperatorConfig`:

```yaml
- group: operator.external-secrets.io
  version: v1alpha1
  kind: OperatorConfig
  chart: helm-charts/external-secrets
  overrideValues:
    installCRDs: false
    # override runAsUser everywhere
    webhook:
      securityContext:
        runAsUser: null
    certController:
      securityContext:
        runAsUser: null
    securityContext:
      runAsUser: null

```

However this removes the ability from the user to specify an explicit value here. See implementation here - it just expands env vars and provides access to sprig template funcs:

https://github.com/operator-framework/operator-sdk/blob/f7d90c430a091279689560715a314fe3d460f184/internal/helm/watches/watches.go#L127-L145

IMHO this should be acceptable for `runAsUser` - as we don't need a specific UID to run ESO. It effectively runs as `nobody` (UID 65534). However for `seccompProfile` this is not acceptable as a user may want to define a custom profile to run the operator. 

OCP 4.10 is EOL in about 2 months from now, we need a way to support this (and preferably earlier versions as well).

I'm going to dig deeper to see if there's a way to modify the upstream default values before packaging the OLM operator :eyes: - any help or suggestions appreciated.
