### ISSUE TITLE
Adding ability to pass session tags (AWS provider)

### ISSUE THREAD

**Issue by nimaft** [external-secrets/external-secrets#2343]
**Is your feature request related to a problem? Please describe.**
This is not an actual problem, but it would make it easier to control access to your secrets when you use AWS provider with Secrets manager in an external AWS account. Imagine you have numerous services running on your cluster and each service has a number of secrets stored in Secrets Manager. Currently we have one service account in each namespace that refers to an IAM role that ESO can assume to talk to the external account and retrieve secret values.
Without session tags, you need to create one role for each service in each namespace to control which secrets they can use (using conditions with tags or secrets name). But if you could pass session tags, you could limit access by matching session tags to secrets tags and only have one IAM role for all namespaces to be assumed by ESO.

**Describe the solution you'd like**
It would be great if you could include session tags in your `SecretStore` object so it can be passed with when using service account's IAM role. For example:
```yaml
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secretsmanager
spec:
  provider:
    aws:
      service: SecretsManager
      # define a specific role to limit access
      # to certain secrets.
      # role is a optional field that
      # can be omitted for test purposes
      role: arn:aws:iam::123456789012:role/external-secrets
      region: eu-central-1
      auth:
        auth:
          jwt:
            serviceAccountRef:
            name: sa-serviceb
          sessiontags:
            - Key: "namespace"
              Value: <namespace name>
```
When you pass session tags with your request, you can modify the IAM role on the target account (where Secrets Manager exists) to only allow access to the secrets that has the same tags as the session tags, you can do the same on Secrets Manager using permission policies.
This approach would eliminate the need to having multiple service account roles and multiple IAM roles on the target account (that can be assumed by SA IAM roles).

**Describe alternatives you've considered**
Currently we have to create one IRSA (IAM role for service account) for each namespace (roughly maps to each service) and have a corresponding IAM role on the external Secrets Manager account to control access to secrets.

**Additional context**
[Information on using session tags](https://docs.aws.amazon.com/IAM/latest/UserGuide/access_tags.html#access_tags_control-requests)
[Secrets manager permission policy](https://docs.aws.amazon.com/secretsmanager/latest/userguide/auth-and-access_examples.html)
[aws:RequestTag/tag-key](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_condition-keys.html#condition-keys-requesttag)

**Comment by moolen** [comment]
Hey, thanks for that detailed write-up. As for the feature this sounds like a valuable addition!

For `jwt` (IRSA) i don't see how to get this to work because the identity provider (Kubernetes in this case) needs to add specific claims to the jwt ([see example here](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_session-tags.html#id_session-tags_adding-assume-role-idp)). And AFAIK there's no way to add custom claims to JWTs with standard Kubernetes APIs (the TokenRequest API in particular).

For `AssumeRole` this is just another parameter to pass into the sdk :+1:

**Comment by nimaft** [comment]
@moolen thank you so much for your response. I believe adding sessions tags to assume role SDK call should do fine, but I'm doing more research just to make sure. Give me a day or two and I will get back to you. This would simplify the process of secrets retrieval a lot when you have tons of services running on your cluster and you want finer access control. Thanks again! :pray:

**Comment by moolen** [comment]
Sounds good!

Now i see how to get it to work with IRSA: by splitting it into two parts. If i understood you correctly, this would be the approach:

![2343 drawio (1)](https://github.com/external-secrets/external-secrets/assets/1709030/62a4869c-6fc7-4201-9bbd-2140a79939af)

To the AssumeRole call (2) we'll need to add SessionTags and that's it. IMO the sessionTags would fit better under `spec.provider.aws`. 
I was thinking if we should apply `sessionTags` to all assume role calls (when defined) or if they should apply to specific calls :thinking:. With the existing design it is hard to make it explicit, applying them to all calls is easier.

```yaml
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secretsmanager
spec:
  provider:
    aws:
      service: SecretsManager
      # assume a role in the target account
      role: arn:aws:iam::{target-account}:role/generic-secret-reader

      # note: a user may define a chain of roles that are assumed in order
      # we can add SessionTags here, too.
      additionalRoles:
      - arn:aws:iam::{example}:role/foo
      - arn:aws:iam::{example}:role/bar

      # Each session tag consists of a key name and an associated value.
      # Session tags are added to __ALL__ assumeRole calls: to both `role` and `additionalRoles`.
      sessionTags:
        - key: namespace
          value: foo

      auth: {} # ...omitted for brevity
```

**Comment by nimaft** [comment]
That is correct. We don’t need to pass tags to IRSA, rather passing them when we assume a role in the target account. However, the architecture I had on my mind was a bit different than yours. I was thinking of using the role reference with service account. So we create an IRSA role on the target account and refer to it in SA definition. similar to this [blog post](https://aws.amazon.com/blogs/containers/cross-account-iam-roles-for-kubernetes-service-accounts/).
Data flow looks like this:
![Architect Diagram](https://github.com/external-secrets/external-secrets/assets/32316839/7566e68d-f8e5-4da1-9424-89f66b86fee4)
Which is achievable by using [EKS Service Account credentials](https://external-secrets.io/v0.8.2/provider/aws-secrets-manager/#eks-service-account-credentials) I believe.
So the service account looks like this:
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<target account ID>:role/<target account IRSA name>
  name: my-serviceaccount
  namespace: myapp
```
And `SecretStore` definition looks like this:
```yaml
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secretstore-sample
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-central-1
      auth:
        jwt:
          serviceAccountRef:
            name: my-serviceaccount
      sessionTags:
        - key: namespace
          value: myapp
```
Regarding adding tags to all sessions, it might be easier to add [transitive tags](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_session-tags.html#id_session-tags_role-chaining). This way you can pick which tags are persistent through role chaining. So your service account definition can look like this:
```yaml
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secretstore-sample
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-central-1
      auth:
        jwt:
          serviceAccountRef:
            name: my-serviceaccount
      sessionTags:
        - key: namespace
          value: foo
      transitiveTags:
        - namespace
```
I'm not a golang pro but I assume if we change assume role API call to take both Tags and TransitiveTagKeys (when available) we would be able to tag all sessions without adding tags to each session separately.
```go
    // Optional, you can pass tag key-value pairs to your session. These tags are called session tags.
    Tags []*sts.Tag

    // A list of keys for session tags that you want to set as transitive.
    // If you set a tag key as transitive, the corresponding key and value passes to subsequent sessions in a role chain.
    TransitiveTagKeys []*string
```




Thank you!
