### ISSUE TITLE
ClusterSecretStore vault certificate error message templating bug

### ISSUE THREAD

**Issue by crazyhouse33** [external-secrets/external-secrets#2347]
**Describe the bug**
There seem to be a bug with the tranmission of errors with vault provider when using CaBundle. This lead to unusable error message: 

````
minikube version
minikube version: v1.30.1
commit: 08896fd1dc362c097c925146c4a0d0dac715ace0
````

````
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  labels:
    app: my-app
    app.kubernetes.io/component: api
    app.kubernetes.io/created-by: compagny
    app.kubernetes.io/managed-by: something
    app.kubernetes.io/name: app
    app.kubernetes.io/part-of: team
    env: dev
  name: vault-store
spec:
  provider:
    vault:
      auth:
        ldap:
          path: ldap
          secretRef:
            key: password
            name: vault-creds
          username: user
      caBundle: blabla==
      server: https://thevaultserver
      version: theversionweuse
````
This result in:
```
kubectl describe clustersecretstores.external-secrets.io
...
Status:
  Conditions:
    Last Transition Time:  2023-05-24T07:46:41Z
    Message:               unable to create client
    Reason:                InvalidProviderConfig
    Status:                False
    Type:                  Ready
Events:
  Type     Reason                 Age                 From                  Message
  ----     ------                 ----                ----                  -------
  Warning  InvalidProviderConfig  11m (x22 over 82m)  cluster-secret-store  cannot set Vault CA certificate: %w
```
**Expected behavior**
I expect the certificate error to be printed correctly and not just %w
