### ISSUE TITLE
Kubernetes Secretstore ServerUrl Provider 

### ISSUE THREAD

**Issue by sdischer-sap** [external-secrets/external-secrets#2356]
**Is your feature request related to a problem? Please describe.**
Some of our use cases include provisioning kubernetes clusters dynamically. In those cases it would be nice to be able to reference the server url of a SecretStore from somewhere, instead of defining it statically within the SecretStore CR. 

**Describe the solution you'd like**
For CA data there is already a way to specify the data directly in the CR or reference it from either a ConfigMap or Secret. A natural solution could be to provider similar means to referencing the server URL. So I guess something like this:

```
...
server: https://example.org # define hardcoded as is OR
serverProvider: # refernence from ConfigMap or Secret similar to caProvider
  type: Secret # or ConfigMap
  name: kube-secret
  key: serverUrl
...
```

**Describe alternatives you've considered**
Open for other approaches of cause.

**Comment by sdischer-sap** [comment]
Happy to hear that you are open for reading a whole `kubeconfig` from a Secret. 
Thats actually even closer to our use case. I guess having both of those options eventually might be the most versatile.

Yes sorry you are right, I didn't double check the CRD and my memory fooled me ;) So yes what I meant is:
```yaml
server:
  url: "http://example.com"
  urlProvider:
    type: "Secret"
    name: "my-url"
    key: "url"
  caBundle: "LS0tLS1CRUd..."
  caProvider:
    type: "Secret"
    name: "my-tls"
    key: "ca.crt"
auth: {} # ...
remoteNamepace: "my-remote"
```
