### ISSUE TITLE
ExternalSecret with name over 92 characters fails to sync with "Too long: must have at most 128 bytes" error

### ISSUE THREAD

**Issue by scartledge** [external-secrets/external-secrets#2362]
**Describe the bug**
ExternalSecret with name over 92 characters fails to sync with one of the following errors (depending on whether the associated Kube secret is being created or updated):
```
CreateOptions.meta.k8s.io "" is invalid: fieldManager: Too long: must have at most 128 bytes
UpdateOptions.meta.k8s.io "" is invalid: fieldManager: Too long: must have at most 128 bytes
```

**To Reproduce**

External Secrets Operator v0.8.2
Kubenetes: v1.23.17 or v1.25.10

1. Create an ExternalSecret definition with a name that is over 92 characters long:
```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: my-external-secret-with-a-long-name-will-fail-to-sync-in-external-secets-802-but-not-801-help
  namespace: default
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: 11111111-1111-1111-1111-111111111111
    secretKey: value
  secretStoreRef:
    kind: ClusterSecretStore
    name: my-secret-store
  target:
    name: my-external-secret-with-a-long-name-will-fail-to-sync
```
2. Apply the above ExternalSecret configuration:
```
kubectl apply -f es.yaml
```
3. Describe the created ExternalSecret:
```
kubectl describe externalsecret -ndefault my-external-secret-with-a-long-name-will-fail-to-sync-in-external-secets-802-but-not-801-help
```
4. In the describe output, notice the following event:
```
Events:
  Type     Reason        Age               From              Message
  ----     ------        ----              ----              -------
  Warning  UpdateFailed  1s (x10 over 6s)  external-secrets  CreateOptions.meta.k8s.io "" is invalid: fieldManager: Too long: must have at most 128 bytes
```
5. Try to list the Kubernetes secret that is associated with the ExternalSecret and notice that the Kubernetes secret has not been created:
```
$ kubectl get secret -ndefault my-external-secret-with-a-long-name-will-fail-to-sync-in-external-secets-802-but-not-801-help
Error from server (NotFound): secrets "my-external-secret-with-a-long-name-will-fail-to-sync-in-external-secets-802-but-not-801-help" not found
```
6. Repeat steps 1 and 2, but this time shorten the name by one character. The sync will now work and the associated Kubernetes secret created.

**Expected behavior**
ExternalSecret with name over 92 characters to sync successfully and create the associated Kubernetes secret.

**Screenshots**
Not applicable

**Additional context**
It appears that the problem was introduced in external-secrets v0.8.2 as the problem can not be recreated in external-secrets v0.8.1.
