### ISSUE TITLE
ClusterExternalSecrets become stale and dont update ExternalSecret Objects

### ISSUE THREAD

**Issue by nnachefski** [external-secrets/external-secrets#2371]
Working with the ESO, i find that ExternalSecret objects are not being updated by the ClusterExternalSecret objects.

Currently using: 
external-secrets-operator.v0.8.3

If i deploy the ESO operator configured to pull secrets from Hashicorp Vault (community edition) i find that the secrets are not being populated to their configured namespaces.  If i "reboot" the 'vault-config-external-secrets' pod, then all the secrets start getting populated correctly.  

This is what i do to 'reboot' the pod
`$OC_CLIENT scale deploy vault-config-external-secrets --replicas=0 -n external-secrets && $OC_CLIENT scale deploy vault-config-external-secrets --replicas=1 -n external-secrets

and here is a screenshot after it starts working:
![image](https://github.com/external-secrets/external-secrets/assets/5325779/f9ab5518-a2c0-46a4-859e-e3649d3fc8d3)

`

**Comment by moolen** [comment]
Hey, can you please paste your ClusterExternalSecret manifest? What does a `kubectl -n dev describe es git-ssh-secret` show? are there events?

**Comment by nnachefski** [comment]
i think this might be the culprit:

# oc logs vault-config-external-secrets-cert-controller-6bbc47b54d-f2fn9 -n external-secrets

```
{"level":"info","ts":1686393725.2129834,"logger":"controllers.webhook-certs-updater","msg":"ignoring webhook due to missing labels","Webhookconfig":"/controlplanemachineset.machine.openshift.io","external-secrets.io/component":"webhook"}
{"level":"info","ts":1686393725.2233844,"logger":"controllers.webhook-certs-updater","msg":"ignoring webhook due to missing labels","Webhookconfig":"/controlplanemachineset.machine.openshift.io","external-secrets.io/component":"webhook"}
{"level":"info","ts":1686393745.0572226,"logger":"controllers.webhook-certs-updater","msg":"ignoring webhook due to missing labels","Webhookconfig":"/performance-addon-operator","external-secrets.io/component":"webhook"}
{"level":"info","ts":1686393745.0669942,"logger":"controllers.webhook-certs-updater","msg":"ignoring webhook due to missing labels","Webhookconfig":"/performance-addon-operator","external-secrets.io/component":"webhook"}

```

**Comment by moolen** [comment]
this is fine, cert-controller ignores webhooks he isn't supposed to modify.

**Comment by nnachefski** [comment]
The issue manifests when i deploy the external-secrets-operator before deploying the workloads.  If i deploy a workloads namespace prior to deploying the ESO, then the secrets get populated.  But if i deploy the namespace after the ESO, the secrets dont get populated.  I have to cycle the vault-config-external-secrets deploy, then it catches up and all the secrets get populated as expected.

**Comment by moolen** [comment]
Can you please share your `ClusterSecretStore` manifest and the namespaces?

The CSS has a `spec.refreshInterval`, please set that to a low value (e.g. 30s). Then at max it should take about 30s after the NS has been created that the ExternalSecret shows up

**Comment by nnachefski** [comment]
Here's an example of one.  It wont show up at all (even after the interval is hit).  I have to cycle the aforementioned pod for it to show up.

```
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: git-ssh-secret
spec:
  externalSecretName: "git-ssh-secret"
  namespaceSelector:
    matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: In
        values:
          - dev
          - gitops
          - pipelines
  externalSecretSpec:
    secretStoreRef:
      name: vault-backend
      kind: ClusterSecretStore
    refreshInterval: "15s"
    target:
      creationPolicy: Owner
      template:
        type: kubernetes.io/ssh-auth
        metadata:
          annotations:
            tekton.dev/git-0: gitlab.***.*****.******
    data:
      - secretKey: ssh-privatekey
        remoteRef:
          key: secret/git-ssh-secret
          property: ssh-privatekey
```

**Comment by nnachefski** [comment]
And here is the namespace as requested (some things omitted to keep it clean):

```
kind: Project
apiVersion: project.openshift.io/v1
metadata:
  name: openshift-pipelines
  labels:
    app.kubernetes.io/part-of: tekton-pipelines
    app.kubernetes.io/instance: default
    operator.tekton.dev/disable-proxy: 'true'
    operator.tekton.dev/targetNamespace: 'true'
    kubernetes.io/metadata.name: openshift-pipelines
    openshift.io/cluster-monitoring: 'true'
    app.kubernetes.io/component: resolvers
    operator.tekton.dev/operand-name: tektoncd-pipelines
    olm.operatorgroup.uid/aed037e5-ab74-4cdb-bf3d-1d7fde19d58e: ''
    pod-security.kubernetes.io/enforce: restricted
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
    ...
    openshift.io/sa.scc.mcs: 's0:c30,c0'
    openshift.io/sa.scc.supplemental-groups: 1000870000/10000
    openshift.io/sa.scc.uid-range: 1000870000/10000
    operator.tekton.dev/last-applied-hash: fbad8a4b6fcbcf8d3433c2dc7be7171bf13ae4f886140b85802467716da037a7
  ownerReferences:
    - apiVersion: operator.tekton.dev/v1alpha1
      kind: TektonPipeline
      name: pipeline
      uid: 2245e9b8-9af6-4e02-98ad-c55211c5752b
      controller: true
      blockOwnerDeletion: true
spec:
  finalizers:
    - kubernetes
status:
  phase: Active
```

**Comment by nnachefski** [comment]
Basically, if i deploy the ESO after i deploy my workloads then it populates the secrets just fine.  But, if i do the ESO first then none of the secrets populate until i cycle the pod.

**Comment by moolen** [comment]
You didn't set the `spec.refreshTime` on the ClusterExternalSecret (sorry, not the refreshInterval, got confused there :sweat:). Once you set that it will reconcile as defined in the refreshInterval and provision new ExternalSecret resources in the newly created namespaces.

**Comment by nnachefski** [comment]
ah ok, so something like this?   

Should the refreshTime and refreshInterval match?

```
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: git-ssh-secret
spec:
  refreshTime: "30s"
  externalSecretName: "git-ssh-secret"
  namespaceSelector:
    matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: In
        values:
          - dev
          - gitops
          - pipelines
  externalSecretSpec:
    secretStoreRef:
      name: vault-backend
      kind: ClusterSecretStore
    refreshInterval: "15s"
    target:
      creationPolicy: Owner
      template:
        type: kubernetes.io/ssh-auth
        metadata:
          annotations:
            tekton.dev/git-0: gitlab.lab.arrowglance.io
    data:
      - secretKey: ssh-privatekey
        remoteRef:
          key: secret/git-ssh-secret
          property: ssh-privatekey

```
