### ISSUE TITLE
Help using PushSecrets and Kubernetes

### ISSUE THREAD

**Issue by stdmje** [external-secrets/external-secrets#2385]
Hi all,
I am trying to sync a secret between namespaces using the PushSecret CRD but i am not able to do that or maybe i am not understanding the documentation.

My idea is to sync the secret `live-postgres-pguser-airflow` from namespace `live-postgres` to namespace `airflow`

**To Reproduce**
1. Create all the required RBAC in the target namespace. This RBAC is used by the SecretStore.
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eso-kubernetes
  namespace: airflow
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: eso-kubernetes-secret
  namespace: airflow
  annotations:
    kubernetes.io/service-account.name: "eso-kubernetes"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eso-kubernetes
rules:
- apiGroups: [""]
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - authorization.k8s.io
  resources:
  - selfsubjectrulesreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eso-kubernetes-airflow
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: eso-kubernetes
subjects:
- kind: ServiceAccount
  name: eso-kubernetes
  namespace: airflow
---
```
2. Create the SecretStore in the target namespace:
```
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: kubernetes-airflow
  namespace: airflow
spec:
  provider:
    kubernetes:
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
      auth:
        serviceAccount:
          name: eso-kubernetes
```
3. Create the PushSecret resource in the source namespace:
```
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: test
  namespace: live-postgres
spec:
  refreshInterval: 10s
  secretStoreRefs:
    - name: kubernetes-airflow
      kind: SecretStore
  selector:
    secret:
      name: live-postgres-pguser-airflow
  data:
  - match:
      secretKey: pgbouncer-uri
      remoteRef:
        remoteKey: live-postgres-pguser-airflow
        property: connection
```

Now the pushSecret is in Errored status because of:
```
  Type     Reason   Age                From        Message
  ----     ------   ----               ----        -------
  Warning  Errored  6s (x12 over 16s)  pushsecret  could not get SecretStore "kubernetes-airflow", SecretStore.external-secrets.io "kubernetes-airflow" not found
```

I understand that a SecretStore is a namespace scoped resource and in fact if i change that SecretStore to be a ClusterSecretStore everything will work fine and the source secret will be synced in ALL the namespaces but i don't want that.

Am i missing something? Can i get some help for syncing a secret between namespaces?

Thanks a lot!
