### ISSUE TITLE
Can I mount external secrets as volume in a pod

### ISSUE THREAD

**Issue by CourageOI** [external-secrets/external-secrets#2390]
How can I mount secrets from externalSecrets as volumes in a k8s pod instead of just as environmental variables

**Comment by moolen** [comment]
Hey @CourageOI, you can find that in the Kubernetes docs here: https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-files-from-a-pod.

ESO just creates `Kind=Secret` resources that can be consumed with the usual secret APIs, e.g.:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: mypod
    image: redis
    volumeMounts:
    - name: foo
      mountPath: "/etc/foo"
      readOnly: true
  volumes:
  - name: foo
    secret:
      secretName: mysecret

```
