### ISSUE TITLE
Annotated example of ExternalSecret missing generator use case

### ISSUE THREAD

**Issue by mloskot** [external-secrets/external-secrets#2392]
I think it would be good if the annotated example on https://external-secrets.io/v0.8.3/api/externalsecret/ presented possible structure under `dataFrom` for use of a generator, that is,

```yaml
 dataFrom:
  - sourceRef:
      generatorRef:
...
```
