### ISSUE TITLE
Using the SecretStore with azurekv provider in the USGovernmentCloud does not seem to work

### ISSUE THREAD

**Issue by miaooss** [external-secrets/external-secrets#2397]
**Describe the bug**
Using the SecretStore with azurekv provider in the USGovernmentCloud does not seem to work

In the ArgoCd helm chart the environmentType get reverted all the time.

The ExternalSecret binding to the store returns this error:

`keyvault.BaseClient#GetSecret: Failure responding to request: StatusCode=401 -- Original Error: autorest/azure: Service returned an error. Status=401 Code="Unauthorized" Message="AKV10022: Invalid audience. Expected https://vault.usgovcloudapi.net, found: https://vault.azure.net."`

```
apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: store-name
  namespace: namespace
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      environmentType: USGovernmentCloud
      serviceAccountRef:
        name: name_of_service_account
```

**To Reproduce**
1. Create the Secret store in USGOv
2. Try to read a secret from keyvault using an "ExternalSecret" binded to the secret store

**Expected behavior**
I should be able to use the `environmentType` and read the secret from the keyvault

**Note**
If I do the same configuration in AzureCloud (Public) without the environmentType parameters It's working fine
