### ISSUE TITLE
Clear text secrets in ESO logs

### ISSUE THREAD

**Issue by jordiprats** [external-secrets/external-secrets#2401]
**Describe the bug**

When there's a mistake referencing a secret with the the ExternalSecret object, it logs into the logs the credentials it is using:

```
external-secrets-main-7f56bc8b9f-qd55g external-secrets {"level":"error","ts":1686216778.8303626,"msg":"Reconciler error","controller":"externalsecret","controllerGroup":"external-secrets.io","controllerKind":"ExternalSecret","ExternalSecret":{"name":"_REDACTED_","namespace":"_REDACTED_"},"namespace":"_REDACTED_","name":"_REDACTED_","reconcileID":"b052d569-8c42-4238-9e1d-2d9ca5848737","error":"IncompleteSignature: '\"_REDACTED_\"' not a valid key=value pair (missing equal-sign) in Authorization header: 'AWS4-HMAC-SHA256 Credential={\"UserName\": \"_REDACTED_\", \"AccessKeyId\": \"_REDACTED_\", \"Status\": \"_REDACTED_\", \"SecretAccessKey\": \"_REDACTED_\", \"CreateDate\": \"_REDACTED_\", \"DeleteOn\": \"_REDACTED_\"}/20230608/us-east-1/sts/aws4_request, SignedHeaders=content-length;content-type;host;x-amz-date, Signature=f623777514cafa003df7f48353c822dacfde3a498dc5ae964efba5e393ae2496'.\n\tstatus code: 400, ","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:235"}
```

**To Reproduce**

1. relevant manifests

SecretStore

```
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: demo-ss
spec:
  provider:
    aws:
      auth:
        secretRef:
          accessKeyIDSecretRef:
            key: AccessKeyId
            name: demo-aws
          secretAccessKeySecretRef:
            key: SecretAccessKey
            name: demo-aws
      region: eu-central-1
      role: arn:aws:iam::_REDACTED_:role/_REDACTED_
      service: SecretsManager
  retrySettings:
    maxRetries: 5
    retryInterval: 10s
```

ExternalSecret

```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: demo-aws
spec:
  data:
  - remoteRef:
      key: /AWSCreds
      property: AccessKeyId
      version: AWSCURRENT
    secretKey: AccessKeyId
  - remoteRef:
      key: /AWSCreds
      property: SecretAccessKey
      version: AWSCURRENT
    secretKey: SecretAccessKey
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: demo-ss
  target:
    creationPolicy: Merge
    deletionPolicy: Retain
    template:
      metadata:
        labels: {}
      type: Opaque
```

Apply first this manifest, so that everything works, then update the ExternalSecret removing the targeting a the property like this:

```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: demo-aws
spec:
  data:
  - remoteRef:
      key: /AWSCreds
    secretKey: AccessKeyId
  - remoteRef:
      key: /AWSCreds
    secretKey: SecretAccessKey
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: demo-ss
  target:
    creationPolicy: Merge
    deletionPolicy: Retain
    template:
      metadata:
        labels: {}
      type: Opaque
```

3. Kubernetes and ESO version

Kubernetes: v1.25.8+37a9a08
ESO: 0.8.3

**Expected behavior**
Redacted or excluded secrets for **error** level, maybe changing the level to debug would be just fine
