### ISSUE TITLE
Support other secret types for IBM Cloud SM

### ISSUE THREAD

**Issue by knelasevero** [external-secrets/external-secrets#242]
Right now the PR (#235) that we have open only implements the support for `type=arbritary` secrets. We want to support other types

AC:

- Support User creds
- Support Certs

**Comment by tpolekhin** [comment]
Hello, @knelasevero 
Thank you for implementing a support for IBM Cloud Secrets Manager!
I have successfully tested it on my Kubernetes cluster.

Regarding other secret types: I was looking at the code and crd structure to find a way to provide a secret type, but can't seem to find a good place to do this. 
I don't want to configure this in the SecretStore CRD because this would require us to create 4 different SecretStores to support all available secret types `arbitrary`, `username_password`, `iam_credentials` and `imported_cert`. 
I would rather detect this somehow in the code (best scenario) or define secret type in the ExternalSecret CRD.

What are your thoughts on this? Maybe you already discussed this with the team?

**Comment by moolen** [comment]
We've had the same issue with the azure keyvault provider. They're called `object-types` there. We went with the following solution: We prefixed the `remoteRef.key` with an object type (or secret type). I think for `v1alpha1` this is the way to go. For the future (maybe?) should embed an `objectType` or `secretType` into the crd to make that explicit.

```yaml
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: example
spec:
  # ...
  data:
  - secretKey: dev-another-secret-test
    remoteRef:
      # {object-type}/{object-name}
      # object type can be omitted, it defaults to type=secret
      key: secret/dev-secret-test

```
