### ISSUE TITLE
Missing ENV variables with Azure Workload Identity Configuration

### ISSUE THREAD

**Issue by mruoss** [external-secrets/external-secrets#2436]
**Describe the bug**

I'm trying to get Azure Workload Identity authentication to work. I'm following the [documentation for mounted service account](https://external-secrets.io/v0.8.3/provider/azure-key-vault/#mounted-service-account). The service account used for the deployment (SA name is `external-secret`) is configured correctly and its token is mounted to the pod. However, I'm getting the following error in the log:

```
could not get provider client: missing environment variables. AZURE_CLIENT_ID, AZURE_TENANT_ID and AZURE_FEDERATED_TOKEN_FILE must be set.
```

I couldn't find any documentation regarding these env variables. From the docs my impression was that setting up the federated identity credentials for the default SA should work. 

**To Reproduce**

Here's the manifest for my SA:

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: xxxxxxx   
    azure.workload.identity/tenant-id: xxxxxxx
  labels:
    app.kubernetes.io/instance: external-secrets
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/version: v0.8.3
    argocd.argoproj.io/instance: external-secrets
    helm.sh/chart: external-secrets-0.8.3
  name: external-secrets
  namespace: external-secrets
```

Secret Store:

 ```yaml
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: azure-kv-store
  namespace: default
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: "https://yadda-yadda-yadda.vault.azure.net/"
status:
  conditions:
  - lastTransitionTime: "2023-06-19T16:51:58Z"
    message: unable to create client
    reason: InvalidProviderConfig
    status: "False"
    type: Ready
```

I can see this SA being used in the deployment, too.

**Expected behavior**

I'd expect the ESO to connect to the KV.

**Comment by mruoss** [comment]
I found the solution by searching for `AZURE_FEDERATED_TOKEN_FILE` on the [Azure Workload Identity documentation](https://azure.github.io/azure-workload-identity/docs/quick-start.html).

I have forgot to add the required label to the pod:

```yaml
kind: Pod
metadata:
  name: external-secrets
  labels:
    azure.workload.identity/use: "true"
```

or in my case adding it in the helm chart:

```yaml
podLabels:
  azure.workload.identity/use: "true"
```

I think adding this to the documentation would help many people.
