### ISSUE TITLE
After Kubernetes upgrade, secret syncs fine but everything that tries to use it gets 401 error

### ISSUE THREAD

**Issue by tdevopsottawa** [external-secrets/external-secrets#2439]
**Describe the bug**
I recently upgraded my cluster (running in AKS) from 1.23 to 1.24. As a result of the upgrade, an external secret stopped working. The secret in question is a GHCR access key. The secret itself is fine (its status is SecretSynced) but every deployment that uses the secret to pull from GHCR now complains of a 401 Unauthorized error when trying to pull images.

**To Reproduce**
Kubernetes version 1.24.10 and ESO version 1.6.1

```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: my-registry
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: my-registry-pull-secret
      secretKey: .dockerconfigjson
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: my-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      type: kubernetes.io/dockerconfigjson
----
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: <redacted>
    azure.workload.identity/tenant-id: <redacted>
  labels:
    azure.workload.identity/use: "true"
  name: my-secret-store-sa
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: my-secret-store
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: https://<redacted>.vault.azure.net/
      serviceAccountRef:
        name: my-secret-store-sa
```

**Expected behavior**
That everything would continue working after the upgrade, especially as the status of the secret is still marked as "SecretSynced".
