### ISSUE TITLE
PushSecrets with Hashicorp Vault kv  v1 doesn't work

### ISSUE THREAD

**Issue by solidnerd** [external-secrets/external-secrets#2446]
**Describe the bug**

External Secrets Operator returns secret not found with Hashicorp Vault Provider and kv store in v1 when using a PushSecret

```
set secret failed: could not write remote ref cert to target secretstore writer: secret not found
```

**To Reproduce**

```
apiVersion: v1
kind: Secret
metadata:
  name: example-tls-secret-opaque
type: Opaque
data:
  cert: ewogICJ0bHMuY3J0IjogImZvbyIsCiAgInRscy5rZXkiOiAiYmFyIgp9Cg==
```

```
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: example-tls-secret # Customisable
spec:
  refreshInterval: 10s # Refresh interval for which push secret will reconcile
  secretStoreRefs: # A list of secret stores to push secrets to
    - name: writer
      kind: ClusterSecretStore
  selector:
    secret:
      name: example-tls-secret-opaque # Source Kubernetes secret to be pushed
  data:
    - match:
        secretKey: cert # Source Kubernetes secret key to be pushed
        remoteRef:
          remoteKey: dev/example-tls-secret # Remote reference (where the secret is going to be pushed)
```

```
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: writer
spec:
  provider:
    vault:
      auth:
        kubernetes:
          mountPath: kubernetes/example-cluster
          role: external-secrets-rw
          serviceAccountRef:
            name: "external-secrets-rw"
            namespace: "external-secrets"
      path: "kv"
      server: https://vault.example.com
      version: "v1"
```
Store is also validated
```
Status:
  Capabilities:  ReadWrite
  Conditions:
    Last Transition Time:  2023-06-23T03:18:27Z
    Message:               store validated
    Reason:                Valid
    Status:                True
    Type:                  Ready
Events:
  Type    Reason  Age                 From                  Message
  ----    ------  ----                ----                  -------
  Normal  Valid   116s (x8 over 29m)  cluster-secret-store  store validated
```

We are using ESO in `v0.9.0` and k8s in version `v1.26.4`

**Expected behavior**

Since we specified in the clustersecretstore v1, it should also be respected by the PushSecret. So that there will be no error at all.

**Screenshots**

**Additional context**
During the pushsecret, we don't set up any vault version, which results in switching to secret engine v2 by default and not v1. https://github.com/external-secrets/external-secrets/blob/main/pkg/provider/vault/vault.go#L471

The main difference between those versions is that v2 has different paths and versioning for secrets which v1 has not.

**Comment by gusfcarvalho** [comment]
Hi @solidnerd. This is by design as there is no way to control which secrets are owned by external-secrets on hashi kv v1 (as there is no metadata bound to the secret).

**Comment by gusfcarvalho** [comment]
If you have set up v1 in your manifest, you would specifically see an error that PushSecret does not support v1 stores.

**Comment by gusfcarvalho** [comment]
Or at least the check used to be there when the feature was first implemented

**Comment by solidnerd** [comment]
Hey @gusfcarvalho, 
Thanks for clarifying this to me. 

In the meantime, I tested it already with a hashi kv v2, and it worked smoothly 👍
Since we are also using some hashi kv v1, it would be nice to use them, but yeah, you are right. Getting metadata is a problem. You could do it only by mixing up the secret and adding a metadata field, which would change it. External secrets would manipulate every secret that its touches.

Let's make it more evident in the documentation. I will make a PR on it.

By the way, there is no that v1 doesn't support push secrets in the operator. We could add this as well.

**Comment by solidnerd** [comment]
I will gonna close this already.

**Comment by shenshanyoumu** [comment]
> Hey @gusfcarvalho, Thanks for clarifying this to me.
> 
> In the meantime, I tested it already with a hashi kv v2, and it worked smoothly 👍 Since we are also using some hashi kv v1, it would be nice to use them, but yeah, you are right. Getting metadata is a problem. You could do it only by mixing up the secret and adding a metadata field, which would change it. External secrets would manipulate every secret that its touches.
> 
> Let's make it more evident in the documentation. I will make a PR on it.
> 
> By the way, there is no that v1 doesn't support push secrets in the operator. We could add this as well.


Hi @solidnerd , actually I use pushSecret to push k8s secret to vault namespace code as below:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: push-secret-demo
  namespace: test-demo
data:
  sourcekey1: IntcImZvb1wiOlwiYmFyXCJ9Ig== # Needs to be a JSON
  sourcekey2: YmFy  # Could be a plain string
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: qa-api-server-tls-push-secret
  namespace: test-demo
spec:
  refreshInterval: 10s
  secretStoreRefs:
    - name: my-secret-store
      kind: SecretStore
  selector:
    secret:
      name: push-secret-demo
  data:
    - match:
        secretKey: sourcekey1
        remoteRef:
          remoteKey: qa/api-server
          property: ca_cert_backup
    - match:
        secretKey: sourcekey2
        remoteRef:
          remoteKey: qa/api-server
          property: key_backup
````

but always error: 
"set secret failed: could not write remote ref sourcekey1 to target
secretstore my-secret-store: secret not managed by external-secrets", can yo help to check anything wrong? thanks
