### ISSUE TITLE
Random fail with HC Vault

### ISSUE THREAD

**Issue by Gianluca755** [external-secrets/external-secrets#2467]
The secret store fails randomly for extended periods of time with
```
Code: 400. Errors:
* error validating token: error verifying token signature: failed to verify id token signature
```

Running on AWS EKS (k8s 1.24) and vault 1.7.0, ESO helm chart 0.8.0.

Logs of the operator:
```
{"level":"error","ts":1688449611.9498436,"msg":"Reconciler error","controller":"secretstore","controllerGroup":"external-secrets.io","controllerKind":"SecretStore","SecretStore":{"name":"secretstore","namespace":"dev-api"},"namespace":"dev-api","name":"secretstore","reconcileID":"d3f563bb-4abe-4b75-ab93-5ea02530eb07","error":"could not get provider client: Error making API request.\n\nURL: PUT https://vault-dev.<...>/v1/auth/jwt-k8s-dev/login\nCode: 400. Errors:\n\n* error validating token: error verifying token signature: failed to verify id token signature","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:235"}
```

Thanks,
Gianluca

**Comment by moolen** [comment]
Hey, can you share your SecretStore and Vault authentication configuration?
To me this looks like a authentication misconfiguration on vault side.

**Comment by Gianluca755** [comment]
I had the same suspicion, but I'm not sure. A way to fix it is to delete and recreate the config on vault.
The config was done with terraform:
```
resource "vault_jwt_auth_backend" "k8s_dev" {
  provider = vault.dev

  description        = "JWT auth for External Secret Operator for Kubernetes"
  oidc_discovery_url = data.terraform_remote_state.aws_eks_dev.outputs.development_eks.cluster_oidc_issuer_url
  path               = "jwt-k8s-dev"
  tune {
    default_lease_ttl            = "24h"
    max_lease_ttl                = "24h"
    allowed_response_headers     = []
    audit_non_hmac_request_keys  = []
    audit_non_hmac_response_keys = []
    listing_visibility           = "hidden"
    passthrough_request_headers  = []
    token_type                   = "default-service"
  }
}
```

```
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secretstore
spec:
  provider:
    vault:
      auth:
        jwt:
          kubernetesServiceAccountToken:
            audiences:
            - argocd
            serviceAccountRef:
              name: ci-serviceacc-argocd
          path: jwt-k8s-dev
          role: eso-role-argocd-develop
      path: ...
      server: https://vault-dev..../
      version: v2
status:
  capabilities: ReadWrite
  conditions:
  - lastTransitionTime: "2023-07-04T09:23:34Z"
    message: store validated
    reason: Valid
    status: "True"
    type: Ready
```
