### ISSUE TITLE
Installation of external-secrets with kustomize does not populate external-secrets-webhook secret

### ISSUE THREAD

**Issue by joseronierison** [external-secrets/external-secrets#2474]
**Describe the bug**
We are setting up the external-secrets using kustomize, but it is failing to start the external-secrets-webhook due to a lack of values in external-secrets-webhook secret.

This is the error logs in of `external-secrets-webhook` pod:
´´´
{"level":"error","ts":1688741970.212487,"logger":"setup","msg":"invalid certs. retrying...","error":"stat /tmp/certs/tls.crt: no such file or directory","stacktrace":"..."}
´´´

**To Reproduce**
Use a kustomization.yaml file like this:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-secrets
resources:
  - namespace.yaml
 
helmCharts:
- name: external-secrets
  releaseName: external-secrets
  repo: https://charts.external-secrets.io
```
namespace.yaml file:
```
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
```

Use the following command to apply the kustomization file:
`kustomize build . --enable-helm | kubectl apply -f -`

It seems the it is not triggering the function to populate the values secrets values.

And the pods are in this state:
```
> kubectl get pods -n external-secrets
NAME                                                READY   STATUS             RESTARTS          AGE
external-secrets-66968d49b4-hgr2w                   1/1     Running            0                 35h
external-secrets-cert-controller-6db44898bd-znjh5   0/1     Running            0                 35h
external-secrets-webhook-6d5c7d847c-4nbx5           0/1     CrashLoopBackOff   202 (2m12s ago)   23h
```

The secret is created without data.
```
> kubectl get secret external-secrets-webhook -o yaml -n external-secrets
apiVersion: v1
kind: Secret
metadata:
  name: external-secrets-webhook
  namespace: external-secrets
type: Opaque
```

**Expected behavior**
The external-secrets installation works with kustomize. :D

**Additional context**
We have tried to install it using the helm command in the same EKS cluster and it worked correctly.
