### ISSUE TITLE
Advanced templating v2 toYaml not converting secret from json to yaml

### ISSUE THREAD

**Issue by MirandaRompoti** [external-secrets/external-secrets#2484]
**Describe the bug**
I am trying to generate a secret the value of which is saved as json on Hashicorp vault. I want the result to be a kubernetes secret with multiple data which will be of yaml format.

**To Reproduce**
1. provide all relevant manifests

Secret saved in Hashicorp Vault:
secret key:
`secrets-options`
secret value: 
```
{
	"glossary": {
		"title": "example glossary",
		"title2": "example glossary"
	},
        "glossary2": {
		"title": "example glossary",
		"title2": "example glossary"
        }
}
```

External Secrets:

```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  namespace: {{ .Release.Namespace }}
  name: secrets-options
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    template:
      engineVersion: v2
      data:
        1.yaml: "{{ .glossary | toYaml }}"
        3.yaml: "{{ .glossary2 | toYaml }}"
    name: secrets-options
  dataFrom:
    - extract:
        key: path-to/secret/
        property: secrets-options
```
2. provide the Kubernetes and ESO version

ESO version: 9.0.1
Kubernetes version: 1.22

**Expected behavior**
Even though the Kind:Secret that is generated has the list of yaml files that I am expecing 1.yaml and 3.yaml the the decoded values of those are in json format:
![image](https://github.com/external-secrets/external-secrets/assets/12545262/b8d8faa5-f467-4d28-b8f1-fe96e34d7fe8)
```
'{"title":"example glossary","title2":"example glossary"}'
'{"title":"example glossary","title2":"example glossary"}'
```
which is not what I was expecting the `toYaml` to do

**Screenshots**

**Additional context**

**Comment by moolen** [comment]
Please try with `{{ .glossary | fromJson | toYaml }}`: The value in vault is supposedly stored as `string` type which first must be parsed with `fromJson` into a `map[string]string` type and the serialised into yaml. Please let me know if that helped

**Comment by MirandaRompoti** [comment]
That works fine thank you so much!

Is there are way also to have some logic inside the target.template.data? Like for example to add range?
Something like that?

```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  namespace: {{ .Release.Namespace }}
  name: secrets-options
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    template:
      engineVersion: v2
      data:
        {{- range $k, $v := .Data.data }}
           {{ .k }}.yaml: "{{ .v | fromJson | toYaml }}"
        {{- end }}        
#        1.yaml: "{{ .glossary | fromJson | toYaml}}"
#        3.yaml: "{{ .glossary2 | fromJson | toYaml }}"
    name: secrets-options
  dataFrom:
    - extract:
        key: path-to/secret/
        property: secrets-options
```

**Comment by moolen** [comment]
What you need are dynamic keys. You can achieve that with `templateFrom.literal`

```yaml
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: fake-template-01
spec:
  provider:
    fake:
      data:
      - key: "backend"
        value: "$$$backend$$$"
      - key: "frontend"
        value: "$$$frontend$$$"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: fake-template-01
spec:
  refreshInterval: "10s"
  secretStoreRef:
    name: fake-template-01
    kind: ClusterSecretStore
  target:
    name: "fake-template-01"
    template:
      engineVersion: v2
      templateFrom:
      - target: Data
        literal: |
          {{ range $key, $value := . }}
          custom-prefix-{{$key}}: ${{$value}}
          {{ end }}
  data:
  - secretKey: backend
    remoteRef:
      key: backend
  - secretKey: frontend
    remoteRef:
      key: frontend
```

which yields:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: fake-template-01
  namespace: default
data:
  custom-prefix-backend: JCQkJGJhY2tlbmQkJCQ= # $$$$backend$$$
  custom-prefix-frontend: JCQkJGZyb250ZW5kJCQk # $$$$frontend$$$
```
