### ISSUE TITLE
External Secrets Operator integrates with Alibaba Cloud Key Management Service for secrets and Keys management.

### ISSUE THREAD

**Issue by chiliast123** [external-secrets/external-secrets#2492]
Hi, could you tell me how to configure the "secretstore&externalsecret" files through Access key rather than RRSA authentication. thank you so much!

**Comment by moolen** [comment]
The following SecretStore assumes you have your credentials stored in a `Kind=Secret` with the name `my-creds`.

Hope that helps :pray: 
```yaml
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secretstore-sample
spec:
  provider:
    alibaba:
      regionID: ap-southeast-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: my-creds
            key: akid
          accessKeySecretSecretRef:
            name: my-creds
            key: secret
```

You can lookup the yaml spec under [API specification](https://external-secrets.io/v0.8.5/api/spec/), that helps you to explore the fields which are not well documented :sweat_smile:  :wink:
