### ISSUE TITLE
ExternalSecret in SecretSyncedError when the last key in storage provider is being deleted with `dataFrom`

### ISSUE THREAD

**Issue by aneveu** [external-secrets/external-secrets#2493]
**Describe the bug**
I have an ExternalSecret configured to retrieve keys from multiple paths using `dataFrom`. 
When there is only one key left in the storage provider, if the key is deleted, ExternalSecret goes into `SecretSyncError` mode, and its secret is not removed (as it will be with `data`).

**To Reproduce**

1. manifests used: 

```
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: external-secrets
spec:
  provider:
    vault:
      server: "http://vault.vault.svc:8200"
      path: "secret"
      version: "v2"
      auth:
        tokenSecretRef:
          name: "vault-token"
          key: "token"
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-token
  namespace: external-secrets
data:
  token: cm9vdA== 
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-example
  namespace: external-secrets
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: example-sync
    deletionPolicy: Delete
  dataFrom:
  - find:
      name: 
        regexp: test-path/my-keys
    rewrite:
    - regexp:
        source: "test-path/my-keys/(.*)"
        target: "my-keys.$1"
---
apiVersion: v1
kind: Secret
metadata:
  name: source-secret
  namespace: external-secrets
stringData:
  source-key: "{\"foo\":\"bar\"}" # Needs to be a JSON
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: pushsecret-example
  namespace: external-secrets
spec:
  refreshInterval: 10s # Refresh interval for which push secret will reconcile
  deletionPolicy: Delete
  secretStoreRefs: # A list of secret stores to push secrets to
    - name: vault-backend
      kind: SecretStore
  selector:
    secret:
      name: source-secret # Source Kubernetes secret to be pushed
  data:
    - match:
        secretKey: source-key
        remoteRef:
          remoteKey: test-path/my-keys/1
```

2. k8s version 

```
Client Version: v1.25.9
Kustomize Version: v4.5.7
Server Version: v1.27.1
```

ESO version: observed with 0.8.1 and 0.9.1

**Expected behavior**

I create an ExternalSecret with `dataFrom` to retrieve multiple secrets. Then I create a secret and a PushSecret. When I delete the PushSecret, and if there is no other key left in the storage provider, I expect ExternalSecret's target to be deleted, as it would be if I had declared it with `data`.
