### ISSUE TITLE
PushSecrets are not deleted when running Helm uninstall

### ISSUE THREAD

**Issue by aneveu** [external-secrets/external-secrets#2494]
**Describe the bug**
When I run `helm uninstall external-secrets -n external-secrets`, SecretStore and ExternalSecret are deleted but not PushSecrets. And trying to delete it manually with `kubectl delete` is not working either. 

**To Reproduce**

1. manifests used: 

```
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: external-secrets
spec:
  provider:
    vault:
      server: "http://vault.vault.svc:8200"
      path: "secret"
      version: "v2"
      auth:
        tokenSecretRef:
          name: "vault-token"
          key: "token"
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-token
  namespace: external-secrets
data:
  token: cm9vdA== 
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-example
  namespace: external-secrets
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: example-sync
    deletionPolicy: Delete
  dataFrom:
  - find:
      name: 
        regexp: test-path/my-keys
    rewrite:
    - regexp:
        source: "test-path/my-keys/(.*)"
        target: "my-keys.$1"
---
apiVersion: v1
kind: Secret
metadata:
  name: source-secret
  namespace: external-secrets
stringData:
  source-key: "{\"foo\":\"bar\"}" # Needs to be a JSON
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: pushsecret-example
  namespace: external-secrets
spec:
  refreshInterval: 10s # Refresh interval for which push secret will reconcile
  deletionPolicy: Delete
  secretStoreRefs: # A list of secret stores to push secrets to
    - name: vault-backend
      kind: SecretStore
  selector:
    secret:
      name: source-secret # Source Kubernetes secret to be pushed
  data:
    - match:
        secretKey: source-key
        remoteRef:
          remoteKey: test-path/my-keys/1
```

2. k8s version 

```
Client Version: v1.25.9
Kustomize Version: v4.5.7
Server Version: v1.27.1
```

ESO version: observed with 0.8.1 and 0.9.1

**Expected behavior**

I run `helm install external-secrets ...` and create a SecretStore, an ExternalSecret and a PushSecret. Then I run `helm uninstall external-secrets -n external-secrets` and every resource present (SecretStore, ExternalSecret and PushSecret) get deleted.
