### ISSUE TITLE
Getting successful sync with <no value> when top-level json key doesn't exist instead of an error

### ISSUE THREAD

**Issue by sandoichi** [external-secrets/external-secrets#2497]
**Describe the bug**
When using
```
dataFrom:
- extract:
```
to grab secrets from AWS Secret Manager that are in a flat key:value format with no nesting, specifying a valid secret but a json key that doesn't exist won't trigger an error. Instead, the secret will sync successfully but have an encoded string literal of `<no value>`.

**To Reproduce**
Create an external secret that looks something like this:
```
  target:
    name: testing_secret
    template:
      data:
        FOO: '{{ .I_DONT_EXIST }}'
      engineVersion: v2
      metadata: {}
      type: Opaque
  dataFrom:
  - extract:
      key: some-secret-that-exists
```

**Expected behavior**
I would expect the sync to fail with a message saying that the key doesn't exist.

**Additional context**
I saw that this is the default go template behavior, but there is an option `missingkey=error` that can be set in the code that uses go template to produce the desired behavior. I did not see any options in External Secrets to set this value.

I am using external secrets `0.6.1`. If this is fixed in a newer version, I can try upgrading.
