### ISSUE TITLE
labels/annotations not propagated to child secret if using both spec.dataFrom and spec.target.template.data unless worked around

### ISSUE THREAD

**Issue by thetombombadil** [external-secrets/external-secrets#2517]
**Describe the bug**

For an ExternalSecret, if `spec.target.template.data` is used with `spec.dataFrom`, the annotations/values on the ExternalSecret aren't propagated down to the child secret. I raise this as a bug because https://external-secrets.io/v0.9.1/api/externalsecret/#example notes that labels/annotations are expected to be propagated down. Adding the labels annotations under `spec.target.template.metadata` will propagate the secret down however, so this might just be the expected behaviour, please let me know if this is the case. https://external-secrets.io/v0.9.1/api/spec/#external-secrets.io/v1beta1.ExternalSecretTemplate

Workaround/hack: I found that if only `spec.dataFrom` exists when the secret is created, then if the `spec.target.template.data` field is added and applied after, the labels/annotations are propagated down to the child secret. It has to be done in this order to work.

**To Reproduce**

k8s version: v1.25.11-eks-a5565ad
ESO app version: 0.9.1
ESO chart version: v0.9.1

1. provision `/some/key/path` into SSM and setup secretstore etc.
2. apply external-secret.yaml, observe labels/annotations not propagating to secret
3. remove `spec.target.template.data` from external-secret.yaml and apply again. Observe annotations/data propagating to child secret
4. Re-add `spec.target.template.data` and apply. Observe annotations/data propagating to child secret.

``` yaml
# external-secret.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "hello-world"
  labels:
    foo: bar
  annotations:
    foo: bar
spec:
  secretStoreRef:
    name: ssm
    kind: SecretStore 
  refreshInterval: "2m"

  # the target describes the secret that shall be created
  # there can only be one target per ExternalSecret
  target:
    name: a-secret
    creationPolicy: 'Owner'
    # Specify a blueprint for the resulting Kind=Secret
    template:
      engineVersion: v2
      mergePolicy: "Merge"
      # if the manifest is applied without data first, then the secrets from dataFrom will be propagated into the secret
      data:
        foo: bar
        biz: baz

  dataFrom:
  - extract:
      key: /some/key/path
```

# /some/key/path
``` json
{
  "frog": "dog"
}
```
**Expected behavior**

Based on https://external-secrets.io/v0.9.1/api/externalsecret/#example, I'd expect labels/annotations on the ExternalSecret to be propagated down to the child secret. But perhaps https://external-secrets.io/v0.9.1/api/spec/#external-secrets.io/v1beta1.ExternalSecretTemplate isn't expected to work this way and will always take precedence

**Screenshots**

**Additional context**

Thanks for this project, it's awesome
