### ISSUE TITLE
feat: add option to skip syncing DOPPLER_* keys for doppler provider

### ISSUE THREAD

**Issue by networkhermit** [external-secrets/external-secrets#2518]
**Describe the bug**
Currently syncing every secret from a doppler config will include meta secrets DOPPLER_PROJECT, DOPPLER_ENVIRONMENT and DOPPLER_CONFIG by default, I don't want these extra secrets injected into my k8s deployment.

```yaml
apiVersion: v1
data:
  API_TOKEN: ZGVtbw==
  DOPPLER_CONFIG: ZGVtbw==
  DOPPLER_ENVIRONMENT: ZGVtbw==
  DOPPLER_PROJECT: ZGVtbw==
kind: Secret
metadata:
  name: credential
type: Opaque
```

**To Reproduce**
1. external-secrets v0.9.1
2. follow the [Fetch all](https://external-secrets.io/v0.9.1/provider/doppler/#2-fetch-all) tutorial
3. check the data of generated k8s secret

**Expected behavior**
No extra meta secrets (DOPPLER_PROJECT, DOPPLER_ENVIRONMENT and DOPPLER_CONFIG)，just the secrets I added in doppler config.

**Comment by moolen** [comment]
These values are always returned by the API. When you use `Fetch all`  as you have described above all keys are fetched, including the `DOPPLER_` ones.
If you're only interested in a particular key then you can simply use the [Fetch method](https://external-secrets.io/v0.9.1/provider/doppler/#1-fetch).

**Comment by networkhermit** [comment]
> If you're only interested in a particular key then you can simply use the [Fetch method](https://external-secrets.io/v0.9.1/provider/doppler/#1-fetch).

Yes. I know I can use the Fetch method to specify the keys I want to include, but there are a bunch of keys I want to use and that would be pretty verbose.

I think I can't use Negative Lookahead in regex filter to exclude there DOPPLER_ ones, as regex in golang doesn't support it.

Is there any other method for me to exlude these meta DOPPLER_* keys?

**Comment by gusfcarvalho** [comment]
You can use templates with KeysAndValues filter. On the template you can do a simple match to skip if the key starts with DOPPLER

**Comment by networkhermit** [comment]
> You can use templates with KeysAndValues filter. On the template you can do a simple match to skip if the key starts with DOPPLER

Thanks. I will check it out.

**Comment by networkhermit** [comment]
It's weird that now the generated secret becomes something like this:

```text
data:
  DOPPLER_CONFIG:
  DOPPLER_ENVIRONMENT:
  DOPPLER_PROJECT:
  A:
  A_:
  B:
  B_:
```

Shouldn't the following template skip the DOPPLER_ keys giving that the `mergePolicy` is `Replace`?

```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: demo-secret
  namespace: default
spec:
  dataFrom:
  - find:
      conversionStrategy: Default
      decodingStrategy: None
      name:
        regexp: .*
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: doppler-demo-secret
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    name: demo-secret
    template:
      engineVersion: v2
      mergePolicy: Replace
      templateFrom:
      - literal: |
          {{- range $key, $value := . }}
          {{- if not (eq $key "DOPPLER_CONFIG" "DOPPLER_ENVIRONMENT" "DOPPLER_PROJECT") }}
          {{ $key }}_: {{ $value }}
          {{- end }}
          {{- end }}
        target: Data
````
