### ISSUE TITLE
Webhook crushloops when Cert-Manager is used with default values

### ISSUE THREAD

**Issue by mindw** [external-secrets/external-secrets#2519]
**Describe the bug**
When the cert-manager webhook mode is enabled using default values, external-secrets-webhook enters into a crashloop.

**To Reproduce**
* install cert-manager chart
* create a self-signed cluster issuer
```yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: self-signed-cluster-issuer
spec:
  selfSigned: {}
```
*  install helm chart with the following values
```yaml
certController:
  create: false
webhook:
  certManager:
    cert:
      issuerRef:
        kind: ClusterIssuer
        name: self-signed-cluster-issuer
    enabled: true
```
ESO v0.9.1
k8s (EKS) 1.25

**Expected behavior**
all workloads are running.

**Screenshots**
Readable text dumps instead
```
NAME                                        READY   STATUS             RESTARTS        AGE
external-secrets-7bd898c8b9-qtcz9           1/1     Running            0               16h
external-secrets-webhook-588697595f-jqztw   0/1     CrashLoopBackOff   43 (2m2s ago)   16h
```

```
external-secrets-webhook-588697595f-jqztw webhook {"level":"info","ts":1689771274.029975,"logger":"setup","msg":"validating certs"}
external-secrets-webhook-588697595f-jqztw webhook {"level":"error","ts":1689771274.0303943,"logger":"setup","msg":"certs are not valid at now + lookahead, triggering shutdown","certLookahead":"2160h0m0s","error":"x509: certificate has expired or is not yet valid: current time 2023-10-17T12:54:34Z is after 2023-10-16T09:45:46Z","stacktrace":"github.com/external-secrets/external-secrets/cmd.glob..func3.1\n\t/home/runner/work/external-secrets/external-secrets/cmd/webhook.go:101"}
external-secrets-webhook-588697595f-jqztw webhook {"level":"info","ts":1689771274.0304546,"msg":"Stopping and waiting for non leader election runnables"}
```

**Additional context**
It seems the default lookahead interval is 90d - which is exactly the same as cert-manager certificate default - causing the lookahead check to fail. setting `webhook.lookaheadInterval` to `210h` seems to have solved the issue.

```
  duration      <string>
    The requested 'duration' (i.e. lifetime) of the Certificate. This option may
    be ignored/overridden by some issuer types. If unset this defaults to 90
    days. Certificate will be renewed either 2/3 through its duration or
    `renewBefore` period before its expiry, whichever is later. Minimum accepted
    duration is 1 hour. Value must be in units accepted by Go time.ParseDuration
    https://golang.org/pkg/time/#ParseDuration
```

**Comment by gusfcarvalho** [comment]
even though we support `cert-manager` certificates, this is not the default way to create them. As such, changing the lookahead interval value is not a workaround, but part of the configuration needed when users go for `cert-manager`.

@mindw  is the bug the fact that the default value is not compatible with `cert-manager` default value?

**Comment by mindw** [comment]
> even though we support `cert-manager` certificates, this is not the default way to create them. As such, changing the lookahead interval value is not a workaround, but part of the configuration needed when users go for `cert-manager`.
> 
> @mindw  is the bug the fact that the default value is not compatible with `cert-manager` default value?

Yes, something needs to change I guess - either the default for the certificate or the default for the look ahead.

**Comment by fernferret** [comment]
Hi all!

As the PR author of the cert-manager feature I'm certainly happy to both provide my own experience and some ideas.

My intent was, to use CertManager as my one stop shop for certificate management in my cluster, mainly to make sure I could audit expirations.

I have my install setup with the following config:

```yaml
# helm diff upgrade external-secrets -n external-secrets -f external-secrets.yaml ../oss/external-secrets

replicaCount: 3
leaderElect: true

# Disable cluster secrets/store. I'm using namespaced resources only,
# however I don't want to deploy a multiple copies of ESOs so I'll only deploy the one. it
# will still be able to see all namespaces but the cluster-scoped objects are
# disabled
processClusterExternalSecret: false
processClusterStore: false
crds:
  createClusterExternalSecret: false
  createClusterSecretStore: false

extraArgs:
  # rfc3339 times are a lot nicer to read as a human
  zap-time-encoding: "rfc3339"
  # debug logging is very helpful to determine when an engine is not working
  # correctly.
  # loglevel: debug

# These parameters (all default) control if we want to run the external-secrets
# daemon globally or just in one namespace. For security reasons it might be
# nicer to not allow it to have global perms.
#
# Running in namespaced mode would only protect us if ESO was compromised. As
# long as cluster level CRDs (see above) are disabled, then running ESO in
# "global" mode does NOT let namespace A act as if it was namespace B.
#
# As it stands I'm still going to run this in my lab with only one, however it
# (ESO) will grant itself the ability to create serviceaccounts/token from all
# service accounts. This means it can effectively be any service account it
# wants to.
#
# This is how ESO is able to "assume" different roles just by setting them in
# the CRD, for example this CRD lives in the "auth" namespace, but ESO is able
# to "login" as auth/default (as requested) to retrieve credentials from vault
# using the serviceaccounts/token.
#
# apiVersion: generators.external-secrets.io/v1alpha1
# kind: VaultDynamicSecret
# metadata:
#   name: "crdb-generator"
#   namespace: auth
# spec:
#   ...
#   provider:
#     ...
#     auth:
#       kubernetes:
#         ...
#         serviceAccountRef:
#           name: "default"
scopedNamespace: ""
scopedRBAC: false

serviceMonitor:
  enabled: true

# See the following issues related to setting up the CertManager webhook
# https://github.com/external-secrets/external-secrets/issues/1965
# https://github.com/external-secrets/external-secrets/pull/2394
webhook:
  create: true
  lookaheadInterval: 48h

  # This was added to test the webhook, it defaults to 5m
  # certCheckInterval: 10s

  certManager:
    enabled: true
    cert:
      issuerRef:
        kind: "ClusterIssuer"
        name: "example-issuer"
      duration: "168h"
      renewBefore: "72h"
      annotations:
        foo: bar

certController:
  create: false

nodeSelector:
  node-role.kubernetes.io/control-plane: ""

tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
```

I actually did not intend on this being used without configuration, however I can see some cases where this might be desirable. Before we move on, itt's worth noting that there is a warning about the [self signed issuer](https://cert-manager.io/docs/configuration/selfsigned/) about it's utility in production.

I did leave a small comment about using `renewBefore` in the values file, but I think this really deserves some dedicated documentation (see below):

      # Note that renewBefore should be greater than .webhook.lookaheadInterval
      # since the webhook will check this far in advance that the certificate is
      # valid.

Ref: https://github.com/external-secrets/external-secrets/blob/main/deploy/charts/external-secrets/values.yaml#L281

I'm certainly willing to look to the chart maintainers opinions on this one, mainly the question "should the cert-manager integration work out of the box". I think this is doable, but I will say that I think most CertManager users will be performing heavy configuration changes (linking to Vault, ACME, Venifi whatever), customizing max renewals, ciphers etc, which will lead to the default values rarely being used in production.

However there is something to be said for "I want to try out the integration" and having it "just work" out of the box.

I'm not against providing a default for `duration` (as this is easily overridden) and I see a few options:

* For minimal renewal, `duration: 6504h` which is (3 * 90d) + 1d. This would ensure that the certificate would be renewed at 90.33 days
* For simplicity `duration: 8760h` (1 year) which would trigger renewals @ 121.6 days. I believe this is more in line with what the stock intent was.

After typing this out, I think my choice would be `8760h`.

I do not think a default should be provided for `renewBefore`, as this is [calculated by default to be 2/3 of the duration](https://cert-manager.io/docs/reference/api-docs/#cert-manager.io/v1.CertificateSpec). This means if a user overrode `duration` they would also have to do the math to calculate the 2/3 (assuming they would want to use that) vs letting cert-manager take care of it by default.

I must admit, embarrassingly, I do owe a documentation PR (as I promised @moolen) but I just haven't had the time to complete it. I do think having solid documentation would certainly help clear up these issues, so I'll start writing some this weekend and get at least a draft PR up for a tutorial with cert-manager.

**Comment by moolen** [comment]
@fernferret, thanks for sharing your thoughts on this topic! You don't owe anyone anything, don't worry. Do it if you feel like it, it's also totally fine if you have something better to do, like enjoying the :sun_with_face: outside :sunglasses:  :) 

> should the cert-manager integration work out of the box

I agree with what has already been said. I guess it should be working out of the box, at least for a PoC scenario.  `8760h` sounds good to me. I think it would also be fine if we increase the lookahead interval, although i'm not a big fan of having certificates valid for longer than 3 months :) 

So i'd vouch for increasing the duration, just to get it up and running quickly :+1:

**Comment by dntosas** [comment]
i think this is still an issue ^

**Comment by weikinhuang** [comment]
I think the certmanager templates should be updated to include an issuer much like how kube-prometheus-stack sets up it's webhook with cert-manager https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/prometheus-operator/certmanager.yaml

**Comment by Tycale** [comment]
An effective and easy solution is to adjust the default `webhook.certManager.cert.duration` value in the helm chart to exceed 9 months as suggested by @fernferret in his post. I think this should be done in order to improve UX, that's why I just submitted a PR.

**Comment by michalschott** [comment]
Trend is that certificates should be rotated often, in my case I like to do it daily.

If you're using chart for installation/templating:

```
webhook:
  lookaheadInterval: "1h"
  certManager:
    enabled: true
    addInjectorAnnotations: true
    cert:
      create: true
      issuerRef:
        group: cert-manager.io
        kind: "Issuer"
        name: "external-secrets-selfsigned"
      duration: "1d"
```
