### ISSUE TITLE
invalid header field value for Authorization

### ISSUE THREAD

**Issue by pazfelipe** [external-secrets/external-secrets#2533]
Hey all, I found closed issues related to this problem and I tried to follow the same steps but unfortunately none of them worked for me.

Currently, I have this file

```yaml
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secretstore-ikatron
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-2
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: awssm-secret
            key: access-key
          secretAccessKeySecretRef:
            name: awssm-secret
            key: secret-access-key
```

But I'm getting this error

```shell
{
  "level": "error",
  "ts": 1690197485.2115793,
  "logger": "controllers.ExternalSecret",
  "msg": "could not get secret data from provider",
  "ExternalSecret": {
    "name": "ikatron-secrets",
    "namespace": "default"
  },
  "error": "RequestError: send request failed\ncaused by: Post \"https://secretsmanager.us-east-2.amazonaws.com/\": net/http: invalid header field value for \"Authorization\"",
  "stacktrace": "github.com/external-secrets/external-secrets/pkg/controllers/externalsecret.(*Reconciler).Reconcile\n\t/home/runner/work/external-secrets/external-secrets/pkg/controllers/externalsecret/externalsecret_controller.go:205\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:118\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:314\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:265\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:226"
}
{
  "level": "error",
  "ts": 1690197485.2207506,
  "msg": "Reconciler error",
  "controller": "externalsecret",
  "controllerGroup": "external-secrets.io",
  "controllerKind": "ExternalSecret",
  "ExternalSecret": {
    "name": "ikatron-secrets",
    "namespace": "default"
  },
  "namespace": "default",
  "name": "ikatron-secrets",
  "reconcileID": "dc201568-654c-4f18-8bbb-acac6fc49105",
  "error": "RequestError: send request failed\ncaused by: Post \"https://secretsmanager.us-east-2.amazonaws.com/\": net/http: invalid header field value for \"Authorization\"",
  "stacktrace": "sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:324\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:265\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:226"
}
``` 

Does anybody what can be the problem?
