### ISSUE TITLE
PushSecret Hashicorp Vault creating new versions in cycle

### ISSUE THREAD

**Issue by fallen-up** [external-secrets/external-secrets#2536]
**Describe the bug**
PushSecret Hashicorp Vault creating new versions in cycle. Frequency and amount depend on refreshInterval. In one day it can create more than a thousand versions that "rape" vault store.

**To Reproduce**
1) Create any push secret. Let PushSecret push it to HashiCorp Vault. For example:
```
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: pushsecret-example
  namespace: kafka
spec:
  refreshInterval: 10s
  secretStoreRefs:
    - name: vault-backend
      kind: SecretStore
  selector:
    secret:
      name: restrictions-service
  data:
    - match:
        secretKey: user.crt
        remoteRef:
          remoteKey: services/kafka/restrictions-service
          property: user.crt
    - match:
        secretKey: user.key
        remoteRef:
          remoteKey: services/kafka/restrictions-service
          property: user.key
    - match:
        secretKey: user.p12
        remoteRef:
          remoteKey: services/kafka/restrictions-service
          property: user.p12
    - match:
        secretKey: user.password
        remoteRef:
          remoteKey: services/kafka/restrictions-service
          property: user.password
```
2) Check secrets in Vault

externalsecrets version: 0.9.1

**Expected behavior**
I don't want to create new versions in Vault. I need the secrets to be updated only if it has changed in the kubernetes-secrets. RefreshInterval interval should only affect how often the check will be performed.
As I understand, it requires creationPolicy support, but it is not. there is only deletionPolicy.

**Screenshots**
![image](https://github.com/external-secrets/external-secrets/assets/11389898/d63098cd-df44-4f35-ab4b-7dd90f0409c2)
