### ISSUE TITLE
PushSecret errors on HashiCorp Vault - Key Value store V1

### ISSUE THREAD

**Issue by Jorricks** [external-secrets/external-secrets#2549]
**Describe the bug**
We are attempting to use the PushSecret operation for the HashiCorp vault key-value store V1.
However, we are getting back an error because it's trying to reach endpoints made for `v2` that don't exist in `v1`;
```
set secret failed: could not write remote ref password to target secretstore secret-store: 
Error making API request. URL: PUT https://path-to-my-vault.com/v1/my-cluster-name/metadata/project/project-name/auth/token Code: 403. Errors: * 1 error occurred: * permission denied
```
https://developer.hashicorp.com/vault/api-docs/secret/kv/kv-v2#read-secret-metadata

**To Reproduce**
1. Create a secret named `generated-token-secret` containing a `password` key and a random value
2. Create a SecretStore for a key-value store v1 as follows;
```
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secret-store
  namespace: some-namespace
spec:
  provider:
    vault:
      auth:
        kubernetes:
          mountPath: kubernetes/my-cluster-name
          role: my-role-name
          secretRef:
            name: secret-store-token
      path: path-to-v1
      server: 'https://path-to-my-vault.com'
      version: v1
```
3. Create a PushSecret as follows;
```
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: mypushsecret
  namespace: some-namespace
spec:
  data:
    - match:
        remoteRef:
          property: password
          remoteKey: project/project-name/auth/token
        secretKey: password
  refreshInterval: 10s
  secretStoreRefs:
    - kind: SecretStore
      name: secret-store
  selector:
    secret:
      name: generated-token-secret
```

**Expected behavior**
We expected it to generate the secret in the vault without errors.

**Screenshots**
No screenshots required.

**Additional context**
Nope
