### ISSUE TITLE
How to use templateFrom?

### ISSUE THREAD

**Issue by atsai1220** [external-secrets/external-secrets#255]
Hello! Trying to use the new `templateFrom` feature but I'm unsure if I'm doing this correctly. I am successful in retrieving secrets from Vault but templates in `spec.target.template.templateFrom[].configMap` are not parsed by the templating mechanism. More than likely I'm doing something wrong. Could someone point me in the right direction? I'd be more than happy to contribute towards documentation for this feature once I understand it more.

external secret 
``` yaml
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: containerservices-alertmanager-test
  namespace: cattle-monitoring-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: containerservices
    kind: ClusterSecretStore
  data:
  - secretKey: slack
    remoteRef:
      key: rancher/cluster_data/receivers
      property: slack
  - secretKey: xmatters
    remoteRef:
      key: rancher/cluster_data/receivers
      property: xmatters
  target:
    name: containerservices-alertmanager-test
    creationPolicy: 'Owner'
    template:
      type: Opaque
      templateFrom:
      - configMap:
          name: cs-alertmanager
          items:
          - key: rancher_defaults.tmpl
          - key: alertmanager.yaml
```

Here is the ConfigMap. I do not plan to templatize `rancher_defaults.tmpl`. I just wish to be part of the secret too for mounting. I only want to templatize `alertmanager.yaml` key.

``` yaml
apiVersion: v1
data:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m
    receivers:
    - name: "null"
    - slack_configs:
        - send_resolved: true
          http_config: {}
          api_url: >-
            {{ .slack | toString }}
          text: '{{ template "slack.rancher.text" . }}'
      email_configs: []
      pagerduty_configs: []
      opsgenie_configs: []
      webhook_configs: []
      name: "warning"
    - slack_configs:
        - send_resolved: true
          http_config: {}
          api_url: >-
            {{ .slack | toString }}
          text: '{{ template "slack.rancher.text" . }}'
      webhook_configs:
        - send_resolved: true
          url: >- 
            {{ .xmatters | toString }}
          http_config: {}
      email_configs: []
      pagerduty_configs: []
      opsgenie_configs: []
      name: "critical"
    route:
      group_by: 
      - job
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: "null"
      routes:
      - match:
          alertname: Watchdog
        receiver: "null"
      - group_by: []
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 4h
        match: {}
        match_re:
          alertname: etcdHighNumberOfFailedGRPCRequests
        receiver: "null"
      - group_by:
          - alertname
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 4h
        match: {}
        match_re:
          severity: warning
        receiver: "warning"
      - group_by:
          - alertname
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 4h
        match: {}
        match_re:
          severity: critical
        receiver: "critical"
    templates:
    - /etc/alertmanager/config/*.tmpl
  rancher_defaults.tmpl: |
    {{- define "slack.rancher.text" -}}
    {{ template "rancher.text_multiple" . }}
    {{- end -}}
    {{- define "rancher.text_multiple" -}}
    *[GROUP - Details]*
    One or more alarms in this group have triggered a notification.
    {{- if gt (len .GroupLabels.Values) 0 }}
    *Group Labels:*
        {{- range .GroupLabels.SortedPairs }}
        • *{{ .Name }}:* `{{ .Value }}`
        {{- end }}
    {{- end }}
    {{- if .ExternalURL }}
    *Link to AlertManager:* {{ .ExternalURL }}
    {{- end }}
    {{- range .Alerts }}
    {{ template "rancher.text_single" . }}
    {{- end }}
    {{- end -}}
    {{- define "rancher.text_single" -}}
    {{- if .Labels.alertname }}
    *[ALERT - {{ .Labels.alertname }}]*
    {{- else }}
    *[ALERT]*
    {{- end }}
    {{- if .Labels.severity }}
    *Severity:* `{{ .Labels.severity }}`
    {{- end }}
    {{- if .Labels.cluster }}
    *Cluster:*  {{ .Labels.cluster }}
    {{- end }}
    {{- if .Annotations.summary }}
    *Summary:* {{ .Annotations.summary }}
    {{- end }}
    {{- if .Annotations.message }}
    *Message:* {{ .Annotations.message }}
    {{- end }}
    {{- if .Annotations.description }}
    *Description:* {{ .Annotations.description }}
    {{- end }}
    {{- if .Annotations.runbook_url }}
    *Runbook URL:* <{{ .Annotations.runbook_url }}|:spiral_note_pad:>
    {{- end }}
    {{- with .Labels }}
    {{- with .Remove (stringSlice "alertname" "severity" "cluster") }}
    {{- if gt (len .) 0 }}
    *Additional Labels:*
        {{- range .SortedPairs }}
        • *{{ .Name }}:* `{{ .Value }}`
        {{- end }}
    {{- end }}
    {{- end }}
    {{- end }}
    {{- with .Annotations }}
    {{- with .Remove (stringSlice "summary" "message" "description" "runbook_url") }}
    {{- if gt (len .) 0 }}
    *Additional Annotations:*
        {{- range .SortedPairs }}
        • *{{ .Name }}:* `{{ .Value }}`
        {{- end }}
    {{- end }}
    {{- end }}
    {{- end }}
    {{- end -}}
kind: ConfigMap
metadata:
  name: csalertmanager
  namespace: cattle-monitoring-system
```

the resulting `secret`. I've removed extra metadata and base64 decoded for easy reading. I am expecting `alertmanger.yaml` to contain my secrets `.slack` and `.xmatters`. The logs in the external-secrets app does not indicate any issues.
``` yaml
apiVersion: v1
data:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m
    receivers:
    - name: "null"
    - slack_configs:
        - send_resolved: true
          http_config: {}
          api_url: >-
            {{ .slack | toString }}
          text: '{{ template "slack.rancher.text" . }}'
      email_configs: []
      pagerduty_configs: []
      opsgenie_configs: []
      webhook_configs: []
      name: "warning"
    - slack_configs:
        - send_resolved: true
          http_config: {}
          api_url: >-
            {{ .slack | toString }}
          text: '{{ template "slack.rancher.text" . }}'
      webhook_configs:
        - send_resolved: true
          url: >- 
            {{ .xmatters | toString }}
          http_config: {}
      email_configs: []
      pagerduty_configs: []
      opsgenie_configs: []
      name: "critical"
    route:
      group_by: 
      - job
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: "null"
      routes:
      - match:
          alertname: Watchdog
        receiver: "null"
      - group_by: []
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 4h
        match: {}
        match_re:
          alertname: etcdHighNumberOfFailedGRPCRequests
        receiver: "null"
      - group_by:
          - alertname
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 4h
        match: {}
        match_re:
          severity: warning
        receiver: "warning"
      - group_by:
          - alertname
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 4h
        match: {}
        match_re:
          severity: critical
        receiver: "critical"
    templates:
    - /etc/alertmanager/config/*.tmpl
  rancher_defaults.tmpl: "e3stIGRlZmluZSAic2xhY2sucmFuY2hlci50ZXh0IiAtfX0Ke3sgdGVtcGxhdGUgInJhbmNoZXIudGV4dF9tdWx0aXBsZSIgLiB9fQp7ey0gZW5kIC19fQp7ey0gZGVmaW5lICJyYW5jaGVyLnRleHRfbXVsdGlwbGUiIC19fQoqW0dST1VQIC0gRGV0YWlsc10qCk9uZSBvciBtb3JlIGFsYXJtcyBpbiB0aGlzIGdyb3VwIGhhdmUgdHJpZ2dlcmVkIGEgbm90aWZpY2F0aW9uLgp7ey0gaWYgZ3QgKGxlbiAuR3JvdXBMYWJlbHMuVmFsdWVzKSAwIH19CipHcm91cCBMYWJlbHM6KgogICAge3stIHJhbmdlIC5Hcm91cExhYmVscy5Tb3J0ZWRQYWlycyB9fQogICAg4oCiICp7eyAuTmFtZSB9fToqIGB7eyAuVmFsdWUgfX1gCiAgICB7ey0gZW5kIH19Cnt7LSBlbmQgfX0Ke3stIGlmIC5FeHRlcm5hbFVSTCB9fQoqTGluayB0byBBbGVydE1hbmFnZXI6KiB7eyAuRXh0ZXJuYWxVUkwgfX0Ke3stIGVuZCB9fQp7ey0gcmFuZ2UgLkFsZXJ0cyB9fQp7eyB0ZW1wbGF0ZSAicmFuY2hlci50ZXh0X3NpbmdsZSIgLiB9fQp7ey0gZW5kIH19Cnt7LSBlbmQgLX19Cnt7LSBkZWZpbmUgInJhbmNoZXIudGV4dF9zaW5nbGUiIC19fQp7ey0gaWYgLkxhYmVscy5hbGVydG5hbWUgfX0KKltBTEVSVCAtIHt7IC5MYWJlbHMuYWxlcnRuYW1lIH19XSoKe3stIGVsc2UgfX0KKltBTEVSVF0qCnt7LSBlbmQgfX0Ke3stIGlmIC5MYWJlbHMuc2V2ZXJpdHkgfX0KKlNldmVyaXR5OiogYHt7IC5MYWJlbHMuc2V2ZXJpdHkgfX1gCnt7LSBlbmQgfX0Ke3stIGlmIC5MYWJlbHMuY2x1c3RlciB9fQoqQ2x1c3RlcjoqICB7eyAuTGFiZWxzLmNsdXN0ZXIgfX0Ke3stIGVuZCB9fQp7ey0gaWYgLkFubm90YXRpb25zLnN1bW1hcnkgfX0KKlN1bW1hcnk6KiB7eyAuQW5ub3RhdGlvbnMuc3VtbWFyeSB9fQp7ey0gZW5kIH19Cnt7LSBpZiAuQW5ub3RhdGlvbnMubWVzc2FnZSB9fQoqTWVzc2FnZToqIHt7IC5Bbm5vdGF0aW9ucy5tZXNzYWdlIH19Cnt7LSBlbmQgfX0Ke3stIGlmIC5Bbm5vdGF0aW9ucy5kZXNjcmlwdGlvbiB9fQoqRGVzY3JpcHRpb246KiB7eyAuQW5ub3RhdGlvbnMuZGVzY3JpcHRpb24gfX0Ke3stIGVuZCB9fQp7ey0gaWYgLkFubm90YXRpb25zLnJ1bmJvb2tfdXJsIH19CipSdW5ib29rIFVSTDoqIDx7eyAuQW5ub3RhdGlvbnMucnVuYm9va191cmwgfX18OnNwaXJhbF9ub3RlX3BhZDo+Cnt7LSBlbmQgfX0Ke3stIHdpdGggLkxhYmVscyB9fQp7ey0gd2l0aCAuUmVtb3ZlIChzdHJpbmdTbGljZSAiYWxlcnRuYW1lIiAic2V2ZXJpdHkiICJjbHVzdGVyIikgfX0Ke3stIGlmIGd0IChsZW4gLikgMCB9fQoqQWRkaXRpb25hbCBMYWJlbHM6KgogICAge3stIHJhbmdlIC5Tb3J0ZWRQYWlycyB9fQogICAg4oCiICp7eyAuTmFtZSB9fToqIGB7eyAuVmFsdWUgfX1gCiAgICB7ey0gZW5kIH19Cnt7LSBlbmQgfX0Ke3stIGVuZCB9fQp7ey0gZW5kIH19Cnt7LSB3aXRoIC5Bbm5vdGF0aW9ucyB9fQp7ey0gd2l0aCAuUmVtb3ZlIChzdHJpbmdTbGljZSAic3VtbWFyeSIgIm1lc3NhZ2UiICJkZXNjcmlwdGlvbiIgInJ1bmJvb2tfdXJsIikgfX0Ke3stIGlmIGd0IChsZW4gLikgMCB9fQoqQWRkaXRpb25hbCBBbm5vdGF0aW9uczoqCiAgICB7ey0gcmFuZ2UgLlNvcnRlZFBhaXJzIH19CiAgICDigKIgKnt7IC5OYW1lIH19OiogYHt7IC5WYWx1ZSB9fWAKICAgIHt7LSBlbmQgfX0Ke3stIGVuZCB9fQp7ey0gZW5kIH19Cnt7LSBlbmQgfX0Ke3stIGVuZCAtfX0K"
  slack: https://hooks.slack.com/services/123123/123123/123123
  xmatters: https://example.com
kind: Secret
metadata:
  name: containerservices-alertmanager-test
  namespace: cattle-monitoring-system
  ownerReferences:
  - apiVersion: external-secrets.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: ExternalSecret
    name: containerservices-alertmanager-test
    uid: b561a8bf-af07-4a7c-9b0b-32bb53efba46
type: Opaque

```

I am expecting the `alertmanager` key to be populated with my Slack and xmatters secret.

**Comment by atsai1220** [comment]
Here is a smaller example.
**secret**
```
apiVersion: v1
data:
  slack: aHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMvVEs2MDRCSEs1L0IwMUg2OUpRVlRML2tNaVVoRENZQU9GeGwxMkZlYXFMSjBINg==
  test.yaml: e3sgLnNsYWNrIHwgdG9TdHJpbmcgfX0=
  xmatters: aHR0cHM6Ly9leGFtcGxlLmNvbQ==
kind: Secret
metadata:
  name: containerservices-alertmanager-test
  namespace: cattle-monitoring-system
  ownerReferences:
  - apiVersion: external-secrets.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: ExternalSecret
    name: containerservices-alertmanager-test
    uid: b561a8bf-af07-4a7c-9b0b-32bb53efba46
type: Opaque
```

**externalsecret**
``` yaml
```
