### ISSUE TITLE
ESO does not cleanup keys when using template

### ISSUE THREAD

**Issue by moolen** [external-secrets/external-secrets#2550]
This bug surfaced in #2518. 
It can be reproduced with the manifest further below.

The bug is triggered if the user FIRST creates a `Kind=ExternalSecret` without a `spec.target.template`. Then, if a user creates a template which changes the secret data, the sum of both states old and new will be written to the target secret.

This is probably, because the managed keys cleanup is done before the tempalte is applied. Moving that section further down could resolve the issue.

```go

		// diff existing keys
		keys, err := getManagedKeys(&existingSecret, externalSecret.Name)
		if err != nil {
			return err
		}
		// Sanitize data map for any updates on the ES
		for _, key := range keys {
			if dataMap[key] == nil {
				secret.Data[key] = nil
				// Sanitizing any templated / updated keys
				delete(secret.Data, key)
			}
		}
		err = r.applyTemplate(ctx, &externalSecret, secret, dataMap)
		if err != nil {
			return fmt.Errorf(errApplyTemplate, err)
		}

``` 

```yaml
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: fake-template-01
spec:
  provider:
    fake:
      data:
      - key: "mymap"
        valueMap:
          DOPPLER_CONFIG: "..."
          DOPPLER_ENVIRONMENT: "..."
          frontend: foo
          backend: bar
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: fake-template-01
spec:
  refreshInterval: "10s"
  secretStoreRef:
    name: fake-template-01
    kind: ClusterSecretStore
  target:
    name: "fake-template-01"
    # first, apply as-is with the following section being commented out
    # then, remove the comment and apply.
    # you should see that both old and new values are present.
    # template:
    #   engineVersion: v2
    #   templateFrom:
    #   - target: Data
    #     literal: |
    #       {{- range $key, $value := . }}
    #       {{- if not (eq $key "DOPPLER_CONFIG" "DOPPLER_ENVIRONMENT" "DOPPLER_PROJECT") }}
    #       {{ $key }}_: {{ $value }}
    #       {{- end }}
    #       {{- end }}
    # ----- until here

  dataFrom:
  - extract:
      key: mymap
```
