### ISSUE TITLE
Helm is ignoring service account annotations when defined in values

### ISSUE THREAD

**Issue by quintonthompson** [external-secrets/external-secrets#2553]
**Describe the bug**
When using the external-secrets upstream helm chart and defining annotations under `serviceAccount.annotations`,  the resulting service account is missing the annotation. 

**To Reproduce**

k8s version: v1.24.14-gke.1200

Chart.yaml
```
apiVersion: v2
name: external-secrets
description: A Helm chart for Kubernetes
type: application
version: 0.0.1
dependencies:
  - name: external-secrets
    version: 0.9.1
    repository: "https://charts.external-secrets.io"
```

values.yaml
```
serviceAccount:
  # -- Specifies whether a service account should be created.
  create: true
  # -- Automounts the service account token in all containers of the pod
  automount: true
  # -- Annotations to add to the service account.
  annotations:
    iam.gke.io/gcp-service-account: external-secrets@my-project.iam.gserviceaccount.com
  extraLabels: {}
  # -- The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template.
  name: ""
```
When running `helm -n external-secrets template external-secrets external-secrets` I get the following output for the service account:
```
---
# Source: external-secrets/charts/external-secrets/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: "external-secrets"
  labels:
    helm.sh/chart: external-secrets-0.9.1
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/instance: external-secrets
    app.kubernetes.io/version: "v0.9.1"
    app.kubernetes.io/managed-by: Helm
```

**Expected behavior**
I expect the output to be the following:
```
---
# Source: external-secrets/charts/external-secrets/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: "external-secrets"
  annotations:
    iam.gke.io/gcp-service-account: external-secrets@my-project.iam.gserviceaccount.com
  labels:
    helm.sh/chart: external-secrets-0.9.1
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/instance: external-secrets
    app.kubernetes.io/version: "v0.9.1"
    app.kubernetes.io/managed-by: Helm
```

**Comment by quintonthompson** [comment]
It was a mistake on my end and forgot to add these values under the charts key
```
external-secrets:
  serviceAccount:
    # -- Specifies whether a service account should be created.
    create: true
    # -- Automounts the service account token in all containers of the pod
    automount: true
    # -- Annotations to add to the service account.
    annotations:
      iam.gke.io/gcp-service-account: external-secrets@my-project.iam.gserviceaccount.com
    extraLabels: {}
    # -- The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template.
    name: 
```
