### ISSUE TITLE
Invalid imagePullSecrets using Vault provider

### ISSUE THREAD

**Issue by mxm-tr** [external-secrets/external-secrets#2556]
**Describe the bug**
An imagePullSecret created using the docs at <https://external-secrets.io/v0.8.5/guides/common-k8s-secret-types/#dockerconfigjson-example> does not seem to be working:

The following secret that has been created manually using `kubectl` works:

```text
$ kubectl -n my-ns get secret harbor-test -ojsonpath='{.data.\.dockerconfigjson}' | base64 -d
{"auths":{"registry.mysite.com":{"username":"robot$repo-read","password":"xxxx","auth":"yyyy"}}}
```

But the following which has been created using the Vault operator does not:

```text
$ kubectl -n my-ns get secret harbor-image-pull -ojsonpath='{.data.\.dockerconfigjson}' | base64 -d
{"auths":"{\"registry.mysite.com\":{\"username\":\"robot$repo-read\",\"password\":\"xxxx\",\"auth\":\"yyyy\"}}"}
```

**To Reproduce**

With a `vault-backend` SecretStore pointing to a Vault server:

1. Manifests:

```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pull-secret
  namespace: my-ns
spec:
  data:
  - remoteRef:
      key: pull-secret
    secretKey: secret
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: vault-backend
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: harbor-image-pull
    template:
      data:
        .dockerconfigjson: '{{ .secret }}'
      engineVersion: v2
      mergePolicy: Replace
      type: kubernetes.io/dockerconfigjson
```
This has been taken from the [docs](https://external-secrets.io/v0.8.5/guides/common-k8s-secret-types/#dockerconfigjson-example)

Command used to push the secret inside vault:

```bash
kubectl create secret docker-registry --dry-run=client -ojsonpath='{ .data.\.dockerconfigjson}' --docker-server='registry.mysite.com' --docker-username='robot$repo-read' --docker-password='xxxx' pull-secret | base64 -d | jq -c '.auths' | tr -d $'\n' | vault kv put -address http://127.0.0.1:8200 my-store/pull-secret auths=-
```

3. provide the Kubernetes and ESO version

Kubernetes version: RKE2 v1.23.17+rke2r1
ESO version: 0.8.5

**Expected behavior**

ImagePullSecrets generated using the vault operator matches the one created manually, perhaps without the string escaping sequences?

**Comment by mxm-tr** [comment]
A setup that works for the Vault operator vault is to use Base64 encoding:

```bash
kubectl create secret docker-registry --dry-run=client -ojsonpath='{ .data.\.dockerconfigjson}' --docker-server='registry.mysite.com --docker-username='robot$repo-read' --docker-password='xxxx' pull-secret | vault kv put -address http://127.0.0.1:8200 paas/pull-secret .dockerconfigjson=-
```

A working yaml file:

```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pull-secret
  namespace: my-ns
spec:
  dataFrom:
  - extract:
      conversionStrategy: Default
      decodingStrategy: Base64
      key: pull-secret
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: vault-backend
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: harbor-image-pull
```

**Comment by moolen** [comment]
Your `.secret` is a string, which gets rendered as-is.

```
{"auths":"{\"registry.mysite.com\":{\"username\":\"robot$repo-read\",\"password\":\"xxxx\",\"auth\":\"yyyy\"}}"}
         ^ string starts
```

This should be an object, not a string. 

You can probably just wrap it as follows:

```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pull-secret
spec:
  data:
  - remoteRef:
      key: pull-secret
      property: auths
    secretKey: secret
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: vault-backend
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: harbor-image-pull
    template:
      data:
        .dockerconfigjson: '{"auths":{{ .secret }}}'
      engineVersion: v2
      mergePolicy: Replace
      type: kubernetes.io/dockerconfigjson
```
