### ISSUE TITLE
Hashicorp Vault kubernetes auth method with ClusterSecretStore not working

### ISSUE THREAD

**Issue by tomikonio** [external-secrets/external-secrets#2560]
Hi,
I am using version `v0.9.1` .
I have an issue with the `kubernetes` method of authentication with `hashicorp-vault` .
Using the following `ClusterSecretStore`: 
```yaml
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
  namespace: external-secrets
spec:
  provider:
    vault:
      server: "https://somevault.com:8200"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "external-secrets"
          serviceAccountRef:
            name: "external-secrets"
            namespace: "external-secrets"

```
I am getting the following error on the `ClusterSecretStore`:
```bash
Warning  InvalidProviderConfig  6s (x10 over 10s)         cluster-secret-store  unable to log in to auth method: unable to log in with Kubernetes auth: Error making API request.

URL: PUT https://somevault.com:8200/v1/auth/kubernetes/login
Code: 403. Errors:

* permission denied
```

When I remove the `...kubernetes.serviceAccountRef.namespace` entry:
```yaml
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
  namespace: external-secrets
spec:
  provider:
    vault:
      server: "https://somevault.com:8200"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "external-secrets"
          serviceAccountRef:
            name: "external-secrets"
```
The secret store is marked as valid!

The problem that arises now is that the external-secret objects cannot work with it - getting the following error:
```json
{"level":"error","ts":1690785825.135757,"msg":"Reconciler error","controller":"externalsecret","controllerGroup":"external-secrets.io","controll  
erKind":"ExternalSecret","ExternalSecret":{"name":"app-dev","namespace":"app-dev"},  
"namespace":"app-dev","name":"app-dev","reconcileID":"248124b5-b43a-4574-876b-f604e  
a16aa00","error":"cannot request Kubernetes service account token for service account \"external-secrets\": serviceaccounts \"external-secrets\"  
not found","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.  
k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:324\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller  
).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:265\nsigs.k8s.io/c  
ontroller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/inte  
rnal/controller/controller.go:226"}
```
From what I get from the above is that I need to specify the namespace of the serviceaccount in the clusterstore, but, as I have shown - when the namespace is mentioned the clusterstore is marked as invalid.

Is this a bug or I have some misconfiguration going on?

**Expected behavior**
Using a `ClusterSecretStore` with kubernetes auth and let `ExternalSecert` objects from other namespaces work with it.
