### ISSUE TITLE
Configuring ECRAuthorizationToken using service account token

### ISSUE THREAD

**Issue by mteodor** [external-secrets/external-secrets#2566]
**Describe the bug**
Unable to configure ECRAuthorizationToken using service account token.

**To Reproduce**
Create ECRAuthorizationToken as
```
 apiVersion: generators.external-secrets.io/v1alpha1
  kind: ECRAuthorizationToken
  metadata:
    creationTimestamp: "2023-08-01T22:23:53Z"
    generation: 1
    name: test
    namespace: test
  spec:
    auth:
      jwt:
        serviceAccountRef:
          name: test-app-service
          namespace: test
    region: us-west-1
    role: arn:aws:iam::805133305776:role/testRole
kind: List
metadata:
  resourceVersion: ""

```

and service account
```
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::805133305776:role/testRole
  name: test-app-service
  namespace: test

```

and external secret
```
- apiVersion: external-secrets.io/v1beta1
  kind: ExternalSecret
  metadata:
    creationTimestamp: "2023-08-01T22:23:53Z"
    generation: 1
    name: external-secret-test
    namespace: test
  spec:
    dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ECRAuthorizationToken
          name: test
    refreshInterval: 1m
    target:
      creationPolicy: Merge
      deletionPolicy: Retain
      name: test-secret
      template:
        data:
          password: '{{ .password }}'
        engineVersion: v2
        mergePolicy: Replace
```

ESO v0.8.3
**Expected behavior**
Expect to have password in `test-secret` updated
however I'm getting following log error 
```
{"level":"error","ts":1690929960.1514747,"msg":"Reconciler error","controller":"externalsecret","controllerGroup":"external-secrets.io","controllerKind":"ExternalSecret","ExternalSecret":{"name":"external-secret-test","namespace":"test"},"namespace":"test","name":"external-secret-test","reconcileID":"6b7c2640-afba-4d8c-8d6a-22783d5c2238","error":"could not generate [0]: unable to get authorization token: AccessDenied: User: arn:aws:sts::805133305776:assumed-role/testRole/external-secrets-provider-aws is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::805133305776:role/testRole\n\tstatus code: 403, request id: 24231cd8-0415-479d-b815-bac15ee8bd71","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:235"}

```
my understanding is that what I provide as role in definition of generator is what controller will use to try to generate token, 
I dont understand where does this `external-secrets-provider-aws` comes from?
