### ISSUE TITLE
AWS provider fails validation for the new  `il-central-1` AWS region

### ISSUE THREAD

**Issue by adrianrgould** [external-secrets/external-secrets#2586]
**Describe the bug**

Cluster secret stores using AWS provider fail validation when the region is `il-central-1`:

```
admission webhook "validate.clustersecretstore.external-secrets.io" denied the request: region not found: il-central-1
```

**To Reproduce**

Create a new  AWS SSM Parameter Store  backed  secret store with `region: il-central-1` :
```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    # ARN of IAM role to use when querying SSM
    eks.amazonaws.com/role-arn: arn:aws:iam::12346789023:role/my-iam-role
  name: my-service-account
  namespace: external-secrets
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  annotations:
  name: my-secret-store
spec:
  provider:
    aws:
      auth:
        jwt:
          serviceAccountRef:
            name: my-service-account
            namespace: external-secrets
      region: il-central-1
      service: ParameterStore
```

Kubernetes 1.27
ESO 0.9.2

**Expected behavior**
AWS region id `il-central-1` should pass validation

**Additional context**
This is the (very) new AWS region in Tel Aviv.  It opened for business on 8/1/2023.  I suspect an update to the AWS SDK client would resolve the issue.
