### ISSUE TITLE
Prometheusrules in docs & helm chart 

### ISSUE THREAD

**Issue by wanddynosios** [external-secrets/external-secrets#2590]
**Is your feature request related to a problem? Please describe.**
I would like to reopen https://github.com/external-secrets/external-secrets/pull/1174

The new metrics which came with 0.9.1 allow for a few very useful PrometheusRules.

**Describe the solution you'd like**
In the original pr it was argued that maintaining the PrometheusRules in the chart would be too much effort. My suggestion here would be to at least make it possible to add custom PrometheusRules via the helm chart, without providing a default, e.g. by using a simplified version of [this](https://github.com/search?q=repo%3Aprometheus-community%2Fhelm-charts+additionalPrometheusRulesMap&type=code). The helm chart would then provide a link to the docs, where some examples could be provided.

This would make gitops setups easier, because currently we have have to maintain the PrometheusRules outside of the helm release.

I'd be happy to contribute it all, if we can reach consensus.

**Additional context**
These are the Rules I would suggest for the docs as stating point (ref https://github.com/external-secrets/kubernetes-external-secrets/discussions/544#discussioncomment-182611):
```yaml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: external-secrets
  namespace: external-secrets
  labels:
    release: my-prometheus
spec:
  groups:
    - name: external-secrets
      rules:
        - alert: SecretSyncError
          annotations:
            summary: SecretSyncError {{ $labels.name }}
            description: |
              Synchronization of the Secret `{{ $labels.name }}` in namespace `{{ $labels.exported_namespace }}` is failing.
              Check for errors in the Status field of the associated ExternalSecret object.
          expr: externalsecret_status_condition{status="False"} > 0
          for: 10m
        - alert: SecretStoreError
          annotations:
            summary: SecretStoreError {{ $labels.name }}
            description: |
              Synchronization of the SecretStore `{{ $labels.name }}` in namespace `{{ $labels.exported_namespace }}` is failing.
              Check for errors in the Status field of the associated SecretStoreError object.
          expr: secretstore_status_condition{status="False"} > 0
          for: 10m
        - alert: ClusterSecretStoreError
          annotations:
            summary: ClusterSecretStoreError {{ $labels.name }}
            description: |
              Synchronization of the ClusterSecretStore `{{ $labels.name }}` in namespace `{{ $labels.exported_namespace }}` is failing.
              Check for errors in the Status field of the associated ClusterSecretStoreError object.
          expr: clustersecretstore_status_condition{status="False"} > 0
          for: 10m
```
