### ISSUE TITLE
AWS cross account access (question/request)

### ISSUE THREAD

**Issue by Gianluca755** [external-secrets/external-secrets#2595]
Hello, I was wondering if the ESO supports the AWS cross account access, meaning the ESO in account A assumes a role, while in account B there is a secret with a resource policy allowing access for the role in account A.
It looks like it was available for KES https://github.com/external-secrets/kubernetes-external-secrets/issues/84.

If it's supported please add an example in the docs, otherwise it would be nice to have.

Thanks

**Comment by PLeS207** [comment]
Hello I have a similar question but wise versa 
Does ESO support cross-account secret access but without Assuming a role? only with permissions directly on a secret?

**Comment by atbee** [comment]
Hi @Gianluca755 and @PLeS207,

Here's a nugget from my experience. When using External Secrets with AWS cross accounts and leverage the assume role feature. Just insert the secret ARN into your ExternalSecret resource, like this:

```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example-externalsecret
spec:
  dataFrom:
  - extract:
      key: arn:aws:secretsmanager:<AWS_REGION>:<AWS_ACCOUNT_ID>:secret:<SECRET_ID> # Replace with your specific secret ARN
  secretStoreRef:
    kind: SecretStore
    name: example-secretstore
  target:
    name: example-secret
```

**Comment by Gianluca755** [comment]
@gusfcarvalho and for future readers, it actually works both with a cross account double role role setup and a cross account single role setup.

The single role setup needs the role in the SecretStore or ServiceAccount, the ExternalSecret that reference the ARN of the remote secret as key and the AWS resource-based policy of the secret for allowing the  access for role in the first account.

The double role setup works by creating a ServiceAccount with the annotation for the local role ARN `eks.amazonaws.com/role-arn:`, a SecretStore with the remote role ARN in `spec.provider.aws.role:` and the ExternalSecret that reference the ARN of the remote secret as key. Of course you need a trust policy for allowing the first role to assume the second.

**Comment by yongzhang** [comment]
> Hello I have a similar question but wise versa Does ESO support cross-account secret access but without Assuming a role? only with permissions directly on a secret?

I have the same question, I can't make it work today.

**Comment by gusfcarvalho** [comment]
As long as you specify the ARN for the secret, it will fetch that specific secret on another account.

**Comment by tatsuhikoum** [comment]
In my case, I was able to achieve this by following the steps below.
In short, I created two secret stores.

Prerequisite:
You have two accounts, each with resources
1, own-account: eks and secret-manager
2, another-account: secret-manager

eks wants to reference two secrets:

I created two secret-stores
1, Refer to the secret-manager of your own-account
2, Refer to the secret-manager of another-account
(I don't know if this can be achieved with one secretstore.)

> 1, Refer to the secret-manager of your own-account

is omitted.

>2, Refer to the secret-manager of another-account

1. Create a role (CrossAccountReadSecretManager) in another-account. 

Trusted entities:  `"AWS": "arn:aws:iam::${own-account-id}:root"`

Policy:
```
{
  "Statement": [
    {
      "Effect": "Allow",
      "Action": "secretsmanager:GetSecretValue",
      "Resource": "*"
    },
    {
      "Effect": "Allow",
      "Action": [
      "kms:Decrypt",
      "kms:DescribeKey"
      "Resource": "*"
    }
  ]
}
```

2. Create a service-account (another-account-secret-manager) in own-account
Make sure you can assume the role created in 1
```
{
  Version: "2012-10-17",
  Statement: [
    {
      "Effect": "Allow",
      "Action": "sts:AssumeRole",
      "Resource": "arn:aws:iam::${another-account}:role/CrossAccountReadSecretManager"
    },
  ]
}
```

3. Create a SecretStore in your own-account
```
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
  metadata:
  name: another-account-secrets-manager
namespace: default
  spec:
    provider:
      aws:
        service: SecretsManager
        region: ${region}
        role: arn:aws:iam::${another-account-id}:role/CrossAccountReadSecretManager
        auth:
          jwt:
            serviceAccountRef:
              name: another-account-secret-manager
```

Then you should be able to read the Secret manager from SecretStore created

In my case, it took me a while to come up with the idea of ​​creating separate secret stores for own and another.
