### ISSUE TITLE
ClusterSecretStore: Support namespace glob

### ISSUE THREAD

**Issue by speedfl** [external-secrets/external-secrets#2614]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**

I would like to be able to select namespace using globs so that I can apply company namespace naming convention.

Solution:

1. Add a feature switch such as `clustersecretstore-allow-namespace-glob` (boolean, default false) 
2. Improve [client_manager.go](https://github.com/external-secrets/external-secrets/blob/e5fd5a90a9129194d97a566918f1b3cd328e3616/pkg/controllers/secretstore/client_manager.go#L239) to support glob if feature is enabled

An example is the argocd `AppProject` , it is possible to use glob on destination namespaces

```yaml
kind: AppProject
apiVersion: argoproj.io/v1alpha1
metadata:
  name: project-two
  namespace: argocd
spec:
 destinations:
  - namespace: 'team-two*'
    server: '*'
```

If you are interested in this feature I can contribute.

**Describe alternatives you've considered**

- Create one SecretStore per namespace
- Use Kyverno to mutate SecretStore ref

**Additional context**

**Comment by gusfcarvalho** [comment]
Hi @speedfl . AFAIK you can already use MatchExpressions for that use case. 

Please let me know if that wouldn’t be fitting any specific case here.

**Comment by speedfl** [comment]
Hello.

I don't think MatchExpressions would do the job because It does not supports globs. It is useful when you know in advance the values. Here the goal is to support a pattern (kind of prefix).

Another example in argocd:

```
kind: AppProject
apiVersion: argoproj.io/v1alpha1
metadata:
  name: project-two
  namespace: argocd
spec:
 sourceRepos:
  - https://github.com/speedfl/* => allow to deploy from all repo prefixed with this
```

**Comment by gusfcarvalho** [comment]
Hm I wonder how would that effectively work. 🤔

**Comment by speedfl** [comment]
1. We add a flag [in the command](https://github.com/external-secrets/external-secrets/blob/e5fd5a90a9129194d97a566918f1b3cd328e3616/cmd/root.go#L260) such as `enable-cluster-store-namespace-glob` (default false). We cascade this config to the [client_manager.go](https://github.com/external-secrets/external-secrets/blob/e5fd5a90a9129194d97a566918f1b3cd328e3616/pkg/controllers/secretstore/client_manager.go#L240)

2. Create a utility tool for glob (copied from argocd)

```golang
package glob

import (
	"github.com/gobwas/glob"
	log "github.com/sirupsen/logrus"
)

func Match(pattern, text string, separators ...rune) bool {
	compiledGlob, err := glob.Compile(pattern, separators...)
	if err != nil {
		log.Warnf("failed to compile pattern %s due to error %v", pattern, err)
		return false
	}
	return compiledGlob.Match(text)
}

func MatchStringInList(list []string, item string, exactMatch bool) bool {
	for _, ll := range list {
		if item == ll || (!exactMatch && Match(ll, item)) {
			return true
		}
	}
	return false
}
```

4. In [client_manager.go](https://github.com/external-secrets/external-secrets/blob/e5fd5a90a9129194d97a566918f1b3cd328e3616/pkg/controllers/secretstore/client_manager.go#L240) support glob

```golang
if condition.Namespaces != nil {
	if enableGlobMatching && glob.MatchStringInList(condition.Namespaces, ns, false) {
		return true, nil // namespace in the namespaces list
	} else if slices.Contains(condition.Namespaces, ns) {
		return true, nil // namespace in the namespaces list
	}
}
```

Tell me if it is clearer 😃

**Comment by speedfl** [comment]
Up. Any feelings on this proposal ?
Do you want me to work on a PR so that you can try it ?

**Comment by gusfcarvalho** [comment]
No problems for me. @shuheiktgw do you see any technical issues here? 😁

**Comment by 12345ieee** [comment]
This is not relevant to the proposal proper, but I had the same exact need and I solved it by adding.
```yaml
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        team: team1
```
in my relevant argocd app definitions.

Then I fetch this back with a:
```yaml
  namespaceSelector:
    matchLabels:
      team: team1
```
in the CES.

This would have solved my usecase much more directly.
