### ISSUE TITLE
BREAKING CHANGE - Unable to create k8s secrets with name larger than 55 characters with v0.9.3

### ISSUE THREAD

**Issue by vb250182** [external-secrets/external-secrets#2616]
**Describe the bug**
In previous versions, we were able to create k8s secrets through ESO with a name larger than 55 characters. Now, when we create an external-secrets with 56-63 characters, the external-secrets resource gets created, but the k8s secret cannot.

**To Reproduce**
1. provide all relevant manifests

ESO YAML that fails to create the k8s secret with a name with 56 characters.
```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: unable-to-create-long-name-secrets-anymore-1234567890123
  namespace: default
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: ESO_ISSUE_0_9_3
      version: latest
    secretKey: result
  refreshInterval: 10m
  secretStoreRef:
    kind: ClusterSecretStore
    name: es-cluster-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
```

3. provide the Kubernetes and ESO version
kubernetes: 1.25.10-gke.1200
ESO: v0.9.3

**Expected behavior**
In previous versions, we were able to create secrets that were at least 61 characters long. 
We expect the same behavior as before.

**Screenshots**

Unable to create k8s secret:
<img width="763" alt="image" src="https://github.com/external-secrets/external-secrets/assets/33496975/8aee62d5-5daa-4917-85f9-08c0daa9008c">

Secret created successfully with 55 characters in the name field
<img width="717" alt="image" src="https://github.com/external-secrets/external-secrets/assets/33496975/5a5b3b66-3c3a-4045-ab28-93b35d8ea72e">

**Additional context**
