### ISSUE TITLE
Can not pass specific Access Key&Secret when fetch secret KMS in ALI Cloud

### ISSUE THREAD

**Issue by Duanjax** [external-secrets/external-secrets#2619]
**Describe the bug**

Can not fetch remote KMS secret using Access key authentication in Ali Cloud provider. Got error 'The specified parameter AccessKeyId is not valid'

1、The secretstore resource is Valid status
2、I can decode my access key and secret, they are coccect and have admin access
3、But the external secret resource is SecretSyncedError

**To Reproduce**
1. creat secretsore resource
```
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: demo-store
spec:
  provider:
    alibaba:
      regionID: cn-shanghai
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: ali-access-key-secret
            key: access-key-id
          accessKeySecretSecretRef:
            name: ali-access-key-secret
            key: access-key-secret
```
2. create accesskey and secret using  kubernetes secret 

```
apiVersion: v1
kind: Secret
metadata:
  name: demo-secret
data:
  access-key-id: <access-key-id-in-base64>
  access-key-secret:  <access-secret-id-in-base64>
```
3、 create external secret resource
```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: demo-external-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: demo-store
    kind: SecretStore
  target:
    name: demo-secret
    creationPolicy: Owner
  data:
    - secretKey: key-secret
      remoteRef:
        key: <my-key>
```  

**Expected behavior**
 external secret resource should be ready

**Screenshots**
<img width="1664" alt="image" src="https://github.com/external-secrets/external-secrets/assets/86959085/71a60eaf-68f2-4ace-9b46-13018615c07d">

<img width="1679" alt="image" src="https://github.com/external-secrets/external-secrets/assets/86959085/ec72cbc5-adc4-45dc-83f8-e4ed86fb9e63">

<img width="1267" alt="image" src="https://github.com/external-secrets/external-secrets/assets/86959085/f25520a6-75a0-48f8-ab5d-6775261df4a9">

kubernetes version 

k8s Version: v1.23.0
Server Version: v1.26.3-aliyun.1

full error meaages

StatusCode: 400                                                                                                                                                                                                │    Code: InvalidParameter
│    Message: code: 400, The specified parameter AccessKeyId is not valid.
│    Data: {"Code":"InvalidParameter","HttpStatus":400,"Message":"The specified parameter AccessKeyId is not valid.","statusCode":400}
