### ISSUE TITLE
External Secrets Manager 0.9.3 on OCP crash by targeting destroyed secrets within IBM Secrets Manager

### ISSUE THREAD

**Issue by heygogit** [external-secrets/external-secrets#2632]
**Describe the bug**

The external secrets operator on OCP running into an error which leads into an crash and restart cycle of the corresponding Secrets Operator Pod. 

```
# Error from the log
secrets.io","controllerKind":"ExternalSecret","ExternalSecret":{"name":"my-token","namespace":"default"},"namespace":"default","name":"my-token","reconcileID":"0a09f0bb-XXXX-YYYY-ZZZ-ea45f57c2247"}
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x239b56e]

goroutine 308 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.1/pkg/internal/controller/controller.go:115 +0x1fa
panic({0x3151f60, 0x6685e20})
	/opt/hostedtoolcache/go/1.19.12/x64/src/runtime/panic.go:884 +0x212
github.com/external-secrets/external-secrets/pkg/provider/ibm.getArbitrarySecret(0xc000650930?, 0xc0012b1f00)
	/home/runner/work/external-secrets/external-secrets/pkg/provider/ibm/provider.go:218 +0x4e
github.com/external-secrets/external-secrets/pkg/provider/ibm.(*providerIBM).GetSecret(0xc00037e560, {0x7fec18191a68?, 0x30?}, {{0xc000650930, 0x2e}, {0x0, 0x0}, {0x0, 0x0}, {0x0, ...}, ...})
	/home/runner/work/external-secrets/external-secrets/pkg/provider/ibm/provider.go:154 +0x293
github.com/external-secrets/external-secrets/pkg/controllers/externalsecret.(*Reconciler).handleSecretData(_, {_, _}, _, {{{0x2c87ff2, 0xe}, {0xc008a244c0, 0x1b}}, {{0xc000544bc0, 0x1e}, ...}, ...}, ...)
	/home/runner/work/external-secrets/external-secrets/pkg/controllers/externalsecret/externalsecret_controller_secret.go:96 +0xd3
github.com/external-secrets/external-secrets/pkg/controllers/externalsecret.(*Reconciler).getProviderSecretData(0xc0004dca10, {0x4046e58, 0xc008b31aa0}, 0xc000cc2600)
	/home/runner/work/external-secrets/external-secrets/pkg/controllers/externalsecret/externalsecret_controller_secret.go:78 +0x2be
github.com/external-secrets/external-secrets/pkg/controllers/externalsecret.(*Reconciler).Reconcile(0xc0004dca10, {0x4046e58, 0xc008b31aa0}, {{{0xc00064e5b0, 0x10}, {0xc000544bc0, 0x1e}}})
	/home/runner/work/external-secrets/external-secrets/pkg/controllers/externalsecret/externalsecret_controller.go:202 +0xec5
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x4046e58?, {0x4046e58?, 0xc008b31aa0?}, {{{0xc00064e5b0?, 0x2f2a780?}, {0xc000544bc0?, 0x10?}}})
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.1/pkg/internal/controller/controller.go:118 +0xc8
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0006b40a0, {0x4046db0, 0xc0003553c0}, {0x3382a00?, 0xc001214740?})
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.1/pkg/internal/controller/controller.go:314 +0x3a5
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0006b40a0, {0x4046db0, 0xc0003553c0})
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.1/pkg/internal/controller/controller.go:265 +0x1d9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.1/pkg/internal/controller/controller.go:226 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.1/pkg/internal/controller/controller.go:222 +0x333
```

**To Reproduce**

1. Create an external secrete which targets an destroyed secret within IBM Secrets Manager.

```yaml
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: sm-store
  namespace: default
spec:
  provider:
    ibm:
      auth:
        secretRef:
          secretApiKeySecretRef:
            key: apikey
            name: secret-manager-apikey
      serviceUrl: >-
        https://<my-secret-manager-service-url>
--
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sm-token
  namespace: default
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: arbitrary/<my-secret-ref-id>
      secretKey: token
  refreshInterval: 10m
  secretStoreRef:
    kind: SecretStore
    name: sm-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: my-token
```

2. Using 
RedHat Openshift Version 4.12.22
ESO Version 0.9.3

3. Using
N/A as crash occurs during synchronization

**Expected behavior**
Not crash but stop syncing for that secret.

**Screenshots**
![image](https://github.com/external-secrets/external-secrets/assets/92973673/1852e383-4095-4daa-830b-2e3a2a5eb175)
