### ISSUE TITLE
Add config option to PushSecret to prevent overriding values in external secret store 

### ISSUE THREAD

**Issue by maresac** [external-secrets/external-secrets#2643]
Problem Description

I would like to use ESO to generate a password and then save it to an external secret store. Once the password is generated and pushed, I want the secret store to become the source of truth, so that the password won't be overridden when ExternalSecret or Secret Resources are deleted and regenerated. 
Currently there is no way to prevent this override on regeneration, which can lead to problems with applications consuming the password, that cannot automatically handle password changes. 

Solution Description

There should be an option to prevent PushSecrets from updating values in the secret store, if there already is a value present at the specified location. A possibility would be to configure a `creationPolicy` on the PushSecret resource. For example, if the `creationPolicy` is `Replace`, the value in the secret store should be overridden by default. If it is set to `Merge`, the potential value already present in the secret store should have a higher precedence and should not be updated.

cc @moolen @gusfcarvalho 
Link to Slack thread: https://kubernetes.slack.com/archives/C017BF84G2Y/p1692360187019849

**Comment by moolen** [comment]
Hey, we should write up a design doc for the `creationPolicy`. I can try to come up with something - unless you're working on something already.
Feel free to carry out a PoC implementation that works for you in your context, i'll develop the design doc along the way.

**Comment by moolen** [comment]
Let me quickly share my thoughts around this issue. I'm going to :package: that into a design doc soon to get further feedback on it.

#### (1) Proposal: add `spec.updatePolicy` 

The PushSecret lifecycle consists of these 3 parts:
1. **create** the secret on the provider side
2. **update** the secret value every `spec.refreshInterval`
3. **delete** the secret 

For each part we can apply a policy. For this :point_up_2: use-case the `update` part is relevant. The `create` is not really interesting (discussed [here](https://github.com/external-secrets/external-secrets/pull/2465#discussion_r1254930769) before), and we have a `deletionPolicy` already implemented.

I would propose a `updatePolicy` with the following values: 
* `Replace` default, current behaviour: just write the value
* `IfNotExists`: writes a value only if it doesn't exist

```yaml
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: pushsecret-example
  namespace: default
spec:
  updatePolicy: Replace|IfNotExists
  deletionPolicy: Delete|None
  # ...
```

```mermaid
flowchart TD
    
    C{Create} --> |no policy here| F{Update}
    F -->|updatePolicy=Replace| G[Always overrides the existing value]
    F -->|updatePolicy=IfNotExists| H[Writes the value only\n if no value exists]
    G --> F
    H --> F
    G --> I{Delete}
    H --> I{Delete}
    I --> |deletionPolicy=Delete| J[Deletes the secret]
    I --> |deletionPolicy=None| K[Retains the existing secret]
```

#### (2) Idea: enhance spec.selector

We can consider extending the PushSecret's `spec.selector`, which defines the `source` of a secret value which is supposed to be pushed. At the moment it only supports `secret` resources, but we can point to a `generator`: That would remove the need for the indirection of a `ExternalSecret+Generator+Secret` to generate a value and then a `PushSecret` to push it. Instead, you would just have the `PushSecret+Generator`  

It could look something like this:
```yaml
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
spec:
  selector:
    generatorRef:
      apiVersion: generators.external-secrets.io/v1alpha1
      kind: Password
      name: "my-password"
  # ...
```
