### ISSUE TITLE
0.9.3 version does not create local secrets when the name length is 84 characters

### ISSUE THREAD

**Issue by ealogar** [external-secrets/external-secrets#2647]
**Describe the bug**
The local secrets are not created when the target name is bigger than 84 length

**To Reproduce**
you create an external-secret with a target name reference to the local secret to be of 84 character lenght (In k8s the maximum-lengh is 253 characters for this resources).
With the 0.9.2 and before, the secret is synchronized correctly, the local secret created and binded to the external secret.
With 0.9.3 this has stopped working, the external secret is created and the status is healthy/synchronized but the local secret is not created and the binded 



Kubernetes version 1.26

**Expected behavior**
The local secret should be created as the maximum-lenght is not more than 253 characters

**Screenshots**
with 0.9.3:
```yaml
 status:                                                                                                                                                                                                                                                                                                            
   conditions:                                                                                                                                                                                                                                                                                                      
   - lastTransitionTime: "2023-08-23T20:00:01Z"                                                                                                                                                                                                                                                                     
     message: Secret was synced                                                                                                                                                                                                                                                                                     
     reason: SecretSynced                                                                                                                                                                                                                                                                                           
     status: "True"                                                                                                                                                                                                                                                                                                 
     type: Ready                                                                                                                                                                                                                                                                                                    
   refreshTime: "2023-08-23T20:00:02Z"                                                                                                                                                                                                                                                                              
   syncedResourceVersion: 1-e1c55a9d2c142485c954a4c490697412
```

with 0.9.2 and below:

```yaml
status:
  binding:
    name: test-xxxxxx-longlabel-morethan-63-characters-xxxxxxxxxxxx-filler-externalsecret22
  conditions:
  - lastTransitionTime: "2023-08-23T18:52:15Z"
    message: Secret was synced
    reason: SecretSynced
    status: "True"
    type: Ready
  refreshTime: "2023-08-23T19:09:19Z"
  syncedResourceVersion: 1-82b1b746d7e617ce6c865d3ae87135e3
```

The difference is that the binding is not happening and the local secret not created.
**Additional context**
For secrets of 20-40 characters length is working well (with 0.9.3)

This is the k8s template for the external secret:
```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations: {}
  labels: {}
  name: test-xxxxxx-longlabel-morethan-63-characters-xxxxxxxxxxxxx-filler-externalsecret22
  namespace: test-ns
spec:
  dataFrom:
  - extract:
      key: test/xxxxxx/LongLabel/MoreThan/63/Characters/xxxxxxxxxxxxx/Filler/externalSecret22
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: default
  target:
    name: test-xxxxxx-longlabel-morethan-63-characters-xxxxxxxxxxxxx-filler-externalsecret22
```
