### ISSUE TITLE
How to get single property from the json 

### ISSUE THREAD

**Issue by bala151187** [external-secrets/external-secrets#2663]
Here is my External secret definition

```
apiVersion: external-secrets.io/v1beta1 
kind: ExternalSecret
metadata:
  name:  lab-devops-helloworld-node-external-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secretstore
    kind: ClusterSecretStore
  target:
    name: lab-devops-helloworld-node-rdsmasterpassword
  dataFrom:
  - find:
      tags:
        app-environment: LAB
        app-service: helloworld_nodejs
        app-platform: k8s
    rewrite:
    - regexp:
        source: "(.*)"
        target: "password"
```
The secret i get like this
![Screenshot 2023-08-29 at 9 54 17 AM](https://github.com/external-secrets/external-secrets/assets/5027627/855ca21f-809c-4039-99bb-aea8b26bb0c6)

I want just the **password** property 

I **could not** use the extract & key . bcoz the **key name** is **dynamic** which i cannot control . that's get autogenerated when RDS database gets created and manage it's master password 

Please let me know how to get just the value of password property

**Comment by bala151187** [comment]
@moolen @gusfcarvalho Please help

**Comment by gusfcarvalho** [comment]
You can use templates to “open up” the secret you have. https://external-secrets.io/latest/guides/templating/

In this case templating fromLiteral should be enough.

**Comment by bala151187** [comment]
@gusfcarvalho thanks for the reply .. i tried like this 
`apiVersion: external-secrets.io/v1beta1 
kind: ExternalSecret
metadata:
  name:  lab-devops-helloworld-node-external-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secretstore
    kind: ClusterSecretStore
  target:
    name: lab-devops-helloworld-node-rdsmasterpassword
    template:
      data:
        password : "{{ .rdspwd }}"
  data:
  - secretKey: rdspwd
    remoteRef:
      key: rds!db-74f2c27b-3d0f-4389-bbf7-1786d5b019eb`

**Comment by bala151187** [comment]
@moolen Any help appreciated

**Comment by moolen** [comment]
> I could not use the extract & key . bcoz the key name is dynamic which i cannot control

Just to be clear: AFAIK the AWS Secrets Manager **secret name** is dynamic. The structure of the secret value is always the same ([taken from here](https://docs.aws.amazon.com/secretsmanager/latest/userguide/reference_secret_json_structure.html)):

```json
{
  "engine": "mysql",
  "host": "<instance host name/resolvable DNS name>",
  "username": "<username>",
  "password": "<password>",
  "dbname": "<database name. If not specified, defaults to None>",
  "port": "<TCP port number. If not specified, defaults to 3306>"
}
```

you can try something like this:

This iterates over all secrets matching the desired tags.
For each secret: (1) parse as json, (2) iterate over json key/value pairs and set them as output.
Note: if you have multiple secrets the last one will take precedence. It would be best to reference the particular secret name with `data` as in your example above.
 
```yaml
apiVersion: external-secrets.io/v1beta1 
kind: ExternalSecret
metadata:
  name:  lab-devops-helloworld-node-external-secret
spec:
  # ...
  target:
    name: lab-devops-helloworld-node-rdsmasterpassword
    template:
      templateFrom:
      - target: Data
        literal: |
          {{ range $key, $value := . }}
          {{ $parsed := fromJson $value }}
          {{ range $pk, $pv := $parsed }}
          {{ $pk }}: {{ $pv }}
          {{ end }}
  dataFrom:
  - find:
      tags:
        app-environment: LAB
        app-service: helloworld_nodejs
        app-platform: k8s
    rewrite:
    - regexp:
        source: "(.*)"
        target: "password
```
