### ISSUE TITLE
ExternalSecretSet: Generate mutliple ExternalSecret from a path

### ISSUE THREAD

**Issue by speedfl** [external-secrets/external-secrets#2670]
**Is your feature request related to a problem? Please describe.**

In some cases it could be interesting to generate multiple ExternalSecret based on a path.

Example:

I have several secrets with same format (ie: argocd repositories/db connection strin) under a path.

Example:

```
/teams/teamone/argocd/repositories/repo1
/teams/teamone/argocd/repositories/repo2
/teams/teamone/argocd/repositories/repo3
/teams/teamone/argocd/repositories/repo4
```

The format is always:

```json
{
   "repoURL": "http://github.com/test/test.git",
   "project": "teamone",
   "username": "argocd",
   "password": "123456"
}
```

**Describe the solution you'd like**

I want an auto discovery based on `/teams/teamone/argocd/repositories/*` so that each time a new repository is added in `/teams/teamone/argocd/repositories/` an ExternalSecret is created

```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecretSet
metadata:
  name: "hello-world"
spec:
  syncPolicy:
    childPolicy: "create-only" # create-only / create-delete / create-update / sync
  refreshTime: "1m"
  generators:
      - path:  `/teams/teamone/argocd/repositories/*`
  template: # This is an ExternalSecretTemplate
    metadata:
      labels:
        key: value
      annotation: 
        key: value
      name: "teamone-{ .key }-secret"
    spec:
      secretStoreRef:
        name: secret-store-name
        kind: SecretStore

      refreshInterval: "1h"
```

A `ownerReference` must be added to the generated `ExternalSecret` 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A
