### ISSUE TITLE
Add labels from ExternalSecret object to Prometheus metrics

### ISSUE THREAD

**Issue by ppmkmd** [external-secrets/external-secrets#2676]
**Describe the solution you'd like**

The goal is to have custom labels from **ExternalSecret** object also available as labels in Prometheus metrics.
As I can see similar issue was created some time ago, but only recommended labels have been added as a scope of similar request: #1994 

**Additional context**
An awesome example was provided in the #1994 for the **"owner"** label.
Let's say that my ExternalSecret object looks like this:
```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  labels:
    app: xyz
    app.kubernetes.io/instance: xyz
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: xyz
    app.kubernetes.io/version: 0.1.0
    owner: good-secret-team
  name: xyz-secret
  namespace: test
spec:
  data:
  - remoteRef:
      key: awesome-key
    secretKey: SUPER_SECRET_REFERENCE
  refreshInterval: 30m
  secretStoreRef:
    kind: ClusterSecretStore
    name: clustersecretstore
  target:
    name: xyz-secret
```
The metrics I would like to have in Prometheus should be like:
```
externalsecret_status_condition{condition="Ready",name="xyz-secret",namespace="test",owner="good-secret-team",app="xyz",status="False"} 0
externalsecret_status_condition{condition="Ready",name="xyz-secret",namespace="test",owner="good-secret-team",app="xyz",status="True"} 1
```
