### ISSUE TITLE
"failed to make EC2Metadata request" error is logged

### ISSUE THREAD

**Issue by benbertrands** [external-secrets/external-secrets#2677]
**Describe the bug**
When reconciling secrets, external-secrets logs:
```
{"level":"debug","ts":1693923112.0465071,"logger":"controllers.ExternalSecret","msg":"reconciled secret","ExternalSecret":{"name":"frontend-app-web-qa","namespace":"qa"}}
{"level":"debug","ts":1693923112.0465474,"logger":"events","msg":"Updated Secret","type":"Normal","object":{"kind":"ExternalSecret","namespace":"qa","name":"frontend-app-web-qa","uid":"ca8c7a9d-3b7c-43c4-a392-c03413463a54","apiVersion":"external-secrets.io/v1beta1","resourceVersion":"1484903265"},"reason":"Updated"}
{"level":"debug","ts":1693923112.2464817,"logger":"controllers.ExternalSecret","msg":"skipping refresh","ExternalSecret":{"name":"qa-virtualagent-adapter-qa","namespace":"qa"},"rv":"1-0faa1aff80d50959c482ac26500cdc5c"}
{"level":"debug","ts":1693923112.4468837,"logger":"clientmanager","msg":"creating new client","provider":"*aws.Provider","store":"develop/databus-monitor-develop"}
{"level":"info","ts":1693923112.4470282,"logger":"provider.aws","msg":"using aws session","region":"us-east-1","external id":"","credentials":null}
{"level":"info","ts":1693923112.4470694,"logger":"provider.aws.secretsmanager","msg":"fetching secret map","key":"dev/databus-monitor/secrets"}
{"level":"info","ts":1693923112.4470785,"logger":"provider.aws.secretsmanager","msg":"fetching secret value","key":"dev/databus-monitor/secrets","version":"AWSCURRENT","value":"SECRET"}
2023/09/05 14:11:52 WARN: failed to get session token, falling back to IMDSv1: 403 Forbidden: Forbidden
	status code: 403, request id:
caused by: EC2MetadataError: failed to make EC2Metadata request

	status code: 403, request id:

```

**To Reproduce**
1. provide all relevant manifests
This is our Chart.yaml:
```
apiVersion: v2
name: external-secrets
version: 0.1.0
dependencies:
  - name: external-secrets
    version: 0.9.4
    repository: https://charts.external-secrets.io

```    
And these are our helm values:
```
external-secrets:
      podAnnotations:
        iam.amazonaws.com/role: arn:aws:iam::SuperSecretAccountNumber:role/qa-external-secrets 

```
2. provide the Kubernetes and ESO version
 
k8s: v1.25.11
ESO: 0.9.4
 
**Expected behavior**
Not seeing this error in the logs

**Additional context**
As can be seen in our helm values, we use [IRSA](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html) to bind to the correct aws role.
Why are EC2Metadata calls made? I haven't been able to find anything in the external secrets source code.
The error is created [here](https://github.com/aws/aws-sdk-go/blob/07a76fa4aedbed35c5efc68d9cd3e3f5dd33dea7/aws/ec2metadata/token_provider.go#L68)

**Comment by moolen** [comment]
Hey, can you post your `SeretStore` resource? What authentication method do you use? 
If you don't specify an authentication method, it falls back the default credentials chain. If you intend to run ESO with IRSA, does the ESO pod has the correct environment variables set, like `AWS_ROLE_ARN`, `AWS_WEB_IDENTITY_TOKEN_FILE` - these are supposed to be injected by the EKS.

Why does the IMDSv2 endpoint respond with `http.StatusForbidden, http.StatusNotFound, http.StatusMethodNotAllowed` ?

**Comment by benbertrands** [comment]
> Hey, can you post your SeretStore resource?

This is an example of one of our SecretStores
I should have mentioned that functionality wise we're all set. Its just the warn message in the logs that is a bit weird

```
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata: 
  annotations:
    iam.amazonaws.com/role: arn:aws:iam::123456789012:role/qa-external-secrets
  ...
spec:
  provider:
    aws:
      region: us-east-1
      role: 'arn:aws:iam::123456789012:role/dev-auto-responder'
      service: SecretsManager
status:
  capabilities: ReadWrite
  conditions:
    - lastTransitionTime: '2023-07-25T13:24:37Z'
      message: store validated
      reason: Valid
      status: 'True'
      type: Ready

```


> What authentication method do you use?
If you don't specify an authentication method, it falls back the default credentials chain. If you intend to run ESO with IRSA, does the ESO pod has the correct environment variables set, like AWS_ROLE_ARN, AWS_WEB_IDENTITY_TOKEN_FILE - these are supposed to be injected by the EKS.

Looks like I left out some important information(😳 ): This is not an EKS k8s cluster and we use [kube2iam](https://github.com/jtblin/kube2iam) to bind every pod to its own iam-role. 
The external secrets pod is given role arn:aws:iam::123456789012:role/qa-external-secrets, this role allows nothing but can assume more specific roles that have access to secific secrets in aws secrets-manager(eg arn:aws:iam::123456789012:role/dev-auto-responder)
The external secrets pod manages to retrieve secrets successfully 

>Why does the IMDSv2 endpoint respond with http.StatusForbidden, http.StatusNotFound, http.StatusMethodNotAllowed ?

I'll try to look into this later today
