### ISSUE TITLE
Labels are not removed from generated Secret when removed from the ExternalSecret

### ISSUE THREAD

**Issue by eliaoggian** [external-secrets/external-secrets#2682]
**Describe the bug**
When adding labels to the secret, either on the `metadata.labels` field or on the `spec.target.template.metadata.labels`, they get correctly added to the generated secret. Removing a label from the `ExternalSecret` manifest will not remove it from the generated secret 

**To Reproduce**

1. Apply the externalsecret:

```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cluster-se
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
spec:
  refreshInterval: "60s"
  secretStoreRef:
    name: vault-argocd
    kind: ClusterSecretStore
  target:
    name: cluster-se
    template:
      metadata:
        labels:
          foo: bar
          new: label
  data:
  - secretKey: name
    remoteRef:
      key: cluster-se
      property: name
  - secretKey: server
    remoteRef:
      key: cluster-se
      property: server
  - secretKey: config
    remoteRef:
      key: cluster-se
      property: config
```

2. Remove the `new: label` label

**Versions:** 
Kubernetes: 1.22.5
ESO: 0.9.4 

**Expected behavior**
The `new: label` label should be removed from the secret. But it's not. 

**Additional context**
`ExternalSecret` is deployed with ArgoCD, but it should not matter.
