### ISSUE TITLE
ExternalSecret template not extracting data from ECRAuthorizationToken Generator

### ISSUE THREAD

**Issue by rteeling** [external-secrets/external-secrets#2690]
**Describe the bug**

I need to build a valid AWS ECR dockerconfig secret for another controller I'm using. 
When I attempt to use the templating feature, none of the output variable from the ECR generator seem to be populating. I was unable to find a manifest of this via a web search so I've taken my best cut at this. Perhaps the struct for the template is not what I expect it to be?

**To Reproduce**

Account/region/namespace info redacted for security reasons
```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::[account-a]:role/my-irsa-role
  name: ecr-readonly
  namespace: my-namespace

---
apiVersion: generators.external-secrets.io/v1alpha1
kind: ECRAuthorizationToken
metadata:
  name: ecr-readonly
spec:
  region: REGION
  role: "arn:aws:iam::[account-b]:role/ecr-readonly"
  auth:
    jwt:
      serviceAccountRef:
        name: "ecr-readonly"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ecr-readonly
spec:
  refreshInterval: "10h"
  target:
    name: ecr-readonly
    template:
      engineVersion: v2
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "{{ .proxy_endpoint }}": {
                "auth": "{{ list .username ":" .password | join "" | b64enc }}"
              }
            }
          }
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: ECRAuthorizationToken
        name: ecr-readonly
```

When I do not use the template, the ExternalSecret correctly populates the secret data with the `username`, `password`, `proxy_endpoint`, and `expires_at` properties, which renders like this (base64 decoded)

```
{
  "auths": {
    "": {
      "auth": "Og=="
    }
  }
}
```
(the auth is just the colon)

when i reference them in the template the values are empty, so I can safely eliminate iam auth as the problem. I am using IRSA role-chaining as my cluster is running in a different account from my ECR registry

K8S version 1.24
ESO version 0.9.4

**Expected behavior**
`.proxy_endpoint`, `.username` and `.password` get populated and the template renders my dockerconfig json properly

**Additional context**
I used the template structure provided in the Azure container registry page and the ECRAuthorizationToken generator doc to imply the struct that should be given to the template, so I may have made an error there.

Thanks for your help!

**Comment by moolen** [comment]
Hey, i can not reproduce the issue. Though i found an issue where an error is swallowed [here](https://github.com/external-secrets/external-secrets/blob/main/pkg/controllers/externalsecret/externalsecret_controller.go#L299C1-L300C1), the error assignment is wrong. I'll provide a patch for that asap.

That bug can trigger when you e.g. have invalid json or any other issue that prevents a secret create or update (although the external secrets shows that everything is fine :disappointed: ).

**Comment by rteeling** [comment]
@moolen  Thanks for looking into this, I've resolved the issue and it was entirely self inflicted - I've been deploying this via helm, so I ended up needing to properly escape the template - helm was attempting to resolve the variables before the controller, and so the CR rendered improperly

I changed my manifest to this, and it worked.

``` yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::[account-a]:role/my-irsa-role
  name: ecr-readonly
  namespace: my-namespace

---
apiVersion: generators.external-secrets.io/v1alpha1
kind: ECRAuthorizationToken
metadata:
  name: ecr-readonly
spec:
  region: REGION
  role: "arn:aws:iam::[account-b]:role/ecr-readonly"
  auth:
    jwt:
      serviceAccountRef:
        name: "ecr-readonly"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ecr-readonly
spec:
  refreshInterval: "10h"
  target:
    name: ecr-readonly
    template:
      engineVersion: v2
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "{{printf  "{{ .proxy_endpoint }}" }}": {
                "auth": "{{printf "{{ printf \"%%s:%%s\" .username .password | b64enc }}" }}"
              }
            }
          }**
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: ECRAuthorizationToken
        name: ecr-readonly
```

I'm on  a work machine and my company policy forbids me from creating public PR's so I'll push a doc change PR once I get home. It would be would be very helpful to emphasize that you need to properly escape everything if you use helm instead of just a code block comment.

I'm going to close the issue as it was self-inflicted. Sorry for taking up your time
