### ISSUE TITLE
Provider: AWS Parameter Store

### ISSUE THREAD

**Issue by moolen** [external-secrets/external-secrets#27]
Implement AWS Parameter Store Provider

AC:
* SecretStore should expose AWS Parameter Store as a backend
* Authentication mechanisms implemented: pull credentials from secret, use ambient credentials

**Comment by mcavoyk** [comment]
For AWS Parameter store, I would propose a change to the current SecretStore spec for aws configuration. The current provider field is nested under `awssm`, but `region`, `role` and the secretRef for credentials will all be shared between AWS Parameter store and AWS Secret Store https://github.com/external-secrets/external-secrets/issues/26. Instead the current fields should be nested under `aws`, and a new required `service` field is required with the enum values `SecretManager` or `ParameterStore`. 

The advantages are deduplication of the AWS values for the store, with a disadvantage of another required field. Not sure any default makes sense for the enum between the two values, so would need to be left to user input and documented. 

```yaml
apiVerson: external-secrets.io/v1alpha1
kind: SecretStore # or ClusterSecretStore
metadata:
  name: vault
  namespace: example-ns
spec:
  provider:
    aws:
      service: ParameterStore # or SecretManager
      region: eu-central-1
      role: iam-role
      auth:
        secretRef:
          accessKeyID:
            name: awssm-secret
            key: access-key
          secretAccessKey:
            name: awssm-secret
            key: secret-access-key
```

@moolen
