### ISSUE TITLE
Kubernetes/PushSecret panic when target Secret already exists and empty

### ISSUE THREAD

**Issue by faust64** [external-secrets/external-secrets#2700]
**Describe the bug**
I did notice that when I create a PushSecret, using some Kubernetes SecretStore, expecting that PushSecret to set a key on a Secret that already exists, yet does not have any data yet. then the external-secrets-operator starts crashing on a loop

**To Reproduce**
```
---
kind: SecretStore
spec:
  provider:
    kubernetes:
      auth:
        serviceAccount:
          name: xxx
        [ca+url]
---
kind: PushSecret
spec:
  data:
  - match:
      remoteRef:
        property: abc
        remoteKey: my-operated-secret
      secretKey: password
  deletionPolicy: None
  refreshInterval: 120s
  secretStoreRefs:
  - kind: SecretStore
    name: that-one-above
  selector:
    secret:
      name: source-secret
---
kind: Secret
metadata:
  name: my-operated-secret
[ NO DATA ]
```

2. provide the Kubernetes and ESO version

v0.9.4 -- running in OpenShift, installed through OLM

**Expected behavior**

ESO shouldn't crash when asked to write a key, in an existing Secret that doesn't have any data yet.

**Screenshots**

N/A

**Additional context**

For context: using OpenShift GitOps operator, ArgoCD stack is lifecycled by an operator, that would also provide us with some empty Secret.
We need to push keys in that Secret, for the ArgoCD notifications controller to authenticate against remote services.

When PushSecret object is creqted before deployment of the ArgoCD stack: everything works prefectly.
While if the External Secrets Operator finds that target Secret already existing, yet with no data defined in it: then it crashes.

Can workaround adding some foo=bar key, which unblocks ESO, now able to push my  secrets as expected.
Still it would be nice for ESO not to crash here. No data in a Secret could happend.
