### ISSUE TITLE
Cluster scope requires namespace error for ClusterSecretStore in oracle provider

### ISSUE THREAD

**Issue by antoniolago** [external-secrets/external-secrets#2727]
**Describe the bug**
While trying to kubectl apply a ClusterSecretStore, get:
`Error from server (Forbidden): error when creating ".": admission webhook "validate.clustersecretstore.external-secrets.io" denied the request: cluster scope requires namespace`

I tried messing with the namespaces and nothing seems to work. 

In kind=SecretStore the store is validated just fine, it only occurs as ClusterSecretStore.

**To Reproduce**
1. provide all relevant manifests
```
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: oracle-vault-store-pessoal
  namespace: external-secrets
spec:
  provider:
    oracle:
      vault: #vault_ocid
      region: sa-saopaulo-1
      auth:
        user: #user-ocid
        tenancy: #tenancy-ocid
        secretRef:
          privatekey:
            name: oracle-secret
            key: privateKey
          fingerprint:
            name: oracle-secret
            key: fingerprint
  conditions:
    - namespaces:
      - "external-secrets"
      - "radar-voluntario-dev"

```
3. provide the Kubernetes and ESO version
k8s: 1.27.2
ESO: 0.9.5

**Expected behavior**
ClusterSecretStore should be created with the namespace passed in the manifest
