### ISSUE TITLE
GCP workloadidentity auth not working

### ISSUE THREAD

**Issue by ricosega** [external-secrets/external-secrets#2740]
Can't make it work in GCP with workloadIdentity.
I got the following error:

```
{
  "level": "error",
  "ts": 1695908232.6423109,
  "logger": "controllers.ClusterSecretStore",
  "msg": "unable to validate store",
  "clustersecretstore": {
    "name": "gke-secrets-manager"
  },
  "error": "could not get provider client: failed to create GCP secretmanager client: unable to fetch identitybindingtoken: could not get idbindtoken token, status: 404",
  "stacktrace": "github.com/external-secrets/external-secrets/pkg/controllers/secretstore.reconcile\n\t/home/runner/work/external-secrets/external-secrets/pkg/controllers/secretstore/common.go:68\ngithub.com/external-secrets/external-secrets/pkg/controllers/secretstore.(*ClusterStoreReconciler).Reconcile\n\t/home/runner/work/external-secrets/external-secrets/pkg/controllers/secretstore/clustersecretstore_controller.go:63\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:118\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:314\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:265\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:226"
}

{
  "level": "error",
  "ts": 1695908232.6568358,
  "msg": "Reconciler error",
  "controller": "clustersecretstore",
  "controllerGroup": "external-secrets.io",
  "controllerKind": "ClusterSecretStore",
  "ClusterSecretStore": {
    "name": "gke-secrets-manager"
  },
  "namespace": "",
  "name": "gke-secrets-manager",
  "reconcileID": "36be48a2-d446-4d32-b51f-9cd4b184f29e",
  "error": "could not get provider client: failed to create GCP secretmanager client: unable to fetch identitybindingtoken: could not get idbindtoken token, status: 404",
  "stacktrace": "sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:324\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:265\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:226"
}
```

The only change in the values.yaml is at serviceAccount annotation level adding:
```
serviceAccount:
  annotations:
    iam.gke.io/gcp-service-account: gke-external-secrets@projectid.iam.gserviceaccount.com
```
And the ClusterSecretStore is the following:
```
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gke-secrets-manager
spec:
  provider:
    gcpsm:
      projectID: projectid
      auth:
        workloadIdentity:
          clusterLocation: europe-west1
          clusterName: clustername
          serviceAccountRef:
            name: external-secrets
            namespace: eso
```
Permissions in the serviceaccount are ok, because we tried with a single pod attaching the serviceaccount to it and we are able to see secrets.
