### ISSUE TITLE
Binary File Base64 Encoded Twice in Secret Created by ExternalSecret Using Kubernetes Provider

### ISSUE THREAD

**Issue by BenjaminNeale-Heritage** [external-secrets/external-secrets#2745]
**Describe the bug**
A secret created by the Kubernetes Provider containing a binary file base64 encodes the binary file twice.  This corrupts the Secret resource.

**To Reproduce**
External Secrets Operator: v0.9.5
Kubernetes: v1.24.15 (OpenShift 4.11.48)

1. Create Secret resource containing binary file.
```
kind: Secret
apiVersion: v1
metadata:
  name: secret-test-mobile-image
  namespace: eso
  labels:
    app.kubernetes.io/instance: eso-testing
data:
  mobile.png: >-
    iVBORw0KGgoAAAANSUhEUgAAAAsAAAARCAYAAAAL4VbbAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsQAAA7EAZUrDhsAAAASdEVYdFNvZnR3YXJlAEdyZWVuc2hvdF5VCAUAAAH6SURBVChTlZJLaFNhEIW//96bm5ePNotAbcEIrcEaQi0NWtRUi2LRiogiVaGCi+LSrSBS3EgpLgXJQtCFgiC4UUQkvhaltNQIFUxqNyE10k2CbZPc5++NuGrd5MBs5sycM8yM+LpQlI8zn3AciaIINsN1JaoquDaRRty6+UKapu0VKv/orXBdF13XEKcP3ZDiP4qbIT0HkYwelnVbULMEuirZKWuopoGj+/ltBzFMCAUhGAA1Eu6evJiweHR+nViwzrPe6xQnblNXwkyfyXHvrp9aXeXbdw3FdAQHOy2inSbHuzaoxgewu3uoxPs5lrLoOCBJ9Uks21Pu2BGb9NkGe5w13hZUsuUIlhEgPPuRSHUZx9B5+VpQKoEWchs8bRvhfvwyyvoM06EHXBh4zpNfAZxFl+1mBf1nCKn60YRtYyT6ILUf1xtpuCvD7pNBjtYUIlqFZNKkZGi8Wg6gSU3Dv5iD6D6U3AzZgkX7NovPWY/84cdxBe+W9L+bUmoiwJXqGwr5szxcneJO+RKx+QxTxXOoCZW1E+2Yu/wIBxTDsx7aK+jpDzDa61AbHILhFBuDR7h6qkF61GEk7WJaXnFTfnbFx+qKzvtSmLb8vGe/RHt+gQ9zPspfBHM5gU+jtQu29hutfJ0yNp7yuixMo4FtGVuimW/yY+Mp/gCIo/C/gQ0f/AAAAABJRU5ErkJggg==
type: Opaque
```

2. Create ExternalSecret using a Kubernetes provider to generate a new Secret.
```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: externalsecret-test-mobile-image
  namespace: eso
  labels:
    app.kubernetes.io/instance: eso-testing
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: secret-test-mobile-image
        property: mobile.png
      secretKey: mobile.png
  refreshInterval: 1m0s
  secretStoreRef:
    kind: SecretStore
    name: kubernetes
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    name: test-mobile-image
```

3. Note that the base64 text for the "mobile.png" field in the created Secret resource is the base64 encoding **of** the base64 field.
```
kind: Secret
apiVersion: v1
metadata:
  annotations:
    reconcile.external-secrets.io/data-hash: 0ae8628ec7ded5692cc411a482ea1a98
  resourceVersion: '984446141'
  name: test-mobile-image
  uid: b60de563-38e8-4eca-ae30-f244ffccee14
  creationTimestamp: '2023-09-29T06:08:11Z'
  namespace: eso
  ownerReferences:
    - apiVersion: external-secrets.io/v1beta1
      kind: ExternalSecret
      name: externalsecret-test-mobile-image
      uid: d47ac4db-afbc-4ec2-86ea-0db782345981
      controller: true
      blockOwnerDeletion: true
  labels:
    app.kubernetes.io/instance: eso-testing
    reconcile.external-secrets.io/created-by: 36033e3f2c9456665add2e84319d3a0f
immutable: false
data:
  mobile.png: >-
    aVZCT1J3MEtHZ29BQUFBTlNVaEVVZ0FBQUFzQUFBQVJDQVlBQUFBTDRWYmJBQUFBQVhOU1IwSUFyczRjNlFBQUFBUm5RVTFCQUFDeGp3djhZUVVBQUFBSmNFaFpjd0FBRHNRQUFBN0VBWlVyRGhzQUFBQVNkRVZZZEZOdlpuUjNZWEpsQUVkeVpXVnVjMmh2ZEY1VkNBVUFBQUg2U1VSQlZDaFRsWkpMYUZOaEVJVy8vOTZibTVlUE5vdEFiY0VJcmNFYVFpME5XdFJVaTJMUmlvZ2lWYUdDaStMU3JTQlMzRWdwTGdYSlF0Q0ZnaUM0VVVRa3ZoYWx0TlFJRlV4cU55RTEwazJDYlpQYzUrK051R3JkNU1CczVzeWNNOHlNK0xwUWxJOHpuM0FjaWFJSU5zTjFKYW9xdURhUlJ0eTYrVUthcHUwVkt2L29yWEJkRjEzWEVLY1AzWkRpUDRxYklUMEhrWXdlbG5WYlVMTUV1aXJaS1d1b3BvR2orL2x0QnpGTUNBVWhHQUExRXU2ZXZKaXdlSFIrblZpd3pyUGU2eFFuYmxOWHdreWZ5WEh2cnA5YVhlWGJkdzNGZEFRSE95MmluU2JIdXphb3hnZXd1M3VveFBzNWxyTG9PQ0JKOVVrczIxUHUyQkdiOU5rR2U1dzEzaFpVc3VVSWxoRWdQUHVSU0hVWng5QjUrVnBRS29FV2NoczhiUnZoZnZ3eXl2b00wNkVIWEJoNHpwTmZBWnhGbCsxbUJmMW5DS242MFlSdFl5VDZJTFVmMXh0cHVDdkQ3cE5CanRZVUlscUZaTktrWkdpOFdnNmdTVTNEdjVpRDZENlUzQXpaZ2tYN05vdlBXWS84NGNkeEJlK1c5TCtiVW1vaXdKWHFHd3I1c3p4Y25lSk8rUkt4K1F4VHhYT29DWlcxRSsyWXUvd0lCeFREc3g3YUsranBEekRhNjFBYkhJTGhGQnVEUjdoNnFrRjYxR0VrN1dKYVhuRlRmbmJGeCtxS3p2dFNtTGI4dkdlL1JIdCtnUTl6UHNwZkJITTVnVStqdFF1MjlodXRmSjB5TnA3eXVpeE1vNEZ0R1Z1aW1XL3lZK01wL2dDSW8vQy9nUTBmL0FBQUFBQkpSVTVFcmtKZ2dnPT0=
type: Opaque
```
```
$ echo aVZCT1J3MEtHZ29BQUFBTlNVaEVVZ0FBQUFzQUFBQVJDQVlBQUFBTDRWYmJBQUFBQVhOU1IwSUFyczRjNlFBQUFBUm5RVTFCQUFDeGp3djhZUVVBQUFBSmNFaFpjd0FBRHNRQUFBN0VBWlVyRGhzQUFBQVNkRVZZZEZOdlpuUjNZWEpsQUVkeVpXVnVjMmh2ZEY1VkNBVUFBQUg2U1VSQlZDaFRsWkpMYUZOaEVJVy8vOTZibTVlUE5vdEFiY0VJcmNFYVFpME5XdFJVaTJMUmlvZ2lWYUdDaStMU3JTQlMzRWdwTGdYSlF0Q0ZnaUM0VVVRa3ZoYWx0TlFJRlV4cU55RTEwazJDYlpQYzUrK051R3JkNU1CczVzeWNNOHlNK0xwUWxJOHpuM0FjaWFJSU5zTjFKYW9xdURhUlJ0eTYrVUthcHUwVkt2L29yWEJkRjEzWEVLY1AzWkRpUDRxYklUMEhrWXdlbG5WYlVMTUV1aXJaS1d1b3BvR2orL2x0QnpGTUNBVWhHQUExRXU2ZXZKaXdlSFIrblZpd3pyUGU2eFFuYmxOWHdreWZ5WEh2cnA5YVhlWGJkdzNGZEFRSE95MmluU2JIdXphb3hnZXd1M3VveFBzNWxyTG9PQ0JKOVVrczIxUHUyQkdiOU5rR2U1dzEzaFpVc3VVSWxoRWdQUHVSU0hVWng5QjUrVnBRS29FV2NoczhiUnZoZnZ3eXl2b00wNkVIWEJoNHpwTmZBWnhGbCsxbUJmMW5DS242MFlSdFl5VDZJTFVmMXh0cHVDdkQ3cE5CanRZVUlscUZaTktrWkdpOFdnNmdTVTNEdjVpRDZENlUzQXpaZ2tYN05vdlBXWS84NGNkeEJlK1c5TCtiVW1vaXdKWHFHd3I1c3p4Y25lSk8rUkt4K1F4VHhYT29DWlcxRSsyWXUvd0lCeFREc3g3YUsranBEekRhNjFBYkhJTGhGQnVEUjdoNnFrRjYxR0VrN1dKYVhuRlRmbmJGeCtxS3p2dFNtTGI4dkdlL1JIdCtnUTl6UHNwZkJITTVnVStqdFF1MjlodXRmSjB5TnA3eXVpeE1vNEZ0R1Z1aW1XL3lZK01wL2dDSW8vQy9nUTBmL0FBQUFBQkpSVTVFcmtKZ2dnPT0= | base64 -d

iVBORw0KGgoAAAANSUhEUgAAAAsAAAARCAYAAAAL4VbbAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsQAAA7EAZUrDhsAAAASdEVYdFNvZnR3YXJlAEdyZWVuc2hvdF5VCAUAAAH6SURBVChTlZJLaFNhEIW//96bm5ePNotAbcEIrcEaQi0NWtRUi2LRiogiVaGCi+LSrSBS3EgpLgXJQtCFgiC4UUQkvhaltNQIFUxqNyE10k2CbZPc5++NuGrd5MBs5sycM8yM+LpQlI8zn3AciaIINsN1JaoquDaRRty6+UKapu0VKv/orXBdF13XEKcP3ZDiP4qbIT0HkYwelnVbULMEuirZKWuopoGj+/ltBzFMCAUhGAA1Eu6evJiweHR+nViwzrPe6xQnblNXwkyfyXHvrp9aXeXbdw3FdAQHOy2inSbHuzaoxgewu3uoxPs5lrLoOCBJ9Uks21Pu2BGb9NkGe5w13hZUsuUIlhEgPPuRSHUZx9B5+VpQKoEWchs8bRvhfvwyyvoM06EHXBh4zpNfAZxFl+1mBf1nCKn60YRtYyT6ILUf1xtpuCvD7pNBjtYUIlqFZNKkZGi8Wg6gSU3Dv5iD6D6U3AzZgkX7NovPWY/84cdxBe+W9L+bUmoiwJXqGwr5szxcneJO+RKx+QxTxXOoCZW1E+2Yu/wIBxTDsx7aK+jpDzDa61AbHILhFBuDR7h6qkF61GEk7WJaXnFTfnbFx+qKzvtSmLb8vGe/RHt+gQ9zPspfBHM5gU+jtQu29hutfJ0yNp7yuixMo4FtGVuimW/yY+Mp/gCIo/C/gQ0f/AAAAABJRU5ErkJggg==
```

**Expected behavior**
The generated secret should contain the same contents as the original Secret resource.

**Additional context**
This may be a new issue introduced by https://github.com/external-secrets/external-secrets/pull/2681 which attempted to fix corruption of binary secrets by the Kubernetes provider.

**Comment by BenjaminNeale-Heritage** [comment]
The generated secret is valid if the 'decodingStrategy' is set to "Base64" (refer example ExternalResource below).  This behaviour in ESO v0.9.5 is different to ESO v0.8.1 and earlier which did not require "Base64" decoding strategy.  I do not know which is intended behaviour.  If ESO v0.9.5 is correct then I will update our ExternalSecret resources to use the "Base64" decoding strategy.  Please advise.

```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: externalsecret-test-mobile-image
  namespace: test-rfuel
  labels:
    app.kubernetes.io/instance: eso-testing
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: Base64
        key: secret-test-mobile-image
        property: mobile.png
      secretKey: mobile.png
  refreshInterval: 1m0s
  secretStoreRef:
    kind: SecretStore
    name: kubernetes
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    name: test-mobile-image
```
