### ISSUE TITLE
GCP - unable to fetch identitybindingtoken on ExternalSecret pod

### ISSUE THREAD

**Issue by Genesys05** [external-secrets/external-secrets#2752]
Hello,

**Describe the bug**
I try to use externalSecret to store secret on our cluster.

ExternalSecret pod show an error that i don't understand correctly:

```
{"level":"error","ts":1696450679.2299914,"msg":"Reconciler error","controller":"externalsecret","controllerGroup":"external-secrets.io","controllerKind":"ExternalSecret","ExternalSecret":{"name":"SECRET_NAME_IN_KUBERNETES","namespace":"external-secrets"},"namespace":"external-secrets","name":"SECRET_NAME_IN_KUBERNETES","reconcileID":"85d70f5b-92d1-44a7-b178-26c8cee1e292","error":"failed to create GCP secretmanager client: unable to fetch identitybindingtoken: could not get idbindtoken token, status: 404","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/controller/controller.go:227"}

{"level":"error","ts":1696450843.1249013,"logger":"controllers.ExternalSecret","msg":"could not get secret data from provider","ExternalSecret":{"name":"SECRET_NAME_IN_KUBERNETES","namespace":"external-secrets"},"error":"failed to create GCP secretmanager client: unable to fetch identitybindingtoken: could not get idbindtoken token, status: 404","stacktrace":"github.com/external-secrets/external-secrets/pkg/controllers/externalsecret.(*Reconciler).Reconcile\n\t/home/runner/work/external-secrets/external-secrets/pkg/controllers/externalsecret/externalsecret_controller.go:212\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/controller/controller.go:119\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/controller/controller.go:227"}

```

I have multiple resources:
- ClusterSecretStore
- ExternaSecret resource with reference of existing secret on GCP Secret Manager

Service Account:
I have One Service account defined on :
- ClusterSecretStore
- ExternalSecret pod "define in serviceAccount.name in chart" (I can see this service account on External Secret Pod)

**To know:** The status of the "ClusterSecretStore" resource is **valid**, Ready parameter is on **True** with event **"store validated"**.

Tested:
- I tested to create a pod with gcloud utils to test this service account in the same namespace and all is okay

Test to have SA token:
```
root@external-secret-test:/# curl -H "Metadata-Flavor: Google" http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token

{"access_token":"XXXXX","expires_in":60,"token_type":"Bearer"}
```

Test to retrieve one secret:

```
root@external-secret-test:/#  gcloud secrets versions access latest --secret="MY_SECRET"
I have the secret in answer
```

**To Reproduce**

- Create ClusterSecretStore

```
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-sm-backend
spec:
  provider:
    gcpsm:
      projectID: MY_PROJECT_ID
      auth:
        workloadIdentity:
          # name of the cluster region
          clusterLocation: MY_REGION
          # name of the GKE cluster
          clusterName: gcp-sm-backend
          # projectID of the cluster (if omitted defaults to spec.provider.gcpsm.projectID)
          clusterProjectID: MY_PROJECT_ID
          # reference the sa from above
          serviceAccountRef:
            name: SERVICE_ACCOUNT_NAME
```

- Create ExternalSecret

```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: SECRET_NAME_IN_KUBERNETES
  namespace: APPLICATION_NAMEPSACE
spec:
  refreshInterval: 1h                             # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-sm-backend               # name of the SecretStore (or kind specified)
  target:
    name: SECRET_NAME_IN_KUBERNETES                   # name of the k8s Secret to be created
    creationPolicy: Owner
  data:
  - secretKey: MY_SECRET
    remoteRef:
      key: MY_SECRET      # name of the GCPSM secret key
```

Service account rights:
- roles/secretmanager.secretAccessor

Service account binding:
- roles/iam.workloadIdentityUser on Workload identity[NAMESPACE/SA]

**Expected behavior**
Retrieve and sync my secret correctly.

Thank you for your help.

Regards,
Genesys
