### ISSUE TITLE
ClusterSecretStore with keepersecurity fail

### ISSUE THREAD

**Issue by sebdevaux** [external-secrets/external-secrets#2769]
**Describe the bug**
Error when we try to create a `ClusterSecretStore` with the provider `keepersecurity`
`admission webhook "validate.clustersecretstore.external-secrets.io" denied the request: missing: spec.provider.keepersecurity.auth`
Works well with a simple `SecretStore`

**To Reproduce**
1. provide all relevant manifests
Configure you keeper access:
```
apiVersion: v1
kind: Secret
metadata:
  name: ksm-config-secret
type: Opaque
data:
  ksm_config: "[REPLACE WITH YOUR BASE64 JSON string]"
```
Try to apply:
```
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: clustersecretstore
spec:
  provider:
    keepersecurity:
      authRef:
        name: ksm-config-secret
        key: ksm_config
      folderID: "ABCDEFG"
  conditions:
    - namespaces:
        - "test"
```
3. Kubernetes v1.26.3 and ESO helm-chart version 0.9.5

**Expected behavior**
In the documentation only these two fields are mandatory: `authRef` and `folderID`
