### ISSUE TITLE
Errors when deploying to Openshift 4.7

### ISSUE THREAD

**Issue by zeonin** [external-secrets/external-secrets#277]
While testing external-secrets in an Openshift 4.7 cluster using a Vault SecretStore , I received the following error on the controller:

```json
{"level":"error","ts":1626990715.585248,"logger":"controllers.ExternalSecret","msg":"could not reconcile ExternalSecret","ExternalSecret":"test-project/testing","SecretStore":"test-project/testing","error":"secrets \"testing\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/controller/controller.go:298\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/controller/controller.go:253\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/controller/controller.go:214"}
```

This was resolved by adding `externalsecrets/finalizers` to the `update`/`patch` list in the controller's ClusterRole:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: testing-external-secrets-controller

# ...

- apiGroups:
  - external-secrets.io
  resources:
  - externalsecrets
  - externalsecrets/status
  - externalsecrets/finalizers    # This line added
  verbs:
  - update
  - patch

# ...
```

---

Once that was fixed, I started getting a new error that seemed to relate to the ServiceAccount auth method for Vault:

```json
{"level":"error","ts":1626990862.068932,"logger":"controllers.ExternalSecret","msg":"could not get provider client","ExternalSecret":"test-project/testing","SecretStore":"test-project/testing","error":"cannot find secret data for key: \"token\"","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/controller/controller.go:298\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/controller/controller.go:253\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/controller/controller.go:214"}
```

This was resolved by regenerating the ServiceAccount until the SA's token secret was listed ahead of its Docker secret:

```yaml
# Good SA
apiVersion: v1
imagePullSecrets:
- name: vault-client-dockercfg-6c25d
kind: ServiceAccount
metadata:
  creationTimestamp: "2021-07-22T21:55:21Z"
  name: vault-client
  namespace: test-project
  resourceVersion: "14912275"
  selfLink: /api/v1/namespaces/test-project/serviceaccounts/vault-client
  uid: dcc2a7db-fbcc-471a-a5e7-288e01ebc6f0
secrets:
- name: vault-client-token-vk2ch
- name: vault-client-dockercfg-6c25d
```

compared to

```yaml
# Bad SA
apiVersion: v1
imagePullSecrets:
- name: vault-client-dockercfg-xjw7g
kind: ServiceAccount
metadata:
  creationTimestamp: "2021-07-22T20:49:19Z"
  name: vault-client
  namespace: test-project
  resourceVersion: "14893796"
  selfLink: /api/v1/namespaces/test-project/serviceaccounts/vault-client
  uid: c299cdd4-9c66-4030-be98-e83e2509aad2
secrets:
- name: vault-client-dockercfg-xjw7g
- name: vault-client-token-4v4q8
```

It seems that this operator assumes that the first listed Secret is always the ServiceAccount's token. In Openshift, this isn't always the case; the first Secret could also be a set of credentials for pulling from the built-in Openshift registry.

However, once the secret order was fixed, the rest of the operator worked excellently!

---

Tested config:

```yaml
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: testing
  namespace: test-project
spec:
  secretStoreRef:
    name: testing
    kind: SecretStore  # or ClusterSecretStore
  refreshInterval: "1h"
  target:
    name: testing
  data:
    - secretKey: testing
      remoteRef:
        key: "test/path"
        property: test-key
---
apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: testing
  namespace: test-project
spec:
  provider:
    vault:
      auth:
        kubernetes:
          mountPath: kubernetes/cluster01
          role: test-role
          serviceAccountRef:
            name: vault-client
            namespace: test-project
      path: secret
      server: $SERVER
      version: v2
``` 

Openshift version: 4.7.0-0.okd-2021-04-24-103438
Chart version: 0.2.3 (deployed via Argo - No values overrides used)
