### ISSUE TITLE
Enahnce Oralce Cloud Vault integration with Workload Identity

### ISSUE THREAD

**Issue by anders-swanson** [external-secrets/external-secrets#2771]
The existing Oracle Cloud Vault integration supports User Identity, and Instance Principal, but not [Workload Identity](https://blogs.oracle.com/cloud-infrastructure/post/oke-workload-identity-greater-control-access). This feature proposal is to add Workload Identity to the Oracle Cloud Vault integration.

**Comment by brokedba** [comment]
hi @anders-swanson  thank you for adding the Workload Identity integration  to the project .
I am trying to implement it in my OKE but the Oracle Vault section ( see [doc](https://external-secrets.io/latest/provider/oracle-vault/)) haven't really been updated after your PR. 
I only see the user principal steps but not those for Workload Identity. 
can we have that updated to reflect that case too?  I could help if needed  and once I understand the right syntax in the manifest.

- So far I only see  the below with serviceAccountRef:
```
---

apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: example-workload-identity
spec:
  provider:
    oracle:
      vault: # The vault OCID
      region: # The vault region
      principalType: Workload
---
``` 
- Do you confirm that the right WI definition should be rather as below ? 

```
---

apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: example-workload-identity
spec:
  provider:
    oracle:
      vault: # The vault OCID
      region: # The vault region
      principalType: Workload
      auth:
 #      jwt:
           serviceAccountRef:
             name: my-serviceaccount
```
 
Thank you !
