### ISSUE TITLE
Pass custom metadata into emitted event

### ISSUE THREAD

**Issue by andyren0110** [external-secrets/external-secrets#2775]
**Is your feature request related to a problem? Please describe.**
When a remote reference secret does not exist, it's hard to figure out which secret is missing. Upon taking a closer look at the issue, it seems that when external secret operator emits an event, the metadata passed to the external secret does not show up in the `involvedObject`.

For example 
```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: name-of-external-secret
  labels:
    env: dev
    secretKey: WRONG_SECRET
    service: name-of-service-using-the-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: our-secret-store
    kind: SecretStore
  target:
    name: name-of-secret
    creationPolicy: Owner
  data:
    - secretKey: WRONG_SECRET
      remoteRef:
        key: /path/to/ssm/secret/that/does/not/exist
```

You can see an example in the screen below of a logged event when a remote reference secret (In this case an SSM path) does not exist. The involvedObject does not contain the meta that ideally should be include to allow us to quickly locate the problematic secret.

<img width="357" alt="Screenshot 2023-10-10 at 10 24 12 AM" src="https://github.com/external-secrets/external-secrets/assets/97625402/fdbee8c0-aec8-4e3c-a749-7b68cfc675e9">

**Describe the solution you'd like**

Metadata passed to the external secret should be included in the emitted event.

**Describe alternatives you've considered**

We've worked around this by naming the secret as something like <env>-<service>-<name-of-external-secret>

**Additional context**

N/A
