### ISSUE TITLE
Map a function on secret name to transform them into "classic" environment variables case (upper snake case)

### ISSUE THREAD

**Issue by sonny-semc** [external-secrets/external-secrets#2780]
**Is your feature request related to a problem? Please describe.**

I have not been able to find a way to feed directly the secrets retrieved using a `find` with a regex, into a user-friendly format to serve as environment variables in my deployments. 
I am using Azure Key Vault as secret provider and secret must be named with alphanumerical characters and dashes only, eg. `database-password`. And that name won't load as an environment variables, so at least I need to replace dashes (-) by underscores (_). But I would like to be able to uppercase the name as well. 

**Describe the solution you'd like**
The best would be to be able to define that regex replacement something like:
```
  dataFrom:
  - find:
      name: 
        regexp: "^prod-"
    rewrite:
    - regexp:
        source: "prod-(.*)"
        target: "upper(replace($1, '-', '_'))"
```
But knowing it's purely based on regexp from golang it's unlikely.

So maybe something of the sort:
```
  dataFrom:
  - find:
      name: 
        regexp: "^prod-"
    rewrite:
    - regexp:
        source: "prod-(.*)"
        target: "$1"
    transform:
      map: "{{ .value | upper | replace '-' '_' }}"
```

**Describe alternatives you've considered**
My alternative as that stage are looking into alternatives to External Secrets itself.

**Additional context**
I may be wrong, and I may miss something, let me know if there's a way actually already to do what I am looking to do.

**Comment by moolen** [comment]
Hey :wave: This is a reasonable request! It seems that golang regexp doesn't support `\U` conversion tokens ([example here](https://regex101.com/r/8W4ppq/1)). 

```yaml
  dataFrom:
  - find:
      name: 
        regexp: "^prod-"
    rewrite:
    - regexp:
        source: "prod-(.*)"
        target: "$1"
      # note the indentation, this is part of a rewrite[] element.
      # rewrite operations occur in a predefined order: first regexp, then transform
      # transform applies to each individual secret key, not the value
      # regexp and transform are not exclusive, both can be defined.
      transform:
        template: "{{ .value | upper | replace '-' '_' }}"
```

It's probably best to add it here:
https://github.com/external-secrets/external-secrets/blob/f0ae0e81ee439877a29bb9f2d0014945c5c14277/pkg/utils/utils.go#L46-L53
