### ISSUE TITLE
Invalid Provider Config - ClusterSecretStore - Azure Workload Identity 401 - No Federated Identity

### ISSUE THREAD

**Issue by knechtionscoding** [external-secrets/external-secrets#2783]
**Describe the bug**
External-Secrets is receiving a 401 when configured to use workload identity in AKS. `AADSTS70021: No matching federated identity record found for presented assertion`

Status on the ClusterSecretStore:

```
  Warning  InvalidProviderConfig  20s (x6 over 101s)  cluster-secret-store  (combined from similar events): FromAssertion(): http call(https://login.microsoftonline.com/c90ea95b-aead-4931-b72e-f3e703fc342b/oauth2/v2.0/token)(POST) error: reply status code was 401:
{"error":"invalid_client","error_description":"AADSTS70021: No matching federated identity record found for presented assertion. Assertion Issuer: 'https://eastus.oic.prod-aks.azure.com/c90ea95b-aead-4931-b72e-f3e703fc342b/85ee619b-d637-4610-bacd-d4c64ff20348/'. Assertion Subject: 'system:serviceaccount:external-secrets:external-secrets'. Assertion Audience: 'api://AzureADTokenExchange'. https://docs.microsoft.com/en-us/azure/active-directory/develop/workload-identity-federation\r\nTrace ID: 72348f3f-7ab2-4ad1-a3e5-4fdc75f5ae00\r\nCorrelation ID: 21cae4b9-1c21-4751-bd19-5abac7dc93b6\r\nTimestamp: 2023-10-13 19:07:11Z","error_codes":[70021],"timestamp":"2023-10-13 19:07:11Z","trace_id":"72348f3f-7ab2-4ad1-a3e5-4fdc75f5ae00","correlation_id":"21cae4b9-1c21-4751-bd19-5abac7dc93b6","error_uri":"https://login.microsoftonline.com/error?code=70021"}
```

<details><summary>Exact Error</summary>

```json
{
  "level": "error",
  "ts": 1697222622.299803,
  "logger": "controllers.ClusterSecretStore",
  "msg": "unable to validate store",
  "clustersecretstore": {
    "name": "cloud-provider"
  },
  "error": "could not get provider client: FromAssertion(): http call(https://login.microsoftonline.com/c90ea95b-aead-4931-b72e-f3e703fc342b/oauth2/v2.0/token)(POST) error: reply status code was 401:\n{\"error\":\"invalid_client\",\"error_description\":\"AADSTS70021: No matching federated identity record found for presented assertion. Assertion Issuer: 'https://eastus.oic.prod-aks.azure.com/c90ea95b-aead-4931-b72e-f3e703fc342b/85ee619b-d637-4610-bacd-d4c64ff20348/'. Assertion Subject: 'system:serviceaccount:external-secrets:external-secrets'. Assertion Audience: 'api://AzureADTokenExchange'. https://docs.microsoft.com/en-us/azure/active-directory/develop/workload-identity-federation\\r\\nTrace ID: 82c5ba04-83d8-4598-b435-d1e32dee3000\\r\\nCorrelation ID: a267529c-67c1-477b-bdca-6a2e841b2061\\r\\nTimestamp: 2023-10-13 18:43:42Z\",\"error_codes\":[70021],\"timestamp\":\"2023-10-13 18:43:42Z\",\"trace_id\":\"82c5ba04-83d8-4598-b435-d1e32dee3000\",\"correlation_id\":\"a267529c-67c1-477b-bdca-6a2e841b2061\",\"error_uri\":\"https://login.microsoftonline.com/error?code=70021\"}",
  "stacktrace": "github.com/external-secrets/external-secrets/pkg/controllers/secretstore.reconcile\n\t/home/runner/work/external-secrets/external-secrets/pkg/controllers/secretstore/common.go:68\ngithub.com/external-secrets/external-secrets/pkg/controllers/secretstore.(*ClusterStoreReconciler).Reconcile\n\t/home/runner/work/external-secrets/external-secrets/pkg/controllers/secretstore/clustersecretstore_controller.go:64\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/controller/controller.go:119\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/controller/controller.go:227"
}
```

</details>

<details><summary>Service Account has the correct values:</summary>

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: 085dc855-61d1-43ce-a869-7c80bad7f810
    azure.workload.identity/tenant-id: c90ea95b-aead-4931-b72e-f3e703fc342b
  labels:
    app.kubernetes.io/instance: external-secrets
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/version: v0.9.5
    helm.sh/chart: external-secrets-0.9.5
  name: external-secrets
  namespace: external-secrets
```

</details>

<details><summary>Pod has correct values filled in via the webhook and correct labels:</summary>

```yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    app.kubernetes.io/instance: external-secrets
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/version: v0.9.5
    azure.workload.identity/use: "true"
    helm.sh/chart: external-secrets-0.9.5
    pod-template-hash: 6db9594bc7
  name: external-secrets-6db9594bc7-d7j9m
  namespace: external-secrets
spec:
  automountServiceAccountToken: true
  containers:
  - args:
    - --concurrent=1
    env:
    - name: AZURE_CLIENT_ID
      value: 085dc855-61d1-43ce-a869-7c80bad7f810
    - name: AZURE_TENANT_ID
      value: c90ea95b-aead-4931-b72e-f3e703fc342b
    - name: AZURE_FEDERATED_TOKEN_FILE
      value: /var/run/secrets/azure/tokens/azure-identity-token
    - name: AZURE_AUTHORITY_HOST
      value: https://login.microsoftonline.com/
    image: ghcr.io/external-secrets/external-secrets:v0.9.5
    imagePullPolicy: IfNotPresent
    name: external-secrets
...
    volumeMounts:
...
    - mountPath: /var/run/secrets/azure/tokens
      name: azure-identity-token
      readOnly: true
  serviceAccount: external-secrets
  serviceAccountName: external-secrets
  volumes:
...
  - name: kube-api-access-mmbmf
...
  - name: azure-identity-token
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          audience: api://AzureADTokenExchange
          expirationSeconds: 3600
          path: azure-identity-token
```

</details>

<details><summary>Federated Identities URL Match</summary>

```json
[
  {
    "audiences": [
      "api://AzureADTokenExchange"
    ],
    "id": "/subscriptions/c51b5261-e706-4f79-850e-ec0d2514512d/resourcegroups/SaaS-East/providers/Microsoft.ManagedIdentity/userAssignedIdentities/production-us-east-external-secrets-identity/federatedIdentityCredentials/production-us-east-external-secrets-identity",
    "issuer": "https://eastus.oic.prod-aks.azure.com/c90ea95b-aead-4931-b72e-f3e703fc342b/85ee619b-d637-4610-bacd-d4c64ff20348/",
    "name": "production-us-east-external-secrets-identity",
    "resourceGroup": "SaaS-East",
    "subject": "system:serviceaccount:external-secrets:external-secrets",
    "systemData": null,
    "type": "Microsoft.ManagedIdentity/userAssignedIdentities/federatedIdentityCredentials"
  },
  {
    "audiences": [
      "api://AzureADTokenExchange"
    ],
    "id": "/subscriptions/c51b5261-e706-4f79-850e-ec0d2514512d/resourcegroups/SaaS-East/providers/Microsoft.ManagedIdentity/userAssignedIdentities/production-us-east-external-secrets-identity/federatedIdentityCredentials/production-us-east-external-secrets-identity-certs",
    "issuer": "https://eastus.oic.prod-aks.azure.com/c90ea95b-aead-4931-b72e-f3e703fc342b/85ee619b-d637-4610-bacd-d4c64ff20348/",
    "name": "production-us-east-external-secrets-identity-certs",
    "resourceGroup": "SaaS-East",
    "subject": "system:serviceaccount:external-secrets:external-secrets-cert-controller",
    "systemData": null,
    "type": "Microsoft.ManagedIdentity/userAssignedIdentities/federatedIdentityCredentials"
  },
  {
    "audiences": [
      "api://AzureADTokenExchange"
    ],
    "id": "/subscriptions/c51b5261-e706-4f79-850e-ec0d2514512d/resourcegroups/SaaS-East/providers/Microsoft.ManagedIdentity/userAssignedIdentities/production-us-east-external-secrets-identity/federatedIdentityCredentials/production-us-east-external-secrets-identity-webhook",
    "issuer": "https://eastus.oic.prod-aks.azure.com/c90ea95b-aead-4931-b72e-f3e703fc342b/85ee619b-d637-4610-bacd-d4c64ff20348/",
    "name": "production-us-east-external-secrets-identity-webhook",
    "resourceGroup": "SaaS-East",
    "subject": "system:serviceaccount:external-secrets:external-secrets-webhook",
    "systemData": null,
    "type": "Microsoft.ManagedIdentity/userAssignedIdentities/federatedIdentityCredentials"
  }
]
```
</details>

ClusterSecretStore Yaml:

```
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: cloud-provider
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      environmentType: PublicCloud
      serviceAccountRef:
        name: external-secrets
        namespace: external-secrets
      vaultUrl: https://saas-east.vault.azure.net/
```

**To Reproduce**
1. provide all relevant manifests
2. provide the Kubernetes and ESO version

1. K8s 1.25
2. ESO 0.9.5

**Expected behavior**

ClusterSecretStore to auth and allow for secrets to be pulled

**Screenshots**

**Additional context**

https://azure.github.io/azure-workload-identity/docs/troubleshooting.html#aadsts70021-no-matching-federated-identity-record-found-for-presented-assertion Not helpful, confirmed the URL are the same.

Read all of: https://external-secrets.io/main/provider/azure-key-vault/ didn't get any helpful pointers to what might be going wrong.

https://external-secrets.io/v0.9.5/api/clustersecretstore/ doesn't list azure, but I pulled the spec to figure out what might be going wrong. Nothing super helpful.

I know that workload identity works for the AKS cluster because I have it properly working for external-dns. I've confirmed all the values are the same (minus identity name) for both and I can't figure out why this external-secrets can't get a token.

I've tried both:
- [MOUNTED SERVICE ACCOUNT](https://external-secrets.io/v0.9.5/provider/azure-key-vault/#mounted-service-account)
- [REFERENCED SERVICE ACCOUNT](https://external-secrets.io/v0.9.5/provider/azure-key-vault/#referenced-service-account)
