### ISSUE TITLE
refreshInterval is not respected with a combination of ExternalSecret and VaultDynamicSecret

### ISSUE THREAD

**Issue by vtorikianupgrade** [external-secrets/external-secrets#2812]
**Describe the bug**
`ExternalSecret` refreshInterval is not respected when using a `VaultDynamicSecret` as generator. For example, for a `refreshInterval` of `20m`, we transiently get a "skipped" refresh. Which means our secret is only refreshed on the next `refreshInterval` so 40 minutes after the previous successful one.

No events are registered on the `ExternalSecret` when the skip happens, and no logs are emitted by the controller.
We do see an increase on the `externalsecret_sync_calls_total{name="test"}` metrics counter at every `refreshInterval` though.

**To Reproduce**
Create a `VaultDynamicSecret` to issue certs from Vault's PKI
Create an associated `ExternalSecret` with a `refreshInterval`. 

Example manifests:
```yaml
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test
spec:
  refreshInterval: 20m
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: VaultDynamicSecret
        name: generator
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: VaultDynamicSecret
metadata:
  name: generator
spec:
  path: pki/main/issue/foo
  method: POST
  parameters:
    common_name: foo
    ttl: 30m
  provider: <redacted>
```

ESO Version: 0.9.7
Kube Version: v1.27.4-eks-2d98532

**Expected behavior**
A new certificate should be issued and stored into the `Secret` for each `refreshInterval` that elapse. 

**Screenshots**
N/A

**Additional context**
We generate certificates with short TTL and use `ExternalSecret` to refresh them before expiration.
