### ISSUE TITLE
Add regexp support for fake provider

### ISSUE THREAD

**Issue by joudaon** [external-secrets/external-secrets#2835]
**Is your feature request related to a problem? Please describe.**

I am trying to use regexp to find keys but it is not compatible with Fake Provider.

Example:

```
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: css-fake
spec:
  provider:
    fake:
      data:
      - key: "nginx-dev-var1"
        value: "hello from nginx-dev-var1"
        version: "v1"
      - key: "nginx-dev-var2"
        value: "hello from nginx-dev-var2"
        version: "v1"
      - key: "nginx-pre-var1"
        value: "hello from nginx-pre-var1"
        version: "v1"
      - key: "/nginx/dev/var3"
        value: "hello from nginx-dev-var3"
        version: "v1"
```
```
apiVersion: external-secrets.io/v1beta1 
kind: ExternalSecret
metadata:
  name: es-nginx
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: css-fake
    kind: ClusterSecretStore
  target:
    name: s-nginx
  dataFrom:
  - find:
      name:
        regexp: nginx-dev
```

I am getting this error:

> could not get secret data from provider. GetAllSecrets not implemented.

**Describe the solution you'd like**

This should retrieve data from Fake provider keys. In this case:
- nginx-dev-var1
- nginx-dev-var2

**Describe alternatives you've considered**

**Additional context**
