### ISSUE TITLE
Deleting keys from external secret doesn't remove them from K8S secret

### ISSUE THREAD

**Issue by vasil166** [external-secrets/external-secrets#2838]
**Describe the bug**
We are using external secrets operator with GCP secret manager. Whenever we delete a key from the external secret it doesn't get removed from the K8S secret.

**To Reproduce**

- Create the following external secret

```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
  labels:
    argocd.argoproj.io/instance: app-test
  name: app-test-config
  namespace: test

spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: KEY1
      metadataPolicy: None
    secretKey: KEY1
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: KEY2
      metadataPolicy: None
    secretKey: KEY2
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: KEY3
      metadataPolicy: None
    secretKey: KEY3
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-store
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    name: app-test-config
    template:
      data:
        KEY1: value1
        KEY2: value2
        KEY3: value3
      engineVersion: v2
      mergePolicy: Replace
```

- Remove KEY2 from the external secret
- KEY2 doesn't get removed from the K8S secret
- There are no issues when updating keys or adding new keys

**Expected behavior**
Whenever a key is removed from the external secret, it's expected for it to be removed from the K8S secret

**Additional context**

- external secrets operator v0.9.8
- kubernetes 1.24

**Comment by moolen** [comment]
Can you post the actual contents of the template block?
I don't really see why you would need a template block here at all.
If you define a key in that template block i expect there always will be the same key in the resulting secret.

**Comment by vasil166** [comment]
Here is how the template block looks like.
```
target:
    creationPolicy: Owner
    deletionPolicy: Delete
    name: app-test-config
    template:
      data:
        SMTP_HOST: email-smtp.us-east-1.amazonaws.com
        SMTP_PORT: "587"
        SMTP_USER: '{{ .SMTP_USER  | toString }}'
	SMTP_PASSWORD: '{{ .SMTP_PASSWORD  | toString }}'
      engineVersion: v2
      mergePolicy: Replace
```

We need that template because some values are passed in plain text and only the sensitive data is fetched from GCP secrets

**Comment by shuheiktgw** [comment]
Hmm, let me take a look...

**Comment by shuheiktgw** [comment]
I tried to reproduce the problem but could not make it. I've used the K8s provider instead of GCP, but I don't believe that affects the final output. There may be something more to reproduce it.

```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: k8s-store
  data:
  - secretKey: key1
    remoteRef:
      key: test
      property: key1
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    name: k8s
    template:
      data:
        KEY1: value1
      engineVersion: v2
      mergePolicy: Replace
```
