### ISSUE TITLE
When providing an empty "data", component status should reconcile to something

### ISSUE THREAD

**Issue by patrickdappollonio** [external-secrets/external-secrets#2874]
**Describe the bug**
I have the following situation:

* Teams on self serve want to create a new app, without any secrets (yet)
* They self-serve a bootstrap process that sets up auth against an ExternalSecret backend
* We create for them a SecretStore pointing at this backend, and an empty ExternalSecret (since they have no secrets yet)
* The process fails because an empty ExternalSecret does not yield component statuses so applications like `k9s` or ArgoCD can't understand the resource is "synced".

**To Reproduce**

* Version: latest
* Kubernetes version: latest

To reproduce, I'm using the following fake YAML:

```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hello
  namespace: default
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: example-sync
  data: []
```

**Expected behavior**

What I'm hoping to see is that the application reconciles an empty secret inside the `componentStatuses` of the `ExternalSecret` itself, since [tools like ArgoCD rely on this field to know if it's up-to-date](https://github.com/argoproj/argo-cd/blob/master/resource_customizations/external-secrets.io/ExternalSecret/health.lua).

In short, an event telling me that `ExternalSecret` ran and there's nothing to do but to call the secret "updated" since there's no data to store.

**Screenshots**

What's actually happening is that tools like `k9s` cannot report the status because there isn't one:

![image](https://github.com/external-secrets/external-secrets/assets/930925/695e38df-9a6b-476f-9f31-9d8dec2b4c2b)

And ArgoCD, for example, waits forever and considers the deployment as "forever progressing":

![image](https://github.com/external-secrets/external-secrets/assets/930925/49fce462-6fb6-4d3e-9f9c-27a0ee57cc0c)

**Additional context**

I realize the quickest solution is to simply not generate an `ExternalSecret` in the first place if no data is being consumed. However, for bootstrapping purposes, and via GitOps, you get the value-added behaviour that whenever the secret synchronizes, it will also check if the credentials of the `SecretStore` are correct (and the message propagates correctly). There's value to be shown if the `ExternalSecret` is empty, yet still using a `SecretStore` and validating the credentials are correct: you get feedback faster out of the box, not just *whenever you're ready to add secrets*.

With the help of @gusfcarvalho, we tried a few options, like passing an empty template (or one with a dummy value):

```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hello
  namespace: default
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: example-sync
    template:
      engineVersion: v2
      data: {}
  data: []
```

But he mentioned the issue might be due to the fact "there's no Job on either data or dataFrom [...] so we basically skip reconciling [...] The best should be we reconcile with empty data". [Slack thread](https://kubernetes.slack.com/archives/C017BF84G2Y/p1699901854705809).

I've also tried *not setting a `spec`* but that breaks ExternalSecret with a panic-crash (although I don't think this needs fix, maybe?):

![image](https://github.com/external-secrets/external-secrets/assets/930925/11ec0986-3027-46a5-93d3-5e97c0543aa5)

Happy to answer any questions!
