### ISSUE TITLE
[docs] Why are CRDs installed via an extra GitRepository Kustomization?

### ISSUE THREAD

**Issue by smittnacht** [external-secrets/external-secrets#2876]
Hi,
your installation [guide](https://external-secrets.io/v0.9.8/examples/gitops-using-fluxcd/#deploy-the-crds) describes the installation of the CRDs via an extra GitRepository Kustomization. Is there a reason why the CRDs cannot be installed directly via the Helm chart? If so, what is the reason?

**Comment by smittnacht** [comment]
@gusfcarvalho thank you for the quick reply, actually I was not aware that `dependsOn` is limited to resources of same kind. With that in mind your approach makes totally sense, although you could also wrap the CR and the CRDs+Helm into two Kustomizations.

example:

```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: external-secrets-base
  namespace: flux-system
spec:
  interval: 5m
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./infrastructure/external-secrets/base
  wait: true
  timeout: 2m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: external-secrets-secret-stores
  namespace: flux-system
spec:
  interval: 5m
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./infrastructure/external-secrets/secret-stores
  wait: true
  timeout: 2m
  dependsOn: 
    - name: external-secrets-base
```
