### ISSUE TITLE
secretKey is triggering finding from GitHub Advanced Security and KICS scanning

### ISSUE THREAD

**Issue by RobCannon** [external-secrets/external-secrets#2880]
**Is your feature request related to a problem? Please describe.**
The field `secretKey` is triggering a security finding from both GitHub Advanced Security and KICS scanning.

![image](https://github.com/external-secrets/external-secrets/assets/189862/5cc46989-21f0-402d-b588-7b67cb773a6b)

Also, see:
https://docs.kics.io/latest/secrets/#entropies

**Describe the solution you'd like**
If the field were named `secretKeyName`, it would not trigger these alerts.  I would like to change the field name.

I understand that you just can't change the field name without breaking everyone use the operator, but it would be great if there were an alias for the field name where you could use either field name.  I don't think you can specify an alias for a CRD field name, but you could introduce a new field named `secretKeyName` and then use the value of whichever field is specified (with preference to `secretKeyName`).  You could then schedule a deprecation of `secretKey` if you want to fully transition to the new name.

**Comment by gusfcarvalho** [comment]
hi @RobCannon ! I'm pinging the other maintainers here, but I'm pretty sure this would go to our `wont-do` list 😅 - we already have way too many users to change our stable-ish APIs now.

@moolen @Skarlso @knelasevero @shuheiktgw @sebagomez @IdanAdar  FYI.

**Comment by Skarlso** [comment]
Hi.

Is there a reason you can't use an `allowRules`? Changing the whole API would be incredibly painful for existing users indeed. If we ever would to change it, I would use `secretKeyValue` as the `Name` is misleading to be a reference rather than an actual value. But even that doesn't really give it enough credit. It's the KEY in the secret that is being pushed. :) There is literally no better name for it. :D

**Comment by RobCannon** [comment]
My thought is that if you are already triggering vulnerability warnings in two different products, there are probably more that would flag this as a problem.  As a user, I now have to create exceptions in two different products and I don't even think there is a way to create exceptions in GitHub Advanced Security.

I don't understand why this would be named secretKeyValue instead of secretKeyName.  I am talking about secretKey in this structure.

```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: database-user
spec:
  secretStoreRef:
    kind: SecretStore
    name: secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: database-user
  data:
    - secretKey: userName
      remoteRef:
        key: database-user
        property: userName
    - secretKey: password
      remoteRef:
        key: database-user
        property: password
```

That value is used to generate the key name when the secret is created, not the value;

```
apiVersion: v1
kind: Secret
metadata:
  name: database-user
data:
  userName: some-user
  password: super-secret
```

**Comment by Skarlso** [comment]
```yaml
  - secretKey: userName
...
```
```yaml
data:
  userName: some-user
  password: super-secret
```

Right. So you see it ended up as a key in a key value map. :) Hence the name SecretKey. :)

Regardless, even if we do a deprecation notice, the key will remain there for several months. :)

**Comment by RobCannon** [comment]
It doesn't even need to be deprecated.  Just having two names for the same value would be enough to resolve this issue.

**Comment by Skarlso** [comment]
How... would that resolve it? 🤔 It would still be part of the API and of the things it requires.

**Comment by RobCannon** [comment]
The scanning is done on source code.  If my source looks like this (changing secretKey to secretKeyName), it does not trigger a finding in either KICS or GitHub Advanced Security.

```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: database-user
spec:
  secretStoreRef:
    kind: SecretStore
    name: secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: database-user
  data:
    - secretKeyName: userName
      remoteRef:
        key: database-user
        property: userName
    - secretKeyName: password
      remoteRef:
        key: database-user
        property: password
```

**Comment by Skarlso** [comment]
Oh you mean the output? Sorry, for some reason I was under the impression it's in OUR source code. :D My apologies.

Okay, so... Could you please describe how this is working where it is running and why is your generated yaml in source code? Is it a Gitops repository?

**Comment by RobCannon** [comment]
This is a GitOps repository.  We use ArgoCD for managing our k8s deployments and everything is stored in GitHub (typically as Helm charts).  As part of the PR process, we scan pull requests with KICS.  GitHub Advanced Secuirty is also looking for secrets in the code (but it does not replace much of what KICS does).

Ironically, we are using ExternalSecrets so developers will not try to store secrets in source code, but it is getting flagged as secret based on that attribute name.

**Comment by Skarlso** [comment]
Interesting. Okay, so this pr of mine: https://github.com/external-secrets/external-secrets/pull/2862 will make that key optional. Once that is rolled out, we can add in an alias which we can then internally resolve to secretKey.

After than, maybe we can start to migrate to using secretKeyName and maybe deprecate it. But that's gonna take _some_ time.

**Comment by RobCannon** [comment]
Thank you!

**Comment by Skarlso** [comment]
@gusfcarvalho Does that sounds reasonable?

**Comment by gusfcarvalho** [comment]
my only problem with that is that 'secretKey' does not match that regular expression, and probably is only caught due to entropy configuration. How are we sure that 'secretKeyName' will not get caught, or if this would persist if the entropy is increased by an arbirary value? I don't want to set the expectation that, if the entropy engine changes, we are going to change from 'scretKeyName' to 'anotherWordSoThatEntropyIsLowAndUnrelatedToCeKrets'

(or maybe I'm way too weak on regex these days)

**Comment by gusfcarvalho** [comment]
I understand to go over false alerts is PITA, but I find it hard to envision a project which would comply to all security tooling out there 😞. As I personally don't really see the benefit to fix this for KICKS (and break it for KOCKS or any other tool out there), I'm still in favor to not implement it 😅 

But that's why we have many maintainers , and maybe this problem  generally affects the community instead of a specific use case😄

  @moolen  @knelasevero @sebagomez  @IdanAdar  thoughts?

**Comment by gusfcarvalho** [comment]
(last comment, if we do it, maybe we want to have something like this, as it would solve  some issues with new users figuring out what's `secretKey`, `remoteRef.Key`, and prepare ourselves if we decide to implement the community ask to support multiple Secrets on a single ES)
```
data:
- localRef:
     key: foo #old secretKey
   remoteRef: 
     key: bar # remoteRef.key as it is today  
```
