### ISSUE TITLE
Rewrite to remove common path doesn't work as documented

### ISSUE THREAD

**Issue by ndemeshchenko** [external-secrets/external-secrets#2886]
**Describe the bug**
I have number of parameters in AWS parameter store. e.g
```
/aaa/eks/param1
/aaa/eks/param2
``` 

In mu externalsecret I'm using dataFrom.find

```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pltfrmxxx
spec:
  dataFrom:
  - find:
      conversionStrategy: Default
      decodingStrategy: Auto
      name:
        regexp: eks
      path: "/aaa/"
    rewrite:
    - regexp: 
        source: "/aaa/eks/(.*)"
        target: "$1"
  target:
    name: pltfrmxxx
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: parameterstore
```

External-secrets fails with the following error
```
Secret \"pltfrmxxx\" is invalid: data[]: Invalid value: \"\": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+')**
```

If I apply the same but without rewrite, it works with resulting secret's keys have `_` instead of `/` (which is expected)
But I don't get how to remove this common path `/aaa/eks`

**Comment by gusfcarvalho** [comment]
this error shows that the capture group didn't match anything t all! Can you try providing a bigger capture group and see if this bit on the error message changes?
This is the bit that should have some content
```
Invalid value: \"\":
```

**Comment by ndemeshchenko** [comment]
tried that with `(.*)` however that failing with exactly the same error:
```
"error":"Secret \"pltfrmxxx\" is invalid: data[]: Invalid value: \"\": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+')","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:227"}
```

FYI, if I just a have an externalsecret resource without `rewrite` it works just fine and resulting secret looks like 
```
apiVersion: v1
data:
  _aaaa_eks_param1: blahblah==
  _aaaa_eks_param2: blahblah==
...
immutable: false
kind: Secret
```

**Comment by visla-xugeng** [comment]
@gusfcarvalho any update on this case? I had exactly same issue here, failed to remove the common path. 
```
_abc_eso_username
_abc_eso_password
```
In my external secret yaml file, I tried to rewrite and failed

```
dataFrom:
    - find:
        name: 
          regexp: "/abc/(.*)$"
    - rewrite:
        regexp:
          source: "/abc/(.*)$"
          target: "$1"
```
