### ISSUE TITLE
deprecation notice on find (azure keyvault), but suggestion doesn't seem to work

### ISSUE THREAD

**Issue by joaocc** [external-secrets/external-secrets#2887]
**Describe the bug**
When  trying to fetch all secrets from a azure keyvault using find, we get the following error message (but it works)
```
{"level":"debug","ts":1700259703.815523,"logger":"events","msg":"dataFrom[0].find.conversionStrategy=Default is deprecated and will be removed in further releases. Use dataFrom.rewrite instead","type":"Warning","object":{"kind":"ExternalSecret","namespace":"external-secrets","name":"akv-source","uid":"00000000-0000-0000-0000-111111111111","apiVersion":"external-secrets.io/v1beta1"},"reason":"ParameterDeprecated"}
```
However, when replacing the "find:" with "rewrite:" the synchronization doesn't work.

**To Reproduce**

EKS 1.27, external-secrets v0.9.8

works but generates deprecation notice
```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: akv-get--all
  namespace: external-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akv--store
  dataFrom:
    - find: 
        name:
          regexp: ".*"
```

this new dataFrom doesn't work - ExternalSecret doesn't even get any informational state
```
...
  dataFrom:
    - rewrite: 
        - regexp:
            source: "(.*)"
            target: "$1"
```

**Expected behavior**
rewrite should work

**Comment by joaocc** [comment]
Enabling debug, the following is shown...
Any hints would be very welcomed...
```
{
        "level": "info",
        "msg": "Warning: Reconciler returned both a non-zero result and a non-nil error. The result will always be ignored if the error is non-nil and the non-nil error causes reqeueuing with exponential backoff. For more details, see: https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/reconcile#Reconciler",
        "controller": "externalsecret",
        "controllerGroup": "external-secrets.io",
        "controllerKind": "ExternalSecret",
        "ExternalSecret": {
            "name": "akv-get--all",
            "namespace": "external-secrets"
        },
        "namespace": "external-secrets",
        "name": "akv-get--all",
        "reconcileID": "1be53474-7973-5aaf-9882-6576ba5ebc7e"
    },
    {
        "level": "error",
        "msg": "Reconciler error",
        "controller": "externalsecret",
        "controllerGroup": "external-secrets.io",
        "controllerKind": "ExternalSecret",
        "ExternalSecret": {
            "name": "akv-get--all",
            "namespace": "external-secrets"
        },
        "namespace": "external-secrets",
        "name": "akv-get--all",
        "reconcileID": "a3e327cb-2828-59ea-b5b0-d1c1897a956d",
        "error": "secrets \"akv-get--all\" not found",
        "stacktrace": "sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:227"
    }
```

**Comment by gusfcarvalho** [comment]
You need to set them both up, like this:

```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: akv-get--all
  namespace: external-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akv--store
  dataFrom:
    - find: 
        name:
          regexp: ".*"
      rewrite: 
        - regexp:
            source: "(.*)"
            target: "$1"
```
