### ISSUE TITLE
1Password provider does not work with ClusterSecretStore

### ISSUE THREAD

**Issue by GraysonCAdams** [external-secrets/external-secrets#2892]
**Describe the bug**
When following instructions, if I try to switch a SecretStore to an ExternalSecretStore with 1Password as the provider, the change is rejected. The error produces no results on Google.

**To Reproduce**
1. Create a YAML resource as follows:
```
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: secretstore
spec:
  provider:
    onepassword:
      connectHost: http://onepassword-connect.1password:8080
      vaults:
        myvaultname: 1
      auth:
        secretRef:
          connectTokenSecretRef:
            name: onepassword-connect-token-staging
            key: token
```
2. provide the Kubernetes and ESO version
```
Client Version: v1.28.4
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.7+k3s2
ESO: 0.9.9
```

**Expected behavior**
Allow the ExternalSecretStore to be created, as the documentation suggests is possible for 1Password.

**Screenshots**

**Additional context**
```
$ kubectl apply -f no-upload/1password.yaml --namespace 1password
secret/onepassword-connect-token-staging created
Error from server (Forbidden): error when creating "1password.yaml": admission webhook "validate.clustersecretstore.external-secrets.io" denied the request: received invalid 1Password SecretStore resource: cluster scope requires namespace
```
