### ISSUE TITLE
External Secret show status as SecretSynced but there is NO Kubernetes Secret.

### ISSUE THREAD

**Issue by sbmtn** [external-secrets/external-secrets#2895]
**Describe the bug**
This issue started happening since we installed the ESO in our clusters on 23rd of October. For most of the External Secret manifests applied, we can get the External Secret created and successfully synced along with the Kubernetes Secret in the same namespace that it should be managing. But for some External Secrets, the External Secret is created and shows the status as SecretSynced, even the external-secret pod logs infer the same (no errors or any red flags) but there's Kubernetes secret in the same namespace (or even in any namespace) that it should've been creating or syncing.

**Expected behavior**
When applying the same manifest on cluster, we should be able to see an External Secret resource with status as SecretSynced and a Kubernetes Secret in the same namespace with data store in Hashicorp Vault.

**Additional context**
Weird thing is that if we change the name for Kubernetes Secret that the External Secret should be managing then, same manifest will create the External Secret as well as the Kubernetes Secret. So, when we encountered this issue during October, we thought the issue might be the character limit on Kubernetes Secret for us, so changing the Kubernetes name worked for us then. BUT now, the same issue is happening with already deployed External Secrets. The same External Secret that was showing status as SecretSynced and the Kubernetes Secret can also be seen, the same Kubernetes Secrets are now missing but the External Secrets look fine with status as SecretSynced. This is causing in failing deployments, which is not bearable if it happens on live servers.

Issue is similar to
https://github.com/external-secrets/external-secrets/issues/2894

**Comment by gusfcarvalho** [comment]
Hi @sbmtn ! Can you please share your manifests and which ExternalSecret version are you running on?

**Comment by sbmtn** [comment]
@gusfcarvalho I don't think external-secret manifests will be any helpful as I mentioned earlier that the exact same manifest worked fine when we just changed the kubernetes secret name from target.name field in external secret manifest.

**Versions:**
External secrets chart version: `v0.9.3`

**Comment by Skarlso** [comment]
Then it's especially important to see the manifest. :) Since without knowing what you're trying to do and how, it's really difficult to figure out what's wrong. :)

**Comment by gusfcarvalho** [comment]
Manifests are important, as from the related issue you even pointed out, it was a configuration issue. I believe this will likely to be the same cause, as we have end to end tests that verify secrets indeed exist when setting both with target names or without them.

since we do have this coverage, if we do have a bug on ESO, it is something we can only investigate with the manifests at hand. 

You can redact any sensitive information, though! We don’t need to have the right store names or anything like that.

**Comment by sbmtn** [comment]
@gusfcarvalho @Skarlso here's the sample manifest for our external-secret which did result in the same issue discussed above but, after trying everything like removing external secret, creating k8s secret first then the external secret, etc. when we changed the value for `target.name`, we were able to see the k8s secret with changed name.

```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cluster-test.test.myapp.com
  namespace: argocd
spec:
  data:
  - remoteRef:
      key: my-platform/data/argocd/cluster-test.test.myapp.com
      property: name
    secretKey: name
  - remoteRef:
      key: my-platform/data/argocd/cluster-test.test.myapp.com
      property: server
    secretKey: server
  - remoteRef:
      key: my-platform/data/argocd/cluster-test.test.myapp.com
      property: config
    secretKey: config
  refreshInterval: 15s
  secretStoreRef:
    kind: ClusterSecretStore
    name: external-secrets-operator-vault-cluster-secret-store
  target:
    creationPolicy: Owner
    name: cluster-test.test.myapp.com
    template:
      metadata:
        annotations: null
        labels:
          argocd.argoproj.io/secret-type: cluster
```

**Additional Info:**
We faced this issue twice - once in October when we were deploying ESO on our cluster and second time was recently identified with the external-secrets that were already deployed and running successfully (i.e. we had the external secret and the k8s secret both, also the deployments were working fine) but now the deployments are failing and the error is that the k8s secret cannot be found be when we check the external secret that should be managing these k8s secrets. They're deployed and show status as SecretSynced but no K8s secret.
