### ISSUE TITLE
PushSecret generator integration

### ISSUE THREAD

**Issue by moolen** [external-secrets/external-secrets#2897]
See design proposal #2665

We want `Kind=PushSecret` to be able to directly reference Generator resources.

```
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
spec:
  selector:
    generatorRef:
      apiVersion: generators.external-secrets.io/v1alpha1
      kind: Password
      name: "my-password"
``` 

### Acceptance criteria

- [ ] tests: controller tests for this new field should be sufficient
- [ ] the API changes need to be documented
    - [ ] API/CRD spec inline documentation
    - [ ] PushSecret API documentation
    - [ ] Guides section for `PushSecret` + `generator` functionality
