### ISSUE TITLE
Feature Request: Support Wildcards in Namespace Restrictions for ClusterSecretStore

### ISSUE THREAD

**Issue by shokada** [external-secrets/external-secrets#2907]
**Is your feature request related to a problem? Please describe.**
We are using the Hierarchical Namespace Controller (HNC) in our cluster, which allows development teams to create child namespaces freely under a parent namespace managed by our SRE team. We want to enable these child namespaces to reference `ClusterSecretStore` resources without having to label each namespace explicitly, as developers can freely label their own namespaces.

**Describe the solution you'd like**
I would like to propose a feature that allows the use of wildcards or a more flexible namespace selection mechanism in the `namespaces` field of the `ClusterSecretStore` resource. This would enable us to specify a pattern that matches a group of namespaces, rather than listing each namespace individually or relying on labels which developers can change.

For example, it could look something like this:

```yaml
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: example-clustersecretstore
spec:
  # ... other spec fields ...
  conditions:
    namespaces:
      - "dev-*"
      - "test-*"
```

**Describe alternatives you've considered**
We have considered using namespaceSelector, but since developers can add labels to namespaces, it is not a viable option for us. We also looked into manually updating the namespaces list, but this is not practical due to the dynamic nature of our namespace creation.

**Additional context**
Allowing wildcards for namespace restrictions would greatly simplify the management of access to ClusterSecretStore resources in clusters where namespaces are dynamically created and managed, especially when using hierarchical namespace strategies like HNC.

Thank you for considering this feature request.
