### ISSUE TITLE
Validate `.data[].secretKey` duplicates

### ISSUE THREAD

**Issue by Dgadavin** [external-secrets/external-secrets#2921]
**Describe the bug**
I have same `secretKey` `SERVICE_NAME` but point to diferenet parameters in AWS Parameter Store. I see that operator take the last one in YAML and inject into the secret. So in my example into `test` secret I will go `SERVICE_NAME` from ` /dev/project_env_vars` Parameter instead of `/dev/shared_env_vars` Parameter. 

**To Reproduce**
I have such Externalsecret
```yaml
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: test
  namespace: default
spec:
  secretStoreRef:
    name: ssm-secret-store-global
    kind: ClusterSecretStore
  refreshInterval: "3m"
  target:
    name: test-env
    creationPolicy: 'Owner'
  data:
    - secretKey: SERVICE_NAME
      remoteRef:
        key: /dev/shared_env_vars
        property: TEST_URL
    - secretKey: KAFKA_BROKER_0
      remoteRef:
        key: /dev/shared_env_vars
        property: KAFKA_BROKER_0
    - secretKey: KAFKA_BROKER_1
      remoteRef:
        key: /dev/shared_env_vars
        property: KAFKA_BROKER_1
    - secretKey: KAFKA_BROKER_2
      remoteRef:
        key: /dev/shared_env_vars
        property: KAFKA_BROKER_2
    - secretKey: SERVICE_NAME
      remoteRef:
        key: /dev/project_env_vars
        property: SERVICE_NAME
```

**Expected behavior**
Error. I want to see some kind of duplication error. This is not transperent behaviour because you can inject wrong parameter.

Operator version: **0.9.3**
