### ISSUE TITLE
Support of Human readable name for Yandex Lockbox provider

### ISSUE THREAD

**Issue by kvmenshikov** [external-secrets/external-secrets#2932]
**Is your feature request related to a problem? Please describe.**
I'm using ESO with Yandex Lockbox and have to specify ID of Lockbox for every external secret, for example:
```
kind: ExternalSecret
spec:
  data:
  - remoteRef:
      key: fc3jfe590ugdiao6mon2 <--- HERE
      property: kubeconfig
```
Name of Yandex Lockbox is same for multiple environments but ID is different. So I have to put specific Lockbox ID in environment configuration in Helm charts, it required extra efforts and increase probability of mistakes. I've checked documentation for AWS, Azure and GCP and all providers support human readable name of secrets.

**Describe the solution you'd like**
Yandex lockbox provider should support human readable name of Lockbox, for example:
```
kind: ExternalSecret
spec:
  data:
  - remoteRef:
      key: lockbox-with-kubeconfigs <--- HERE
      property: kubeconfig
```

**Describe alternatives you've considered**
N/A

**Additional context**
N/A
