### ISSUE TITLE
Support dataFrom for google secret manager

### ISSUE THREAD

**Issue by mjcc30** [external-secrets/external-secrets#2933]
**Is your feature request related to a problem? Please describe.**
I'm encountering an issue when attempting to create a secret with dataFrom in an external-secrets setup with Google Secret Manager. Specifically, I'm unable to create a secret environment variable to use with envFrom in a deployment.

**Describe the solution you'd like**
I would like support for the dataFrom feature to be added for Google Secret Manager. This enhancement would allow me to seamlessly integrate secrets stored in Google Secret Manager into my deployments using the envFrom configuration.

**Describe alternatives you've considered**
I've explored various alternatives like volumes, but none seem to provide a straightforward solution. Implementing support for dataFrom with Google Secret Manager would streamline the process and enhance the overall usability of the external-secrets functionality.

**Additional context**
```
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-store
spec:
  provider:
    gcpsm:
      projectID: gcp-project-id
      auth:
        workloadIdentity:
          clusterLocation: us-west1
          clusterName: cluster-test
          serviceAccountRef:
            name: kube-service-account
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: gcp-store
    kind: ClusterSecretStore
  target:
    name: app-secret
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: app-secret
 ---
apiVersion: v1
kind: Pod
metadata:
  name: app-pod
spec:
  containers:
    - name: app
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "env" ]
      envFrom:
      - secretRef:
          name: app-secret
```

**Comment by mjcc30** [comment]
hello @gusfcarvalho, sorry for the delay, yes its gcp-store for SecretStoreRef 
but the problem is when i create a secret in the google secret manager
example
NODE_ENV=dev
i got this problem:
Warning  UpdateFailed  2s (x7 over 13s)   external-secrets  unable to unmarshal secret: invalid character 'N' looking for beginning of value

**Comment by gusfcarvalho** [comment]
That's because dataFrom expects values to be json formatted.

```
{"NODE_ENV":"dev"}
```
should work

**Comment by hsulipe** [comment]
Hi @gusfcarvalho, 

I'm also am using the Google Secret Manager provider. But my issue is related to empty secrets. Or secrets with destroyed versions.

If I create a secret in GSM with a empty json payload like. Or if latest version of GSM secret is destroyed(but previous versions are enabled)

```
{}
```

ESO will not be able to extract that secret and will fail sync not creating any secrets. With the following message. How can I extract that to a empty k8s secret instead of crashing? 

```
    Message:             could not get secret data from provider                                                                  │
    Reason:                SecretSyncedError
```

Here is my external secret CRD

```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
    force-sync: 2024-01-31 12:01:34.227016753 +0000 UTC m=+0.264132497
  labels:
    app:service
  name: service
  namespace: default
spec:
  dataFrom:
  - extract:
      conversionStrategy: Default
      decodingStrategy: None
      key: onboarding
      metadataPolicy: None
  refreshInterval: "0"
  secretStoreRef:
    kind: SecretStore
    name: secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: secrets
status:
  conditions:
  - lastTransitionTime: "2024-01-31T10:58:07Z"
    message: could not get secret data from provider
    reason: SecretSyncedError
    status: "False"
    type: Ready
```
