### ISSUE TITLE
[AWS] Support the new EKS Pod Identity Agent

### ISSUE THREAD

**Issue by corrieriluca** [external-secrets/external-secrets#2951]
## Description of the bug

External Secrets v0.9.9 installed in EKS does not work with the new [EKS Pod Identity Agent](https://docs.aws.amazon.com/eks/latest/userguide/pod-identities.html) feature (alternative to IRSA).

EKS Pod Identity Agent injects the `AWS_CONTAINER_CREDENTIALS_FULL_URI: http://169.254.170.23/v1/credentials` environment variable in the pod, but ESO logs the following error (probably from the AWS SDK):

```
2023/12/13 09:44:17 Ignoring, HTTP credential provider invalid endpoint host, "169.254.170.23", only loopback hosts are allowed. <nil>
```

And thus cannot validate and make ready SecretStores that leverage AWS Secrets Manager.

## To Reproduce

1. On an EKS cluster, version 1.28 
1. Install the EKS Pod Identity Addon on EKS
   `aws eks create-addon --cluster-name my-cluster --addon-name eks-pod-identity-agent --addon-version v1.0.0-eksbuild.1`
2. Create an IAM role for External Secrets with the following policy and trust relationship:
```json
{
    "Statement": [
        {
            "Action": [
                "secretsmanager:GetResourcePolicy",
                "secretsmanager:GetSecretValue",
                "secretsmanager:DescribeSecret",
                "secretsmanager:ListSecretVersionIds"
            ],
            "Effect": "Allow",
            "Resource": [
                "*"
            ]
        }
    ],
    "Version": "2012-10-17"
}
```
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "AllowEksAuthToAssumeRoleForPodIdentity",
            "Effect": "Allow",
            "Principal": {
                "Service": "pods.eks.amazonaws.com"
            },
            "Action": [
                "sts:AssumeRole",
                "sts:TagSession"
            ]
        }
    ]
}
```
3. Create a pod identity association
     `aws eks create-pod-identity-association --cluster-name my-cluster --role-arn arn:aws:iam::111122223333:role/my-role --namespace external-secrets --service-account external-secrets`
4. Install ESO with Helm, version 0.9.9 on EKS 1.28, specifying these values:
```yaml
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::111122223333:role/my-role
  name: external-secrets
```
5. Create a ClusterSecretStore (or SecretStore)
```yaml
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: secret-store
spec:
  provider:
    aws:
      region: eu-west-3 # or another region
      service: SecretsManager
```

## Expected behavior

The ClusterSecretStore should be ready and valid when I run `kubectl get clustersecretstore`

```
NAME           AGE   STATUS   CAPABILITIES   READY
secret-store   1m    Valid    ReadWrite      True
```

## Additional outputs/screenshots

The describe output of the external-secrets pod, with the env variables injected by the Pod Identity Agent:

```
Containers:
  external-secrets:
    Container ID:    containerd://8047ff645c41068b5715ccfe0d9f8d77b4b46fae27d24a0c26680b2bb2170ca7
    Image:           ghcr.io/external-secrets/external-secrets:v0.9.9
    Image ID:        ghcr.io/external-secrets/external-secrets@sha256:88d34938c949af80498b87cdbf6fcedf1d10a80190ff126adfcd9db964bfdf65
    Port:            8080/TCP
    Host Port:       0/TCP
    SeccompProfile:  RuntimeDefault
    Args:
      --concurrent=1
    State:          Running
      Started:      Wed, 13 Dec 2023 10:43:01 +0100
    Ready:          True
    Restart Count:  0
    Limits:
      memory:  256Mi
    Requests:
      cpu:     10m
      memory:  32Mi
    Environment:
      AWS_STS_REGIONAL_ENDPOINTS:              regional
      AWS_DEFAULT_REGION:                      eu-west-3
      AWS_REGION:                              eu-west-3
      AWS_CONTAINER_CREDENTIALS_FULL_URI:      http://169.254.170.23/v1/credentials
      AWS_CONTAINER_AUTHORIZATION_TOKEN_FILE:  /var/run/secrets/pods.eks.amazonaws.com/serviceaccount/eks-pod-identity-token
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-z6t6f (ro)
      /var/run/secrets/pods.eks.amazonaws.com/serviceaccount from eks-pod-identity-token (ro)
```

The output of `kubectl get clustersecretstores`:

```
NAME           AGE   STATUS             CAPABILITIES   READY
secret-store   11m   ValidationFailed                  False
```

## Additional context / potential solution

**A [fix has been introduced](https://github.com/aws/aws-sdk-go/pull/4961) in [AWS SDK Go v1.47.11](https://github.com/aws/aws-sdk-go/releases/tag/v1.47.11).**

ESO v0.9.9 uses AWS SDK v1.47.3 so **this explains why the bug is present**.

This should be fixed with the **next stable release of ESO will be available** since AWS SDK has been [updated on the main branch](https://github.com/external-secrets/external-secrets/blob/main/go.mod#L20).

**Comment by moolen** [comment]
0.9.10 has been released, can someone confirm this is working now? :pray:

**Comment by danieljamesscott** [comment]
I am getting the following error with 0.9.10:
```
Warning  InvalidProviderConfig  1s (x11 over 7s)  secret-store  unable to create session: an IAM role must be associated with service account myservice-secrets (namespace: myservice)
```

I have double checked, and there is definitely a pod identity association between the service account and the IAM role. Is there a validation somewhere which requires the annotation to be present?

**Comment by moolen** [comment]
I found some time to dig the AWS docs.

:warning: We can not use the `serviceAccountRef` based authentication mechanisms on a `(Cluster)SecretStore`.

I.e. the following snippet **will not work when using EKS Pod Identity**.
Why? The `serviceAccountRef` uses `aws.AssumeRoleWithWebIdentity()` to exchange a Kubernetes service account token  with AWS creds.

EKS Pod Identity uses a link-local address `169.254.170.23` or defined via env var `AWS_CONTAINER_CREDENTIALS_FULL_URI`  to acquire credentials by talking to the EKS Pod Identity Agent.
That agent verifies the source ip address and the service account in use.

ESO can not impersonate other service accounts. 

```yaml
# this can not work with EKS Pod Identity
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secretstore-sample
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-central-1
      auth:
        jwt:
          serviceAccountRef:
            name: my-serviceaccount
```
docs: https://external-secrets.io/latest/provider/aws-secrets-manager/#eks-service-account-credentials

:bulb: Instead, one must use the ESO service account to acquire short-lived credentials through the agent.
In order to apply the principal of least privilege one can specify a `role` in the SecretStore spec to assume a role with the initial credentials. That assumed role then must have the least privilege principle applied. 

To prevent users from specifying any role in the SecretStore one must use a policy engine such as kyverno or Gatekeeper/OPA. More on that on the [Security Best Practices](https://external-secrets.io/latest/guides/security-best-practices/#policy-engine-best-practices) docs.

```yaml
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: team-b-store
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-central-1
      # do a sts:assumeRole before fetching secrets
      role: team-b
```

I think @corrieriluca shared an example of using EKS Pod Identity that  should work with the recent update.

@danieljamesscott can you share your SecretStore? From the error message i think you're using a `serviceAccountRef` which will not work with the reasons described above.

I think this information :point_up_2:  is valuable for people struggling with this, this should end up in the docs [in this section here](https://github.com/external-secrets/external-secrets/blob/main/docs/snippets/provider-aws-access.md) eventually. I would really appreciate it if someone could open a PR :pray:

**Comment by gdasson** [comment]
I'd like to work in it, I also enabled Vault Provider AWS IAM auth and thus, I am somewhat familiar with the code. Could you please assign it to me? @moolen 

Thx.

**Comment by danieljamesscott** [comment]
> @danieljamesscott can you share your SecretStore? From the error message i think you're using a serviceAccountRef which will not work with the reasons described above.

Yes, I am using `serviceAccountRef`. Are you saying that this won't work because the pod has already assumed the role using the identity association, and can't then assume another role?

I'm unsure how the alternative solution works. Does it do a "double assume"? i.e. The eso pod runs with a service account + iam role which is then permitted to `sts:AssumeRole` into another iam role?

Would it be possible to have eso start another pod, with the correct namespace and name to match the identity association and allow the role authentication?

**Comment by moolen** [comment]
> Are you saying that this won't work because the pod has already assumed the role using the identity association, and can't then assume another role?


You can use `serviceAccountRef` only with IRSA, not Pod Identity. That's because the Pod Identity agent verifies the identity of the caller (ESO) and hence it can not impersonate a different service account.

> I'm unsure how the alternative solution works. Does it do a "double assume"? i.e. The eso pod runs with a service account + iam role which is then permitted to sts:AssumeRole into another iam role?

We're first creating a session using default credentials (EKS Pod Identity, if configured). Then with that IAM Role that is attached to that pod identity we can do a `sts:AssumeRole` call to jump to another role which has the required permissions.


> Would it be possible to have eso start another pod, with the correct namespace and name to match the identity association and allow the role authentication?

Technically this is possible, but i don't think this is a good idea. This comes with a lot of limitations and just feels like a very bad workaround :thinking:

**Comment by danieljamesscott** [comment]
> We're first creating a session using default credentials (EKS Pod Identity, if configured). Then with that IAM Role that is attached to that pod identity we can do a `sts:AssumeRole` call to jump to another role which has the required permissions.

Got it. Thanks.

**Comment by wdonne** [comment]
If the `secretAccountRef` in the secret store would refer to the service account of the ESO, would that work?

**Comment by danieljamesscott** [comment]
Possibly, but isn't the point that each SecretStore can use a different service account (with its own IAM role), so that it can be scoped with least privilege? ESO works differently from the "usual" pattern where pods run with a single service account which maps to a single role. The ESO service account needs to jump to another role to fetch secrets.

**Comment by wdonne** [comment]
Indeed, it would only be a workaround for a cluster secret store.

**Comment by bmgeek** [comment]
will there be support a eks pod identity in the future?

**Comment by moolen** [comment]
> will there be support a eks pod identity in the future?

It is supported, however only the `serviceAccountRef`-based authentication can not be supported due to the limitations of EKS Pod Identity. Everything else is still possible.
With that being said, this is solely a documentation issue. I guess it would also be great to have e2e test coverage for AWS EKS Pod Identity based authentication. I'll open a separate issue for that.

**Comment by bmgeek** [comment]
Mb I do something wrong, I have error
`an IAM role must be associated with service account`.

**Comment by dowlingw** [comment]
In my current work, I am using a [managed SecretStore per Namespace](https://external-secrets.io/latest/guides/multi-tenancy/#managed-secretstore-per-namespace) approach to multi-tenancy, where a compatible solution for using EKS Pod Identity would drastically simplify our lives vs IRSA (infra as code complexity for adding multiple trust policies to the roles.

I'm reaching out to our AWS account management team to understand whether there's anything on the public roadmap to allow cluster operators to configure impersonation in the EKS Addon, and will share that here if I hear back - though suspect this is very unlikely.

**Comment by pdeva** [comment]
folks, i am stumbling into the issue in this thread regarding pod identity. its unclear from this thread what the solution is. this is my current yaml which is throwing an error since switching to pod identity. what should it be changed to, to make it work?

```yaml
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-sm
  namespace: external-secrets
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-astradot
            namespace: external-secrets

```

**Comment by takebozu** [comment]
@pdeva I also tried using EKS Pod Identity and would like to share my successful procedure.

The service account name is `external-secrets`, if you've installed ESO as described in Getting started like this:

```
helm install external-secrets \
   external-secrets/external-secrets \
    -n external-secrets \
    --create-namespace
```

Then create an appropriate role and associate it to the service account with:

```
aws eks create-pod-identity-association --cluster-name my-cluster \
  --role-arn arn:aws:iam::111122223333:role/my-role \
  --namespace external-secrets \
  --service-account external-secrets
```

And your manifest shouldn't have `auth` section. It should be:

```
kind: ClusterSecretStore
metadata:
  name: aws-sm
  namespace: external-secrets
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
```

This works fine for me.

If you want to use your own service account name such as `external-secrets-astradot`, supplying `--set serviceAccount.name=external-secrets-astradot` on helm install may do that.

**Comment by Smana** [comment]
Hey I have the same issue, even by following the steps described by @pdeva 

my association has been created
```console
aws eks describe-pod-identity-association --cluster-name mycluster-0 --association-id a-9n44rhfah0x0jnybz |jq
{
  "association": {
    "clusterName": "mycluster-0",
    "namespace": "security",
    "serviceAccount": "external-secrets",
    "roleArn": "arn:aws:iam::396740644681:role/xplane-external-secrets-mycluster-0",
    "associationArn": "arn:aws:eks:eu-west-3:xxx:podidentityassociation/mycluster-0/a-9n44rhfah0x0jnybz",
    "associationId": "a-9n44rhfah0x0jnybz",
    "tags": {
      "crossplane-providerconfig": "default",
      "crossplane-kind": "podidentityassociation.eks.aws.upbound.io",
      "crossplane-name": "xplane-external-secrets-mycluster-0-brp5f-rg8ps"
    },
    "createdAt": "2024-02-20T18:36:43.903000+01:00",
    "modifiedAt": "2024-02-20T18:36:43.903000+01:00"
  }
}
```

My ClusterSecretStore:
```yaml
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  labels:
    kustomize.toolkit.fluxcd.io/name: security
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: clustersecretstore
spec:
  provider:
    aws:
      region: eu-west-3
      service: SecretsManager
  refreshInterval: 0
```

Using an ephemeral container, I'm able to read secrets, so I suppose something is missing on ESO side.
```console
kubectl debug -n "${NS}" --copy-to="${POD_NAME}" -it "${TARGET_POD}" -it --image=${DEBUG_IMG} -- /bin/bash

⬢ [Docker] ❯ aws secretsmanager get-secret-value --secret-id security/vault/vault-snapshot
{
    "ARN": "arn:aws:secretsmanager:eu-west-3:396740644681:secret:security/vault/vault-snapshot-DDI4np",
    "Name": "security/vault/vault-snapshot",
    <REDACTED>
    "CreatedDate": "2024-01-24T20:15:09.244000+00:00"
}
```

For information this is part of a work in progress in order to build a Crossplane Composition [here](https://github.com/Smana/demo-cloud-native-ref/pull/137).

Thanks for your help

**Comment by Smana** [comment]
Nevermind, it seems to be working after a few minutes. That's strange and I'll let you know if I find the cause

**Comment by bmgeek** [comment]
Yeah, all works! Great, Thank all )

**Comment by diego7marques** [comment]
I've tested the scenario proposed by @moolen to ensure the concept of least privileges and it worked as expected. If anyone is struggling with it, here are the terraform I used to create the roles and policies.

**External Secrets role with no policy associated besides the assume role policy:**
```HCL
resource "aws_iam_role" "eso_role" {
  name = "eso-role"
  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Action = [
        "sts:AssumeRole",
        "sts:TagSession"
      ]
      Effect = "Allow"
      Principal = {
        Service = [
	    "pods.eks.amazonaws.com"
	]
      }
    }]
  })
}
```

**Workload policy with the permissions to read the secrets from AWS Secrets Manager and permissions to be assumed only by the ESO role:**
```HCL
resource "aws_iam_role" "workload01_eso_role" {
  name = "workload01-eso-role"
  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Action = [
        "sts:AssumeRole",
        "sts:TagSession"
      ]
      Effect = "Allow"
      Principal = {
        AWS = aws_iam_role.eso_role.arn
      }
    }]
  })
}

## Create the policy document with the required actions over the secret created in the last step
## Ref: https://external-secrets.io/v0.9.13/provider/aws-secrets-manager/
data "aws_iam_policy_document" "eso_policy" {
    statement {
      sid = "eso"
      effect = "Allow"
      actions = [
        "secretsmanager:GetResourcePolicy",
        "secretsmanager:GetSecretValue",
        "secretsmanager:DescribeSecret",
        "secretsmanager:ListSecretVersionIds"
      ]
      resources = [
        <AWS_SECRETS_MANAGER_ARN>
      ]
    }

    statement {
      sid = "allowListSecrets"
      effect = "Allow"
      actions = [ 
        "secretsmanager:ListSecrets"
      ]
      resources = [
        "*"
      ]
    }
}

## Create the IAM policy with the document created above
resource "aws_iam_policy" "eso_policy" {
  name        = "eso-policy"
  description = "Policy for ExternalSecretsOperator read content from SecretsManager of workload01"
  policy      = data.aws_iam_policy_document.eso_policy.json
}

## Associate the policy with the workload-eso-role
resource "aws_iam_role_policy_attachment" "attach" {
  role       = aws_iam_role.workload01_eso_role.name
  policy_arn = aws_iam_policy.eso_policy.arn
}

```

**Associate the ESO role with the external secrets service account**

```HCL
## Ref: https://github.com/external-secrets/external-secrets/issues/2951#issuecomment-1866943943
resource "aws_eks_pod_identity_association" "role_association" {
  cluster_name    = "eks-lab-cluster"
  namespace       = "external-secrets"
  service_account = "external-secrets"
  role_arn        = aws_iam_role.eso_role.arn
}
```

**Set the role workload role in the SecretStore**

```YAML
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: containscloud-lab-store
  namespace: workload01
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      # Role that will be assumed by the opertaor to access the secret
      # Update the AWS account id with yours
      role: arn:aws:iam::000011112222:role/workload01-eso-role
```

There is also a full lab available in: https://containscloud.com/2024/03/24/integrating-aws-secrets-manager-to-eks-using-external-secrets/

Any questions, let me know. Hope it helps.

**Comment by moolen** [comment]
Not stale, still need to add a section to the docs to point out the limitations of ESO and EKS Pod Identity. Previous comments and blog articles can be linked. Thanks everyone for contributing :bow:

**Comment by tgmatt** [comment]
> I've tested the scenario proposed by @moolen to ensure the concept of least privileges and it worked as expected. If anyone is struggling with it, here are the terraform I used to create the roles and policies.
> ... snip ...

This doesn't make sense - you've entrusted the ESO role to assume the workload role, but you haven't given the workload role permission to assume any other roles. I can't see how this has ever worked.

**Comment by cromega** [comment]
@diego7marques so the namespace sort of doesn't matter? (you put "external-secrets" in the identity binding but "workload01" in the SecretStore. I still don't see how things hang together.

**Comment by diego7marques** [comment]
> @diego7marques so the namespace sort of doesn't matter? (you put "external-secrets" in the identity binding but "workload01" in the SecretStore. I still don't see how things hang together.

The namespace of `aws_eks_pod_identity_association` terraform resource must match only the namespace you are going to install the operator in. If you look at my post, it matches the namespace used later on `helm install` command:

`helm install external-secrets external-secrets/external-secrets -n external-secrets --create-namespace`

The `ExternalSecrets` and `SecretStore` resources don't need to be in the same namespace as the operator and must be running in the same namespace as the pod (unless you are using `ClusterStoreStore`).

**Comment by maven2016** [comment]
@diego7marques i tried to make it work cross account but i get the following error:
`AccessDeniedException: User: arn:aws:sts::<account id>:assumed-role/<role-name> is not authorized to perform: secretsmanager:GetSecretValue on resource: <secret-name> because no identity-based policy allows the secretsmanager:GetSecretValue action status code: 400`

I tried both approaches: assume role and resource based policy:
https://itarunkumar.medium.com/securely-access-aws-secrets-manager-across-different-aws-accounts-3b0821f4e2e1)
It didn't work.

From this post i see its possible to make it work with OIDC:
https://stackoverflow.com/questions/77068202/external-secret-error-accessdeniedexception-for-cross-aws-account-secret-manager

But is it possible with Pod Identity?

**Comment by joshbench** [comment]
Has anyone had any luck moving from IRSA to Pod Identity with the Vault Provider IAM Auth? It seems like it uses separate IAM authentication code than the AWS provider: https://github.com/external-secrets/external-secrets/blob/main/pkg/provider/vault/auth_iam.go

I'm currently getting this error:
```
cluster-secret-store  expected env variable: AWS_WEB_IDENTITY_TOKEN_FILE not found on controller's pod
```

With the following ClusterSecretStore spec:
```
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      auth:
        iam:
          path: vaultauthpath
          region: <region>
          role: arn:aws:iam::<account>:role/<role>
          vaultAwsIamServerID: serverid
          vaultRole: vaultrole
      path: vaultpath
      server: https://vault-server-address
```

**Comment by yb-yu** [comment]
I am currently successfully granting AWS Secrets Manager permissions to External Secrets using Pod Identity. 

I am using v0.9.20.

If Pod Identity and corresponding IAM roles are correctly configured, the following secret store manifest are sufficient.

```
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: secretsmanager
spec:
  provider:
    aws:
      region: us-east-1
      service: SecretsManager
```
