### ISSUE TITLE
allow creation of additional manifests in values file

### ISSUE THREAD

**Issue by H777K** [external-secrets/external-secrets#2961]
**Is your feature request related to a problem? Please describe.**
I am currently trying to deploy external-secrets with FluxCD and the corresponding `helmrelease` custom resource. However, I have the problem that I have to deploy the `ClusterSecretStore` custom resource in addition to the helm chart.

I have already read your documentation [GitOps using FluxCD (v2)](https://github.com/external-secrets/external-secrets/blob/main/docs/examples/gitops-using-fluxcd.md) in which the problem of the independently resource management between `kustomization` and `helmrelease` custom resources is explained. The solution described therein could solve my problem, but this would be problematic because the CRDs are currently deployed via the helm chart. That's why i was looking for a simpler solution.

**Describe the solution you'd like**
My suggestion is that additional manifests can be defined in `values.yaml`. This way they are part of the helm chart and helm takes care of the installation order.

**Example:**

**values.yaml**
```
# array of extraManifests
extraManifests:
- apiVersion: external-secrets.io/v1beta1
  kind: ClusterSecretStore
  metadata:
    name: vault-backend
  spec:
    provider:
      vault:
        server: "https://my-vault-server.com"
        namespace: "vault-namespace"
        ...
```

**templates/extra-manifests.yaml**
```
{{ range .Values.extraManifests }}
---
{{ tpl (toYaml .) $ }}
{{ end }}
```

I have also found this approach in other helm charts such as [grafana](https://github.com/grafana/helm-charts/tree/main/charts/grafana).

To be honest it feels a bit strange to define manifests in the `values.yaml`, but it is a good way to solve my problem quite easily.

**Describe alternatives you've considered**
An alternative approach is already described in your [GitOps using FluxCD (v2)](https://github.com/external-secrets/external-secrets/blob/main/docs/examples/gitops-using-fluxcd.md) documentation.
