### ISSUE TITLE
HA setup for ESO in case of zone unavailability (IBM Secret Manager)

### ISSUE THREAD

**Issue by fdberlking** [external-secrets/external-secrets#2964]
**Is your feature request related to a problem? Please describe.**

I want to setup ESO together with **IBM Secret Manager** in a production env. Therefore,I also need to consider DR & HA for my setup. However, when I use either a ClusterSecretStore or SecretStore CRD for my solution, there's not the option yet to configure an internal failover to another instance in case all HA zones inside a region are down, so we still have secrets being available whilst the primary instance is down. 

```
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secret-store-name
  namespace: some-namespace
spec:
 
# which contains the secret exactly one provider must be configured  
provider:
 
    # IBM Cloud Secret Manager
    ibm:
      serviceUrl: <PUBLIC_URL> 
      auth:
        secretRef:
          secretApiKeySecretRef:
            name: name-of-the-secret-in-K8s
            key: authenticationApiKey
```

Maybe this scenario is only not covered by IBM Secret Manager, but for other providers. At least that's what I was reading in the [documentation](https://cloud.ibm.com/docs/secrets-manager?topic=secrets-manager-ha-dr&locale=en): 

`However, because Secrets Manager is a regional service, cross-regional failover, and cross-regional disaster recovery are not automatic. If all the availability zones in a region fail, Secrets Manager becomes unavailable in that location. When the region is available again, data and traffic is restored without any need for action from you.`

The documentation only describes how I'd be able to back up my secrets manually (or via a job).

**Describe the solution you'd like**

As a ESO user/admin, I'd like to be able to configure a HA setup within the ESO core resources (ClusterSecretStore/SecretStore) with an **internal** failover mechanism to switch to another SM instance in case of zone unavailability.

**Describe alternatives you've considered**

Alternatively, you can backing up your secrets on multiple instances on different regions, but in case of region failure, you need to manually switch the provider instance to use the available one. Personally, I'd rather like to see this feature within ESO.

**Additional context**

I hope this feature is also relevant for other providers and scenarios, thank you!

**Comment by moolen** [comment]
Just to clarify: we're talking about regional unavailability, not a single zone being unavailable, right? AFAIK IBM Secret Manager is a regional service.

ESO acts as a caching layer. Even though the API is unavailable the secrets in Kubernetes are still present and workloads continue to function.
We don't have facilities in place that provide cross-regional failover., here's a sketch on how that could look like:

```yaml
Kind: SecretStore
spec:
  provider: {} # ...
  # point to a SecretStore that is used as a fallback in case this SecretStore
  # is unavailable.
  fallbackSecretStoreRef:
    name: "foo"
```

How to determine unavailability?
That's the tough part: TCP handshake? should we verify credentials to determine availability?

CC @IdanAdar
