### ISSUE TITLE
Helm chart section to add custom resources to the chart like `extraDeploy` or `extraObjects`

### ISSUE THREAD

**Issue by MurzNN** [external-secrets/external-secrets#2984]
**Is your feature request related to a problem? Please describe.**
Many Helm charts provide the ability to add custom resources to the chart, which is very convenient. But the `external-secrets` chart seems missing it?

For example, via this section, we can deploy a custom `SecretStore` together with the main `external-secrets` chart, without having to create a separate custom chart, just describe it in the `values.yaml` for the main chart, and that's it!

For example, in all Bitnami charts we have the `extraDeploy` parameter: https://docs.bitnami.com/kubernetes/apps/aspnet-core/administration/deploy-extra-resources/

In the Grafana chart we have `extraObjects` array: https://github.com/grafana/helm-charts/blob/adac294d65952e6cfc00d02d9d009f4452adcfae/charts/grafana/values.yaml#L1290C1-L1290C13

And the same for many other popular charts.

**Describe the solution you'd like**
So, could you please add this section to the `external-secrets` Helm chart?

**Describe alternatives you've considered**
An alternative is to create a separate chart to deploy custom secret stores, which is not very convenient.

**Comment by mruoss** [comment]
I'd love to have this possibility in the helm cart, too!

**Comment by jasonwashburn** [comment]
I think this issue may have gotten stranded/forgotten about? There is an `extraObjects` value present in the latest helm chart.

ref: https://github.com/external-secrets/external-secrets/blob/04ec19ce5ebe652539fd596f90e099d667eab998/deploy/charts/external-secrets/values.yaml#L150

One caveat though, if you want to use it to create external-secrets specific resources, you'll either need to install the CRDs first, or you can add helm post-install and post-upgrade hooks to the resources you want to create to make sure they're installed after helm has installed the CRDs.

For example...

```yaml
installCRDs: true

extraObjects:
  - apiVersion: generators.external-secrets.io/v1alpha1
    kind: Fake
    metadata:
      name: fake-generator-for-testing
      namespace: external-secrets
      # These helm hooks are needed to ensure helm tries to create the extraObjects
      # after the external-secrets CRDs have been installed by the chart.
      annotations:
        "helm.sh/hook": post-install,post-upgrade
        "helm.sh/hook-weight": "1"
    spec:
      data:
        foo: bar

```
