### ISSUE TITLE
could not write remote ref  to target secretstore gsm: pushing the whole secret is not yet implemented

### ISSUE THREAD

**Issue by lodotek** [external-secrets/external-secrets#2994]
**Describe the bug**
```
"error":"could not write remote ref  to target secretstore gsm: pushing the whole secret is not yet implemented","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:227"}
```
`set secret failed: could not write remote ref to target secretstore gsm: pushing the whole secret is not yet implemented`

**To Reproduce**
1. provide all relevant manifests:
```
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: cmdev.restapiserver
  namespace: cmdev

spec:
  refreshInterval: 5m
  secretStoreRefs:
    - name: gsm
      kind: ClusterSecretStore

  selector:
    secret:
      name: cmdev-restapiserver1

  data:
    - match:
        remoteRef:
          remoteKey: maui01__cmdev__restapiserver

```

3. provide the Kubernetes and ESO version: ESO Version `0.9.11` K8s Version 1.26

**Expected behavior**
able to push entire k8s secret to one GCPSM object as a json.

**Comment by Skarlso** [comment]
Hello @lodotek 👋 

Provider specific implementation is added on a needed basis. :) We don't implement a feature for all providers all the time. That would be a giant effort and features would never be implemented. :D

So features for providers are implemented by the community normally if the need arises for them. In this particular case, pushing the whole secret for GCP isn't implemented yet.

This happened because you didn't define a `SecretKey`. I assume on purpose.

Here is the provider and location to implement this feature at:

https://github.com/external-secrets/external-secrets/blob/main/pkg/provider/gcp/secretmanager/client.go#L133

Thanks!

**Comment by phclark** [comment]
It would be helpful if this policy was highlighted somewhere in the documentation

**Comment by BenjaminWinks** [comment]
Yes, this would be very appreciated because telling users that something is possible only for it to error as "Pushing the whole secret is not yet implemented" is confusing if you don't know what providers are supported. Azure does not appear to be supported at the moment as well given the errors I'm seeing.

**Comment by Skarlso** [comment]
> It would be helpful if this policy was highlighted somewhere in the documentation. A feature compatibility matrix of some sort would be great!

I agree, absolutely! We roll out functionality periodically. It would be nice to track which provider supports what functionality.

**Comment by artarik** [comment]
Have the same error but I have `SecretKey`
Provider Amazon
```
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: pw-generator
  namespace: test
spec:
  length: 16
  digits: 5
  symbols: 5
  symbolCharacters: "-_$@"
  noUpper: false
  allowRepeat: true
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "generated-password"
  namespace: test
spec:
  refreshInterval: "10m"
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: Password
        name: pw-generator
  target:
    template:
      type: kubernetes.io/basic-auth
      engineVersion: v2
      data:
        username: "username"
        password: "{{ .password }}"
    name: generated-basic-auth-password
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: pushsecret
  namespace: test
spec:
  refreshInterval: 10m
  secretStoreRefs:
    - name: css-awssm-argocd-rw
      kind: ClusterSecretStore
  selector:
    secret:
      name: generated-basic-auth-password # Source Kubernetes secret to be pushed
  data:
    - match:
        secretKey: password # property in the generator output
        remoteRef:
          remoteKey: /secrets/staging
          property: K8S_GENERATED_PWD # The key within the destination secret object.

```
