### ISSUE TITLE
IBM Cloud Secrets Manager: Secret Key Not Found

### ISSUE THREAD

**Issue by ob-nitaib** [external-secrets/external-secrets#300]
**Describe the solution you'd like**
I would like the solution to connect to IBM Cloud Secrets Manager and find the secrets that I have stored there, regardless of which secret group they are stored in. 

**What is the added value?**
This will make the IBM Cloud Secrets Manager provider functional, or please make the error more detailed so can debug

**Observations (Constraints, Context, etc):**
I am using OpenShift 4.5.x deploying in IBM Cloud with External Secrets that has been deployed with the Helm Chart v0.3.0.
The API Key I am using (and therefore the secret store) are able to authenticate with my IBM Cloud account. Furthermore when I use the API Key in Postman, I can list the secrets in the secret manager without any difficulty. 

The following is my external secret resource: 
```yaml
{{- range $secrets := .Values.secrets }}
---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: {{ $secrets.extSecName }}
spec:
  secretStoreRef:
    name: {{ $.Values.secretStore.name }}
    kind: SecretStore
  refreshInterval: {{ $secrets.refreshInterval }}
  target:
    name: {{ $secrets.secName }}
    creationPolicy: "Owner"
    template:
      type: {{ $secrets.type }}
  data:
    - secretKey: {{ $secrets.secKey }}
      remoteRef:
        key: {{ $secrets.remoteSecId }}
{{- end }}
```
If you would like me to include the values file, I can do so.

When I apply this secret to the cluster I get the following status:
```bash
Status:
  Conditions:
    Last Transition Time:  2021-07-29T12:33:33Z
    Message:               could not get secret data from provider: key "<redacted>" from ExternalSecret "<redacted>": Not Found
    Reason:                SecretSyncedError
    Status:                False
    Type:                  Ready
```
