### ISSUE TITLE
Ability to skip non-existing secrets with `dataFrom.find`

### ISSUE THREAD

**Issue by alpozcan** [external-secrets/external-secrets#3004]
**Is your feature request related to a problem? Please describe.**
We're using external-secrets with the Vault provider. In our setup, we have a hierarchical secrets path convention where a secret for a given app can be a result of merging multiple secret paths' contents, with the Vault secret paths as follows:
- app-secrets/all-apps/all-environments/runtime
- app-secrets/my-app/all-environments/runtime
- app-secrets/my-app/production/runtime

etc...

But the problem is that, external-secrets seems to be expecting every single one of these paths to be populated with secrets, and fails to sync the secret if one of them don't exist, with an error like the below:

```
kubectl describe es ...
...
provided path my-app/metadata/all-environments/runtime does not contain any secrets
```

**Describe the solution you'd like**

If would good if the ExternalSecret could skip the paths that are not found and perform merge only on the secrets that are found instead of failing.

This could be accomplished with a configuration attribute like `optional = true` under `find` or `extract` entries.

**Describe alternatives you've considered**
Initially we were using `dataFrom.extract` entries in our `ExternalSecret`, but that resulted in the same outcome with a similar error.
Then we tried with `datafrom.find` with path and name like the following:
```
Spec:
  Data From:
    Find:
      Conversion Strategy:  Default
      Decoding Strategy:    None
      Name:
        Regexp:  runtime
      Path:      my-app/all-environments
```

**Comment by Skarlso** [comment]
@alpozcan added `IgnoreNotFound` option to the Find ref.

**Comment by gusfcarvalho** [comment]
Out of curiosity - did you try using DeletionPolicy: Merge?

that should fix the not found behavior you’re seeing.

**Comment by Skarlso** [comment]
Hmm... how would that.. help? There is a distinct path in the vault code that says if there are no secrets, then error.

**Comment by gusfcarvalho** [comment]
If the deletionPolicy is not Retain, we ignore `NoSecretErr` on the main controller:
https://github.com/external-secrets/external-secrets/blob/main/pkg/controllers/externalsecret/externalsecret_controller_secret.go#L68-L71

**Comment by Skarlso** [comment]
Sure, but that is too high level. That will ignore all secrets, meanwhile the vault list secret is a recursive function. So it would return some secrets but ignore others that could not be found as it traverses the path.

At the high level would not return the secrets that would have been found at the deeper level of the path.

**Comment by gusfcarvalho** [comment]
> Sure, but that is too high level. That will ignore all secrets, meanwhile the vault list secret is a recursive function. So it would return some secrets but ignore others that could not be found as it traverses the path.
> 
> At the high level would not return the secrets that would have been found at the deeper level of the path.

That would depend on each provider - and for vault, that's not the case

If `path/to/nested/secret` exists, any calls to `path/`, `path/to`, and `path/to/nested` will return with metadata content

**Comment by Skarlso** [comment]
Right, but the problem is, that ListWithContext or the other one doesn't return with an error! It returns an empty secret.
It doesn't return NotFound for whatever reason.... Maybe there is actually a different problem here. :)

**Comment by Skarlso** [comment]
Neat. :D

**Comment by gusfcarvalho** [comment]
> Right, but the problem is, that ListWithContext or the other one doesn't return with an error! It returns an empty secret.
It doesn't return NotFound for whatever reason.... Maybe there is actually a different problem here. :)

yeah, I think if we change https://github.com/external-secrets/external-secrets/blob/main/pkg/provider/vault/client_get_all_secrets.go#L121 to a `NoSecretErr` that will already be fully covered with deletion policy checks.

**Comment by Skarlso** [comment]
Yah, that makes sense to me.

**Comment by Skarlso** [comment]
Okay, this makes sense hopefully. :)

**Comment by alpozcan** [comment]
> [@alpozcan](https://github.com/alpozcan) added `IgnoreNotFound` option to the Find ref.

Hi,
I'm a bit confused - in the latest version 0.13.0, neither the `secretstores.external-secrets.io` nor `externalsecrets.external-secrets.io` CRD has `IgnoreNotFound` in the definition. I don't see it in the API documentation, and [it only comes up as a test code addition in the repo search](https://github.com/search?q=repo%3Aexternal-secrets%2Fexternal-secrets%20IgnoreNotFound&type=code).

Have I missed something?

**Comment by Skarlso** [comment]
I think the fix was that it should return a `NoSecretError`. Which is effectively ignored and not raised as an error if I recall correctly.

Are you still getting the above problems?

**Comment by alpozcan** [comment]
This feature request has been about a user-side fix at ExternalSecret level or similar but I keep getting responses that are seemingly about the internals of the operator...

**Comment by Skarlso** [comment]
I mean, did you try the same thing with the latest version?

**Comment by gusfcarvalho** [comment]
> This feature request has been about a user-side fix at ExternalSecret level or similar but I keep getting responses that are seemingly about the internals of the operator...

We understand you requested for a feature, but the thing is this feature is already done. 

What's happening here is a bug specifically for `dataFrom.find`, hence internals discussion.

**Comment by alpozcan** [comment]
Hi SkarIso & gusfcarvalho,

How can I test this feature? I am asking because I didn't find it described in the docs.With the following ES on version 0.13.0:
```
apiVersion: v1
items:
- apiVersion: external-secrets.io/v1beta1
  kind: ExternalSecret
  metadata:
    name: myapp
    namespace: default
  spec:
    dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: myapp/runtime/all-environments/all-regions
        metadataPolicy: None
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: myapp/runtime/all-environments/ap-southeast-2
        metadataPolicy: None
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: myapp/runtime/staging/all-regions
        metadataPolicy: None
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: myapp/runtime/staging/ap-southeast-2
        metadataPolicy: None
    refreshInterval: 10m
    secretStoreRef:
      kind: SecretStore
      name: myapp
    target:
      creationPolicy: Orphan
      deletionPolicy: Retain
      name: myapp-runtime
kind: List
metadata:
  resourceVersion: ""
```

It results in:
```
  Conditions:
    Last Transition Time:   2025-01-23T23:46:18Z
    Message:                could not get secret data from provider
    Reason:                 SecretSyncedError
    Status:                 False
    Type:                   Ready
  Refresh Time:             2025-01-23T23:35:59Z
  Synced Resource Version:  1-2f2c636d06132f67992c15a1daeb0a5f
Events:
  Type     Reason        Age   From              Message
  ----     ------        ----  ----              -------
  Warning  UpdateFailed  1s    external-secrets  Secret does not exist
```

If I delete `myapp/runtime/staging/ap-southeast-2` in Vault.

**Comment by Skarlso** [comment]
But... you are specifically extracting that.. 🤔 Of course it will say not found if you specifically are looking for that thing. Or am I misunderstanding something/

**Comment by Skarlso** [comment]
No, you shouldn't need anything specific. If you just use find, it should skip things now that don't exist and not error because of it.

**Comment by alpozcan** [comment]
> No, you shouldn't need anything specific. If you just use find, it should skip things now that don't exist and not error because of it.

Thank you. If I hit any issues with it I'll let you know.

**Comment by Skarlso** [comment]
Thanks.

**Comment by alpozcan** [comment]
Unfortunately it doesn’t seem to be possible to achieve the merging behaviour we want using  `find` . This seems to be the same situation as in [this GH issue](https://github.com/external-secrets/external-secrets/issues/2886).

I performed the below test on myapp/staging on the latest version 0.14.3:

The current ExternalSecret:
```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
...
spec:
  dataFrom:
  - extract:
      conversionStrategy: Default
      decodingStrategy: None
      key: myapp/runtime/all-environments/all-regions
      metadataPolicy: None
  - extract:
      conversionStrategy: Default
      decodingStrategy: None
      key: myapp/runtime/all-environments/eu-west-1
      metadataPolicy: None
  - extract:
      conversionStrategy: Default
      decodingStrategy: None
      key: myapp/runtime/staging/all-regions
      metadataPolicy: None
  - extract:
      conversionStrategy: Default
      decodingStrategy: None
      key: myapp/runtime/staging/eu-west-1
      metadataPolicy: None
...
```

The initial version of the rewritten ExternalSecret with extract converted to the equivalent find:
```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
...
spec:
  dataFrom:
  - find:
      conversionStrategy: Default
      decodingStrategy: None
      path: myapp/runtime/all-environments
      name: 
        regexp: all-regions/*
  - find:
      conversionStrategy: Default
      decodingStrategy: None
      path: myapp/runtime/all-environments
      name: 
        regexp: eu-west-1/*
  - find:
      conversionStrategy: Default
      decodingStrategy: None
      path: myapp/runtime/staging
      name: 
        regexp: all-regions/*
  - find:
      conversionStrategy: Default
      decodingStrategy: None
      path: myapp/runtime/staging
      name: 
        regexp: eu-west-1/*
...
```

Results in the below result, which is not what we want:

myapp_runtime_all-environments_all-regions:  2 bytes
myapp_runtime_all-environments_eu-west-1:    2 bytes
myapp_runtime_staging_all-regions:           1717 bytes
myapp_runtime_staging_eu-west-1:             2 bytes


Note that it was also necessary to add the policy following capabilities to the policy to allow find to list the secrets in the path (otherwise received a ):
```
path "app-secrets/metadata/myapp/runtime/all-environments" {
  capabilities = ["read", "list"]
}
path "app-secrets/metadata/myapp/runtime/staging" {
  capabilities = ["read", "list"]
}
```

Next, I added [rewrite rules as mentioned in the documentation](https://external-secrets.io/v0.14.3/guides/datafrom-rewrite/) to try and merge the secret entries into one:
```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
...
spec:
  dataFrom:
  - find:
      conversionStrategy: Default
      decodingStrategy: None
      path: myapp/runtime/all-environments
      name: 
        regexp: all-regions
    rewrite:
    - regexp:
        source: "myapp/runtime/all-environments/all-regions/(.*)"
        target: "$1"
  - find:
      conversionStrategy: Default
      decodingStrategy: None
      path: myapp/runtime/all-environments
      name: 
        regexp: eu-west-1
    rewrite:
    - regexp:
        source: "myapp/runtime/all-environments/eu-west-1/(.*)"
        target: "$1"
  - find:
      conversionStrategy: Default
      decodingStrategy: None
      path: myapp/runtime/staging
      name: 
        regexp: all-regions
    rewrite:
    - regexp:
        source: "myapp/runtime/staging/all-regions/(.*)"
        target: "$1"
  - find:
      conversionStrategy: Default
      decodingStrategy: None
      path: myapp/runtime/staging
      name: 
        regexp: eu-west-1
    rewrite:
    - regexp:
        source: "myapp/runtime/staging/eu-west-1/(.*)"
        target: "$1"
...
```


Resulted in the issue below:
```
Events:
  Type     Reason        Age                From              Message
  ----     ------        ----               ----              -------
  Warning  UpdateFailed  10s (x2 over 41s)  external-secrets  error processing spec.dataFrom[0].find, err: invalid secret keys (TIP: use rewrite or conversionStrategy to change keys): key has invalid character /, only alphanumeric, '-', '.' and '_' are allowed: myapp/runtime/all-environments/all-regions
```

Despite having confirmed that none of the four paths actually contained keys with / in their names. **Note that some of these paths contain empty secrets.**

Then I added the following second regexp into each of the four find entries:

```
    - regexp:
        source: "[^a-zA-Z0-9 -]"
        target: "_"
```

Which resulted in a kube secret with four keys in it that correspond to the paths in Vault, same as before, as if no rewrite rules have been provided.

I have also tried other regexp sources "[\/]", "[/]", “/", and swapping the order of `regexp`s all with the same result.

Also tried: `conversionStrategy = “Unicode”` to no avail.

**Comment by gusfcarvalho** [comment]
Can you share your whole manifest?

Also, these secrets then do exist within your vault, they are just `{}`? this is different than not having a secret at all.

**Comment by gusfcarvalho** [comment]
In that case, what you'll really need to do is template `fromLiteral` over all your keys:

```
spec:
  target:
    template:
      templateFrom:
      - Literal: |
            #iterate over all the keys
            {{ $k, $v := range . }}
            #transform from json into object
            {{ $val := $v | fromJson }}
            # iterate over object
            {{ $kk, $vv := range $val }}
            # add each iteam in a loop (overwrites if two exists)
            {{ $kk }}: { $vv }}
            {{- end}}
            {{- end}}
  dataFrom:
  - find:
      conversionStrategy: Default
      decodingStrategy: None
      path: myapp/runtime
      name: 
        regexp: ".*"
    rewrite:
       - regexp:
           source: "myapp/runtime/(.*)"
           target: "$1"
       - regexp:
           source: "/"
           target: "_"
```

this will likely need tampering as I'm writing this from my phone - but it should point you to the correct direction.


An easier solution is to be sure that those empty keys are actually _deleted_ as oposed to be empty values.

**Comment by alpozcan** [comment]
Hi Gustavo,
Thank you for your replies.

As noted in my previous post, there are many paths in the app's secrets hierarchy with empty secrets. This is a workaround against having the secret sync failing entirely with `... does not contain any secrets` with the `extract` method, if even one of the paths were non-existent.

I'll also note that I deliberately didn't use the more concise `dataFrom.find.name.regexp: ".*"` because we want to be explicit about the merge order in accordance with our path hierarchy. In other words we don't want the (alphabetical?) merge order of subpaths that would result with the regex windcard, even if it may happen to have the same order in this particular instance. Hence my current example manifest having several `find`s.

I just tried your suggestion, and got the below event emitted from the ES:
```
  Warning  UpdateFailed  42s                  external-secrets  could not apply template: error fetching templateFrom data: unable to execute template at key #iterate over all the keys
{{ $k, $v := range . }}
#transform from json into object
{{ $val := $v | fromJson }}
# iterate over object
{{ $kk, $vv := range $val }}
# add each iteam in a loop (overwrites if two exists)
{{ $kk }}: { $vv }}
{{- end}}
{{- end}}
: unable to parse template at key #iterate over all the keys
{{ $k, $v := range . }}
#transform from json into object
{{ $val := $v | fromJson }}
# iterate over object
{{ $kk, $vv := range $val }}
# add each iteam in a loop (overwrites if two exists)
{{ $kk }}: { $vv }}
{{- end}}
{{- end}}
: template: #iterate over all the keys
{{ $k, $v := range . }}
#transform from json into object
{{ $val := $v | fromJson }}
# iterate over object
{{ $kk, $vv := range $val }}
# add each iteam in a loop (overwrites if two exists)
{{ $kk }}: { $vv }}
{{- end}}
{{- end}}
:2: too many declarations in command
```

Following is the current version of the full manifest:
```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: myapp-alptest
  namespace: default
spec:
  dataFrom:
  - find:
      conversionStrategy: Default
      decodingStrategy: None
      path: myapp/runtime/all-environments
      name: 
        regexp: all-regions
    rewrite:
    - regexp:
        source: "myapp/runtime/all-environments/all-regions/(.*)"
        target: "$1"
    - regexp:
        source: "/"
        target: "_"

  - find:
      conversionStrategy: Default
      decodingStrategy: None
      path: myapp/runtime/all-environments
      name: 
        regexp: eu-west-1
    rewrite:
    - regexp:
        source: "myapp/runtime/all-environments/eu-west-1/(.*)"
        target: "$1"
    - regexp:
        source: "/"
        target: "_"

  - find:
      conversionStrategy: Default
      decodingStrategy: None
      path: myapp/runtime/staging
      name: 
        regexp: all-regions
    rewrite:
    - regexp:
        source: "myapp/runtime/staging/all-regions/(.*)"
        target: "$1"
    - regexp:
        source: "/"
        target: "_"

  - find:
      conversionStrategy: Default
      decodingStrategy: None
      path: myapp/runtime/staging
      name: 
        regexp: eu-west-1
    rewrite:
    - regexp:
        source: "myapp/runtime/staging/eu-west-1/(.*)"
        target: "$1"
    - regexp:
        source: "/"
        target: "_"

  refreshInterval: 10m
  secretStoreRef:
    kind: SecretStore
    name: myapp
  target:
    creationPolicy: Orphan
    deletionPolicy: Retain
    name: myapp-runtime-alptest
    template:
      templateFrom:
      - target: Data
        literal: |
            #iterate over all the keys
            {{ $k, $v := range . }}
            #transform from json into object
            {{ $val := $v | fromJson }}
            # iterate over object
            {{ $kk, $vv := range $val }}
            # add each iteam in a loop (overwrites if two exists)
            {{ $kk }}: { $vv }}
            {{- end}}
            {{- end}}

```

**Comment by alpozcan** [comment]
Since we're only iterating over a single level of key-value pairs, I guess we only need a single level of iteration. I tried this might fix the `:2: too many declarations in command` but I got the same error with the following:
```
    ...
    template:
      templateFrom:
      - target: Data
        literal: |
            #iterate over all the keys
            {{ $key, $value := range . }}
            {{ $key }}: { $value }}
            {{- end}}
```

**Comment by gusfcarvalho** [comment]
you can use `esoctl` to validate the template. I mentioned it is likely to be wrong 😄. Re your full manifests:

```
  - find:
      conversionStrategy: Default
      decodingStrategy: None
      path: myapp/runtime/staging
      name: 
        regexp: eu-west-1
    rewrite:
    - regexp:
        source: "myapp/runtime/staging/eu-west-1/(.*)"
        target: "$1"
    - regexp:
        source: "/"
        target: "_"
```

This rewrite there is targeting nothing, because `datafrom.find` does not open up the secret values. You'll have a single secret named `myapp/runtime/staging/eu-west-1` with a value of `{"key":"1","secondKey":"2"}`. So this rewrite is the cause of your original error.
