### ISSUE TITLE
AWS SecretsManager requiring AWS_CA_BUNDLE

### ISSUE THREAD

**Issue by j-wozniack** [external-secrets/external-secrets#3009]
**Describe the bug**
When I provide a CA bundle, my deployment appears all healthy, but no secret is ultimately created. If I don't provide the CA, I see x509 TLS errors as I would otherwise expect.

**To Reproduce**
I've deployed the latest (0.9.11) helm chart to a cluster with values like
```
extraVolumes:
  - name: aws-ca-bundle
    secret:
      secretName: aws-ca-bundle
extraVolumeMounts:
  - name: aws-ca-bundle
    mountPath: "/tmp/ca-bundle"
extraEnv:
  - name: AWS_CA_BUNDLE
    value: "/tmp/ca-bundle/tls-ca-bundle.pem"

certController:
  extraVolumes:
    - name: aws-ca-bundle
      secret:
        secretName: aws-ca-bundle
  extraVolumeMounts:
    - name: aws-ca-bundle
      mountPath: "/tmp/ca-bundle"
  extraEnv:
    - name: AWS_CA_BUNDLE
      value: "/tmp/ca-bundle/tls-ca-bundle.pem"

webhook:
  extraVolumes:
    - name: aws-ca-bundle
      secret:
        secretName: aws-ca-bundle
  extraVolumeMounts:
    - name: aws-ca-bundle
      mountPath: "/tmp/ca-bundle"
  extraEnv:
    - name: AWS_CA_BUNDLE
      value: "/tmp/ca-bundle/tls-ca-bundle.pem"
```

I have the following ClusterSecretStore which reports a healthy status
```
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secretsmanager
spec:
  provider:
    aws:
      service: SecretsManager
      region: <my region>
```

And the following ClusterExternalSecret, also reporting a healthy status

```
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: test-secret
spec:
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: default
  refreshTime: "15s"
  externalSecretSpec:
    refreshInterval: 1m
    secretStoreRef:
      name: aws-secretsmanager
      kind: ClusterSecretStore
    target:
      name: test-secret
    data:
    - secretKey: test-key
      remoteRef:
        key: test-secret
```

I can see that the ClusterExternalSecret properly creates an ExternalSecret in the default namespace.

Each of the pod's logs look healthy as well, but ultimately no secret is created. I've also tried setting the loglevel for each pod to debug but the additional logs don't indicate any problems.

When I remove the CA bundle, the external-secrets pod throws x509 TLS errors as expected (indicating it's being respected).

**Expected behavior**
The service should pull the secret from SecretsManager and utilize the AWS_CA_BUNDLE in order to utilize TLS.

**Screenshots**
None

**Additional context**
N/A
