### ISSUE TITLE
Allow to push secret in another format than JSON object

### ISSUE THREAD

**Issue by T0myC** [external-secrets/external-secrets#3027]
I would like to push secret containing certificate generated from cert-manager.
Here is the structure of the generated secret :

```
Name:         secret-cert
Type:  kubernetes.io/tls 

Data
====
tls.crt:  ----cert----- 
tls.key:  -----key-----
```
I would like to push this secret in a Hashicorp Vault by using PushSecret resource like following :

```
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: pushsecret-example
  namespace: external-secrets
spec:
  refreshInterval: 10s 
  secretStoreRefs:
    - name: vault-backend-push
      kind: SecretStore
  selector:
    secret:
      name: secret-cert
  data:
    - match:
        secretKey: tls.crt
        remoteRef:
          remoteKey: certificate_test
          property: cert
    - match:
       secretKey: tls.crt
       remoteRef:
         remoteKey: certificate_test
         property: key
```
Do you think is it possible ?
