### ISSUE TITLE
SecretKey with symbols in combination with template are not generating a Kubernetes secret

### ISSUE THREAD

**Issue by janpfischer** [external-secrets/external-secrets#3028]
**Describe the bug**
If I want to try to utilize template functions in external-secrets to extract the crt and key from a pfx which is stored in Azure Key Vault like described in the documentation (https://external-secrets.io/latest/guides/templating/#extract-keys-and-certificates-from-pkcs12-archive) I'll have to make sure that the `secretKey` in `data` does not contain any symbols like `-`.

If it contains symbols the external-secret CRD is successfully synced but the Kubernetes secret is not created. There are no error messages logged in the controller and no indication that the secret is not created. It is simply missing. 

Example:
```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $secret.name }}
  namespace: {{ $namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ $.Values.secretStore }}
    kind: ClusterSecretStore
  target:
    name: {{ $secret.name }}
    creationPolicy: Owner
    template:
      type: kubernetes.io/tls
      engineVersion: v2
      data:
        tls.crt: "{{ `{{ .certpfx | b64dec | pkcs12cert }}` }}"
        tls.key: "{{ `{{ .certpfx | b64dec | pkcs12key }}` }}"
  data:
    - secretKey: certpfx
      remoteRef:
        key: secret/{{ $secret.remoteKey }}
```

In this example the `secretKey` is `certpfx` which is used in the template function. If you write `cert-pfx` the secret will not be created.

**To Reproduce**
1. Change the `secretKey` to something that contains symbols like `-`.
2. Check that the external-secret is successfully synced
3. Verify that the Kubernetes secret is missing

**Expected behavior**
I would expect that the secret is created even if symbols like `-` are used. If this is not possible I would at least expect errors which are logged to give me a hint. Currently nothing is logged.
