### ISSUE TITLE
Find by tags getting same password  

### ISSUE THREAD

**Issue by bala151187** [external-secrets/external-secrets#3031]
**Describe the bug**
**Find by tags getting same password for two different set of tags**

```
apiVersion: external-secrets.io/v1beta1 
kind: ExternalSecret
metadata:
  name:  dev-delmar-lti-content-del-external-secret
spec:
  refreshInterval: 2m
  secretStoreRef:
    name: clustersecretstore
    kind: ClusterSecretStore
  target:
    name: dev-delmar-lti-content-del-rdsmasterpassword
  dataFrom:
  - find:
      tags:
        app-environment: "DEV"
        app-service: "lti_content_delivery"
        app-platform: "k8s"
        services.k8s.aws/namespace: "delmar"
    rewrite:
    - regexp:
        source: "(.*)"
        target: credentials

apiVersion: external-secrets.io/v1beta1 
kind: ExternalSecret
metadata:
  name:  dev-delmar-sec-lti-content-del-external-secret
spec:
  refreshInterval: 2m
  secretStoreRef:
    name: clustersecretstore
    kind: ClusterSecretStore
  target:
    name: dev-delmar-sec-lti-content-del-rdsmasterpassword
  dataFrom:
  - find:
      tags:
        app-environment: "DEV"
        app-service: "lti_content_delivery_int"
        app-platform: "k8s"
        services.k8s.aws/namespace: "delmar-secondary"
    rewrite:
    - regexp:
        source: "(.*)"
        target: credentials
```

**secret -** 

```
dev-delmar-lti-content-del-rdsmasterpassword 
{"username":"admin","password":"eA>z7X3$4O"}

dev-delmar-sec-lti-content-del-rdsmasterpassword
{"username":"admin","password":"eA>z7X3$4O"}
```

**External secret operator log** 

```
{"level":"info","ts":1705442073.3943007,"logger":"provider.aws.secretsmanager","msg":"fetching secret value","key":"rds!cluster-3727d10e-9dae-4c70","version":"AWSCURRENT","value":"SECRET"}
{"level":"info","ts":1705442073.4248736,"logger":"provider.aws.secretsmanager","msg":"fetching secret value","key":"rds!cluster-0e9d845a-11e1-4827-898c","version":"AWSCURRENT","value":"SECRET"}
{"level":"info","ts":1705442319.7837257,"logger":"provider.aws","msg":"using aws session","region":"us-east-2","external id":"","credentials":{}}
{"level":"info","ts":1705442619.881724,"logger":"provider.aws","msg":"using aws session","region":"us-east-2","external id":"","credentials":{}}
{"level":"info","ts":1705442920.0147681,"logger":"provider.aws","msg":"using aws session","region":"us-east-2","external id":"","credentials":{}}
```
