### ISSUE TITLE
Silent error when using `regexReplaceAllLiteral` sprig function in template literal

### ISSUE THREAD

**Issue by adambournsonos** [external-secrets/external-secrets#3034]
**Describe the bug**
I'm trying to use the `regexReplaceAllLiteral` [sprig function ](http://masterminds.github.io/sprig/strings.html#regexreplaceallliteral-mustregexreplaceallliteral) in a template literal, such that I can generate keys within the Kubernetes secret with valid characters (i.e. only alphanumeric and underscores).  When I try to use this function, the ExternalSecret object gets created, but a Kubernetes Secret is never produced.   

There are seemingly no errors logged regarding a template issue.  I can only assume that I'm doing something wrong, but my several different permutations have not worked so I thought I'd report here. 

**To Reproduce**

Kubernetes version 1.27
ESO version 0.9.4

The following `ExternalSecret` manifest results in the described behavior. 

```yaml
apiVersion: 'external-secrets.io/v1beta1'
kind: ExternalSecret
metadata:
  name: abourn-test
spec:
  refreshInterval: "30s"
  secretStoreRef:
    name: awssecretsmanager
    kind: ClusterSecretStore
  target:
    name: abourn-test
    creationPolicy: Owner
    template:
      engineVersion: v2
      templateFrom:
      - target: Data
        literal: |
          {{ range $key, $value := . }}
          {{ range $skey, $svalue := fromJson $value }}
          {{$key}}_{{regexReplaceAllLiteral "[^a-zA-Z\d\s:_]" $skey "_"}}: {{$svalue}}
          {{ end }}
          {{ end }}
  dataFrom:
  - find:
      name:
        regexp: "example/dev"
    rewrite:
    - regexp:
        source: "[^a-zA-Z\\d\\s_]"
        target: "_"
```
The contents of a matching secret in the secret store is:
`{"theSecret":"noPeeking"}`

I've also tried other approaches, such as `{{"_" | regexReplaceAllLiteral "[^a-zA-Z\d\s:_]" $skey}}: {{$svalue}}`, but I couldn't get that to work either.

In all my attempts, describing the `ExternalSecret` shows only "normal" events:
```
│ Status:                                                                                                                                             │
│   Conditions:                                                                                                                                       │
│     Last Transition Time:   2024-01-17T20:25:32Z                                                                                                    │
│     Message:                Secret was synced                                                                                                       │
│     Reason:                 SecretSynced                                                                                                            │
│     Status:                 True                                                                                                                    │
│     Type:                   Ready                                                                                                                   │
│   Refresh Time:             2024-01-17T20:25:32Z                                                                                                    │
│   Synced Resource Version:  1-49ee35f5763751e9b68610a5004cb774                                                                                      │
│ Events:                                                                                                                                             │
│   Type    Reason   Age                From              Message                                                                                     │
│   ----    ------   ----               ----              -------                                                                                     │
│   Normal  Updated  20s (x3 over 21s)  external-secrets  Updated Secret                                                                              │
│   Normal  Updated  20s (x2 over 20s)  external-secrets  Updated Secret
```

I would have provided a repro using the "fake" provider, but seemingly `GetAllSecrets` isn't implemented for that so my case of using 'find' isn't portable there.

**Expected behavior**
I expect the Kubernetes Secret to be created, like it would be when using other "simpler" sprig functions.  Alternatively,  if there is something wrong with my usage of the template, I would at least expect the error to show up somewhere(either logs or events on the `ExternalSecret` object).

For example, with the following manifest, the Kubernetes Secret gets created as expected (notice the use of `upper` sprig function):
```yaml
apiVersion: 'external-secrets.io/v1beta1'
kind: ExternalSecret
metadata:
  name: abourn-test
spec:
  refreshInterval: "30s"
  secretStoreRef:
    name: awssecretsmanager
    kind: ClusterSecretStore
  target:
    name: abourn-test
    creationPolicy: Owner
    template:
      engineVersion: v2
      templateFrom:
      - target: Data
        literal: |
          {{ range $key, $value := . }}
          {{ range $skey, $svalue := fromJson $value }}
          {{$key}}_{{$skey | upper}}: {{$svalue}}
          {{ end }}
          {{ end }}
  dataFrom:
  - find:
      name:
        regexp: "example/dev"
    rewrite:
    - regexp:
        source: "[^a-zA-Z\\d\\s_]"
        target: "_"

```
This `ExternalSecret` produces the expected `Secret` object:

```
Name:         abourn-test
Namespace:    default
Labels:       reconcile.external-secrets.io/created-by=b251da1d3ae2592d2b7d85f83fbdc88a
Annotations:  reconcile.external-secrets.io/data-hash: c606e2cf150c2cae99ccd5727faae292

Type:  Opaque

Data
====
example_dev_secret_THESECRET:  9 bytes # value here is "noPeeking"
```

**Screenshots**
N/A

**Additional context**
I need this `ExternalSecret` to use the `dataFrom.find` option  AND for the resulting Secret to "extract" all of the key/value pairs which exist within a matching entry in the secret store.  This is the reason why I'm using both the `rewrite` option _and_ the template literal option.  If I didn't need to use `dataFrom.find`, I would simply use `dataFrom.extract` and `rewrite`, as unfortunately `dataFrom.extract` seemingly does not support regex lookups for keys in the secret store.

**Comment by adambournsonos** [comment]
I put together a bit simpler of a repro using the Fake provider, see:

Fake secret store:
```yaml
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: fake
spec:
  provider:
    fake:
      data:
      - key: "example"
        value: '{"theSecret": "noPeeking"}'
        version: "v1"
```

An ExternalSecret which does not produce a K8s Secret:
```yaml
apiVersion: 'external-secrets.io/v1beta1'
kind: ExternalSecret
metadata:
  name: abourn-test
spec:
  refreshInterval: "30s"
  secretStoreRef:
    name: fake
    kind: ClusterSecretStore
  target:
    name: abourn-test
    creationPolicy: Owner
    template:
      engineVersion: v2
      templateFrom:
      - target: Data
        literal: |
          {{ range $key, $value := . }}
          {{ range $skey, $svalue := fromJson $value }}
          {{$key}}_{{regexReplaceAllLiteral "[^a-zA-Z\d\s_]" $skey "_"}}: {{$svalue}}
          {{ end }}
          {{ end }}
  data:
  - secretKey: myExample
    remoteRef:
      key: example
      version: v1
```
Meanwhile, something like this does result in a K8s Secret being generated:
```yaml
apiVersion: 'external-secrets.io/v1beta1'
kind: ExternalSecret
metadata:
  name: abourn-test
spec:
  refreshInterval: "30s"
  secretStoreRef:
    name: fake
    kind: ClusterSecretStore
  target:
    name: abourn-test
    creationPolicy: Owner
    template:
      engineVersion: v2
      templateFrom:
      - target: Data
        literal: |
          {{ range $key, $value := . }}
          {{ range $skey, $svalue := fromJson $value }}
          {{$key | upper}}-{{$skey | upper}}: {{$svalue}}
          {{ end }}
          {{ end }}
  data:
  - secretKey: myExample
    remoteRef:
      key: example
      version: v1
```
That would produce something like:
```
│ Name:         abourn-test                                                                                                                           │
│ Namespace:    default                                                                                                                               │
│ Labels:       reconcile.external-secrets.io/created-by=b251da1d3ae2592d2b7d85f83fbdc88a                                                             │
│ Annotations:  reconcile.external-secrets.io/data-hash: 1543f8b5c7c50674576708075ee002b1                                                             │
│                                                                                                                                                     │
│ Type:  Opaque                                                                                                                                       │
│                                                                                                                                                     │
│ Data                                                                                                                                                │
│ ====                                                                                                                                                │
│ MYEXAMPLE-THESECRET:  9 bytes # value is "noPeeking"
```

**Comment by moolen** [comment]
After fiddling around a bit i found it: the `\` need to be escaped:

```
{{ range $key, $value := . }}
{{ range $skey, $svalue := fromJson $value }}
{{$key}}_{{regexReplaceAllLiteral "[^a-zA-Z\\d\\s_]" $skey "_"}}: {{$svalue}}
{{ end }}
{{ end }}
```

will yield:

```yaml
apiVersion: v1
data:
  myExample_theSecret: bm9QZWVraW5n # noPeeking
```
