### ISSUE TITLE
unknown field "spec.target.template.stringData"

### ISSUE THREAD

**Issue by kubegurus** [external-secrets/external-secrets#3035]
**Describe the bug**
When working with externalsecrets I wanted to use advance template for stringData.

**To Reproduce**
```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: file-realm-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secret-store
  data:
    - secretKey: elastic-users
      remoteRef:
        key: eck-stack
        property: users
  target:
    template:
      engineVersion: v2
      metadata:
        annotations:
          reloader.stakater.com/match: "true"
      stringData:
        users: |-
          "{{ `{{ .elastic-users }}` }}" 
```

In secret manager I create a key value the following:

```
users: {test:test}
```

**Expected behavior**
Create external secrets and setup kubernetes secrets according to the template.
While the external secrets had been synced the secrets successfully I got the following error

W0118 11:02:37.969303    6007 warnings.go:70] unknown field "spec.target.template.stringData"

Rather having StringData field external secrets had converted it to data
