### ISSUE TITLE
Allow `dataFrom` secret gathering to parse YAML secret (along JSON)

### ISSUE THREAD

**Issue by prune998** [external-secrets/external-secrets#3053]
**Is your feature request related to a problem? Please describe.**
Most of Kubernetes stuff are YAML, and not Json. 
As of now `dataFrom` only work with Json secrets:
```
  dataFrom:
  - extract:
      key: my-secret
```

**Describe the solution you'd like**
Either we should be able to hint the secret as Json or YAML, or both should be tested (json first to keep the same behaviour, then fallback to Yaml, then return an error).

**Describe alternatives you've considered**
I tried using `template` and `| fromyaml` to parse the content of the secret (of a key of the secret) into yaml, but templates work on a per-key value, which means we have to explicitely set the key name in the template (my-key):

```
    template:
      engineVersion: v2
      data: 
        my-key: |
          {{- $myvar := .key | fromYaml -}}
          {{ $myvar.envVars.FEATURE_FLAGS_ID }}
```

What is needed is that the whole secret's key: values are listed in the data.

**Additional context**

I tested adding yaml after json in the GCP provider at `pkg/provider/gcp/secretmanager/client.go`, like:

```go
func (c *Client) GetSecretMap(ctx context.Context, ref esv1beta1.ExternalSecretDataRemoteRef) (map[string][]byte, error) {

	if c.smClient == nil || c.store.ProjectID == "" {
		return nil, fmt.Errorf(errUninitalizedGCPProvider)
	}

	data, err := c.GetSecret(ctx, ref)
	if err != nil {
		return nil, err
	}

	kv := make(map[string]json.RawMessage)
	err = json.Unmarshal(data, &kv)
	if err != nil {
		log.V(1).Error(err, "json unmarshal failed, trying yaml...", "name", ref.Key)
		kv := make(map[interface{}]interface{})
		err = yaml.Unmarshal(data, &kv)
		if err != nil {
			log.V(1).Error(err, "yaml and json unmarshal failed, giving up", "name", ref.Key, "data", string(data))
			return nil, fmt.Errorf(errJSONSecretUnmarshal, err)
		}
		log.V(1).Error(err, "yaml succeded...", "name", ref.Key, "data", string(data))
...
```

this is working, even if moving this parsing out of the providers would be better...

**Comment by moolen** [comment]
crossreference slack thread: https://kubernetes.slack.com/archives/C017BF84G2Y/p1705440846155629

You can use `templateFrom` with `target: Data` that lets you render keys dynamically

```yaml
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: fake
spec:
  provider:
    fake:
      data:
        - key: foo
          value: |
            {
              "secrets": [
                {
                  "_id": "abc123",
                  "environment": "dev",
                  "secretComment": "Lorem ipsum",
                  "secretKey": "STRIPE_KEY",
                  "secretValue": "abc123",
                  "version": 1,
                  "workspace": "abc123"
                },
                {
                  "_id": "xxx666",
                  "environment": "not-dev",
                  "secretComment": "foobar",
                  "secretKey": "OTHER_KEY",
                  "secretValue": "xxx666",
                  "version": 42,
                  "workspace": "abc123"
                }
              ]
            }
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example
spec:
  refreshInterval: "5s"
  secretStoreRef:
    kind: Fake
    name: fake
  target:
    name: test-secret
    template:
      templateFrom:
        - target: Data
          literal: |
            {{- $payload := .foo | fromJson }}
            fart: '{{ $payload.secrets | toJson }}'
            {{- range $payload.secrets }}
            {{ .secretKey }}: '{{ .secretValue }}'
            {{- end }}
  data:
  - remoteRef:
      key: foo
    secretKey: foo


```

**Comment by edwardccg** [comment]
Thank you for the reference of `templateFrom`. I have a usecase to sync the cacerts which store in yaml format in secret provider. Following are working as expected, it'd be the best if `dataFrom` can support yaml without these.

```yaml
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: fake
spec:
  provider:
    fake:
      data:
        - key: some-multivalue-secret
          value: |
            ca-cert.pem: |-
              -----BEGIN CERTIFICATE-----
              ca-cert content
              -----END CERTIFICATE-----
            ca-key.pem: |-
              -----BEGIN PRIVATE KEY-----
              ca-key content
              -----END PRIVATE KEY-----
            cert-chain.pem: |-
              -----BEGIN CERTIFICATE-----
              cert-chain content
              -----END CERTIFICATE-----
            root-cert.pem: |-
              -----BEGIN CERTIFICATE-----
              root-cert content
              -----END CERTIFICATE-----
            some-extra-key: some-extra-value
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: some-multivalue-secret
spec:
  secretStoreRef:
    kind: Fake
    name: fake
  target:
    name: some-multivalue-secret
    template:
      engineVersion: v2
      templateFrom:
        - target: Data
          literal: "{{ .data }}"
  data:
    - remoteRef:
        key: some-multivalue-secret
      secretKey: data

```

Results:
```shell
$ k get secrets some-multivalue-secret -o yaml | yq '.data | map_values(@base64d)'
ca-cert.pem: |-
  -----BEGIN CERTIFICATE-----
  ca-cert content
  -----END CERTIFICATE-----
ca-key.pem: |-
  -----BEGIN PRIVATE KEY-----
  ca-key content
  -----END PRIVATE KEY-----
cert-chain.pem: |-
  -----BEGIN CERTIFICATE-----
  cert-chain content
  -----END CERTIFICATE-----
root-cert.pem: |-
  -----BEGIN CERTIFICATE-----
  root-cert content
  -----END CERTIFICATE-----
some-extra-key: some-extra-value
```
