### ISSUE TITLE
Values are not being replaced in the template

### ISSUE THREAD

**Issue by asshutossh** [external-secrets/external-secrets#3071]
**Describe the bug**
The secrets are not injected into the secret that needs to be created. 

**To Reproduce**
1. provide all relevant manifests
2. provide the Kubernetes and ESO version

```

oc version                                                         
Client Version: 4.14.6
Kustomize Version: v5.0.1
Server Version: 4.13.13
Kubernetes Version: v1.26.7+c7ee51f
```

Created a config map 

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: ntx-cred-config
  namespace: test
data: 
  credentials: |
	  [{"type":"basic_auth","data":{"prismCentral":{"username": {{ .username }},"password":"{{ .password }}" },"prismElements":null}}]  

```

Used this in an external secret resource:

```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: template-just-password
  namespace: test
spec:
  # ...
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.esstore }}
    kind: ClusterSecretStore
  target:
    name: secret-to-be-created
    # this is how the Kind=Secret will look like
    template:
      engineVersion: v2
      templateFrom:
      - configMap:
          # name of the configmap to pull in
          name: ntx-cred-config
          # here you define the keys that should be used as template
          items:
          - key: credentials
  data:
  - secretKey: user
    remoteRef:
      key: "ocp/new-svc-account" #AWS Secrets Manager secret name
      property: "username"
  - secretKey: password
    remoteRef:
      key: "ocp/new-svc-account"
      property: "password"
     
```   

**Expected behavior**
Username and password fields are empty
```

oc -n test get secrets secret-to-be-created -o jsonpath='{.data.*}' | base64 --decode
[{"type":"basic_auth","data":{"prismCentral":{"username": ,"password":"" },"prismElements":null}}]
```

Despite the creation of the external secret successfully:

`
template-just-password                 aws-secrets-manager   1h                 SecretSynced        True
`

```
$ oc -n test describe externalsecrets.external-secrets.io template-just-password 
Name:         template-just-password
Namespace:    test
Labels:       app.kubernetes.io/managed-by=Helm
Annotations:  meta.helm.sh/release-name: es
              meta.helm.sh/release-namespace: default
API Version:  external-secrets.io/v1beta1
Kind:         ExternalSecret
Metadata:
  Creation Timestamp:  2024-01-23T09:11:17Z
  Generation:          1
  Resource Version:    122377050
  UID:                 4d23dbe6-90b7-4eae-bbad-93d4e90d8dce
Spec:
  Data:
    Remote Ref:
      Conversion Strategy:  Default
      Decoding Strategy:    None
      Key:                  ocp/new-svc-account
      Metadata Policy:      None
      Property:             username
    Secret Key:             user
    Remote Ref:
      Conversion Strategy:  Default
      Decoding Strategy:    None
      Key:                  ocp/new-svc-account
      Metadata Policy:      None
      Property:             password
    Secret Key:             password
  Refresh Interval:         1h
  Secret Store Ref:
    Kind:  ClusterSecretStore
    Name:  aws-secrets-manager
  Target:
    Creation Policy:  Owner
    Deletion Policy:  Retain
    Name:             secret-to-be-created
    Template:
      Engine Version:  v2
      Merge Policy:    Replace
      Template From:
        Config Map:
          Items:
            Key:          credentials
            Template As:  Values
          Name:           ntx-cred-config
        Target:           Data
Status:
  Binding:
    Name:  secret-to-be-created
  Conditions:
    Last Transition Time:   2024-01-23T09:11:17Z
    Message:                Secret was synced
    Reason:                 SecretSynced
    Status:                 True
    Type:                   Ready
  Refresh Time:             2024-01-23T09:11:17Z
  Synced Resource Version:  1-a25e66e5085e7c6c67772bff62c1b506
Events:
  Type    Reason   Age              From              Message
  ----    ------   ----             ----              -------
  Normal  Updated  3s (x2 over 3s)  external-secrets  Updated Secret

 **oc -n test get secrets secret-to-be-created -o jsonpath='{.data.*}' | base64 --decode**
[{"type":"basic_auth","data":{"prismCentral":{"username": ,"password":"" },"prismElements":null}}]

$ oc -n test describe secrets secret-to-be-created                                     
Name:         secret-to-be-created
Namespace:    test
Labels:       reconcile.external-secrets.io/created-by=337276e7b34752d3c425abdcae386218
Annotations:  reconcile.external-secrets.io/data-hash: ad27d78778bff54e9d228ab648f9c095

Type:  Opaque

Data
====
credentials:  99 bytes
```

**Additional context**
Secrets are stored in AWS Secrets Manager and they are can be successfully be fetched. 

Once the above works, I will use externalsecrets to fetch secrets to patch an existing secret which is stored as follows. The credentials need to be replaced with new ones.:

```

**oc -n openshift-machine-api get secrets nutanix-credentials -o jsonpath='{.data.*}' | base64 --decode**
[{"type":"basic_auth","data":{"prismCentral":{"username":"svc_ocp","password":"<secret>."},"prismElements":null}}]% 
```

This is also stored in JSON format so decided to create a cm and use[templatefrom]( https://external-secrets.io/v0.4.4/guides-templating/#templatefrom.)

putting the template inline also results in the same issue.

```
 apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: template-secret-to-be-created
  namespace: test
spec:
  # ...
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.esstore }}
    kind: ClusterSecretStore
  target:
    name: secret-to-be-created
    # this is how the Kind=Secret will look like
    template:
      engineVersion: v2
      data:
        credentials: |
          type: basic_auth
          data:
            prismCentral:
              username: {{ .user }}
              password: {{ .pass }} 
              prismElements: null 
  data:  
  - secretKey: user
    remoteRef:
      key: "ocp/new-svc-account" #AWS Secrets Manager secret name
      property: "username"
  - secretKey: pass
    remoteRef:
      key: "ocp/new-svc-account"
      property: "password"
        
```

**Comment by lure8225** [comment]
maybe this is related? https://github.com/external-secrets/external-secrets/issues/3150

**Comment by gusfcarvalho** [comment]
hi @asshutossh - can you confirm the configmap:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: ntx-cred-config
  namespace: test
  ```
  in the cluster actually contains the templated `{{}}`  keys in it? Many times, if you install this configMap with tools like e.g. helm - helm will template it already and make that value be empty.
