### ISSUE TITLE
Invalid certs when using cert-manager with CA issuer

### ISSUE THREAD

**Issue by sestegra** [external-secrets/external-secrets#3080]
**Describe the bug**
external-secrets version v0.9.11

When deploying ESO using cert-manager to replace cert controller, if cert-manager issuer is CA issuer, the external-secrets-webhook POD is unhealthy due to following error.

```
{"level":"info","ts":1706300660.7643616,"logger":"setup","msg":"validating certs"}
{"level":"error","ts":1706300660.7648668,"logger":"setup","msg":"invalid certs. retrying...","error":"x509: certificate signed by unknown authority","stacktrace":"github.com/external-secrets/external-secrets/cmd.waitForCerts\n\t/home/runner/work/external-secrets/external-secrets/cmd/webhook.go:214\ngithub.com/external-secrets/external-secrets/cmd.glob..func3\n\t/home/runner/work/external-secrets/external-secrets/cmd/webhook.go:83\ngithub.com/spf13/cobra.(*Command).execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115\ngithub.com/spf13/cobra.(*Command).Execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039\ngithub.com/external-secrets/external-secrets/cmd.Execute\n\t/home/runner/work/external-secrets/external-secrets/cmd/root.go:254\nmain.main\n\t/home/runner/work/external-secrets/external-secrets/main.go:21\nruntime.main\n\t/opt/hostedtoolcache/go/1.21.5/x64/src/runtime/proc.go:267"}
```

**To Reproduce**
1. Create cert-manger issuer with CA issuer using intermediate CA. See: https://cert-manager.io/docs/configuration/ca/
2. Deploy ESO with following values.yaml
```
webhook:
  certManager:
    enabled: true
    addInjectorAnnotations: true
    cert:
      create: true
      issuerRef:
        group: cert-manager.io
        kind: ClusterIssuer
        name: ca-issuer

certController:
  create: false
```

**Expected behavior**
external-secrets-webhook should be healthy.

**Screenshots**
N/A

**Additional context**
With SelfSigned issuer, the deployement works well. But my context is using CA issuer from cert-manager.
