### ISSUE TITLE
Cannot make ClusterSecretStore to remote vault server work

### ISSUE THREAD

**Issue by gilShin** [external-secrets/external-secrets#3093]
**Describe the bug**
When I create a ClusterSecretStore to connect to a remote Vault server (using a token that is being held in a k8s secret) I get an error 403 forbidden while trying to reach v1/auth/token/lookup-self

**To Reproduce**
1. Create a generic secret for the root token of the Vault server
2. Create a ClusterSecretStore that uses this secret and has the URL of the Vault server
```
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-server
spec:
  provider:
    vault:
      server: "https://<vault URL>/"
      path: "kv"
      auth:
        tokenSecretRef:
          name: "vault-token"
          namespace: "default"
          key: "token"
```

**Expected behavior**
ClusterSecretStore should be in OK status and validated

**Screenshots**
```
Events:
  Type     Reason            Age                 From                  Message
  ----     ------            ----                ----                  -------
  Warning  ValidationFailed  19s (x21 over 47m)  cluster-secret-store  invalid vault credentials: Error making API request.

URL: GET https://<vault URL>/v1/auth/token/lookup-self
Code: 403. Raw Message:

<html>\r
<head><title>403 Forbidden</title></head>\r
<body>\r
<center><h1>403 Forbidden</h1></center>\r
<hr><center>nginx</center>\r
</body>\r
</html>
```

**Additional context**
When I run curl command on my laptop while adding the same root token to the header, I get 200OK status. If I use an invalid token, I get 403 error.
My assumption is that the operator does not read the secret of the token or getting a wrong value of the token
