### ISSUE TITLE
"Secret does not exist" error when it clearly exists

### ISSUE THREAD

**Issue by stea-uw** [external-secrets/external-secrets#3094]
I'm getting the "secret does not exist" error below, but the secret clearly exists.

Error:

```bash
> kubectl describe externalsecret/mytldsecret
  Secret Store Ref:
    Kind:  ClusterSecretStore
    Name:  mystore
Status:
  Conditions:
    Message:               could not get secret data from provider
    Reason:                SecretSyncedError
    Status:                False
    Type:                  Ready
Events:
  Type     Reason        Age                   From              Message
  ----     ------        ----                  ----              -------
  Warning  UpdateFailed  7m11s (x22 over 79m)  external-secrets  error retrieving secret at .data[0], key: prod/mytlssecret, err: Secret does not exist
```

Secret exists:

```bash
> kubectl describe clustersecretstore/mystore
Name: mystore
Spec:
  Provider:
    Fake:
      Data:
        Key:  prod/mytlssecret
        Value Map:
          cert:  "-----BEGIN CERTIFICATE REQUEST-----\nabcd<snip>"
          key: "-----BEGIN PRIVATE KEY-----\nabcd<snip>"
```

Running on Rancher desktop MacOS

Why is externalsecrets not finding my secret? How do I debug this?

**Comment by shuheiktgw** [comment]
Hi @stea-uw, thanks for reporting the issue!
Could you share the output by executing `kubectl get externalsecret/mytldsecret -o yaml`? I feel something is missing.

**Comment by stea-uw** [comment]
```
> kubectl get externalsecret/mytlssecret
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"external-secrets.io/v1beta1","kind":"ExternalSecret","metadata":{"annotations":{},"name":"mytlssecret","namespace":"default"},"spec":{"data":[{"remoteRef":{"key":"prod/mytlssecret","property":"cert"},"secretKey":"tls.crt"},{"remoteRef":{"key":"prod/mytlssecret","property":"key"},"secretKey":"tls.key"}],"secretStoreRef":{"kind":"ClusterSecretStore","name":"mystore"}}}
  creationTimestamp: "2024-01-31T22:04:51Z"
  generation: 1
  name: mytlssecret
  namespace: default
  resourceVersion: "1461"
  uid: 380948f0-87ba-4399-93d4-e213e29fda6b
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: prod/mytlssecret
      metadataPolicy: None
      property: cert
    secretKey: tls.crt
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: prod/mytlssecret
      metadataPolicy: None
      property: key
    secretKey: tls.key
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: mystore
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
status:
  conditions:
  - lastTransitionTime: "2024-01-31T22:04:51Z"
    message: could not get secret data from provider
    reason: SecretSyncedError
    status: "False"
    type: Ready
```

**Store config:**
```
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: mystore
spec:
  provider:
    fake:
      data:
      - key: prod/myregularsecret
        valueMap:
          username: fake
          password: fake
      - key: prod/mytlssecret
        valueMap:
          cert: "-----BEGIN (FAKE) CERTIFICATE REQUEST-----\nMIIM4jCCC8oCAQAwSjEVMBMGA1UEAwwMKi5nb29nbGUuY29tMQswCQYDVQQGEwJV\nUzETMBEGA1UECAwKV2FzaGluZ3RvbjEPMA0GA1UEBwwGVGFjb21hMIIBIjANBgkq\nhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsLwiqE2JuWvKBU/Y15bRNsvNblWWYniQ\nBmnrXikaSWg88ZCZsH9ssPb6rafFzB6RMahJfkgGwfwoJOXkdHB2jhyf6Z2ipds+\nV1DivyjB9ejCcSc5yRnpOTVnVudCeX9A1dckpJwLPS2vU//XXPT9B0oIC3E/Enqq\nlX3TDVzSd8JCX+xCHMhamK/e9uvmAh+mT2LxjPd9vFPCyz8WxNtm17JFKjQsXZtr\n4hGKGAL1sImMxfFHBuwKymBeKWbvTXPeFzn5A9XsTU9Px/TsShY4HXNoRsLB9nK5\nxy0nJ/H8jQA6XtZKsjPPJutvBXoOI1eev8YVayN/BH8aotJWB4yLbQIDAQABoIIK\nUTCCCk0GCSqGSIb3DQEJDjGCCj4wggo6MA4GA1UdDwEB/wQEAwIHgDATBgNVHSUE\nDDAKBggrBgEFBQcDATAMBgNVHRMBAf8EAjAAMIIKAwYDVR0RBIIJ+jCCCfaCDCou\nZ29vZ2xlLmNvbYIWKi5hcHBlbmdpbmUuZ29vZ2xlLmNvbYIJKi5iZG4uZGV2ghUq\nLm9yaWdpbi10ZXN0LmJkbi5kZXaCEiouY2xvdWQuZ29vZ2xlLmNvbYIYKi5jcm93\nZHNvdXJjZS5nb29nbGUuY29tghgqLmRhdGFjb21wdXRlLmdvb2dsZS5jb22CCyou\nZ29vZ2xlLmNhggsqLmdvb2dsZS5jbIIOKi5nb29nbGUuY28uaW6CDiouZ29vZ2xl\nLmNvLmpwgg4qLmdvb2dsZS5jby51a4IPKi5nb29nbGUuY29tLmFygg8qLmdvb2ds\nZS5jb20uYXWCDyouZ29vZ2xlLmNvbS5icoIPKi5nb29nbGUuY29tLmNvgg8qLmdv\nb2dsZS5jb20ubXiCDyouZ29vZ2xlLmNvbS50coIPKi5nb29nbGUuY29tLnZuggsq\nLmdvb2dsZS5kZYILKi5nb29nbGUuZXOCCyouZ29vZ2xlLmZyggsqLmdvb2dsZS5o\ndYILKi5nb29nbGUuaXSCCyouZ29vZ2xlLm5sggsqLmdvb2dsZS5wbIILKi5nb29n\nbGUucHSCEiouZ29vZ2xlYWRhcGlzLmNvbYIPKi5nb29nbGVhcGlzLmNughEqLmdv\nb2dsZXZpZGVvLmNvbYIMKi5nc3RhdGljLmNughAqLmdzdGF0aWMtY24uY29tgg9n\nb29nbGVjbmFwcHMuY26CESouZ29vZ2xlY25hcHBzLmNughFnb29nbGVhcHBzLWNu\nLmNvbYITKi5nb29nbGVhcHBzLWNuLmNvbYIMZ2tlY25hcHBzLmNugg4qLmdrZWNu\nYXBwcy5jboISZ29vZ2xlZG93bmxvYWRzLmNughQqLmdvb2dsZWRvd25sb2Fkcy5j\nboIQcmVjYXB0Y2hhLm5ldC5jboISKi5yZWNhcHRjaGEubmV0LmNughByZWNhcHRj\naGEtY24ubmV0ghIqLnJlY2FwdGNoYS1jbi5uZXSCC3dpZGV2aW5lLmNugg0qLndp\nZGV2aW5lLmNughFhbXBwcm9qZWN0Lm9yZy5jboITKi5hbXBwcm9qZWN0Lm9yZy5j\nboIRYW1wcHJvamVjdC5uZXQuY26CEyouYW1wcHJvamVjdC5uZXQuY26CF2dvb2ds\nZS1hbmFseXRpY3MtY24uY29tghkqLmdvb2dsZS1hbmFseXRpY3MtY24uY29tghdn\nb29nbGVhZHNlcnZpY2VzLWNuLmNvbYIZKi5nb29nbGVhZHNlcnZpY2VzLWNuLmNv\nbYIRZ29vZ2xldmFkcy1jbi5jb22CEyouZ29vZ2xldmFkcy1jbi5jb22CEWdvb2ds\nZWFwaXMtY24uY29tghMqLmdvb2dsZWFwaXMtY24uY29tghVnb29nbGVvcHRpbWl6\nZS1jbi5jb22CFyouZ29vZ2xlb3B0aW1pemUtY24uY29tghJkb3VibGVjbGljay1j\nbi5uZXSCFCouZG91YmxlY2xpY2stY24ubmV0ghgqLmZscy5kb3VibGVjbGljay1j\nbi5uZXSCFiouZy5kb3VibGVjbGljay1jbi5uZXSCDmRvdWJsZWNsaWNrLmNughAq\nLmRvdWJsZWNsaWNrLmNughQqLmZscy5kb3VibGVjbGljay5jboISKi5nLmRvdWJs\nZWNsaWNrLmNughFkYXJ0c2VhcmNoLWNuLm5ldIITKi5kYXJ0c2VhcmNoLWNuLm5l\ndIIdZ29vZ2xldHJhdmVsYWRzZXJ2aWNlcy1jbi5jb22CHyouZ29vZ2xldHJhdmVs\nYWRzZXJ2aWNlcy1jbi5jb22CGGdvb2dsZXRhZ3NlcnZpY2VzLWNuLmNvbYIaKi5n\nb29nbGV0YWdzZXJ2aWNlcy1jbi5jb22CF2dvb2dsZXRhZ21hbmFnZXItY24uY29t\nghkqLmdvb2dsZXRhZ21hbmFnZXItY24uY29tghhnb29nbGVzeW5kaWNhdGlvbi1j\nbi5jb22CGiouZ29vZ2xlc3luZGljYXRpb24tY24uY29tgiQqLnNhZmVmcmFtZS5n\nb29nbGVzeW5kaWNhdGlvbi1jbi5jb22CFmFwcC1tZWFzdXJlbWVudC1jbi5jb22C\nGCouYXBwLW1lYXN1cmVtZW50LWNuLmNvbYILZ3Z0MS1jbi5jb22CDSouZ3Z0MS1j\nbi5jb22CC2d2dDItY24uY29tgg0qLmd2dDItY24uY29tggsybWRuLWNuLm5ldIIN\nKi4ybWRuLWNuLm5ldIIUZ29vZ2xlZmxpZ2h0cy1jbi5uZXSCFiouZ29vZ2xlZmxp\nZ2h0cy1jbi5uZXSCDGFkbW9iLWNuLmNvbYIOKi5hZG1vYi1jbi5jb22CFGdvb2ds\nZXNhbmRib3gtY24uY29tghYqLmdvb2dsZXNhbmRib3gtY24uY29tgh4qLnNhZmVu\ndXAuZ29vZ2xlc2FuZGJveC1jbi5jb22CDSouZ3N0YXRpYy5jb22CFCoubWV0cmlj\nLmdzdGF0aWMuY29tggoqLmd2dDEuY29tghEqLmdjcGNkbi5ndnQxLmNvbYIKKi5n\ndnQyLmNvbYIOKi5nY3AuZ3Z0Mi5jb22CECoudXJsLmdvb2dsZS5jb22CFioueW91\ndHViZS1ub2Nvb2tpZS5jb22CCyoueXRpbWcuY29tggthbmRyb2lkLmNvbYINKi5h\nbmRyb2lkLmNvbYITKi5mbGFzaC5hbmRyb2lkLmNvbYIEZy5jboIGKi5nLmNuggRn\nLmNvggYqLmcuY2+CBmdvby5nbIIKd3d3Lmdvby5nbIIUZ29vZ2xlLWFuYWx5dGlj\ncy5jb22CFiouZ29vZ2xlLWFuYWx5dGljcy5jb22CCmdvb2dsZS5jb22CEmdvb2ds\nZWNvbW1lcmNlLmNvbYIUKi5nb29nbGVjb21tZXJjZS5jb22CCGdncGh0LmNuggoq\nLmdncGh0LmNuggp1cmNoaW4uY29tggwqLnVyY2hpbi5jb22CCHlvdXR1LmJlggt5\nb3V0dWJlLmNvbYINKi55b3V0dWJlLmNvbYIUeW91dHViZWVkdWNhdGlvbi5jb22C\nFioueW91dHViZWVkdWNhdGlvbi5jb22CD3lvdXR1YmVraWRzLmNvbYIRKi55b3V0\ndWJla2lkcy5jb22CBXl0LmJlggcqLnl0LmJlghphbmRyb2lkLmNsaWVudHMuZ29v\nZ2xlLmNvbYIbZGV2ZWxvcGVyLmFuZHJvaWQuZ29vZ2xlLmNughxkZXZlbG9wZXJz\nLmFuZHJvaWQuZ29vZ2xlLmNughhzb3VyY2UuYW5kcm9pZC5nb29nbGUuY26CGmRl\ndmVsb3Blci5jaHJvbWUuZ29vZ2xlLmNughh3ZWIuZGV2ZWxvcGVycy5nb29nbGUu\nY24wDQYJKoZIhvcNAQELBQADggEBAIHQcBlK+PaTD8zMAf/RZR9g3kvUDOKl8sW2\nkc7wGGRrEAe6bouJP8Z7xkaf5mXOK0haEH5hFS8pxbidJ6+7xGLEhxQWHPtfOsCX\nsQ8Yrp/TUp3H5nOQIiG9kRTGAp+jZIYtJTuMT/aiGtz/BxA8k3zfKE/2zOq4ymES\nFfMOKAu6CfJu22l8qgLBrno8/F8iyCkkbisis3Xy8xY3S05jMf82xYhT6brdr96N\nDs42SFt4bLhQyHak5xBMm0GJ1xCx3+7zCRv/ig7t0w3q7hxCF00IffdBtzrfkNVS\n0WI3/T+aRKJpGPBPPHr85Xj/R6fmxjHjqIuMr66s9cBWJ9wK94s=\n-----END (FAKE) CERTIFICATE REQUEST-----"
          key: "-----BEGIN (FAKE) PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCwvCKoTYm5a8oF\nT9jXltE2y81uVZZieJAGaeteKRpJaDzxkJmwf2yw9vqtp8XMHpExqEl+SAbB/Cgk\n5eR0cHaOHJ/pnaKl2z5XUOK/KMH16MJxJznJGek5NWdW50J5f0DV1ySknAs9La9T\n/9dc9P0HSggLcT8SeqqVfdMNXNJ3wkJf7EIcyFqYr9726+YCH6ZPYvGM9328U8LL\nPxbE22bXskUqNCxdm2viEYoYAvWwiYzF8UcG7ArKYF4pZu9Nc94XOfkD1exNT0/H\n9OxKFjgdc2hGwsH2crnHLScn8fyNADpe1kqyM88m628Feg4jV56/xhVrI38Efxqi\n0lYHjIttAgMBAAECggEBAJGCdG5pWIlHS89PzFLEI4CgD4VWBjkQ1lPRhS3DXZcu\nsW6aBU+huhWBYybyyRGj4RsnWUsVdirktxCaDpwntBSRUMABP1aayhsNx4Jnxjn2\n55BOIW+HW9P0Oh78zGhH81OcjNjSeRZntMDOFby9IE6OD02Mccd/I09thwSrdcWO\n1r3LleqGrs5aZsUDREOPDuEfjgP7YJO0RE95iD3yl0zGUQSM2NRv4uEwdWv2auD4\njA36oeSMo/TwMJfXgvdaBEphQqOyJA4Mai7NMK8hnl8/6hA+q0N+DG6lcgpagoYM\nmq78wcQ60N4IB3QBi44ZI2iIxdfFWQixRtDcczec+SkCgYEA2sf+wZ9J3lb4Jifr\nMrkNDgZhJV3JLUX1cmvjRXqKUrznw4q6F6mdZTtdfq58KQkBKJBe37Cef4jL8laH\nyzqHU4Z9SEdw1s/9y6eS602/Ht3JrTuiRSuLTSLAXtihlwEMLn8RHIveGV1wg4rs\nhyrqvcjUTrXv8MYetqIxGgIXMrMCgYEAzs0BwxKxsMDwR5mK1Ue1nvR6aiNZ50rN\nEWCOFNWg05VZ2wXcwiwgm0xwW42anh+7HTEvTXcCK+oBoXbPaf5FhSBaZmBs0/o/\nHbn2iRLMhpDUUeWJvYGAXcA/MdiMgSM9BZDh6yAPVeN5sr6hdLctNfoVmrcCE69x\nv4Mr7Fyt2V8CgYAIJhTWD2HH90NM4IXBIOVclV4+7wxUNFvdBCm158eJJ2IWhW9C\n/F1RbPGhi0wylxRE94OhH0n4BBdckl6Cck6iDMtTyt1oEt0oHbi6LO4mbypY2nTD\n0Mhieh3iKn1yS2axwKfZgVgnZ7SOIbmHm1Cc+wL1X49tT2PLd6UOi+9jQwKBgQC7\nq0uYDdT3RIBJWcul9aeakt6sh1xFC5rB1E/cFGoY2QZsPwuxon4MsPed/gl8yery\nePomYIO1+mx0bO+ZjsjkIRIoqgTY8dZpUaOrjUXSMIidsaKoOWeWrKoswAnx/1qX\nPH3o9HU2SnLchSbcVodO3p7Qgpf96U9ertkjbI/QHQKBgDifHV1YjwgDOevQh/J5\no/ZFUs1rfpWaK/JXX+TlfzyJ+tVsYHoBPzh0YMtynQGZH9L7NaoJFIavOy4tPTW1\nkkVI0txN3RZuCN/ZUkJ7TuzhKRjr2ALVWdplXA/PrXAMvF5vRYfdz4fARnYUPWen\nprTjmn0FF8qwyEMlH+QoBpbR\n-----END (FAKE) PRIVATE KEY-----"
```

**Comment by shuheiktgw** [comment]
@stea-uw Thanks for sharing the specs! Now I see where the confusion comes from. In short, `valueMap` does not work with `property`.  Instead, if you want to use `property`, please use the `value` field. 

For example:
```
spec:
  provider:
    fake:
      data:
      - key: prod/mytlssecret
        value: '{"cert":"YOURCERT","key":"YOURKEY"}'
```

To avoid this type of confusion, we deprecated `valueMap` lately. Please take a look at [the latest fake doc](https://external-secrets.io/main/provider/fake/) for more details.
