### ISSUE TITLE
Manage multiple properties of one 1Password entry

### ISSUE THREAD

**Issue by Zachu** [external-secrets/external-secrets#3130]
**Is your feature request related to a problem? Please describe.**
I would like to be able to manage multiple properties in one `onepassword` `PushSecret` manifest. My initial use case is to synchronize a [Kubernetes TLS Secret](https://kubernetes.io/docs/concepts/configuration/secret/#tls-secrets) into 1Password.

**Describe the solution you'd like**
With following manifests I would want to have one secret entry in 1Password having properties `foo` and `bar` set to the correct values:
```yaml
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: 1pass
spec:
  provider:
    onepassword:
      connectHost: http://onepassword-connect.1password.svc.cluster.local:8080
      vaults:
        Development: 1
      auth:
        secretRef:
          connectTokenSecretRef:
            name: ismtip-1pass-token
            key: token
---
apiVersion: v1
kind: Secret
metadata:
  name: foo-secret
stringData:
  foo: asd
  bar: das
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: foo-secret
spec:
  refreshInterval: 60s
  secretStoreRefs:
    - name: 1pass
      kind: SecretStore
  selector:
    secret:
      name: foo-secret
  data:
    - match:
        secretKey: foo
        remoteRef:
          remoteKey: test-foo-secret
          property: foo
    - match:
        secretKey: bar
        remoteRef:
          remoteKey: test-foo-secret
          property: bar
```

Instead I am getting two entries in 1Password with the exact same name `test-foo-secret` and after the second refresh the `PushSecret` goes into `Errored` state due to having two entries with the same name.

**Describe alternatives you've considered**
I tried separating these into two different entries (which isn't nice solution in my opinion) but ran across https://github.com/external-secrets/external-secrets/issues/3129 which is preventing me actually using the `onepassword` `PushSecret` completely :/

**Comment by onedr0p** [comment]
Confirmed on my end...

```yaml
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: thanos
spec:
  secretStoreRefs:
    - name: onepassword-connect
      kind: ClusterSecretStore
  selector:
    secret:
      name: thanos-bucket-v2
  data:
    - match:
        secretKey: AWS_ACCESS_KEY_ID
        remoteRef:
          remoteKey: thanos
    - match:
        secretKey: AWS_SECRET_ACCESS_KEY
        remoteRef:
          remoteKey: thanos
```

```
  Normal   Synced   2s                   pushsecret  PushSecret synced successfully

  Warning  Errored  1s (x3 over 3s)      pushsecret  set secret failed: could not write remote ref AWS_SECRET_ACCESS_KEY to target secretstore onepassword-connect: error updating 1Password Item: status 400: Unable to update item "thanos" in Vault "xyz"
```

**Comment by onedr0p** [comment]
Pinging @bthuilot since they are the author of the original PR. Maybe they can shed some insight.

**Comment by acelinkio** [comment]
PushSecret functions and successfully created a secret in 1password, however the status is error.  

```yaml
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: wildcard-production
  namespace: cilium-secrets
spec:
  refreshInterval: 10s
  secretStoreRefs:
    - name: 1password
      kind: ClusterSecretStore
  selector:
    secret:
      name: wildcard-production
  data:
    - match:
        secretKey: tls.crt
        remoteRef:
          remoteKey: tls.crt
    - match:
        secretKey: tls.key
        remoteRef:
          remoteKey: tls.key
```

and throws the following failures relating to `token does not have permission to perform create on vault`.  This is using an Secrets Automation (https://developer.1password.com/docs/secrets-automation/) access token that has full access to my specified vault.

```log
{"level":"error","ts":1707615832.498571,"msg":"Reconciler error","controller":"pushsecret","controllerGroup":"external-secrets.io","controllerKind":"PushSecret","PushSecret":{"name":"wildcard-production","namespace":"cilium-secrets"},"namespace":"cilium-secrets","name":"wildcard-production","reconcileID":"0a8145f9-206e-414a-9b24-a76cb79e14f2","error":"could not write remote ref tls.crt to target secretstore 1password: error creating 1Password Item: status 403: Authorization: token does not have permission to perform create on vault h2cklnzoiixetlponscqvqcydm","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.0/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.0/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.0/pkg/internal/controller/controller.go:227"}
```
