### ISSUE TITLE
Extra character in field using bitarden-fields

### ISSUE THREAD

**Issue by Ulrar** [external-secrets/external-secrets#3133]
**Describe the bug**
I'm trying to use bitwarden-fields as described here : https://external-secrets.io/latest/examples/bitwarden/
Somehow the password in k8s ends up with an extra '%' (as rendered by cat -e, it does look highlighted in my terminal, not sure what that means) at the end.
In the base64 of the secret yaml that looks like the last character flipping from 'K' (good) to '=' (bad).

I'm using the latest vaultwarden as the server, and I confirmed using `bw get item` that the password returned by the cli doesn't contain any weird characters, it's alphanumerical.

**To Reproduce**
```
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: my-secret
spec:
  secretStoreRef:
    name: bitwarden-fields
    kind: ClusterSecretStore
  target:
    name: my-super-secret
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        my-password: |-
          {{ .my_password }}
  data:
    - secretKey: my_password
      remoteRef:
        key: xxxx-xxxx-xxxx-xxxx...
        property: my_password
        decodingStrategy: None
```

**Expected behavior**
I expect the generated secret to not contain any extra characters at the end.

Is there anything I may be doing wrong here, causing the templating to add a character ?
I tried messing with the spec to avoid advanced templating and let it map the key directly but same behavior.

- Talos v1.6.4
- Kubernetes v1.29.1
- External Secrets 0.9.12 (installed through argocd's lovely plugin, using the official helm chart)
- ghcr.io/charlesthomas/bitwarden-cli:2024.1.0
- Vaultwarden 2024.1.2 
Thanks

EDIT: It's interesting, it looks like some other secrets (manually created) already have this so I wonder if it might be an expected artifact of kubectl create secret, maybe ? Not sure what the difference is between the ones that have it and the ones that don't.
