### ISSUE TITLE
Secret not deployed although logs and ExternalSecret claim it's synced

### ISSUE THREAD

**Issue by lure8225** [external-secrets/external-secrets#3150]
**Describe the bug**

I was trying to sync a secret from vault using a template but the actual secret never did appear in the namespace. 

When I limited the template just to some printf everything worked but as sun as I referenced the secretKey containing a "-" it silently fails. after naming the secretKey differently it works absolutely fine.

It seems that currently the secretKey can not contain "-" (not sure about "/").

**To Reproduce**
1. Create external secret using "-" in secretKey
2. Reference the secretKey containing "-" in the template (I used the dockerconfiigjson example)

**Expected behavior**
Secret gets created and is in sync
(If "-" really is not allowed it should cause an error when syncing and it should be mentioned clearly in documentation)

**Additional context**
Fails silently, no secret created, logs in externalsecrets-controller just report it has ben sucessfuly synced and so does the status in the ExternalSecret resource
``` YAML
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pull-secret-registry-someuser
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: pull-secret-registry-someuser
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: '{"auths": {"some.registry.com": { "auth": "{{ printf "someuser:%s" .someuser-pat | b64enc }}"} } }'
  data:
    - secretKey: someuser-pat
      remoteRef:
        key: pull-secrets
        property: pat-someuser
```
But this works just fine (someuser-pat replaced by someuserpat):
``` YAML
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pull-secret-registry-someuser
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: pull-secret-registry-someuser
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: '{"auths": {"some.registry.com": { "auth": "{{ printf "someuser:%s" .someuserpat | b64enc }}"} } }'
  data:
    - secretKey: someuserpat
      remoteRef:
        key: pull-secrets
        property: pat-someuser
```
