### ISSUE TITLE
Example SecretStore of provider oracle has principalType: UserPrincipal at wrong level

### ISSUE THREAD

**Issue by makker-nl** [external-secrets/external-secrets#3152]
**Describe the bug**
At https://external-secrets.io/latest/provider/oracle-vault/ the example for _principalType: UserPrincipal_ is wrong. It has _principalType: UserPrincipal_ under _auth_, but it should be under _oracle_

**To Reproduce**
1. provide all relevant manifests
css-oke-vault-failing.yaml, from the example on the page, but entered my own parameters:
````
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: orcl-oke-vault-failing
spec:
  provider:
    oracle:
      vault: ocid1.vault.oc1.eu-amsterdam-1.focidofmyfaultbutobiouslyobfuscatedita
      region: eu-amsterdam-1
      auth:
        user: ocid1.user.oc1..ausedhermyownusersocidbutobuscateditforthisexamplea
        tenancy: ocid1.tenancy.oc1..aocidofmytenancybutobfuscatedita
        principalType: UserPrincipal
        secretRef:
          privatekey:
            name: oke-vault-creds
            key: privateKey
            namespace: central-secrets
          fingerprint:
            name: oke-vault-creds
            key: fingerprint
            namespace: central-secrets
````
Get this error:
````
$ kubectl apply -f ./samples/css-oke-vault-failing.yaml
Error from server (BadRequest): error when creating "./samples/css-oke-vault-failing.yaml": ClusterSecretStore in version "v1beta1" cannot be handled as a ClusterSecretStore: strict decoding error: unknown field "spec.provider.oracle.auth.principalType"
````
But, with a principalType on the proper level it works. 
css-oke-vault-okidoki.yaml:
````
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: orcl-oke-vault-failing
spec:
  provider:
    oracle:
      vault: ocid1.vault.oc1.eu-amsterdam-1.focidofmyfaultbutobiouslyobfuscatedita
      region: eu-amsterdam-1
      principalType: UserPrincipal
      auth:
        user: ocid1.user.oc1..ausedhermyownusersocidbutobuscateditforthisexamplea
        tenancy: ocid1.tenancy.oc1..aocidofmytenancybutobfuscatedita
        secretRef:
          privatekey:
            name: oke-vault-creds
            key: privateKey
            namespace: central-secrets
          fingerprint:
            name: oke-vault-creds
            key: fingerprint
            namespace: central-secrets
````
Created:
````
$ kubectl apply -f ./samples/css-oke-vault-okidoki.yaml
clustersecretstore.external-secrets.io/orcl-oke-vault-okidoki created
````
3. provide the Kubernetes and ESO version
v1.28.2 on OKE.

**Expected behavior**
I would expect that using the example with the proper values, it should successfully create the store.

**Screenshots**
![image](https://github.com/external-secrets/external-secrets/assets/20109787/0180b25a-52a0-4b8f-bf4d-d1ce39d36700)

**Additional context**
