### ISSUE TITLE
Hardcode a value a data field, usefull for simple templates that can be patched by Flux

### ISSUE THREAD

**Issue by Richard87** [external-secrets/external-secrets#3163]
**Is your feature request related to a problem? Please describe.**
I want to override part of a secret with values from Flux `substitutes`, imagine this secret:
```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: database
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-store

  data:
    - secretKey: password
      remoteRef:
        key:db_password
    - secretKey: username
      remoteRef:
        key: db_username
    - secretKey: password
      remoteRef:
        key: db_password

    - secretKey: dbname
      value: "will be patched by flux"
    - secretKey: dbhost
      value: "will be patched by flux"
   
```
**Describe the solution you'd like**
I want to specify a secret value in the data section

**Describe alternatives you've considered**
Create a template (hard to target by kustomize patch), add (in this example) dbname/dbhost to key vault

**Comment by CodingJonas** [comment]
I encountered this requirement, too, and used a template to hardcode some values. This allowed to specify values of some secrets within the template directly. It would look something like this:
```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: database
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-store
  target:
    name: database
    template:
      engineVersion: v2
      data:
        password: "{{ .password }}"
        username: "{{ .username }}"
        dbname: "will be patched by flux"
        dbhost: "will be patched by flux"
  data:
    - secretKey: password
      remoteRef:
        key:db_password
    - secretKey: username
      remoteRef:
        key: db_username
    - secretKey: password
      remoteRef:
        key: db_password
```
