### ISSUE TITLE
feat: Azure Keyvault MSI authentication

### ISSUE THREAD

**Issue by lukasmrtvy** [external-secrets/external-secrets#317]
Would be great to support "credential less" integration with Azure Keyvault with MSI authentication. 

ping @ahmedmus-1A @asnowfix @ncourbet-1A @1A-mj

**Comment by moolen** [comment]
With OPA you would prevent creating a SecretStore (or ExternalSecret that references an invalid store) in the first place.

Let's assume we would go with a secret store that can configure a pod identity and we would request credentials from [NMI](https://github.com/Azure/aad-pod-identity/blob/1cda91abd69ca1bda2c5f1f83e7c3c897f132396/pkg/nmi/server/server.go#L493-L496):

```yaml
apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: example-secret-store
spec:
  provider:
    azurekv:
      tenantId: "d3bc2180-xxxx-xxxx-xxxx-154105743342"
      vaultUrl: "https://my-keyvault-name.vault.azure.net"
      nmi:
        clientId: "foo"
        resource: "bar" #
```

OPA/Kyverno can validate the resource before it is stored. The tool would look if `spec.provider.azurekv.nmi.clientId=foo` is allowed in that particular namespace.
It's up to the user to come up with a policy that matches the particular scope they would want to allow.
