### ISSUE TITLE
Helm RBAC Role/RoleBinding for generators.external-secrets.io/webhooks lost

### ISSUE THREAD

**Issue by vitalyu** [external-secrets/external-secrets#3187]
**Describe the bug**

```
webhooks.generators.external-secrets.io "webhook" is forbidden: User "system:serviceaccount:infra-external-secrets:external-secrets" cannot get resource "webhooks" in API group "generators.external-secrets.io"
```

**Expected behavior**
Role rules for webhook presents in [helm's rbac.yaml](https://github.com/external-secrets/external-secrets/blob/main/deploy/charts/external-secrets/templates/rbac.yaml)

**Additional context**

To add
```
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: examplerole
rules:
  - apiGroups: ["generators.external-secrets.io"]
    resources: ["webhooks"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: examplerole-binding
subjects:
  - kind: ServiceAccount
    name: external-secrets
    namespace: examplens
roleRef:
  kind: Role
  name: examplerole
  apiGroup: rbac.authorization.k8s.io
```
