### ISSUE TITLE
pushSecret giving nvalid: data[tls.crt]: Required value

### ISSUE THREAD

**Issue by rakeshreddyrg09** [external-secrets/external-secrets#3202]
**Describe the bug**
I have a ClusterSecretStore at k8s cluster(host cluster), and using ClusterExternalSecret I'm trying to pull secret(type: [kubernetes.io/tls](http://kubernetes.io/tls)) into test namespace(virtual cluster) from host cluster.
here is the status of ClusterExternalSecret and ExternalSecret is TRUE and  SecretSynced.
now I am using pushSecret to push it to the SecretStore(which is created in test namespace).
problem:

- Case when I don't  provide the data section the pushSecret status is Synced, but not replicating in required namespace.
- if I provide the data section giving an error saying
`set secret failed: could not write remote ref tls.key to target secretstore k8s-store-test: Secret "sealed-secrets-key" is invalid: data[tls.crt]: Required value`

here are my files:
**_pushsecretwithdata.yaml_**
```
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: test-sealed-secrets-key
  namespace: test
spec:
  refreshInterval: 10s
  secretStoreRefs:
    - name: k8s-store-test
      kind: SecretStore
  selector:
    secret:
      name: sealed-secrets-key
  data:
    - match:
        secretKey: tls.key
        remoteRef:
          remoteKey: sealed-secrets-key
          property: tls.key
    - match:
        secretKey: tls.crt
        remoteRef:
          remoteKey: sealed-secrets-key
          property: tls.crt
```
**_pushsecret.yaml(with out data)_**
```
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: test-sealed-secrets-key
  namespace: test
spec:
  refreshInterval: 10s
  secretStoreRefs:
    - name: k8s-store-test
      kind: SecretStore
  selector:
    secret:
      name: sealed-secrets-key
```
**_ces.yaml_**
```
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: sealed-secrets-key-test
spec:
  externalSecretName: sealed-secrets-key-test
  namespaceSelector:
    matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: In
        values:
          - test
  externalSecretSpec:
    refreshInterval: 5m
    secretStoreRef:
      name: test-cs-store
      kind: ClusterSecretStore
    target:
      name: sealed-secrets-key
      creationPolicy: Owner
      template:
        type: kubernetes.io/tls
        data:
          tls.crt: "{{ .myCert | toString }}"
          tls.key: "{{ .myKey | toString }}"
    data:
      - secretKey: myCert
        remoteRef:
          key: sealed-secrets-3aeb3
          property: tls.crt
      - secretKey: myKey
        remoteRef:
          key: sealed-secrets-3aeb3
          property: tls.key
```
Can anyone help me out.
**To Reproduce**
1. Create a EKS cluster.
2. Install the latest external secret via helm (v0.9.13).
3. Create **_ClusterSecretStore_**.
4. Create a secret(**_tls_**) in host cluster (EKS).
5. Create [virtual cluster](https://www.vcluster.com/docs/getting-started/deployment) in test namespace on top of host cluster(EKS).
6. create secretStore in test(virtual cluster) namespace.
7. create ClusterExternalSecret to pull secret to test namespace.
8. use pushSecret to replicate the secret on virtual cluster test-1 namespace. 

**Expected behavior**

- The tls secret should be created in test-1 namsepace on virtual cluster using pushSecret 

slack link: https://kubernetes.slack.com/archives/C017BF84G2Y/p1709023334668079
