### ISSUE TITLE
No error logs or Events when template rendering fails

### ISSUE THREAD

**Issue by murtll** [external-secrets/external-secrets#3210]
**Is your feature request related to a problem? Please describe.**

I see no errors when rendering secret template fails. Example:
1. I created external secret looking like this
```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: foo
spec:
  data:
    - remoteRef:
        key: /path/to/secret
        property: some-data
      secretKey: some-data
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: foo
    template:
      data:
        some-data.json: |
          {
            "password": "{{ .some-data }}"
          }
      engineVersion: v2
      mergePolicy: Replace
      type: Opaque
```
2. External secret status says `Status: SecretSynced` and `Ready: True`
3. My pods starting but are not able to find secret `foo`, because it was not created
4. I see no errors in Events or operator logs
5. Have do to debug it by myself and find out that secret was not created because of rendering failure due to `-` in property name (`{{ .some-data }}`), which is not allowed by Go templates.

**Describe the solution you'd like**

I want to see any error Events and/or logs informing me that template rendering failed and telling me the reason why.

**Describe alternatives you've considered**

I am able to resolve this using `{{ index . "some-data" }}`, but it was not the first case of getting no errors when secret was not created. Lack of error messages makes debug way more difficult.
If there already are some options to enable such logs or events, tell me please, because i was not able to find them.

**Additional context**

Chart version 0.9.4

**Comment by Skarlso** [comment]
Hah, I remember encountering this problem several months ago.

**Comment by shuheiktgw** [comment]
Hmm, I cannot reproduce this error. I've used the fake provider, but I believe that does not relate to it. There is likely to be something missing here. @murtll Would you check if you can reproduce the error with the manifest above?

Here are the manifests I've used.

```
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: fake
spec:
  provider:
    fake:
      data:
      - key: "another-key"
        value: "Hi"
```

```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: fake-es
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: fake
    kind: ClusterSecretStore
  data:
    - remoteRef:
        key: another-key
      secretKey: another-key
  target:
    name: fake-secret
    template:
      data:
        some-data.json: |
          {
            "password": "{{ .another-key }}"
          }
      engineVersion: v2
      mergePolicy: Replace
      type: Opaque
```

And the controller outputs the error log below

```
{"level":"error","ts":1709863332.3713782,"msg":"Reconciler error","controller":"externalsecret","controllerGroup":"external-secrets.io","controllerKind":"ExternalSecret","ExternalSecret":{"name":"fake-es","namespace":"default"},"namespace":"default","name":"fake-es","reconcileID":"c1c9a967-f495-4e68-8210-c87ccf9bf836","error":"could not apply template: could not execute template: could not execute template: unable to execute template at key huga: unable to parse template at key huga: template: huga:1: bad character U+002D '-'","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/Users/shuheiktgw/go/1.21.1/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/Users/shuheiktgw/go/1.21.1/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/Users/shuheiktgw/go/1.21.1/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:227"}
```

Also, the status was `SecretSyncedError`.

```
NAME                                          AGE   STATUS   CAPABILITIES   READY
clustersecretstore.external-secrets.io/fake   12m   Valid    ReadWrite      True

NAME                                         STORE   REFRESH INTERVAL   STATUS              READY
externalsecret.external-secrets.io/fake-es   fake    1h                 SecretSyncedError   False
```
