### ISSUE TITLE
Failing helm.test for crds due to missing JWT authentication sample within snapshot folder 

### ISSUE THREAD

**Issue by fdberlking** [external-secrets/external-secrets#3231]
**Describe the bug**
After the introduction of JWT authentication, I realised that the helm.test started to fail for `crds_test.yaml`.

**To Reproduce**
1. Update your local repository to the latest version
2. run `make helm.test`

**Expected behavior**
All tests passes.

**Screenshots**

```yaml
 ➜  external-secrets git:(main) make helm.test
./hack/helm.generate.sh deploy/crds deploy/charts/external-secrets
13:45:07 [ OK ] Finished generating helm chart files

### Chart [ external-secrets ] deploy/charts/external-secrets/

 PASS  test cert controller deployment  deploy/charts/external-secrets/tests/cert_controller_test.yaml
 PASS  test controller deployment       deploy/charts/external-secrets/tests/controller_test.yaml
 FAIL  test crds        deploy/charts/external-secrets/tests/crds_test.yaml
        - should match snapshot of default values

                - asserts[0] `matchSnapshot` fail
                        Template:       external-secrets/templates/crds/secretstore.yaml
                        DocumentIndex:  0
                        Path:   
                        Expected to match snapshot 1:
                                --- Expected
                                +++ Actual
                                @@ -2174,2 +2174,7 @@
                                                                   type: string
                                +                                hostId:
                                +                                  description: |-
                                +                                    Optional HostID for JWT authentication. This may be used depending
                                +                                    on how the Conjur JWT authenticator policy is configured.
                                +                                  type: string
                                                                 secretRef:

 PASS  test service monitor     deploy/charts/external-secrets/tests/service_monitor_test.yaml
 PASS  test webhook deployment  deploy/charts/external-secrets/tests/webhook_test.yaml

Snapshot Summary: 1 snapshot failed in 1 test suite. Check changes and use `-u` to update snapshot.

Charts:      1 failed, 0 passed, 1 total
Test Suites: 1 failed, 4 passed, 5 total
Tests:       1 failed, 38 passed, 39 total
Snapshot:    1 failed, 4 passed, 5 total
Time:        437.93014ms

Error: plugin "unittest" exited with error
make: *** [helm.test] Error 1
```

**Additional context**
The crd tests are failing because no sample is present in the snapshot.
