### ISSUE TITLE
"error":"could not get provider client: unable to get credentials: oauth2: cannot fetch token: Post \"https://oauth2.googleapis.com/token\": dial tcp 142.250.186.138:443: i/o timeout"

### ISSUE THREAD

**Issue by alibahramian** [external-secrets/external-secrets#3236]
**Describe the bug**
I am encountering an issue when trying to use the external secrets operator for Google Secret Manager on an on-premises Kubernetes cluster. The error message indicates a timeout while trying to fetch credentials from the Google OAuth2 service.

**To Reproduce**
1. Deploy the external secrets operator on an on-premises Kubernetes cluster.
2. Create a secret for Google Secret Manager with valid credentials and use it on ClusterSecretStore
3. Observe the timeout error when trying to fetch credentials.

**Troubleshooting Steps Taken**
Checked network connectivity.
Verified firewall rules.
Ensured DNS resolution is working.
Confirmed the validity of Google Cloud credentials.
Checked service account permissions.

**Additional context**
Exact same configuration works nice on GKE cluster but not on on-premise 

```yaml

apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-store
  namespace: external-secrets 
spec:
  provider:
    gcpsm:
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: gcpsm-secret              # secret name containing SA key
            key: secret-access-credentials  # key name containing SA key
            namespace: external-secrets 
      projectID: GOOGLE-PROJECT-ID
 ```
 **Error**
 ```bash
 {"level":"error","ts":1709722748.9885485,"logger":"controllers.ClusterSecretStore","msg":"unable to validate store","clustersecretstore":{"name":"gcp-store"},"error":"could not get provider client: unable to get credentials: oauth2: cannot fetch token: Post \"https://oauth2.googleapis.com/token\": dial tcp 172.217.168.42:443: i/o timeout","stacktrace":"github.com/external-secrets/external-secrets/pkg/controllers/secretstore.reconcile\n\t/home/runner/work/external-secrets/external-secrets/pkg/controllers/secretstore/common.go:69\ngithub.com/external-secrets/external-secrets/pkg/controllers/secretstore.(*ClusterStoreReconciler).Reconcile\n\t/home/runner/work/external-secrets/external-secrets/pkg/controllers/secretstore/clustersecretstore_controller.go:64\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.1/pkg/internal/controller/controller.go:119\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.1/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.1/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.1/pkg/internal/controller/controller.go:227"}
{"level":"error","ts":1709722749.0381377,"msg":"Reconciler error","controller":"clustersecretstore","controllerGroup":"external-secrets.io","controllerKind":"ClusterSecretStore","ClusterSecretStore":{"name":"gcp-store"},"namespace":"","name":"gcp-store","reconcileID":"08817133-bbfe-44a3-ac8f-fcda88655abe","error":"could not get provider client: unable to get credentials: oauth2: cannot fetch token: Post \"https://oauth2.googleapis.com/token\": dial tcp 172.217.168.42:443: i/o timeout","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.1/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.1/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.1/pkg/internal/controller/controller.go:227"}
 ```
