### ISSUE TITLE
Webhook Generator JSON Issues

### ISSUE THREAD

**Issue by davidcorrigan714** [external-secrets/external-secrets#3239]
**Describe the bug**
When using the Webhook generator there seems to be some issues parsing non-string types in the response JSON:

"could not generate [0]: failed to get response (wrong type in key 'expires_in': float64)"

The request works with the non-generator version of the Webhook provider and digging through the code it seems like some of the conversion logic implemented [here](https://github.com/external-secrets/external-secrets/blob/1f498c83f86e42bd2b25eadaf18e4b18981716fc/pkg/provider/webhook/webhook.go#L136C1-L193C1) is [missing here](https://github.com/external-secrets/external-secrets/blob/1f498c83f86e42bd2b25eadaf18e4b18981716fc/pkg/common/webhook/webhook.go#L76C1-L117C2). The issue seems very reminiscent of #2899  .

**To Reproduce**

The API response the Webhook is receiving looks like:
```
{
    "access_token": "long_jwt_token",
    "expires_in": 86400,
    "issued_token_type": "urn:ietf:params:oauth:token-type:access_token",
    "token_type": "Bearer"
}
```

Haven't quite poked through the code enough to try to work that into a unit test and try to fix it myself. Golang is not my strong suite but I've done some from time to time.

The resources I've been testing with look like this:

```

apiVersion: generators.external-secrets.io/v1alpha1
kind: Webhook
metadata:
  name: artifactory-role-token-generator-2
spec:
  method: "POST"
  url: https://example.com/access/api/v1/oidc/token
  result:
    jsonPath: "$"
  body: |
      {
          "grant_type": "urn:ietf:params:oauth:grant-type:token-exchange",
          "subject_token_type": "urn:ietf:params:oauth:token-type:id_token",
          "subject_token": "{{ "{{" }} .oidc_token.token {{ "}}" }}",
          "provider_name": "eks-rdssis-dev"
      }
  headers:
    Content-Type: application/json
  secrets:
  - name: oidc_token
    secretRef:
      name: role-oidc-token
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: webhook-backend
spec:
  provider:
    webhook:
      method: "POST"
      url: https://example.com/access/api/v1/oidc/token
      result:
        jsonPath: "$"
      body: |
          {
              "grant_type": "urn:ietf:params:oauth:grant-type:token-exchange",
              "subject_token_type": "urn:ietf:params:oauth:token-type:id_token",
              "subject_token": "{{ "{{" }} .oidc_token.token {{ "}}" }}",
              "provider_name": "eks-rdssis-dev"
          }
      headers:
        Content-Type: application/json
      secrets:
      - name: oidc_token
        secretRef:
          name: role-oidc-token
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: artifactory-external-secret-loader-opaque-3
spec:
  refreshInterval: "20h"
  target:
    name: token-test
  secretStoreRef:
    name: webhook-backend
    kind: SecretStore
  data:
  - secretKey: foobar
    remoteRef:
      key: secret
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: artifactory-external-secret-loader-opaque-2
spec:
  refreshInterval: "20h"
  target:
    # Name of the private registry secret to create
    name: niartifacts-pre
    template:
      data:
        ".dockerconfigjson": 'long-template-string-here'
      type: kubernetes.io/dockerconfigjson
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: Webhook
        name: artifactory-role-token-generator-2
---

```
 I'm using ESO version 0.9.13 .

**Comment by cringdahl** [comment]
@davidcorrigan714, I'm seeing the bug, but in the non-generator webhook provider. The error is `"error":"failed to get response (wrong type in key 'every_single_key': float64)"`. Were you doing anything differently in your webhook provider test?

```yaml
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: passwords-example
spec:
  provider:
    webhook:
      url: "https://passwords.example.com/credentials/{{ .remoteRef.key }}/search"
      result:
        jsonPath: "$.credential"
      headers:
        Content-Type: application/json
        Accept: application/json
        X-Auth-Token: "{{ .auth.token }}"
      secrets:
      - name: auth
        secretRef:
          name: secret-token
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: eso-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: passwords-example
  target:
    name: generated-secret
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: "169957"
```
