### ISSUE TITLE
Can I select keys from the secret for the template engine from the pushsecret without pushing them to the secret store?

### ISSUE THREAD

**Issue by ma-ble** [external-secrets/external-secrets#3243]
With PushSecret, is it possible to use templating to combine keys from the secret under a new key and at the same time not push the original key from the secret?

In my example, I would like to include all the keys of the secret "input" in the template engine of the PushSecret. However, in the PushSecret itself, which is pushed to the SecretStore, I only want to transfer the fields: "username", "password", "url". Both fields "endpoint" and "port" should be transfered to the SecretsStore.

```
kind: Secret
apiVersion: v1
metadata:
  name: input
  namespace: source
data:
  username: aGVsbG8=
  password: d29ybGQ=
  endpoint: ZXAtdGVzdA==
  port: ODA4MA==
type: Opaque
```
```
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: test
  namespace: source
spec:
  deletionPolicy: Delete
  refreshInterval: 10s
  secretStoreRefs:
    - name: build
      kind: SecretStore
  selector:
    secret:
      name: input
  template:
    data:
      username: "{{ .username }}"
      password: "{{ .password }}" 
      url: "postgres://{{ .username }}:{{ .password }}@{{ .endpoint }}:{{ .port }}/postgres"
  data:
    - match:
        remoteRef:
          remoteKey: target
```

My target secret should look like this. 

```
kind: Secret
apiVersion: v1
metadata:
  name: target
  namespace: target
data:
  username: aGVsbG8=
  password: d29ybGQ=
  url: cG9zdGdyZXM6Ly9hd3NfYWRtaW46d29ybGRAZXAtdGVzdDo4MDgwL3Bvc3RncmVz
type: Opaque
```

Is this possible with the current template engine for PushSecrets?

**Comment by RafaelBroseghini** [comment]
I was actually looking into the same thing and I believe I was able to solve it.

You won't be able to push all keys defined under `data` to the same remote secret but if your `input` secret already has the `username`, `password`, `endpoint` and `port` keys, the below should work:

```yaml
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: test
  namespace: source
spec:
  deletionPolicy: Delete
  refreshInterval: 10s
  secretStoreRefs:
    - name: build
      kind: SecretStore
  selector:
    secret:
      name: input
  template:
    data:
      url: "postgres://{{ .username }}:{{ .password }}@{{ .endpoint }}:{{ .port }}/postgres"
  data:
    - match:
       secretKey: url
        remoteRef:
          remoteKey: target
```
