### ISSUE TITLE
```yaml

### ISSUE THREAD

**Issue by Dicked1211** [external-secrets/external-secrets#3267]
```yaml
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: thanos
spec:
  secretStoreRefs:
    - name: onepassword-connect
      kind: ClusterSecretStore
  selector:
    secret:
      name: thanos-bucket-v2
  data:
    - match:
        secretKey: AWS_ACCESS_KEY_ID
        remoteRef:
          remoteKey: thanos-test
    - match:
        secretKey: AWS_SECRET_ACCESS_KEY
        remoteRef:
          remoteKey: thanos-test
```

_Originally posted by @onedr0p in https://github.com/external-secrets/external-secrets/issues/3238#issuecomment-1984154134_
