### ISSUE TITLE
Cannot use PushSecret to upload certificate with EC private key to Azure KeyVault Certificates

### ISSUE THREAD

**Issue by gravufo** [external-secrets/external-secrets#3284]
**Describe the bug**
ExternalSecrets fails to upload a valid PEM-formatted PKCS8 certificate that has an EC private key.

**To Reproduce**
K8s version: v1.28.3
ESO version: v0.9.13

1. Have a secret containing a valid certificate + private key in a PEM format:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: test-cert
stringData:
  tls-combined.pem: |
    -----BEGIN PRIVATE KEY-----
    MIGHA<Redated>
    -----END PRIVATE KEY-----
    
    -----BEGIN CERTIFICATE-----
    MIIDr<Redacted>
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIDC<Redacted>
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIEm<Redacted>
    -----END CERTIFICATE-----
```
2. Create the following PushSecret (assuming you have a working ClusterSecretStore or SecretStore that can write to an Azure KeyVault)
```yaml
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: test-cert-pushsecret
  namespace: cert-manager
spec:
  refreshInterval: 10s # Refresh interval for which push secret will reconcile
  deletionPolicy: None
  secretStoreRefs: # A list of secret stores to push secrets to
    - name: certificates-readwrite
      kind: ClusterSecretStore
  selector:
    secret:
      name: test-cert # Source Kubernetes secret to be pushed
  data:
    - match:
        secretKey: tls-combined.pem # Source Kubernetes secret key containing the certificate
        remoteRef:
          remoteKey: cert/test-cert
```
3. Check the Events of the PushSecret object to find the error.

**Expected behavior**
It should push the certificate with its private key successfully.

**Screenshots**
![image](https://github.com/external-secrets/external-secrets/assets/475807/4c3e63ea-68e9-4eb7-8e79-f865d20a7fba)

**Additional context**
The problem lies in the import path used in the SDK here: https://github.com/external-secrets/external-secrets/blob/main/pkg/provider/azure/keyvault/keyvault.go#L30

A super quick fix could be to simply change that line to `github.com/Azure/azure-sdk-for-go/services/keyvault/v7.0/keyvault`.
That said, I believe the keyvault SDK has been changed considerably and they now recommend using [this module](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/security/keyvault/azcertificates) for certificates, for example.

I believe doing the quick fix of bumping to v7.0 and releasing a hotfix version of ESO would be most helpful, then this issue or a new one could be used to track the migration to the new SDK.
