### ISSUE TITLE
[ECRAuthorizationToken] Failed to find an auth secret in the other namespace

### ISSUE THREAD

**Issue by jlandowner** [external-secrets/external-secrets#3289]
**Describe the bug**
Failed to find an auth secret in the other namespace in `spec.auth.secretRef` in `ECRAuthorizationToken`.

```
 Warning  UpdateFailed  11m (x29 over 3h20m)  external-secrets  could not generate [0]: unable to create aws session: could not fetch SecretAccessKey secret: cannot get Kubernetes secret "secrets-aws-iam-cred": secrets "secrets-aws-iam-cred" not found
```

**To Reproduce**
1. provide all relevant manifests

```
apiVersion: generators.external-secrets.io/v1alpha1
kind: ECRAuthorizationToken
metadata:
  name: aws-ecr-token-generator
  namespace: default
spec:
  region: ap-northeast-1
  auth:
    secretRef:
      accessKeyIDSecretRef:
        name: secrets-aws-iam-cred
        namespace: kube-system
        key: AWS_ACCESS_KEY_ID
      secretAccessKeySecretRef:
        name: secrets-aws-iam-cred
        namespace: kube-system
        key: AWS_SECRET_ACCESS_KEY
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aws-ecr-token
  namespace: default
spec:
  refreshInterval: "3h"
  target:
    name: aws-ecr-token
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: ECRAuthorizationToken
        name: aws-ecr-token-generator
---
apiVersion: v1
kind: Secret
metadata:
  name: secrets-aws-iam-cred
  namespace: kube-system
type: Opaque
data:
  AWS_ACCESS_KEY_ID: ******
  AWS_SECRET_ACCESS_KEY: ******
```

3. provide the Kubernetes and ESO version

Kubernetes: v1.28.1 (kubeadm)
external-secrets: 0.9.13

**Expected behavior**
find aws auth secret and a generator's secret should be created

**Screenshots**

```
$ k describe externalsecret.external-secrets.io/aws-ecr-token
Name:         aws-ecr-token
Namespace:    default
Labels:       <none>
Annotations:  <none>
API Version:  external-secrets.io/v1beta1
Kind:         ExternalSecret
Metadata:
  Creation Timestamp:  2024-03-20T08:21:22Z
  Generation:          1
  Managed Fields:
    API Version:  external-secrets.io/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        .:
        f:conditions:
    Manager:      external-secrets
    Operation:    Update
    Subresource:  status
    Time:         2024-03-20T08:21:22Z
    API Version:  external-secrets.io/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:dataFrom:
        f:refreshInterval:
        f:secretStoreRef:
          .:
          f:kind:
          f:name:
        f:target:
          .:
          f:creationPolicy:
          f:deletionPolicy:
          f:name:
    Manager:         kubectl-client-side-apply
    Operation:       Update
    Time:            2024-03-20T08:21:22Z
  Resource Version:  94729663
  UID:               80bde12f-ddd2-49c9-a0db-53dbd573ef69
Spec:
  Data From:
    Source Ref:
      Generator Ref:
        API Version:  generators.external-secrets.io/v1alpha1
        Kind:         ECRAuthorizationToken
        Name:         aws-ecr-token-generator
  Refresh Interval:   3h
  Target:
    Creation Policy:  Owner
    Deletion Policy:  Retain
    Name:             aws-ecr-token
Status:
  Conditions:
    Last Transition Time:  2024-03-20T08:21:22Z
    Message:               could not get secret data from provider
    Reason:                SecretSyncedError
    Status:                False
    Type:                  Ready
Events:
  Type     Reason        Age                   From              Message
  ----     ------        ----                  ----              -------
  Warning  UpdateFailed  11m (x29 over 3h20m)  external-secrets  could not generate [0]: unable to create aws session: could not fetch SecretAccessKey secret: cannot get Kubernetes secret "secrets-aws-iam-cred": secrets "secrets-aws-iam-cred" not found

# The secret actually exists
$ k get secret secrets-aws-iam-cred -n kube-system
NAME                   TYPE     DATA   AGE
secrets-aws-iam-cred   Opaque   2      6d20h
```

**Additional context**
First I tried to create `ECRAuthorizationToken` in `kube-system`(the same namespace with auth secret) and reference it in `generatorRef` in `ClusterExternalSecret`.

But I found `generatorRef` does not have `namespace` property and `ExternalSecret` created by `ClusterExternalSecret` also failed. So I do like this.

```yaml
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: ECRAuthorizationToken
        name: aws-ecr-token-generator
        namespace: kube-system # <-- Not allowed
```
