### ISSUE TITLE
Add `namespace` property in `generatorRef` for `ClusterExternalSecret`

### ISSUE THREAD

**Issue by jlandowner** [external-secrets/external-secrets#3290]
**Is your feature request related to a problem? Please describe.**

I have to use the same generator in all user namespaces(multi tenant cluster).
Currently `ClusterExternalSecret` can distribute `ExternalSecret` but `generatorRef` can not accept `namespace`.
So I have to create the same generator and its auth secret in every namespaces for now.

For instance, I have to create the following manifests in all namespaces.
Especially I do not want to create `secrets-aws-iam-cred` in all namespaces for security.

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: secrets-aws-iam-cred
  namespace: every-namespace
type: Opaque
data:
  AWS_ACCESS_KEY_ID: ******
  AWS_SECRET_ACCESS_KEY: ******
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: ECRAuthorizationToken
metadata:
  name: aws-ecr-token-generator
  namespace: every-namespace
spec:
  region: ap-northeast-1
  auth:
    secretRef:
      accessKeyIDSecretRef:
        name: secrets-aws-iam-cred
        key: AWS_ACCESS_KEY_ID
      secretAccessKeySecretRef:
        name: secrets-aws-iam-cred
        key: AWS_SECRET_ACCESS_KEY
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aws-ecr-token
  namespace: every-namespace
spec:
  refreshInterval: "3h"
  target:
    name: aws-ecr-token
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: ECRAuthorizationToken
        name: aws-ecr-token-generator
```

**Describe the solution you'd like**

Add `namespace` property in `generatorRef` struct for `ClusterExternalSecret`.
It will be passed to `ExternalSecret` and use it only if the `ExternalSecret` is created by `ClusterExternalSecret`.

- ClusterExternalSecret

```yaml
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: aws-ecr-token
spec:
  externalSecretName: aws-ecr-token
  namespaceSelector:
    matchLabels: 
      aws-ecr-token: enabled
  refreshTime: "1m"
  externalSecretSpec:
    refreshInterval: "3h"
    target:
      name: aws-ecr-token
    dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ECRAuthorizationToken
          name: aws-ecr-token-generator
          namespace: kube-system # Add
```

- ExternalSecret created by ClusterExternalSecret

```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  creationTimestamp: "2024-03-20T13:54:40Z"
  generation: 1
  name: aws-ecr-token
  namespace: default
  ownerReferences:
  - apiVersion: external-secrets.io/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: ClusterExternalSecret
    name: aws-ecr-token
    uid: ebec1975-2d04-4e08-90a2-29ceaa5a9949
  resourceVersion: "94778801"
  uid: 47bd5d56-4e26-4be1-95ed-2c1420f81293
spec:
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: ECRAuthorizationToken
        name: aws-ecr-token-generator
        namespace: kube-system # Use only if owner is ClusterExternalSecret
  refreshInterval: 3h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ecr-token-generator
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: aws-ecr-token
status:
  conditions:
  - lastTransitionTime: "2024-03-20T13:54:40Z"
    message: could not get secret data from provider
    reason: SecretSyncedError
    status: "False"
    type: Ready
```

**Describe alternatives you've considered**

I struggled to find a workaround but fail #3289

**Comment by shuheiktgw** [comment]
The same as https://github.com/external-secrets/external-secrets/issues/2009. We need cluster-scoped Generators to support it.

**Comment by jlandowner** [comment]
@shuheiktgw Thank you for replying.

Cluster-scoped generators are great! Is it planned or someone is already working on it?

I thought creating new cluster-scoped APIs will be a hard work and came up with the idea cross-namespaced reference for ExternalSecret created by ClusterExternalSecret.

**Comment by g5rg** [comment]
@shuheiktgw Is there any plan to release this feature any time soon? Either cluster-scoped generators or namespace parameter?
Thanks

**Comment by shuheiktgw** [comment]
I stepped down from a maintainer a while ago so you may want to reach out to the current maintainers🙂

**Comment by moolen** [comment]
Yeah, it has came up a couple of times. Generally we want to keep the isolation mechanism that namespaces provide.
Allowing cross-namespace references breaks this idiom, it opens the door for unprivileged data access and eventually exfiltration.

With namespaced resources we can easily leverage rbac for access control. Cross-namespace references make it hard/impossible to properly isolate it.

Hope that makes sense.

Also: for some reason my phone autocompletes `idiom` to `idiot`, i hope a caught all "autocorrect" issues 😀

**Comment by Skarlso** [comment]
@jlandowner Are you satisfied with the current ClusterGenerator? :) Are you aware that it's a thing now?

**Comment by Skarlso** [comment]
@konradasb Are you okay with the proposed solution? It has been released with 0.11.0.

**Comment by jlandowner** [comment]
@Skarlso Sorry but I didn't know that😳 Thank you for a great job, I'll try it🚀

**Comment by jlandowner** [comment]
Sorry for my late update. I tried ClusterGenerator but currently I met the error about cross-namespace secret reference.

```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aws-ecr-token
  namespace: default
spec:
  refreshInterval: "3h"
  target:
    name: aws-ecr-token
    template:
      type: kubernetes.io/dockerconfigjson
      engineVersion: v2
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "{{ .proxy_endpoint }}": {
                "username": "{{ .username }}",
                "password": "{{ .password }}",
                "auth": "{{ printf "%s:%s" .username .password | b64enc }}"
              }
            }
          }
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1 # Use ClusterGenerator
          kind: ClusterGenerator
          name: aws-ecr-token-generator
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: ClusterGenerator
metadata:
  name: aws-ecr-token-generator
spec:
  kind: ECRAuthorizationToken
  generator:
    ecrAuthorizationTokenSpec:
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-ecr-iam
            namespace: external-secrets # THIS IS IGNORED
            key: AWS_ACCESS_KEY_ID
          secretAccessKeySecretRef:
            name: aws-ecr-iam
            namespace: external-secrets # THIS IS IGNORED
            key: AWS_SECRET_ACCESS_KEY
      region: ap-northeast-1
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aws-ecr-iam
  namespace: external-secrets
spec:
  secretStoreRef:
    name: aws-secretsmanager-store
    kind: ClusterSecretStore
  refreshInterval: "0"
  dataFrom:
    - extract:
        key: *****

```

I got sync error in ExternalSecret which is referencing ClusterGenerator.

```
Events:
  Type     Reason        Age                    From              Message
  ----     ------        ----                   ----              -------
  Warning  UpdateFailed  5m58s (x197 over 22h)  external-secrets  error processing spec.dataFrom[0].sourceRef.generatorRef, err: error using generator: unable to create aws session: could not fetch SecretAccessKey secret: cannot get Kubernetes secret "aws-ecr-iam" from namespace "default": secrets "aws-ecr-iam" not found
```

I found this is already reported in #4384.
I expect this feature is implemented in the feature.

**Comment by gusfcarvalho** [comment]
the fact that ClusterGenerators resemble more ClusterExternalSecrets than ClusterSecretStores in terms of behavior, I'm not sure we can even introduce namespaces to it while honoring the `namespaced` promise on Generators.

We would need to add reference checks and validation checks on top of each generator, as each one will have Secrets/ServiceAccounts/Tokens references to be checked 😖

**Comment by Skarlso** [comment]
I kinda had that feeling. But didn't quite know yet before diving into the code. :/

**Comment by gusfcarvalho** [comment]
maybe we should just make it official via API changes that generator credentials can only be namespaced ?

**Comment by Skarlso** [comment]
Sounds good to me.

**Comment by toms-place** [comment]
Would it be possible to create a separate Kind for this usecase? Otherwise I would need to use something like cert-manager is proposing [here](https://cert-manager.io/docs/devops-tips/syncing-secrets-across-namespaces/) to sync secrets across namespaces: 

- https://github.com/emberstack/kubernetes-reflector
- https://github.com/mittwald/kubernetes-replicator

I am really looking forward to this kind of functionality, not only for generators, but also for eg. ClusterExternalSecrets...

**Comment by Skarlso** [comment]
You can already replicate secrets using a ClusterSecretStore of type Kubernetes. Select a secret, then create a ClusterExternalSecrets that creates ExternalSecrets inside the desired namespaces and then they can replicate your secret into the namespace you desire using the same selectors as the Generator.

**Comment by gusfcarvalho** [comment]
> Would it be possible to create a separate Kind for this usecase? Otherwise I would need to use something like cert-manager is proposing [here](https://cert-manager.io/docs/devops-tips/syncing-secrets-across-namespaces/) to sync secrets across namespaces:
> 
> * https://github.com/emberstack/kubernetes-reflector
> * https://github.com/mittwald/kubernetes-replicator
> 
> I am really looking forward to this kind of functionality, not only for generators, but also for eg. ClusterExternalSecrets...

Generators and ClusterGenerators are still `v1alpha1`, so we can break them if we want to.

The problem is that this breaking change is just too big to do, and would provide minimal value (there are workarounds leveraging ClusterSecretStores and ClusterExternalSecrets as @Skarlso mentioned - you basically create one Secret in one namespace using a Generator and then copy it over with ExternalSecrets pointing to ClusterSecretStores.

@toms-place I see you are new to this issue - what's the exact use case you're trying to cover here? Can you share your manifests?

**Comment by toms-place** [comment]
@Skarlso - oh nice! Didn't know that I can do this! I will try it out, thanks.

@gusfcarvalho - my use-case is as follows:

I have a multi-tenant setup where each tenant has a separate namespace. I am using the gitlab provider to sync variables to k8s. I now want to enable each tenant to pull images from azure. Therefore I would like to have a single azure credential in the external-secrets namespace, which is used by the clustergenerator to create an imagepullsecret in each tenants namespace.

Currently this is only working on a namespace basis, so I would need to replicate the AZURE_CLIENT_ID & AZURE_CLIENT_SECRET to each namespace to make this work. But I actually would only need the token for the registry auth in each namespace:

```yaml
---
# The ClusterSecretStore is a used to sync secrets from Gitlab to the cluster
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gitlab-group-<ID>-<NAME>
spec:
  # Conditions about namespaces in which the ClusterSecretStore is usable for ExternalSecrets
  # If not specified, the ClusterSecretStore is usable in all namespaces
  conditions:
    - namespaces:
        - "<NAME>"
  provider:
    gitlab:
      auth:
        SecretRef:
          accessToken:
            name: gitlab-group-<ID>-<NAME> # Name of the flux-api-token-ro secret in the external-secrets namespace
            namespace: external-secrets
            key: token
      groupIDs:
      - "<ID>"
      environment: dev
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: azure-container-registry-az-client
  namespace: <NAME>
spec:
  refreshInterval: 1h

  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab-group-<ID>-<NAME>

  target:
    name: azure-container-registry-az-client # Name for the secret to be created on the cluster
    creationPolicy: Owner
    deletionPolicy: Delete

  data:
    - secretKey: clientsecret # Key name given to the secret to be created on the cluster
      remoteRef:
        key: AZURE_CLIENT_SECRET # Key of the variable on Gitlab (can be found in the CI/CD settings, can't have dashes)
    - secretKey: clientid # Key name given to the secret to be created on the cluster
      remoteRef:
        key: AZURE_CLIENT_ID # Key of the variable on Gitlab (can be found in the CI/CD settings, can't have dashes)
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: ClusterGenerator
metadata:
 name: azure-container-registry-token-generator
spec:
 kind: ACRAccessToken
 generator:
   acrAccessTokenSpec:
     tenantId: <TENANT_ID>
     registry: <REGISTRY_FQDN>
     auth:
       servicePrincipal:
         secretRef:
           clientSecret:
             name: azure-container-registry-az-client
             key: clientsecret
           clientId:
             name: azure-container-registry-az-client
             key: clientid
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: azure-container-registry-token
  namespace: <NAME>
spec:
  refreshInterval: "1h"
  target:
    name: azure-container-registry-token
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "untis.azurecr.io": {
                "username": "{{ .username }}",
                "password": "{{ .password }}"
              }
            }
          }
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: ClusterGenerator
        name: azure-container-registry-token-generator

```

As far as I understood now, I could create the `azure-container-registry-token` in the external-secrets namespace and sync it to all my tenants namespaces, right?
