### ISSUE TITLE
ESO pod crashes if the secret referenced in the PushSecret has no data

### ISSUE THREAD

**Issue by ma-ble** [external-secrets/external-secrets#3294]
**Describe the bug**
If you create a PushSecret that references a secret without a data key, the ESO pod crashes with the error message 

```
{"level":"info","ts":1711105214.26202,"msg":"Observed a panic in reconciler: assignment to entry in nil map","controller":"pushsecret","controllerGroup":"external-secrets.io","controllerKind":"PushSecret","PushSecret":{"name":"my-secret","namespace":"test"},"namespace":"test","name":"my-secret","reconcileID":"566de87-9b33-403c-9006-adbece35940a"}
panic: assignment to entry in nil map [recovered]
	panic: assignment to entry in nil map
```

**To Reproduce**
1. Install ESO with Version v0.9.13
2. Create Secret without data field

```
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
  namespace: test
```

3. Create PushSecret 

```
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: my-secret
  namespace: test
spec:
  deletionPolicy: Delete
  refreshInterval: 10s
  secretStoreRefs:
    - name: build
      kind: SecretStore
  selector:
    secret:
      name: my-secret
  template:
    data:
      test: "{{ .test }}"
  data:
    - match:  
        secretKey: test
        remoteRef:
          remoteKey: test
          property: test
```

**Expected behavior**
My expectation is that the pod will not crash when a secret referenced by a PushSecret has no data field.

**Comment by shuheiktgw** [comment]
@ma-ble Thanks for reporting the issue! I cannot reproduce the behavior with the fake provider. I believe this is a provider-specific problem. Would you tell me which provider you use for the "build" SecretStore?

**Comment by ma-ble** [comment]
@shuheiktgw sorry that I didn't include this information. I use the kubernetes provider in my SecretStore: 

```
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: build
  namespace: test
spec:
  provider:
    kubernetes:
      remoteNamespace: target
      server:
        url: "https://kubernetes.default.svc/"
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
      auth:
        serviceAccount:
          name: "store"
```
In my test setup I push the secrets from one namespace (test) into the target namespace (target) of the same cluster.
