### ISSUE TITLE
admission webhook denied: missing `spec.provider.keepersecurity.auth` when creating clustersecretstore for keeper

### ISSUE THREAD

**Issue by sujan46** [external-secrets/external-secrets#3295]
**Describe the bug**
admission webhook denied: missing `spec.provider.keepersecurity.auth` when creating clustersecretstore for keeper

**To Reproduce**
1. provide all relevant manifests
```yaml
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
 name: xxxx-keeper-clustersecretstore
 namespace: xxxxx
spec:
  provider:
    keepersecurity:
    auth:
     secretRef:
        name: ksm-config-secret
        key: ksm_config
    folderID: "xxxxxx"
```
3. provide the Kubernetes and ESO version
`kubernetes v1.27.10`
`ESO v0.9.13`

**Expected behavior**
I would expect you to create a clustersecretstore but it fails with below error
`Error from server (Forbidden): error when creating "keeper_xxxxx_cssecretstore.yml": admission webhook "validate.clustersecretstore.external-secrets.io" denied the request: missing: spec.provider.keepersecurity.auth`

I know we are using `authref` for keepersecurity but error checks for `auth`

**Screenshots**

**Additional context**

**Comment by sujan46** [comment]
I was able fix this issue by making the below changes. I was going through the code and found the fix
```yaml
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
 name: xxxx-keeper-clustersecretstore
spec:
  provider:
    keepersecurity:
    auth:
     secretRef:
        name: ksm-config-secret
        key: ksm_config
        namespace: xxxx
    folderID: "xxxxxx"
```

Error was misleading and lack of documentation of clustersecret for keeper.
