### ISSUE TITLE
Webhook TLS Client Renegotiation Error

### ISSUE THREAD

**Issue by rickymulder** [external-secrets/external-secrets#3331]
**Describe the bug**
When setting up a Webhook Provider connection to a Cyberark CCP Endpoint, it fails with error `local error: tls: no renegotiation`

Kubernetes provides this event message for the externalsecret object:
```
Events:
  Type     Reason        Age                From              Message
  ----     ------        ----               ----              -------
  Warning  UpdateFailed  2s (x12 over 13s)  external-secrets  error retrieving secret at .data[0], key: <cyberark username field>, err: failed to call endpoint: Get "https://ccp.example.com/AIMWebService/api/Accounts?ConnectionTimeout=30&AppId=MY-APPID&Query=Safe=MY-SAFE;UserName=<cyberark username field>;Address=<cyberark address field>": local error: tls: no renegotiation
```

**To Reproduce**
1. Create either a secretstore or clustersecretstore
```
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: cyberark-test
spec:
  provider:
    webhook:
      url: "https://ccp.example.com/AIMWebService/api/Accounts?ConnectionTimeout=30&AppId=MY-APP-ID&Query=Safe=MY-SAFE;UserName={{ .remoteRef.key }};Address={{ .remoteRef.property }}"
      timeout: 30s
      result:
        jsonPath: $.Content
      caBundle: ...
```
2. Create an external secret using this secretstore
```
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: webhook-example
spec:
  refreshInterval: "30m"
  secretStoreRef:
    name: cyberark-test
    kind: ClusterSecretStore
  target:
    name: example-sync
  data:
  - secretKey: username
    remoteRef:
      key: <cyberark username field>
      property: <cyberark address field>
      decodingStrategy: Auto
```
3. Kubernetes Version: v1.25.16+5c97f5b
4. ESO Version 0.9.14

**Expected behavior**
I expect the External Secrets Operator to fetch the secret appropriately and not error

**Additional context**
Cyberark CCP (at least in our environment) doesn't allow TLS Renegotiation.  TLS Renegotiation as I understand it will only affect long-lived connections.  Webhook connects to the URL in question authenticating each request individually, thus changing this behavior should have little to no impact on other existing webhook providers.

I operate in a highly regulated environment and have sanitized this severely.  Please take my example with a grain of salt.  This same environment prevents me from pushing a pull request for review.

I tested this locally and confirmed the following code fixed our issue and passed all the tests.
```
diff --git a/pkg/common/webhook/webhook.go b/pkg/common/webhook/webhook.go
index 7a32cc3e..78a5bd3d 100644
--- a/pkg/common/webhook/webhook.go
+++ b/pkg/common/webhook/webhook.go
@@ -203,8 +203,9 @@ func (w *Webhook) GetHTTPClient(provider *Spec) (*http.Client, error) {
        }

        tlsConf := &tls.Config{
-               RootCAs:    caCertPool,
-               MinVersion: tls.VersionTLS12,
+               RootCAs:       caCertPool,
+               MinVersion:    tls.VersionTLS12,
+               Renegotiation: tls.RenegotiateOnceAsClient,
        }
        client.Transport = &http.Transport{TLSClientConfig: tlsConf}
        return client, nil
```
