### ISSUE TITLE
Pulumi: Extracted secrets contain unwanted characters

### ISSUE THREAD

**Issue by alphayax** [external-secrets/external-secrets#3332]
**Describe the bug**
When using the extract feature with the pulumi provider, the extracted secrets who are strings contains double quotes

**To Reproduce**

#### Manifests
```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test-extract
  namespace: test

spec:
  dataFrom:
    - extract:
        conversionStrategy: Default
        key: test
  refreshInterval: 30m
  secretStoreRef:
    kind: ClusterSecretStore
    name: pulumi-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
```

On pulumi, values are : 
```json
{
  "test": {
    "bar": {
      "foo": "bar"
    },
    "foo": "bar",
    "foobar": 42
  }
}
```

#### Versions
- K8s version : 1.29.2
- ESO version : 0.9.14

**Expected behavior**
I want to have the string whitout quotes : `bar` instead of `"bar"`

**Screenshots**

```
$ kubectl get secret test-extract -o yaml | yq  .data
bar: eyJmb28iOiJiYXIifQ==
foo: ImJhciI=
foobar: NDI=

$ kubectl get secret test-extract -o yaml | yq  .data.foo | base64 -d
"bar"
```

**Additional context**
I'll made a PR with tests to fix this.
