### ISSUE TITLE
Unable extract Key and Certificate which has password protected from Azure Key Vault

### ISSUE THREAD

**Issue by kgopi1** [external-secrets/external-secrets#3351]
**Describe the bug**
Unable to sync the Azure key vault certificate with password protected to Kubernetes TLS type secret. 

**Error message:**

"error": "could not apply template: could not execute template: could not execute template: unable to execute template at key tls.key: unable to execute template at key tls.key: template: tls.key:1:36: executing \"tls.key\" at <pkcs12keyPass \"mypassword1234\">: error calling pkcs12keyPass: unable to decode pkcs12 with password: pkcs12: error reading P12 data: asn1: structure error: tags don't match (16 vs {class:0 tag:13 length:45 isCompound:true}) 

**To Reproduce**
1. provide all relevant manifests
My external secret yaml file. 
```
# creating tls-cert with password. 

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test-tls-example
  namespace: tls-example
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: my-clusterSecretStore
    kind: ClusterSecretStore
  target:
    name: my-tls-example
    # this is how the Kind=Secret will look like
    template:
      type: kubernetes.io/tls
      data:
        tls.crt: '{{ .mysecret | b64dec | pkcs12cert | pkcs12certPass "mypassword1234" }}'
        tls.key: '{{ .mysecret | b64dec | pkcs12key | pkcs12keyPass "mypassword1234" }}'
      engineVersion: v2
      mergePolicy: Replace

  data:
  # this is a pkcs12 archive that contains
  # a cert and a private key
  - secretKey: mysecret
    remoteRef:
      key: my-tls-cert

```

3. provide the Kubernetes and ESO version
Kubernetes version: 1.28.3
ESO Version:  0.9.1 

**Expected behavior**
TLS certificate needs to created in kubernetes. 

**Screenshots**

**Additional context**
