### ISSUE TITLE
Duplicate Secrets Created in Vault Due to PushSecret Feature Bug with ClusterSecretStore Path

### ISSUE THREAD

**Issue by framsouza** [external-secrets/external-secrets#3352]
There appears to be a malfunction within the PushSecret feature that leads to the creation of duplicate keys in Vault under certain conditions. Specifically, when a `ClusterSecretStore` is configured to target the `app/` directory and a PushSecret is used where the remoteKey also incorporates the `app/` path, Vault ends up generating two separate keys instead of one. This behavior is unintended and results in unnecessary duplication of secrets.

**Example**
_Config:_
The `ClusterSecretStore` is set to the `app/` path. A `PushSecret` is configured with a `remoteKey` that targets `app/dev/aws/my-app/credentials`.

_Observed Outcome_:
Instead of a single secret, Vault creates:
- One secret under `app/dev/aws/my-app/credentials` (as expected).
- An additional, unexpected secret under `app/app/dev/aws/my-app/credentials`.
This duplication is unintended and leads to confusion and potential security concerns by having an additional, unnecessary secret within Vault.

ESO version: 0.9.9

**Comment by Skarlso** [comment]
This is most likely caused by pushsecret pushing one-by-one instead of in a bulk. Or there is a lock needed for pushing so it sees the new environment before trying to do another push.

**Comment by gusfcarvalho** [comment]
I think this bug might be related due to `getMetadata` generating another path to put the metadata information.

@framsouza can you confirm one of these secrets contain a `custom_metadata` block while the other one does not? If this is confirmed, this is indeed a bug somewhere on the path generation for metadata with secretStores with explicit path.

**Comment by shxdxwraze** [comment]
any updates on this?

**Comment by gusfcarvalho** [comment]
hi @shxdxwraze . Since the user did not provide the extra information we were asking, it was closed as not planned.

**Comment by benke-lukas-futureplc** [comment]
Hi @gusfcarvalho 

we've encountered the same issue and I can confirm that the PushSecret indeed created one secret containing `custom_metadata` (the one with the extra `app/` in the path) and the other secret without the `custom_metadata`

To summarize what happens for us:

We have `ClusterSecretStore` configured to target the `app` directory - same as the OP

We have specified the following `PushSecret`

```yaml
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name:  api-key-push-secret
spec:
  updatePolicy: IfNotExists
  deletionPolicy: Delete
  secretStoreRefs:
    - name: some-store
      kind: ClusterSecretStore
  selector:
    generatorRef:
      apiVersion: generators.external-secrets.io/v1alpha1
      kind: Password
      name: api-key
  template:
    metadata:
      labels: # For some reason, these do not make it to Vault
        # Environment for which the key will be generated
        environment: prod
        # Who requested the key
        requester: some-app
  data:
    - match:
        secretKey: password # property in the generator output
        remoteRef:
          remoteKey: app/app-name/api-keys/requester
          property: api_key
```

Once synced, we get two secrets in Vault:

1) `app/app-name/api-keys/requester`
This one is in the expected path and has the correct secret value, but no metadata

2) `app/app/app-name/api-keys/requester`
This one has an extra `app/`, there is no value for the secret (no versions) - but it has metadata - worth noting that the only metadata is `managed-by: external-secrets` but none of my custom metadata defined in the `template.metadata.labels` in the `PushSecret`

Any idea what could be wrong? 

Please let me know if I can provide anything else :)

Thank You!
