### ISSUE TITLE
dataFrom can't extract keys with underscores

### ISSUE THREAD

**Issue by kbsquared** [external-secrets/external-secrets#3363]
**Describe the bug**
ESO can not extract keys with underscores in them.

**To Reproduce**
```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test-secret
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: example
    kind: SecretStore
  target:
    name: k8s-secret
  # this works
  #data:
  #- secretKey: TEST_SECRET
    #remoteRef:
      #key: staging/TEST_SECRET
  # this dataFrom guy doesn't like the underscores
  dataFrom:
  - extract:
      key: staging/TEST_SECRET
```
Create a key with an underscore in the name and then try to use dataFrom to extract it.

k8s version v1.27.7
ESO version v0.9.9

Message:
Secret "test-secret" is invalid: data[]: Invalid value: "": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+')

**Expected behavior**
This works if you're using data instead of dataFrom.  And the warning says underscores are valid.  I would expect this to work.
