### ISSUE TITLE
Extend Azure Key Vault Provider's authType 'WorkloadIdentity' to include clientID and TenantID sourced from authSecretRef

### ISSUE THREAD

**Issue by mehighlow** [external-secrets/external-secrets#3366]
**Is your feature request related to a problem? Please describe.**

Azure Key Vault Provider's authType 'WorkloadIdentity' requires the Service Account to have the following annotations set, which is the default way of ingesting clientId and tenantId into the pod:
```yaml
    azure.workload.identity/client-id: 7d8cdf74-xxxx-xxxx-xxxx-274d963d358b
    azure.workload.identity/tenant-id: 5a02a20e-xxxx-xxxx-xxxx-0ad5b634c5d8
```
I'm leveraging Azure Service Operator to create Azure resources and bundle our applications together with these resources' CRDs. Since Helm lacks dependency management (and seems like it will never support it based on discussions in the Helm threads) and deploys everything together, it creates an interpolation problem because the `clientId` is not known at the time of deployment, and thus I can't set annotations.

However, `clientId` and `tenantId` can be injected directly into the pod as environment variables via secret or configMap reference (which is a common workaround) as WorkloadIdentity hook reads these environment variables to perform authentication. 

**Describe the solution you'd like**
Add `authSecretRef` configuration to the `SecretStore` when `authType` is set to `WorkloadIdentity`.

e.g.
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  # this service account was created by azwi
  name: workload-identity-sa
  annotations: {}
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: azure-store
spec:
  provider:
    azurekv:
      # tenantId spec option #1
      tenantId: "5a02a20e-xxxx-xxxx-xxxx-0ad5b634c5d8"
      authType: WorkloadIdentity
      vaultUrl: "https://xx-xxxx-xx.vault.azure.net"
      serviceAccountRef:
        name: workload-identity-sa
      authSecretRef:
        clientId:
          name: umi-secret
          key: clientId
        # tenantId spec option #2
        tenantId:
          name: umi-secret
          key: tenantId
```

**Describe alternatives you've considered**
* A hook/job that patches SA annotations.
This solution adds unnecessary complexity, noise, and makes configuration tangled.
* A mutating admission webhook. 
Timeout is limited to 30 seconds, which might be not enough for Azure Service Operator to create ManagedIndetity.

**Additional context**
Azure Service Operator only supports the export of `clientId` and `tenantId` in the form of a ConfigMap only at this time. I have implemented the export in a form of secrets as well, which you can find here: https://github.com/Azure/azure-service-operator/pull/3937.
I also had a conversation with Azure Service Operator maintainer (@matthchr) and he agrees to merge PR if this feature request is approved.
