### ISSUE TITLE
Can't retrieve secrets when working with Gitlab variables at group level defined for different environments

### ISSUE THREAD

**Issue by felixprado-mc** [external-secrets/external-secrets#3379]
**Describe the bug**
We are getting an error when retrieving some variables in Gitlab that:
- Are defined at the group level (instead of the project level).
- Have different values for environments (review/*, dev, stage and prod)

The error we receive is:
`error retrieving secret at .data[1], key: MY_VARIABLE, err: GET https://gitlab.com/api/v4/groups/XXXXXXX/variables/MY_VARIABLE: 409 {message: There are multiple variables with provided parameters. Please use 'filter[environment_scope]'}`

I'm pretty convinced that in this particular case, the query does not includes that filter. I have made the same request with Postman (see snapshots) and using the same token that ExternalSecret uses and I can retrieve the variable:

**To Reproduce**
1- These are my manifests. You can't reproduce the issue but at least see the configuration.
2. Kubernetes version; v1.27.9
   ESO: v0.9.14

```
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: my-product
spec:
  provider:
    gitlab:
      auth:
        SecretRef:
          accessToken:
            key: EXTERNAL_SECRETS_GITLAB_TOKEN
            name: external-secret-gitlab-token
      environment: dev
      groupIDs:
      - "{my_group_id}"
      projectID: "{my_project_id}"
```

```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name:  my-product
spec:
  data:
  - remoteRef:
      key: MY_VARIABLE
    secretKey: MY_VARIABLE
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name:  my-product
  target:
    creationPolicy: Owner
    name: secrets-external
```

**Expected behavior**
The variable can be retrieved as any other using ExternalSecrets even if it has different values per environment.

**Screenshots**
![image](https://github.com/external-secrets/external-secrets/assets/144702716/c9a7c34c-0261-4f94-bd97-3790c4a79aa6)
---
![image](https://github.com/external-secrets/external-secrets/assets/144702716/9e5cbd7d-7556-4d01-bfd8-96e2a1035be7)

**Additional context**

**Comment by Farfaday** [comment]
I can confirm the issue as I also am affected :)

**Comment by felixprado-mc** [comment]
The bug is still there.

**Comment by Skarlso** [comment]
@hpza can you test with 0.14.2 please? We made some fixes to gitlap provider.

**Comment by hpza** [comment]
Hi, thanks, I can confirm, that it is working again :-)

**Comment by fprado** [comment]
Any idea? We are still suffering this bug.

Thank you.

**Comment by Skarlso** [comment]
What's your current error / version of ESO?

**Comment by fprado** [comment]
> What's your current error / version of ESO?

v0.14.3

**Comment by Skarlso** [comment]
Sadly, we aren't supporting that version anymore. Can you please try the latest version or at least 0.16.0?

**Comment by gusfcarvalho** [comment]
@fprado  - according to your error message:

```
Unable to save changes: error patching resource: admission webhook "validate.secretstore.external-secrets.io" denied the request: defining groupIDs and inheritFromGroups = true is not allowed
```

try removing the groupIDs from your manifest.

**Comment by fprado** [comment]
@Skarlso 

We'll update the version and test it again.

Thanks!

**Comment by fprado** [comment]
ESO v0.16.1 installed.

Still having this error in the ExternalSecret object:

> error processing spec.data[0] (key: DUMMY_CI_VARIABLE_GITLAB), err: GET https://gitlab.com/api/v4/groups/xxxxxx/variables/DUMMY_CI_VARIABLE_GITLAB: 409 {message: There are multiple variables with provided parameters. Please use 'filter[environment_scope]'}

I have created 4 variables in Gitlab at **Group level** (so they are inherited to Project level) , all of them with the same name (`DUMMY_CI_VARIABLE_GITLAB`) but different environment (`review/*`, `dev`, `stage`, `prod`) and values.

These are my SecretStore:
```

apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  labels:
    app.kubernetes.io/name: blueprint
  name: blueprint
  namespace: platform
spec:
  provider:
    gitlab:
      auth:
        SecretRef:
          accessToken:
            key: EXTERNAL_SECRETS_GITLAB_TOKEN
            name: trx-external-secret-gitlab-token
      environment: dev
      groupIDs:
      - "xxxxxx"
      projectID: "xxxxxx"
```


And ExternalSecret object:

```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: blueprint
spec:
  data:
  - remoteRef:
      key: DUMMY_CI_VARIABLE_GITLAB
    secretKey: DUMMY_EXTERNAL_SECRET_VALUE
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: blueprint
  target:
    creationPolicy: Owner
    name: blueprint-external
```

@Skarlso, can you support here?
