### ISSUE TITLE
Azure-Vault certificate returned in DER format

### ISSUE THREAD

**Issue by FelixRTU** [external-secrets/external-secrets#3381]
**Describe the bug**
Azure-Vault provider returns certs in DER format and no template function exists to process this format and to create a valid kubernetes tls secret.

**To Reproduce**
1. Create ExternalSecret requesting a certificate from an azure-vault
```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: azure-cert
  namespace: default
spec:
  data:
  - secretKey: rawCertData
    remoteRef:
      conversionStrategy: Default
      key: cert/my-azure-cert
  refreshInterval: 15m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name:  my-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: azure-cert
    template:
      type: Opaque
      data:
        raw: "{{ .rawCertData }}"
```

2. Download certificate via cli in DER encoding
` az keyvault certificate download --vault-name "<vault name>" --name "<cert name>" --encoding DER --file /dev/stdout`
3. Get kubernetes secret value returned from vault
`kubectl get secrets/azure-cert --template={{.data.raw}}`
4. Compare both outputs from cli and kubernetes secret

**Expected behavior**

The kubernetes secret contains a certificate in PEM format or PKCS. In my example both outputs are the same which shows that the format of the kubernetes secrets is in the DER format, as i explicitly got the cli output in that format.
