### ISSUE TITLE
External Secrets Operator Advanced Templating with External ConfigMaps

### ISSUE THREAD

**Issue by ContainerDevCloud** [external-secrets/external-secrets#3387]
I'm trying to inject some values to my `ConfigMap` using External Secrets Operator. The `ConfigMap` is created using a YAML file. The YAML file looks like below. 

**aws-secrets.yml**
```
credentials:
  s3:
    access-key:  aws_s3_access_key # These needs to be replaced  
    secret-key:  aws_s3_secret_key # These needs to be replaced  
```

I have templated my **aws-secrets.ym**l as below.

```
credentials:
  s3:
    access-key: "{{ .aws_s3_access_key }}"
    secret-key: "{{ .aws_s3_secret_key}}"
```

I need to inject the `aws_s3_access_key`  and `aws_s3_secret_key` from Hashicorp Vault using ESO. I have already created the `SecretStore` and it's synced with Hashicorp Vault and able to successfully fetch the `aws_s3_access_key`  and `aws_s3_secret_key`  from Vault and create as a Kubernetes secret. But when I describe the `ConfigMap`, it hasn't replaced the `aws_s3_access_key ` and `aws_s3_secret_key`  The ConfigMap still shows as the same way as above (YAML file above). Below is my `ExternalSecret`.

```
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: aws-secrets
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-secretstore
    kind: SecretStore
  target:
    name: aws-secrets
    template:
      engineVersion: v2
      templateFrom:
      - configMap:
            name: aws-secrets-configmap
            items:
            - key: aws-secrets.yml
  data:
    - secretKey: aws_s3_access_key
      remoteRef:
        key: kv/data/aws
        property: aws_s3_access_key
    - secretKey: aws_s3_secret_key
      remoteRef:
        key: kv/data/aws
        property: aws_s3_secret_key
```

So when I describe the `ConfigMap`, it hasn't replaced the values. It looks like below.

```
Name:         aws-secrets-configmap
Namespace:    aws-service-test
Labels:       currently-used-by-kustomize=true
Annotations:  <none>

Data
====
aws-secrets.yml:
----
credentials:
  s3:
    access-key: "{{ .aws_s3_access_key }}"
    secret-key: "{{ .aws_s3_secret_key}}"


BinaryData
====

Events:  <none>
```

Any idea why it hasn't replaced with the actual secrets (`aws_s3_access_key`  and `aws_s3_secret_key`) which are fetched from vault?
