### ISSUE TITLE
GCP Secret Manager Integration: Unable to authenticate the Anthos cluster secret store using GCP Workload Identity

### ISSUE THREAD

**Issue by Kalaivani19** [external-secrets/external-secrets#3408]
GCP Secret Manager Integration: Unable to authenticate the cluster secret store using GCP Workload Identity
 
**Error message:** Warning  InvalidProviderConfig  11m (x71 over 14h)  cluster-secret-store  failed to create GCP secretmanager client: unable to fetch identitybindingtoken: could not get idbindtoken token, status: 404
GSA service account is associated to Kubernetes service account and namespace. Here is the o/p of “gcloud iam service-accounts get-iam-policy external-secrets-d@dev-project.iam.gserviceaccount.com" command:
bindings:
- members:
  - serviceAccount:dev-project.svc.id.goog[es/external-secrets]
  role: roles/iam.workloadIdentityUser

GSA service account “external-secrets-d” has roles/secretmanager.secretAccessor and roles/iam.serviceAccountTokenCreator roles.

**KSA Service Account is annotated with the GSA service account:**

Annotations: iam.gke.io/gcp-service-account: external-secrets-d@dev-project.iam.gserviceaccount.com

**Manifest file:**
```
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-store
spec:
  provider:
    gcpsm:
      projectID: dev-project
      auth:
        workloadIdentity:
          # name of the cluster Location, region or zone
          clusterLocation: us-central1
          # name of the GKE cluster
          clusterName: dev-cluster
          # projectID of the cluster (if omitted defaults to spec.provider.gcpsm.projectID)
          clusterProjectID: dev-project
          # reference the sa from above
          serviceAccountRef:
            name: external-secrets
            namespace: es
```
gcloud container fleet memberships describe dev-project—The manifest above uses the location that this command returns.
Please note that we're able to authenticate using the same GSA service account key JSON file and access the secrets from GCP secret manager.

Any suggestions or leads would be highly appreciated. Thanks in advance!

**Comment by gusfcarvalho** [comment]
hi @Kalaivani19 ! This error is typically when there is a typo on the KSA/GSA names - as the error is basically that there is no valid `external-secrets-d` GSA for ESO KSA to consume.


However -  if you intend to use GSA on `external-secrets` service account, you can try this simpler manifest here:

```
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-store
spec:
  provider:
    gcpsm:
      projectID: dev-project
```

**Comment by Kalaivani19** [comment]
@gusfcarvalho - Thank you for your input. I am currently using Fleet Workload Identity on Anthos cluster. Could you please confirm whether the ESO operator is compatible with the Fleet WI of this cluster? I am experiencing issues that appear to be related to the following threads:
https://github.com/external-secrets/external-secrets/issues/1641
https://github.com/external-secrets/external-secrets/issues/1946
Your assistance in resolving these issues would be greatly appreciated.

**Comment by andrzejkaras** [comment]
I have similar issue. My config:

```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: integration-secrets
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: integration-secrets
    kind: ClusterSecretStore
  target:
    name: integration-secrets
    creationPolicy: Owner
  data:
    - secretKey: some-key
      remoteRef:
        key: some-remote-key
        version: latest
```

```yaml
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: integration-secrets
spec:
  provider:
    gcpsm:
      projectID: my-project-id
      auth:
        workloadIdentity:
          # name of the cluster region
          clusterLocation: my-location
          # name of the GKE cluster
          clusterName: cluster-name
          serviceAccountRef:
            name: my-sa-name
            namespace: {{ .Release.Namespace }}
```

I checked a couple of potential causes:
- Workload Identity Not Enabled on the Cluster - confirmed it's enabled
- IAM Role Bindings Missing or Incorrect on the Cluster - confirmed bindings are correct
- Kubernetes Service Account (KSA) Annotation Missing or Incorrect - GSA and KSA are mapped correctly
- Network Policies Blocking Metadata Server Access - we have custom network policy, but e.g. `169.254.169.252/32` is whitelisted, should I whitelist a namespace where external-secrets are deployed?
- Differences in GKE Versions or Configuration - on a cluster that it does not work I have `1.28.12-gke.1052000`, but I have different cluster with `1.29.6-gke.1326000` where everything works as it should be (I used there older versions and it worked too, so I think this is not a cause). I used `0.9.19` and `0.10.2` of external secrets, but with no luck.

I still have an error like this: `Warning  InvalidProviderConfig  14m (x19 over 36m)  cluster-secret-store  failed to create GCP secretmanager client: unable to fetch identitybindingtoken: could not get idbindtok │
│ en token, status: 404` 

In addition:
- I can retrieve secret by using shell from pod that is in my namespace and it's having correct SA attached. When I run: `gcloud secrets versions access latest --secret=my-secret --project=my-project` then I am getting secret value. But when I try to do the same via ESO I got an error shown above.
- When I call this `curl -H "Metadata-Flavor: Google" "http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/token"` from the same pod I mentioned above, then I am getting access token response.
- I am trying to retrieve secrets from GCP Secret Manager.

Please let me know what else could be missconfigured or what I should provide so you could help me to resolve this issue. Thanks!

**Comment by andrzejkaras** [comment]
I had the same error when I had `clusterLocation` set incorrectly.

```yaml
spec:
  provider:
    gcpsm:
      projectID:
      auth:
        workloadIdentity:
          clusterLocation: 
```
