### ISSUE TITLE
ClusterSecretStore "unable to create client"

### ISSUE THREAD

**Issue by AndreasBergmeier6176** [external-secrets/external-secrets#3412]
**Describe the bug**
I have a ClusterSecretStore. When I look at the status it says:

```
status:
  conditions:
  - lastTransitionTime: "2024-04-24T10:08:20Z"
    message: unable to create client
    reason: InvalidProviderConfig
    status: "False"
    type: Ready
```

**To Reproduce**
1. Create 1.28 GKE Autopilot cluster.
1. Deploy latest ESO
1. Deploy:
  ```
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp
spec:
  provider:
    gcpsm:
      projectID: foo

  ```
4. Look at `gcp` status.

**Expected behavior**
It should either work or at least provide a meaningful error/tracing. There is no output in ESO pods.

**Additional context**
We have a 1.27 cluster in another GCP project, where the same config works.
