### ISSUE TITLE
Support for AWS Secrets Engine in Hashicorp Vault Provider

### ISSUE THREAD

**Issue by tech1ndex** [external-secrets/external-secrets#3418]
**Is your feature request related to a problem? Please describe.**
We use the [AWS Secrets Engine](https://developer.hashicorp.com/vault/docs/secrets/aws) in Vault to ease authentication for some workloads that we need to connect to AWS Services.

**Describe the solution you'd like**
I would love a field added under the SecretStore or ClusterSecretStore Schema to support this Secrets Engine. Perhaps something like `engine:` under `vault:` that defaults to `kv` unless you specify something else, ie. aws. This of course could then toggle something like the version tag to be required (secrets) or not required (other), along with any other required schema validation.

**Describe alternatives you've considered**
At the moment, the only alternative would need to be to continue to use vault-injector which will soon be deprecated, or try to leverage the AWS Secrets manager itself which breaks the current pattern of using Vault for secret management.

**Comment by gusfcarvalho** [comment]
hi @tech1ndex ! Did you try using Vault Dynamic Secrets? With it, it is virtually possible to use any Vault provider.

**Comment by gusfcarvalho** [comment]
link to appropriate documentation https://external-secrets.io/latest/api/generator/vault/

**Comment by tech1ndex** [comment]
Hey @gusfcarvalho ,

I will give this a shot, I see in the example there it is using the POST method but I assume GET is available as well?

**Comment by tech1ndex** [comment]
Hi @gusfcarvalho 

Configured the following:

```
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: VaultDynamicSecret
metadata:
  name: "vault-aws-backend"
  namespace: monitoring
spec:
  path: "nanny/${cloudProvider}/${name}/creds/secret"
  method: "GET"
  provider:
    server: "${vaultAddr}"
    auth:
      jwt:
        # Path where the Kubernetes authentication backend is mounted in Vault
        path: "jwt-cp/${name}-control-plane-jwt-method"
        # A required field containing the Vault Role to assume.
        role: REPLACE_ME
        kubernetesServiceAccountToken:
          serviceAccountRef:
            name: REPLACE_ME
```
Getting the following when trying to create the secret:

Status:
  Conditions:
    Last Transition Time:  2024-05-03T18:44:50Z
    Message:               could not get secret data from provider
    Reason:                SecretSyncedError
    Status:                False
    Type:                  Ready
Events:
  Type     Reason        Age                   From              Message
  ----     ------        ----                  ----              -------
  Warning  UpdateFailed  3m21s (x19 over 14m)  external-secrets  could not generate [0]: unable to setup Vault client: Error making API request.
  
  Normally I would say permissions, but checked the vault jwt role and testing connecting to this path with the CLI. 
 Everything works as expected.
