### ISSUE TITLE
fix documentation for Aws irsa provider

### ISSUE THREAD

**Issue by alekc** [external-secrets/external-secrets#342]
I was trying to implement an aws Irsa approach by following https://external-secrets.io/provider-aws-secrets-manager/

On that page, there is a following example:

```yaml
apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: secretstore-sample
spec:
  provider:
    aws:
      service: SecretsManager
      auth:
        jwt:
          serviceAccountRef:
            name: my-serviceaccount
```

however, when I was trying to apply a pretty much similar object, I got following error:
`SecretStore.external-secrets.io "xxxxxx" is invalid: spec.provider.aws.region: Required value`

I am not 100% sure if in this case the `region` field can be omitted (by assuming the same region as the assumed role), if not the documentation should be amended and the region added to the example above.
