### ISSUE TITLE
Expose logging options like human readable verbose and json format in values.yaml

### ISSUE THREAD

**Issue by rojomisin** [external-secrets/external-secrets#3440]
**Is your feature request related to a problem? Please describe.**
It would be very helpful to make the logs more readable and operator friendly to expose simple yaml options in the helm chart. Cert-manager does this like:
```
## -- Map of extra arguments to pass to container.
extraArgs:
  zap-time-encoding: iso8601
  loglevel: debug
```
and it's documented on their site

**Describe the solution you'd like**
`helm show values external-secrets/external-secrets` should show a default values.yaml file which shows the currently logging settings and commented out reference docs on how to enable json, human readable, and verbosity level settings

**Describe alternatives you've considered**
n/a

**Additional context**
n/a
