### ISSUE TITLE
PushSecret spec.template is not propagated with a Kubernetes cluster->cluster SecretStore

### ISSUE THREAD

**Issue by pre** [external-secrets/external-secrets#3443]
According to the documentation in <https://external-secrets.io/v0.9.17/guides/pushsecrets/>, PushSecret spec.template exists. However, nothing is copied with a Kubernetes cluster->cluster SecretStore.

External Secrets Operator v0.9.17

**To Reproduce**
Given the following PushSecret, only the attribute defined in `spec.data` is copied to the remote Secret. 

Nothing from `spec.template.metadata.labels` or `spec.template.data` is copied to the remote Secret.

I also tried what happens when `spec.data` is not present at all: then the remote Secret is not created at all even though PushSecret `.status` shows `message: PushSecret synced successfully`.

```yaml
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: ps-example
spec:
  refreshInterval: 30m
  secretStoreRefs:
  - name: example-store
    kind: SecretStore
  selector:
    secret:
      name: exaple-secret 
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: argocd
    data:
      example-1: "{{ .url | toString }}"
  # Pushing a whole secret is not yet possible in v0.8.3 so individual keys need to be picked
  # https://github.com/external-secrets/external-secrets/issues/2836
  data:
  - match:
      secretKey: url
      remoteRef:
        remoteKey: example-remote-key
        property: url

```

**Expected behavior**
The `.spec.template` should be reflected to the remote Secret.

Related
* https://github.com/external-secrets/external-secrets/issues/2836
* https://github.com/external-secrets/external-secrets/issues/3353

**Comment by ron1** [comment]
What provider are you using? Using the kubernetes provider, `.spec.template.data` behaves as expected for me. As mentioned in https://github.com/external-secrets/external-secrets/issues/3353, `.spec.template.metadata` is currently broken.

**Comment by pre** [comment]
I'm using the Kubernetes provider with External Secrets Operator v0.9.17.

Given the following SecretStore

```yaml
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: example-secretstore
spec:
  provider:
    kubernetes:
      auth:
        token:
          bearerToken:
            name: example-resource-name
            key: token
      remoteNamespace: argocd
      server:
        url: ".. api url .."
        caProvider:
          type: Secret
          name: example-resource-name
          key: ca.crt
```

The following `PushSecret` only copies the `url` attribute. The `example-1` attribute is not present in the remote Secret (only `url` is).

```yaml
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: ps-example
spec:
  refreshInterval: 30m
  secretStoreRefs:
  - name: example-secretstore
    kind: SecretStore
  selector:
    secret:
      name: example-source-secret
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: argocd
    data:
      example-1: "test"
  data:
  - match:
      secretKey: url
      remoteRef:
        remoteKey: example-remote-secret
        property: url
```

**Comment by ron1** [comment]
Does the `spec.template.data` get pushed it if you remove the `property` field as is done in the example on the following page? https://external-secrets.io/latest/api/pushsecret/

**Comment by gusfcarvalho** [comment]
@ron1  you can even do it - but then you need to address the generated template property:

```
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: ps-example
spec:
  refreshInterval: 30m
  secretStoreRefs:
  - name: example-secretstore
    kind: SecretStore
  selector:
    secret:
      name: example-source-secret
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: argocd
    data:
      example-1: "test"
  data:
  - match:
      secretKey: url
      remoteRef:
        remoteKey: example-remote-secret
        property: example-1 ## Valid
```

**Comment by belaytzev** [comment]
I have the same issue, and neither `.spec.template.metadata` nor `.spec.data[0].metadata` are working right now

**Comment by moolen** [comment]
Thanjs for bumping this issue, i'll take a look at it.

**Comment by moolen** [comment]
:wave: Hello folks, i have a proposal in #3600, please take a look at the design, it should address all points raised in this issue. I'll leave the PR open for a couple of weeks to get feedback on the design.

**Comment by ErikLundJensen** [comment]
Do we have room for a simpler implementation than PR #3600 ?

**Comment by pre** [comment]
Not stale

**Comment by Skarlso** [comment]
We don't use a bot, it's just a github action. Sorry. Is this _STILL_ not working? :D Could you please check? @pre 

I will fix it if not.

**Comment by pre** [comment]
Right! I’ll attempt to try this out ”next week”. 

Thanks

**Comment by aabouzaid** [comment]
The same issue, `spec.template` doesn't render when  `property` is set, which is required by the K8s provider.

Here is an example where the `spec.template` has no effect at all.

I think the property key affects the template functionality.


This works:

```
apiVersion: external-secrets.io/v1beta1
kind: PushSecret
metadata:
  name: template
spec:
  # ...
  template:
    engineVersion: v2
    data:
      token: "{{ .token | toString | upper }} was templated"
  data:
    - match:
        secretKey: token
        remoteRef:
          remoteKey: create-secret-name
          property: token # this key "token" is the same as the key "spec.template.data.token"
```


This does **NOT** work:

```
apiVersion: external-secrets.io/v1beta1
kind: PushSecret
metadata:
  name: template
spec:
  # ...
  template:
    engineVersion: v2
    data:
      url: "{{ .token | toString | upper }} was templated"
  data:
    - match:
        secretKey: token
        remoteRef:
          remoteKey: create-secret-name
          property: token # this key "token" is not the same as the key "spec.template.data.url"
```

That creates a secret with the key `data.token`, which has the same data as the key in the source/remote secret `create-secret-name` (no templating happens at all).

Tested with latest ESO (v0.17.0).

**Comment by gusfcarvalho** [comment]
> The same issue, `spec.template` doesn't render when `property` is set, which is required by the K8s provider.
> 
> Here is an example where the `spec.template` has no effect at all.
> 
> I think the property key affects the template functionality.
> 
> This works:
> 
> ```
> apiVersion: external-secrets.io/v1beta1
> kind: PushSecret
> metadata:
>   name: template
> spec:
>   # ...
>   template:
>     engineVersion: v2
>     data:
>       token: "{{ .token | toString | upper }} was templated"
>   data:
>     - match:
>         secretKey: token
>         remoteRef:
>           remoteKey: create-secret-name
>           property: token # this key "token" is the same as the key "spec.template.data.token"
> ```
> 
> This does **NOT** work:
> 
> ```
> apiVersion: external-secrets.io/v1beta1
> kind: PushSecret
> metadata:
>   name: template
> spec:
>   # ...
>   template:
>     engineVersion: v2
>     data:
>       url: "{{ .token | toString | upper }} was templated"
>   data:
>     - match:
>         secretKey: token
>         remoteRef:
>           remoteKey: create-secret-name
>           property: token # this key "token" is not the same as the key "spec.template.data.url"
> ```
> 
> That creates a secret with the key `data.token`, which has the same data as the key in the source/remote secret `create-secret-name` (no templating happens at all).
> 
> Tested with latest ESO (v0.17.0).


I don’t think this issue is related. Your template is creating a `url` key and you specified to push the `token`, non-templated key.

**Comment by aabouzaid** [comment]
@gusfcarvalho Thanks for your reply. I may be missing something, so please correct me if I'm wrong.

I want to create a new secret with a key called `url`, which is a composition of, let's say, `user` and `token`.


Then, I will create a template like this:

```
apiVersion: external-secrets.io/v1beta1
kind: PushSecret
metadata:
  name: template
spec:
  # ...
  template:
    engineVersion: v2
    data:
      url: "{{ .user }}:{{ .token }}"
  data:
    - match:
        secretKey: user
        remoteRef:
          remoteKey: create-secret-name
          property: user
    - match:
        secretKey: token
        remoteRef:
          remoteKey: create-secret-name
          property: token
```

The desired Secret that should be created:

```
apiVersion: v1
kind: Secret
metadata:
  name: create-secret-name
data:
  url: "..."
```

What's actually created:

```
apiVersion: v1
kind: Secret
metadata:
  name: create-secret-name
data:
  user: "..."
  token: "..."
```

**Comment by gusfcarvalho** [comment]
You are using PushSecret wrong 🙂 and this is heavily documented on our documentation page. I’d favor you to read it first as to support the countless hours of efforts done by this community to create and maintain that documentation page

**Comment by aabouzaid** [comment]
@gusfcarvalho I read multiple pages in the docs like [PushSecret](https://external-secrets.io/latest/api/pushsecret/) and [templating with PushSecret](https://external-secrets.io/latest/guides/templating/#templating-with-pushsecret), but it's not clear to me how to do it so far (I've been using ESO for some years now, but this is my first time using PushSecret, so maybe I'm missing the logic here).

Could you please refer me to the page in the docs that explains what I want to achieve? 🙌

**Comment by gusfcarvalho** [comment]
https://external-secrets.io/latest/api/pushsecret/ With several in-line comments on how it works 🙂

You need to specify: secretKey as the templated key. You’re templating the information and not using it across your manifests.

**Comment by aabouzaid** [comment]
Thank you, I will give it another try 👍

**Comment by aabouzaid** [comment]
OK, I achieved it (thanks to your tip in the last comment).

The confusion comes from the docs using the same keys everywhere, so it wasn't clear which one was from the source and which was from the template.


```
apiVersion: external-secrets.io/v1beta1
kind: PushSecret
metadata:
  name: template
spec:
  # ...
  template:
    engineVersion: v2
    data:
      url: "{{ .user }}:{{ .token }}" # <= The ".user" and ".token" come from the source secret.
  data:
    - match:
        secretKey: url
        remoteRef:
          remoteKey: create-secret-name
          property: url
```

I will create a PR with a full example to add to the [PushSecret templating section](https://external-secrets.io/latest/api/pushsecret/#templating), so it saves the time for the next person as it's that clear as it seems.
