### ISSUE TITLE
Support for Azure KV Authentication with ClientCertificate

### ISSUE THREAD

**Issue by lieberlois** [external-secrets/external-secrets#3461]
**Is your feature request related to a problem? Please describe.**
I find that the operator should be able to authenticate via ClientCredentials. This is an easy implementation since the used kvauth package already supports this: https://pkg.go.dev/github.com/Azure/go-autorest/autorest/azure/auth#NewClientCertificateConfig

**Describe the solution you'd like**
In the perfect world, it should be possible to configure a `SecretStore` and a `ClusterSecretStore` to fetch the clientCertificate key from a secret and use that for authentication against Azure KV rather than the clientSecret field.

**Describe alternatives you've considered**
None

**Additional context**
This is how I want the CRD to work:

```yaml
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: store
spec:
  provider:
    azurekv:
      authSecretRef:
        clientId:
          key: ClientID
          name: azure-secret-sp
        clientCertificate:
          key: ClientCertificate
          name: azure-secret-sp
      authType: ServicePrincipal
      environmentType: PublicCloud
      tenantId: <omitted>
      vaultUrl: "https://<kv>.vault.azure.net/"
```

If somebody is willing to point me to the relevant code locations, I am very happy to contribute this myself, if others agree that this would be a good feature!
