### ISSUE TITLE
Removal of namespace qualifier for clustersecretstore fixes "invalid vault credentials: configured Vault token contains non-printable" but produces not found error in pod

### ISSUE THREAD

**Issue by ndlanier** [external-secrets/external-secrets#3473]
**Describe the bug**
ClusterSecretStores in my deployment were seeing _invalid vault credentials: configured <enter provider name here> token contains non-printable characters. The references to the credentials for the secret stores have namespace fields. When the namespace fields are removed, the clustersecretstores start validating but the pod reports the credential is not found. When put back in place they are unable to authenticate as ESO cannot find the credential or it sees it as invalid.

In our case the ESO deployment lives in the same namespace as the secrets for the clustersecretstores, "external-secrets"

```
spec:
  provider:
    vault:
      auth:
        tokenSecretRef:
          key: token
          name: vault-token
          namespace: external-secrets
      path: ci
      server: 'redacted'
      version: v2
```

```
spec:
  provider:
    gcpsm:
      auth:
        secretRef:
          secretAccessKeySecretRef:
            key: secret-access-credentials
            name: gcpsm-secret
            namespace: external-secrets
      projectID: redacted
```

**To Reproduce**
1. See above manifests
2. GKE 1.26, ESO 0.9.14

**Expected behavior**
The expected behavior is that the credentials are supposed to be seen and be valid with the namespace field filled out in accordance with the ESO documentation on ClusterSecretStores.
