### ISSUE TITLE
Empty ExternalSecret should create an empty Secret instead of not creating anything

### ISSUE THREAD

**Issue by stephen-dexda** [external-secrets/external-secrets#3478]
The following:

```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: foo
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: foo
  target:
    name: foo
  data: []
```

Should result in an empty secret (which is perfectly valid) as follows:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: foo
type: Opaque
data:
```

Currently (with 0.9.17), the ExternalSecret "syncs", but no corresponding Secret is created.

Example use case: workloads that have a secret mounted and monitor that mount location for changes (so need the secret to exist in order to start), and where the secret's contents are populated/varied separately from its creation.

**Comment by gusfcarvalho** [comment]
sorry - if you need the secret to exist before application is there - did you try to `template` any known value, or just some mock data?

Regarding the issue itself - I do not agree with you that this is a bug, but rather a feature. The operator should decide when to create a secret (and when to not create it), as the ownership of that object is theirs. This does means not creating a secret when there is no secret to create.

**Comment by kartoch** [comment]
@gusfcarvalho Could you give an example ?

I've tried the following, but `data` requires at least one entry:

```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dummy
  namespace: default
spec:
  data: []
  refreshInterval: 2m
  secretStoreRef:
    kind: ClusterSecretStore
    name: dummy-backend
  target:
    name: dummy
    template:
      data: {}
      type: Opaque
```

Output:
```
admission webhook "validate.externalsecret.external-secrets.io" denied the request: either data or dataFrom should be specified
```

**Comment by cmateos-holcim** [comment]
Hello @gusfcarvalho 

> The operator should decide when to create a secret (and when to not create it), as the ownership of that object is theirs.

It would be nice to have the ability to choose whether the secret is created or not, as long as someone might want to create the secrets even if it is empty.
For example, a platform engineer could deploy some empty secret at a provider and mount the values of the secret as pods environment variables. Later provide permissions to the development team to add any pair of key:value data into the secrets and expect that data to be synced and created as environment variables inside the pod.

```
kind: Pod
apiVersion: v1
metadata:
  name: example-pod
spec:
  containers:
      name: my-expample-container
      envFrom:
        - secretRef:
            name: my-secrets
      image: example_Image
```

The problem is that while the secret is not created, the pod is not capable to start as the secret does not exist and can not be mounted.

**Comment by ivasilyev-servicetitan-com** [comment]
I was debugging while k8s secret was not creating like 2 days.
What would help me to realize Azure KV has no secrets, if external operator controller logged a warning message.
Instead operator logs normal message
```
{"level":"info","ts":1738964007.6005616,"logger":"controllers.ExternalSecret","msg":"reconciled secret","ExternalSecret":{"name":"<REDACTED>","namespace":"<REDACTED>"}}
```

If log messaging can be improved here, that will make sense

**Comment by Skarlso** [comment]
Can you try with `loglevel` set to `debug`

**Comment by int128** [comment]
I found a workaround for this issue. By setting the `deletionPolicy` to `Merge`, the controller creates an empty Secret. For example,

```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
spec:
  target:
    # Create a secret even if the data source is empty
    deletionPolicy: Merge
```

The controller continues the reconcilation process when deletionPolicy is Merge.
https://github.com/external-secrets/external-secrets/blob/de14523e4bfedd6f85798967c80ed38925258bc7/pkg/controllers/externalsecret/externalsecret_controller.go#L327-L367

**Comment by Skarlso** [comment]
This would be a change from expected behavior where if nothing exists nothing is created. Maybe, it would work with a `creationPolicy: Empty` or something. But in that case, you can't use a different creation policy.

**Comment by Skarlso** [comment]
_Note_ that this will also cause deletion not to happen. Meaning if creation Policy is `Empty` if remote secrets are deleted, the secret will be updated to be empty.

**Comment by Skarlso** [comment]
@stephen-dexda Does the workaround from @int128 work for you or do you wish to have my proposed behavior of creation policy?

**Comment by gusfcarvalho** [comment]
I think we don't really need a new creation policy. IIRC this is currently the available options with DeletionPolicies:

* Retain - If Secret Not Found, Fail the ExternalSecret reconciliation with SecretSyncError status
* Merge - If Secret Not Found, continue normally - results in an empty Secret if nothing is found with SecretSynced status
* Delete - If all Secrets are Not Found, delete the Secret and Succeed the ExternalSecret reconciliation with SecretDeleted status

This cover all the cases right?
I think we should just document that better on deletion policies.

**Comment by Skarlso** [comment]
Yep that's why I asked if that solution is good enough. I agree. ☝️

**Comment by gusfcarvalho** [comment]
How can you create an empty secret that would not return a not found operation?

I think this is somewhat impossible to achieve, no?

**Comment by stephen-dexda** [comment]
See the example in my intial report - a K8s secret with an empty `data` key is valid, so it can exist without having any keys.

**Comment by gusfcarvalho** [comment]
I mean in the remote secret.

**Comment by stephen-dexda** [comment]
In terms of the "why", there is orchestration value in separating the creation of the initial resources from subsequent population of those resources, for example, if the use case is an "account credentials"-type secret in a form resembling `{"<user>": "<pass>"}', in which case initially there may be no secrets.

Having an empty AWS secret/ K8s secret allows for the initial one-off resources to be provisioned and the consumer(s) of the K8s secret to start properly because the Secret resource exists, and then the management of the contents of the AWS secret/ExternalSecret to look the same for the first and subsequent entries, which simplifies orchestration in the general case.

Currently, ExternalSecrets behaves differently in the zero-keys case from the one-or-more-keys case despite it being possible and potentially useful for it to behave consistently in both.

Is there a situation in which creating an empty K8s secret would be disadvantageous?

**Comment by gusfcarvalho** [comment]
> Having an empty AWS secret/ K8s secret allows for the initial one-off resources to be provisioned and the consumer(s) of the K8s secret to start properly because the Secret resource exists, and then the management of the contents of the AWS secret/ExternalSecret to look the same for the first and subsequent entries, which simplifies orchestration in the general case.

This - is supported. Just have an empty value on AWS Secrets MAnager and it will create an empty secret if you use Merge policies;

What you cannot do is to have no `data` object. ExternalSecrets is not a tool for you to randomly create secrets; its a tool to synchronize Secrets from a well defined source.

Still, IMO, non goal of this project to support no sources :). this project is not a templating engine.

**Comment by gusfcarvalho** [comment]
Zero keys in data means: "always create and make sure to produce an empty secret. IF anything changes it, erase and make sure its still empty".

I continue to believe there is no use case for the above :).

**Comment by stephen-dexda** [comment]
So maybe we're talking cross-purposes here. I'd asked previously if "Merge" would work for the described use case (empty key/value object on the source side), but I think "empty" in my question was taken to mean "zero character string" instead of "empty object representation" (`{}` in AWS). So would that policy work?

Can you also clarify on your reconciliation policies from above?

> Merge - If Secret Not Found, continue normally - If the Secret keys existed but now are not found, remove them from the Secret. Results in an empty Secret if nothing is found, with SecretSynced status even on the first reconcile.
> 
> Delete - If all Secrets are Not Found, delete the Secret and Succeed the ExternalSecret reconciliation with SecretDeleted status. Results in no Secrets in the first reconcile (but with a Passing state)

This is a bit unclear to me - specifically:

* "if secret not found, continue normally" - does this mean if the external source secret doesn't exist at all, the ExternalSecret won't enter an error state?
* "if all secrets are not found" - does this actually mean if all secret _keys_ are not found?

**Comment by gusfcarvalho** [comment]
> So maybe we're talking cross-purposes here. I'd asked previously if "Merge" would work for the described use case (empty key/value object on the source side), but I think "empty" in my question was taken to mean "zero character string" instead of "empty object representation" ({} in AWS). So would that policy work?

yup. https://github.com/external-secrets/external-secrets/blob/main/pkg/provider/aws/secretsmanager/secretsmanager.go#L470-L486 ; then https://github.com/external-secrets/external-secrets/blob/main/pkg/controllers/externalsecret/externalsecret_controller.go#L328-L336. Just use `dataFrom` to parse `{}` into an empty object.

**Comment by gusfcarvalho** [comment]
> This is a bit unclear to me - specifically:
> 
> "if secret not found, continue normally" - does this mean if the external source secret doesn't exist at all, the ExternalSecret won't enter an error state?
> "if all secrets are not found" - does this actually mean if all secret keys are not found?

If a secret is not found (specific API Error or is empty), we continue the operation normally.

If all secrets defined in an ES manifest are not found (as you can have multiple data entries, multiple sources, multiple secrets being fetched out at the same time with `dataFrom.find`, etc.) - deletionPolicy =delete will also delete the k8s secret. 

In your use case (1 secret being fetched), if it is fully parsed as empty,  `deletionPolicy=delete` will delete the k8s Secret object, which is not what you want. `deletionPolicy=merge` will create and manage an empty secret; which is what you want.

**Comment by pachecoc** [comment]
Hi all.
Not sure if the use case here is the same I had when I commented here.
My requirements were:

- Create a Kubernetes secrets with a `data` field empty even if the `secretKey` reference points to a non existing object
- In a point of the future, when the `secretKey` becomes available, the secret `data` field would be updated.

I was able to achieve data, doing sort of `fallback` value in my ExternalSecret configuration using gotemplate `default` function as:

```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example
spec:
  refreshInterval: 1m
  data:
  - secretKey: example
     remoteRef:
       key: /ssm/nonexistingkeyyet
  target:
    deletePolicy: Merge
    template:
       data:
          example: '{{- default "fallbackvalue" (index . "example") }}'
```

If, in my case, the AWS ParameterStore does not exist, the secret will be created with the value of `fallbackvalue`. Once the parameter is created, the secret value will be updated after the refresh interval. 

I hope it helps.
Cheers.
