### ISSUE TITLE
Does not send a POST request. Sends PUT

### ISSUE THREAD

**Issue by tebaly** [external-secrets/external-secrets#3495]
Does not send a POST request. Sends PUT

```yaml
apiVersion: generators.external-secrets.io/v1alpha1
kind: VaultDynamicSecret
metadata:
  name: "mysql"
spec:
  method: 'POST'
...
```

> could not generate [0]: Error making API request. URL: PUT http://vault***:8200/v1/database/static-creds/*** Code: 405. Errors: * 1 error occurred: * unsupported operation

**Comment by Skarlso** [comment]
Yep, because the Hashicorp Library uses Put on the Write.

```go

func (c *Logical) WriteWithContext(ctx context.Context, path string, data map[string]interface{}) (*Secret, error) {
	r := c.c.NewRequest(http.MethodPut, "/v1/"+path)
	if err := r.SetJSONBody(data); err != nil {
		return nil, err
	}

	return c.write(ctx, path, r)
}
```

And they offer no overwrite in that. I wonder though if that error is not about the Put operation?

And if we take a look at the current implementation, it's still a PUT operation https://github.com/hashicorp/vault/blob/main/api/logical.go#L207

**Comment by moolen** [comment]
AFAIK vault does not differentiate between POST and PUT calls. are you sure everything is set up correctly? Can you use `vault write` or `curl` to make a call?

**Comment by tebaly** [comment]
@moolen @Skarlso I think this is obviously a bug. A request to change a database secret requires exactly that POST

Hashicorp doc 
https://developer.hashicorp.com/vault/api-docs/secret/databases#rotate-static-role-credentials
https://developer.hashicorp.com/vault/api-docs/secret/databases/mysql-maria 

```bash
curl \
    --header "X-Vault-Token: ..." \
    --request POST \
    http://127.0.0.1:8200/v1/database/rotate-role/my-static-role

```

 It seems that in your answer you appealed to getting KV secrets. Requesting a database secret rotation with the PUT method returns an error. According to your documentation, I can specify the method in the description. So why is it not used when requesting a secret then?

```yaml
apiVersion: generators.external-secrets.io/v1alpha1
kind: VaultDynamicSecret
spec:
  method: "POST"
  path: "/database/static-creds/******"
```

> could not generate [0]: Error making API request. URL: PUT http://vault***:8200/v1/database/static-creds/*** Code: 405. Errors: * 1 error occurred: * unsupported operation

# This is really a bug, a real one

Because I can't use the secret for the database, since there is no `POST` request sent, and the secret expires when the rotation time in `Vault` is reached. Obviously, I have to request rotation by `refreshInterval` myself, since it is impossible to guess and synchronize the `rotation of the secret` in the cluster with the rotation in Vault
