### ISSUE TITLE
AcrAccesstokeToken do not work when serviceaccount is in a different namespace

### ISSUE THREAD

**Issue by kogsox** [external-secrets/external-secrets#3552]
**Describe the bug**
When trying to generate an acr token in a different ns than the serviceaccount. the fetching fails with error: `"error":"could not generate [0]: ServiceAccount \"eso-managedidentity\" not found`
in the documentation eso hints to supporting this:
```yaml
    # option 3:
    workloadIdentity:
      # note: you can reference service accounts across namespaces.
      serviceAccountRef:
        name: "my-service-account"
        audiences: []
```

**To Reproduce**
1. provide all relevant manifests
````yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: <managed identity clientId>
    azure.workload.identity/tenant-id: <managed identity tenantId>
  name: eso-managedidentity
  namespace: externalsecrets
--- 
apiVersion: generators.external-secrets.io/v1alpha1
kind: ACRAccessToken
metadata:
  name: myacr-azurecr-io
  namespace: argocd # <-- deployed in a separate ns from sa
spec:
  auth:
    workloadIdentity:
      serviceAccountRef:
        name: eso-managedidentity
        namespace: externalsecrets # <-- reference sa ns
  environmentType: PublicCloud
  registry: myacr.azurecr.io
  tenantId: <managed identity tenantId>
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: n11056acr-azurecr-io
  namespace: argocd
spec:
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: ACRAccessToken
        name: myacr-azurecr-io
  refreshInterval: 6h
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: myacr-azurecr-io
    template:
      data:
        enableOCI: "true"
        name: myacr
        password: '{{ .password }}'
        type: helm
        url: myacr.azurecr.io
        username: '{{ .username }}'
      engineVersion: v2
      mergePolicy: Replace
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
````

3. provide the Kubernetes: `1.29.4` and ESO version: `0.9.16` 

**Expected behavior**
1. if it is intendend behaviour, the docs should be updated; remove the line that indicates that we can reference sa across namespaces
2. if it should be supported, fix the generator to support using seviceaccount from another namespaces. [code link](https://github.com/external-secrets/external-secrets/blob/542f3a6a083dc3a368ffb22f7809a2fe1095bf91/pkg/generator/acr/acr.go#L230)
````golang
	err := crClient.Get(ctx, types.NamespacedName{
		Name:      serviceAccountRef.Name,
		Namespace: namespace, // hardcoded to same namespace
	}, &sa)
```
