### ISSUE TITLE
Can't create custom resources such as `ClusterSecretStore` using `extraObjects` value when `installCRDs` is `true`

### ISSUE THREAD

**Issue by AndrewJo** [external-secrets/external-secrets#3557]
**Describe the bug**
Helm attempts to create the extra manifests in `extraObjects` before it has a chance to install the CRDs.

**To Reproduce**
1. Ensure `installCRDs` option is set to `true`
2. Set extraObjects:
   ```yaml
   extraObjects:
   - apiVersion: external-secrets.io/v1beta1
     kind: ClusterSecretStore
     metadata:
       name: vault
     spec:
       provider:
       # ...
   ```

**Expected behavior**
The `ClusterSecretStore` should be created.

**Actual behavior**
Returns an error message:
```
Release "external-secrets-operator" does not exist. Installing it now.
Error: unable to build kubernetes objects from release manifest: resource mapping not found for name: "vault" namespace: "" from "": no matches for kind "ClusterSecretStore" in version "external-secrets.io/v1beta1"
ensure CRDs are installed first
```

**Screenshots**
<img width="906" alt="image" src="https://github.com/external-secrets/external-secrets/assets/3170805/d8b48c09-0197-4e15-8467-49aa94128a1d">

**Additional context**
I believe the original intent of `extraObjects` is referenced here (#2961), to create custom resources like `ClusterSecretStore` at the time of chart installation.

The PR #3421 has a unit test but the resource manifest it creates is not a external-secrets CRD; it is just a ServiceAccount which is a resource type that already exists in Kubernetes and doesn't sufficiently catch the issue.

**Comment by moolen** [comment]
Thats expected as helm doesn't install the CRDs before applying the CRs.
You would have to install the CRDs separately and the you can use extraObjects.

**Comment by ketozhang** [comment]
@moolen Then isn't this first sentence in the docs wrong?

> The default install options will automatically install and manage the CRDs as part of your helm release. 
> —https://external-secrets.io/latest/introduction/getting-started/

**Comment by jasonwashburn** [comment]
Apologize for adding to a closed issue, but hopefully this will help future seekers...

It is possible to use the `extraObjects` value to create external-secrets specific resources during the chart deployment by adding helm post-install and post-upgrade hooks to the resources you want to create to make sure they're installed after helm has installed the CRDs.

For example...

```yaml
installCRDs: true 

extraObjects:
  - apiVersion: generators.external-secrets.io/v1alpha1
    kind: Fake
    metadata:
      name: fake-generator-for-testing
      namespace: external-secrets
      # These helm hooks are needed to ensure helm tries to create the extraObjects
      # after the external-secrets CRDs have been installed by the chart.
      annotations:
        "helm.sh/hook": post-install,post-upgrade
        "helm.sh/hook-weight": "1"
    spec:
      data:
        foo: bar

```

**Comment by maciej-markowski** [comment]
@jasonwashburn  Can you specify what exact chart version were you using? I am having the same issue as @AndrewJo. I tried your example with 0.18.2 and 0.19.0 but still I am getting the same error.

```
# ./linux-amd64/helm version
version.BuildInfo{Version:"v3.18.0", GitCommit:"cc58e3f5a3aa615c6a86275e6f4444b5fdd3cc4e", GitTreeState:"clean", GoVersion:"go1.24.3"}
```

```
# cat values_test.yaml
extraObjects:
  - apiVersion: generators.external-secrets.io/v1alpha1
    kind: Fake
    metadata:
      name: fake-generator-for-testing
      namespace: external-secrets
      # These helm hooks are needed to ensure helm tries to create the extraObjects
      # after the external-secrets CRDs have been installed by the chart.
      annotations:
        "helm.sh/hook": post-install,post-upgrade
        "helm.sh/hook-weight": "1"
    spec:
      data:
        foo: bar
```

```
# ./linux-amd64/helm -n external-secrets upgrade --install external-secrets eso/external-secrets --version 0.19.0  --values values_test.yaml --create-namespace
Release "external-secrets" does not exist. Installing it now.
Error: failed post-install: unable to build kubernetes object for deleting hook external-secrets/templates/extra-manifests.yaml: resource mapping not found for name: "fake-generator-for-testing" namespace: "external-secrets" from "": no matches for kind "Fake" in version "generators.external-secrets.io/v1alpha1"
ensure CRDs are installed first
```

**Comment by jasonwashburn** [comment]
I'm currently using that test with 0.18.2 successfully. I'm setting the helm values via uds bundle overrides though...which makes me wonder if there's something else happening under the hood that would explain the difference you're seeing. I'll see if I can get a minimal example using helm directly to work.

**Comment by jasonwashburn** [comment]
~~Ok, so what was probably missing missing is the `installCRDs: true` in your values~~ ok, maybe not...that does appear to be the default value anyway... but, I was able to deploy it successfully on a new cluster (k3d) using helm with the following values:

```yaml
installCRDs: true

extraObjects:
  - apiVersion: generators.external-secrets.io/v1alpha1
    kind: Fake
    metadata:
      name: fake-generator-for-testing
      namespace: external-secrets
      # These helm hooks are needed to ensure helm tries to create the extraObjects
      # after the external-secrets CRDs have been installed by the chart.
      annotations:
        "helm.sh/hook": post-install,post-upgrade
        "helm.sh/hook-weight": "1"
    spec:
      data:
        foo: bar
```
...and using the following command:

```
~/dev/tmp-external-secrets-test on ☁️  (us-east-2) 
❯ helm install external-secrets \
   external-secrets/external-secrets \
    -n external-secrets \
    --create-namespace --values values.yaml
NAME: external-secrets
LAST DEPLOYED: Tue Aug  5 18:17:06 2025
NAMESPACE: external-secrets
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
external-secrets has been deployed successfully in namespace external-secrets!

In order to begin using ExternalSecrets, you will need to set up a SecretStore
or ClusterSecretStore resource (for example, by creating a 'vault' SecretStore).

More information on the different types of SecretStores and how to configure them
can be found in our Github: https://github.com/external-secrets/external-secrets

~/dev/tmp-external-secrets-test on ☁️  (us-east-2) took 3s
❯ kubectl get fake -n external-secrets
NAME                         AGE
fake-generator-for-testing   4s
```

I also successfully tested it using nearly the same command you posted above (different chart repository eso vs external-secrets, and name of values file):
```
~/dev/tmp-external-secrets-test on ☁️  (us-east-2) took 13s
❯ kubectl get fake -n external-secrets
error: the server doesn't have a resource type "fake"

~/dev/tmp-external-secrets-test on ☁️  (us-east-2) 
❯ helm -n external-secrets upgrade --install external-secrets external-secrets/external-secrets --version 0.19.0  --values values.yaml --create-namespace
Release "external-secrets" does not exist. Installing it now.
NAME: external-secrets
LAST DEPLOYED: Tue Aug  5 19:28:57 2025
NAMESPACE: external-secrets
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
external-secrets has been deployed successfully in namespace external-secrets!

In order to begin using ExternalSecrets, you will need to set up a SecretStore
or ClusterSecretStore resource (for example, by creating a 'vault' SecretStore).

More information on the different types of SecretStores and how to configure them
can be found in our Github: https://github.com/external-secrets/external-secrets

~/dev/tmp-external-secrets-test on ☁️  (us-east-2) took 3s
❯ kubectl get fake -n external-secrets
NAME                         AGE
fake-generator-for-testing   2s
```
