### ISSUE TITLE
Tushikha

### ISSUE THREAD

**Issue by Sakib43351** [external-secrets/external-secrets#3575]
Hi @moolen,

I use the akeyless provider. I've created k8s auth method and deployed the external secret operator to a k8s cluster following this doc => https://docs.akeyless.io/docs/external-secret-operator

```yml
---
apiVersion: v1
kind: Secret
metadata:
  name: akeylss-secret-creds
type: Opaque
stringData:
  accessId: "access-id"
  accessType: k8s
  accessTypeParam: "auth-method-name"
---
apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: akeyless-secret-store
spec:
  provider:
    akeyless:
      # URL of your akeyless API
      akeylessGWApiURL: "https://gatewaylURL:8080/v2"
      authSecretRef:
        secretRef:
          accessID:
            name: akeylss-secret-creds
            key: accessId
          accessType:
            name: akeylss-secret-creds
            key: accessType
          accessTypeParam:
            name: akeylss-secret-creds
            key: accessTypeParam
---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: akeyless-external-secret-example
spec:
  refreshInterval: 5h
  secretStoreRef:
    kind: SecretStore
    name: akeyless-secret-store
  target:
    name: akeyless-secret-to-create
    creationPolicy: Owner
  data:
    - secretKey: username 
      remoteRef:
        key: /k8s/demoapp
```

_Originally posted by @precompiler in https://github.com/external-secrets/external-secrets/issues/985#issuecomment-1094978577_
