### ISSUE TITLE
Secrets get updated when a time based go template function is used 

### ISSUE THREAD

**Issue by WatcherWhale** [external-secrets/external-secrets#3602]
**Describe the bug**
When using for example the `htpasswd` function in a go template, every refresh period the secret gets updated with a new value.

**To Reproduce**
1. Create a secret with for example the `htpasswd` function in a template
2. See the generated secret
3. Refresh the secret
4. Look again at the secret, it has now changed

<details>
<summary>Example secret</summary>
```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: reproducer
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: reproducer
    template:
      engineVersion: v2
      data:
        auth: '{{ htpasswd "user" "password" }}'
  dataFrom:
    - extract:
        key: secret/test
```

</details>

**Expected behavior**
I expect that the secret doesn't get updated with every refresh.

A possible suggestion to fix this is to compare to a checksum of the incoming secret data, instead of generating the result and comparing against the last secret.

**Additional context**
- Version: 0.9.19
- Environment: Azure AKS 1.29.4
- Secret Provider: Azure KeyVault
