### ISSUE TITLE
Let PushSecret define the namespace where to push

### ISSUE THREAD

**Issue by kaedwen** [external-secrets/external-secrets#3629]
**Is your feature request related to a problem? Please describe.**
Currently the `remoteNamespace` must be set on the store. But let's imagine you have a store equipped with credentials to talk to the whole remote cluster (kubernetes provider) we have to define a `SecretStore` for each remote Namespace.

**Describe the solution you'd like**
Why not just let the `PushSecret` set the Namespace where the secret should end up? This can also be an optional overwrite to not break the current flow.

**Describe alternatives you've considered**
Open for other suggestions.

**Comment by moolen** [comment]
Thanks for writing up that issue, i've had the same thoughts.
My take: add `remoteNamespaces` which defines the remote namespaces with a labelSelector and/or a matchExpressions list.

This will be a major refactoring of the provider but definitely worth it.

**Comment by Deltachaos** [comment]
This is exactly my usecase. I would love to see this added

**Comment by Skarlso** [comment]
I'll take this one.

**Comment by Skarlso** [comment]
I have a question. This is rather specific to the Kubernetes provider though, right? @moolen If we add a namespace selector to the push secret API how does that make sense for the other providers?

**Comment by moolen** [comment]
Yes, this is specific to the k8s provider.

**Comment by Skarlso** [comment]
Okay, but then... it doesn't make sense to add it to the PushSecret API, not...? Add is a metadata field instead or something like that?

**Comment by moolen** [comment]
its on the SecretStore provider i'd say :thinking: ? It would error out if it is used in conjunction with an ExternalSecret?

**Comment by Deltachaos** [comment]
What if you would make it so that the you can specify the namespace separated by slash in `remoteKey`?

The vault provider for example uses slashes in `remoteKey` to specify the directory as well.

**Comment by Skarlso** [comment]
I was probably confused because the initial request was about adding something to pushsecret and then you said add remoteNamespace and I thought you meant to the pushsecret. 😁

**Comment by Skarlso** [comment]
@Deltachaos I'm okay with that. @kaedwen @moolen Are you okay with that solution?

**Comment by moolen** [comment]
Regarding `remoteKey`:
I don't like that idea, the SecretStore should specify where the data is supposed to go, not the External|PushSecret. This allows for a better separation of concerns and security boundaries between resources. That allows users to simply use RBAC to restrict access to certain areas.

**Comment by Skarlso** [comment]
I'm so confused right now. :D

The initial issue is exactly that it's defined on the SecretStore and you said you have the same thought. So now... did you reconsider or...?

**Comment by moolen** [comment]
My above comment is the response to the proposal from @Deltachaos . Does that make sense?

**Comment by Skarlso** [comment]
Right, but you say this:
> SecretStore should specify where the data is supposed to go

Are you referring to the `remoteNamespace`?

**Comment by moolen** [comment]
I had something like this in mind, though i'm open to alternatives!

```yaml
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: k8s-store-default-ns
spec:
  provider:
    kubernetes:
      remoteNamespaces:
        # simple
        matchLabels:
          foo: bar
        # more advanced
        matchExpressions:
          - { key: tier, operator: In, values: [cache] }
          - { key: environment, operator: NotIn, values: [dev] }

```
