### ISSUE TITLE
PushSecret gives 400 when using 1password provider

### ISSUE THREAD

**Issue by onedr0p** [external-secrets/external-secrets#3631]
**Describe the bug**

PushSecret gives 400 when using 1password provider, this was working at some point...

**To Reproduce**

Kubernetes version: 1.30.2
ESO version: helm-chart-0.9.19

```yaml
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: devbu-io-tls
spec:
  refreshInterval: 1m
  secretStoreRefs:
    - name: onepassword-connect
      kind: ClusterSecretStore
  selector:
    secret:
      name: devbu-io-tls
  template:
    engineVersion: v2
    data:
      tls.crt: '{{ index . "tls.crt" | b64enc }}'
      tls.key: '{{ index . "tls.key" | b64enc }}'
  data:
    - match:
        secretKey: &key tls.crt
        remoteRef:
          remoteKey: devbu-io-tls
          property: *key
    - match:
        secretKey: &key tls.key
        remoteRef:
          remoteKey: devbu-io-tls
          property: *key
```

**Expected behavior**

PushSecret to update item and not give a 400 error

**Additional context**

Logs from the controller:

```
{"level":"error","ts":1719243410.2330096,"msg":"Reconciler error","controller":"pushsecret","controllerGroup":"external-secrets.io","controllerKind":"PushSecret","PushSecret":{"name":"devbu-io-tls","namespace":"cert-manager"},"namespace":"cert-manager","name":"devbu-io-tls","reconcileID":"967fe611-d1c8-44b9-8716-4f6d7f595bfb","error":"could not write remote ref tls.crt to target secretstore onepassword-connect: error updating 1Password Item: status 400: Unable to update item \"devbu-io-tls\" in Vault \"bkjqolx73zaafkwu2zq2shyz3i\"","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.3/pkg/internal/controller/controller.go:324\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.3/pkg/internal/controller/controller.go:261\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.3/pkg/internal/controller/controller.go:222"}
{"level":"error","ts":1719243414.3571475,"msg":"Reconciler error","controller":"pushsecret","controllerGroup":"external-secrets.io","controllerKind":"PushSecret","PushSecret":{"name":"devbu-io-tls","namespace":"cert-manager"},"namespace":"cert-manager","name":"devbu-io-tls","reconcileID":"75c99570-1335-4bb5-8327-65cd9d0ef9a7","error":"could not write remote ref tls.key to target secretstore onepassword-connect: error updating 1Password Item: status 400: Unable to update item \"devbu-io-tls\" in Vault \"bkjqolx73zaafkwu2zq2shyz3i\"","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.3/pkg/internal/controller/controller.go:324\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.3/pkg/internal/controller/controller.go:261\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.3/pkg/internal/controller/controller.go:222"}
```

Strange that the pushsecret CR reports all is fine:

```
❯ k get pushsecret -A
NAMESPACE      NAME           AGE   STATUS
cert-manager   devbu-io-tls   86d   Synced

home-ops [󱃾 main (default)] on  main (5ee43cc5) [$!]
❯ k -n cert-manager describe pushsecrets devbu-io-tls
Name:         devbu-io-tls
Namespace:    cert-manager
Labels:       app.kubernetes.io/name=certificates
              kustomize.toolkit.fluxcd.io/name=certificates
              kustomize.toolkit.fluxcd.io/namespace=flux-system
Annotations:  <none>
API Version:  external-secrets.io/v1alpha1
Kind:         PushSecret
Metadata:
  Creation Timestamp:  2024-04-02T11:40:01Z
  Generation:          1
  Resource Version:    134343267
  UID:                 3ee82a24-4198-4351-b0dd-d2296ca2aacf
Spec:
  Data:
    Conversion Strategy:  None
    Match:
      Remote Ref:
        Property:         tls.crt
        Remote Key:       devbu-io-tls
      Secret Key:         tls.crt
    Conversion Strategy:  None
    Match:
      Remote Ref:
        Property:    tls.key
        Remote Key:  devbu-io-tls
      Secret Key:    tls.key
  Deletion Policy:   None
  Refresh Interval:  1h
  Secret Store Refs:
    Kind:  ClusterSecretStore
    Name:  onepassword-connect
  Selector:
    Secret:
      Name:  devbu-io-tls
  Template:
    Data:
      tls.crt:       {{ index . "tls.crt" | b64enc }}
      tls.key:       {{ index . "tls.key" | b64enc }}
    Engine Version:  v2
    Merge Policy:    Replace
  Update Policy:     Replace
Status:
  Conditions:
    Last Transition Time:  2024-06-24T15:36:56Z
    Message:               PushSecret synced successfully
    Reason:                Synced
    Status:                True
    Type:                  Ready
  Synced Push Secrets:
    ClusterSecretStore/onepassword-connect:
      devbu-io-tls/tls.crt:
        Conversion Strategy:  None
        Match:
          Remote Ref:
            Property:    tls.crt
            Remote Key:  devbu-io-tls
          Secret Key:    tls.crt
      devbu-io-tls/tls.key:
        Conversion Strategy:  None
        Match:
          Remote Ref:
            Property:    tls.key
            Remote Key:  devbu-io-tls
          Secret Key:    tls.key
Events:
  Type    Reason  Age                    From        Message
  ----    ------  ----                   ----        -------
  Normal  Synced  52m (x129 over 4d19h)  pushsecret  PushSecret synced successfully
```

Refs:
https://github.com/external-secrets/external-secrets/issues/3129
https://github.com/external-secrets/external-secrets/issues/3130
https://github.com/external-secrets/external-secrets/issues/2565
https://github.com/external-secrets/external-secrets/pull/3238
https://github.com/external-secrets/external-secrets/pull/2646

cc: @Skarlso @bthuilot
