### ISSUE TITLE
Use versioned secret for HashiCorp Vault

### ISSUE THREAD

**Issue by AndreKoepke** [external-secrets/external-secrets#3673]
**Is your feature request related to a problem? Please describe.**
We want to use the versioned secrets offered by HashiCorp Vault on KV-engine v2.  
If we change a secret, then we expect that none of our system using that new value until we started a explicit deployment.  
This feature allows us to prepare deployments and rollback very fast.

**Describe the solution you'd like**
In Spring, it is possible to add the version to path. Like this:  
```yaml
spring:
  config:
    import: vault://kv/space/secret?version=5
```
Something like that should enough
```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "resource.name" . }}-vault
spec:
  dataFrom:
    - extract:
        key: space/secret?version=5
```

**Comment by AndreKoepke** [comment]
To easy, it is also integrated. 👍 

```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "resource.name" . }}-vault
spec:
  dataFrom:
    - extract:
        key: space/secret
        version: '5'
```
