### ISSUE TITLE
Infisical Provider -> Empty Secret

### ISSUE THREAD

**Issue by nadecancode** [external-secrets/external-secrets#3686]
**Describe the bug**
With Infisical provider the secrets (Opaque) have been created just fine, except all the fields have empty values.

**To Reproduce**
1. Install external-secrets with Infisical provider
2. Monitor the secrets

**Expected behavior**
All secrets should have non-empty values

**Screenshots**
![image](https://github.com/user-attachments/assets/779fcb6b-6fad-4b9b-b156-83601b7e88fc)

**Additional context**
```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name cert-manager-cf-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical-cloudflare
  target:
    name: *name
    creationPolicy: Owner
  data:
    - secretKey: API_TOKEN
      remoteRef:
        key: TOKEN
```
![image](https://github.com/user-attachments/assets/c517dc87-eb00-47c3-bbaa-f8af0e6389cb)

```yaml
data:
  API_TOKEN: ''
type: Opaque
```
No errors / warnings, statuses say secrets have been reconciled & synced as normal.
