### ISSUE TITLE
GCRAccessToken created GCP Access token cannot be used to authenticate with GCR in order to pull OCI images.

### ISSUE THREAD

**Issue by nerahou** [external-secrets/external-secrets#3694]
**Describe the bug**
GCRAccessToken created GCP Access token cannot be used to authenticate with GCR in order to pull OCI images.

**To Reproduce**

Hello !

I installed ESO using the official helm chart repository.

1. provide all relevant manifests

The following helm values were used (from docs example [here](https://external-secrets.io/latest/api/generator/gcr/))
```yaml
extraObjects:
  - apiVersion: generators.external-secrets.io/v1alpha1
    kind: GCRAccessToken
    metadata:
      name: gcr-gen
      namespace: external-secrets
    spec:
      # project where gcr lives in
      projectID: __my-project__

      # choose authentication strategy
      auth:
        # GCP service account
        secretRef:
          secretAccessKeySecretRef:
            name: external-secret
            key: secret-access-credentials
  - apiVersion: external-secrets.io/v1beta1
    kind: ExternalSecret
    metadata:
      name: "gcr-token"
      namespace: external-secrets
    spec:
      refreshInterval: "30m"
      target:
        name: gcr-token
      dataFrom:
        - sourceRef:
            generatorRef:
              apiVersion: generators.external-secrets.io/v1alpha1
              kind: GCRAccessToken
              name: "gcr-gen"
```

The secretRef points to a secret created following [GCP Service Account authentication](https://external-secrets.io/latest/provider/google-secrets-manager/#authentication) with a Service account that has roles/storage.admin role on the GCP project.

The gcr-token is successfully created, try using it to pull images from GCR in a pod
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test-gcr-access-token
  namespace: external-secrets
spec:
  containers:
    - name: test-gcr-access-token
      image: eu.gcr.io/project/imager:latest
      ports:
        - containerPort: 80
  imagePullSecrets:
  - name: gcr-token
```
The gcr-token is successfully created BUT an ImagePullBackOff Error with the following message is thrown when used as imagePullSecrets : 
```
Failed to pull image "__image__": failed to pull and unpack image "__image__": failed to resolve reference "__image__": failed to authorize: failed to fetch anonymous token: unexpected status from GET request to https://eu.gcr.io/v2/token?scope=repository%3A...: 403 Forbidden
```

2. ESO version
Used helm chart 0.9.20

**Expected behavior**
The generated gcr-token should be a valid imagePullsecrets and be be used to authenticate with GCR in order to pull OCI images.

Is there something i am missing out ?

Thanks for your help !

**Comment by nerahou** [comment]
Managed to get this working with the following values applied separately from the chart :
```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gcr-token
  namespace: external-secrets
spec:
  refreshInterval: "30m"
  target:
    name: gcr-token
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "eu.gcr.io": {
                "username": "{{ .username }}",
                "password": "{{ .password }}"
              }
            }
          }
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: GCRAccessToken
          name: gcr-gen
```
