### ISSUE TITLE
Gitlab Variables environment not honoured

### ISSUE THREAD

**Issue by AlexEndris** [external-secrets/external-secrets#3698]
**Describe the bug**
I'm facing the issue that ExternalSecrets doesn't seem to correctly filter the variables using Gitlab Variables. The SecretStore is capable of retrieving a secret of environment "b" even though it's being restricted to "a".

**To Reproduce**
ESO: 0.9.20
k8s: 1.30.0

Let's say I have the secrets "TEST_SECRET_A" (environment "a") and "TEST_SECRET_B" (environment "b"), neither secret exists in any other environment.
Using this secretstore:
```yaml
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: a-secrets
  namespace: default
spec:
  provider:
    gitlab:
      auth:
        SecretRef:
          accessToken:
            name: xxx
            key: xxx
      projectID: "xxx"
      inheritFromGroups: false
      environment: a
```

Adding an ExternalSecret resource like this, actually retrieves the secret:
```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitlab-external-secret-b
  namespace: default
spec:
  refreshInterval: 1m

  secretStoreRef:
    kind: SecretStore
    name: a-secrets

  target:
    name: b-secret 
    creationPolicy: Owner

  data:
    - secretKey: secretKey
      remoteRef: 
        key: TEST_SECRET_B
```

**Expected behavior**
Trying the same using the gitlab API with the filter for the environment_scope of "a" correctly returns "404 Variable Not Found".
I would expect/hope that this is actually a way to also restrict a SecretStore from accessing variables of other environments.

Am I doing something wrong, is this intended (in the documentation I can only see environment mentioned when having the same variable name for multiple environments) or is this indeed a bug?
