### ISSUE TITLE
Support for cloudfoundry Credhub 

### ISSUE THREAD

**Issue by gberche-orange** [external-secrets/external-secrets#3712]
**Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

CloudFoundry credhub is widely used in the cloudfoundry and bosh communities as a secret store. See introduction at https://docs.cloudfoundry.org/credhub/index.html

Consumming credhub secrets from k8s currently requires adhoc mechanisms to export them as a secrets. Publishing k8s secrets in credhub likewise involves specific custom mechanisms such as a wrapping the credhub cli into a k8s Job.

Support for cloudfoundry Credhub would support the following use-cases:
- Platform operators can automate reading secrets from credhub in k8s-hosted control planes (e.g. managed services)
- Application developers can ease interoperability betwen apps running in cloudfoundry and accessing secrets using credhub, and apps running in k8s

**Describe the solution you'd like**

A new credhub provider supporting the pull and push models.

**Describe alternatives you've considered**

For pull models, my team currently uses CI/CD shell scripts that dump a secret of credhub keys, a push them as k8s secrets.
For push models, my team currently use a helm chart which generates a cronjob wrapping the credhub cli in order to publish a set of secrets into credhub.

**Additional context**

The full credhub api and reference documentation is available at https://docs.cloudfoundry.org/api/credhub/version/main/
The main repo is at https://github.com/cloudfoundry/credhub

Integration with bosh as secret pull and secret push is documented at https://bosh.io/docs/variable-types/ and https://bosh.io/docs/cli-int/

**Comment by gberche-orange** [comment]
Here is the outcome of a POC by @poblin-orange and @o-orand attempting to use the webhook provider against the credhub api following the push support in https://github.com/external-secrets/external-secrets/pull/4360 contributed by @Skarlso:
* [x] worked around lack of support for bearer token with a cronjob which generates a uaa access token with client credentials grant type, see https://github.com/external-secrets/external-secrets/issues/3871#issuecomment-3511119930

<details><summary>script to generate UAA Oauth token by @poblin-orange</summary>
<p>

```bash
#!/bin/bash
set -e
echo "started at $(date)"

# uaa generate token
curl  -sSL -X POST -H "Content-Type: application/x-www-form-urlencoded" \
  -d "grant_type=client_credentials&client_id=$CLIENT_ID&client_secret=$CLIENT_SECRET" \
  --cacert /etc/ssl/certs/crt \
  https://uaa-credhub.$MYDOMAIN:8443/oauth/token \
  | jq '.access_token' > tokenfile
REFRESH_AT=$(date +'%Y-%m-%d.%H-%M-%S')
export TOKEN=`cat tokenfile`
cat - > secret.yaml <<EOF
apiVersion: v1
kind: Secret
metadata:
  name: webhook-credentials
  labels:
    external-secrets.io/type: webhook #Needed to allow webhook to use this secret
stringData:
  bearer_token: $TOKEN
  refresh_at: $REFRESH_AT
EOF

echo "apply new token at $(date)"
cat secret.yaml | envsubst | kubectl apply -f -


TOKEN_FROM_K8S=$(kubectl get secret webhook-credentials -o jsonpath='{.data.bearer_token}' | base64 -d)
if curl -sSL --fail-with-body --cacert /etc/ssl/certs/crt -H "Authorization: Bearer $TOKEN_FROM_K8S" "https://credhub.internal.paas:8844/api/v1/data?current=true&name=/meta/template_version";then
  echo ""
  echo "Token is valid"
else
  echo ""
  echo "ERROR detected !"
fi

echo "ended at $(date)"
```

</p>
</details> 

* [x] Successfully used the ExternalSecret for fetching secret from credhub using [Get a Credential by Name](https://docs.cloudfoundry.org/api/credhub/version/main/#_get_a_credential_by_name] endpoint

<details><summary>Sample secret store</summary>
<p>

```yaml
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: credhub-get
spec:
  provider:
    webhook:
      url: https://credhub.mydomain.org:8844/api/v1/data?current=true&name=%2Fsecret-eso%2F{{ .remoteRef.key }}
      result:
        jsonPath: "$.data[0].value"
      headers:
        Accept: application/json
        Authorization: Bearer {{ print .auth.bearer_token }}
      caProvider:
        type: Secret
        name: my-internal-ca
        key: crt

      secrets:
        - name: auth
          secretRef:
            name: webhook-credentials

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: test
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: credhub-get
    kind: SecretStore
  data:
  #--- Formal domains
  - remoteRef:
      key: cloudfoundry_ops_domain
    secretKey: cloudfoundry_ops_domain

  target:
    template:
      type: Opaque
      engineVersion: v2
      data:
        ops_domain: '{{- .cloudfoundry_ops_domain -}}'
```
</p>
</details> 

* [ ] Promising use of pushSecret support of webhook, but met the following limitations (see related issue at https://github.com/external-secrets/external-secrets/issues/5571 )
   * [ ] it was challenging to debug 400 errors from credhub when failing to parse malformed HTTP request from ESO. See related suggested feature https://github.com/external-secrets/external-secrets/issues/5576
   * [ ] the url used for the DELETE endpoint does not yet seem configurable from the url used by the push (there is a single webhook for create/read/update/delete). However credhub expects PUT on `https://example.com/api/v1/data` and DELETE on `/api/v1/data?name=/some-credential-name`. The URL templating for push or delete don't yet pass in the method to support conditional templating of the url, see https://github.com/external-secrets/external-secrets/blob/aad919a408f45e8ef3c9efe30a769d56ae1fbb09/providers/v1/webhook/webhook.go#L124-L133, https://github.com/external-secrets/external-secrets/blob/aad919a408f45e8ef3c9efe30a769d56ae1fbb09/providers/v1/webhook/pkg/webhook/webhook.go#L242-L262,  and https://github.com/external-secrets/external-secrets/blob/aad919a408f45e8ef3c9efe30a769d56ae1fbb09/providers/v1/webhook/pkg/webhook/webhook.go#L215-L225
      * [ ] Worked around with deletionPolicy=None
   * [ ] when configuring a PushSecret with refresh interval, then the webhook provider is systematically calling the webhook regardless of whether the secret has changed, similar to https://github.com/external-secrets/external-secrets/issues/5443 As a result, this fills up the remote credhub database.
      * [ ]  As a workaround, trying to use `updatePolicy=IfNotExists` (see https://external-secrets.io/latest/guides/pushsecrets/ and [design doc](https://github.com/external-secrets/external-secrets/blob/2a8213669afda42d876fa497b2bcd9ef5d98241b/design/008-pushsecret-update-policy.md)), fails because credhub API URL is  `/api/v1/data?name=/some-credential-name` on get and `https://example.com/api/v1/data` on POST/PUT, and the body would also require conditional rendering on delete, see error below on rendering of body. `message: 'set secret failed: could not verify if secret exists in store: failed to parse body: template: webhooktemplate:1:81: executing "webhooktemplate" at <index .remoteRef .remoteRef.remoteKey>: error calling index: value is nil; should be of type string'`
      * [ ] Ended up using refreshInterval="525600h" as a workaround ("365d" did not work). Trying `5256000h` (10 years also failed at k8s api)
```
{"level":"error","ts":1762785268.5047133,"logger":"controller-runtime.cache.UnhandledError","msg":"Failed to watch","reflector":"pkg/mod/k8s.io/client-go@v0.34.1/tools/cache/reflector.go:290","type":"*v1a
lpha1.PushSecret","error":"failed to list *v1alpha1.PushSecret: time: invalid duration \"5256000h\"","stacktrace":"k8s.io/apimachinery/pkg/util/runtime.logError\n\t/home/runner/go/pkg/mod/k8s.io/apimachin
ery@v0.34.1/pkg/util/runtime/runtime.go:221\nk8s.io/apimachinery/pkg/util/runtime.handleError\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.34.1/pkg/util/runtime/runtime.go:212\nk8s.io/apimachinery/pk
g/util/runtime.HandleErrorWithContext\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.34.1/pkg/util/runtime/runtime.go:198\nk8s.io/client-go/tools/cache.DefaultWatchErrorHandler\n\t/home/runner/go/pkg/m
od/k8s.io/client-go@v0.34.1/tools/cache/reflector.go:205\nk8s.io/client-go/tools/cache.(*Reflector).RunWithContext.func1\n\t/home/runner/go/pkg/mod/k8s.io/client-go@v0.34.1/tools/cache/reflector.go:361\nk
8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.34.1/pkg/util/wait/backoff.go:233\nk8s.io/apimachinery/pkg/util/wait.BackoffUntilWithContext.func1\n\t
/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.34.1/pkg/util/wait/backoff.go:255\nk8s.io/apimachinery/pkg/util/wait.BackoffUntilWithContext\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.34.1/pkg/util/
wait/backoff.go:256\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.34.1/pkg/util/wait/backoff.go:233\nk8s.io/client-go/tools/cache.(*Reflector).RunWithCo
ntext\n\t/home/runner/go/pkg/mod/k8s.io/client-go@v0.34.1/tools/cache/reflector.go:359\nk8s.io/client-go/tools/cache.(*controller).RunWithContext.(*Group).StartWithContext.func3\n\t/home/runner/go/pkg/mod
/k8s.io/apimachinery@v0.34.1/pkg/util/wait/wait.go:63\nk8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.34.1/pkg/util/wait/wait.go:72"}             
```
