### ISSUE TITLE
InvalidProviderConfig Passbolt error in unlocking key

### ISSUE THREAD

**Issue by HoaMi** [external-secrets/external-secrets#3713]
**Describe the bug**
I'm having trouble configuring the passbolt provider on external-secrets
When I deploy the SecretStore on my cluster with the passbolt provider configuration
I get this error :
```
InvalidProviderConfig: Unable to Unlock UserPrivateKey using UserPassword: gopenpgp: error in unlocking key: openpgp: invalid data: private key checksum failure
```

**To Reproduce**
- OS: Ubuntu 24.04 ARM on Raspberry pi
- Kube: k3s v1.30.2
- external-secrets: helm chart v0.9.20
- passbolt: helm chart v1.1.1 and app v4.9.0-1-ce

I've taken the example from the [documentation](https://external-secrets.io/latest/provider/passbolt/)
```
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: passbolt
  namespace: toto
spec:
  provider:
    passbolt:
      host: [host]
      auth:
        passwordSecretRef:
          key: password
          name: passbolt-credentials
        privateKeySecretRef:
          key: privateKey
          name: passbolt-credentials
```
For the `password`, I use my account's passphrase, and for the `privatekey`, the private key generated by passbolt

Its credentials are base64 encrypted to be deployed in opaque secret on the cluster

**Expected behavior**

**Screenshots**

**Additional context**
I tested my passphrase and privatekey with the [go script](https://github.com/passbolt/go-passbolt) and my credentials work
