### ISSUE TITLE
AWS EKS cross kubernetes cluster secrets

### ISSUE THREAD

**Issue by jonerer** [external-secrets/external-secrets#3717]
Hello! Thanks for this amazing project, it feels very cloud native and very helpful in many ways. But we've stumbled onto an area which could use improvement.

Unsure if this should be a bug or feature request. From the documentation, I expected this to work, but reading the source code, it seems not implemented. So bug in the documentation and feature request for the project?

**Describe the bug**
I wish to be able to load secrets from another EKS cluster. I expected to be able to do it with the kubernetes provider by authenticating with a serviceaccount as seen on: https://external-secrets.io/latest/provider/kubernetes/#authenticating-with-serviceaccount

My usecase is that i generate Kafka users in one cluster with Strimzi's KafkaUser CRD. When they have been generated, i wish to use them in anohter cluster, and so i want to transfer the connection credentails from cluster A to cluster B. And I was thrilled to see External Secrets, that seems to fill that niche.

I provided a serviceaccount with proper authentication settings to be able to access the target cluster, and authorization in RBAC to be able to access the target `Secrets` and create `SelfSubjectRulesReview` objects. I have manually verified that the serviceaccount is able to perform the expected actions.

**To Reproduce**

1. provide all relevant manifests
```
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: kafka-secret-store
spec:
  provider:
    kubernetes:
      auth:
        serviceAccount:
          name: kafka-secret-sync
          namespace: external-secrets
      remoteNamespace: kafka
      server:
        caBundle: LS0tLS1C [...] 0tLS0K
        url: https://6C332 ... 4.gr7.eu-west-1.eks.amazonaws.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::8...[accountId]...5:role/work-dev-kafka-secret-sync
  name: kafka-secret-sync
  namespace: external-secrets
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kafka-configuration-external-secret
  namespace: hazard-info-ingestion
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: hazard-info-ingestion
      metadataPolicy: None
      property: password
    secretKey: password
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: hazard-info-ingestion
      metadataPolicy: None
      property: sasl.jaas.config
    secretKey: sasljaasconfig
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: kafka-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: hazard-info-ingestion-kafka-config
    template:
      data:
        kafka-client.properties: |
          sasl.mechanism=SCRAM-SHA-512
          security.protocol=SASL_SSL
          sasl.jaas.config={{ `{{ .sasljaasconfig }}` }}
          bootstrap.servers=kafka-bootstrap.myclusterdomain.se:443
        password: '{{ `{{ .password }}` }}'
        sasl.jaas.config: '{{ `{{ .sasljaasconfig }}` }}'
      engineVersion: v2
      mergePolicy: Replace

```
2. provide the Kubernetes and ESO version
ESO: v0.9.20
Kubernetes Server Version: v1.29.4-eks-036c24b

** What happens? **
The kubernetes provider seems to create a Token with ServiceAccount.CreateToken: https://github.com/external-secrets/external-secrets/blob/26153cc9bdd25c233945f6856f433614b10841d0/pkg/provider/kubernetes/auth.go#L149 . Equivalent to `kubectl create token <serviceaccount>`. And then it tries to use this token to authenticate to the target cluster.

But that's not how it's done with EKS. With EKS, you need to get an AWS token, and then use the aws SDK to convert that to an "eks-token". The first half of that is implemented in the `aws` provider already: https://github.com/external-secrets/external-secrets/blob/26153cc9bdd25c233945f6856f433614b10841d0/pkg/provider/aws/auth/auth.go#L310 as explained on https://external-secrets.io/latest/provider/aws-secrets-manager/#eks-service-account-credentials

```
Pseudocode for what currently happens
$ kubectl create token <serviceaccount>
$ curl -H "Authentication: Bearer <srvaccount_token>" https://target_cluster_url:443/api/v1/namespaces/kafka/secrets
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "Unauthorized",
  "reason": "Unauthorized",
  "code": 401
}

```

```
# Log output
{"level":"error","ts":1721806209.063621,"logger":"controllers.ExternalSecret","msg":"could not get secret data from provider","ExternalSecret":{"name":"kafka-configuration-external-secret","namespace":"hazard-info-ingestion"},"error":"error retrieving secret at .data[0], key: hazard-info-ingestion, err: Unauthorized","stacktrace":"github.com/external-secrets/external-secrets/pkg/controllers/externalsecret.(*Reconciler).markAsFailed\n\t/home/runner/work/external-secrets/external-secrets/pkg/controllers/externalsecret/externalsecret_controller.go:348\ngithub.com/external-secrets/external-secrets/pkg/controllers/externalsecret.(*Reconciler).Reconcile\n\t/home/runner/work/external-secrets/external-secrets/pkg/controllers/externalsecret/externalsecret_controller.go:225\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.4/pkg/internal/controller/controller.go:114\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.4/pkg/internal/controller/controller.go:311\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.4/pkg/internal/controller/controller.go:261\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.4/pkg/internal/controller/controller.go:222"}

{"level":"error","ts":1721806209.072046,"msg":"Reconciler error","controller":"externalsecret","controllerGroup":"external-secrets.io","controllerKind":"ExternalSecret","ExternalSecret":{"name":"kafka-configuration-external-secret","namespace":"hazard-info-ingestion"},"namespace":"hazard-info-ingestion","name":"kafka-configuration-external-secret","reconcileID":"3a76093a-0930-4136-be51-f2ec16192381","error":"error retrieving secret at .data[0], key: hazard-info-ingestion, err: Unauthorized","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.4/pkg/internal/controller/controller.go:324\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.4/pkg/internal/controller/controller.go:261\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.4/pkg/internal/controller/controller.go:222"}
```

**Expected behavior**
I expected the `kubernetes` provider to fetch the proper credentials to authenticate with the target cluster, and then for it to populate the target secret.

If this is (as I suspect) not currently supported, I wish for the documentation to be updated to reflect this. I can provide a PR for that if that's the case.

```
Pseudocode for what is expected
$ (Get AWS Token from Serviceaccount mount via ISRA or similar)
$ aws --region eu-west-1 eks get-token --cluster-name target_cluster
$ curl -H "Authentication: Bearer <eks_token> https://target_cluster_url:443/api/v1/namespaces/kafka/secrets
{
  // json response with the actual contents
}
```

Currently the `aws` provider is halfway there when it comes to authentication. And the `kubernetes` provider knows how to fetch the data. So if this functionality should live in the `aws` provider or the `kubernetes` provider, I can't say. Ideally use the `aws` provider for auth and then the `kubernetes` provider for data fetching?

Maybe something like this:
```
# Not currently possible. Desired solution

apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: kafka-secret-store
spec:
  provider:
    kubernetes:
      auth:
        aws:
            jwt:
              serviceAccountRef:
                name: my-serviceaccount
      remoteNamespace: kafka
      server:
        eks:
            clusterName: target_cluster
```

Thanks in advance!
