### ISSUE TITLE
GCP: Support Multiple Workload Identity

### ISSUE THREAD

**Issue by tsawada** [external-secrets/external-secrets#372]
It'd be great if it is easy to configure external-secrets to use separate workload identity per SecretStore (or per namespace) in multi-tenant situations.

For example, in my cluster setup, each namespace has its dedicated service account. I would like to configure ExternalSecret in each namespace to fetch secrets from Secret Manager using the service account associated with the namespace via Workload Identity.

Added value:
This allows easy and secure multi-tenancy setup in GCP.

Alternative ways available:
1. Export credential keys for service accounts. Setup SecretStore in each namespace, with the exported keys.
    * problem: Less secure than Workload Identity. Use of keys are discouraged in favor of Workload Identity due to security risks. Have to manage key files, which can become cumbersome when there are many namespaces.
2. Run completely separate external-secrets instances in each namespace.
    * problem: complex setup. No how-to documents available

Observations:

Config connector's ConfigConnectorContext might be an example of how this could be solved. When configured as "namespaced mode", each namespace should create a ConfigConnectorContext resource that points to a service account the namespace wants to use. ConfigConnector watches this resource, and spins up a separate `cnrm-controller-manager-` StatefulSet per ConfigConnectorContext (in config connector's namespace) with the specified service account set as its workload identity.
https://cloud.google.com/config-connector/docs/how-to/advanced-install#creating_a_configconnectorcontext

Thanks!

**Comment by moolen** [comment]
Yes, please! This is missing in the GCP provider. relates to #261 and #251.

I suggest to integrate with GCP using service account tokens directly just like the folks at `csi-driver-provider-gcp` do here:

https://github.com/GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp/blob/main/auth/auth.go#L116-L172

I think we shouldn't care about how the tokens are created and just consume them. Creating these tokens and bindings is up to the user. 
Similar to how the AWS/EKS provider implements it ([docs](https://external-secrets.io/provider-aws-secrets-manager/#eks-service-account-credentials)) we could add a :
```yaml
apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: example
spec:
  provider:
      gcpsm:
        auth:
          # TODO: consider adding a new node for each authentication strategy
          #       e.g. "serviceAccountToken", "gcpServiceAccount"
          serviceAccountRef:
            name: my-serviceaccount
            namespace: xxx # only valid for ClusterSecretStore
        projectID: myproject                  # name of Google Cloud project
```
