### ISSUE TITLE
Doc: Lacking details and examples for Controller options

### ISSUE THREAD

**Issue by hhemied** [external-secrets/external-secrets#3743]
Documentation for [Controller Options](https://external-secrets.io/latest/api/controller-options/) are not clear which one needs to be used with what.
**The page also lacking examples.**

It's not clear where to change and add what.

```yaml
apiVersion: operator.external-secrets.io/v1alpha1
kind: OperatorConfig
metadata:
  name: sample
spec:
  # this must be set to false when using olm
  installCRDs: false
  # Default values copied from <project_dir>/helm-charts/external-secrets/values.yaml
  replicaCount: 1
  image:
    repository: ghcr.io/external-secrets/external-secrets
    pullPolicy: IfNotPresent
    tag: ""
  crds:
    createClusterExternalSecret: true
    createClusterSecretStore: true
  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""
  leaderElect: false
  controllerClass: ""
  scopedNamespace: ""
  scopedRBAC: false
  processClusterExternalSecret: true
  processClusterStore: true
  createOperator: true
  concurrent: 1
  serviceAccount:
    create: true
    annotations: {}
    name: ""
  rbac:
    create: true
  extraEnv: []
  extraArgs: {}
  deploymentAnnotations: {}
  podAnnotations: {}
  podLabels: {}
  podSecurityContext: {}
  securityContext: {}
  resources: {}
  prometheus:
    enabled: false
    service:
      port: 8080
  nodeSelector: {}
  tolerations: []
  affinity: {}
  priorityClassName: ""
  webhook:
    create: true
    certCheckInterval: "5m"
    replicaCount: 1
    certDir: /tmp/certs
    image:
      repository: ghcr.io/external-secrets/external-secrets
      pullPolicy: IfNotPresent
      tag: ""
    imagePullSecrets: []
    nameOverride: ""
    fullnameOverride: ""
    rbac:
      create: true
    serviceAccount:
      create: true
      annotations: {}
      name: ""
    nodeSelector: {}
    tolerations: []
    affinity: {}
    priorityClassName: ""
    prometheus:
      enabled: false
      service:
        port: 8080
    extraEnv: []
    extraArgs: {}
    deploymentAnnotations: {}
    podAnnotations: {}
    podLabels: {}
    podSecurityContext: {}
    securityContext: {}
    resources: {}
  certController:
    create: true
    requeueInterval: "5m"
    image:
      repository: ghcr.io/external-secrets/external-secrets
      pullPolicy: IfNotPresent
      tag: ""
    imagePullSecrets: []
    nameOverride: ""
    fullnameOverride: ""
    rbac:
      create: true
    serviceAccount:
      create: true
      annotations: {}
      name: ""
    nodeSelector: {}
    tolerations: []
    affinity: {}
    priorityClassName: ""
    prometheus:
      enabled: false
      service:
        port: 8080
    extraEnv: []
    extraArgs: {}
    deploymentAnnotations: {}
    podAnnotations: {}
    podLabels: {}
    podSecurityContext: {}
    securityContext: {}
    resources: {}
```
