### ISSUE TITLE
Merge secrets using find exceeds max size of secret

### ISSUE THREAD

**Issue by mproffitt** [external-secrets/external-secrets#3760]
**Describe the bug**

A key of `secret-name` is added to the managed secret when using `find`. The contents of this key are constantly being updated with an escaped version of the contents of the key, meaning the secret very quickly exceeds its size.

**To Reproduce**

This can be replicated easily with the following manifests:

<details>
<summary>ESO Manifests</summary>

```yaml
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test
  namespace: default
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: default
    kind: SecretStore
  dataFrom:
  - find:
      name:
        regexp: "^flux-project-ssa$"
  target:
    name: flux-project-ssa
    creationPolicy: Orphan
    deletionPolicy: Merge
    template:
      engineVersion: v2
      mergePolicy: Merge
      data:
        myproject: "{{ \"merge\" | b64enc }}"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test2
  namespace: default
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: default
    kind: SecretStore
  dataFrom:
  - find:
      name:
        regexp: "^flux-project-ssa$"
  target:
    name: flux-project-ssa
    creationPolicy: Orphan
    template:
      engineVersion: v2
      mergePolicy: Merge
      data:
        myproject2: "{{ \"merge\" | b64enc }}"
```

</details>

If the above manifests are applied, after about 10 minutes or so, the key of `flux-project-ssa` will overflow the max size of the secret, causing the secret to enter a `SecretSyncedError` state with the event `Secret "flux-project-ssa" is invalid: data: Too long: must have at most 1048576 bytes`

```bash
$ k delete secret flux-project-ssa; k apply -f externalsecret.yaml ; \
    while true; do \
        k get secrets flux-project-ssa -o yaml | yq '.data.flux-project-ssa | @base64d' | wc -c; \
        sleep 60; \
    done
externalsecret.external-secrets.io/test configured
externalsecret.external-secrets.io/test2 configured
4
99
311
811
2463
8723
33415
131835
525167
525167 <--- This overflowed and the ExternalSecrets are in SecretSyncedError
525167
```

2. provide the Kubernetes and ESO version

- ESO version: v0.9.20
- Server Version: v1.29.2

**Expected behavior**

Either: ESO should not add the key containing the contents of the secret
OR: ESO should correctly replace the value with a new merged version rather than a merged + escaped content

**Screenshots**

**Additional context**

This can be mitigated by adding a key with an empty value to the `target` template but this should not be necessary

```yaml
    template:
      engineVersion: v2
      mergePolicy: Merge
      data:
        flux-project-ssa: ""
        myproject2: "{{ \"merge\" | b64enc }}"
```

Edit: Attaching secret store config [eso-k8s.yaml.txt](https://github.com/user-attachments/files/16482388/eso-k8s.yaml.txt)
