### ISSUE TITLE
ExternalSecret using GCPSM ClusterSecretStore gcpsm-secret not found

### ISSUE THREAD

**Issue by allevimi** [external-secrets/external-secrets#3769]
**Describe the bug**
I have an ESO installed on namespace external-secrets, I'm using GCP Secret Manager and IAM Service Account as auth mechanism; as per docs, service account is stored in a **secret** on namespace external-secrets.
I created an ExternalSecret on namespace **example** referencing a ClusterSecretStore, but I'm getting SyncError due to `secrets "gcpsm-secret" not found`

**To Reproduce**
### Secret
```yaml
apiVersion: v1
kind: Secret
metadata:
  namespace: external-secrets
  name: gcpsm-secret
  labels:
    type: gcpsm
type: Opaque
stringData:
  secret-access-credentials: <sa_json>
```

### ClusterSecretStore
```yaml
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-store
spec:
  provider:
    gcpsm:
      auth:
        secretRef:
          secretAccessKeySecretRef:
            namespace: external-secrets
            name: gcpsm-secret
            key: secret-access-credentials
      projectID: gcp_project_id
```
NB: describing it after apply, field `spec.provider.gcpsm.auth.secretRef.secretAccessKeySecretRef.namespace` is gone... I suppose this is the problem

### ExternalSecret
```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  namespace: example
  name: database-user
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-store
  target:
    name: database-user
    creationPolicy: Owner
  data:
  - secretKey: secret
    remoteRef:
      key: gcpsm_database_user
```
Result status will be SecretSyncedError and getting event message
```
kubectl --namespace example events --for es/database-user

LAST SEEN            TYPE      REASON         OBJECT                                MESSAGE
70s (x36 over 99m)   Warning   UpdateFailed   ExternalSecret/database-user   error retrieving secret at .data[0], key: gcpsm_database_user, err: failed to create GCP secretmanager client: cannot get Kubernetes secret "gcpsm-secret": secrets "gcpsm-secret" not found
```
### Versions
K8S version: v1.28.11-gke.1019001
ESO version: 0.10.0

**Expected behavior**
I'm expecting that gcpsm-secret is been taken from **external-secrets** namespace as specified in ClusterSecretStore. 

**Additional context**
If I create gcpsm-secret on namespace **example**, everything works fine, but I think this is not the correct behavior.

**Comment by Skarlso** [comment]
Hello. Try adding some `conditions` to the clustersecretstore to allow ES to use the store in a different namespace.

```yaml
  # Conditions about namespaces in which the ClusterSecretStore is usable for ExternalSecrets
  conditions:
    # Options are namespaceSelector, namespaces or namespacesRegex
    - namespaceSelector:
        matchLabels:
          my.namespace.io/some-label: "value" # Only namespaces with that label will work

    - namespaces:
        - "namespace-a"
        - "namespace-b"

    # Namespace regexes are useful for policy management or when external tools auto-generate namespaces with prefixes/suffixes
    - namespaceRegexes:
        - "namespace-a-.*" # All namespaces prefixed by namespace-a- will work
        - "namespace-b-.*" # All namespaces prefixed by namespace-b- will work

    # conditions needs only one of the conditions to meet for the CSS to be usable in the namespace.
```
