### ISSUE TITLE
Secret getting updated by External Secrets controller when no update to the remote secret occurs

### ISSUE THREAD

**Issue by jharlow1** [external-secrets/external-secrets#3777]
**Describe the bug**

We have a secret being pulled using the 1password provider like:

```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: my-secrets
  namespace: my-namespace
spec:
  dataFrom:
  - extract:
      conversionStrategy: Default
      decodingStrategy: None
      key: mykey
      metadataPolicy: None
  refreshInterval: 5m
  secretStoreRef:
    kind: SecretStore
    name: mysecretstore
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: my-secret
```

The ExternalSecret object is created/owned by ArgoCD.

What we are seeing is that the Secret target gets updated mostly on the 5m refreshInterval (but not entirely consistently)

The only field that changes on the secret seems to be the resourceVersion

```
38c38
<   resourceVersion: '67003035'
---
>   resourceVersion: '67007502'
40a41
```

The only thing I can think of is that maybe somehow ArgoCD is fighting with external-secrets? But i can't figure out how to prove this or fix it if that's the case. Debug logs only show the secret being updated, not why there's a diff.

**To Reproduce**
See above

External secrets version 0.9.20
ArgoCD version 2.11.0

**Expected behavior**

Secret only updates when the actual data has changed in 1password.

**Screenshots**

n/a

**Additional context**

n/a
