### ISSUE TITLE
PushSecret needs an good example of how to use it

### ISSUE THREAD

**Issue by alexander-redmann-teaching** [external-secrets/external-secrets#3788]
**Is your feature request related to a problem? Please describe.**
I want to use the PushSecret after implementing successfully the normal ExternalSecret. When I create an secret before the PushSecret I've got "secret not managed by external-secrets", when I add it after the PushSecret it logs that "it couldn't be referenced"
But from the guide perspective i coludn't see what I'm doing wrong https://external-secrets.io/v0.10.0/guides/pushsecrets/

**Describe the solution you'd like**
A complete example of creating an secret and push it via PushSecret to the vault, not only the snippet part for the PushSecret.

** Snippet
Here is the code-snippet of the kuberenetes descriptors:
```
apiVersion: v1
kind: Secret
metadata:
  name: e2e-kubeconfig
  namespace: e2e-test
type: Opaque
data:
  kubeconfig: Hide
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: e2e-kubeconfig-push
  namespace: e2e-test
spec:
  refreshInterval: "5s"
  secretStoreRefs:
    - name: vault-e2e-secret-store
      kind: SecretStore
  selector:
    secret:
      name: e2e-kubeconfig
  data:
    - match:
        secretKey: kubeconfig
        remoteRef:
          remoteKey: "aks/clusters/private/prod/kube_configs/namespaces/e2e-test"
          property: config
```
The SecretStore is already used by ExternalSecret and can fetch secrets from the vault successfully.

Thanks for your advices
