### ISSUE TITLE
Permit ignore not recognized certificate in infisical provider

### ISSUE THREAD

**Issue by jorgelon** [external-secrets/external-secrets#3793]
**Is your feature request related to a problem? Please describe.**
When I deploy a self hosted infisical instance served via a self signed certificate I get this error:

kubectl describe css infisical
```
failed to authenticate via universal auth Post "https://XXX/api/v1/auth/universal-auth/login": tls: failed to verify certificate: x509: certificate signed by unknown authority
```
**Describe the solution you'd like**
Permit to ignore this

**Describe alternatives you've considered**
Offer a way to provider a ca certificate

**Additional context**
None

**Comment by Skarlso** [comment]
Could be fixed once https://github.com/external-secrets/external-secrets/pull/3699 is pushed and so a uniform way exists to load / provider certificates.

**Comment by akhilmhdh** [comment]
Hi @Skarlso @jorgelon 

Is this still an issue, or a stale one

**Comment by Skarlso** [comment]
I'm not sure, I don't know...

**Comment by adelmoradian** [comment]
I had a similar situation with the kubernetes provider trying to push secrets to a remote cluster. Initially got this error because I provided a wrong secret for caProvider... But once I provided the correct secret it worked 👍

**Comment by jorgephiguera** [comment]
Sorry for the delay. Does infisical SecretStore support CAprovider or something similar?

**Comment by Skarlso** [comment]
@jorgephiguera as of https://github.com/external-secrets/external-secrets/pull/5040 it should. It's not released yet though. :)

**Comment by Skarlso** [comment]
Huh, actually, no. Sorry. It doesn't support it.

**Comment by Skarlso** [comment]
Okay, so this is still open. The PR I linked first is merged, so now it could be used for Infisical to load up CAProvider data into their client.

Their client provides CACertificate `string` option:

```go
type Config struct {
	SiteUrl              string `default:"https://app.infisical.com"`
	CaCertificate        string
	UserAgent            string `default:"infisical-go-sdk"` // User-Agent header to be used on requests sent by the SDK. Defaults to `infisical-go-sdk`. Do not modify this unless you have a reason to do so.
	AutoTokenRefresh     bool   `default:"true"`             // Wether or not to automatically refresh the auth token after using one of the .Auth() methods. Defaults to `true`.
	SilentMode           bool   `default:"false"`            // If enabled, the SDK will not print any warnings to the console.
	CacheExpiryInSeconds int    // Defines how long certain API responses should be cached in memory, in seconds. When set to a positive value, responses from specific fetch API requests (like secret fetching) will be cached for this duration. Set to 0 to disable caching. Defaults to 0.
	CustomHeaders        map[string]string
}
```

So here:
```go
	sdkClient := infisicalSdk.NewInfisicalClient(ctx, infisicalSdk.Config{
		SiteUrl: infisicalSpec.HostAPI,
	})
```

Just add the certificate if it exists and you should be golden.

**Comment by jorgelon** [comment]
Great, thank you

I have found a temporary workaround with this values.yaml, passing a custom CA to the external-secrets pod. It uses the SSL_CERT_FILE environment variable with /etc/ssl/certs/ca-certificates.crt as value

This break things. It is neccesary, for example, to extract the original ca-certificates.crt, merge with it custom CA in the key ca.crt key in a configmap infisical-ca and apply the workaround

```yaml
extraVolumes:
  - name: infisical-ca
    configMap:
      name: infisical-ca
      defaultMode: 0644
extraVolumeMounts:
  - name: infisical-ca
    mountPath: /etc/ssl/certs/ca-certificates.crt
    subPath: ca.crt
    readOnly: true
```


I will follow the new external-secret releases to try #5040

**Comment by dharapandya85** [comment]
Can I work on this issue? Please assign me.

**Comment by dharapandya85** [comment]
```
var caCertData []byte
	if infisicalSpec.CAProvider!= nil{
		switch infisicalSpec.CAProvider.Type{
		case esv1beta1.CAProviderTypeSecret:
			var sec corev1.Secret
			name := clientObjectKey{
				Name:      infisicalSpec.CAProvider.Name,
				Namespace: namespace,
			}
			if infisicalSpec.CAProvider.Namespace != nil {
				name.Namespace = *infisicalSpec.CAProvider.Namespace
			}
			if err := kube.Get(ctx, name, &sec); err != nil {
				cancelSdkClient()
				return nil, fmt.Errorf("failed to get CAProvider: %w", err)
			}
			caCertData = []byte(sec.Data[infisicalSpec.CAProvider.Key])
	}
	sdkClient := infisicalSdk.NewInfisicalClient(ctx, infisicalSdk.Config{
		SiteUrl: infisicalSpec.HostAPI,
		CaCertificate: string(caCertData),
	})
```

This is failing in `provider.go`, `caCertData` is empty. Configuration is failing. 
```
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: infisical-secrets-store
spec:
  provider:
    infisical:
      hostAPI: "https://infisical.com"
      
      # caBundle:
      #   name: infisical-ca-secret
      #   key: ca.crt
      #   namespace: external-secrets
    
      secretsScope:
        projectSlug: "slug"  
        environmentSlug: "dev"            
      
      
      auth:
        universalAuthCredentials:
          clientId:
            key: clientId
            name: infisical-credentials
            namespace: external-secrets
          clientSecret:
            key: clientSecret
            name: infisical-credentials
            namespace: external-secrets
```
Applied `update-ca-certificates` and kubectl patch. Cannot reproduce the issue, 
```
kubectl describe clustersecretstore infisical-secrets-store
Name:         infisical-secrets-store
Namespace:
Labels:       <none>
Annotations:  <none>
API Version:  external-secrets.io/v1
Kind:         ClusterSecretStore
Metadata:
  Creation Timestamp:  2025-11-11T16:48:33Z
  Generation:          1
  Resource Version:    6041
  UID:                 d..
Spec:
  Provider:
    Infisical:
      Auth:
        Universal Auth Credentials:
          Client Id:
            Key:        clientId
            Name:       infisical-credentials
            Namespace:  external-secrets
          Client Secret:
            Key:        clientSecret
            Name:       infisical-credentials
            Namespace:  external-secrets
      Host API:         https://infisical.com
      Secrets Scope:
        Environment Slug:          dev
        Expand Secret References:  true
        Project Slug:             slug
        Recursive:                 false
        Secrets Path:              /
Events:                            <none>
```

How to proceed further. Used v1.0.0
