### ISSUE TITLE
SecretSyncedError in PulumiProvider after upgrading to 0.10.0

### ISSUE THREAD

**Issue by networkhermit** [external-secrets/external-secrets#3796]
**Describe the bug**

After upgrading ESO to 0.10.0, ExternalSecret fails with `SecretSyncedError` - UpdateFailed: undefined response type.

```text
{"level":"error","ts":1723638585.8175535,"logger":"controllers.ExternalSecret","msg":"could not get secret data from provider","ExternalSecret":{"name
":"oci-credential","namespace":"envoy-gateway-system"},"error":"undefined response type","stacktrace":"github.com/external-secrets/external-secrets/pk
g/controllers/externalsecret.(*Reconciler).markAsFailed\n\t/home/runner/work/external-secrets/external-secrets/pkg/controllers/externalsecret/external
secret_controller.go:357\ngithub.com/external-secrets/external-secrets/pkg/controllers/externalsecret.(*Reconciler).Reconcile\n\t/home/runner/work/ext
ernal-secrets/external-secrets/pkg/controllers/externalsecret/externalsecret_controller.go:226\nsigs.k8s.io/controller-runtime/pkg/internal/controller
.(*Controller).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.4/pkg/internal/controller/controller.go:114\nsigs.k8s.io/cont
roller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.4/pkg/internal/c
ontroller/controller.go:311\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.
k8s.io/controller-runtime@v0.18.4/pkg/internal/controller/controller.go:261\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Star
t.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.4/pkg/internal/controller/controller.go:222"}
```

**To Reproduce**
1. provide all relevant manifests

```yaml
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: pulumi-oci-credential
  namespace: default
spec:
  provider:
    pulumi:
      accessToken:
        secretRef:
          key: PULUMI_ACCESS_TOKEN
          name: pulumi-credential
      apiUrl: https://api.pulumi.com
      environment: example
      organization: example
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oci-credential
  namespace: default
spec:
  dataFrom:
    - extract:
        key: oci-credential
  secretStoreRef:
    kind: SecretStore
    name: pulumi-oci-credential
  target:
    deletionPolicy: Delete
    name: oci-credential
```

It works when I change the apiUrl to `https://api.pulumi.com/api/preview`, taken from https://github.com/external-secrets/external-secrets/pull/3597.

2. provide the Kubernetes and ESO version

Kubernetes: v1.30.3+k3s1

ESO: v0.10.0

**Expected behavior**

Secret using pulumi provider got synced, without opting into preview api.

**Comment by Skarlso** [comment]
Sooo... it works...?

**Comment by networkhermit** [comment]
> Sooo... it works...?

No. It doesn't make sense if pulumi preview api is needed when upgrading to ESO 0.10.0.

At least it's a regression or breaking change.

BTW, I think changing provider default in crd like https://github.com/external-secrets/external-secrets/pull/3597 is against the best practice.

**Comment by Skarlso** [comment]
In normal cases for sure. But this a minor version upgrade which can have breaking changes ( it has another one for webhooks ). It was planned to be released like that, but you are absolutely right that I forgot to add it to the release notes for better visibility.

That said, the default was changed because the library was changed from an older unsupported one to a more recent one.

Arguably, that could have been done separately, but the functionality needed was in the more recent library with the more recent API.

My apologies for the inconvenience. We'll make sure to be more visible on provider breaking changes.

**Comment by networkhermit** [comment]
> That said, the default was changed because the library was changed from an older unsupported one to a more recent one.

If that is the case, the following provider document should be updated too. As for ESO v0.10.0，the apiUrl can only be set to https://api.pulumi.com/api/preview.

From https://external-secrets.io/v0.10.0/provider/pulumi/:

> If required, the API URL (apiUrl) can be customized as well. If not specified, the default value is https://api.pulumi.com/api/preview.

**Comment by Skarlso** [comment]
The problem is that I'm not sure how to support the old one. I mean, we could import both libraries I guess and detect which URL is used. 🤔 But that would be weird I think? I'm not sure, WDYT?

**Comment by networkhermit** [comment]
Well, as Pulumi ESC itself is a preview feature, it's not really a big issue to break compatibility.

> We'll make sure to be more visible on provider breaking changes.

I think this visibility is enough.

**Comment by BoatPartyJesus** [comment]
We have had similar issue today in v0.10.3, setting url to: `https://api.pulumi.com/api/esc` solved the issue. 

```yaml
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: pulumi-esc-staging
  namespace: external-secrets
spec:
  provider:
    pulumi:
      accessToken:
        secretRef:
          key: accessKey
          name: esc-key
      apiUrl: https://api.pulumi.com/api/esc
      environment: "project/environment"
      organization: org-id
```
