### ISSUE TITLE
Support extract (GetSecretMap()) in Bitwarden provider

### ISSUE THREAD

**Issue by justSem** [external-secrets/external-secrets#3799]
**Is your feature request related to a problem? Please describe.**
The `extract` stanza is not implemented in the Bitwarden Provider, meaning that you can't put a JSON map into the value field for external secrets to parse.

**Describe the solution you'd like**
Right now using
```yaml
dataFrom:
  - extract:
```
Yields a `GetSecretMap() not implemented` error.
Bitwarden doesn't support multiple values in secrets, it does however support multiline, allowing one to past a JSON map in there like you can do in GCSM, as referenced in the example [here](https://external-secrets.io/latest/guides/all-keys-one-secret/)

**Describe alternatives you've considered**
I think using the `fromYaml` helper function might help as an intermediate solution.
Though a more 'universal' approch might be implementing a `fromJson` helper function that could yield the same functionality.
Edit: A mention that `fromJson` is already available as sprig funtion.

**Comment by justSem** [comment]
For people reading this and wondering the same. There is an intermediate solution. It's just not pretty.
I'll just leave this here as this isn't fully documented and I've been fighting to get this work all night :)

Please keep in mind that there is a caveat.
If you make an error in your JSON, it'll error out whilst syncing because `fromJson` can't decode the values.

Example:
```yaml
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: my-secret
spec:
  refreshInterval: 10s
  secretStoreRef:
    name: bitwarden-secrets
    kind: ClusterSecretStore
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: my-secret
    template:
      engineVersion: v2
      data:
        EXAMPLE_KEY_ONE: '{{ ( .my_secret | fromJson ).EXAMPLE_KEY_ONE}}'
        EXAMPLE_KEY_TWO: '{{ ( .my_secret | fromJson ).EXAMPLE_KEY_TWO}}'
        EXAMPLE_KEY_THREE: '{{ ( .my_secret | fromJson ).EXAMPLE_KEY_THREE }}'
        
  data:
  - secretKey: my_secret
    remoteRef: 
      key: my-secret

```
