### ISSUE TITLE
Unlimited Reconcile

### ISSUE THREAD

**Issue by timrhomberg16** [external-secrets/external-secrets#3817]
**Describe the bug**
The external-secrets Operator updates the Kubernetes Secret every time, the postgres Operator changes something in it. It should instead only update it according to the refresh time, which i set to 1 hour.

**To Reproduce**
My External Secret Object looks like this. It updates the secret and put the password in it. The Postgres Cluster updates the secret and puts all other fields in it like dbname, verifier and so on. After the Postgres Cluster is finished, the external secret Operator updates the secrets again and it is stuck in an reconcile loop.

```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: XXXXX-pg-XXXXX-pguser-XXXXX
  namespace: XXXXX-pg-XXXXX
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: XXXXX/pg/XXXXX-pg-XXXXX-pguser-XXXXX
      metadataPolicy: None
      property: password
    secretKey: password
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: default-secretstore
  target:
    creationPolicy: Oprhan
    deletionPolicy: Retain
    name: XXXXX-pg-XXXXX-pguser-XXXXX
    template:
      engineVersion: v2
      mergePolicy: Replace
      type: Opaque
```

**Expected behavior**
The Secret should be updatet according to the refreshintervall.

**Additional context**
The goal should be to update the secrets of the postgres cluster
