### ISSUE TITLE
PKCS12 function template is generating different data whenever refreshInterval is reached

### ISSUE THREAD

**Issue by mfmbarros** [external-secrets/external-secrets#3819]
**Describe the bug**

When using PKCS12 function templates ( pemToPkcs12 and fullPemToPkcs12 ) , the output looks different whenever refreshInterval is reached. I noticed this as I have a PushSecret pushing a secret  that depends on those function templates) into Azure Keyvault secret. When looking at that secret on Azure Key Vault side, I realised there are many dozens of previous versions, without having any changes on source secret.

**To Reproduce**

My PushSecret resource:

```
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: mypush
  namespace: mynamespace
spec:
  refreshInterval: 10s # Refresh interval for which push secret will reconcile
  secretStoreRefs: # A list of secret stores to push secrets to
    - name: azure-store
      kind: SecretStore
  selector:
    secret:
      name: source-secret
  template:
    data:
      pfx: |
        {{ fullPemToPkcs12 (index . "tls.crt") (index . "tls.key") }}
  data:
    - match:
        secretKey: pfx
        remoteRef:
          remoteKey: secret/cert-pfx
```

ESO version: v0.10.0
Kubernetes version: AKS 1.29.7

**Expected behavior**

As there's no changes on the source ( in this case represented by tls.crt and tls.key in K8s secret ) , wasn't expecting to have any new secret version on Azure Key Vault.

**Screenshots**

**Additional context**

Full flow: Cert-manager secret -> ESO PushSecret -> Azure KeyVault

Also, tried to inspect the content, via openssl,  of those many versions of the secret and it seems the part that looks different lies on Encrypted Private Key but on K8s secret side, there was no change.
