### ISSUE TITLE
Generate multiple passwords within one secret containing multiple key-value pairs as template

### ISSUE THREAD

**Issue by l-rossetti** [external-secrets/external-secrets#3823]
**Is your feature request related to a problem? Please describe.**
The problem is that I would like to generate a secret whose template contains multiple key-value pairs via the `Password` generator. The problem has been highlighted in [discussion-3820](https://github.com/external-secrets/external-secrets/discussions/3820). At the moment you can only generate one password per secret which is not very flexible.

**Describe the solution you'd like**
As describe in the referenced page one idea might be to simply allow the user to provide, as parameter, the generated output key name, instead of defaulting it to `password` (although password might still be the default if no value is provided).

Here an example:
```yaml
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: random-string-0-9-a-z
spec:
  length: 64
  digits: 5
  symbols: 0
  symbolCharacters: ""
  noUpper: false
  allowRepeat: true
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: auth-secrets
spec:
  refreshInterval: "30m"
  target:
    name: auth-secrets 
    template:
      type: Opaque
      data:
        key1: "{{ .mykey1 | toString }}"
        key2: "{{ .mykey2 | toString }}"
  dataFrom:
  - sourceRef:
       generatorRef:
         apiVersion: generators.external-secrets.io/v1alpha1
         kind: Password
         name: random-string-0-9-a-z
         generatedKeyName: mykey1 # --> here the key name override to be referenced within the template section
  - sourceRef:
       generatorRef:
         apiVersion: generators.external-secrets.io/v1alpha1
         kind: Password
         name: random-string-0-9-a-z
         generatedKeyName: mykey2   # --> here the key name override to be referenced within the template section

```
