### ISSUE TITLE
dataFrom.find support nested templateFrom literal json values 

### ISSUE THREAD

**Issue by ilyastoliar** [external-secrets/external-secrets#3825]
**Is your feature request related to a problem? Please describe.**
I want to be able to create from aws secret like this `aws_secret:{"secret_key":"secret_value"}`
So basically I want to filter the "`secret_key`" and use only the "`secret_value`" as value and "`aws_secret`" as the key

```
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
data:
  aws_secret: secret_value
type: Opaque
```

**Describe the solution you'd like**
I'm trying to achieve that by
```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: my-secret
spec:
  dataFrom:
  - find:
      name:
        regexp: "/path/to/secrets"
    rewrite:
    - regexp:
        source: "/path/to/secrets/(.*)"
        target: "$1"
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: my-secret
    template:
      engineVersion: v2
      templateFrom:
        - target: Data
          literal: |-
            {{- range $key, $val := . }}
                {{ $key }}: {{ $val.secret_key | quote }}
              {{- end }}
            {{- end }}
```

**Describe alternatives you've considered**
Also tried: 
```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: my-secret
spec:
  dataFrom:
  - find:
      name:
        regexp: "/path/to/secrets"
    rewrite:
    - regexp:
        source: "/path/to/secrets/(.*)"
        target: "$1"
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: my-secret
    template:
      engineVersion: v2
      templateFrom:
        - target: Data
          literal: |-
            {{- range $key, $val := . }}
              {{- range $subKey, $subVal := $val }}
                {{ $key }}: {{ $subVal | quote }}
              {{- end }}
            {{- end }}
```

Currently the secret is not created at all even though the external secret is synced and ready, also there is not error in the logs
