### ISSUE TITLE
I would like to reference a config map as a data source for an external secret.

### ISSUE THREAD

**Issue by vyas-n** [external-secrets/external-secrets#3840]
**Is your feature request related to a problem? Please describe.**

I'm currently using External Secrets to template secrets for PostgreSQL connections:

Format
```
postgres://{{ .username }}:{{ .password }}@{{ .endpoint }}:{{ .port }}/{{ .dbName }}?sslmode={{ .sslmode }}
```

But the PostgreSQL helm chart that I'm using only stores the password key in a secret. The rest of these values are only stored in the generated configmap.

**Describe the solution you'd like**

I'd like a way to reference a value in a configmap the same way we can currently reference values in secrets:

For example:
```
    - configKey: <name-of-key>
      remoteRef:
        key: <config-map-name>
        property: <config-map-key>

```

**Describe alternatives you've considered**

I'm currently hard-coding the non-sensitive values into the template, but this is not ideal because most of these values are generated from other helm charts and can change over time.

**Additional context**

N/A

**Comment by gusfcarvalho** [comment]
hi @vyas-n  - templates already support using configmaps as basis. Can you confirm this is the feature you need?

**Comment by vyas-n** [comment]
Hey @gusfcarvalho,

Not in this case, if I understand the existing config map support, it has to have the full go template with variable placeholders that can only be replaced with secrets.

That's not the situation I have. Here's a clearer example of what I'm trying to do:
```
apiVersion: v1
kind: ConfigMap
data:
  database: <redacted>
  username: <redacted>
  sslmode: <redacted>
  port: <redacted>
  endpoint: <redacted>
```
- apiVersion: v1
  data:
    password: <redacted>
  kind: Secret
```

The above Secret & ConfigMap are dynamically generated, so I don't have the ability to hardcode the values into the template.

The feature I'm asking for is to use an ExternalSecret template to pull values from both the above Secret & the ConfigMap:
```
postgres://{{ .username }}:{{ .password }}@{{ .endpoint }}:{{ .port }}/{{ .database }}?sslmode={{ .sslmode }}
```

**Comment by gaima8** [comment]
How about this?

```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: database
data:
  username: <redacted>
...
---
apiVersion: v1
kind: Secret
metadata:
  name: database
data:
  password: <redacted>
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: externalsecret
spec:
  refreshInterval: 1m
  target:
    template:
      engineVersion: v2
      data:
        DSN: "postgres://{{ .username }}:{{ .password }}@{{ .endpoint }}:{{ .port }}/{{ .database }}?sslmode={{ .sslmode }}"
  data:
    - secretKey: username
      configMapRef:
        name: database
        key: username
    - secretKey: password
      secretRef:
        name: database
        key: password
...
```

No `secretStoreRef` or `remoteRef` included as nothing is from a remote secret store. I'd certainly like to retain the option to pull from all three at the same time though.
`configMapRef` and `secretRef` the same as `envFrom` for containers.

I almost certainly have zero ability to implement any of this, sorry, I just want it.
