### ISSUE TITLE
Regression in v0.9.19 when using 'default' in secret templates

### ISSUE THREAD

**Issue by rmoesbergen** [external-secrets/external-secrets#3843]
**Describe the bug**
We have secret templates that use the default filter in the template, like this:

```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: my-secrets
spec:
  dataFrom:
  - find:
      conversionStrategy: Default
      decodingStrategy: None
      name:
        regexp: acme.*
    rewrite:
    - regexp:
        source: acme_(.*)
        target: $1
  - find:
      conversionStrategy: Default
      decodingStrategy: None
      name:
        regexp: .*_staging
    rewrite:
    - regexp:
        source: (.*)_staging
        target: $1
    sourceRef:
      storeRef:
        kind: ClusterSecretStore
        name: shared-secret-store
  refreshInterval: 10m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: project-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    name: my-secrets
    template:
      data:
        LANGFUSE_HOST: '{{ ((.langfuse | default "{}") | fromJson).host | default "" }}'
        LANGFUSE_PUBLIC_KEY: '{{ ((.langfuse | default "{}") | fromJson).public_key | default "" }}'
        LANGFUSE_SECRET_KEY: '{{ ((.langfuse | default "{}") | fromJson).secret_key | default "" }}'
      engineVersion: v2
      mergePolicy: Replace
      type: Opaque
```

This used to work in v0.9.18, but started throwing this error in 0.9.19 and higher:
```
could not apply template: could not execute template: could not execute template: unable to execute template at key LANGFUSE_HOST: unable to execute template at key LANGFUSE_HOST: template: LANGFUSE_HOST:1:5: executing \"LANGFUSE_HOST\" at <.langfuse>: map has no entry for key \"langfuse\"","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.3/pkg/internal/controller/controller.go:324\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.3/pkg/internal/controller/controller.go:261\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.3/pkg/internal/controller/controller.go:222


could not apply template: could not execute template: could not execute template: unable to execute template at key 
LANGFUSE_PUBLIC_KEY: unable to execute template at key LANGFUSE_PUBLIC_KEY: template: LANGFUSE_PUBLIC_KEY:1:5: 
executing \"LANGFUSE_PUBLIC_KEY\" at <.langfuse>: map has no entry for key \"langfuse\"",
"stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.4/pkg/internal/controller/controller.go:324\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.4/pkg/internal/controller/controller.go:261\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.4/pkg/internal/controller/controller.go:222"}
```

**To Reproduce**
1. See the example above
2. Kubernetes = GKE 1.29.7, version 0.9.19

**Expected behavior**
I expect the templates that work in 0.9.18 to keep working in 0.9.19.

**Additional context**
The ClusterSecretStore's we use are google secret manager stores. The .langfuse key is present in some, but not all secrets, so that's why we provide a default when it's not there.
