### ISSUE TITLE
cert-controller container emitting "Failed to watch *v1.ValidatingWebhookConfiguration: unknown (get validatingwebhookconfigurations.admissionregistration.k8s.io)" logger="UnhandledError"

### ISSUE THREAD

**Issue by AdamStaudt** [external-secrets/external-secrets#3844]
**Describe the bug**
Since the update to external-secrets v0.10.1, the `cert-controller` container is emitting the following error:

```E0828 09:27:06.311366       1 reflector.go:158] "Unhandled Error" err="pkg/mod/k8s.io/client-go@v0.31.0/tools/cache/reflector.go:243: Failed to watch *v1.ValidatingWebhookConfiguration: unknown (get validatingwebhookconfigurations.admissionregistration.k8s.io)" logger="UnhandledError"```

**To Reproduce**
update external-secrets controller to v0.10.1. no other changes in configuration or manifests from previous versions which do not emit this error.

external-secrets v0.10.1 running on EKS 1.30

**Expected behavior**
No error messages in logs

**Additional context**
I can resolve this by adding the `watch` verb privilege to `apiGroups.admissionregistration.k8s.io` with `resources.validatingwebhookconfigurations` in the `external-secrets-cert-controller` ClusterRole, so that it looks like this:
```
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  verbs:
  - list
  - watch
```

This ClusterRole also has
```
- apiGroups:
  - admissionregistration.k8s.io
  resourceNames:
  - secretstore-validate
  - externalsecret-validate
  resources:
  - validatingwebhookconfigurations
  verbs:
  - get
  - watch
  - update
  - patch
```
  
  however, the error message looks like it's referring to a webhook that isn't one of the two referenced there (i.e. "unknown").
  I am not sure if the errors we're seeing are a result of something specific to our configuration, or if this is an oversight in the helm chart since the release of v0.10.1.
