### ISSUE TITLE
Webhook provider with bearer authentication token

### ISSUE THREAD

**Issue by andreyolv** [external-secrets/external-secrets#3871]
**Is your feature request related to a problem? Please describe.**
I would like to do exactly this python equivalent using the webhook provider:

```
import requests

url = 'https://yyyyyyyyyyy'
client_id = 'zzzzzzzzzzz'
client_secret = 'kkkkkkkkkk'
token_url = 'https://xxxxxxxxxx/oauth2/token'

# first request to get bearer token
auth_response = requests.post(
    token_url,
    data={
        'grant_type': 'client_credentials',
        'client_id': client_id,
        'client_secret': client_secret
    },
    verify=False
)

access_token = auth_response.json().get('access_token')

# second request to send bearer token and get credentials
headers = {
    'Authorization': f'Bearer {access_token}'
}

conteudo = requests.get(url, headers=headers, verify=False)
resp = conteudo.json()

resp
```

The Webhook provider only allows you to configure 1 url and 1 request, but the way I would like it would need 2 urls for 2 requests. One to get the bearer token and one to send the bearer token.

According to what I read in the documentation, it is not possible to recover credentials this way, right? Would it be interesting to have this possibility?

Or do you have any way to do this using the operator? If so, would it be good to have a documented example?

Thanks

**Comment by gberche-orange** [comment]
My team has worked around the lack of bearer authentication token with a cronjob which generates a secret containing a bearer token, and then reference it in the `Authorization` header as follows. 

```yaml
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: credhub-set
spec:
  provider:
    webhook:
      [...]

      headers:
        Content-Type: application/json
        Authorization: Bearer {{ print .auth.bearer_token }}

      secrets:
      - name: auth
        secretRef:
          name: webhook-credentials
```

```yaml
apiVersion: v1
kind: Secret
metadata:
  labels:
    external-secrets.io/type: webhook
  name: webhook-credentials
type: Opaque
data:
  bearer_token: ZX...
```

Luckily, the auth credentials is reloaded by the webhook secretstore for each get/push, so we did not meet issues with expired bearer token that could have been cached.
