### ISSUE TITLE
ExternalSecret should not set `reason: SecretSynced` when not all secret are synced

### ISSUE THREAD

**Issue by DrummyFloyd** [external-secrets/external-secrets#3879]
**Describe the bug**
when you provide a list of data[] to fetch from the provider, if some secret are missing, the ExternalSecret should not gave the  `reason: SecretSynced `but something more explicit, like `PartialSync` or `NotSync`

**To Reproduce**
1. provide all relevant manifests
```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  labels:
    xrandomsecret.common.xor.io/name: test-random-ppsr5
  name: test-random-ppsr5-test-secrets
  namespace: crossplane
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: toto
      metadataPolicy: None
    secretKey: foobar # exist in the provider
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: foobar4
      metadataPolicy: None
    secretKey: foobar4 # do not exist atm in the provider
  refreshInterval: 10s
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-kv-css-xxxxxxxxxxxxx
  target:
    creationPolicy: Owner
    deletionPolicy: Merge
    name: test-random-ppsr5-test-secrets
    template:
      data: {}
      engineVersion: v2
      mergePolicy: Replace
      metadata:
        annotations:
          a1: a1
        labels:
          l1: l1
      templateFrom: []
      type: Opaque

```
2. provide the Kubernetes and ESO version
K8S: 1.30.0
ESO:  0.10.2

**Expected behavior**
Should set a different reason, beacause not everysecret is sync
