### ISSUE TITLE
Templating secrets with static and Vault values is not idempotent and results random rendering from multiple sources

### ISSUE THREAD

**Issue by germainlefebvre4** [external-secrets/external-secrets#3897]
**Describe the bug**

When defining a `PushSecret` with templating v2 with values from static (attributes in `spec.template.data`) and kubernetes secret (attributes from `spec.selector.secret.name`) source and push to Vault (secrets in `spec.data[*].match.remoteRef.remoteKey`), it appears that a computed value asserting a variable from the 2 sources with the same name does not provide the same result at each time.

**To Reproduce**

1) Setup Vault to welcome the rendered values

2) Here are the manifests

```yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: pg-secret
data:
  PGUSER: YWRtaW4= # admin
  PGPASSWORD: cGFzc3dvcmQ= # password
  PGHOST: bG9jYWxob3N0 # localhost
  PGPORT: NTQzMg== # 5432
  POSTGRESQL_SSLMODE: cmVxdWlyZQ== # require
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: pg-pushsecret
spec:
  deletionPolicy: Delete
  refreshInterval: 5s
  secretStoreRefs:
    - name: css-vault # ClusterSecretStore to target a Vault instance. Not provided in the example.
      kind: ClusterSecretStore
  selector:
    secret:
      name: pg-secret
  template:
    mergePolicy: Merge
    engineVersion: v2
    data:
      POSTGRESQL_SSLMODE: "verify-ca"
      POSTGRESQL_URI: "postgresql://{{ .PGUSER }}:{{ .PGPASSWORD }}@{{ .PGHOST }}:{{ .PGPORT }}/defaultdb?sslmode={{ .POSTGRESQL_SSLMODE }}" # Raw manifest
      # POSTGRESQL_URI: "postgresql://{{ `{{ .PGUSER }}` }}:{{ `{{ .PGPASSWORD }}` }}@{{ `{{ .PGHOST }}` }}:{{ `{{ .PGPORT }}` }}/defaultdb?sslmode={{ `{{ .POSTGRESQL_SSLMODE }}` }}" # Helm chart
  data:
  - conversionStrategy: None
    match:
      secretKey: PGUSER
      remoteRef:
        remoteKey: aap/test/bug
        property: PGUSER
  - conversionStrategy: None
    match:
      secretKey: PGPASSWORD
      remoteRef:
        remoteKey: aap/test/bug
        property: PGPASSWORD
  - conversionStrategy: None
    match:
      secretKey: PGHOST
      remoteRef:
        remoteKey: aap/test/bug
        property: PGHOST
  - conversionStrategy: None
    match:
      secretKey: PGPORT
      remoteRef:
        remoteKey: aap/test/bug
        property: PGPORT
  - conversionStrategy: None
    match:
      secretKey: POSTGRESQL_SSLMODE
      remoteRef:
        remoteKey: aap/test/bug
        property: PGSSLMODE
  - conversionStrategy: None
    match:
      secretKey: POSTGRESQL_URI
      remoteRef:
        remoteKey: aap/test/bug
        property: POSTGRESQL_URI
```

* The static variable `POSTGRESQL_SSLMODE` always assert `verify-ca` as expected.
* The computed variable `POSTGRESQL_URI` randomly renders/asserts the static variable `POSTGRESQL_SSLMODE` (which is `verify-ca`) or the Kubernetes secret `POSTGRESQL_SSLMODE` (which is `require`)
    * Once `postgresql://admin:password@localhost:5432/defaultdb?sslmode=verify-ca` (with the right static var)
    * Once `postgresql://admin:password@localhost:5432/defaultdb?sslmode=require` (with the wrrong k8s secret var)

4) Provide the Kubernetes and ESO version

* Kubernetes: `v1.30.0`
* * ESO: `v0.9.20`

**Expected behavior**

* Variable `POSTGRESQL_SSLMODE` should render `verify-ca` (which is the case)
* Variable `POSTGRESQL_URI` should render `postgresql://admin:password@localhost:5432/defaultdb?sslmode=verify-ca` (which is randomly the case)

**Additional context**

The impacts from this behavior is the regeneration of the secret in Vault, which automatically triggers the restart of the pods at the end of the supply chain.

**Comment by gusfcarvalho** [comment]
hi @germainlefebvre4  - did you try to _not_ add the fetch for the verify-ca information?


IIRC - we do not include other `data` blocks into the templates - you cannot use them as a dependency of other blocks. in order to achieve this logic you want, you need to create a different templating scheme (or, simpler, just rename this):

```
  - conversionStrategy: None
    match:
      secretKey: T_POSTGRESQL_SSLMODE
      remoteRef:
        remoteKey: aap/test/bug
        property: PGSSLMODE
```

with a template like this:
```
      POSTGRESQL_SSLMODE: {{ .T_POSTGRESQL_SSL_MODE}}
      POSTGRESQL_URI: "postgresql://{{ .PGUSER }}:{{ .PGPASSWORD }}@{{ .PGHOST }}:{{ .PGPORT }}/defaultdb?sslmode={{ .T_POSTGRESQL_SSL_MODE}}" # Raw manifest
```
