### ISSUE TITLE
AWS SecretManager Metadata secretPushFormat: string is ignored 

### ISSUE THREAD

**Issue by tomasz-lyko** [external-secrets/external-secrets#3906]
**Describe the bug**
The `secretPushFormat: string` in the PushSecret specification is being ignored, and the secret is still being stored in AWS Secrets Manager in binary format. This issue occurs even though the secret is explicitly configured to be pushed as a string.

**To Reproduce**

We have simple secret in key:value format
`KEYCLOAK_CLIENT_SECRET: xyz`

```
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: streams-secrets-store
  namespace: platform-keycloak
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-west-1
      auth:
        jwt:
          serviceAccountRef:
            name: streams-dge-external-secrets-sa
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: dge-argonath-keycloak-push-secret
  namespace: platform-keycloak
spec:
  secretStoreRefs:
    - name: streams-secrets-store
      kind: SecretStore
  selector:
    secret:
      name: dge-argonath-keycloak-secrets
  data:
    - match:
        secretKey: KEYCLOAK_CLIENT_SECRET
        remoteRef:
          remoteKey: streams/dge/keycloak/credentialss
      metadata:
        secretPushFormat: string
```

2. provide the Kubernetes and ESO version
Kubernetes version:  `v1.29.7-eks-2f46c53`
(ESO) version: `0.9.12`

**Expected behavior**
The expected result is that the secret should be stored in plaintext (key-value format) in AWS Secrets Manager.

**Screenshots**
![Screenshot 2024-09-13 at 09 30 49](https://github.com/user-attachments/assets/eefaa307-d873-4679-9bd6-dc53b12581e2)

**Comment by Skarlso** [comment]
Ah, I think this has been updated, but poorly communication. :/ The way the metadata has to be provided now is like an object.

```yaml
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: pushsecret-example # Customisable
  namespace: default # Same of the SecretStores
spec:
  deletionPolicy: Delete # the provider' secret will be deleted if the PushSecret is deleted
  refreshInterval: 10s # Refresh interval for which push secret will reconcile
  secretStoreRefs: # A list of secret stores to push secrets to
    - name: aws-parameterstore
      kind: SecretStore
  selector:
    secret:
      name: pokedex-credentials # Source Kubernetes secret to be pushed
  data:
    - match:
        remoteRef:
          remoteKey: my-first-parameter # Remote reference (where the secret is going to be pushed)
      metadata:
        parameterStoreType: "SecureString"
```

**Comment by Skarlso** [comment]
Or rather `String` in your case I guess.

**Comment by tomasz-lyko** [comment]
Unfortunately It did not help for both `"String"` and `"string"`
```
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: dge-argonath-keycloak-push-secret
  namespace: platform-keycloak
spec:
  secretStoreRefs:
    - name: streams-secrets-store
      kind: SecretStore
  selector:
    secret:
      name: dge-argonath-keycloak-secrets
  data:
    - match:
        secretKey: KEYCLOAK_CLIENT_SECRET
        remoteRef:
          remoteKey: streams/dge/keycloak/credentials
      metadata:
        secretPushFormat: "string"
```
