### ISSUE TITLE
beyondtrust provider: implement GetAllSecrets function

### ISSUE THREAD

**Issue by dmpe** [external-secrets/external-secrets#3925]
**Is your feature request related to a problem? Please describe.**

I am somewhat struggling to fetch all secrets from BT Secrets Safe.

I have 1 group which has multiple subgroups. Some of these subgroups have their own secrets; at the same time "ESO_Group" has a few secrets on its own too. 

![image](https://github.com/user-attachments/assets/21722ba2-b0e3-4ee7-b83e-d6cd39401975)

Ultimately, ESO_Group contains now 2 secrets and via external secrets operator I am trying to fetch all of them. 

Unfortunately, operator is printing `GetAllSecrets not implemented`

**Describe the solution you'd like**

Support something like this:

```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: beyondtrust-external-secret
  namespace: external-secrets
spec:
  refreshInterval: 300s
  secretStoreRef:
    kind: SecretStore
    name: secretstore-beyondtrust
  target:
    name: my-beyondtrust-secret # name of secret to create in k8s secrets (etcd)
    creationPolicy: Owner
  dataFrom:
    - find: 
        name: 
          regexp: ".*"
        path: ESO_Group
```

maybe @btfhernandez you would know ? (otherwise thank you very much for your effort here, greetings BT customer)

Thanks. 

version of BT: `24.1.1.268`, ESO operator 0.10.3
