### ISSUE TITLE
Unable to pull multiple SSM Params based on path

### ISSUE THREAD

**Issue by willhume** [external-secrets/external-secrets#3937]
**Describe the bug**
When I try to query parameters in the SSM provider using dataFrom it returns an ssm error.

Error
```
ValidationException: Parameter name: can't be prefixed with "ssm" (case-insensitive). If formed as a path, it can consist of sub-paths divided by slash symbol; each sub-path can be formed as a mix of letters, numbers and the following 3 symbols .-_
```
None of the secrets have ssm in the name and secrets work if you use the exact key rather then path.

**To Reproduce**
1. provide all relevant manifests
2. ExternalSecret resource
```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: foo-ssm-params
  namespace: foo
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: parameterstore
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: foo-configs
  dataFrom:  
    - extract:
          key: /foo/
```

3. provide the Kubernetes and ESO version
EKS:  1.30
ESO: v0.10.1

**Expected behavior**
it should create a secret with all the parameters in the object
