### ISSUE TITLE
[Infisical] - I'm not able to read recursive secrets

### ISSUE THREAD

**Issue by Tchoupinax** [external-secrets/external-secrets#3938]
**Describe the bug**
With Infisical store, when the password is on the root path, it works well. When the password is inside a folder, it is not found (the find + regex show it well)

**Additional context**
I open a pull request to improve this behaviour

**Comment by Tchoupinax** [comment]
Hello,
The work in #3939 fixes one part of the issue but not all and I guess the second part is from Infisical (or maybe I'm doing something wrong)

```
error retrieving secret at .data[0], key: folder1/folder2, err: unable to unmarshal secret:
invalid character '<' looking for beginning of value
```

My secret
```
  data:
    - secretKey: accessKey
      remoteRef:
        key: folder1/folder2
        property: secretKey
```

My store configuration
```
      secretsScope:
        projectSlug: project-name-j-h52
        environmentSlug: prod
        secretsPath: "/"
        recursive: true
```

**Comment by crstian19** [comment]
Is this working after this https://github.com/external-secrets/external-secrets/pull/3939? @Tchoupinax can you give me an example? I've tried everything and still can't get it to work.

```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: infisical-managed-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore  
    name: infisical          
  target:
    name: immich-secret      
  dataFrom:
  - extract:
      key: immich    # infisical folder name
```
