### ISSUE TITLE
Support Secret Config in PushSecret

### ISSUE THREAD

**Issue by apresti12** [external-secrets/external-secrets#3954]
Currently, there is no way to add much configuration to a remote secret through the `pushSecret` object when the secret is initially created.  Specifically, I would like to be able to add additional config to my secretStore ref to tell the controller to include specific configuration on creation, such as a pubsub notification topic for a GCP SM Secret.

Example interface:
```
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: gcp-secret-with-topic
  namespace: app
spec:
  providerSecretConfig:
  secretStoreRefs:
    - name: gcp-secretstore
      kind: SecretStore
  data:
    - conversionStrategy: None # Also supports the ReverseUnicode strategy
      match:
        secretKey: best-pokemon # Source Kubernetes secret key to be pushed
        remoteRef:
          secretConfig: # Maybe this is just a map[string]interface{} that is parsed later
              topics:
                - "projects/xyz/topics/mytopic"
          remoteKey: my-first-parameter
```

Example Implementation:
- the GCP secret manager protobuf already supports the `topics` field https://pkg.go.dev/cloud.google.com/go/secretmanager@v1.14.1/apiv1/secretmanagerpb#Secret 
```
func (c *Client) PushSecret(ctx context.Context, secret *corev1.Secret, pushSecretData esv1beta1.PushSecretData) error {
...
  gcpSecret, err = c.smClient.CreateSecret(ctx, &secretmanagerpb.CreateSecretRequest{
			Parent:   fmt.Sprintf("projects/%s", c.store.ProjectID),
			SecretId: pushSecretData.GetRemoteKey(),
                         Secret: &secretmanagerpb.Secret{
				Labels: map[string]string{
					managedByKey: managedByValue,
				},
				Replication: replication,
                                Topics: GetSMTopics(),
			},
		})
```

I would be happy to contribute on this if it's within the scope of the roadmap for the push secret functionality

**Comment by realsystem** [comment]
It will be a very nice feature if implemented, notifications can be used for automatic secret rotation.

**Comment by Coder63** [comment]
We have a comparable use case and consider this a highly valuable feature if we are able to implement it. We kindly request your assistance in adding this feature to the roadmap for ES

**Comment by Skarlso** [comment]
We have a way to pass in provider specific configuration through the metadata field (which is under redesign atm but that's besides the point).

So any extra information can be encoded in that field, similar to how we do it for AWS provider:
```yaml
  data:
    - match:
        secretKey: key1 # Source Kubernetes secret key to be pushed
        remoteRef:
          remoteKey: teamb-my-first-parameter-3 # Remote reference (where the secret is going to be pushed)
      metadata:
        secretPushFormat: string
```
