### ISSUE TITLE
Webhook: ClusterSecretStore does not pass the provided Secret namespace when using type Secret

### ISSUE THREAD

**Issue by samwambach** [external-secrets/external-secrets#3959]
**Describe the bug**

I am unable to upgrade past v0.9.12 due to what appears to be a bug with the caProvider Secret type for the webhook provider. After upgrading, the ClusterSecretStore becomes unready with status 'InvalidProviderConfig' and error message `failed to get cert from secret: failed to resolve secret key ref: cannot get Kubernetes secret "my-certificate": an empty namespace may not be set when a resource name is provided`

However, I am providing a namespace for the secret:
```yaml
spec:
  provider:
    webhook:
      caProvider:
        key: ca.crt
        name: my-certificate
        namespace: secret-system
        type: Secret
```

After tracing this through with a debugger the issue seems to be caused because a StoreKind is not provided to the `wh` Webhook in NewClient(). 

line 65 webhook.go
```go
wh := webhook.Webhook{
	Kube:      kube,
	Namespace: namespace,
}
```

When `whClient.wh.GetHTTPClient(ctx, provider)` is called on line 85 it gets called with StoreKind unset on `wh`. 

Once we reach SecretKeyRef() in secret_ref.go, the conditional fails because storeKind is empty and therefor `key.Namespace` does not get assigned the value of `ref.Namespace`
```go
if (storeKind == esv1beta1.ClusterSecretStoreKind) && (ref.Namespace != nil) {
        key.Namespace = *ref.Namespace
}
```

When the key is passed to c.Get(), the namespace of the secret is missing, resulting in the error.

**Proposed Fix**
A simple fix would be to add StoreKind on creation of wh
```go
wh := webhook.Webhook{
	Kube: kube,
	Namespace: namespace,
	StoreKind: store.GetObjectKind().GroupVersionKind().Kind,
}
```

Running this fix through the debugger results in the namespace being properly added to key.Namespace and a successful call to `c.Get(ctx, key, secret)`.

**To Reproduce**
Observed this bug on k8s v1.28 and all versions of external-secrets above v0.9.12

Create a ClusterSecretStore that uses caProvider Secret type, resulting in `InvalidProviderConfig  2s (x13 over 23s)  cluster-secret-store  failed to get cert from secret: failed to resolve secret key ref: cannot get Kubernetes secret "my-certificate": an empty namespace may not be set when a resource name is provided`

```yaml
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: my-secret-store
spec:
  provider:
    webhook:
      caProvider:
        key: ca.crt
        name: my-certificate
        namespace: secret-system
        type: Secret
      headers:
        Authorization: Basic {{ print .auth.USER ":" .auth.PASS | b64enc }}
        Content-Type: application/json
      method: GET
      result:
        jsonPath: $
      secrets:
      - name: auth
        secretRef:
          name: auth-secret
          namespace: secret-system
      url: https://myservice.secret-system.svc.cluster.local:8000/secrets/{{
        .remoteRef.key | replace "%2F" "/" | replace "%3F" "?" | replace "%3D" "="
        | replace "%26" "&" }}
```

**Expected behavior**
I expect the provided namespace to be used when retrieving the caProvider Secret type.
