### ISSUE TITLE
webhook cluster secret store to use service account in namespace associated with external secret

### ISSUE THREAD

**Issue by vamsinm** [external-secrets/external-secrets#3963]
we are looking to create cluster secret store with webhook that uses service account for authentication. we want to use service account from the namespace where external secret is trying to connect to cluster secret store. we will have the same service account in all namespaces but will have access to different secrets based on namespace. 

```
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: webhook-cluster-store
spec:
  provider:
    webhook:
      headers:
        Authorization: '{{ .saauth.token }}'
        Content-Type: application/json
      result:
        jsonPath: $.data.secret
      secrets:
        - name: saauth
          secretRef:
            name: eso-creds-managed
      url: 'https://webhook.url/secrets?name={{ .remoteRef.key }}&env=test'
```
i tried to create with out namespace and see error: `err: no namespace on ClusterScoped webhook secret eso-creds-managed`

also tried templating but did not work either:

```
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: webhook-cluster-store
spec:
  provider:
    webhook:
      headers:
        Authorization: '{{ .saauth.token }}'
        Content-Type: application/json
      result:
        jsonPath: $.data.secret
      secrets:
        - name: saauth
          secretRef:
            name: eso-creds-managed
            namespace: '{{ .namespace }}'
      url: 'https://webhook.url/secrets?name={{ .remoteRef.key }}&env=test'
```
err: failed to get clustersecretstore webhook secret eso-creds-managed: secrets \"eso-creds-managed\" not found". 

secret named eso-creds-managed is available in dev namespace.

external secret:

```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
    force-sync: '1727116922'
  name: demo-es
  namespace: dev
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: secret
        metadataPolicy: None
      secretKey: secret
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: webhook-cluster-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: demo-secret
status:
  conditions:
    - lastTransitionTime: '2024-09-26T22:40:57Z'
      message: could not get secret data from provider
      reason: SecretSyncedError
      status: 'False'
      type: Ready
```
