### ISSUE TITLE
VaultDynamicSecret: Add auth method "None"

### ISSUE THREAD

**Issue by ambis** [external-secrets/external-secrets#3975]
**Is your feature request related to a problem? Please describe.**
When using kind: VaultDynamicSecret, it requires you to spesify `.spec.provider.auth`. In our case, we talk to a Vault Agent that does the auth itself, and the API proxy it provides requires no auth (access strictly controlled by Network Policies, also this is a very dynamic CI kubernetes where test namespaces come and go).

**Describe the solution you'd like**
If I could either leave the VauldDynamicSecret.spec.provider.auth as {} or tell it to use "None" or which ever way would be most suitable to have it do no auth.

**Describe alternatives you've considered**
There really are none, because with every auth method it tries to make an auth which fails.

**Comment by Skarlso** [comment]
I think this falls on the same side as https://github.com/external-secrets/external-secrets/issues/3927 right?

**Comment by ambis** [comment]
Do you mean that it would be "unsafe" for ExtSec users to configure a VaultDynamicSecret to not use an auth method?

**Comment by Skarlso** [comment]
No, I mean that you have a case for allowing no auth at all. :)

**Comment by ambis** [comment]
I realized I could test this with an empty token. Looks like it works. This is hacky and ugly, but at least of now we can get this working with this:

```yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: test
stringData:
  token: "" # This must be empty!

---
apiVersion: generators.external-secrets.io/v1alpha1
kind: VaultDynamicSecret
metadata:
  name: test
spec:
  method: GET
  path: /path/to/our/secret/engine
  resultType: Data
  provider:
    server: http://my-vault-agent.my-vault-agent.svc.cluster.local
    auth:
      tokenSecretRef:
        key: token
        name: test

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test
spec:
  target:
    name: test
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: VaultDynamicSecret
          name: test

```
