### ISSUE TITLE
helm chart 0.9.11 to 0.10.4 results in: remote error: tls: handshake failure, SecretStore, vault

### ISSUE THREAD

**Issue by lknite** [external-secrets/external-secrets#3978]
**Describe the bug**
Upgrading external-secrets helm chart from 9.11 to 10.4 results in an SecretStore error:
```
unable to log in to auth method: unable to log in with app role auth: Put "https://vfp-vault-ip.<redacted>:8200/v1/auth/approle-k-infra-admin/login": remote error: tls: handshake failure
```
- I can rollback the chart to 0.9.11 and then the SecretStore begins working again.
- When I install the external-secrets helm chart, I don't have anything in my values.yaml, no customizations.  Do I need to define something now with 10.4?

**To Reproduce**
1. provide all relevant manifests
```
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: sealed-secrets
spec:
  provider:
    vault:
      server: https://vfp-vault-vip.<redacted>:8200
      path: "k-infra-admin"
      # Version is the Vault KV secret engine version.
      # This can be either "v1" or "v2", defaults to "v2"
      version: "v2"
      auth:
        # AppRole auth: https://www.vaultproject.io/docs/auth/approle
        appRole:
          path: "approle-k-infra-admin"
          roleId: <redacted>
          secretRef:
            name: "approle"
            key: "vault-token"
#      caProvider:
#        key: ca.crt
#        name: k.<redacted>
#        namespace: sealed-secrets
#        type: Secret
```
The 'caProvider' shouldn't be needed, and isn't used in the 9.11 helm chart which works.

2. provide the Kubernetes and ESO version
```
kubernetes version: v1.30.1
eso helm chart versions 0.9.11 and 0.10.4
```

**Expected behavior**
I was hoping for things to work after upgrading to 0.10.4.

**Additional context**
I see the breaking fix when going to 0.10, about adding the label to secrets, but I don't think I have any secrets which need to be labeled around this secretstore.

**Comment by lknite** [comment]
I'm using a secret in the auth.appRole ... maybe that needs the new "external-secrets.io/type: webhook" label, testing ...

**Comment by lknite** [comment]
Tested more charts, looks like 9.16 works and in 9.17 the issue appears

**Comment by Skarlso** [comment]
Hello. Can you please provide the complete error message so I know where it's coming from? This is not something we throw. So I need some context.

**Comment by lknite** [comment]
{"level":"error","ts":1727983658.9061542,"logger":"controllers.ExternalSecret","msg":"could not get secret data from provider","ExternalSecret":{"name":"sealed-secrets-shared-key","namespace":"sealed-secrets"},"error":"error retrieving secret at .data[0], key: private/vfp/vfp-admin/sealed-secrets, err: the desired SecretStore sealed-secrets is not ready","stacktrace":"github.com/external-secrets/external-secrets/pkg/controllers/externalsecret.(*Reconciler).markAsFailed\n\t/home/runner/work/external-secrets/external-secrets/pkg/controllers/externalsecret/externalsecret_controller.go:333\ngithub.com/external-secrets/external-secrets/pkg/controllers/externalsecret.(*Reconciler).Reconcile\n\t/home/runner/work/external-secrets/external-secrets/pkg/controllers/externalsecret/externalsecret_controller.go:210\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.0/pkg/internal/controller/controller.go:114\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.0/pkg/internal/controller/controller.go:311\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.0/pkg/internal/controller/controller.go:261\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.0/pkg/internal/controller/controller.go:222"}
{"level":"error","ts":1727983658.9112535,"msg":"Reconciler error","controller":"externalsecret","controllerGroup":"external-secrets.io","controllerKind":"ExternalSecret","ExternalSecret":{"name":"sealed-secrets-shared-key","namespace":"sealed-secrets"},"namespace":"sealed-secrets","name":"sealed-secrets-shared-key","reconcileID":"008d45cf-bc2b-46da-880c-dbcf00c52738","error":"error retrieving secret at .data[0], key: private/vfp/vfp-admin/sealed-secrets, err: the desired SecretStore sealed-secrets is not ready","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.0/pkg/internal/controller/controller.go:324\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.0/pkg/internal/controller/controller.go:261\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.0/pkg/internal/controller/controller.go:222"}
{"level":"error","ts":1727983703.1910534,"logger":"controllers.SecretStore","msg":"unable to validate store","secretstore":{"name":"sealed-secrets","namespace":"sealed-secrets"},"error":"could not get provider client: unable to log in to auth method: unable to log in with app role auth: Put \"https://vfp-vault-vip.<redacted>:8200/v1/auth/approle-k-infra-admin/login\": remote error: tls: handshake failure","stacktrace":"github.com/external-secrets/external-secrets/pkg/controllers/secretstore.reconcile\n\t/home/runner/work/external-secrets/external-secrets/pkg/controllers/secretstore/common.go:69\ngithub.com/external-secrets/external-secrets/pkg/controllers/secretstore.(*StoreReconciler).Reconcile\n\t/home/runner/work/external-secrets/external-secrets/pkg/controllers/secretstore/secretstore_controller.go:66\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.0/pkg/internal/controller/controller.go:114\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.0/pkg/internal/controller/controller.go:311\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.0/pkg/internal/controller/controller.go:261\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.0/pkg/internal/controller/controller.go:222"}
{"level":"error","ts":1727983703.1991944,"msg":"Reconciler error","controller":"secretstore","controllerGroup":"external-secrets.io","controllerKind":"SecretStore","SecretStore":{"name":"sealed-secrets","namespace":"sealed-secrets"},"namespace":"sealed-secrets","name":"sealed-secrets","reconcileID":"abbb8812-1a56-47b6-89b4-b0b2ce9083a4","error":"could not get provider client: unable to log in to auth method: unable to log in with app role auth: Put \"https://vfp-vault-vip.<redacted>:8200/v1/auth/approle-k-infra-admin/login\": remote error: tls: handshake failure","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.0/pkg/internal/controller/controller.go:324\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.0/pkg/internal/controller/controller.go:261\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.0/pkg/internal/controller/controller.go:222"}

**Comment by lknite** [comment]
What is weird is that by rolling back the helm chart by one fixes it.  So certs must be ok, vault must be ok, and credentials to access things must be ok ...

**Comment by Skarlso** [comment]
When you say that caProvider shouldn't be needed, does that mean that everything works if you DO provide it?

**Comment by Skarlso** [comment]
I know which PR causes this. It's this one: https://github.com/external-secrets/external-secrets/pull/3072

**Comment by Skarlso** [comment]
It was released in [v0.9.12](https://github.com/external-secrets/external-secrets/releases/tag/v0.9.12). So most likely there has been SOME kind of change that does what you think is happening.

**Comment by Skarlso** [comment]
Oh actually, it might be this: https://github.com/external-secrets/external-secrets/pull/3018/files

mTLS for Vault..

**Comment by lknite** [comment]
I mean, I shouldn't need to provide a ca-bundle because the company where I work has a public domain and certs that have a ca-chain that's included by default.  Those certs are used internally in this case by the vault instance I'm accessing.  If I rollback the helm chart and do not provide a caProvider everything still works, no certificate verification errors.  I do have a cert available to put in the caProvider field, if we wanted to perform tests with that (I already have, it didn't help).

**Comment by lknite** [comment]
when i tested all the helm charts worked 0.9.11 - 0.9.16, it wasn't until 0.9.17 that it failed; i haven't tried testing past 0.9.17 (other than 0.10.4 that failed)

**Comment by Skarlso** [comment]
The secret store refactor shouldn't matter. :/ It's a certificate issue for sure, but I don't see what's causing it.

**Comment by Skarlso** [comment]
I think I know what's up. :) 

There was a minor version bump of the vault client going from 16-17.

```
	github.com/hashicorp/vault/api v1.12.2
	github.com/hashicorp/vault/api v1.13.0
```

The minor version change included a bunch of rework around certificates so now Login of their includes a certificate check. I'm looking into if it can be disabled.

**Comment by Skarlso** [comment]
Yes. There is a `TLSConfig` now, that has an `Insecure` flag. We don't expose that ofc...

**Comment by Skarlso** [comment]
There is a TLSConfig that can be used to enabled insecure connections. But we don't expose that option.

**Comment by Skarlso** [comment]
You need to set `tls` inside the `vault` store setting like this:
```yaml
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: example
spec:
  provider:
    vault:
      server: "https://vault.acme.org"
      path: "secret"
      version: "v2"

      # client TLS related configuration
      caBundle: "..."
      tls:
        clientCert:
          name: "my-cert-secret"
          key: "tls.crt"
        secretRef:
          name: "my-cert-secret"
          key: "tls.key"

      # the authentication methods are not really related to the client TLS configuration
      auth:
        ...
```
