### ISSUE TITLE
Fetch secrets from two different vault KV2 mount points

### ISSUE THREAD

**Issue by abnvanand** [external-secrets/external-secrets#3980]
**Is your feature request related to a problem? Please describe.**
Is it possible to fetch secrets from 2 separate mount points using vault provider so as to be able to inject both secrets into a template file?

So, I have 2 secret mount points of KV2 type.
```
vault secrets list
Path                                                                                Type            Accessor                 Description
----                                                                                 ----              --------                 -----------
mount1/                                                                              kv              kv_abcd123              n/a
mount2/                                                                             kv              kv_abcdefg              n/a
``` 

**Describe the solution you'd like**
I want to be able to inject secrets at path mount1/secret1 and mount2/secret2 into same K8s secret created by ExternalSecret.
using `ExternalSecret.spec.target.template`

**Describe alternatives you've considered**
I tried setting SS.provider.vault.path to "" empty 

```yaml
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: https://my.vault.com
      path: "" # Set this to empty
      version: v2
      namespace: ""
      auth:
         ...
```

and then using full path in External Secret
```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example-secret
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: combined-secrets
  data:
  - secretKey: username1
    remoteRef:
      key: mount1/secret1
      property: username
  - secretKey: username2
    remoteRef:
      key: mount2/secret2
      property: username
```

**Additional context**
