### ISSUE TITLE
Kubernetes provider can not authenticate with Client Certificates

### ISSUE THREAD

**Issue by greenmapc** [external-secrets/external-secrets#3998]
**Describe the bug**
During the configuration of kubernetes provider, there is a bug to use tls certificates. When I create SecretStore with auth type Client Certificates I get `InvalidProviderConfig` status for SecretStore object with description 

> failed to prepare auth: no auth provider given

**To Reproduce**

Create SecretStore. The configuration (like url) should be valid and secrets should exist.

```
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: test-secretstore
  namespace: default
spec:
  provider:
    kubernetes:
      remoteNamespace: default
      server:
        url: https://k8s.orb.local:26443
        caProvider:
          type: ConfigMap
          name: ca.crt
          key: ca.crt
      auth:
        cert:
          clientCert:
            name: "sa-certs"
            key: "tls.crt"
          clientKey:
            name: "sa-certs"
            key: "tls.key"
```
2. Apply manifest
3. `kubectl describe secretstores.external-secrets.io test-secretstore` provides with error: ` Warning  InvalidProviderConfig  4s (x12 over 15s)  secret-store  failed to prepare auth: no auth provider given`

ESO Version **external-secrets-0.10.0**
Kubernetes Version: 
minikube
``` kubectl version
Client Version: v1.29.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.3
```

**Expected behavior**
SecretStore authenticates with certificates.

**Additional context**
I made a bit of investigation, the problem popped up in version 0.9.20 and most probably was caused by **[PR](https://github.com/external-secrets/external-secrets/pull/3628)**

According the code, [this part of the code](https://github.com/external-secrets/external-secrets/blob/a5ddd97c217fb11afb0c7a401c2bd82731e06641/pkg/provider/kubernetes/auth.go#L74) can not be reached if no token or SA specified.
