### ISSUE TITLE
unable to validate store: NoCredentialProviders: no valid providers in chain. Deprecated. For verbose messaging see aws.Config.CredentialsChainVerboseErrors

### ISSUE THREAD

**Issue by brandon-cai** [external-secrets/external-secrets#4012]
**Describe the bug**
Running into an issue with creating a `ClusterSecretStore` in our AWS EKS cluster. All of the pods inherit the worker node role, which has access to AWS Secrets Manager. I have two environments with identical configurations: one environment is able to communicate with Secrets Manager and successfully create the ClusterSecretStore without issue, and the other cluster I am getting an error. I pulled these logs out of the external-secrets pod. I've cross-checked manifests to verify that the clusters are configured correctly and they seem nearly identical. 

```
{"level":"info","ts":1729011905.369762,"logger":"provider.aws","msg":"using aws session","region":"us-east-1","external id":"","credentials":null}
{"level":"error","ts":1729011908.5027807,"logger":"controllers.ClusterSecretStore","msg":"unable to validate store","clustersecretstore":{"name":"cluster-secrets-store"},"error":"could not validate provider: NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors","stacktrace":"github.com/external-secrets/external-secrets/pkg/controllers/secretstore.reconcile\n\t/home/runner/work/external-secrets/external-secrets/pkg/controllers/secretstore/common.go:69\ngithub.com/external-secrets/external-secrets/pkg/controllers/secretstore.(*ClusterStoreReconciler).Reconcile\n\t/home/runner/work/external-secrets/external-secrets/pkg/controllers/secretstore/clustersecretstore_controller.go:65\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:116\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:303\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:224"}
{"level":"error","ts":1729011908.5105143,"msg":"Reconciler error","controller":"clustersecretstore","controllerGroup":"external-secrets.io","controllerKind":"ClusterSecretStore","ClusterSecretStore":{"name":"cluster-secrets-store"},"namespace":"","name":"cluster-secrets-store","reconcileID":"2afdfcc6-4e8f-4a22-ad0a-bb1c553f2452","error":"could not validate provider: NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:224"}
```

Is there a specific configuration needed for external-secrets to use a worker node role? I'm not sure what's missing here since I was able to get it working in the first cluster but not this identical cluster that's just in a different AWS account.

**To Reproduce**
1. Create ArgoCD Application:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-{{.Values.region}}-{{.Values.environment}}
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.10.4
    chart: external-secrets
    helm:
      parameters:
        - name: "installCRDs"
          value: "true"
  destination:
    namespace: external-secrets
    server: {{ .Values.destination.server }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
```
2. Create ClusterSecretStore
```
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: cluster-secrets-store
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.region }}
  conditions:
    - namespaces:
      - {omitted}
      - newrelic

```
3. Versions: 
- Kubernetes: 1.30
- ESO: 0.10.4
- EKS Platform: eks.8
- Addons:
  - Amazon VPC CNI: v1.18.1-eksbuild.3
  - kube-proxy: v1.30.0-eksbuild.3
  - CoreDNS: v1.11.1-eksbuild.8
  - Amazon EKS Pod Identity Agent: v1.3.0-eksbuild.1

**Expected behavior**
`ClusterSecretStore` is successfully created.

**Additional context**
- I get the same error when trying to create a SecretStore
