### ISSUE TITLE
Improve documentation for AWS ECRAuthenticationToken

### ISSUE THREAD

**Issue by BrianKopp** [external-secrets/external-secrets#4015]
**Is your feature request related to a problem? Please describe.**
As a new user of External Secrets Operator, I would love to see a more complete example of using the AWS ECRAuthenticationToken generator to create a Kubernetes image pull secret.

**Describe the solution you'd like**
An example of the accompanying ExternalSecret required to plumb an ECR token from the ECRAuthenticationToken generator into a kubernetes secret. Similar to the example provided for Azure Container Registry.

**Describe alternatives you've considered**
It might be good to centralize the dockerconfigjson sample templates into the Examples or Guides section, and refer to those from the various container token generators.

**Additional context**
I would be happy to write these docs if this seems worthwhile to yall! I lost a few hours because I assumed that ECRAuthenticationToken would automatically format the resulting secret.

**Comment by phyber** [comment]
Do you have an example of how you formatted the secret that you could post here until the documentation is fixed? I'm currently struggling with this at the moment. Thanks!

**Comment by BrianKopp** [comment]
Good idea! I ended up using this:

```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ecr-docker
spec:
  refreshInterval: "1h"
  target:
    name: ecr-docker
    template:
      type: kubernetes.io/dockerconfigjson
      metadata:
        annotations:
          expiresAt: "{{ .expires_at }}"
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "{{ .proxy_endpoint }}": {
                "username": "{{ .username }}",
                "password": "{{ .password }}"
              }
            }
          }

  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: ECRAuthorizationToken
        name: ecr-auth-token
```
