### ISSUE TITLE
Problem with ESO + AWS Secret Manager

### ISSUE THREAD

**Issue by vietwow** [external-secrets/external-secrets#4017]
I'm running EKS 1.31, and deployed "External Secrets Operator (ESO)" using official helm chart (chart version "0.10.4" without any user-supplied values), then intergate with AWS Secret Manager by give Pod Identity and start using below config :

```
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secret-manager
  namespace: external-secrets
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa
```

and :

```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-github-apps
  namespace: external-secrets
spec:
  refreshInterval: 1h

  secretStoreRef:
    kind: SecretStore
    name: aws-secret-manager

  target:
    name: argocd-github-apps
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        url: '{{ .url }}'

  data:
  - secretKey: url
    remoteRef:
      key: lz/argocd-github-apps
      property: url
```

In AWS Secret Manager, I created secret "lz/argocd-github-apps", type is plaintex, the content is : {"url":"abc"}

Everything is fine, I got k8s secret with the content key "url" and the value is based64 encoded of "abc".

Now, (as the requirement from https://argo-cd.readthedocs.io/en/stable/operator-manual/argocd-repo-creds-yaml/), I want the value in k8s secret is plaintext (not based64 encoded), so I changed the above code, in part :
url: '{{ .url }}'
to:
url: '{{ .url | b64dec }}'

Then I noticed that :
- if the length of value in "url" key in "lz/argocd-github-apps" is 4, 8 ,12, ...  (means 4 * n) characters, for example "abcd" or "1234" or "http", ... so it works as expected, means I got plaintext
- Otherwise, for example, length of value is 3, 5, ... characters, I still got based64 encoded value.
**Note**: I understand that b64 encode is default behaviour in k8s secret (not ESO), but if that's true, why I can got plaintext with cases 4-n length characters ?

Any one has idea on this issue ? Thank you so much.

Best Regards,
