### ISSUE TITLE
Unable to use Hashicorp ClusterSecretStore

### ISSUE THREAD

**Issue by urbaman** [external-secrets/external-secrets#4018]
**Describe the bug**
The ClusterSecretStore cannot be used:

- Cannot read the token if put into external-secrets namespace (invalid vault credentials: configured Vault token contains non-printable characters and cannot be used)
- Cannot find the token secret from an externalSecret if without namespace

**To Reproduce**

```
apiVersion: v1
kind: Secret
metadata:
  name: vault-token
  namespace: external-secrets
data:
  token: <base64RootToken>
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
  namespace: external-secrets
spec:
  provider:
    vault:
      server: "https://vault.domain.com"
      path: "kv-secrets"
      # Version is the Vault KV secret engine version.
      # This can be either "v1" or "v2", defaults to "v2"
      version: "v2"
      auth:
        # points to a secret that contains a vault token
        # https://www.vaultproject.io/docs/auth/token
        tokenSecretRef:
          name: "vault-token"
          key: "token"
```

**Expected behavior**
The clusterSecretStore should be able to use the token
