### ISSUE TITLE
PushSecret not works with kv2 secret engine in vault

### ISSUE THREAD

**Issue by shenshanyoumu** [external-secrets/external-secrets#4028]
code snippet as below:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: push-secret-demo
  namespace: demo
data:
  sourcekey1: IntcImZvb1wiOlwiYmFyXCJ9Ig== # Needs to be a JSON
  sourcekey2: YmFy  # Could be a plain string
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: qa-api-server-tls-push-secret
  namespace: demo
spec:
  refreshInterval: 10s
  secretStoreRefs:
    - name: qa-demo-mtls-eso-vault-store
      kind: SecretStore
  selector:
    secret:
      name: push-secret-demo
  data:
    - match:
        secretKey: sourcekey1
        remoteRef:
          remoteKey: qa/api-server
          property: sourcekey1
```

I can make sure secretStore with read-write capalities, and can read secrets from vault to generate a k8s secrets as expectly, but when use PushSecret error as below:
"pushsecret  set secret failed: could not write remote ref sourcekey1 to target secretstore qa-demo-mtls-eso-vault-store: secret not managed by external-secrets"

My ESO version is  v0.9.20
