### ISSUE TITLE
Create a clusterscoped Password generator

### ISSUE THREAD

**Issue by jsalatiel** [external-secrets/external-secrets#4031]
Currently the password generator is namespace scoped, so one have to create the same generator for each namespace I want generate a random password. It would be awesome If we could have a cluster scoped Password generator that one could just refer directly from a sourceRef in any externalSecret in any namespace.

**Comment by DrummyFloyd** [comment]
Would quite game changing , bit annoying to declare same rule over different namespace
+ 
Now due to https://github.com/external-secrets/external-secrets/pull/3965

**Comment by Skarlso** [comment]
I believe there were security concerns involved in having a cluster scoped generator. I'll try to look up the arguments later on.

**Comment by DrummyFloyd** [comment]
If it's a security issue , can we add a dedicated cluster generator , like `ClusterPassword` 

Because ESO had already some cluster scope CRD 

Like `ClusterSecretStore` ?
Like this is up to the user to handle this security issue ?

**Comment by Skarlso** [comment]
Here: https://github.com/external-secrets/external-secrets/issues/3290#issuecomment-2459858683

**Comment by Skarlso** [comment]
It's not just the random password generator. The `Generator` interface and respectively all other generators that implement it are the ones that would need to be cluster scoped which means ANY generator can be cluster scoped if that makes sense.

**Comment by DrummyFloyd** [comment]
> It's not just the random password generator. The `Generator` interface and respectively all other generators that implement it are the ones that would need to be cluster scoped which means ANY generator can be cluster scoped if that makes sense.

i'll get it atm all Generator come from the same struct,
so  how hard, it would be to make the generator clusterScope aat this point ? 
or provide a `namespace` key to references

```yaml
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: pushsecret-example # Customisable
  namespace: default # Same of the SecretStores
spec:
  updatePolicy: Replace # Policy to overwrite existing secrets in the provider on sync
  deletionPolicy: Delete # the provider' secret will be deleted if the PushSecret is deleted
  refreshInterval: 10s # Refresh interval for which push secret will reconcile
  secretStoreRefs: # A list of secret stores to push secrets to
    - name: aws-parameterstore
      kind: SecretStore
  selector:
    secret:
      name: pokedex-credentials # Source Kubernetes secret to be pushed
    # Alternatively, you can point to a generator that produces values to be pushed
    generatorRef:
      apiVersion: external-secrets.io/v1alpha1
      kind: ECRAuthorizationToken
      name: prod-registry-credentials
      namesapce: foo # here
      
    ```
