### ISSUE TITLE
Vault provider try login every 5 min

### ISSUE THREAD

**Issue by tot19** [external-secrets/external-secrets#4032]
### Discussed in https://github.com/external-secrets/external-secrets/discussions/3011

<div type='discussions-op-text'>

<sup>Originally posted by **Ethonwu** January 10, 2024</sup>
Hi community 
I try to use external-secrets integration in our Vault service 
I used appRole and secretID to access Vault 
But Vault log shows our k8s do login and revoke-self every 5 min
<img width="1127" alt="MicrosoftTeams-image" src="https://github.com/external-secrets/external-secrets/assets/13677052/120a2bfe-1cca-4a93-9f1c-1c8584ec6fe7">

Can I modify this duration? 

helm value 
```
affinity: {}
certController:
  affinity: {}
  create: true
  deploymentAnnotations: {}
  extraArgs: {}
  extraEnv: []
  extraVolumeMounts: []
  extraVolumes: []
  fullnameOverride: ""
  hostNetwork: false
  image:
    pullPolicy: IfNotPresent
    repository: ghcr.io/external-secrets/external-secrets
    tag: ""
  imagePullSecrets: []
  metrics:
    listen:
      port: 8080
    service:
      annotations: {}
      enabled: false
      port: 8080
  nameOverride: ""
  nodeSelector: {}
  podAnnotations: {}
  podDisruptionBudget:
    enabled: false
    minAvailable: 1
  podLabels: {}
  podSecurityContext: {}
  priorityClassName: ""
  rbac:
    create: true
  readinessProbe:
    address: ""
    port: 8081
  replicaCount: 1
  requeueInterval: 40m
  resources: {}
  revisionHistoryLimit: 10
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault
  serviceAccount:
    annotations: {}
    automount: true
    create: true
    extraLabels: {}
    name: ""
  tolerations: []
  topologySpreadConstraints: []
commonLabels: {}
concurrent: 1
controllerClass: ""
crds:
  annotations: {}
  conversion:
    enabled: true
  createClusterExternalSecret: false
  createClusterSecretStore: false
  createPushSecret: true
createOperator: true
deploymentAnnotations: {}
dnsConfig: {}
extendedMetricLabels: false
extraArgs: {}
extraContainers: []
extraEnv: []
extraVolumeMounts: []
extraVolumes: []
fullnameOverride: ""
hostNetwork: false
image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/external-secrets/external-secrets
  tag: ""
imagePullSecrets: []
installCRDs: true
leaderElect: false
metrics:
  listen:
    port: 8080
  service:
    annotations: {}
    enabled: false
    port: 8080
nameOverride: ""
nodeSelector: {}
podAnnotations: {}
podDisruptionBudget:
  enabled: false
  minAvailable: 1
podLabels: {}
podSecurityContext: {}
podSpecExtra: {}
priorityClassName: ""
processClusterExternalSecret: false
processClusterStore: false
processPushSecret: true
rbac:
  create: true
  servicebindings:
    create: true
replicaCount: 1
resources: {}
revisionHistoryLimit: 10
scopedNamespace: ""
scopedRBAC: false
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
  seccompProfile:
    type: RuntimeDefault
serviceAccount:
  annotations: {}
  automount: true
  create: true
  extraLabels: {}
  name: ""
serviceMonitor:
  additionalLabels: {}
  enabled: false
  honorLabels: false
  interval: 30s
  metricRelabelings: []
  namespace: ""
  relabelings: []
  scrapeTimeout: 25s
tolerations: []
topologySpreadConstraints: []
webhook:
  affinity: {}
  certCheckInterval: 40m
  certDir: /tmp/certs
  certManager:
    addInjectorAnnotations: true
    cert:
      annotations: {}
      create: true
      duration: ""
      issuerRef:
        group: cert-manager.io
        kind: Issuer
        name: my-issuer
      renewBefore: ""
    enabled: false
  create: true
  deploymentAnnotations: {}
  extraArgs: {}
  extraEnv: []
  extraVolumeMounts: []
  extraVolumes: []
  failurePolicy: Fail
  fullnameOverride: ""
  hostNetwork: false
  image:
    pullPolicy: IfNotPresent
    repository: ghcr.io/external-secrets/external-secrets
    tag: ""
  imagePullSecrets: []
  lookaheadInterval: ""
  metrics:
    listen:
      port: 8080
    service:
      annotations: {}
      enabled: false
      port: 8080
  nameOverride: ""
  nodeSelector: {}
  podAnnotations: {}
  podDisruptionBudget:
    enabled: false
    minAvailable: 1
  podLabels: {}
  podSecurityContext: {}
  port: 10250
  priorityClassName: ""
  rbac:
    create: true
  readinessProbe:
    address: ""
    port: 8081
  replicaCount: 1
  resources: {}
  revisionHistoryLimit: 10
  secretAnnotations: {}
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault
  serviceAccount:
    annotations: {}
    automount: true
    create: true
    extraLabels: {}
    name: ""
  tolerations: []
  topologySpreadConstraints: []
```

SecretStore yaml 
```
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "https://vault.xxxx"
      path: "secret/data"
      version: "v1"
      auth:
        # VaultAppRole authenticates with Vault using the
        # App Role auth mechanism
        # https://www.vaultproject.io/docs/auth/approle
        appRole:
          # Path where the App Role authentication backend is mounted
          path: "approle"
          # RoleID configured in the App Role authentication backend
          roleId: ""
          # Reference to a key in a K8 Secret that contains the App Role SecretId
          secretRef:
            name: "vault-secret"
            key: "secret-id"
```

External secret yaml 
```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-hc
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: example-secret
  dataFrom:
   ....
```</div>

**Comment by Skarlso** [comment]
If you source the token from a secret, than it won't be revoked once the client closes.

```yaml
      auth:
        # points to a secret that contains a vault token
        # https://www.vaultproject.io/docs/auth/token
        tokenSecretRef:
          name: "vault-token"
          key: "token"
```

**Comment by Skarlso** [comment]
No idea, sorry. :)

**Comment by gusfcarvalho** [comment]
the login every five minutes is caused because of the SecretStore refreshInterval defaults.

If you configure it to any other value, you will have a proper behavior for your usecase:

```
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
spec:
  refreshInterval: "720h"
  provider:
    vault:
      server: "https://vault.xxxx"
      path: "secret/data"
      version: "v1"
      auth:
        # VaultAppRole authenticates with Vault using the
        # App Role auth mechanism
        # https://www.vaultproject.io/docs/auth/approle
        appRole:
          # Path where the App Role authentication backend is mounted
          path: "approle"
          # RoleID configured in the App Role authentication backend
          roleId: ""
          # Reference to a key in a K8 Secret that contains the App Role SecretId
          secretRef:
            name: "vault-secret"
            key: "secret-id"
  ```

Beware though that any failure of that SecretStore to validate itself with vault will make all of your ExternalSecrets to fail if they try to reconcile while the fail state persists.
