### ISSUE TITLE
Keeper backend doesn't work correctly with Custom Record Types

### ISSUE THREAD

**Issue by evilhamsterman** [external-secrets/external-secrets#4063]
**Describe the bug**
When trying to access data from a custom record the fields are not processed correctly. The fields are identified by their type rather than their label. This leads to two problems

1. If you have duplicate field types, like say multiple text fields you get the error `Following keys are duplicated <type>`
2. If you don't have duplicates your fields are all called generic types like `text` or `secret`

**To Reproduce**
1. Create a couple custom record types one with duplicate field types one without
2. Try to access them with extract and no templating so you see all the keys in the resulting secret
 ```yaml

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test-secret
  namespace: test-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: ksm-secretstore
    kind: ClusterSecretStore
  target:
    name: test-secret
    template:
      engineVersion: v2
  dataFrom:
    - extract:
        key: uid
```
The one with the duplicates will give the error above, if you don't have duplicate field types then you'll get a secret with field names like text or secret instead of useful identifiers.

**Expected behavior**
Custom records with duplicate field types don't cause a complete failure. Records regardless of the field types are accessible via the label, since labels are free form it will probably require some form of manipulation like replace spaces with _

**Comment by gusfcarvalho** [comment]
Hi @evilhamsterman ! Keeper is a community maintained provider - and as such @ppodevlabs is your best shot at getting this implemented 😄

**Comment by ppodevlabs** [comment]
> **Describe the bug** When trying to access data from a custom record the fields are not processed correctly. The fields are identified by their type rather than their label. This leads to two problems
> 
> 1. If you have duplicate field types, like say multiple text fields you get the error `Following keys are duplicated <type>`
> 2. If you don't have duplicates your fields are all called generic types like `text` or `secret`
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Create a couple custom record types one with duplicate field types one without
> 2. Try to access them with extract and no templating so you see all the keys in the resulting secret
> 
> ```yaml
> ---
> apiVersion: external-secrets.io/v1beta1
> kind: ExternalSecret
> metadata:
>  name: test-secret
>  namespace: test-secret
> spec:
>  refreshInterval: 1m
>  secretStoreRef:
>    name: ksm-secretstore
>    kind: ClusterSecretStore
>  target:
>    name: test-secret
>  dataFrom:
>    - extract:
>        key: uid
> ```
> 
> The one with the duplicates will give the error above, if you don't have duplicate field types then you'll get a secret with field names like text or secret instead of useful identifiers.
> 
> **Expected behavior** Custom records with duplicate field types don't cause a complete failure. Records regardless of the field types are accessible via the label, since labels are free form it will probably require some form of manipulation like replace spaces with _

Hi, duplicated types should be allowed, what can not be duplicated is the label on the field. Could you please confirm you do not have duplicated labels?? As those are used as keys as stated in 
```
remoteRef.property is equated to one of the following options:
- Fields: [Record's field's Type](https://docs.keeper.io/secrets-manager/secrets-manager/about/field-record-types)
- CustomFields: Record's field's Label
- Files: Record's file's Name
If empty, defaults to the complete Record in JSON format
```

**Comment by evilhamsterman** [comment]
Yes I do not have duplicate labels

I created a Custom Record type called "Duplicate type exampled" and a record of that type. Here's the sanitized json of the record object as returned by the Keeper API

```json
{
  "record_uid": "recordid",
  "title": "Test record",
  "type": "Duplicate type example",
  "fields": [
    {
      "type": "text",
      "label": "Field 1",
      "value": [
        "foo"
      ]
    },
    {
      "type": "text",
      "label": "Field 2",
      "value": [
        "bar"
      ]
    }
  ],
  "custom": [],
  "version": 3,
  "shared": true,
  "client_modified_time": "2024-11-22T14:57:27",
  "user_permissions": [
    {
      "username": "myuser",
      "owner": true,
      "share_admin": true,
      "shareable": true,
      "editable": true
    }
  ],
  "shared_folder_permissions": [
    {
      "shared_folder_uid": "uuid",
      "reshareable": true,
      "editable": true,
      "revision": 12
    }
  ],
  "share_admins": [
    ""
  ],
  "revision": 12
}

```

When I create an ExternalSecret for that record  like this

```yaml
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
 name: test-secret
spec:
 refreshInterval: 1m
 secretStoreRef:
   name: ksm-secretstore
   kind: ClusterSecretStore
 target:
   name: test-secret
 dataFrom:
   - extract:
       key: recordid
```

it fails to sync the secret with the event `invalid Secret. Following keys are duplicated text` When it says text it means the duplicate text type field, the labels are different but the type is the same. This is shown by if I create another custom type with the fields 

```json
"fields": [
    {
      "type": "date",
      "label": "Date Active",
      "value": [
        1732316915948
      ]
    },
    {
      "type": "date",
      "label": "Date of Birth",
      "value": [
        1731971318326
      ]
    }
  ]
```

I get a similar error `invalid Secret. Following keys are duplicated date `

You properly support Custom FIELDS in a record but this is regarding Custom RECORD Types. As far as I can tell none of the builtin in record types have fields with duplicate types, but with custom records it is entirely possible to have more than one of the same type of field with the labels differentiating them.
