### ISSUE TITLE
ThrottlingException: Rate exceeded errors

### ISSUE THREAD

**Issue by josemrs** [external-secrets/external-secrets#4065]
**Describe the bug**

After setting an ExternalSecret using wildcards (/develop/istio/*/*) I started to see ThrottlingException: Rate exceeded errors. They do not follow a pattern in time, sometimes every 40s sometimes nothing for 10min.

When we have a Parameter created (eg. /develop/istio/us-east-1/name_of_the_parameter) the K8S secret is created fine (perhaps it takes longer than usual) while the errors keep showing up.

Setting RetryInterval in the CSS does not seem to fix it.

It does not matter we have SSM Parameters created or not.

```{"level":"error","ts":1730390363.3979635,"logger":"controllers.ExternalSecret","msg":"could not get secret data from provider","ExternalSecret":"istio-system/istio-clusters-monitor","error":"ThrottlingException: Rate exceeded\n\tstatus code: 400, request id: fe1373f4-1bcc-4f19-8a11-ae2f12be1917","stacktrace":"github.com/external-secrets/external-secrets/pkg/controllers/externalsecret.(*Reconciler).Reconcile\n\t/home/runner/work/external-secrets/external-secrets/pkg/controllers/externalsecret/externalsecret_controller.go:190\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:122\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:323\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:235"}```

**To Reproduce**
ClusterSecretStore

```
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/tracking-id: develop_adm.us-east-1.develop-external-secrets-operator:external-secrets.io/ClusterSecretStore:external-secrets/aws-ssm-paramstore
  name: aws-ssm-paramstore
spec:
  provider:
    aws:
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
      region: us-east-1
      service: ParameterStore
  retrySettings:
    retryInterval: 60s
status:
  capabilities: ReadWrite
  conditions:
  - lastTransitionTime: "2024-04-10T06:00:02Z"
    message: store validated
    reason: Valid
    status: "True"
    type: Ready
```

The ExternalSecret is:
```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
    argocd.argoproj.io/tracking-id: adm.us-east-1.develop-istio:external-secrets.io/ExternalSecret:istio-system/istio-clusters-monitor
  name: istio-clusters-monitor
  namespace: istio-system
spec:
  dataFrom:
  - find:
      conversionStrategy: Default
      decodingStrategy: None
      name:
        regexp: /develop/istio/*/*
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm-paramstore
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: istio-cluster-tokens
status:
  conditions:
  - lastTransitionTime: "2024-10-31T14:51:05Z"
    message: could not get secret data from provider
    reason: SecretSyncedError
    status: "False"
    type: Ready
  refreshTime: "2024-10-31T14:31:45Z"
  syncedResourceVersion: 1-473731255a18ae26092c1c70b35945e6
```

**Expected behavior**
The secret is created with the parameters or empty
No Throttling errors

**Additional context**
Kubernetes 1.31 
Running on AWS EKS
ESO v0.7.2

**Comment by Skarlso** [comment]
Hello.

Please upgrade your ESO version and try again.

Thanks!

**Comment by josemrs** [comment]
Using 10.5 now. The error persist. It looks like there is an issue when querying SSM Params with wildcards.

```Events:
  Type     Reason        Age    From              Message
  ----     ------        ----   ----              -------
  Warning  UpdateFailed  7m18s  external-secrets  ThrottlingException: Rate exceeded
           status code: 400, request id: 5e033b12-2106-4a45-9cfa-f40fd3c1ae67
  Warning  UpdateFailed  7m7s  external-secrets  ThrottlingException: Rate exceeded
           status code: 400, request id: e1e20a15-dff6-450d-b022-32a4dba3ee6a
  Warning  UpdateFailed  6m50s  external-secrets  ThrottlingException: Rate exceeded
           status code: 400, request id: f4822cac-c087-4e16-b841-d2d03bdd8a6c
  Warning  ParameterDeprecated  6m1s  external-secrets  dataFrom[0].find.conversionStrategy=Default is deprecated and will be removed in further releases. Use dataFrom.rewrite instead
  Normal   Created              6m1s  external-secrets  Created Secret
  Warning  UpdateFailed         4s    external-secrets  ThrottlingException: Rate exceeded
           status code: 400, request id: d9102921-b4ae-4073-8409-4a5370d47d1c
`
``

The "Created Secret" appeared a few seconds after an SSM Parameter was created where ESO is monitoring.

The K8S secret is then deleted manually and this happens:
```
  Warning  UpdateFailed         2m7s  external-secrets  ThrottlingException: Rate exceeded
           status code: 400, request id: d9102921-b4ae-4073-8409-4a5370d47d1c
  Warning  UpdateFailed  113s  external-secrets  ThrottlingException: Rate exceeded
           status code: 400, request id: 3760c3b4-0a36-4cef-88c4-5b527147a6f7
  Warning  UpdateFailed  107s  external-secrets  ThrottlingException: Rate exceeded
           status code: 400, request id: 108ec275-c916-43a4-b7c4-71836d10ab08
  Warning  UpdateFailed  94s  external-secrets  ThrottlingException: Rate exceeded
           status code: 400, request id: b7e394fa-1c68-4132-b568-b50e62f980b5
  Warning  UpdateFailed  85s  external-secrets  ThrottlingException: Rate exceeded
           status code: 400, request id: 0d334c01-7923-417d-9de2-fb3e01469d64
  Warning  UpdateFailed  78s  external-secrets  ThrottlingException: Rate exceeded
           status code: 400, request id: 0aaacbce-3bf7-468b-923c-8b918ae5f2f2
  Warning  UpdateFailed  41s (x2 over 50s)  external-secrets  (combined from similar events): ThrottlingException: Rate exceeded
           status code: 400, request id: 431aa454-eef1-4e23-8c20-d5372b68a2ed
```

It does not recreate the secret until after a few minutes.

**Comment by Skarlso** [comment]
Huh, it's trying to do an update on the remote? 🤔 

why 🤔 * 💯

**Comment by josemrs** [comment]
Exactly, I thought I read about caches in place. Right when the secret is deleted It goes back to AWS, and it hits the limit again

**Comment by josemrs** [comment]
Hey, any update on this? did you managed to reproduce it? it's kind of giving me headaches

**Comment by Skarlso** [comment]
Hey, I haven't had the time yet, sorry. It's at the top of my todo list for none-work hours. :)

**Comment by Skarlso** [comment]
Ok, so we can ignore that it's an update failure. I just noticed that all events are using UpdateFailed reason.. 🤦 

```go
	r.recorder.Event(externalSecret, v1.EventTypeWarning, esv1beta1.ReasonUpdateFailed, err.Error())
```

So that won't help us. :D

**Comment by Skarlso** [comment]
@josemrs can you please share the new controller error log using 0.10.5?

**Comment by josemrs** [comment]
mmmh, odd. The policy is fine, policysim is happy and I resfresehd the pod but it's still complaining about 

This is what happens when I delete the secret:

```external-secrets-c444bcf99-xwcxv external-secrets {"level":"info","ts":1730927012.778331,"logger":"provider.aws","msg":"using aws session","region":"us-east-1","external id":"","credentials":{}}
external-secrets-c444bcf99-xwcxv external-secrets {"level":"info","ts":1730927016.097568,"logger":"provider.parameterstore","msg":"GetParametersByPath: access denied. using fallback to describe parameters. It is recommended to add ssm:GetParametersByPath permissions","path":"/"}
external-secrets-c444bcf99-xwcxv external-secrets {"level":"error","ts":1730927022.1335683,"logger":"controllers.ExternalSecret","msg":"could not get secret data from provider","ExternalSecret":{"name":"istio-clusters-monitor","namespace":"istio-system"},"error":"ThrottlingException: Rate exceeded\n\tstatus code: 400, request id: 665b6aca-8705-4358-9487-4e1497a3a07e","stacktrace":"github.com/external-secrets/external-secrets/pkg/controllers/externalsecret.(*Reconciler).markAsFailed\n\tgithub.com/external-secrets/external-secrets/pkg/controllers/externalsecret/externalsecret_controller.go:360\ngithub.com/external-secrets/external-secrets/pkg/controllers/externalsecret.(*Reconciler).Reconcile\n\tgithub.com/external-secrets/external-secrets/pkg/controllers/externalsecret/externalsecret_controller.go:229\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile\n\tsigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:116\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\tsigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:303\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\tsigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:224"}
external-secrets-c444bcf99-xwcxv external-secrets {"level":"error","ts":1730927022.1458817,"msg":"Reconciler error","controller":"externalsecret","controllerGroup":"external-secrets.io","controllerKind":"ExternalSecret","ExternalSecret":{"name":"istio-clusters-monitor","namespace":"istio-system"},"namespace":"istio-system","name":"istio-clusters-monitor","reconcileID":"0b8300cb-bbef-4085-924c-1a9dd0cae49e","error":"ThrottlingException: Rate exceeded\n\tstatus code: 400, request id: 665b6aca-8705-4358-9487-4e1497a3a07e","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\tsigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\tsigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:224"}
external-secrets-c444bcf99-xwcxv external-secrets {"level":"info","ts":1730927022.1545177,"logger":"provider.aws","msg":"using aws session","region":"us-east-1","external id":"","credentials":{}}
external-secrets-c444bcf99-xwcxv external-secrets {"level":"info","ts":1730927025.321876,"logger":"provider.parameterstore","msg":"GetParametersByPath: access denied. using fallback to describe parameters. It is recommended to add ssm:GetParametersByPath permissions","path":"/"}
external-secrets-c444bcf99-xwcxv external-secrets {"level":"error","ts":1730927030.660042,"logger":"controllers.ExternalSecret","msg":"could not get secret data from provider","ExternalSecret":{"name":"istio-clusters-monitor","namespace":"istio-system"},"error":"ThrottlingException: Rate exceeded\n\tstatus code: 400, request id: 68dd84f8-afe2-41df-8ee6-03c6222963af","stacktrace":"github.com/external-secrets/external-secrets/pkg/controllers/externalsecret.(*Reconciler).markAsFailed\n\tgithub.com/external-secrets/external-secrets/pkg/controllers/externalsecret/externalsecret_controller.go:360\ngithub.com/external-secrets/external-secrets/pkg/controllers/externalsecret.(*Reconciler).Reconcile\n\tgithub.com/external-secrets/external-secrets/pkg/controllers/externalsecret/externalsecret_controller.go:229\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile\n\tsigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:116\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\tsigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:303\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\tsigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:224"}
external-secrets-c444bcf99-xwcxv external-secrets {"level":"error","ts":1730927030.6686502,"msg":"Reconciler error","controller":"externalsecret","controllerGroup":"external-secrets.io","controllerKind":"ExternalSecret","ExternalSecret":{"name":"istio-clusters-monitor","namespace":"istio-system"},"namespace":"istio-system","name":"istio-clusters-monitor","reconcileID":"491b1ec2-dbc1-4771-904e-1e41e2078a08","error":"ThrottlingException: Rate exceeded\n\tstatus code: 400, request id: 68dd84f8-afe2-41df-8ee6-03c6222963af","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\tsigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\tsigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:224"}
```

The policy:

```{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "secretsmanager:GetResourcePolicy",
                "secretsmanager:GetSecretValue",
                "secretsmanager:DescribeSecret",
                "secretsmanager:ListSecretVersionIds"
            ],
            "Resource": "arn:aws:secretsmanager:*:*:secret:*"
        },
        {
            "Sid": "VisualEditor1",
            "Effect": "Allow",
            "Action": [
                "ssm:PutParameter",
                "ssm:GetParameter*",
                "ssm:DescribeParameters",
                "ssm:AddTagsToResource",
                "ssm:ListTagsForResource"
            ],
            "Resource": "*"
        }
    ]
}
```

Policysim happy:

![image](https://github.com/user-attachments/assets/4611967f-fd1e-41b0-936a-f5db6fbe1ab1)

I'll try again tomorrow, perhaps it's something silly I'm missing, it's a bit late.

**Comment by josemrs** [comment]
It recreates the secret, eventually. 

```
external-secrets-c444bcf99-xwcxv external-secrets {"level":"info","ts":1730927191.69569,"logger":"provider.aws","msg":"using aws session","region":"us-east-1","external id":"","credentials":{}}
external-secrets-c444bcf99-xwcxv external-secrets {"level":"info","ts":1730927195.1384318,"logger":"provider.parameterstore","msg":"GetParametersByPath: access denied. using fallback to describe parameters. It is recommended to add ssm:GetParametersByPath permissions","path":"/"}
external-secrets-c444bcf99-xwcxv external-secrets {"level":"info","ts":1730927231.9111748,"logger":"provider.aws","msg":"using aws session","region":"us-east-1","external id":"","credentials":{}}
external-secrets-c444bcf99-xwcxv external-secrets {"level":"info","ts":1730927231.9496877,"logger":"provider.aws","msg":"using aws session","region":"us-east-1","external id":"","credentials":{}}
external-secrets-c444bcf99-xwcxv external-secrets {"level":"info","ts":1730927237.7762713,"logger":"controllers.ExternalSecret","msg":"reconciled secret","ExternalSecret":{"name":"istio-clusters-monitor","namespace":"istio-system
```

It's hitting AWS hard, it even shows the Rate Exceeded when accessing AWS console.

**Comment by Skarlso** [comment]
So, I think you are falling into this section with your permission issue:

https://github.com/external-secrets/external-secrets/blob/main/pkg/provider/aws/parameterstore/parameterstore.go#L310

And this code block:
https://github.com/external-secrets/external-secrets/blob/main/pkg/provider/aws/parameterstore/parameterstore.go#L360

will call 

```go
	out, err := pm.client.GetParameterWithContext(ctx, &ssm.GetParameterInput{
		Name:           utilpointer.To(name),
		WithDecryption: aws.Bool(true),
	})
```

For each parameter. This is super aggressive. :D

**Comment by Skarlso** [comment]
GetParametersByPath is the thing that needs to be called, otherwise it will try by name which is just a describe and then it will Get all parameters one by one in order to get the data. GetParametersByPath is waaaay more efficient in this regard.

So I suggest you fix the permission issue somehow...

**Comment by Skarlso** [comment]
This is the issue from the code https://github.com/external-secrets/external-secrets/issues/1839#issuecomment-1489023522

**Comment by Skarlso** [comment]
Ugh and now i see I can't just change the function. I wanted to improve it to use `*Pages` function, but it seems the policies and permissions are per function name. So I would break a LOT of installations. I guess it could still be done if I release it as a minor version update. Though I doubt it would help. Since that STILL would need ot Describe then Get all parameters to retrieve the values if it can't use GetParameter.

**Comment by josemrs** [comment]
Sure, I'll figure out what is going on with the permissions. It's not like there are 100 parameters, right now there is only one matching the pattern. Anyway, I'll let you know.

thanks

**Comment by josemrs** [comment]
Something I noticed. There are mentions to GetParametersByPathWithContext and DescribeParametersWithContext. Policy editor complains those are not valid permissions, I mean, there is no permissions *WithContext anywhere.

**Comment by Skarlso** [comment]
Yah weird. :D

Ok. I need to go to bed, I'll try and continue with this tomorrow. :)

It's weird that one parameter causes a Throttling issue. Unless the token is never nil somehow and the for loop just keeps on going. 

If you can, try building a docker image for this PR? https://github.com/external-secrets/external-secrets/pull/4081

And then try to use it. Also I think something builds a dev image for it, but I don't remember where to check and I'm super tired now.

**Comment by josemrs** [comment]
OK, good news. It's working now. It was a combination of missing permissions and missing path in the YAML.

The policy looks like this: 
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "GetParameters",
            "Effect": "Allow",
            "Action": "ssm:GetParameter*",
            "Resource": "*"
        },
        {
            "Sid": "PutParameter",
            "Effect": "Allow",
            "Action": [
                "ssm:PutParameter*"
            ],
            "Resource": "arn:aws:ssm:*:*:parameter/*"
        },
        {
            "Sid": "FindByTags",
            "Effect": "Allow",
            "Action": [
                "ssm:DescribeParameters",
                "ssm:AddTagsToResource",
                "ssm:ListTagsForResource"
            ],
            "Resource": "*"
        }
    ]
}
```

And the ExternalSecret spec is like this:

```
spec:
  dataFrom:
  - find:
      conversionStrategy: Default
      decodingStrategy: None
      name:
        regexp: .*/.*
      path: /develop/admin/istio/tokens/
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm-paramstore
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: istio-cluster-tokens
```

The bit I missed was `spec.dataFrom[].find.path`.

With these two changes it's working. No more throttling, the secret is created instantly.

I need to check now what is adding `conversionStrategy: Default`, I keep removing it and something adds it and it's deprecated:
```
dataFrom[0].find.conversionStrategy=Default is deprecated an will be removed in further releases. Use dataFrom.rewrite instead
```

Don't worry, problem for another time. This is solved. Thanks a lot for your help.
