### ISSUE TITLE
Order of the keys inside the provider config shouldn't matter

### ISSUE THREAD

**Issue by rahtr** [external-secrets/external-secrets#4082]
**Describe the bug**
It seems ESO looks for a strict ordering of the keys inside the vault provider. For example if the auth is added as the first object then you get this error:

```
`error":"could not get provider client: unable to log in to auth method: unable to log in with AWS auth: Error making API request

`
```

**To Reproduce**
1. This works:

```
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend-aws-1
  namespace: test
spec:
  provider:
    vault:
      path: test
      server: 'https://vault.test.net'
      version: v2    
      auth:
        iam:
          jwt:
            serviceAccountRef:
              name: vault-sa
          path: aws
          region: us-east-1
          vaultRole: vault_access

```

This throws an error:

```
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend-aws
  namespace: test
spec:
  provider:
    vault:
      auth:
        iam:
          jwt:
            serviceAccountRef:
              name: vault-sa
          path: aws
          region: us-east-1
          vaultRole: vault_access
      path: test
      server: 'https://vault.test.net'
      version: v2
```

2. provide the Kubernetes and ESO version
```
Client Version: v1.31.2
Kustomize Version: v5.4.2
Server Version: v1.29.8-eks-a737599
ESO: v0.9.20
```

**Expected behavior**
Order of the keys inside the vault object shouldn't matter. 

**Screenshots**

**Additional context**
