### ISSUE TITLE
ESO points to outdated/initial version of certificate in Azure Key Vault

### ISSUE THREAD

**Issue by is-consulting** [external-secrets/external-secrets#4084]
**Describe the bug**
I am using External Secrets Operator to synchronise certificates from an Azure Key Vault. When I create a new version of the certificate in Azure Key Vault, ESO continues to use the initial version and never targets the new version unless the version key is explicitly specified in the ExternalSecret manifest. I'd expect ESO to always target the latest version on refresh. 

This will continue to happen even after the manifests and resources have been completely removed.

**To Reproduce**

- Create or upload a certificate to Azure KeyVault
- Create a ClusterSecretStore and ExternalSecret as shown in the manifests below
- Create a new version of the aforementioned certificate in Azure Key Vault
- Verify that ESO still points to the old version on refresh

1. provide all relevant manifests
ClusterSecretStore
```
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-key-vault-at-devops
spec:
  provider:
    azurekv:
      authType: ManagedIdentity
      identityId: "***"
      vaultUrl: "***"
```

ExternalSecret
```
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tls-mde-api
spec:
  secretStoreRef:
    name: azure-key-vault-at-devops
    kind: ClusterSecretStore
  refreshInterval: 1h
  target:
    name: tls-mde-api
    template:
      type: kubernetes.io/tls
      engineVersion: v2
      data:
        tls.key: "{{ `{{ .certificate | b64dec | pkcs12key }}` }}"
        tls.crt: "{{ `{{ .certificate | b64dec | pkcs12cert }}` }}"
  data:
  - secretKey: certificate
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
      key: <name-of-cert-in-keyvault>
```

2. provide the Kubernetes and ESO version

external-secrets version: 0.9.18
kubernetes version: 1.29.8

**Expected behavior**
I'd expect eso to always target the latest version on refresh.

**Screenshots**
![image](https://github.com/user-attachments/assets/2a5774fe-bda8-4c5a-b7d0-4fef9a0207ec)
The screenshot shows the certificate in Azure KeyVault with more than one version. ESO always targets the outdated version.

**Additional context**
Explicitly specifying the version key in the manifest is not really an elegant option, as it requires manual labour.
