### ISSUE TITLE
[Feat] Add support to push whole secrets to bitwarden

### ISSUE THREAD

**Issue by justSem** [external-secrets/external-secrets#4087]
**Is your feature request related to a problem? Please describe.**
I tried to push a whole secret to bitwarden. It simply resulted in a message saying the feature is not yet implemented.

`Warning  Errored  7m48s (x53 over 12h)  pushsecret  set secret failed: could not write remote ref  to target secretstore bitwarden-secrets: pushing the whole secret is not yet implemented`

**Describe the solution you'd like**
What I would expect is a secret to be pushed to bitwarden as a whole. Preferrably as JSON, but YAML should work just as well.

**Describe alternatives you've considered**
I could push it all as different secrets, but that's pretty tedious. I'd say that pushing a secret as a whole just works better.

**Additional context**
An example of a pushsecret that errors:
```yaml
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: push-to-bitwarden
  namespace: app
spec:
  deletionPolicy: None 
  refreshInterval: 10s 
  secretStoreRefs:
    - name: bitwarden-secrets
      kind: ClusterSecretStore
  selector:
    secret:
      name: app-pg
  template:
    engineVersion: v2
    data:
      pg_user: "{{ .user }}"
      pg_password: "{{ .password }}"
      pg_host: "{{ .host }}"
      pg_dbname: "{{ .dbname }}"
  data:
    - match:
        remoteRef:
          remoteKey: app
```
