### ISSUE TITLE
Allow passing of Cert to Vault Provider from K8s ConfigMaps or Secrets

### ISSUE THREAD

**Issue by ADustyOldMuffin** [external-secrets/external-secrets#410]
**Describe the solution you'd like**
When describing a `SecretStore` and using the Provider `Vault` you can specify a `caBundle`. This is not super useful as you have to provide a base64 encoded string inline. Allowing users to provide a ConfigMap or Secret containing the Cert would be better.

**What is the added value?**
Allows users to define certs in a single place, and allow them another option than just specifying the cert inline.

**Give us examples of the outcome**

```yaml
vault:
  [...]
  caProvider:
    type: ConfigMap
    name: cert-name-ca.crt
```
The code behind this would then go and grab the data of this ConfigMap and use it as the cert.

```yaml
vault:
  [...]
  caProvider:
    type: Secret
    name: cert-secret
    key: cert-data
```
The code behind this would grab a Secret with the specified name, and the key `cert-data` and use it as the cert.

**Observations (Constraints, Context, etc):**

Context is that the lack of documentation around the `caBundle` for the Vault Provider makes the usage of it difficult. Once figured out how to use it, we'd like to automate the process and it would be easier if we could specify an existing cert in our clusters.
