### ISSUE TITLE
Kubeconfig Generators

### ISSUE THREAD

**Issue by moshloop** [external-secrets/external-secrets#4105]
Some projects like Flux and Argo can use a kubeconfig file to connect to remote clusters. However, they don't always fully support cloud providers (see [Flux discussion](https://github.com/fluxcd/flux2/discussions/4548)).

It would be useful to have a generator that:
1. Uses cloud provider credentials / workload identity (AWS STS, GCP tokens etc)
2. Takes a cluster name (or discovers all clusters)
3. Generates corresponding secrets containing normalized kubeconfig files that:
   - Do not rely on kubectl exec plugins
   - Use short-lived tokens for authentication
   - Work consistently across different cloud providers
  
```
apiVersion: generators.external-secrets.io/v1alpha1
kind: EKSKubeconfig
metadata:
  name: gen-gen
spec:
  cluster: eks-cluster-1
  region: eu-west-1
  auth:
      serviceAccountRef:
        name: "irsa-sa"
```
