### ISSUE TITLE
Secret store is unable to resolve an endpoint for oidc when using workload identity in azure: status code 404 with 0.10.6

### ISSUE THREAD

**Issue by papanito** [external-secrets/external-secrets#4139]
**Describe the bug**
We are using workload identity in azure for the secret store to authenticate against the keyvault. With the latest update, this does not work anymore and we get

```
unable to resolve an endpoint: http call(https://login.microsoftonline.com/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/oauth2/token/v2.0/.well-known/openid-configuration?)(GET) error: reply status code was 404
```

**To Reproduce**
1. provide all relevant manifests

  ```yaml
  apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      azure.workload.identity/client-id: aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa
    labels:
      azure.workload.identity/use: "true"
    name: sa-ess
    namespace: myns
  ---
  apiVersion: external-secrets.io/v1beta1
  kind: SecretStore
  metadata:
    name: secret-store-kv
    namespace:  myns
  spec:
    provider:
      azurekv:
        tenantId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
        authType: WorkloadIdentity
        vaultUrl: "https://xxxx.vault.azure.net/"
        serviceAccountRef:
          name: sa-ess
  ```

2. provide the Kubernetes and ESO version
   
   Kubernetes 1.30.0

**Expected behavior**
No errors

**Screenshots**
N/A

**Additional context**

We upgraded from 0.10.5 to 0.10.6.
- helm chart 0.10.5 is working fine
- helm chart 0.10.6 breaks
