### ISSUE TITLE
Using extractFrom filter keys by some prefix and strip the prefix

### ISSUE THREAD

**Issue by Jonnymcc** [external-secrets/external-secrets#4151]
**Is your feature request related to a problem? Please describe.**
We have a custom tool that pulls in secrets from one source and can filter secrets by prefix and then strip the prefixes. 

**Describe the solution you'd like**
```
dataFrom:
  - extract:
      key:  something
      prefix: APP1_
      stripPrefix: true
```

converts 
```
APP1_USER
APP1_PASS
APP2_USER
APP2_PASS
```

into
```
USER
PASS
```

**Describe alternatives you've considered**
I have been able to achieve this using templateFrom and sprig functions, but the problem is I want to use the transformed keys in templates. Later templates that target Data only seem to have access to the original keys and not the ones with the prefix removed.

**Additional context**
