### ISSUE TITLE
ExternalSecret Cuts Off Parameters When Using AWS SSM Parameter Store

### ISSUE THREAD

**Issue by DanielOved93** [external-secrets/external-secrets#4155]
**Description**
I am using external-secrets version 0.10.0 with a single ExternalSecret resource configured to retrieve approximately 500 parameters from AWS SSM Parameter Store. Suddenly, the ExternalSecret was truncated, and only the first 350 parameters were retrieved. This behavior started recently and was not observed previously.

I have the required IAM permissions, and the environment was functioning as expected before this issue arose.

**Steps Taken**

1. Create an ExternalSecret resource with ~500 parameters from AWS SSM Parameter Store.
2. Observe that only 350 parameters are retrieved in the generated secret.
3. Redeploy the Helm chart managing the ExternalSecret.
4. Update the ExternalSecret manually and redeploy the Helm chart again.
5. Observe that the issue persists.
6. Fix the issue by manually deleting the ExternalSecret and redeploying the Helm chart.

**Expected Behavior**
The ExternalSecret should retrieve all ~500 parameters without truncation.

**Observed Behavior**
The ExternalSecret retrieves only the first 350 parameters, leaving the rest missing.

**Environment Details**

- ExternalSecrets version: 0.10.0
- Kubernetes version: EKS 1.31
- Cloud Provider: AWS

**Additional Notes**

- No errors were observed in the logs of the external-secrets controller.
- Redeploying the Helm chart did not resolve the issue.
- Manually deleting the ExternalSecret and redeploying the Helm chart fixed the issue temporarily.
- This issue occurred suddenly, and I cannot identify a specific trigger or consistent reproduction steps.

**Comment by DanielOved93** [comment]
Hi,

I executed the following command to check the size of the Secret:
```bash
kubectl get secret my-secret -n my-namespace -o json | jq -r '.data | to_entries[] | .value | @base64d' | wc -c
```
The output of the command was `15756`, indicating that the total size of the decoded secret data is `15,756 bytes`, which equals approximately `15.4 KB`. This is well within the Kubernetes limit of 1 MB per secret.

Regarding the ExternalSecret manifests, I am using Helm templates to define them. Here is the relevant template:
```yaml
{{- range .Values.externalSecrets }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .name }}
spec:
  refreshInterval: {{ .refreshInterval }}
  secretStoreRef:
    name: {{ .secretStoreRef.name }}
    kind: ClusterSecretStore
  target:
    name: {{ .name }}
  data:
    {{- range .data }}
    - secretKey: {{ .key }}
      remoteRef:
        key: {{ .name }}
    {{- end }}
---
{{- end }}
```

The `values.yaml` file looks like this:
```yaml
externalSecrets:
  - name: my-external-secret
    refreshInterval: 5m
    secretStoreRef:
      name: aws-ssm-parameters
    targetSecretName: my-secret
    data:
      - key: PARAMETER1
        name: /pl1/stage/PARAMETER1
      - key: PARAMETER2
        name: /pl1/stage/PARAMETER2
      # Additional ~500 parameters...
```

Let me know if you need further details, thank you!
