### ISSUE TITLE
Upgrading to 0.10.x results in "could not get secret data from provider" when using the webhook provider

### ISSUE THREAD

**Issue by Farioko** [external-secrets/external-secrets#4158]
**Describe the bug**
After upgrading to 0.10.7 from 0.9.11, we are having issues syncing secrets using the webhook provider. We are aware of the breaking change that was introduced in 0.10.0.

**To Reproduce**

1. Create the resulting secret with the webhook label.

`oc create secret generic my-secrets`
`oc label secret/my-secrets external-secrets.io/type=webhook`

2. Create the `SecretStore`:

```yaml
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: serviceaccounts
  namespace: my-namespace
spec:
  provider:
    webhook:
      caProvider:
        key: ca-bundle.crt
        name: local-ca
        type: ConfigMap
      headers:
        AUTHTOKEN: '{{ .auth.token }}'
      result:
        jsonPath: $.operation.Details.PASSWORD
      secrets:
        - name: auth
          secretRef:
            key: token
            name: token
      url: 'https://vault.localdomain/restapi/json/v1/resources/10200/accounts/{{ .remoteRef.key }}/password'
```

3. Create the `ExternalSecret`:

```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: my-secrets
  namespace: my-namespace
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: '44754'
        metadataPolicy: None
      secretKey: MSSQL_PASSWORD
  refreshInterval: 15s
  secretStoreRef:
    kind: SecretStore
    name: serviceaccounts
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: my-secrets
```

4. Check the logs from the controller complaining about the webhook label:

```
{"level":"error","ts":1732779612.0838761,"logger":"controllers.ExternalSecret","msg":"could not get secret data from provider","ExternalSecret":{"name":"my-secrets","namespace":"my-namespace"},"error":"error retrieving secret at .data[0], key: 44754, err: secret does not contain needed label 'external-secrets.io/type: webhook'. Update secret label to use it with webhook","stacktrace":"github.com/external-secrets/external-secrets/pkg/controllers/externalsecret.(*Reconciler).markAsFailed\n\t/home/runner/work/external-secrets/external-secrets/pkg/controllers/externalsecret/externalsecret_controller.go:360\ngithub.com/external-secrets/external-secrets/pkg/controllers/externalsecret.(*Reconciler).Reconcile\n\t/home/runner/work/external-secrets/external-secrets/pkg/controllers/externalsecret/externalsecret_controller.go:229\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.1/pkg/internal/controller/controlle...
```

5. Verify that the label is set on the resulting `Secret`:

```yaml
apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: "2024-11-28T07:36:06Z"
  labels:
    external-secrets.io/type: webhook
  name: my-secrets
  namespace: my-namespace
  resourceVersion: "1127478238"
  uid: 5aa27ed6-0eeb-4238-8356-2bff4b3abd9b
type: Opaque
```

**Expected behavior**
I expected `my-secrets` to be updated with the value from our password vault.

**Additional context**
Installed using the Helm chart on OpenShift 4.14.

**Comment by Skarlso** [comment]
Well... that's weird. 🤔

**Comment by Skarlso** [comment]
ah, I think you labeled the wrong secret?

```yaml
        - name: auth
          secretRef:
            key: token
            name: token
```

Does this one have the label?
