### ISSUE TITLE
Retrieve username field from BeyondTrust Password Safe secret

### ISSUE THREAD

**Issue by sarah-soo** [external-secrets/external-secrets#4171]
It would be great if we could retrieve the username alongside the password for a secret in BeyondTrust Password Safe.

This could be done by adding an optional `property` or `field` key/value pair in the ExternalSecret `spec.data` object, for example in the Delinea ESO - https://external-secrets.io/latest/provider/delinea/#referencing-secrets.
```
...
    data:
      - secretKey: <KEY_IN_KUBE_SECRET>
        remoteRef:
          key: <SECRET_PATH>
          property: <JSON_PROPERTY>
```

My current solution is to hardcode the username into the Kubernetes secret object, which is functional but not ideal.
