### ISSUE TITLE
Template Engine Version v1 does not support labels containing a `/`

### ISSUE THREAD

**Issue by joggeli34** [external-secrets/external-secrets#4172]
**Describe the bug**

When trying to add a label containing a `/` we get following error since v0.11.0. It works with older versions.

```json
{
  "level": "error",
  "ts": 1733237303.9388177,
  "msg": "Reconciler error",
  "controller": "externalsecret",
  "controllerGroup": "external-secrets.io",
  "controllerKind": "ExternalSecret",
  "ExternalSecret": {
    "name": "k8s-prod-cluster",
    "namespace": "argocd"
  },
  "namespace": "argocd",
  "name": "k8s-prod-cluster",
  "reconcileID": "5740ff88-2d61-4cdf-b04e-6a005105bdd0",
  "error": "unable to update secret k8s-prod-cluster: Secret \"k8s-prod-cluster\" is invalid: data[argocd.argoproj.io/secret-type]: Invalid value: \"argocd.argoproj.io/secret-type\": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+')",
  "stacktrace": "sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.2/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.2/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.2/pkg/internal/controller/controller.go:224"
}
```

The external secret manifest we like to apply:

```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  labels:
    app.kubernetes.io/instance: argocd
  name: k8s-dev-cluster
  namespace: argocd
spec:
  data:
    - remoteRef:
        key: dev-cluster-config
      secretKey: config
    - remoteRef:
        key: dev-cluster-name
      secretKey: name
    - remoteRef:
        key: dev-cluster-server
      secretKey: server
  refreshInterval: 24h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: keyvault-cluster-secret-store
  target:
    name: k8s-dev-cluster
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: cluster
```

**To Reproduce**

See Manifest above

**Expected behavior**
The external secret creates a secret containing the label with `/`

**Additional context**
Happened already once before:
https://github.com/external-secrets/external-secrets/issues/1910
