### ISSUE TITLE
the option "crds.createClusterGenerator" does not work in the helm chart

### ISSUE THREAD

**Issue by deshifcodes** [external-secrets/external-secrets#4179]
When installing "external-secrets", I set the following parameters in the helm chart:

```
installCRDs: true
crds:
  createClusterExternalSecret: true
  createClusterSecretStore: true
  createClusterGenerator: false
  createPushSecret: false
```

The "createClusterGenerator" parameter has the value "**false**", however, "CRDs Generators" are still created

**Comment by Skarlso** [comment]
Thank you for reporting it! I'll take a look.

**Comment by Skarlso** [comment]
Hm, it's definitely being used.

```yaml
{{- if and (.Values.installCRDs) (.Values.crds.createClusterGenerator) }}

```

**Comment by Skarlso** [comment]
Thanks @gusfcarvalho ! I was going to test that later today. :D But now I don't have to! :D :D :D

**Comment by deshifcodes** [comment]
> I just did ` helm template external-secrets external-secrets/external-secrets --set installCRDs=true --set crds.createClusterGenerator=false | grep ClusterGenerator -A20 -B20` and I can`t see any mention to Cluster Generator CRDs in it @deshifcodes . The only references are for generatorRefs, which is expected.
> 
> Can you share more how are you installing ESO? Are you fetching our generated helm chart repositories?


I am installing "external-secrets" using ArgoCD:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-30"

spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    - ServerSideApply=true
    retry:
      limit: -1
      backoff:
        duration: 5s
        factor: 2 
        maxDuration: 10m
        
  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: {{ .Values.externalSecrets.chartVersion }}
    helm:
      valuesObject:
        fullnameOverride: "external-secrets"
        installCRDs: true
        crds:
          createClusterExternalSecret: true
          createClusterSecretStore: true
          createClusterGenerator: false
          createPushSecret: false
        processPushSecret: false
```

**Comment by gusfcarvalho** [comment]
I just did the same installation with Argocd (using your manifest) on a clean kind cluster - it installed these crds:

```
acraccesstokens.generators.external-secrets.io          2024-12-08T09:48:50Z
applications.argoproj.io                                2024-12-08T09:46:31Z
applicationsets.argoproj.io                             2024-12-08T09:46:31Z
appprojects.argoproj.io                                 2024-12-08T09:46:31Z
clusterexternalsecrets.external-secrets.io              2024-12-08T09:48:50Z
clustersecretstores.external-secrets.io                 2024-12-08T09:48:50Z
ecrauthorizationtokens.generators.external-secrets.io   2024-12-08T09:48:50Z
externalsecrets.external-secrets.io                     2024-12-08T09:48:50Z
fakes.generators.external-secrets.io                    2024-12-08T09:48:50Z
gcraccesstokens.generators.external-secrets.io          2024-12-08T09:48:50Z
githubaccesstokens.generators.external-secrets.io       2024-12-08T09:48:50Z
passwords.generators.external-secrets.io                2024-12-08T09:48:50Z
secretstores.external-secrets.io                        2024-12-08T09:48:50Z
stssessiontokens.generators.external-secrets.io         2024-12-08T09:48:50Z
uuids.generators.external-secrets.io                    2024-12-08T09:48:50Z
vaultdynamicsecrets.generators.external-secrets.io      2024-12-08T09:48:50Z
webhooks.generators.external-secrets.io                 2024-12-08T09:48:50Z                                                                       /0.1s
```
☝️ Which as you can see do not contain `clusterGenerator` at all.

If you want to reproduce:
```
kind create cluster
helm repo add argo https://argoproj.github.io/argo-helm 
helm install my-release argo/argo-cd
cat << EOF | kubectl apply -f -
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    - ServerSideApply=true
    retry:
      limit: -1
      backoff:
        duration: 5s
        factor: 2 
        maxDuration: 10m
        
  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: "0.11.0"
    helm:
      valuesObject:
        fullnameOverride: "external-secrets"
        installCRDs: true
        crds:
          createClusterExternalSecret: true
          createClusterSecretStore: true
          createClusterGenerator: false
          createPushSecret: false
        processPushSecret: false
EOF
echo waiting for app to sync
sleep 20
kubectl get crd | grep external-secrets
```

I recommend you to ask for support on slack channels (we are on #external-secrets on kubernetes slack) - maybe someone from the community can help out.

☝️ if you still need support to figure out what's going on, you can DM me @gusfcarvalho on kubernetes slack.
