### ISSUE TITLE
Very slow secret retrieval from azure key vault to on-prem k3s (how to troubleshoot?)

### ISSUE THREAD

**Issue by AurimasNav** [external-secrets/external-secrets#4204]
**Describe the bug**
Secrets take 30-60 or more minutes to retrieve

**To Reproduce**

values.yaml

```yaml
serviceMonitor:
  enabled: false
resources:
  limits:
    cpu: 1
    memory: 512Mi
  requests:
    cpu: 10m
    memory: 32Mi
webhook:
  serviceMonitor:
    enabled: false
  resources:
    limits:
      cpu: 1
      memory: 512Mi
    requests:
      cpu: 1m
      memory: 16Mi
certController:
  serviceMonitor:
    enabled: false
  resources:
    limits:
      cpu: 1
      memory: 512Mi
    requests:
      cpu: 1m
      memory: 16Mi
```

```yaml

clusterSecretStore.yaml

```yaml
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-keyvault
spec:
  provider:
    azurekv:
      environmentType: PublicCloud
      authType: ServicePrincipal
      tenantId: <tenant_id>
      authSecretRef:
        clientId:
          name: k3s-keyvault
          key: clientId
        clientSecret:
          name: k3s-keyvault
          key: clientSecret
      vaultUrl: "https://<my>.vault.azure.net/"
```

secretStoreAuth.yaml

```yaml
apiVersion: v1
data:
  clientId: <client_id>
  clientSecret: <client_secret>
kind: Secret
metadata:
  name: k3s-keyvault
  namespace: app-namespace
type: Opaque
```

externalSecret.yaml

```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: acr-pull
spec:
  refreshInterval: 30s
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault
  target:
    template:
      type: kubernetes.io/dockerconfigjson
    name: acr-pull
  dataFrom:
  - extract:
      key: acrpull
```

helm chart version 0.10.5
Server Version: v1.30.6+k3s1

**Expected behavior**
I expect secret to get synced in a few seconds, but it happens in 30 minutes to one hour or even more

**Additional context**
I'm running external-secrets on 4 clusters now with very similar setups, 2 in AKS and 2 on-prem, the problem happens on-prem only, I've assumed it has to do with network problems, however if I launch a debug pod and try to retrieve secrets from key-vault with curl etc. I get response pretty fast (few secs at most). 

How to debug this? I'm not able to see any logs in external-secrets pods indicating any issues, there are no visible timeouts, failed attempts etc. it just seems like nothing is happening and then suddenly the secret is synced:

log:
> {"level":"info","ts":1733988390.2331958,"logger":"provider.vault","msg":"initializing vault cache","size":262144}
{"level":"info","ts":1733988390.233209,"logger":"setup","msg":"starting manager"}
{"level":"info","ts":1733988390.2332935,"logger":"controller-runtime.metrics","msg":"Starting metrics server"}
{"level":"info","ts":1733988390.2334864,"logger":"controller-runtime.metrics","msg":"Serving metrics server","bindAddress":":8080","secure":false}
{"level":"info","ts":1733988390.334327,"msg":"Starting EventSource","controller":"secretstore","controllerGroup":"external-secrets.io","controllerKind":"SecretStore","source":"kind source: *v1beta1.SecretStore"}
{"level":"info","ts":1733988390.3343372,"msg":"Starting Controller","controller":"secretstore","controllerGroup":"external-secrets.io","controllerKind":"SecretStore"}
{"level":"info","ts":1733988390.3343632,"msg":"Starting EventSource","controller":"clustersecretstore","controllerGroup":"external-secrets.io","controllerKind":"ClusterSecretStore","source":"kind source: *v1beta1.ClusterSecretStore"}
{"level":"info","ts":1733988390.3343818,"msg":"Starting Controller","controller":"clustersecretstore","controllerGroup":"external-secrets.io","controllerKind":"ClusterSecretStore"}
{"level":"info","ts":1733988390.3344314,"msg":"Starting EventSource","controller":"externalsecret","controllerGroup":"external-secrets.io","controllerKind":"ExternalSecret","source":"kind source: *v1beta1.ExternalSecret"}
{"level":"info","ts":1733988390.3344443,"msg":"Starting EventSource","controller":"externalsecret","controllerGroup":"external-secrets.io","controllerKind":"ExternalSecret","source":"kind source: *v1.PartialObjectMetadata"}
{"level":"info","ts":1733988390.334447,"msg":"Starting Controller","controller":"externalsecret","controllerGroup":"external-secrets.io","controllerKind":"ExternalSecret"}
{"level":"info","ts":1733988390.3344805,"msg":"Starting EventSource","controller":"pushsecret","controllerGroup":"external-secrets.io","controllerKind":"PushSecret","source":"kind source: *v1alpha1.PushSecret"}
{"level":"info","ts":1733988390.3344922,"msg":"Starting Controller","controller":"pushsecret","controllerGroup":"external-secrets.io","controllerKind":"PushSecret"}
{"level":"info","ts":1733988390.3345454,"msg":"Starting EventSource","controller":"clusterexternalsecret","controllerGroup":"external-secrets.io","controllerKind":"ClusterExternalSecret","source":"kind source: *v1beta1.ClusterExternalSecret"}
{"level":"info","ts":1733988390.334569,"msg":"Starting EventSource","controller":"clusterexternalsecret","controllerGroup":"external-secrets.io","controllerKind":"ClusterExternalSecret","source":"kind source: *v1beta1.ExternalSecret"}
{"level":"info","ts":1733988390.3345833,"msg":"Starting EventSource","controller":"clusterexternalsecret","controllerGroup":"external-secrets.io","controllerKind":"ClusterExternalSecret","source":"kind source: *v1.Namespace"}
{"level":"info","ts":1733988390.334586,"msg":"Starting Controller","controller":"clusterexternalsecret","controllerGroup":"external-secrets.io","controllerKind":"ClusterExternalSecret"}
{"level":"info","ts":1733988390.4349144,"msg":"Starting workers","controller":"clustersecretstore","controllerGroup":"external-secrets.io","controllerKind":"ClusterSecretStore","worker count":1}
{"level":"info","ts":1733988390.4349277,"msg":"Starting workers","controller":"secretstore","controllerGroup":"external-secrets.io","controllerKind":"SecretStore","worker count":1}
{"level":"info","ts":1733988390.4356375,"msg":"Starting workers","controller":"clusterexternalsecret","controllerGroup":"external-secrets.io","controllerKind":"ClusterExternalSecret","worker count":1}
{"level":"info","ts":1733988390.4356534,"msg":"Starting workers","controller":"externalsecret","controllerGroup":"external-secrets.io","controllerKind":"ExternalSecret","worker count":1}
{"level":"info","ts":1733988390.436667,"msg":"Starting workers","controller":"pushsecret","controllerGroup":"external-secrets.io","controllerKind":"PushSecret","worker count":1}
{"level":"info","ts":1733988423.8232667,"logger":"controllers.ExternalSecret","msg":"reconciled secret","ExternalSecret":{"name":"acr-pull","namespace":"app-namespace"}}

**Comment by Skarlso** [comment]
Hi. Please try with 0.11.0 where we significantly improved the reconcile loop and refresh of secrets.

**Comment by AurimasNav** [comment]
It has been few minutes since I deployed 0.11.0, deleted couple of ExternalSecrets to let argocd recreate them and seeing same behavior as before, secrets are not being synced for a few minutes already, nothing seems to be happening in logs.

**Comment by Skarlso** [comment]
That seems ominous... Hm. Any status information on the external secret object or events in the event log?

**Comment by AurimasNav** [comment]
describe externalSecret:

```yaml
Name:         acr-pull
Namespace:    my-app
Annotations:  argocd.argoproj.io/tracking-id: my-app:external-secrets.io/ExternalSecret:my-app/acr-pull
API Version:  external-secrets.io/v1beta1
Kind:         ExternalSecret
Metadata:
  Creation Timestamp:  2024-12-12T08:11:13Z
  Generation:          2
  Resource Version:    560827
  UID:                 39af2f58-b9f4-416e-98b8-76ffb5826b2c
Spec:
  Data From:
    Extract:
      Conversion Strategy:  Default
      Decoding Strategy:    None
      Key:                  acrpull
      Metadata Policy:      None
  Refresh Interval:         30s
  Secret Store Ref:
    Kind:  ClusterSecretStore
    Name:  azure-keyvault
  Target:
    Creation Policy:  Owner
    Deletion Policy:  Retain
    Name:             acr-pull
    Template:
      Engine Version:  v2
      Merge Policy:    Replace
      Type:            kubernetes.io/dockerconfigjson
Events:                <none>
```
