### ISSUE TITLE
Forcing external-secret synchronization using 1password token secret fails sometimes with `status 403: Authorization: token does not have access to vault`

### ISSUE THREAD

**Issue by renepupil** [external-secrets/external-secrets#4205]
**Describe the bug**

We create a 1password token with read access to a vault that we use as a kubernetes secret in a external-secrets.io `SecretStore` which is used in an `ExternalSecret`

We sometimes force the synchronization of the external secret in our deployment.

Most times this works without issues, but sometimes the token is said to be invalid.

**To Reproduce**

1. Create 1password token for a vault and create kubernetes secret from it:

```bash
connect_token="$(op connect token create "fuzzy-token" --vault "fuzzy-vault,r")"
kubectl create secret generic onepassword-connect-token --type=Opaque --from-literal=token="${connect_token}"
```

2. Use secret in secret store:

```yaml
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: onepassword-secret-store
spec:
  provider:
    onepassword:
      connectHost: http://onepassword-connect.external-secrets:8080
      vaults: 
        fuzzy-vault: 1
      auth:
        secretRef:
          connectTokenSecretRef:
            name: onepassword-connect-token
            key: token
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: env-secret
spec:
  secretStoreRef:
    kind: SecretStore
    name: onepassword-secret-store
  target:
    name: env-secret
  data:
  - secretKey: MY_SECRET
    remoteRef:
      key: MY-SECRET-ITEM
```

3. Force synchronization of external secrets:

```bash
kubectl annotate externalsecret env-secret force-sync="$(date +%s)" --overwrite
```

4. Retrieve error events:

```bash
kubectl describe externalsecret env-secret
```

```
Events:
  Type     Reason        Age                   From              Message
  ----     ------        ----                  ----              -------
  Warning  UpdateFailed  2m7s (x627 over 14d)  external-secrets  status 403: Authorization: token does not have access to vault <vault-id>
  Warning  UpdateFailed  86s (x223 over 14d)   external-secrets  error finding 1Password Item: status 403: Authorization: token does not have access to vault <vault-id>
```

4. Recheck token state

```bash
op connect token list
```

```
ID                  NAME                                      STATE      INTEGRATION ID                EXPIRES AT
<token-id>    fuzzy-token                              ACTIVE     <integration-id>                    never
```
                              
**Expected behavior**

That the external secret is successfuly updated.

Expected event that we normally get is:

```
Events:
  Type     Reason        Age                   From              Message
  ----     ------        ----                  ----              -------
  Normal   Updated       47s (x341 over 14d)   external-secrets  Updated Secret
```

No idea why the token is valid sometimes and sometimes not.

**Additional context**

Maybe related https://github.com/1Password/connect/issues/82
