### ISSUE TITLE
[Question] How can I use aws provider in a different cloud

### ISSUE THREAD

**Issue by yongzhang** [external-secrets/external-secrets#4206]
Hi there

I'm trying to fetch secrets from aws secrets manager but from a differnent cloud like azure, I have secret store like this:

```
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: cluster-secrets-store
spec:
  provider:
    aws:
      service: SecretsManager
      region: ${aws_region}
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: awssm-secret
            namespace: kube-system
            key: access-key-id
          secretAccessKeySecretRef:
            name: awssm-secret
            namespace: kube-system
            key: secret-access-key
```

I created the aws user and granted required access permissions. But looks like it can't work, I see error:
```
RequestError: send request failed\ncaused by: Post \"https://secretsmanager.cn-northwest-1.amazonaws.com.cn/\": net/http: invalid header field value for \"Authorization\"","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.2/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.2/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.2/pkg/internal/controller/controller.go:224"
```

Please help, thanks.

**Comment by Skarlso** [comment]
Hello. Did you take a look at https://external-secrets.io/latest/provider/aws-secrets-manager/ on how to configure the AWS provider?

**Comment by yongzhang** [comment]
> Hello. Did you take a look at https://external-secrets.io/latest/provider/aws-secrets-manager/ on how to configure the AWS provider?

yeah but what am I missing?

**Comment by Skarlso** [comment]
Just asking if you have a `role` defined and all the required policies set up?

**Comment by yongzhang** [comment]
> Just asking if you have a `role` defined and all the required policies set up?

I also tried with a role, but that does not work too. And I see `role` is optional.

Here's the logs when adding a role:
```
"error":"could not validate provider: RequestError: send request failed\ncaused by: Post \"https://sts.cn-northwest-1.amazonaws.com.cn/\": net/http: invalid header field value for \"Authorization\"","stacktrace":"github.com/external-secrets/external-secrets/pkg/controllers/secretstore.reconcile\n\t/home/runner/work/external-secrets/external-secrets/pkg/controllers/secretstore/common.go:69\ngithub.com/external-secrets/external-secrets/pkg/controllers/secretstore.(*ClusterStoreReconciler).Reconcile\n\t/home/runner/work/external-secrets/external-secrets/pkg/controllers/secretstore/clustersecretstore_controller.go:66\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.2/pkg/internal/controller/controller.go:116\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.2/pkg/internal/controller/controller.go:303\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.2/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.2/pkg/internal/controller/controller.go:224"
```

So I'm curious if external-secerts supports my use case?

**Comment by Skarlso** [comment]
Are you able to confirm that those creds work with AWS CLI for example given that region?

**Comment by yongzhang** [comment]
I guess I had the same [here](https://github.com/external-secrets/external-secrets/discussions/1043#discussioncomment-9670482), let me try it.

**Comment by gusfcarvalho** [comment]
you need to add a specific ARN as a secret key if you want to do cross account connection without assuming any role
```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: key-value-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secretstore-dev
    kind: SecretStore
  target:
    name: key-value-dev
    creationPolicy: Owner
  data:
  - secretKey: test-value
    remoteRef:
      key: <full-arn>:<of-aws>::<goes-here>
```
