### ISSUE TITLE
Support Customer-Managed Encryption Keys (CMEK) for GCP Secret Manager

### ISSUE THREAD

**Issue by janlauber** [external-secrets/external-secrets#4209]
**Is your feature request related to a problem? Please describe.**
When using External Secrets Operator with GCP Secret Manager, there is currently no way to use Customer-Managed Encryption Keys (CMEK) for encrypting secrets. This is problematic for organizations that:
- Need to comply with specific security requirements
- Want to maintain control over their encryption keys
- Must meet regulatory requirements for key management
- Need to implement additional security controls for their secrets

**Describe the solution you'd like**
Add support for specifying a Cloud KMS key when creating secrets in GCP Secret Manager through the SecretStore resource. The solution should allow users to configure CMEK like this:

```yaml
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
  metadata:
    name: gcp-secret-store
spec:
  provider:
    gcpsm:
       projectID: my-project
       location: us-east-1
       cmekKeyName: projects/my-project/locations/us-east-1/keyRings/my-keyring/cryptoKeys/my-key
```

This would require:
1. Adding a new `cmekKeyName` field to the GCPSMProvider configuration
2. Implementing the CustomerManagedEncryption configuration when creating secrets

**Describe alternatives you've considered**
1. Using Google-managed encryption keys (current default) - but this doesn't provide the level of control required by some organizations
2. Implementing client-side encryption before storing secrets - but this adds complexity and doesn't integrate well with GCP's security model
3. Using a different secrets backend - but this may not be feasible for organizations already invested in GCP infrastructure

**Additional context**
- GCP Secret Manager documentation about CMEK: https://cloud.google.com/secret-manager/docs/cmek
- Similar functionality exists in other cloud providers (AWS KMS, Azure Key Vault)
- This feature is particularly important for regulated industries (finance, healthcare) that require control over encryption keys
