### ISSUE TITLE
Merge on secret managed by externalsecret

### ISSUE THREAD

**Issue by tomassatka** [external-secrets/external-secrets#4225]
**Describe the bug**
I have 2 external secrets that uses 2 different secretStoreRef.

- credentials-init: First one is pulling from vault and sets up username and password in template and create target secret
- credentials-ca: Second reads ca-bundle source secret and extracts ca and merge into target secret

```mermaid
graph TD;
  Vault -->|SecretStoreRef| ExternalSecret_credentials-init -->|CreationPolicy: Owner| Secret
  SourceSecret -->|SecretStoreRef| ExternalSecret_credentials-ca -->|CreationPolicy: Merge| Secret
```

Before updating to release 0.11.0 this used to work fine. Now i am getting error on second external secret:
`unable to mutate secret credentials: secret is owned by another ExternalSecret: credentials-init`

**To Reproduce**

first external secret 
```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: credentials-init
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: credentials
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      data:
        username: '{{ `{{ .username }}` }}'
        password: '{{ `{{ .password }}` }}'
  data:
    - secretKey: username
      remoteRef:
        key: kv/secret
        property: username
    - secretKey: password
      remoteRef:
        key: kv/secret
        property: password
```

second external secret
```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: credentials-ca
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: k8s-{{ .Release.Namespace }}
    kind: SecretStore
  target:
    name: credentials
    creationPolicy: Merge
    deletionPolicy: Retain
    template:
      type: Opaque
      data:
        ca.crt: '{{ `{{ .ca }}` }}'
  data:
    - secretKey: ca
      remoteRef:
        key: ca-certs
        property: ca.crt
```

kubernetes version:
```
[~]$ kubectl version
Client Version: v1.29.5
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.10
```
