### ISSUE TITLE
"Secret does not exist" with Vault SecretStore (using OpenBao)

### ISSUE THREAD

**Issue by franz-dalitz** [external-secrets/external-secrets#4227]
**Describe the bug**

If this is not an External-Secrets problem I'm sorry, just started learning both OpenBao and ESO yesterday.
Anyways, I think ESO is successfully connected to OpenBao, yet it says "Secret does not exist" for a secret that to me very clearly does exist.
I heard others have already used OpenBao as a drop-in for Vault successfully with ESO.
Ultimately this is simply a request for help I assume, if that isn't welcome feel free to tell me, I didn't know how else to solve my problem, tried what I could think of.
The exact error I see in Argo is `error retrieving secret at .data[0], key: test, err: Secret does not exist`.

**To Reproduce**

My system is a Rancher managed RKE2 cluster running on OpenSUSE Leap, controlled via ArgoCD and Kustomize.
The K8s version is v1.30.4 +rke2r1.
This is all of the relevant ESO stuff I think:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://github.com/external-secrets/external-secrets/releases/download/v0.11.0/external-secrets.yaml
- sa-token.yaml
- secret-store.yaml
- secret-test.yaml
```

```yaml
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: openbao
spec:
  provider:
    vault:
      server: http://openbao:8200
      path: kv
      auth:
        kubernetes:
          mountPath: kubernetes
          role: test
```

```yaml
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: test
spec:
  secretStoreRef:
    name: openbao
    kind: SecretStore
  target:
    name: external-secret-bao-test
  data:
  - secretKey: somesecret
    remoteRef:
      key: test
      property: somekey
```

```yaml
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: external-secrets-sa-token
  annotations:
    kubernetes.io/service-account.name: external-secrets
```

And this is the OpenBao setup:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: openbao
  repo: https://openbao.github.io/openbao-helm
  releaseName: openbao
  version: 0.7.0
  valuesFile: values.yaml
```

```yaml
server:
  dev:
    enabled: false
  standalone:
    enabled: true
  ha:
    enabled: false
ui:
  enabled: true
```

```bash
bao policy write test -<<EOF     
path "*"                                                  
{  capabilities = ["read"]                
}                         
EOF
```

```bash
bao auth enable kubernetes
```

```bash
bao write auth/kubernetes/config \  
    token_reviewer_jwt="$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" \  
    kubernetes_host=https://${KUBERNETES_PORT_443_TCP_ADDR}:443 \  
    kubernetes_ca_cert=@/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
```

```bash
bao write auth/kubernetes/role/test \
    bound_service_account_names=external-secrets \
    bound_service_account_namespaces=default \
    policies=test \
    ttl=168h
```

```bash
bao write auth/kubernetes/login role=test jwt=COPIED_FROM_THE_ESO_SA_TOKEN
```

```bash
bao secrets enable kv
```

```bash
bao kv put kv/test somekey=somevalue
```

**Expected behavior**
I'd assume the kv pair is read from bao and a secret called `external-secret-bao-test` is created, with the key `somesecret` that contains `somevalue`.

**Additional information**
I've checked that everything is in the same namespace.
`bao read kv/test` results in a correct output, so the secret should be present.
Also just tested that curling `openbao.default:8200/v1/kv/test` from somewhere else in the cluster, using my bao root token returns the correct data, so the api seems to be working.

**Comment by Skarlso** [comment]
Does the property exist?

```yaml
    remoteRef:
      key: test
      property: somekey
```

What's `somekey?`
