### ISSUE TITLE
UnrecognizedClientException: The security token included in the request is invalid. status code 400

### ISSUE THREAD

**Issue by alelapi** [external-secrets/external-secrets#4254]
**Describe the bug**
Hello, I'm still not sure if this is a bug or something I set up incorrectly, but my use case is quite simple, and I strictly followed the documentation. Therefore, I am confident that it is a bug.

I'm using Minikube on my local machine to test my cluster. I'm trying to set up an external secret from AWS Secret Manager. 
These are my configurations:
- external-secrets installed on a dedicated namespace `external-secrets`
- a cluster secret store (created successfully and in a Valid state):
```
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: secretstore
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-central-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-credentials
            key: aws_access_key_id
            namespace: external-secrets
          secretAccessKeySecretRef:
            name: aws-credentials
            key: aws_secret_access_key
            namespace: external-secrets
```

- the external secret:
```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: es-aws-credentials
  namespace: my-namespace
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secretstore
    kind: ClusterSecretStore
  target:
    name: es-aws-credentials
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: <my-aws-secret-id>
```

- the kubernetes secret containing the AWS credential, created manually with:
```
kubectl create secret generic aws-credentials \
  --from-literal=aws_access_key_id=$aws_access_key_id \
  --from-literal=aws_secret_access_key=$aws_secret_access_key \
  --namespace=external-secrets
```
The external-secrets controller can't create the Kubernetes secret, the ExternalSecret is an SecretSyncedError state and logs contain this error:
```
error processing spec.dataFrom[0].extract, err: UnrecognizedClientException: The security token included in the request is invalid. status code 400
```

Any hints? I think it might be an issue with Minikube (I'm using it on a MacOS, ARM, M2), but I don't know what else to try.
Edit: also, I'm using Colima as container runtime
