### ISSUE TITLE
Issue with Base64 Decoding in PushSecret for AWS Parameter Store

### ISSUE THREAD

**Issue by atali** [external-secrets/external-secrets#4263]
Description:

I am trying to push a secret to AWS Parameter Store using external-secrets (PushSecret) and encountered an issue with the Base64 decoding of certain fields. Specifically, the dbname and username fields are not being decoded correctly, while the password field works as expected.

Input Secret:

Here is the Kubernetes Secret I am working with:

```yaml
apiVersion: v1
data:
  dbname: YXBw
  password: bnh5MDhjZmExanhVWGtYMjRoeE14WWlBSmxlQWZMeFE=
  username: c3VwYWJhc2VfYWRtaW4=
kind: Secret
metadata:
  name: postgres-credentials
  namespace: database-dev-ca
type: Opaque
```

PushSecret:

Here is the PushSecret configuration:
```yaml
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: postgres-credentials
  namespace: database-dev-ca
spec:
  data:
  - conversionStrategy: None
    match:
      remoteRef:
        remoteKey: /xxxxxxx/dev/postgres-creds
    metadata:
      parameterStoreType: SecureString
  deletionPolicy: Delete
  refreshInterval: 1h
  secretStoreRefs:
  - kind: ClusterSecretStore
    name: aws-cluster-secret-store
  selector:
    secret:
      name: postgres-credentials
  template:
    data:
      dbname: '{{ .dbname | b64dec }}'
      password: '{{ .password | b64dec }}'
      username: '{{ .username | b64dec }}'
    engineVersion: v2
    mergePolicy: Replace
  updatePolicy: Replace
```

Expected Output:
---

In AWS Parameter Store, I expected the following decoded secret:

```json
{"dbname":"app","password":"nxy08cfa1jxUXkX24hxMxYiAJleAfLxQ","username":"supabase_admin"}
```
Actual Output:

However, I got the following:
```json
{"dbname":"aWxsZWdhbCBiYXNlNjQgZGF0YSBhdCBpbnB1dCBieXRlIDA=","password":"nxy08cfa1jxUXkX24hxMxYiAJleAfLxQ","username":"aWxsZWdhbCBiYXNlNjQgZGF0YSBhdCBpbnB1dCBieXRlIDg="}
```
Additional Debugging:
---
When manually decoding the dbname and username values, I encountered errors:
* Decoding *aWxsZWdhbCBiYXNlNjQgZGF0YSBhdCBpbnB1dCBieXRlIDA=* results in: *illegal base64 data at input byte 0*
* Decoding *aWxsZWdhbCBiYXNlNjQgZGF0YSBhdCBpbnB1dCBieXRlIDg=* results in: *illegal base64 data at input byte 8*
* The password field is decoded correctly and works as expected.

Question:
	•	Is there something wrong with how I am using the b64dec function in the PushSecret template?
	•	Could there be an issue with how the external-secrets operator handles Base64 decoding for these fields?

Any insights or suggestions on what I might be doing wrong would be greatly appreciated!

Let me know if you need further details or logs.

external-secrets: 0.12.1

**Comment by gusfcarvalho** [comment]
@atali hi! why did you add `b64dec` in the first place? anything rendered by the templates are read without being encoded.

**Comment by gusfcarvalho** [comment]
can you try using different names for the template out of a test?

```
  template:
    engineVersion: v2
    data:
      dbname2: "{{ .dbname  | b64dec }}"
      username2: "{{ .username  | b64dec }}"
      password2: "{{ .password | b64dec }}"
```

**Comment by Skarlso** [comment]
@atali if you could check out this PR: https://github.com/external-secrets/external-secrets/pull/4277 it has a command. You could test your template and see what it renders and then quickly play around with the values to figure out where they are broken.

Also would be a good feedback for the tool on what it could provide you with to make the debugging easier.

**Comment by Skarlso** [comment]
@atali Nice! I'm so glad this helped you out. :)

Actually I think this already caused some issues somewhere else too. I'll try looking to what I can do about it.

**Comment by Skarlso** [comment]
Hello. I didn't have the time to deal with this yet, sorry. :/ It is on my todo list though. :D

**Comment by Skarlso** [comment]
Okay, so, the issue here is that it's getting double encoded, right? So, if it's BASE64 already, don't do the encoding... Did I get that right? 🤔

**Comment by Skarlso** [comment]
I'm not sure yet. I need to play around. I'll try to replicate something with a unit test so I can move more rapidly.

**Comment by Skarlso** [comment]
Okay, I wrote a unit test to see what's up.

And now I get it. It's because it's a `map[string][]byte`. Some of the other providers do a conversion beforehand to a map[string]string. I don't want to change the default behaviour because that would be a breaking change, but let me see if I can make it optional. 🤔

**Comment by Skarlso** [comment]
@atali Let's make it a Metadata option, okay? So you would define it as such:

```yaml
    - match:
        remoteRef:
          remoteKey: my-first-parameter # Remote reference (where the secret is going to be pushed)
      metadata:
        apiVersion: kubernetes.external-secrets.io/v1alpha1
        kind: PushSecretMetadata
        spec:
          encodeAsDecoded: true
```

Or something like that. :D I'm open for better names. :)
