### ISSUE TITLE
IAM issue when filtering on only tags when using AWS secrets manager BatchGetSecretValue

### ISSUE THREAD

**Issue by UnyieldingOrca** [external-secrets/external-secrets#4264]
**Describe the bug**
I believe the new feature added https://github.com/external-secrets/external-secrets/pull/4181 broke our setup and it's not possible to update our IAM policy to make it work and keep the same scope it had before. The situation we have is we are trying to filter by a set of tag key value pairs only to search for some number of secrets to fill in a template. But even with the recommended update to the IAM policy I am getting a secret sync error.

**To Reproduce**
External Secret Manifest
```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: extsecret
  namespace: prometheus
spec:
  dataFrom:
    - find:
        tags:
          SlackWebhookUrl: "true"
          Component: abc
          Team: xyz
          Environment: dev
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: secretstore
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: test-secret
    template:
      data:
        values.yaml: |
          ...
```

IAM Policy
```
{
    "Statement": [
        {
            "Action": [
                "secretsmanager:List*",
                "secretsmanager:Get*",
                "secretsmanager:Describe*",
                "secretsmanager:BatchGet*"
            ],
            "Condition": {
                "StringEquals": {
                    "aws:ResourceTag/Component": [
                        "abc"
                    ],
                    "aws:ResourceTag/Environment": [
                        "dev"
                    ]
                }
            },
            "Effect": "Allow",
            "Resource": "*",
            "Sid": "AllowViewSecretValues"
        },
        {
            "Action": [
                "secretsmanager:ListSecrets",
                "secretsmanager:DescribeSecret"
            ],
            "Effect": "Allow",
            "Resource": "*",
            "Sid": "AllowListDescribeSecret"
        }
    ],
    "Version": "2012-10-17"
}
```

Reported Error
```
  Warning  UpdateFailed  3m7s  external-secrets  error processing spec.dataFrom[0].find, err: error getting all secrets: AccessDeniedException: User: arn:aws:sts::1234:assumed-role/role/session-name is not authorized to perform: secretsmanager:BatchGetSecretValue because no identity-based policy allows the secretsmanager:BatchGetSecretValue action
           status code: 400, request id: ...
```

ESO version: v0.12.1

**Additional context**
I believe the underlying issue is with the aws batch get secret filter semantics. I believe it performs a union over all filters and not an intersection so the operation is trying to read more secrets than the IAM permission allows for (and that I don't want to give access to). If I'm right about it being a union I would have to update the policy to allow access to all secrets who's tags match that team and all secrets in that environment which is clearly problematic. 

I think one workaround is to also supply a path regex filter to only match my specific secrets and not match on tags but this may not be suitable for all situations. 

**Suggestion**
One suggestion I have is to add an optional flag to the spec to allow using the old logic that uses the ListSecrets operation.
