### ISSUE TITLE
Impossible to disable conversion

### ISSUE THREAD

**Issue by michaelswierszcz** [external-secrets/external-secrets#4272]
**Describe the bug**
I am running external-secrets v0.3.10. All of my externalsecrets are v1alpha1. I would like to upgrade to the latest operator and then convert my externalsecrets manually from v1alpha1 to v1beta1. I do not want to use the conversion as I am running in a GitOps style and would like to have all cluster state reflected in my in git repository. There seems to be no way to disable this conversion in the helm chart. From what I can tell.

**To Reproduce**
```
installCRDs: false
crds:
  # -- If true, create CRDs for Cluster External Secret.
  createClusterExternalSecret: false
  # -- If true, create CRDs for Cluster Secret Store.
  createClusterSecretStore: false
  # -- If true, create CRDs for Cluster Generator.
  createClusterGenerator: false
  # -- If true, create CRDs for Push Secret.
  createPushSecret: false
  annotations: {}
  conversion:
    # -- If webhook is set to false this also needs to be set to false otherwise the kubeapi will be hammered because the conversion is looking for a webhook endpoint.
    enabled: false
```

Kubernetes v1.30
ESO v.0.12.1

**Expected behavior**
crds.conversion.enabled = false to actually work.
