### ISSUE TITLE
Support for `namespace` parameter in service principal secretref for `ACRAccessToken` generator

### ISSUE THREAD

**Issue by djryanj** [external-secrets/external-secrets#4295]
**Is your feature request related to a problem? Please describe.**
Currently, in a `ClusterSecretStore`, you can do this:

```yaml
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-store
spec:
  provider:
    azurekv:
      tenantId: tenantId
      vaultUrl: "https://url.vault.azure.net"
      authSecretRef:
        clientId:
          name: azure-secret-sp
          key: ClientID
          namespace: external-secrets
        clientSecret:
          name: azure-secret-sp
          key: ClientSecret
          namespace: external-secrets
```

However, that same capability does not exist for `ACRAccessToken` (cluster or otherwise):

```yaml
apiVersion: generators.external-secrets.io/v1alpha1
kind: ClusterGenerator
metadata:
  name: registry-generator
  namespace: external-secrets
spec:
  kind: ACRAccessToken
  generator:
    acrAccessTokenSpec:
      tenantId: tenantId
      registry: url.azurecr.io
      environmentType: "PublicCloud"
      auth:
        servicePrincipal:
          secretRef:
            clientId:
              name: azure-secret-sp
              key: ClientID
              namespace: external-secrets # can't do this!
            clientSecret:
              name: azure-secret-sp
              key: ClientSecret
              namespace: external-secrets # can't do this!
```

The obvious issue here is that we need to have the service principal secret available in the namespace. This means either using a clusterexternalsecret, an externalsecret, or somehow reflecting the secret into all required namespaces. This is unnecessarily complex.

**Describe the solution you'd like**
Within the `spec.generator.acrAccessTokenSpec.auth.servicePrincipal.secretRef` fields (or just `spec.auth.servicePrincipal.secretRef` if not using a cluster generator), the ability to specify and use secrets from another namespace in the same way as is possible with `SecretStore` and `ClusterSecretStore`.

**Describe alternatives you've considered**
As mentioned, it's possible to get the secret into the namespace so this works, but it's suboptimal and presents an inconsistent API between objects that appear similar.

**Additional context**
None.
