### ISSUE TITLE
AzureKV Backend not working with ClusterSecretStore Configuration

### ISSUE THREAD

**Issue by gusfcarvalho** [external-secrets/external-secrets#433]
**Describe the solution you'd like**
When configuring a cluster secret store to use an azure backend provider, we get the following error from ESO:

```
{"level":"error","ts":1634324495.556207,"logger":"controllers.ExternalSecret","msg":"could not get provider client","ExternalSecret":"default/external-secret-key","SecretStore":"/azurekeyvault-secretstore-autogen-xvlbzgba","error":"could not find secret /azure-credentials: Secret \"azure-credentials\" not found","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.3/pkg/internal/controller/controller.go:298\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.3/pkg/internal/controller/controller.go:253\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.3/pkg/internal/controller/controller.go:214"}
{"level":"error","ts":1634324495.5643294,"logger":"controllers.ExternalSecret","msg":"could not get provider client","ExternalSecret":"default/external-secret-key","SecretStore":"/azurekeyvault-secretstore-autogen-xvlbzgba","error":"could not find secret /azure-credentials: Secret \"azure-credentials\" not found","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.3/pkg/internal/controller/controller.go:298\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.3/pkg/internal/controller/controller.go:253\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.3/pkg/internal/controller/controller.go:214"}
```

It seems that the cause is a parsing failure from the configured namespace information.

**Observations (Constraints, Context, etc):**
eso version: 0.3.6
manifest files applied:
ExternalSecret:
```
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  creationTimestamp: null
  name: external-secret-key
spec:
  data:
  - remoteRef:
      key: example-externalsecret-key
    secretKey: external-key
  secretStoreRef:
    kind: ClusterSecretStore
    name: azurekeyvault-secretstore-autogen-xvlbzgba
  target:
    name: external-secret-key
    template:
      metadata: {}
status:
  refreshTime: null
  ```
  
  ClusterStore:
  ```
kind: ClusterSecretStore
metadata:
  creationTimestamp: null
  name: azurekeyvault-secretstore-autogen-xvlbzgba
spec:
  controller: ""
  provider:
    azurekv:
      authSecretRef:
        clientId:
          key: clientid
          name: azure-credentials
          namespace: kes
        clientSecret:
          key: clientsecret
          name: azure-credentials
          namespace: kes
      tenantId: bc51f07b-XXXXXXXXXbe
      vaultUrl: xxxxxxxxxxxxxxxxx
status:
  conditions: null
  ```
