### ISSUE TITLE
Add support for exclude fields in External Secrets

### ISSUE THREAD

**Issue by brunomartins84** [external-secrets/external-secrets#4330]
## Description:
I would like to request a new feature for the External Secrets Operator: **`exclude`**. This feature would enable more efficient and scalable handling of secrets, particularly when working with external secret stores like **1Password**.

In my use case, I am synchronizing secrets from 1Password to Kubernetes using `External Secrets Operator`. However, 1Password includes unnecessary fields by default, such as `notesPlain`, `username`, and `password`. These fields are synchronized even when they are blank, resulting in cluttered Kubernetes Secrets.

---

### 1. `exclude` Field
The `exclude` field would allow users to specify a list of fields that should not be included in the resulting Kubernetes Secret. This would be especially useful when using `dataFrom`.

#### Proposed Configuration:
```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example-secret
spec:
  secretStoreRef:
    name: my-secret-store
    kind: SecretStore
  dataFrom:
    - extract:
        key: my-secret-key
        exclude:
          - notesPlain
          - password
          - username

  ```
  **Expected Behavior**:
  The operator would fetch all fields from the specified external secret but would exclude the fields listed under exclude when creating the Kubernetes Secret.
  
  ----
  
  Thank you for considering this feature request!

**Comment by gusfcarvalho** [comment]
Actually, this is the expected behavior of using `dataFrom`. It will fetch all data from that place 😄 

I don't think this is a bug at all.

To filter out these information you can already use either `data` and name the `property` you want individually, or use templating to filter out these specific keys from being added.


IMO, I don't think this feature request is worth given some alternatives already exist.

**Comment by Skarlso** [comment]
Ah sorry, I assumed that data and key selection already exists just it wasn't shown. :D

**Comment by brunomartins84** [comment]
@gusfcarvalho thank you for the clarification! However, I believe that explicitly listing all desired fields using data or templating can be impractical and error-prone when dealing with secrets that have many fields.

An exclude field would simplify configurations by allowing users to focus only on the fields they don't need, instead of listing all the ones they do. This could make managing large secrets much more efficient.

**Comment by gusfcarvalho** [comment]
I don`t agree the feature is going to be useful. The problem is it's hard to maintain. This needs to be done across all providers.

**Comment by brunomartins84** [comment]
Yeah, would be great, I understand your point about the maintenance challenge, and I can’t really assess the effort involved. I just wanted to share this need, which I believe others might have as well. Thank you for considering it.

**Comment by Skarlso** [comment]
I believe an exclusion would be way more errorprone. And considering we are dealing with secrets here an exclusion is more of a security risk than explicit definition.

Consider the scenario where you define an exclusion and forgot to add a field that has a token access to production data.
Now, every secret reconciled with that exclusion list will have that token and could be used for malicious purposes.

Defining secrets _explicitly_ is the only viable option IMHO.

**Comment by gusfcarvalho** [comment]
🤔 what we could do that would be easier to maintain is apply it as a post-fetching data filter (like we do with `rewrite`):

```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example-secret
spec:
  secretStoreRef:
    name: my-secret-store
    kind: SecretStore
  dataFrom:
    - extract:
        key: my-secret-key
      rewrite:
      - regexp:
           source: foo
           target: bar
      select:
      # exclude all keys got from dataFrom
      -  regexp: "*" 
         operation: Exclude 
     # Re-Add only `bar`
      -  names: [ "bar" ] #one or the other 
         operation: Include # Include or Exclude
```

@Skarlso  WDYT?

**Comment by Skarlso** [comment]
I could get behind that, because at that point it's either all or specific fields. Choosing _all_ **IS** specific too. So... this could work.

**Comment by brunomartins84** [comment]
@gusfcarvalho @Skarlso thank you for the clarification! Based on my understanding, I believe we can simplify the approach without needing the rewrite section if the goal is to include all keys by default and exclude only specific ones. Here's an updated example with multiple keys in the Exclude section:

```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example-secret
spec:
  secretStoreRef:
    name: my-secret-store
    kind: SecretStore
  dataFrom:
    - extract:
        key: my-secret-key
      select:
      # Include everything by default
      - regexp: "*" 
        operation: Include 
      # Exclude specific keys
      - names: 
          - "unwanted-key-1"
          - "unwanted-key-2"
          - "unwanted-key-3"
        operation: Exclude
```

With this configuration:
- All keys extracted from my-secret-key are included by default.
- Specific keys like unwanted-key-1, unwanted-key-2, and unwanted-key-3 are excluded explicitly.

Does this approach align with the intended behavior? If yes, I can proceed to create a PR for it!
