### ISSUE TITLE
Use a secret key that contains "." in ExternalSecret template

### ISSUE THREAD

**Issue by vezzalinistefano** [external-secrets/external-secrets#4332]
Given an ExternalSecret like that
```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gradle-settings
  namespace: test
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: test-secrets-store
  target:
    name: gradle-settings
    creationPolicy: Owner
    template:
      data:
        "gradle.properties": "{{ `{{ .gradle.properties }}` }}"
  data:
    - secretKey: gradle.properties
      remoteRef:
        key: secret_store_gradle_properties
```

ESO gives me an error because it can't find the property "gradle", I'd like to understand how can i escape the dot in the template data, i tried various escape methods but nothing seems to work. Is the only solution to change `gradle.properties` in the datas to something like `gradle_properties` ?
That would be a solution but generates new problems when i don't need to use the template.
