### ISSUE TITLE
Gitlab group variable regression between v0.10.7 and v0.11.0 (still present in v0.13.0)

### ISSUE THREAD

**Issue by babs** [external-secrets/external-secrets#4361]
**Describe the bug**
I use on prem Gitlab and uses a *Group* to store some of my secrets as variables.

Using v0.10.7, secrets are properly fetched from the Gitlab instance and related Secret object is created:
```
ip.ip.ip.ip - - [02/Feb/2025:17:22:48 +0100] "GET /api/v4/projects//variables/MY_SECRET_VARIABLE HTTP/2.0" 404 25 "" "go-gitlab" -
ip.ip.ip.ip - - [02/Feb/2025:17:22:48 +0100] "GET /api/v4/groups/{my group id}/variables/MY_SECRET_VARIABLE HTTP/2.0" 200 250 "" "go-gitlab" 1.48
```

When using the very same setup with external secret v0.11.0 and v0.13.0 the secret is not fetched anymore and I've only one call made to gitlab:
```
ip.ip.ip.ip - - [02/Feb/2025:17:24:39 +0100] "GET /api/v4/projects//variables/MY_SECRET_VARIABLE HTTP/2.0" 404 25 "" "go-gitlab" -
```

**To Reproduce**
1. create a `ClusterSecretStore` referencing the gitlab instance and the groupid
2. create a CI/CD variable in the group
3. create an `ExternalSecret`

```yaml
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: my-store
spec:
  provider:
    gitlab:
      auth:
        SecretRef:
          accessToken:
            key: token
            name: gitlab-secret
            namespace: external-secrets
      groupIDs:
        - '{my group id}'
      url: {my_gitlab_url}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: my-secret-variable-secret
spec:
  dataFrom:
    - extract:
        key: MY_SECRET_VARIABLE
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: my-store
```

**Expected behavior**

I'd expect the provider to not stop trying on the first 404 and try the group, like in v0.10.7 and bellow, or even don't try the project as it's not referenced in the ClusterSecretStore.
