### ISSUE TITLE
ECRAuthorizationToken ClusterGenerator ignores namespace in serviceAccountRef

### ISSUE THREAD

**Issue by jmalloc** [external-secrets/external-secrets#4384]
## **Describe the bug**

When using a `ClusterGenerator` of kind `ECRAuthorizationToken` with `JWT` (IRSA) authentication, the controller attempts to lookup the service account in the namespace of the `ExternalSecret`, instead of the namespace specified in the `serviceAccountRef` of the `ClusterGenerator`.

The `ExternalSecret` then fails to resolve with the following error:

```
error processing spec.dataFrom[0].sourceRef.generatorRef, err: error using generator: unable to create aws session: ServiceAccount "external-secrets.ecr" not found
```

## **To Reproduce**

Define a `ClusterGenerator` that refers to a service account in one namespace, and an `ExternalSecret` in a different namespace.

```yaml
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  namespace: kube-addons # SERVICE ACCOUNT NAMESPACE
  name: external-secrets.ecr
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<REDACTED>:role/external-secrets.ecr
---  
apiVersion: generators.external-secrets.io/v1alpha1
kind: ClusterGenerator
metadata:
  name: aws-elastic-container-registry
spec:
  kind: ECRAuthorizationToken
  generator:
    ecrAuthorizationTokenSpec:
      auth:
        jwt:
          serviceAccountRef:
            namespace: kube-addons # CORRECTLY REFERS TO SERVICE ACCOUNT NAMESPACE
            name: external-secrets.ecr
      region: us-east-1
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  namespace: argocd # EXTERNAL SECRET NAMESPACE
  name: ecr-helm
spec:
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: ClusterGenerator
        name: aws-elastic-container-registry
  refreshInterval: 6h
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    name: ecr-helm
    template:
      data:
        enableOCI: "true"
        name: ecr-helm
        password: '{{ .password }}'
        type: helm
        url: <REDACTED>.dkr.ecr.us-east-1.amazonaws.com
        username: '{{ .username }}'
      engineVersion: v2
      mergePolicy: Replace
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
```

ESO version: 0.14.0
K8s version: v1.31.5-eks-8cce635

## **Expected behavior**

The resolver/generator should use look in the namespace specified in the `serviceAccountRef` instead of in the namespace of the `ExternalSecret`.

## **Additional context**

I'm not familiar with the codebase, but in an attempt to provide some more context, I've found that the [call to `credsFromServiceAccount()`](https://github.com/external-secrets/external-secrets/blob/92b7ebcc6bfb3f2be3d3686e8e0cbd9b3c218467/pkg/provider/aws/auth/auth.go#L170) hardcodes `false` for the `isClusterKind` parameter, but this should probably be set based on whether or not the generator is a "virtual" generator created by a `ClusterGenerator` resource. 

Perhaps an `IsVirtual` field could be added to [`ecr.Generator`](https://github.com/external-secrets/external-secrets/blob/92b7ebcc6bfb3f2be3d3686e8e0cbd9b3c218467/pkg/generator/ecr/ecr.go#L39) and a different instance returned based on whether or not the generator was obtained via a `ClusterGenerator`. I'm not sure if this is possible or logical given the existing registry of generators. Otherwise, I think the [`Generate()` method](https://github.com/external-secrets/external-secrets/blob/92b7ebcc6bfb3f2be3d3686e8e0cbd9b3c218467/apis/generators/v1alpha1/generator_interfaces.go#L35) of the `v1alpha1.Generator` interface would need to accept such a parameter. 

Thank you!
