### ISSUE TITLE
Allow multiple generators in the same ExternalSecret

### ISSUE THREAD

**Issue by uncycler** [external-secrets/external-secrets#4386]
**Is your feature request related to a problem? Please describe.**
It is possible to add multiple generators in dataFrom. But since results are merged, only last generator's values are available. In this example, I have 3 ACR instances and I would to like to produce a single dockerconfigjson. But It's not possible since I can only retrieve .username and .password from the last one.

```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  generation: 15
  name: registries
spec:
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: ACRAccessToken
        name: acr1
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: ACRAccessToken
        name: acr2
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: ACRAccessToken
        name: acr3
```

**Describe the solution you'd like**
Elements from dataFrom should be accessible individualy in template.

```yaml
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: registries
    template:
      data:
        dockercfg.json: |
         {{- range $k, $v := . -}}
              username = $v.username
              password = $v.password
         {{end}}
      mergePolicy: Replace
```

**Comment by Skarlso** [comment]
Technically, you can define multiple generators... IF they are of a different type. :D What you are requesting is accessing generators separately even if they are the _same_ type. :)

**Comment by uncycler** [comment]
> Technically, you can define multiple generators... IF they are of a different type. :D What you are requesting is accessing generators separately even if they are the _same_ type. :)

Well, except if the generators return the same keys ;-)

**Comment by Skarlso** [comment]
Yes. :D 

I don't know yet how to do this nicely as generators are the ones defining the keys they produce. Ugh. Maybe prefix them with the generator name? But then you can't reference the SAME generator multiple times of course. Random values don't work either, since you need to template it. I have to think of something _good_ to do with this.

**Comment by uncycler** [comment]
What about something:

```yaml
spec:
  dataFrom:
  - sourceRef:
      nameRef: acr1
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: ACRAccessToken
        name: acr1
```

And then you access keys like that:

```yaml
    template:
      data:
        dockercfg.json: {{ .acr1.username }}
```

Could be nameRef, namespace, prefix..., or just a bool use use name as prefix.

**Comment by Skarlso** [comment]
Modifying the sourceRef should be the last option. But referencing through name is one of the potential things, yes.

**Comment by Skarlso** [comment]
Follow this discussion you can actually define multiple generators if you use Rewrite key -> https://github.com/external-secrets/external-secrets/discussions/3820#discussioncomment-12128302

**Comment by uncycler** [comment]
Exactly what I was looking for!

```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: registries
spec:
  dataFrom:
  - rewrite:
    - regexp:
        source: (.*)
        target: acr1_$1
    sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: ACRAccessToken
        name: acr1
  - rewrite:
    - regexp:
        source: (.*)
        target: acr2_$1
    sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: ACRAccessToken
        name: acr2
  - rewrite:
    - regexp:
        source: (.*)
        target: acr3_$1
    sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: ACRAccessToken
        name: acr3
```

Then I can access key with `acr1_username`.

Thanks for the good work!
