### ISSUE TITLE
Kuberenetes external-secret.io operator can not unmarshal GCP secret value stored as plain text

### ISSUE THREAD

**Issue by divyangjp** [external-secrets/external-secrets#4391]
**Describe the bug**
Kuberenetes external-secret.io operator can not unmarshal GCP secret value stored as plain text

**To Reproduce**
Created GCP secret and stored plain text value e.g. `userpassword`

Created and applied external-secrets.io yaml manifest as shown below

```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test-ext-secret-gcp
  namespace: myplatform
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: secret-store
  target:
    name: db-readonly-userpass
  dataFrom:
      # GCP Secrets Manager secret name
    - extract:
        key: gcp-db-readonly-userpass
```

When doing kubectl describe, it gives error `unable to unmarshal secret: invalid character 'u' looking for beginning of value`

**Expected behavior**
A kubernetes secret should be created with the value stored in GCP secret

**Comment by Skarlso** [comment]
Hello.

`dataFrom` is used for JSON based keys. If you have a plain text entry you need to use data like this:

```yaml
  data:
  - secretKey: gcp-db-readonly-userpass
    remoteRef:
      key: gcp-db-readonly-userpass  
```
