### ISSUE TITLE
Allow in external-secrets to pull from existing k8s ConfigMap with a Kubernetes Provider

### ISSUE THREAD

**Issue by qdrddr** [external-secrets/external-secrets#4395]
**Is your feature request related to a problem? Please describe.**
Currently, ESO allows the use of Kubernetes Provider I can pull into my ExternalSecret data from existing k8s Secret resources only.
But **not from configMaps**. The season is simple: in the configMap, we can specify a hostname, and in ES secret I want to create a Postgres URL that includes the hostname from my configMap. This ensures to removal of duplication and human error for the user when they work with k8s so if the hostname was changed, there will be no need (forget) to also fix the secret.

**Describe the solution you'd like**
In the ExternalSecret using Kubernetes provider, I want to be able to pull from existing configMap k8s resources.
(similar to how it currently works with k8s secret resources.

**Describe alternatives you've considered**
Webhooks

**Additional context**
example how it could look like, notice `type: ConfigMap` in the `data[0].remoteRef` at the very bottom:
```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: database-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-store-cluster            # name of the SecretStore (or kind specified)
  target:
    name: database-credentials  # name of the k8s Secret to be created
  data:
  - secretKey: secret1
    remoteRef:
      # The name of the k8s secret resource
      key: mysecret
      # The key inside the secret
      property: username
      namespace: cert-manager-system
  - secretKey: configmap2
    remoteRef:
      # The name of the k8s configMap resource
      key: myconfigmap
      # The key inside the configMap
      property: url
      type: ConfigMap
      namespace: cert-manager-system
```

**Comment by qdrddr** [comment]
connected with https://github.com/external-secrets/external-secrets/issues/4396

**Comment by Skarlso** [comment]
That should already be possible through templating. You can use templating in order to pull values from a ConfigMap.

**Comment by qdrddr** [comment]
I do not store templates in my config map. These configMaps are automatically generated buly 3rd parthelp charts and I'm not in control of how they created:
I just want to pull from the configMap just like I can pull from a secret.

**Comment by Skarlso** [comment]
I understand. That's actually a bigger undertaking than you'd think. And there is already something brewing in that regard here: https://github.com/external-secrets/external-secrets/issues/2503

**Comment by Skarlso** [comment]
@gusfcarvalho is the one that wanted to take it and work on it :) ( Sorry for calling you out Gustavo :D :D )

**Comment by gusfcarvalho** [comment]
Hi @qdrddr ! 

ESO already allows you to pull information from configmaps. Check templateFrom - you can specify a configmap as the source.

**Comment by Skarlso** [comment]
But... but... I said that too.... 🤔

**Comment by Skarlso** [comment]
@qdrddr 

>I do not store templates in my configMaps. These configMaps are automatically generated by 3rd party helm charts and I'm not in control of how they are created:


To be clear, I misread sorry, you don't need templates in there, you can just read values from a config map.

**Comment by qdrddr** [comment]
@Skarlso @gusfcarvalho can you guys please provide and example of CR manifests?

Say I have configMap named "superconf" with key "URL".
How do I pull it into my ExternalSecret? How such a reference would look like?

**Comment by qdrddr** [comment]
Because this is NOT what I need:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config-tpl
data:
  config.yaml: |
    datasources:
      - name: Graphite
        type: graphite
        access: proxy
        url: http://localhost:8080
        password: "{{ .password | toString }}" # <-- convert []byte to string
        user: "{{ .user | toString }}"         # <-- convert []byte to string
---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: my-template-example
spec:
  # ...
  target:
    name: secret-to-be-created
    template:
      templateFrom:
      - configMap:
          # name of the configmap to pull in
          name: grafana-config-tpl
          # here you define the keys that should be used as template
          items:
          - key: config.yaml
  data:
  - secretKey: user
    remoteRef:
      key: /grafana/user
  - secretKey: password
    remoteRef:
      key: /grafana/password
```


What I want to do is to pull values from configMap as variables. To make something like this:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfigmap
data:
  config.yaml: |
    datasources:
      - name: Graphite
        type: graphite
        access: proxy
        host: postgresdb1
        port: 5432
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: database-credentials-es
spec:
  refreshInterval: 1h
  secretStoreRef:
    - kind: ClusterSecretStore
       name: k8s-store-cluster            # name of the SecretStore (or kind specified)
    - name: bitwarden-secretsmanager
       kind: SecretStore
  target:
    name: database-credentials
    template:
      engineVersion: v2
      data:
        URL: "postgres://postgres:${{ .PG_PASSWORD }}@${{ .cm_host }}:${{ .cm_port }}"

  data:
  - secretKey: cm_host
    remoteRef:
      # The name of the k8s configMap resource
      key: myconfigmap
      # The key inside the configMap
      property: host
      type: ConfigMap
      namespace: cert-manager-system
  - secretKey: cm_port
    remoteRef:
      # The name of the k8s configMap resource
      key: myconfigmap
      # The key inside the configMap
      property: port
      type: ConfigMap
      namespace: cert-manager-system
  - secretKey: PG_PASSWORD
    remoteRef:
      key: "1ee75c6-beed-43ee5-aeed7-b26eee5c7f6"
```
