### ISSUE TITLE
ExternalSecret.data[0].remoteRef.namespace && ClusterSecretStore.spec.provider.kubernetes.remoteNamespace: '*' || Allow ExternalSecret to pool from multiple namespaces for Kubernetes provider

### ISSUE THREAD

**Issue by qdrddr** [external-secrets/external-secrets#4396]
**Is your feature request related to a problem? Please describe.**
Currently, ESO allows the create both ClusterSecretStore & SecretStore with Kubernetes provider. Though *ClusterSecretStore is still limited to only one namespace* via the `remoteNamespace`.

**Describe the solution you'd like**
If remoteNamespace is not set or is set to '*' ClusterSecretStore should be able to pull from any namespaces and limited only by the conditions namespaces. 

**Describe alternatives you've considered**

**Additional context**
Example how it would look like, notice `remoteNamespace: '*'`, in ClusterRole `configMaps` and  the `namespace: cert-manager-system` in ExternalSecret:
```yaml
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: k8s-store-cluster
spec:
  provider:
    kubernetes:
      # with this, the store can pull only from `kube-systems` namespace
      # Required, if not set then populated to the "default" namespace
      remoteNamespace: '*' # <- When not provided or is set to '*' all namespaces are allowed
      auth:
        serviceAccount:
          name: eso-store-sa
          namespace: kube-system
      server:
        url: "https://kubernetes.default.svc"
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
          namespace: kube-system
  conditions:
  - namespaces:
      - kube-system
      - cert-manager-system
      - default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eso-store-role
rules:
- apiGroups: [""]
  resources:
  - secrets
  - configMaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - authorization.k8s.io
  resources:
  - selfsubjectrulesreviews
  verbs:
  - create
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eso-store-sa
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: eso-store-crb
subjects:
- kind: ServiceAccount
  name: eso-store-sa
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: eso-store-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: database-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-store-cluster            # name of the SecretStore (or kind specified)
  target:
    name: database-credentials  # name of the k8s Secret to be created
  data:
  - secretKey: secret1
    remoteRef:
      # The name of the k8s secret resource
      key: mysecret
      # The key inside the secret
      property: username
      namespace: cert-manager-system
  - secretKey: configmap2
    remoteRef:
      # The name of the k8s configMap resource
      key: myconfigmap
      # The key inside the configMap
      property: url
      type: ConfigMap
      namespace: cert-manager-system
```

**Comment by qdrddr** [comment]
Connected with https://github.com/external-secrets/external-secrets/issues/4395

**Comment by Skarlso** [comment]
Related https://github.com/external-secrets/external-secrets/issues/4384

**Comment by Skarlso** [comment]
Hm. Did you try out what happens if you leave it empty?

**Comment by gusfcarvalho** [comment]
just FYI, an AWS Secrets Manager ClusterSecretStore is not able to talk to all AWS SM Accounts over an organization. It just allows consumers from all namespaces to use it.

IMO, this feature if done (carefully, as it has a lot of security considerations), would also need to apply to SecretStores.

**Comment by gusfcarvalho** [comment]
an example I see this being used in terms of implementation is this:

```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: database-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-store-cluster            # name of the SecretStore (or kind specified)
  target:
    name: database-credentials  # name of the k8s Secret to be created
  data:
  - secretKey: secret1
    remoteRef:
      sourceRef:
        secretStoreRef:
          kind: ClusterSecretStore
          name: k8s-store-cluster
      key: mynamespace/mysecret ## Similar to what we do at other providers for namespacing
      property: username
  - secretKey: configmap2
    remoteRef:
      sourceRef:
        secretStoreRef:
          kind: ClusterSecretStore
          name: k8s-store-cm-cluster
      key: myothernamespace/myconfigmap
      property: url
```
