### ISSUE TITLE
PushSecret stopped updating after helm chart upgrade

### ISSUE THREAD

**Issue by caycehouse** [external-secrets/external-secrets#4397]
**Describe the bug**
After updating to Helm chart version [v0.14.0](https://github.com/external-secrets/external-secrets/releases/tag/v0.14.0) my PushSecret stopped updating, and errors with: `"panic":"runtime error: invalid memory address or nil pointer dereference"`

**To Reproduce**
```
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: home-tls
spec:
  secretStoreRefs:
    - name: onepassword
      kind: ClusterSecretStore
  selector:
    secret:
      name: home-tls
  template:
    engineVersion: v2
    data:
      tls.crt: '{{ index . "tls.crt" | b64enc }}'
      tls.key: '{{ index . "tls.key" | b64enc }}'
  data:
    - match:
        secretKey: &key tls.crt
        remoteRef:
          remoteKey: home-tls
          property: *key
    - match:
        secretKey: &key tls.key
        remoteRef:
          remoteKey: home-tls
          property: *key
```

**Expected behavior**
I expected my PushSecret to continue updating.

**Additional context**
I have downgraded for now back to [v0.13.0](https://github.com/external-secrets/external-secrets/releases/tag/v0.13.0), and it immediately started updating again.
