### ISSUE TITLE
Support for GCP regional Secrets

### ISSUE THREAD

**Issue by timrhomberg** [external-secrets/external-secrets#4416]
**Is your feature request related to a problem? Please describe.**
I can't use currently GCP Regional Secrets. It would be great if we could add the functionality.

**Describe the solution you'd like**
There seems to be an official documentation on how to address regional secrets. It would be great if we could add to the SecretStore an parameter like region: europe-west1 and then it will look for secrets only in this area.
https://cloud.google.com/secret-manager/regional-secrets/create-regional-secret?hl=de#create-secret-go

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by Skarlso** [comment]
That's literally the location you are looking for.

```yaml
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gcp-secret-store
spec:
  provider:
    gcpsm:
      projectID: my-project
      location: us-east1  # Specify a single location
```

**Comment by timrhomberg** [comment]
@Skarlso Still doesn't work. I assume the problem is, that the variable location isn't used where it supposed to. In the file pkg/provider/gcp/secretmanager/client.go is the function GetSecret. On line 484 we see the following:
`		Name: fmt.Sprintf("projects/%s/secrets/%s/versions/%s", c.store.ProjectID, ref.Key, version),`

But should they not also make a second request for regional secrets like this one 
`		Name: fmt.Sprintf("projects/%s/locations/%s/secrets/%s/versions/%s", c.store.ProjectID, c.store.location, ref.Key, version),`

**Comment by Skarlso** [comment]
You can prefix it I think with the `clusterLocation`?

**Comment by Skarlso** [comment]
It's in the workload identity section:

```yaml
      auth:
        workloadIdentity:
          # name of the cluster Location, region or zone
          clusterLocation: europe-central2
```

Maaaaybe that works. 🤔
