### ISSUE TITLE
Panic in externalsecret_controller due to an incorrect key in the spec.dataFrom

### ISSUE THREAD

**Issue by sboschman** [external-secrets/external-secrets#4421]
**Describe the bug**
After upgrading from 0.13.0 to 0.14.0 we see the external secrets controller throwing a panic if a provider cannot find the defined secret and returns a `esv1beta1.NoSecretErr` error. The code path seems to suggest a panic in the new 0.14.0 Stateful Generators impl.

With 0.13.0 the error from the provider that the secret cannot be found is reported on the ExternalSecret resource:
```
status:
  conditions:
    - lastTransitionTime: '2025-02-12T17:47:57Z'
      message: could not get secret data from provider
      reason: SecretSyncedError
      status: 'False'
      type: Ready
```

together with an event:
```
Reason: UpdateFailed
Message: error processing spec.dataFrom[0].extract, err: Secret does not exists
```

With 0.14.0 there is nothing reported on the ExternalSecret manifest, no status field and no event, but the controller log shows a panic.

**To Reproduce**
1. provide all relevant manifests
```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
...
spec:
  ...
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: this_key_does_not_exist_because_a_typo_was_made
        metadataPolicy: None
      rewrite:
        - regexp:
            source: xxx
            target: XXX
```

2. provide the Kubernetes and ESO version
k8s 1.30.8 and ESO 0.14.0

3. stacktrace
```
invalid memory address or nil pointer dereference
pkg/generator/statemanager.(*Manager).Rollback (pkg/generator/statemanager/statemanager.go:80)
pkg/controllers/externalsecret.(*Reconciler).getProviderSecretData.func1 (pkg/controllers/externalsecret/externalsecret_controller_secret.go:55)
pkg/controllers/externalsecret.(*Reconciler).getProviderSecretData (pkg/controllers/externalsecret/externalsecret_controller_secret.go:90)
pkg/controllers/externalsecret.(*Reconciler).Reconcile (pkg/controllers/externalsecret/externalsecret_controller.go:327)
```

4. Provider impl, the `handleExtractSecrets` method calls the `GetSecretMap` method on the provider
```
func (c *client) GetSecretMap(...) (map[string][]byte, error) {
 ...
 // Do provider stuff, but `ref.Key` cannot be found
 return nil, esv1beta1.NoSecretErr
}
```

**Expected behavior**
Same behaviour as with 0.13.0, no panic in the controller log and a ExternalResource with status and event indicating there is an error with getting the secret.
