### ISSUE TITLE
Metrics services not created if certManager is enabled

### ISSUE THREAD

**Issue by alexanderldavis** [external-secrets/external-secrets#4429]
**Describe the bug**

The "-metrics" Services used by the ServiceMonitors are not being created if `.Values.webhook.certManager.enabled` is set to `true`. This seems like a regression introduced by https://github.com/external-secrets/external-secrets/pull/4356.

On `v0.13.0` of the external-secrets chart, we were creating the `external-secrets-cert-controller-metrics` and `external-secrets-webhook-metrics` services simply by setting `.Values.serviceMonitor.enabled=true`.

The PR linked above changed the logic to create the services to include `(not .Values.webhook.certManager.enabled)` as a requirement. In our configuration, we have `.Values.webhook.certManager.enabled=true`, so the services are being erroneously deleted.

**To Reproduce**

Relevant `values`:

```yaml
serviceMonitor:
  enabled: true

certController:
  metrics:
    service:
      enabled: true

webhook:
  certManager:
    enabled: true # <- By setting certManager.enabled=true, Services are not created for the ServiceMonitors despite serviceMonitor.enabled=true, above
    cert:
      issuerRef:
        name: self-signed-ca-issuer
  metrics:
    service:
      enabled: true
```

Kubernetes version: `v1.30.8`
ESO: `v0.14.2`

**Expected behavior**

Setting the following should create the ServiceMonitors and appropriate Services, even if `webhook.certManager.enabled=true`.

```yaml
serviceMonitor:
  enabled: true
```
