### ISSUE TITLE
'unable to validate store: invalid vault credentials: context deadline exceded'

### ISSUE THREAD

**Issue by 7899945307** [external-secrets/external-secrets#4445]
my cluster secret store is 

```
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  generation: 1
  name: vault-backend
spec:
  provider:
    vault:
      auth:
        tokenSecretRef:
          key: token
          name: vault-token
          namespace: external-secrets
      path: Test-Secret
      server: https://vault-test-server:443/
      version: v2
status:
  conditions:
  - lastTransitionTime: "2025-02-18T05:36:01Z"
    message: 'unable to validate store: invalid vault credentials: context deadline
      exceeded'
    reason: ValidationFailed
    status: "False"
    type: Ready


------- ----->     My secret token is here <--------------------

apiVersion: v1
data:
  token: Lmjhfuyhgujhiokuhlhkhbkdujgiyhgdkjugkjdbkljbhkujhnfddqjhvjyhgeqiyhgikujhbhwdjkhgjyhgdkugkywfk,jbx,jbkjedhvnmjvgdRkSEk=
kind: Secret
metadata:
  name: vault-token
  namespace: external-secrets
type: Opaque
```

My secret token is here 

Any solution please
As i have tested token by decoding it and its working fine by doing curl to the Vault url  but when it comes to external secrets it giving me this error in the external-secret pod logs 

{"level":"error","ts":13656553876,"msg":"Reconciler error","controller":"clustersecretstore","controllerGroup":"external-secrets.io","controllerKind":"ClusterSecretStore","ClusterSecretStore":{"name":"vault-backend"},"namespace":"","name":"vault-backend","reconcileID":"dwugfutgvf-edgvd","error":"could not validate provider: invalid vault credentials: context deadline exceeded","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.1/pkg/internal/controller/controller.go:341\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.1/pkg/internal/controller/controller.go:288\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.1/pkg/internal/controller/controller.go:249"}

and the status is like 

Events:
  Type     Reason            Age                  From                  Message
  ----     ------            ----                 ----                  -------
  Warning  ValidationFailed  2m30s (x7 over 41m)  cluster-secret-store  invalid vault credentials: context deadline exceeded
