### ISSUE TITLE
Experimental AWS session cache issue in case of cross-account assumed roles

### ISSUE THREAD

**Issue by imunhatep** [external-secrets/external-secrets#4455]
**Describe the bug**
Enabling argument `--experimental-enable-aws-session-cache=true` and using cross account CSS with assuming role results in failed authentications.
Disabling it results in all secrets updated without issues.

**To Reproduce**
 - enable `--experimental-enable-aws-session-cache=true` 
 - add a few CSS with cross-account and cross region AWS SecretsManager providers.

**Expected behavior**
ESO properly cache sessions and does not try to assume role from already assumed session.

**Additional context**
Error:
```
error retrieving secret at .data[0], key: externalsecret-name-replaced, err: AccessDenied: User: arn:aws:sts::1234567890:assumed-role/target-iam-role/1740057294654071001 is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::1234567890:role/target-iam-role\n\tstatus code: 403,
```

ESO version: v0.10.4

**Comment by moolen** [comment]
Oh, and please also post the ExternalSecret. Do you use an ECR or STS generator?

**Comment by imunhatep** [comment]
Note we have several CSS defined per account and per region. 

CSS
```yaml
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  labels:
    app.kubernetes.io/instance: instance-name
  name: aws-css-eu-north-1
spec:
  provider:
    aws:
      region: eu-north-1
      role: arn:aws:iam::1234567890:role/external-secrets-target-role
      service: SecretsManager
```

ExternalSecret
```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
  labels:
    app.kubernetes.io/instance: external-secret-example
  name: external-secret-example
  namespace: default
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: some-secret-key
      metadataPolicy: None
      property: SECRET_VAR
    secretKey: SECRET_VAR
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-css-eu-north-1
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: external-secret-example-envs
```

**Comment by imunhatep** [comment]
> Do you use an ECR or STS generator?
Sorry.. generator? for what?

**Comment by moolen** [comment]
Nevermind the generator, that's not relevant i think.

I was able to make it work with the manifests below. All CSS and ES sync up and store the value as expected.

I assume you use IRSA (or pod identity) to give ESO permissions to AWS services. Can you share the role and trust policy?

From the error message above it seems that we're not allowed to assume the role that we already have. Is this intentional?

```yaml
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  labels:
    app.kubernetes.io/instance: instance-name
  name: aws-css-eu-north-1
spec:
  provider:
    aws:
      region: eu-north-1
      role: arn:aws:iam::123412341234:role/admin
      service: SecretsManager
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  labels:
    app.kubernetes.io/instance: instance-name
  name: aws-css-eu-west-1
spec:
  provider:
    aws:
      region: eu-west-1
      role: arn:aws:iam::123412341234:role/admin
      service: SecretsManager
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
  labels:
    app.kubernetes.io/instance: external-secret-example
  name: external-secret-example-west-1
  namespace: default
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: some-secret-key
    secretKey: SECRET_VAR
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-css-eu-west-1
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: external-secret-example-west-1
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
  labels:
    app.kubernetes.io/instance: external-secret-example
  name: external-secret-example-north-1
  namespace: default
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: some-secret-key
    secretKey: SECRET_VAR
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-css-eu-north-1
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: external-secret-example-north-1

```
