### ISSUE TITLE
Vault LDAP auth does not handle enterprise namespaces

### ISSUE THREAD

**Issue by yabberyabber** [external-secrets/external-secrets#4460]
**Describe the bug**
When using the LDAP auth provider with the VaultDynamicSecret CRD, there is no way to authenticate to anything other than the root namespace.

It looks like the CRD makes a request to `v1/auth/ldap/login/${USERNAME}` but with enterprise namespaces, one would need to put the namespace in the path like so `v1/${NAMESPACE}/auth/ldap/login/${USERNAME}`.

There is a `path` attribute that you can set, but this gets injected in the wrong spot. The `Path` attribute, if set, goes here: `v1/auth/${PATH}/login/${USERNAME}`

**To Reproduce**

```
apiVersion: generators.external-secrets.io/v1alpha1
kind: VaultDynamicSecret
metadata:
  name: demo-vaultdynamicsecret
  namespace: example
spec:
  method: GET
  path: /my-example-namespace/gpg/export/srv-example
  #     |--------------------| this is the namespace in the 2nd post-auth request
  provider:
    auth:
      ldap:
        # Need to be able to specify `my-example-namespace` here somewhere
        # so that we can authenticate into that namespace.
        secretRef:
          key: example-pass-secret
          name: example-pass-secret
        username: srv-example
    server: http://vault.example:8200
    version: v2
  resultType: Data
```

**Expected behavior**
I would expect the CRD to accept either a `Namespace` argument (which gets injected before `auth` in the reques tpath), or an `AdditionalHTTPHeaders` (which gets send in the ldap auth request as an alternate way to specify the namespace)

**Additional context**
It looks like the underlying API that the external-secrets operator is using in the vault repo does not accept a namespace argument either ref https://github.com/hashicorp/vault/issues/29688 --- so adding it to the CRD may be blocked on adding support to the underlying API.

I'm happy to submit the PR that adds support for this if a repo maintainer thinks this is a reasonable assessment of the problem and a reasonable solution.
