### ISSUE TITLE
Vault provider with TokenApi toggles ready status on controller restart

### ISSUE THREAD

**Issue by jmmclean** [external-secrets/external-secrets#4461]
**Describe the bug**
When using a Vault provider for a SecretStore, configured as below (redacted some info), the SecretStore will flip between ready=true and ready=false upon the restart of the external-secrets controller
```
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-prod
  namespace: external-secrets
spec:
  provider:
    vault:
      server: "https://prod.vault.mycompany.com"
      path: "clusters/my-cluster"
      namespace: "my-namespace"
      version: "v2"
      auth:
        jwt:
          path: "jwt/my-cluster"
          role: "admin"
          kubernetesServiceAccountToken:
            serviceAccountRef:
              name: "external-secrets"
              audiences:
              - https://prod.vault.my-company.com
```

**To Reproduce**
1. Create a SecretStore CR that has access to Vault using a configuration similar to the above (specifically where the SA token is generated by ESO)
2. while having a terminal running `kubectl get secretstore -w`, do a rolling restart in a different terminal for the eso controller as such - `kubectl rollout restart deploy external-secrets`
3. The secret store will flip between ready and not ready when the ESO controller restarts

The below content shows results from bouncing the ESO controller
```
> k get secretstore -A -w
NAMESPACE          NAME         AGE   STATUS   CAPABILITIES   READY
external-secrets   vault-prod   0s
external-secrets   vault-prod   0s    Valid    ReadWrite      True
external-secrets   vault-prod   36s   InvalidProviderConfig   ReadWrite      False
external-secrets   vault-prod   69s   Valid                   ReadWrite      True
external-secrets   vault-prod   3m1s   Valid                   ReadWrite      True
external-secrets   vault-prod   3m29s   InvalidProviderConfig   ReadWrite      False
external-secrets   vault-prod   4m24s   Valid                   ReadWrite      True
```

version: 0.14.2 (also experience on 0.10.4, but upgraded in hopes of a fix)

**Expected behavior**
The SecretStore status is retained after a restart of the ESO controller.
