### ISSUE TITLE
PushSecrets (with multiple secrets) to Azure Keyvaults

### ISSUE THREAD

**Issue by perpective2410** [external-secrets/external-secrets#4510]
Hello.

I am trying to push a kubernetes secret containing 2 keys (tls.crt, and tls.key) to Azure Keyvault inside a Azure Secret.
It looks like that only the content of tls.key is pushed to Azure Keyvault. It also looks like its creating the secrets in keyvault in a loop. Is there anything obvious that Im missing?

Here is the configuration

```
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: elastic-stack-mgmt-es-transport-ca-internal
  namespace: elastic-stack
spec:
  refreshInterval: 1m
  deletionPolicy: Delete
  secretStoreRefs:
    - name: mgmt-kv
      kind: ClusterSecretStore
  selector:
    secret:
      name: elasticsearch-es-transport-ca-internal
  template:
    engineVersion: v2
    data:
      tls.crt: '{{ index . "tls.crt" }}'
      tls.key: '{{ index . "tls.key" }}'
  data:
    - match:
        secretKey: tls.crt
        remoteRef:
          remoteKey: elasticsearch-es-transport-ca-internal
          property: tls.crt

    - match:
        secretKey: tls.key
        remoteRef:
          remoteKey: elasticsearch-es-transport-ca-internal
          property: tls.key
```

The kubernetes secrets called 'elasticsearch-es-transport-ca-internal' looks like this

```
tls.crt: |                                                           
  -----BEGIN CERTIFICATE-----                                        
  xxxxx   
  -----END CERTIFICATE-----                                          
tls.key: |                                                           
  -----BEGIN RSA PRIVATE KEY-----
 yyyy
  -----END RSA PRIVATE KEY-----    
```
