### ISSUE TITLE
Can External secret transform the key?

### ISSUE THREAD

**Issue by perpective2410** [external-secrets/external-secrets#4513]
Is there a a way to configure external secret to support the following scenario?
Scenario: upper case the kubernetes secret key prefixed with KV_

**Scenario:**
Azure Keyvault secret: foo-bar
Kubernetes Secret name: foo-bar
Content of the Kubernetes Secret: 
  KV_FOO_BAR: |
   <content of azure keyvault secret)

**Comment by Skarlso** [comment]
Yes. Take a look at templating. https://external-secrets.io/latest/guides/templating/

**Comment by gusfcarvalho** [comment]
Hi @perpective2410 ! I don't think `data` is really the appropriate call for you to do these rewrites, as effectively you still need to add each key manually. (btw, just adding to the secretKey `KV_FOO_BAR` should work, you need no templating there).

If you still want to do it, you should check `templateFrom.literal`, which allows you to create templating expressions for both keys and values.

**Comment by kivagant-ba** [comment]
@perpective2410 , I bet you are looking for something like this:
```yaml
spec:
  dataFrom:
  - find: # use any FIND rules you need in your case
      conversionStrategy: Default
      decodingStrategy: None
      tags:
        myapp: true
    rewrite:
# VARIANT 1:
    - transform:
        template: '{{ .value | upper | replace "-" "_" }}'

# VARIANT 2:
    - regexp:
        source: '[^a-zA-Z0-9_]'
        target: '_' # \U is not supported in golang, so we need to transform
      transform:
        template: '{{ .value | upper }}'
```

Source: https://github.com/external-secrets/external-secrets/pull/2802
