### ISSUE TITLE
Error while pulling multiple secrets from a path in aws parameter store

### ISSUE THREAD

**Issue by JayaHariniR** [external-secrets/external-secrets#4526]
**Describe the bug**
Error while pulling multiple secrets from a path in aws parameter store 
`ValidationException: Parameter name: can't be prefixed with \"ssm\" (case-insensitive). If formed as a path, it can consist of sub-paths divided by slash symbol; each sub-path can be formed as a mix of letters, numbers and the following 3 symbols .-_\n\tstatus code: 400,`

**To Reproduce**
1. provide all relevant manifests
2. provide the Kubernetes and ESO version
````
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.name }}
  namespace: {{ .Values.externalSecret.namespace }}
spec:
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.externalSecret.target.name }}
 dataFrom:
    - extract:
        key: "/xyz/"
```
versions:
EKS:1.30
ESO:v0.14.3

**Expected behavior**
it should create a secret with all the parameters in the path

**Comment by gusfcarvalho** [comment]
hi @JayaHariniR . `dataFrom.extract` does not support regular expressions, meaning your manifests are wrong. what are you trying to achieve here?

**Comment by JayaHariniR** [comment]
There are multiple secrets in aws parameter store in path /xyx/ .Is there a way instead of adding them in yaml files separately

**Comment by jarpoole** [comment]
> There are multiple secrets in aws parameter store in path /xyx/ .Is there a way instead of adding them in yaml files separately

@JayaHariniR did you end up figuring out how to get this to work? I would love to avoid listing out every secret also...

**Comment by gusfcarvalho** [comment]
https://external-secrets.io/latest/guides/getallsecrets/ you should check this reference @jarpoole

**Comment by jarpoole** [comment]
Thank you so much for the quick reply, that resource was very helpful! 

In my case, the issue turned out to be that I had specified `find.path` but not `find.name.regex`. For any future readers getting stuck here, a working configuration is:

```
  dataFrom:
    - find:
        path: /app/runtime/
        name:
          regexp: '.*'
      rewrite:
        - regexp:
            source: '^/app/runtime/(.*)$'
            target: '$1'
```
