### ISSUE TITLE
Generate multiple passwords in a PushSecret

### ISSUE THREAD

**Issue by codrutpanea** [external-secrets/external-secrets#4537]
**Is your feature request related to a problem? Please describe.**
The Password generator in a PushSecret can only create a single password. I need to create a PushSecret that can generate multiple passwords.

Right now to create a single password i use the following PushSecret:
```yaml
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: my-secret
spec:
  selector:
    generatorRef:
      apiVersion: generators.external-secrets.io/v1alpha1
      kind: Password
      name: strong-password
  data:
    - match:
        secretKey: password
        remoteRef:
          remoteKey: my-secret
 ```

But i need to create multiple passwords in the same PushSecret and right now it's not possible because in the selector we can only use a single`generatorRef` and the Password generator can only create a single password.

**Describe the solution you'd like**
I need to generate multiple passwords using the same PushSecret.

A solution would be to generate multiple passwords using the same Password generator like:

```yaml
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: strong-password
spec:
  length: 32
  digits: 5
  symbols: 5
  symbolCharacters: "-_$@"
  noUpper: false
  allowRepeat: true
    # the password keys to generate
  passwords:
    - first-password
    - second-password
    - etc
```
and now i could use the PushSecret like
```yaml
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: my-secret
spec:
  selector:
    generatorRef:
      apiVersion: generators.external-secrets.io/v1alpha1
      kind: Password
      name: strong-password
  template:
    data:
      test: |-
        {
          "firstPassword": "{{ .first-password }}",
          "secondPassword": "{{ .second-password }}"
        }
  data:
    - match:
        secretKey: test
        remoteRef:
          remoteKey: my-secret
 ```

**Comment by Skarlso** [comment]
Hello!

I distinctly remember someone doing just that where they generate multiple passwords. I will find the ticket for you in the morning. Just commenting to remind myself. 🙂

**Comment by Skarlso** [comment]
Okay, so something like this should work:
```yaml
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: mariadb-galera-secrets
  namespace: {{ include "common.names.namespace" . | quote }}
spec:
  length: 20
  digits: 10
  symbols: 0
  allowRepeat: true
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mariadb-galera-secrets
  namespace: {{ include "common.names.namespace" . | quote }}
spec:
  refreshInterval: 0s
  target:
    name: mariadb-galera-secrets
  dataFrom:
  - sourceRef:
       generatorRef:
         apiVersion: generators.external-secrets.io/v1alpha1
         kind: Password
         name: mariadb-galera-secrets
    rewrite:
    - regexp:
        source: "(.*)"
        target: "mariadb-root-password"
  - sourceRef:
       generatorRef:
         apiVersion: generators.external-secrets.io/v1alpha1
         kind: Password
         name: mariadb-galera-secrets
    rewrite:
    - regexp:
        source: "(.*)"
        target: "mariadb-galera-secret-backup"
```

**Comment by Skarlso** [comment]
Oh but this is externalsecret. I have to check if the same goes for PushSecret.

**Comment by Skarlso** [comment]
ah, yes. Sadly, this isn't possible with PushSecret it seems, because I can't reference the same generator twice like in ES... :/

**Comment by codrutpanea** [comment]
@Skarlso  I noticed you added this to the 0.15.0 milestone. Will the implementation involve modifying the PushSecret object or the Password object?
Maybe changing the Password object to generate multiple keys is the better approach since it can be used in a PushSecret and also in ExternalSecret, and it will look more elegant than the `rewrite` solution.

Being able to do something like:
```yaml
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: strong-password
spec:
  length: 32
  digits: 5
  symbols: 5
  symbolCharacters: "-_$@"
  noUpper: false
  allowRepeat: true
    # the password keys to generate
  secretKeys:
    - first-password
    - second-password
    - etc
```
