### ISSUE TITLE
Passing '{{' and '}}' through ESO

### ISSUE THREAD

**Issue by gaima8** [external-secrets/external-secrets#4544]
I have a JSON string in a ConfigMap using an ExternalSecret to template in some secrets. All entirely normal.

```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configjson-eso-template
data:
 configjson.json:
    "{\"secret\": \"{{ .clientSecret }}\"}"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: configjson-config
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: secretstore
  target:
    name: configjson-config
    template:
      engineVersion: v2
      templateFrom:
        - target: Data
          configMap:
            name: configjson-eso-template
            items:
              - key: configjson.json
                templateAs: Values
  data:
    - remoteRef:
        key: 'client1-clientSecret'
      secretKey: clientSecret
```

I now need to have another element in the JSON that needs to be the literal string '{{otherValue}}'.
No amount of weird extra quoting or escaping is letting me get that past ESO. I either get some sort of parsing failure, unexpected characters, or an invalid string in the resulting secret.

Using three, instead of two, curly braces results in: `unexpected "{" in command`.
A single backslash on all four curly braces is illegal for kubernetes.
Two backslashes on all four curly braces is legal, and passes ESO, but the resulting string is `\{\{otherValue\}\}` which isn't legal to the container parsing the JSON.
`'{{'otherValue'}}'`, and not trying to escape `otherValue`, just results in ESO trying to go-template it, which obviously fails because ESO can't do that.

How do I make ESO ignore something in mustaches?

**Comment by Skarlso** [comment]
Huh, this is a tough one.

**Comment by gaima8** [comment]
> Huh, this is a tough one.

Thanks! ;)

I'm not done with fully working out this, or even a, solution, but by quitting time Friday I did come up with the idea of using a fake secret store to hold the actual mustache values and including ESO parsable references to them in the template.
Helm gets to parse something, and ESO gets to parse something, with ESO printing out the value our container needs, but without having to deal with writing genuinely not-secret plain strings into an actual secret manager.

```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configjson-eso-template
data:
 configjson.json:
    "{\"secret\": \"{{ .clientSecret }}\", \"specialValue\": \"{{ .fakeMustacheValue }}\"}"
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: configjson-fake
spec:
  provider:
    fake:
      data: 
        - key: "mustacheValue"
          value: "{{otherValue}}"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: configjson-config
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: secretstore
  target:
    name: configjson-config
    template:
      engineVersion: v2
      templateFrom:
        - target: Data
          configMap:
            name: configjson-eso-template
            items:
              - key: configjson.json
                templateAs: Values
  data:
    - remoteRef:
        key: 'client1-clientSecret'
      secretKey: clientSecret
    - remoteRef:
        key: 'mustacheValue'
      secretKey: fakeMustacheValue
      sourceRef:
        storeRef:
          kind: SecretStore
          name: configjson-fake
```
