### ISSUE TITLE
PushSecret errors with UUID generator

### ISSUE THREAD

**Issue by druchoo** [external-secrets/external-secrets#4546]
**Describe the bug**
`kind: PushSecret` errors with `could not get source secret` when using `kind: UUID` generator.

**To Reproduce**
1. relevant manifests
```
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: UUID
metadata:
  name: uuid

---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: my-push-secret
spec:
  data:
    - match:
        remoteRef:
          remoteKey: my-push-secret
        secretKey: uuid
      metadata:
        secretPushFormat: string
  secretStoreRefs:
    - kind: ClusterSecretStore
      name: aws-sm
  selector:
    generatorRef:
      apiVersion: external-secrets.io/v1alpha1
      kind: UUID
      name: uuid
```

2. Kubernetes and ESO version
Kubernetes: EKS 1.30
ESO: v0.14.4

**Expected behavior**
The PushSecret should successfully reconcile when using the UUID generator.

**Additional context**
A PushSecret with a similar manifest (change generatorRef and secretKey) using `Fake`, `ECRAuthorizationToken` and `Password` generators all successfully reconcile.
