### ISSUE TITLE
"property: value" doesn't work unless used in "template:"

### ISSUE THREAD

**Issue by apidhoro** [external-secrets/external-secrets#4613]
**Describe the bug**

Consider the following example:
```
...
    template:
      engineVersion: v2
      data:
        options.json: |
          {
            "api-key": "{{`{{ .API_KEY }}`}}",
          }
  data:
  - secretKey: API_KEY
    remoteRef:
      key: /api_key
      property: value
  - secretKey: SSH_KEY
    remoteRef:
      key: /ssh_key
      property: value
```
Data in `/api_key`, `/ssh_key` is stored as JSON of the following format `{"value":"data"}`

The problem:
if you `kubectl get secret target-secret -o jsonpath="{.data.SSH_KEY}" | base64 --decode`
you'll get `{"value":"ssh key data"}`

though doing the same for `API_KEY` will give you plain text with data, as expected.

To workaround this you have to use `SSH_KEY` in templating as well:
```
...
        SSH_KEY_FILE: |
         {{`{{ .SSH_KEY }}`}}
...
```

**To Reproduce**
Use the following definition, execute `kubectl get secret target-secret -o jsonpath="{.data.SSH_KEY}" | base64 --decode`
```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: eso-secrets
  namespace: default
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: eso-secrets-store
    kind: SecretStore
  target:
    name: target-secret
    template:
      engineVersion: v2
      data:
        options.json: |
          {
            "api-key": "{{`{{ .API_KEY }}`}}",
          }
  data:
  - secretKey: API_KEY
    remoteRef:
      key: /api_key
      property: value
  - secretKey: SSH_KEY
    remoteRef:
      key: /ssh_key
      property: value
```
K8s version: 1.30
ESO version: 0.9.20

**Expected behavior**
`SSH_KEY` is also given as a plain text (as expected by using `"property:"`) even if not used in templating.
