### ISSUE TITLE
CRDs need updating to support recent change in gcpsm auth provider

### ISSUE THREAD

**Issue by jbehrends** [external-secrets/external-secrets#4616]
**Describe the bug**
This PR brought an enhancement to the GCPSM auth provider so that Google Workload Identity values could automatically be looked up vs defining them. 
https://github.com/external-secrets/external-secrets/pull/4575

However, the CRDs for a **secretstore** and **clustersecretstore** were not updated.  Values which were required are no longer required.  So currently you are not able to take advantage of this enhancement because you are blocked by the CRD still requiring the values to be set.

**To Reproduce**
Install version 0.15.1 using Helm.

Define a secretstore:
```
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: test-secretstore
  namespace: testing
spec:
  provider:
    gcpsm:
      projectID: myproject-12345
      auth:
        workloadIdentity:
          serviceAccountRef:
            name: test
```
Then apply the secretstore:
```
$ kubectl apply -f ./secretstore.yaml
The SecretStore "test-secretstore" is invalid:
* spec.provider.gcpsm.auth.workloadIdentity.clusterLocation: Required value
* spec.provider.gcpsm.auth.workloadIdentity.clusterName: Required value
$
```

**Expected behavior**
The above secretstore should be able to be applied without defining clusterLocation or clusterName

I believe this needs to be fixed for both secretstore and clustersecretstore CRDs.
