### ISSUE TITLE
Can ClusterPushSecret be used to push multiple secrets?

### ISSUE THREAD

**Issue by murphm54** [external-secrets/external-secrets#4627]
Hi,

I am trying to use ClusterPushSecret to sync multiple secrets based on label to azure keyvault. My primary use for this is syncing multiple kafka user/connection details generated by strimzi to keyvault. My understanding was that this could be solved with #4162. However, I am not sure I am using it correctly. Please see my configuration below: 

```
apiVersion: external-secrets.io/v1alpha1
kind: ClusterPushSecret
metadata:
  name: "kafka-users-clusterpushsecret" # Customisable
spec:
  # The name to be used on the PushSecrets
  pushSecretName: "kafka-users-ps"

  # This is a list of basic label selector to select the namespaces to deploy PushSecrets to.
  # you can read more about them here https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#resources-that-support-set-based-requirements
  # The list is OR'd together, so if any of the namespaceSelectors match the namespace,
  # the ExternalSecret will be deployed to that namespace.
  namespaceSelectors:
  - matchLabels:
      kubernetes.io/metadata.name: external-secrets

  # How often the ClusterPushSecret should reconcile itself
  # This will decide how often to check and make sure that the PushSecrets exist in the matching namespaces
  refreshTime: "1m"

  # This is the spec of the PushSecrets to be created
  # The content of this was taken from our PushSecret example
  pushSecretSpec:
    updatePolicy: Replace # Policy to overwrite existing secrets in the provider on sync
    deletionPolicy: Delete # the provider' secret will be deleted if the PushSecret is deleted
    refreshInterval: 1h # Refresh interval for which push secret will reconcile
    secretStoreRefs: # A list of secret stores to push secrets to
      - name: azure-keyvault # Name of the secret store
        kind: SecretStore
    selector:
      secret:
        selector:
          matchLabels:
            strimzi.io/kind: KafkaUser
    data:
      - match:
          secretKey: password # Source Kubernetes secret key to be pushed
          remoteRef:
            remoteKey: kafka-user-password # Remote reference (where the secret is going to be pushed)
``` 

This does work in that it picks up a secret with the matchlabel and successfully syncs it but it has not picked up multiple secrets. Is it possible to sync multiple secrets with this configuration? I think the limitation is that remoteRef is static. 
Is it possible that this could  be dynamically generated based on the source secret name? Let me know if there is anything I'm missing or I can provide any more information. Thanks for your help.
