### ISSUE TITLE
Issue with cross-namespace serviceAccountRef in VaultDynamicSecret

### ISSUE THREAD

**Issue by DarthVaderRC** [external-secrets/external-secrets#4629]
**Description of the Issue:**

I am experiencing an issue with the `VaultDynamicSecret` resource in External Secrets Operator (ESO) where it fails to find a Kubernetes Service Account specified in the `spec.provider.auth.kubernetes.serviceAccountRef` when that Service Account resides in a different namespace.

**Expected Outcome:**

The `VaultDynamicSecret` resource should successfully authenticate to Vault using the Kubernetes auth method. The `spec.provider.auth.kubernetes.serviceAccountRef` in the `VaultDynamicSecret` manifest allows specifying the name and namespace of the Service Account to be used for authentication. Even if the `VaultDynamicSecret` is in a different namespace than the Service Account, it should be able to locate and use the specified Service Account for authentication with Vault.

**Actual Result:**

When I create a `VaultDynamicSecret` resource in the `external-secrets-consumer` namespace and configure its `spec.provider.auth.kubernetes.serviceAccountRef` to point to a Service Account named `external-secrets` in the `external-secrets` namespace, the ESO controller throws the following error:

`error processing spec.dataFrom[0].sourceRef.generatorRef, err: error using generator: unable to setup Vault client: cannot request Kubernetes service account token for service account "external-secrets": cannot get Kubernetes service account "external-secrets": ServiceAccount "external-secrets" not found`

The error indicates that the controller is looking for the `external-secrets` Service Account in the `external-secrets-consumer` namespace (where the `VaultDynamicSecret` is), even though the manifest explicitly specifies the namespace as `external-secrets`.

**Workaround:**

I have been able to get around this issue by creating a Service Account named "external-secrets" in the `external-secrets-consumer` namespace. This suggests that the controller is not correctly handling the cross-namespace reference in the `serviceAccountRef`. However, this approach doesn't align with the centralised authentication concept of ESO.

Example Manifests:

1. VaultDynamicSecret Manifest (in external-secrets-consumer namespace):
```
apiVersion: generators.external-secrets.io/v1alpha1
kind: VaultDynamicSecret
metadata:
  name: dynamic-postgres-secrets-consumer
  namespace: external-secrets-consumer
spec:
  allowEmptyResponse: false
  method: GET
  path: database/creds/my-postgres-db-role
  provider:
    auth:
      kubernetes:
        mountPath: kubernetes
        role: eso-role
        serviceAccountRef:
          name: external-secrets
          namespace: external-secrets # Service Account is in this namespace
    server: "http://vault-persistent-service.vault-namespace.svc.cluster.local:8200"
    version: v2
  resultType: Data
```
2. Relevant Part of the ESO Controller Deployment Manifest (in external-secrets namespace):
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  ... other spec ...
  template:
    spec:
      serviceAccountName: external-secrets
      containers:
        - name: external-secrets
          image: ghcr.io/external-secrets/external-secrets:v0.15.1
          args: [] # The --namespace argument has been removed
          ... other container spec ...
```

P.S. Issue details co-authored using GenAI.
