### ISSUE TITLE
GCP Secret Extraction Fails in v0.15.1: "Secret does not exist" Error (v0.15.0 Working)

### ISSUE THREAD

**Issue by janlauber** [external-secrets/external-secrets#4631]
**Describe the bug**  
When running ExternalSecrets version **v0.15.1** in our environment, the controller repeatedly logs an error when attempting to fetch secrets from GCP Secret Manager. Although the ClusterSecretStore appears healthy, the ExternalSecret resource fails with the error:  

```
error processing spec.dataFrom[0].extract, err: unable to access Secret from SecretManager Client: Secret does not exist
```

This error is absent with ExternalSecrets **v0.15.0**. We suspect the issue is linked to changes introduced in commit [[b6acfe8](https://github.com/external-secrets/external-secrets/commit/b6acfe84513626af55820c59821c8348fe2dd1b2)](https://github.com/external-secrets/external-secrets/commit/b6acfe84513626af55820c59821c8348fe2dd1b2). There could also be additional changes affecting secret extraction behavior. (just an assumption by going through what has been changed https://github.com/external-secrets/external-secrets/compare/v0.15.0...v0.15.1)

---

**To Reproduce**  
1. **Environment Setup:**  
   - Use a Kubernetes cluster with Workload Identity configured.  
   - Ensure that GCP Secret Manager contains a secret with the corresponding key (e.g., `your-secret-key`).

2. **Install ExternalSecrets v0.15.1:**  
   - Deploy the ExternalSecrets controller using version **v0.15.1**.

3. **Deploy ClusterSecretStore:**  
   Use a configuration similar to the following (with internal names replaced) (the service account has the role roles/secretmanager.admin):
   ```yaml
   apiVersion: external-secrets.io/v1beta1
   kind: ClusterSecretStore
   metadata:
     name: <your-clustersecretstore-name>
   spec:
     provider:
       gcpsm:
         auth:
           workloadIdentity:
             clusterLocation: <your-cluster-location>
             clusterName: <your-cluster-name>
             serviceAccountRef:
               name: <your-serviceaccount-name>
               namespace: <your-serviceaccount-namespace>
         location: <your-cluster-location>
         projectID: <your-gcp-project-id>
   ```
   
4. **Deploy ExternalSecret Resource:**  
   Create an ExternalSecret that references the secret by its key:
   ```yaml
   apiVersion: external-secrets.io/v1beta1
   kind: ExternalSecret
   metadata:
     name: <your-externalsecret-name>
     namespace: <your-namespace>
   spec:
     dataFrom:
       - extract:
           key: <your-secret-key>
           conversionStrategy: Default
           decodingStrategy: None
           metadataPolicy: None
     refreshInterval: 1h
     secretStoreRef:
       kind: ClusterSecretStore
       name: <your-clustersecretstore-name>
     target:
       name: <your-target-secret-name>
       creationPolicy: Owner
       deletionPolicy: Retain
   ```
   
5. **Observe:**  
   - Monitor the controller logs and the status of the ExternalSecret resource.  
   - The error message indicating that the secret cannot be found should appear repeatedly.

---

**Expected behavior**  
The ExternalSecret should fetch the secret data from GCP Secret Manager without error. After the ExternalSecret resource is applied, the corresponding Kubernetes Secret (with the specified target name) should be created and populated with the secret data from GCP.

---

**Screenshots**  
*(If applicable, attach screenshots of the relevant error logs or resource statuses to help illustrate the issue.)*

---

**Additional context**  
- **Version Comparison:** The issue appears only in ExternalSecrets **v0.15.1**; rolling back to **v0.15.0** resolves the error. This suggests that a change (possibly from commit [[b6acfe8](https://github.com/external-secrets/external-secrets/commit/b6acfe84513626af55820c59821c8348fe2dd1b2)](https://github.com/external-secrets/external-secrets/commit/b6acfe84513626af55820c59821c8348fe2dd1b2)) is responsible for the regression.  
- **Suspected Changes:** The commit may have altered the secret extraction or validation logic for GCP Secret Manager, causing a valid secret to be reported as missing.  
- **Versions:**  
  - Kubernetes: 1.30.9-gke
  - ExternalSecrets: v0.15.1 (exhibiting the bug) vs. v0.15.0 (working, v0.14.2 / v0.14.3 / v0.14.4 also working)  
- **Environment Details:**  
  - GCP Secret Manager is used in conjunction with Workload Identity.  
  - The ExternalSecret references the secret by key `<your-secret-key>`.  
- **Impact:** This issue prevents the automatic synchronization of secrets into Kubernetes, affecting deployments that depend on these secrets.

---

Please let me know if further details (logs, configuration excerpts, etc.) are needed. Any guidance on what might have changed in the secret extraction logic would be greatly appreciated.
