### ISSUE TITLE
Dynamically create a Kubernetes Secret from Multiple Secerts and apply a Template for each of the secrets

### ISSUE THREAD

**Issue by Nickelkette** [external-secrets/external-secrets#4643]
**Is your feature request related to a problem? Please describe.**
I am pulling multiple Secrets from my HashiCorp Vault with dataFrom.extract.key, now i want to apply a Template on each of those Secrets and create a Kubernetes Secret Property for each Secret. 

**Describe the solution you'd like**
I have 3 Secrets in my Vault called:
- secert_one.env
- secert_two.env
- secert_threee.env

In My External Secret i would like to do something like:

```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-env
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: app-env
    template:
      engineVersion: v2
      data:
        {{- range $secretName, $secretData := . }}
          {{ $secretName }}: |
          {{- range $k, $v := $secretData }}
            {{ $k }}="{{ $v }}"
          {{- end }}
        {{- end }}
  dataFrom:
      - extract:
        key: secret/data/my-app
```

Here i want that i get an Kubernetes Secret with multiple Properties (for each Secret one Property) something like:

```
apiVersion: v1
kind: Secret
metadata:
  name: vault-token
  namespace: innascor-services-staging
data:
  secert_one.env: some_data
  secert_two.env: some_data
  secert_threee.env: some_data
```

**Describe alternatives you've considered**
Maybe it is possible to write a template without an additional Key below the template.data Property
```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-env
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: app-env
    template:
      engineVersion: v2
      data:
        {{- range $k, $v := . }}
          {{ $k }}="{{ $v }}"
        {{- end }}
  dataFrom:
      - extract:
        key: secret/data/my-app
```
