### ISSUE TITLE
Suddenly failing in all clusters with no kind "ClusterSecretStore" is registered for version "external-secrets.io/v1"

### ISSUE THREAD

**Issue by WTPOptAxe** [external-secrets/external-secrets#4658]
**Describe the bug**
External Secrets operator suddenly failing in all clusters since roughly 14:50 BST. I believe that this because we deploy CRDs from a git repository with flux and the promotion of v1 has happened.

We're looking for a way to 
* downgrade these resources in the cluster
* pin the CRs to a specific branch or tag in the repo

Error being alerted is
```
ClusterSecretStore/external-secrets/external-secrets-store dry-run failed: conversion webhook for external-secrets.io/v1beta1, Kind=ClusterSecretStore failed: no kind "ClusterSecretStore" is registered for version "external-secrets.io/v1" in scheme "pkg/runtime/scheme.go:100"
```

Entry in log is 
```
{"level":"error","ts":1744638571.8916311,"logger":"controllers.ClusterSecretStore","msg":"unable to patch status: %w","clustersecretstore":{"name":"external-secrets-store"},"error":"conversion webhook for external-secrets.io/v1beta1, Kind=ClusterSecretStore failed: no kind \"ClusterSecretStore\" is registered for version \"external-secrets.io/v1\" in scheme \"pkg/runtime/scheme.go:100\"","stacktrace":"github.com/external-secrets/external-secrets/pkg/controllers/secretstore.reconcile.func1\n\t/home/runner/work/external-secrets/external-secrets/pkg/controllers/secretstore/common.go:66\ngithub.com/external-secrets/external-secrets/pkg/controllers/secretstore.reconcile\n\t/home/runner/work/external-secrets/external-secrets/pkg/controllers/secretstore/common.go:92\ngithub.com/external-secrets/external-secrets/pkg/controllers/secretstore.(*ClusterStoreReconciler).Reconcile\n\t/home/runner/work/external-secrets/external-secrets/pkg/controllers/secretstore/clustersecretstore_controller.go:66\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.1/pkg/internal/controller/controller.go:118\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.1/pkg/internal/controller/controller.go:328\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.1/pkg/internal/controller/controller.go:288\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.1/pkg/internal/controller/controller.go:249"}
```

**To Reproduce**
1. provide all relevant manifests

*Deployment CRs*
```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: external-secrets-crs
  namespace: flux-system
spec:
  dependsOn:
    - name: external-secrets-crds
  interval: 120m
  path: ./environments/gcpprojecect/flux-infra/external-secrets-operator/crs 
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
```

*HelmRelease*
```
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  releaseName: external-secrets
  targetNamespace: external-secrets
  interval: 10m
  chart:
    spec:
      chart: external-secrets
      version: 0.14.2
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
  values:
    installCRDs: false
    serviceAccount:
      create: true
      annotations:
        iam.gke.io/gcp-service-account: external-secrets-sa@gcpproject.iam.gserviceaccount.com
  install:
    createNamespace: true
```

*Repositories*
```
# ESO Helm Repo
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 120m
  url: https://charts.external-secrets.io
---
# ESO Git Repo
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: external-secrets
  namespace: flux-system
  annotations:
spec:
  interval: 120m
  ref:
    branch: main
  url: http://github.com/external-secrets/external-secrets

```

*ClusterSecretStore*
```
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  namespace: external-secrets 
  name: external-secrets-store
spec:
  provider:
    gcpsm:
      projectID: myproject
```

2. provide the Kubernetes and ESO version
ESO version is 0.14.2 installed via helm charts
Impacted cluster versions are
* 1.32.1-gke.1357001
* 1.32.2-gke.1297000

**Screenshots**

**Additional context**
This started happening simultaneously in 3 GCP clusters running 0.14.2 installed via helm charts. 
Impacted cluster versions are
* 1.32.1-gke.1357001
* 1.32.2-gke.1297000

Clusters have not had updates since March.
