### ISSUE TITLE
GitLab provider returns empty string for missing GitLab CI/CD variables

### ISSUE THREAD

**Issue by nmiekley** [external-secrets/external-secrets#4682]
**Describe the bug**
When referencing a GitLab CI/CD variable in remoteRef which does not exist or is not available to the configured environment, external-secrets-operator will treat it as existing with an empty string as value. 

This also means that if a GitLab CI/CD variable is deleted, the deletion policy is not honored and the secret is updated with an empty string.  

**To Reproduce**
1. Create a secretStore with a specific environment.
2. Create a GitLab CI/CD variable
  - Option A: with the wrong name, but correct environment
  - Option B: with the correct name, but wrong environment
  - Option C: with the correct name, correct environment and later delete it
3. Create an ExternalSecret referencing the variable.
  * The ExternalSecret is `Ready`. 
  * The generated secret does contain an empty string instead of the referenced credentials. 

**Expected behavior**
In both cases, I would expect an appropriate error (e.g. SecretSyncedError).

**Comment by gusfcarvalho** [comment]
Hi @nmiekley . Please share manifests for both the secretstore and the ExternalSecret as to reproduce this problem.. 

Also - does this problem happen if environments are not specified?

**Comment by nmiekley** [comment]
I just confirmed that it also happens without specifying an environment. I am using EOS  v0.16.1. 
Here are the manifests:

```yaml
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: default
spec:
  provider:
    gitlab:
      url: URL
      auth:
        SecretRef:
          accessToken:
            name: SECRET
            key: token
            namespace: NAMESPACE
      projectID: "123456"
      environment: ENVIRONMENT # exists in gitlab
  conditions:
    - namespaces:
        - default
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: test-secret
  namespace: default
spec:
  secretStoreRef:
    name: default
    kind: ClusterSecretStore
  refreshInterval: "1h"
  target:
    name: test_secret
  data:
    - secretKey: KEY
      remoteRef: 
        key: VARIABLE_NAME_IN_GITLAB
```
