### ISSUE TITLE
SecretStore prefix incompatibility with dataFrom

### ISSUE THREAD

**Issue by netguino** [external-secrets/external-secrets#4702]
**Describe the bug**
When adding a prefix to the SecretStore, said prefix is not applied when making queries based on a `dataFrom` spec.

**To Reproduce**

If one specifies the following SecretStore:
```
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: ssm
spec:
  provider:
    aws:
      prefix: /foo
      service: ParameterStore
      region: us-west-2
      auth:
        jwt:
          serviceAccountRef:
            name: serviceaccount
```
followed by an ExternalSecret like:
```
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test
  namespace: default
spec:
  secretStoreRef:
    name: ssm
    kind: SecretStore
  target:
    name: secrets
  dataFrom:
  - find:
      path: /mysecrets
      name:
        regexp: .*
```

Upon applying this, you can see that the prefix isn't added properly:

`permissions","path":"/mysecrets"}`

```
{"level":"info","ts":1745508481.2321577,"logger":"provider.parameterstore","msg":"GetParametersByPath: access denied. using fallback to describe parameters. It is recommended to add ssm:GetParametersByPath permissions","path":"/mysecrets"}
```

Versions:
`Server Version: v1.32.3-eks-d0fe756` + `helm-chart-0.16.1`

**Expected behavior**
Since the prefix is defined at SecretStore and not external secret, I would expect the prefix to be added resulting in:
`/foo/mysecrets`.

**Comment by gusfcarvalho** [comment]
Hi @netguino . IIRC - the use case for `prefix` is exactly when you can't use path for whatever the reason ('path' is actually better as it reduces the permissions scope needed for your SecretStore). Did you try using either one of the two (`path` or `prefix`) instead of them combined? Why do you need them combined? IMO, it seems you can do things just fine with standard 'path' logic

**Comment by netguino** [comment]
When I read the original discussion and implementation of `prefix`:  [issue](https://github.com/external-secrets/external-secrets/issues/1649) + [pr](https://github.com/external-secrets/external-secrets/pull/3718), it seems that the scenario was exactly what I had in mind.

Operators would set SecretStores for `/dev/`, `/prod`, `/test` etc,:

```
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: ssm
spec:
  provider:
    aws:
      prefix: /dev
      service: ParameterStore
      region: us-west-2
      auth:
        jwt:
          serviceAccountRef:
            name: serviceaccount
```
Then the `ExternalSecret` manifest is exactly the same alongside all environments, and can technically be distributed alongside the app and applied by the developer, where they don't care where the secret comes from, except that it belong to their app:

```
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test
  namespace: default
spec:
  secretStoreRef:
    name: ssm
    kind: SecretStore
  target:
    name: mysecrets
  dataFrom:
  - find:
      path: /myapp
      name:
        regexp: .*
```

At least that's what I was thinking.

**Comment by gusfcarvalho** [comment]
this incompatibility is for sure not a bug - as it wasn't part of the feature request. Plus, it is way more nuanced than you might think. `Path` triggers a completely different API set to be called (iirc more succeptible to rate limiting). IMO It should not be used as an alternative for users as a replacement for passing the prefixes in the regexp.


```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test
  namespace: default
spec:
  secretStoreRef:
    name: ssm
    kind: SecretStore
  target:
    name: mysecrets
  dataFrom:
  - find:
      name:
        regexp: "/myapp/.*"
```

should work as you intend it to.
