### ISSUE TITLE
PushSecret remoteRef remoteKey parameterized/templatized

### ISSUE THREAD

**Issue by pippitt** [external-secrets/external-secrets#4720]
**Is your feature request related to a problem? Please describe.**
I would like to use PushSecret to backup secrets based on a label (selector) to the same remoteKey name as the secret (.metatdata.name), and possibly the metadata.namespace
The label selector was [recently added](https://github.com/external-secrets/external-secrets/pull/4162).

Very similar to this comment https://github.com/external-secrets/external-secrets/issues/3183#issuecomment-2038639289

**Describe the solution you'd like**
Some mechanism to re-use the secret name (.metadata.name) as the remoteKey name, and possibly the namespace (.metadata.name), to avoid any collisions.
Example.
existing secrets created by service I would like to backup:
```
kubectl get secret -n systemx -l systemx-secrets-key=active
NAME                      TYPE                DATA   AGE
systemx-key2524p   kubernetes.io/tls   2      2y239d
systemx-key252gs   kubernetes.io/tls   2      2y149d
systemx-key2dqzw   kubernetes.io/tls   2      131d
systemx-key2g864   kubernetes.io/tls   2      159d
systemx-key2hfs2   kubernetes.io/tls   2      489d
systemx-key5jp5j   kubernetes.io/tls   2      249d
```

In this case each secret has 2 keys in data `tls.crt` and `tls.key`
Ideally a single PushSecret could create multiple secret in the external store based on something like:
```
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: backup-secret
  namespace: systemx
spec:
  data:
    - match:
        remoteRef:
          remoteKey:"{{.metadata.namespace}}-{{.metadata.name}}"
  deletionPolicy: None
  selector:
    secret:
      selector:
        matchLabels:
          systemx-secrets-key: active
  refreshInterval: 1h
  secretStoreRefs:
  - kind: ClusterSecretStore
    name: mysecretstore
```

**Describe alternatives you've considered**
Possibly a way to get at the .metadata.name in the template so multiple secrets (with multiple keys) could be backed up in a single remote secret, so would be json something like:
```
{
  "items": [
    {
      "data": {
        "tls.crt": "a",
        "tls.key": "b"
      },
      "name": "systemx-key2524p"
    },
    {
      "data": {
        "tls.crt": "c",
        "tls.key": "d"
      },
      "name": "systemx-key252gs"
    }
  ], 
...
}
```
