### ISSUE TITLE
Target template label keys that contain "." in their key, make ExternalSecrets fail silently

### ISSUE THREAD

**Issue by mr-pascal** [external-secrets/external-secrets#4723]
**Describe the bug**
When using target template labeling external secrets fail silently (not updating the K8s secret or creating it if it doesn't exists) when there is a `.` in the label key.

e.g. 
`konghq.com/credential` -> FAILS
`konghqcom/credential` -> WORKS

**To Reproduce**
Create a new ExternalSecret that has a `spec.target.template.metadata.labels` which contains a key with a `.` in it.

```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: xxx
  namespace: xxx
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: xxx
      version: latest
    secretKey: xxx
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: xxx
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: crawler-scheduler-auth-token
    template:
      engineVersion: v2
      mergePolicy: Replace
      metadata:
        labels:
          konghq.com/credential: key-auth # <- DOESN'T WORK, due to the `.`
```

**Expected behavior**
The label, containing a `.` in the label key should be added to the underlying K8s secret.
External secrets shouldn't fail silently

**Additional context**
We are currently running on external secrets version 0.9.4.

I checked the changelog of the newest version till ours, but couldn't find a related fix to this one.

I assume (just a gut feeling, no clue actually) the template engine tries to evaluate the `.` in the label key, but I don't know how to prevent this.
