### ISSUE TITLE
Bug in 1password provider documentation on external-secrets.io

### ISSUE THREAD

**Issue by stearz** [external-secrets/external-secrets#4728]
**Describe the bug**
The onepassword provider documentation (https://external-secrets.io/v0.5.7/provider-1password-automation/#setup-authentication) presents a faulty example for the `SecretStore`:

```
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: staging
spec:
  provider:
    onepassword:
      connectHost: https://onepassword-connect-staging
      vaults:
        staging: 1  # look in this vault first
        shared: 2   # next look in here. error if not found
      auth:
        secretRef:
        connectTokenSecretRef:
          name: onepassword-connect-token-staging
          key: token
```

There is an indentation error, here is a corrected version of that snippet:

```
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: staging
spec:
  provider:
    onepassword:
      connectHost: https://onepassword-connect-staging
      vaults:
        staging: 1  # look in this vault first
        shared: 2   # next look in here. error if not found
      auth:
        secretRef:                            # <- indentation underneath was wrong
          connectTokenSecretRef:
            name: onepassword-connect-token-staging
            key: token
```

I wasn't able to find the source of that documentation otherwise I would have opened a PR for this myself.

**To Reproduce**
Take a look at https://external-secrets.io/v0.5.7/provider-1password-automation/#setup-authentication and use the example SecretStore in your cluster... :)

**Expected behavior**
Example should be correct

**Screenshots**

![Image](https://github.com/user-attachments/assets/2c3bd7a3-95d7-47e1-94fa-172a0b2f45ac)

**Additional context**
n/a
