### ISSUE TITLE
PushSecret: push multiple properties at secret creation time instead of sending updates for each extra match.remoteRef.property

### ISSUE THREAD

**Issue by codrutpanea** [external-secrets/external-secrets#4746]
**Is your feature request related to a problem? Please describe.**
When pushing secrets in AWS Secrets Manager the controller creates the secret with the first `match` then updates the secret for each extra `match`. The problem with this approach is that we need permissions in AWS to update secrets. 

I can't give ExternalSecrets operator permissions to update secrets, I only need it to create the secrets once at cluster bootstrap, and never update them again.

**Describe the solution you'd like**
When pushing multiple keys like:
```yaml
  data:
    - match:
        secretKey: username
        remoteRef:
          remoteKey: db-credentials
          property: db-username
      metadata:
        secretPushFormat: string
    - match:
        secretKey: password
        remoteRef:
          remoteKey: db-credentials
          property: db-password
      metadata:
        secretPushFormat: string
```
I'd like all matches to be pushed at the same time when creating the secret instead of sending updates for each extra `match`.

**Comment by gusfcarvalho** [comment]
Hi @codrutpanea . This is already supported. Just don’t use multiple matches for individual properties and the whole secret should be pushed once.

**Comment by gusfcarvalho** [comment]
Re: the feature request itself; we cannot guarantee on runtime time that all matches will go for the same remote key, so I’m not sure it would be possible to achieve this. Specially since some matches might be property triggered, but some might not 🤔

**Comment by codrutpanea** [comment]
Thank you @gusfcarvalho so it was implemented in [#2862](https://github.com/external-secrets/external-secrets/pull/2862)

This is what i did to push a generated password along with the username:
```yaml
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: postgres-credentials
spec:
  refreshInterval: 0s
  updatePolicy: IfNotExists        # only create on first run
  secretStoreRefs:
    - name: cluster-secret-store
      kind: ClusterSecretStore
  selector:
    generatorRef:
      apiVersion: generators.external-secrets.io/v1alpha1
      kind: Password
      name: strong-password-no-special-chars
  template:
    data:
      username: db-user
      password: "{{ .password }}"
  data:
    - match:
        remoteRef:
          remoteKey: postgres-credentials
      metadata:
        secretPushFormat: string
```
So the solution is to use templating and exclude the `property` from remoteRef.
