### ISSUE TITLE
Propagate Labels from ExternalSecret to the Generated Secret

### ISSUE THREAD

**Issue by Sn0rt** [external-secrets/external-secrets#4749]
### Background:

Currently, when creating a `Secret` using an `ExternalSecret`, users notice that the generated `Secret` does **not** inherit the `metadata.labels` from the `ExternalSecret`.

---

### Current Behavior:

**Case 1: No label on `ExternalSecret`, the generated `Secret` also has no labels (as expected)**

```yaml
metadata:
  labels: {}
```

**Case 2: When setting `.spec.target.creationPolicy = Owner`, the generated `Secret` includes a controller-managed label:**

```yaml
metadata:
  labels:
    reconcile.external-secrets.io/created-by: <hash>
```

**Case 3: When adding a custom label to the `ExternalSecret`, it does not propagate to the `Secret`:**

```yaml
metadata:
  labels:
    test: test1
```

But the corresponding `Secret` does not reflect this custom label:

```yaml
metadata:
  labels:
    reconcile.external-secrets.io/created-by: <hash>
```

---

### Expected Behavior:

Labels defined on the `ExternalSecret` should be propagated to the generated `Secret`, which would enable better integration with tools that rely on labels for automation, access control, or monitoring.

---

**Comment by gusfcarvalho** [comment]
Hi @Sn0rt . this only happens if you are setting a template with labels. And then, this is by design, as you are telling to external-secrets that you want to own the labels on the Secret.

**Comment by gusfcarvalho** [comment]
these manifests:

```
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: fake
spec:
  provider:
    fake:
      data:
      - key: "/foo/bar"
        value: "HELLO1"
        version: "v1"
      - key: "/foo/bar"
        value: "HELLO2"
        version: "v2"
      - key: "/foo/baz"
        value: '{"john": "doe"}'
        version: "v1"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example
  labels:
    copy: yesplease
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: fake
    kind: ClusterSecretStore
  target:
    name: secret-to-be-created
  data:
  - secretKey: foo_bar
    remoteRef:
      key: /foo/bar
      version: v1
  dataFrom:
  - extract:
      key: /foo/baz
      version: v1
```

generates a secret with the labels:
```
  labels:
    copy: yesplease
    reconcile.external-secrets.io/created-by: 45b719e2f6ed40358b2fb7face01965d
    reconcile.external-secrets.io/managed: "true"
```
