### ISSUE TITLE
External Secret fails to sync with error "expected one 1Password ItemField matching: 'credential' in 'sops-age', got 0"

### ISSUE THREAD

**Issue by ShawnDen-coder** [external-secrets/external-secrets#4805]
## **Describe the bug**
External-secrets operator is unable to find the specified property 'credential' in the 1Password item 'sops-age', resulting in the ExternalSecret failing to sync. The error is:

```
error processing spec.data[0] (key: sops-age), err: expected one 1Password ItemField matching: 'credential' in 'sops-age', got 0
```

This suggests that either the item 'sops-age' doesn't exist in the specified 1Password vault, or it exists but doesn't have a field named 'credential'.

## **To Reproduce**

1. Created a SecretStore that points to 1Password:
```yaml
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: onepassword-store
  namespace: external-secrets
spec:
  provider:
    onepassword:
      auth:
        secretRef:
          connectTokenSecretRef:
            key: token
            name: onepassword-connect-token
      connectHost: http://onepassword-connect.external-secrets.svc.cluster.local:8080
      vaults:
        k8s: 1
```

2. Created an ExternalSecret to fetch a secret from 1Password:
```yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sops-age
  namespace: external-secrets
spec:
  data:
  - remoteRef:
      key: sops-age
      property: credential
    secretKey: age.agekey
  refreshInterval: 15m
  secretStoreRef:
    kind: SecretStore
    name: onepassword-store
  target:
    creationPolicy: Owner
    name: sops-age
```

3. Observed the error in the ExternalSecret events:
```
Warning  UpdateFailed  37s (x21 over 79m)  external-secrets  error processing spec.data[0] (key: sops-age), err: expected one 1Password ItemField matching: 'credential' in 'sops-age', got 0
```

## **Expected behavior**
I expect the ExternalSecret to successfully fetch the 'credential' property from the 'sops-age' item in my 1Password vault and create a Kubernetes Secret named 'sops-age' with the key 'age.agekey' containing the value of that property.

## **Additional context**
op path: "op://k8s/j5wkqrdha3kw5uvgbqwxugz3g4/credential"
![Image](https://github.com/user-attachments/assets/7a14217f-6edb-4a18-bbba-e636accee533)
