### ISSUE TITLE
Upgraded to v0.16.2 and observing 'Internal error occurred: failed calling webhook' errors from ArgoCD

### ISSUE THREAD

**Issue by skumsi** [external-secrets/external-secrets#4814]
**Describe the bug**
We are using templates generated from the helm chart to deploy via ArgoCD.
The new version (v0.16.2) seems to be installed but ArgoCD shows a 'sync failed' message below:
> one or more objects failed to apply, reason: error when patching "/dev/shm/2098203346": Internal error occurred: failed calling webhook "validate.externalsecret.external-secrets.io": failed to call webhook: the server could not find the requested resource

**Additional context**
Checked the pods are running as expected and do not show any errors in logs:
```
$ k get pods -n external-secrets
NAME                                                READY   STATUS    RESTARTS   AGE
external-secrets-85f7586669-qv82v                   1/1     Running   0          26h
external-secrets-cert-controller-77c8896f5d-vnn2b   1/1     Running   0          46m
external-secrets-webhook-7ddbb69fd4-dxj6t           1/1     Running   0          46m

```
Followed the upgrade instructions:
```
$ kubectl get crd \
    externalsecrets.external-secrets.io\
    secretstores.external-secrets.io\
    clustersecretstores.external-secrets.io\
    clusterexternalsecrets.external-secrets.io\
    -o jsonpath='{.items[*].status.storedVersions[?(@=="v1alpha1")]}' | \
    grep -q v1alpha1 && echo "NOT SAFE! REMOVE v1alpha1 FROM YOUR STORED VERSIONS" || echo "Safe to Continue"
Safe to Continue
```
CRDs currently installed:
```
$ kubectl get crd -o custom-columns=NAME:.metadata.name,VERSIONS:.spec.versions[*].name | grep external-secrets
acraccesstokens.generators.external-secrets.io          v1alpha1
clusterexternalsecrets.external-secrets.io              v1,v1beta1
clustergenerators.generators.external-secrets.io        v1alpha1
clusterpushsecrets.external-secrets.io                  v1alpha1
clustersecretstores.external-secrets.io                 v1,v1beta1
ecrauthorizationtokens.generators.external-secrets.io   v1alpha1
externalsecrets.external-secrets.io                     v1,v1beta1
fakes.generators.external-secrets.io                    v1alpha1
gcraccesstokens.generators.external-secrets.io          v1alpha1
generatorstates.generators.external-secrets.io          v1alpha1
githubaccesstokens.generators.external-secrets.io       v1alpha1
grafanas.generators.external-secrets.io                 v1alpha1
passwords.generators.external-secrets.io                v1alpha1
pushsecrets.external-secrets.io                         v1alpha1
quayaccesstokens.generators.external-secrets.io         v1alpha1
secretstores.external-secrets.io                        v1,v1beta1
stssessiontokens.generators.external-secrets.io         v1alpha1
uuids.generators.external-secrets.io                    v1alpha1
vaultdynamicsecrets.generators.external-secrets.io      v1alpha1
webhooks.generators.external-secrets.io                 v1alpha1
```
The idea was to upgrade to v0.16.2 and migrate the manifests to v1 and upgrade to v0.17.0.

**Comment by skumsi** [comment]
I'm seeing the same error when I try to modify the ExternalSecret resource from ArgoCD, it would just bounce back with the error mentioned.

When tried applying a external-secret resource manually to the EKS cluster observing the same error:
```
$ kubectl apply -f test-external-secret.yaml
Error from server (InternalError): error when creating "test-external-secret.yaml": Internal error occurred: failed calling webhook "validate.externalsecret.external-secrets.io": failed to call webhook: the server could not find the requested resource
```
Here are my validatingwebhookconfiguration manifests for externalsecret-validate and secretstore-validate webhooks:
```
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: >-
      argocd-isone-cluster_k8s-cluster-eks-pubweb-dev-use1:admissionregistration.k8s.io/ValidatingWebhookConfiguration:/secretstore-validate
  labels:
    app.kubernetes.io/instance: external-secrets
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: external-secrets-webhook
    app.kubernetes.io/version: v0.16.2
    external-secrets.io/component: webhook
    helm.sh/chart: external-secrets-0.16.2
  name: secretstore-validate
webhooks:
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: external-secrets-webhook
        namespace: external-secrets
        path: /validate-external-secrets-io-v1-secretstore
    name: validate.secretstore.external-secrets.io
    rules:
      - apiGroups:
          - external-secrets.io
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
          - DELETE
        resources:
          - secretstores
        scope: Namespaced
    sideEffects: None
    timeoutSeconds: 5
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: external-secrets-webhook
        namespace: external-secrets
        path: /validate-external-secrets-io-v1-clustersecretstore
    name: validate.clustersecretstore.external-secrets.io
    rules:
      - apiGroups:
          - external-secrets.io
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
          - DELETE
        resources:
          - clustersecretstores
        scope: Cluster
    sideEffects: None
    timeoutSeconds: 5
```
```
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: >-
      argocd-isone-cluster_k8s-cluster-eks-pubweb-dev-use1:admissionregistration.k8s.io/ValidatingWebhookConfiguration:/externalsecret-validate
  labels:
    app.kubernetes.io/instance: external-secrets
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: external-secrets-webhook
    app.kubernetes.io/version: v0.16.2
    external-secrets.io/component: webhook
    helm.sh/chart: external-secrets-0.16.2
  name: externalsecret-validate
webhooks:
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: external-secrets-webhook
        namespace: external-secrets
        path: /validate-external-secrets-io-v1-externalsecret
    failurePolicy: Fail
    name: validate.externalsecret.external-secrets.io
    rules:
      - apiGroups:
          - external-secrets.io
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
          - DELETE
        resources:
          - externalsecrets
        scope: Namespaced
    sideEffects: None
    timeoutSeconds: 5
```

**Comment by gusfcarvalho** [comment]
What's happening here is that while the `validatingwebhookconfig` are already deployed to `v0.16.2`, it seems your webhook pod is still running on a previous version.

You can work-around it by changing:
```diff
-        path: /validate-external-secrets-io-v1-externalsecret
+        path: /validate-external-secrets-io-v1beta1-externalsecret
```

**Comment by skumsi** [comment]
not installing ExternalSecrets along with the operator. 
Some external-secrets already exist in the cluster with v1beta1 API version.
Your guess about the webhook pod still running a previous version could be correct. I see the following in the webhook pod logs.
```
$ k logs external-secrets-webhook-79cfb8c74-wlx9x -n external-secrets
Defaulted container "webhook" out of: webhook, dynatrace-operator (init)
{"level":"info","ts":1747782599.610011,"logger":"setup","msg":"validating certs"}
{"level":"info","ts":1747782599.80695,"logger":"controller-runtime.builder","msg":"Registering a validating webhook","GVK":"external-secrets.io/v1beta1, Kind=ExternalSecret","path":"/validate-external-secrets-io-v1beta1-externalsecret"}
{"level":"info","ts":1747782599.8071046,"logger":"controller-runtime.webhook","msg":"Registering webhook","path":"/validate-external-secrets-io-v1beta1-externalsecret"}
{"level":"info","ts":1747782599.8072746,"logger":"controller-runtime.webhook","msg":"Registering webhook","path":"/convert"}
{"level":"info","ts":1747782599.8073132,"logger":"controller-runtime.builder","msg":"Conversion webhook enabled","GVK":"external-secrets.io/v1beta1, Kind=ExternalSecret"}
{"level":"info","ts":1747782599.8074214,"logger":"controller-runtime.builder","msg":"Registering a validating webhook","GVK":"external-secrets.io/v1beta1, Kind=SecretStore","path":"/validate-external-secrets-io-v1beta1-secretstore"}
{"level":"info","ts":1747782599.8075118,"logger":"controller-runtime.webhook","msg":"Registering webhook","path":"/validate-external-secrets-io-v1beta1-secretstore"}
{"level":"info","ts":1747782599.8075912,"logger":"controller-runtime.builder","msg":"Conversion webhook enabled","GVK":"external-secrets.io/v1beta1, Kind=SecretStore"}
{"level":"info","ts":1747782599.8076687,"logger":"controller-runtime.builder","msg":"Registering a validating webhook","GVK":"external-secrets.io/v1beta1, Kind=ClusterSecretStore","path":"/validate-external-secrets-io-v1beta1-clustersecretstore"}
{"level":"info","ts":1747782599.8078446,"logger":"controller-runtime.webhook","msg":"Registering webhook","path":"/validate-external-secrets-io-v1beta1-clustersecretstore"}
{"level":"info","ts":1747782599.8079765,"logger":"controller-runtime.builder","msg":"Conversion webhook enabled","GVK":"external-secrets.io/v1beta1, Kind=ClusterSecretStore"}
{"level":"info","ts":1747782599.808115,"logger":"controller-runtime.builder","msg":"Conversion webhook enabled","GVK":"external-secrets.io/v1alpha1, Kind=ExternalSecret"}
{"level":"info","ts":1747782599.808209,"logger":"controller-runtime.builder","msg":"Conversion webhook enabled","GVK":"external-secrets.io/v1alpha1, Kind=SecretStore"}
{"level":"info","ts":1747782599.8083587,"logger":"controller-runtime.builder","msg":"Conversion webhook enabled","GVK":"external-secrets.io/v1alpha1, Kind=ClusterSecretStore"}
{"level":"info","ts":1747782599.9056923,"logger":"setup","msg":"starting manager"}
{"level":"info","ts":1747782599.9058867,"logger":"controller-runtime.metrics","msg":"Starting metrics server"}
{"level":"info","ts":1747782599.9060454,"logger":"controller-runtime.metrics","msg":"Serving metrics server","bindAddress":":8080","secure":false}
{"level":"info","ts":1747782599.9061503,"logger":"controller-runtime.webhook","msg":"Starting webhook server"}
{"level":"info","ts":1747782599.9061272,"msg":"starting server","name":"health probe","addr":"[::]:8081"}
{"level":"info","ts":1747782599.9065104,"logger":"controller-runtime.certwatcher","msg":"Updated current TLS certificate"}
{"level":"info","ts":1747782599.9065847,"logger":"controller-runtime.webhook","msg":"Serving webhook server","host":"","port":10250}
{"level":"info","ts":1747782599.906765,"logger":"controller-runtime.certwatcher","msg":"Starting certificate poll+watcher","interval":10}
{"level":"info","ts":1747782899.8086288,"logger":"setup","msg":"validating certs"}
{"level":"info","ts":1747782899.8092303,"logger":"setup","msg":"certs are valid"}

```
But then I verified and the webhook deployment is updated to use the container image version v0.16.2. Is there is a way to force it to use  ```path: /validate-external-secrets-io-v1-externalsecret``` instead?

I tried applying the workaround you suggested, still seeing the same error. The webhook config looks like this now:
```
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: >-
      argocd-isone-cluster_k8s-cluster-eks-pubweb-dev-use1:admissionregistration.k8s.io/ValidatingWebhookConfiguration:/externalsecret-validate
  labels:
    app.kubernetes.io/instance: external-secrets
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: external-secrets-webhook
    app.kubernetes.io/version: v0.16.2
    external-secrets.io/component: webhook
    helm.sh/chart: external-secrets-0.16.2
  name: externalsecret-validate
webhooks:
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: external-secrets-webhook
        namespace: external-secrets
        path: /validate-external-secrets-io-v1beta1-externalsecret
    failurePolicy: Fail
    name: validate.externalsecret.external-secrets.io
    rules:
      - apiGroups:
          - external-secrets.io
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
          - DELETE
        resources:
          - externalsecrets
        scope: Namespaced
    sideEffects: None
    timeoutSeconds: 5
```
Now when I try to create an external-secret I see this:
>$ k apply -f test-external-secret.yaml
Error from server: error when creating "test-external-secret.yaml": admission webhook "validate.externalsecret.external-secrets.io" denied the request: no kind "ExternalSecret" is registered for version "external-secrets.io/v1" in scheme "pkg/runtime/scheme.go:100"
