### ISSUE TITLE
can't use ClusterSecretStore, helm chart 0.17.0

### ISSUE THREAD

**Issue by masterkain** [external-secrets/external-secrets#4823]
so I'm trying out external-secrets with scaleway and flux:

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  # installed in external-secrets namespace via kustomize
spec:
  releaseName: external-secrets
  chart:
    spec:
      chart: external-secrets
      version: "0.17.0"
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
  interval: 3m0s
  install:
    remediation:
      retries: 10
  upgrade:
    remediation:
      retries: 10
  values:
    replicaCount: 1
    installCRDs: true
    concurrent: 1
```

```yaml
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: secret-store
  namespace: default
spec:
  provider:
    scaleway:
      region: fr-par
      projectId: xxxx
      accessKey:
        secretRef:
          name: scwsm-secret # created via kubectl create secret generic scwsm-secret
          key: access-key
      secretKey:
        secretRef:
          name: scwsm-secret
          key: secret-access-key
  conditions:
    - namespaceSelector:
        matchLabels:
          kustomize.toolkit.fluxcd.io/name: apps
```

however in controller I get:

_could not get provider client: when using a ClusterSecretStore, namespaces must be explicitly set_

```
{"level":"error","ts":1747852480.8375347,"logger":"controllers.ClusterSecretStore","msg":"unable to validate store","clustersecretstore":{"name":"secret-store"},"error":"could not get provider client: when using a ClusterSecretStore, namespaces must be explicitly set","stacktrace":"github.com/external-secrets/external-secrets/pkg/controllers/secretstore.reconcile\n\t/home/runner/work/external-secrets/external-secrets/pkg/controllers/secretstore/common.go:76\ngithub.com/external-secrets/external-secrets/pkg/controllers/secretstore.(*ClusterStoreReconciler).Reconcile\n\t/home/runner/work/external-secrets/external-secrets/pkg/controllers/secretstore/clustersecretstore_controller.go:66\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...[]).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.4/pkg/internal/controller/controller.go:119\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...[]).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.4/pkg/internal/controller/controller.go:334\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...[]).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.4/pkg/internal/controller/controller.go:294\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.4/pkg/internal/controller/controller.go:255"}
{"level":"error","ts":1747852480.8457704,"msg":"Reconciler error","controller":"clustersecretstore","controllerGroup":"external-secrets.io","controllerKind":"ClusterSecretStore","ClusterSecretStore":{"name":"secret-store"},"namespace":"","name":"secret-store","reconcileID":"e9d85413-1cd8-4af7-9de2-43d8caf62d8c","error":"could not get provider client: when using a ClusterSecretStore, namespaces must be explicitly set","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...[]).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.4/pkg/internal/controller/controller.go:347\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...[]).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.4/pkg/internal/controller/controller.go:294\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.4/pkg/internal/controller/controller.go:255"}
```

what am I missing?

**Comment by gusfcarvalho** [comment]
for `ClusterSecretStores`, a namespace must be set on your `Ref` objects:
```
secretKey:
  secretRef:
     name: scwsm-secret
     key: secret-access-key
     namespace: the-namespace-where-the-secret-exists-goes-here
```

Some providers support this field to be empty; most of them don't.
