### ISSUE TITLE
How to inject annotations to ExternalSecrets

### ISSUE THREAD

**Issue by divyangjp** [external-secrets/external-secrets#4827]
I wanted to inject some annotations in k8s `secret` created. 
Is that possible?
How to do it?

**Comment by Skarlso** [comment]
Hello.

Yep, you should be able to do that with `templates`. It has an `annotations` section.

**Comment by gusfcarvalho** [comment]
this is documented in https://external-secrets.io/latest/guides/templating/#examples 😄:

```
spec: 
  target:
    template:
      annotations:
         hihihi: hohoho
      labels:
        custom.domain/part-of: my-project
```

You can also set dynamic annotations / labels with `templateFrom` - also in the same docs page.
