### ISSUE TITLE
Solution to inject labels and/ or annotations to the k8s secret using ExternalSecret

### ISSUE THREAD

**Issue by yashwanth-l** [external-secrets/external-secrets#4834]
**Describe the bug**
k8s secret created from `kind: ExternalSecret` doesnt have labels or annotaton created as described [in this example](https://external-secrets.io/v0.16.2/api/externalsecret/#example) or neither with the solution described in https://github.com/external-secrets/external-secrets/issues/4827 

**To Reproduce**
K8S: v1.31.7-gke.1212000
ESO: 0.16.2

**As per example:**

```
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: podinfo
  namespace: podinfo
  labels:
    app: podinfo
  annotations:
    reloader.stakater.com/match: "true"
    version: "1"
spec:
  refreshInterval: 1m
  refreshPolicy: OnChange
...
```

The outcome of this is that the k8s secret has no labels as configured in `ExternalSecretMetadata` as as documented in https://external-secrets.io/v0.16.2/api/externalsecret/#example 

**As per solution in issue:**

```
spec: 
  target:
    template:
      annotations:
         hihihi: hohoho
      labels:
        custom.domain/part-of: my-project
```

The error is:

```
strict decoding error: unknown field "spec.target.template.annotations"
```

What is the correct format and what is the solution to inject labels and/ or annotations to the k8s secret using ExternalSecret

**Comment by gusfcarvalho** [comment]
one general tip, if you do ` kubectl explain <crd>` you can interatively figure out whats the correct way to write a manifest:

You are missing the `metadata` block.
```
spec: 
  target:
    template:
      metadata:
          annotations:
             hihihi: hohoho
          labels:
            custom.domain/part-of: my-project
```

**Comment by yashwanth-l** [comment]
Thanks @gusfcarvalho !! I validated other ExternalSecretSpec - but since this had 2 different solutions, didn't quite know which one is th apt solution to consider and the docs has a different solution :)

**Comment by yashwanth-l** [comment]
> if you remove the spec.target.template.metadata field completely, ESO will copy whatever is on your ExternalSecret object.

I tried this, but the k8s-Secret didnt have any labels / annotations present when ExternalSecret

**Comment by gusfcarvalho** [comment]
> > if you remove the spec.target.template.metadata field completely, ESO will copy whatever is on your ExternalSecret object.
> 
> I tried this, but the k8s-Secret didnt have any labels / annotations present when ExternalSecret


Can you add complete manifests to your response?

**Comment by yashwanth-l** [comment]
@gusfcarvalho The manifest is as below:

```yaml
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: podinfo
  annotations:
     reloader.stakater.com/match: "true"
   labels:
     app: podinfo
spec:
  refreshInterval: 1h
  refreshPolicy: OnChange
  secretStoreRef:
    name: secret-store
    kind: ClusterSecretStore
  target:
    name: podinfo
    template:
      engineVersion: v2
      data:
        PODINFO_UI_MESSAGE: '{{ .PODINFO_UI_MESSAGE }}'
  data:
  - secretKey: PODINFO_UI_MESSAGE
    remoteRef:
      key: podinfo-token-json
      property: PODINFO_UI_MESSAGE
```

I dont see the below labels and annotations in the created k8s secret:

```yaml
...
  annotations:
     reloader.stakater.com/match: "true"
   labels:
     app: podinfo
...
```
