### ISSUE TITLE
0.17.0 breaks fluxcd with GCP store

### ISSUE THREAD

**Issue by blindrood** [external-secrets/external-secrets#4848]
**Describe the bug**
I have recently migrated from 0.10.0 to 0.16.2 and upgraded API versions everywhere to v1. All works great.
Now I'm migrating to 0.17.0 and suddenly fluxcd is unable to sync them properly

**To Reproduce**
secret definition in my repo

```yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gcp-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-store
  target:
    name: app-secrets
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: stage-k8s
```

fluxcd syncs periodically cluster. Up until 0.16.2 all works great.
After migration to 0.17.0 ExternalSecret resources look ok from my point of view but suddenly fluxcd keeps returning

```
health check failed after 10m0.02452782s: timeout waiting for: [ExternalSecret/namespace/gcp-secret status: 'NotFound']
```

**Expected behavior**
fluxcd should still sync properly secrets

**Additional context**
eso deployed via helm chart using terraform, just bumping here version to 0.17.0

```hcl
resource "helm_release" "external_secrets" {
  name          = "external-secrets"
  repository    = "https://charts.external-secrets.io"
  chart         = "external-secrets"
  namespace     = kubernetes_namespace_v1.external-secrets.metadata[0].name
  recreate_pods = true
  reuse_values  = true
  version       = "0.16.2"

  set {
    name  = "serviceAccount.annotations.iam\\.gke\\.io/gcp-service-account"
    value = google_service_account.eso_sa.email
  }
  set {
    name = "certController.resources.requests.cpu"
    value = "100m"
  }
  set {
    name = "certController.resources.requests.memory"
    value = "64Mi"
  }
  set {
    name = "webhook.service.enabled"
    value = "true"
  }
  set {
    name = "webhook.resources.requests.cpu"
    value = "25m"
  }
  set {
    name = "webhook.resources.requests.memory"
    value = "32Mi"
  }
  set {
    name = "resources.requests.cpu"
    value = "25m"
  }
  set {
    name = "resources.requests.memory"
    value = "64Mi"
  }
  set {
    name = "grafanaDashboard.enabled"
    value = "false"
  }
}
```
