### ISSUE TITLE
ClusterSecretStore is valid and ready, but ExternalSecrets is in state "SecretSyncedError"

### ISSUE THREAD

**Issue by federicochiesa** [external-secrets/external-secrets#4867]
**Describe the bug**
I'm using AWS Parameter Store and EKS. This is the yaml for the ClusterSecretStore:
```yaml
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  namespace: external-secrets
  name: parameterstore
spec:
  provider:
    aws:
      service: ParameterStore
      role: arn:aws:iam::516205768730:role/ParameterStoreEKSAccess
      region: eu-central-1
      auth:
        jwt:
          serviceAccountRef:
            name: default
```
This gives me a valid and ready store:
```
Status:                                                                                                                                                                                                                                            
  Capabilities:  ReadWrite                                                                                                                                                                                                                         
  Conditions:                                                                                                                                                                                                                                      
    Last Transition Time:  2025-06-03T13:56:14Z                                                                                                                                                                                                    
    Message:               store validated                                                                                                                                                                                                         
    Reason:                Valid                                                                                                                                                                                                                   
    Status:                True                                                                                                                                                                                                                    
    Type:                  Ready                                                                                                                                                                                                                   
Events:                                                                                                                                                                                                                                            
  Type    Reason  Age                 From                  Message                                                                                                                                                                                
  ----    ------  ----                ----                  -------                                                                                                                                                                                
  Normal  Valid   56s (x17 over 74m)  cluster-secret-store  store validated        
```

If I try to create a secret using this store with the following YAML:
```yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "registrycredentials"
  namespace: "xxxxxxxxxxxxxx"
spec:
  secretStoreRef:
    name: parameterstore
    kind: ClusterSecretStore
  refreshPolicy: OnChange
  refreshInterval: "1h"
  target:
    name: regcred
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: '{"auths":{"xxxxxxxxxxxxxxxx":{"username":"xxxxxxxxxxx","password":"{{ .password }}","auth":"{{ printf "%s:%s" xxxxxxxxxxx .password | b64enc }}"}}}'
  dataFrom:
  - extract:
      key: xxxxxxxxxxxxxxxxx
```

I get the following status: 
```
Status:                                                                                                                                                                                                                                            
  Binding:                                                                                                                                                                                                                                         
    Name:                                                                                                                                                                                                                                          
  Conditions:                                                                                                                                                                                                                                      
    Last Transition Time:  2025-06-03T15:04:40Z                                                                                                                                                                                                    
    Message:               could not get secret data from provider                                                                                                                                                                                 
    Reason:                SecretSyncedError                                                                                                                                                                                                       
    Status:                False                                                                                                                                                                                                                   
    Type:                  Ready                                                                                                                                                                                                                   
  Refresh Time:            <nil>                                                                                                                                                                                                                   
Events:                                                                                                                                                                                                                                            
  Type     Reason        Age                   From              Message                                                                                                                                                                           
  ----     ------        ----                  ----              -------                                                                                                                                                                           
  Warning  UpdateFailed  72s (x10 over 9m41s)  external-secrets  error processing spec.dataFrom[0].extract, err: unable to create session: an IAM role must be associated with service account default (namespace: xxxxxxxxxxxx)  
```

What I expected is for the externalSecret to use the role from the serviceaccount it already has in the "external-secrets" namespace. Moreover, if I try to give an IAM role to the default serviceaccount in that namespace via Pod Identity it still gives me the same message.

**To Reproduce**
1. Create a ClusterSecretStore
2. Create an ExternalSecret using the ClusterSecretStore
