### ISSUE TITLE
ACRAccessToken Generation fails when using System Assigned Managed Identity

### ISSUE THREAD

**Issue by i-make-razors** [external-secrets/external-secrets#4889]
**Describe the bug**
When creating an ACR token using the `ACRAccessToken` generator on a K3s cluster running on an Azure Virtual Machine, the generator fails unless a User Assigned Managed Identity is used.

We're running a cluster on Azure VMs using K3s (I know we should be using AKS, but at the moment that isn't an option for us). The VMs that are part of the cluster are all configured with System Assigned Managed Identities. The ACRAccessToken generator doesn't support this option, even though it is supported by the Azure Identity SDK.

Information:

- ESO Version: 0.17.0
- K3s Version: v1.32.3+k3s1
- Host OS: Ubuntu 24.04.2 LTS

**To Reproduce**
Create a ACRAccessToken generator with an empty `managedIdentity` section:

```yaml
apiVersion: generators.external-secrets.io/v1alpha1
kind: ACRAccessToken
metadata:
  name: acr-generator
spec:
  tenantId: 00000000-0000-0000-0000-000000000000
  registry: my-private-acr.azurecr.io
  auth:
    managedIdentity:
```

Create a Secret referencing the generator

```yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: acr-token
spec:
  refreshInterval: 1h
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ACRAccessToken
          name: "acr-generator"
  target:
    name: acr-token
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "my-private-acr.azurecr.io": {
                "username": "00000000-0000-0000-0000-000000000000",
                "password": "{{ .password }}"
              }
            }
          }
```

**Expected behavior**
If no identity id is provided, the generator should fall back to using the System Assigned managed Identity. Alternativly there could be a property `useSystemAssignedManagedIdentity: true` that allows this behavior.

**Screenshots**
Error message from the controller: 

```json
{"level":"error","ts":1749492524.1120706,"msg":"Reconciler error","controller":"externalsecret","controllerGroup":"external-secrets.io","controllerKind":"ExternalSecret","ExternalSecret":{"name":"acr-token","namespace":"aio"},"namespace":"aio","name":"acr-token","reconcileID":"5455e24b-2d0c-440d-831d-51d8dae1e194","error":"error processing spec.dataFrom[0].sourceRef.generatorRef, err: error using generator: unexpeted configuration","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.4/pkg/internal/controller/controller.go:347\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.4/pkg/internal/controller/controller.go:294\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.4/pkg/internal/controller/controller.go:255"}
```

**Additional context**

[By Default](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/azidentity/managed_identity_client.go#L121) The Managed Identity Client will use a `SystemAssigned` identity. If the passed in options are not `nill` then it will switch to a `User Assigned` identity.

![Image](https://github.com/user-attachments/assets/1433a0c8-39c9-4420-8011-9c84e4ef0d06)

In the ACR Generator code, options are[ always generated](https://github.com/external-secrets/external-secrets/blob/main/pkg/generator/acr/acr.go#L295) and passed into the `NewManagedIdentityCredential` function, meaning system assigned managed identities can never be used.

![Image](https://github.com/user-attachments/assets/8e64fac6-0208-4221-9f6f-9e09fe480554)

**Comment by i-make-razors** [comment]
I have found a workaround, for this bug that i'm using at the moment, but it would be very nice if I didn't have to do it this way :)

1. Create a webhook generate to generate that will connect to the VMs meta-data endpoint to generate an entraid token:

```yaml
apiVersion: generators.external-secrets.io/v1alpha1
kind: Webhook
metadata:
  name: azure-entra-token-generator
spec:
  url: "http://169.254.169.254/metadata/identity/oauth2/token?resource=https://management.core.windows.net&api-version=2018-02-01"
  result:
    jsonPath: "$"
  headers:
    Metadata: 'true'
```

2.  Generate a entra token as a secret:

```yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: entra-token
spec:
  refreshInterval: 30m
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Webhook
          name: azure-entra-token-generator
  target:
    name: entra-token
```

3. Create another Webhook generator to perform a token exchange of the entra token for an ACR token:

```yaml
apiVersion: generators.external-secrets.io/v1alpha1
kind: Webhook
metadata:
  name: acr-token-generator
spec:
  url: https://my-secret-acr.azurecr.io/oauth2/exchange
  method: POST
  body: grant_type=access_token&service=my-secret-acr.azurecr.io&tenant=f92686be-221d-4308-b43a-30195ccd11d9&access_token={{ print .auth.access_token }}
  result:
    jsonPath: "$"
  headers:
    Content-Type: application/x-www-form-urlencoded
  secrets:
    - name: auth
      secretRef:
        name: entra-token
```

4. Generate a docker credentials secret from the ACR webhook generator

```yaml
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: acr-token
spec:
  refreshInterval: 30m
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Webhook
          name: acr-token-generator
  target:
    name: acr-token
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "my-secret-acr.azurecr.io": {
                "username": "00000000-0000-0000-0000-000000000000",
                "password": "{{ .refresh_token }}"
              }
            }
          }
```
