### ISSUE TITLE
AWS EKS Pod Identity Step Missing Annotation In Example

### ISSUE THREAD

**Issue by chrisblatt** [external-secrets/external-secrets#4892]
**Describe the bug**

I was following the steps [here](https://external-secrets.io/v0.17.0/provider/aws-secrets-manager/#eks-pod-identity-setup) to enable EKS pod identity auth for ESO and this step is missing the needed annotation to work:

**Install ESO using helm and define these values:**

```yaml
serviceAccount:
  annotations:
  name: external-secrets
```

The following SecretStore would not auth and threw an error, I found this [issue](https://github.com/external-secrets/external-secrets/issues/2951) and noticed the role arn annotation was missing:

```yaml
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::111122223333:role/my-role
  name: external-secrets
```

Once I added that annotation to the service account, the SecretStore connected successfully.

**To Reproduce**
- Follow steps above for setting up EKS Pod Identity and notice the missing annotation
- Try to create a SecretStore and observe it fails
- Add the annotation to the service account
- Observe that the SecretStore connects successfully now

**Expected behavior**
Update docs so example works

**Screenshots**

**Additional context**

**Comment by gusfcarvalho** [comment]
@chrisblatt what you did was use IRSA as opposed to POD Identity.

Was this expected?

**Comment by chrisblatt** [comment]
@gusfcarvalho not my intention to use that, my Secret Store looks like this which I thought meant I was using Pod Identity, I don't specify a `auth` section:
```yaml
kind: SecretStore
  metadata:
    name: my-store
    namespace: external-secrets
  spec:
    provider:
      aws:
        region: us-east-1
        service: SecretsManager
  status:
    capabilities: ReadWrite
    conditions:
    - lastTransitionTime: "2025-06-10T18:37:31Z"
      message: store validated
      reason: Valid
      status: "True"
      type: Ready
```
