### ISSUE TITLE
Cannot get ExternalSecret synced in a Google GKE private cluster environment / cryptic error message

### ISSUE THREAD

**Issue by oliverboehme-ida** [external-secrets/external-secrets#4904]
**Describe the bug**
I tried to set up a sample namespaced SecretStore and ExternalSecret, connecting to Google Secret Manager, from within a private cluster GKE. Authentication is done via method ["Linking a KSA to a GSA"](https://external-secrets.io/latest/provider/google-secrets-manager/#linking-a-kubernetes-service-account-to-a-gcp-service-account) from the documentation.
The SecretStore resource in the GKE seems fine, reporting "store validated", but the ESO cannot sync the External Secret with the **Error message pasted below**.

It somehow sounds like a network error. Since I am in a very private and restricted network-setup, can you maybe point out how the ESO connects to the Secret Manager, and which networks I need to share?

Or maybe please point out what I'm missing.

**To Reproduce**
* Kubernetes version: 1.31.7-gke.1390000 
* ESO version: v0.17.0

Installed ESO using Helm Chart with values:
```yaml
image:
  pullPolicy: IfNotPresent
  repository: ghrc.io/external-secrets/external-secrets

log:
  level: debug
  timeEncoding: epoch

serviceAccount:
  name: external-secrets

certController:
  create: false

webhook:
  create: false
```

*SecretStore manifest*
```yaml
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: myapp-secretstore
spec:
  provider:
    gcpsm:
      auth:
        workloadIdentity:
          clusterLocation: <...>
          clusterName: <...>
          serviceAccountRef:
            name: myserviceaccount
      location: <...>
      projectID: myproject
```

*ExternalSecret manifest*
```yaml
spec:
  dataFrom:
  - extract:
      conversionStrategy: Default
      decodingStrategy: None
      key: <...>
      metadataPolicy: None
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: myapp-secretstore
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: <...>
```

**Error message (redacted)**
```json
{
  "jsonPayload": {
    "error": "error processing spec.dataFrom[0].extract, err: unable to access Secret from SecretManager Client: context deadline exceeded",
    "level": "error",
    "name": "myapp-externalsecret",
    "controllerGroup": "external-secrets.io",
    "controllerKind": "ExternalSecret",
    "reconcileID": "79574d9b-ab0f-4d7c-855f-11fb91701b29",
    "msg": "Reconciler error",
    "controller": "externalsecret",
    "namespace": "mynamespace",
    "ExternalSecret": {
      "namespace": "mynamespace",
      "name": "myapp-externalsecret"
    },
    "stacktrace": "sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.4/pkg/internal/controller/controller.go:347\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.4/pkg/internal/controller/controller.go:294\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.4/pkg/internal/controller/controller.go:255",
    "ts": 1749812601.0802016
  },
  "resource": {
    "type": "k8s_container",
    "labels": {
      "namespace_name": "external-secrets",
      "pod_name": "external-secrets-58f67fcbb5-kb28c",
      "cluster_name": "dlr-gke-test-cluster",
      "container_name": "external-secrets",
      "project_id": "myproject"
    }
  },
  "timestamp": "2025-06-13T11:03:21.080461448Z",
  "severity": "ERROR",
  "labels": {
    "logging.gke.io/top_level_controller_name": "external-secrets",
    "k8s-pod/app_kubernetes_io/name": "external-secrets",
    "k8s-pod/helm_sh/chart": "external-secrets-0.17.0",
    "k8s-pod/app_kubernetes_io/managed-by": "Helm",
    "compute.googleapis.com/resource_name": "REDACTED",
    "k8s-pod/app_kubernetes_io/instance": "external-secrets",
    "logging.gke.io/top_level_controller_type": "Deployment",
    "k8s-pod/app_kubernetes_io/version": "v0.17.0",
    "k8s-pod/pod-template-hash": "58f67fcbb5"
  },
  "logName": "projects/myproject/logs/stderr",
  "receiveTimestamp": "2025-06-13T11:03:21.414927188Z"
}
```
