### ISSUE TITLE
Azure k/v certificates doesn't extract pemPrivateKey

### ISSUE THREAD

**Issue by alrosx** [external-secrets/external-secrets#492]
Having an issue with azure certificates.
I've pushed cert.pem (which includes cert and private key) into azure k/v type: certificates.
External-secrets only retrieves the public cert, and adds that to secret
I'm stuck with "tls.key" External-secrets adds "-----BEGIN PRIVATE KEY-----" and then dumps the public cert so both tls.crt and tls.key are identical apart from the cert header/footer.
```
spec:
  data:
    - remoteRef:
        key: cert/myco
      secretKey: myco
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: clustersecretstore
  target:
    creationPolicy: Owner
    name: secret-to-be-created
    template:
      data:
        tls.crt: '{{ .myco | pemCertificate }}'
        tls.key: '{{ .myco | pemPrivateKey }}'
      type: kubernetes.io/tls
```

**Comment by sebagomez** [comment]
Hey @alrosx, unfortunately, this is by design since the PrivateKey is never returned.

You can take a look at this thread for more context: https://github.com/Azure/azure-sdk-for-js/issues/7647#issuecomment-594935307

**Comment by jimmyh85** [comment]
Hello together, 
as we were also running into this issue and it seems that currently, the Azure Key Vault provider is not able to download the private part of the certificate, I was researching through the docs and as you are right @sebagomez that by default it only downloads the public cert, there are supported ways to get both, the certificate and the private key. Maybe https://docs.microsoft.com/en-us/azure/key-vault/certificates/how-to-export-certificate?tabs=azure-cli helps to adjust the current implementation. 
I have not looked yet, how the retrieval is currently implemented but it seems that in addition to fetching the certificate itself, you then need to grab the secret and keys from a different API path, as can be seen in the Powershell example on the above documentation page.

**Comment by moolen** [comment]
It depends on how you set the keyvault certificate policy: You can set a content-type of `PEM` or `PKCS#12`. We've covered the PKCS#12 cert/key extraction with the functions `pkcs12cert` and `pkcs12key`.

The PEM use-case wasn't covered before, i added a `filterPEM` function in #701. Multiple certs/keys can be extracted with this PR, too #358

**Comment by jimmyh85** [comment]
Hi all, thank you for the all of the feedback. However, I still struggle to get it working within my setup. Not sure if I am missing something. So maybe to summarize again, I am trying to create a k8s secret of type `kubernetes.io/tls` from a certificate stored in Azure Key Vault. The certificate has the option "Exportable Private Key?" set to "yes", it is stored in format PKCS#12. 
When trying to fetch via the templating as described in https://external-secrets.io/v0.4.2/guides-templating/ 

```yaml
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: template
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secretstore-sample
    kind: SecretStore
  target:
    name: secret-to-be-created
    # this is how the Kind=Secret will look like
    template:
      type: kubernetes.io/tls
      data:
        tls.crt: "{{ .mysecret | pkcs12cert | pemCertificate }}"
        tls.key: "{{ .mysecret | pkcs12key | pemPrivateKey }}"

  data:
  # this is a pkcs12 archive that contains
  # a cert and a private key
  - secretKey: mysecret
    remoteRef:
      key: secret/my-certname
```
the k8s secret cannot be created. The error logs say 
`could not execute template: unable to execute template at key tls.crt: unable to execute template at key tls.crt: template: tls.crt:1:15: executing \"tls.crt\" at <pkcs12cert>: error calling pkcs12cert: unable to decode pkcs12 certificate with password: pkcs12: error reading P12 data: asn1: structure error: tags don't match (16 vs {class:1 tag:13 length:73 isCompound:false}) {optional:false explicit:false application:false private:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false} pfxPdu @2","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:114\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:311\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:227"}`

Any ideas what I am missing? Also I think it should be added to the docs that you should use 'secret/certname' instead of 'cert/certname' when trying to fetch the certificate with its private key.
