### ISSUE TITLE
dataFrom.find + rewrite causes secret to be rewritten even when source secrets don't change

### ISSUE THREAD

**Issue by assaftir** [external-secrets/external-secrets#4927]
Hey,
I'm using an `ExternalSecret` with `dataFrom.find.name.regexp` to match multiple `bootstrap-token-*` secrets in `kube-system`, and I'm using a rewrite block to flatten the data under `.token`, then generate a single key in the target secret using a template.

Here's the gist of my config:

```
dataFrom:
  - find:
      name:
        regexp: bootstrap-.*
    rewrite:
      - regexp:
          source: (.*)
          target: token
template:
  data:
    KUBELET_BOOTSTRAP_TOKEN: >-
      {{ index (fromJson .token) "token-id" }}.{{ index (fromJson .token) "token-secret" }}
```

There are 3 matching source secrets. None of them have changed — their `resourceVersion, data, and metadata` all stay the same.

Still, I’ve noticed that the target secret (`karpenter-token`) gets rewritten intermittently. Not every `refreshInterval`, but sometimes — even though the rendered value (`KUBELET_BOOTSTRAP_TOKEN`) remains the same. Each rewrite bumps the `resourceVersion`, which triggers Reloader and causes Karpenter to restart unnecessarily.

Is this expected behavior?
Could it be that the merged source data ordering or internal rendering causes false-positive changes?

Any way to avoid unnecessary rewrites if the actual final data didn’t change?

Thanks!

**Comment by gusfcarvalho** [comment]
what version of `external-secrets` are you using? 😄

**Comment by gusfcarvalho** [comment]
btw, this manifest does not guarantee only one value for `KUBELET_BOOTSTRAP_TOKEN`. Actually, the expected behavior is a flap if you have more than one entry. (i.e. if you have two secrets with that expression, the expected behavior is indeed a flapping only-one value because we make no promises the keys on a `find` operation are ordered in any way (and IIRC neither does K8s on a `list`). 

So, I take you somehow have a way to ensure only one `bootstrap-token` exists at a given point in time in your `kube-system` namespace. If that's the case, you'd need to give us the `data-hash` label for each of the new generated Secrets when `resourceVersions` are bumped =)

Of course, after you've already bumped your controllers to `0.17.0`, as we do not provide support for any other versions than the latest (as per https://external-secrets.io/latest/introduction/stability-support/).

**Comment by assaftir** [comment]
Thanks for the quick reply! I can confirm that we're using `v0.17.0`.

Unfortunately, I don't have a way to ensure that only one `bootstrap-token-*` secret exists at a time — those tokens are managed automatically by AKS, so I can’t control their creation or deletion.

Would it be possible to support deterministic behavior in this scenario?
For example: sorting the matched secrets alphabetically and consistently picking the first one. That would at least allow us to predictably select the same source secret as long as it still exists, and avoid unnecessary updates and restarts.

Let me know if that could be considered, or if there's a workaround you recommend.
Thanks again!

**Comment by gusfcarvalho** [comment]
> Would it be possible to support deterministic behavior in this scenario?
For example: sorting the matched secrets alphabetically and consistently picking the first one. That would at least allow us to predictably select the same source secret as long as it still exists, and avoid unnecessary updates and restarts.

I find it hard to believe you'll always want the first one alphabetically, as in reality you probably want the newest one instead of any one of them.

you can work around it implementing `templateFrom.literal` conditions instead of `template`, as this will allow you to also template keys and values; thus you can create conditionals based on the key values:

some non-working example is in these lines:
```
templateFrom:
- literal:
     {{- if len(.) > 1 }}
     # two tokens found - build custom logic based on whatever you want here
     {{- else }}
         {{- $key, $value := range . }}
         KUBELET_BOOTSTRAP_TOKEN: {{ $key }}.{{ $value }}
         {{- end }}
     {{- end }}
```

**Comment by assaftir** [comment]
Thanks!
Looks like `templateFrom` is what I was looking for.
I'm trying to embed it to my ExternalSecret under target but looks like it silently fails and dropped when I apply the yaml.
Can you please take a looks at this one and tell me what I'm missing?

```
target:
  templateFrom:
    - literal: |-
        {{- $selectedSecretName := "" -}}
        {{- $selectedSecretValue := "" -}}
        {{- $first := true -}}
  
        {{- range $secretName, $secretValue := . }}
          {{- if or $first (lt $secretName $selectedSecretName) }}
            {{- $selectedSecretName  = $secretName }}
            {{- $selectedSecretValue = $secretValue }}
            {{- $first = false }}
          {{- end }}
        {{- end }}
  
        {{- $secretValueJson := fromJson $selectedSecretValue }}
        KUBELET_BOOTSTRAP_TOKEN: {{ $secretValueJson.token-id }}.{{ $secretValueJson.token-secret }}
```

Thanks.

**Comment by gusfcarvalho** [comment]
we have a dedicated tool for that called `esoctl`. You should use it 😄

If you still need support with figuring out your manifests, this is something I do not do as part of my free time commitment to this open source project. You should check our slack and see if anyone there is willing to help you out (or wait for anyone to reply to this issue 🤷 )

**Comment by gusfcarvalho** [comment]
since we've confirmed the issue here is due to the fact one or more tokens are generated (though out of your control), it means this issue isn't a bug on external-secrets. Updating the labels to reflect `support` :)

**Comment by assaftir** [comment]
Thanks for your help @gusfcarvalho.

I am trying with this ExternalSecret configuration:

```
Working
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: karpenter-bootstrap-token
  namespace: karpenter
spec:
  dataFrom:
    - find:
        conversionStrategy: Default
        decodingStrategy: None
        name:
          regexp: bootstrap-.*
      rewrite:
        - regexp:
            source: (.*)
            target: token
  refreshInterval: 15s
  secretStoreRef:
    kind: ClusterSecretStore
    name: kube-system-cluster-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: karpenter-bootstrap-token
    template:
      engineVersion: v2
      mergePolicy: Replace
      templateFrom:
        - literal: >-
            {{- $selectedSecretName := "" -}}
            {{- $selectedSecretValue := "" -}}
            {{- $first := true -}}

            {{- range $secretName, $secretValue := . }}
              {{- if or $first (lt $secretName $selectedSecretName) }}
                {{- $selectedSecretName  = $secretName }}
                {{- $selectedSecretValue = $secretValue }}
                {{- $first = false }}
              {{- end }}
            {{- end }}

            {{- $secretValueJson := fromJson $selectedSecretValue }}

            KUBELET_BOOTSTRAP_TOKEN: {{ printf "%s.%s" (index $secretValueJson "token-id") (index $secretValueJson "token-secret") | quote }}
          target: Data
```

I have three secrets let's say `bootstrap-a, bootstrap-b, bootstrap-c`.
With that template I was hoping that `bootstrap-a` will be the chosen one in each `refreshInterval`, but I see the karpenter-bootstrap-token flips between the values of the 3 secrets.

What am I missing?

**Comment by assaftir** [comment]
Thanks for your help @gusfcarvalho

Pasting here a working configuration for future reference.

```
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: karpenter-bootstrap-token
  namespace: karpenter
spec:
  dataFrom:
    - find:
        conversionStrategy: Default
        decodingStrategy: None
        name:
          regexp: bootstrap-.*
  refreshInterval: 10s
  secretStoreRef:
    kind: ClusterSecretStore
    name: kube-system-cluster-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: karpenter-bootstrap-token
    template:
      engineVersion: v2
      mergePolicy: Replace
      templateFrom:
        - literal: >-
            {{- $selectedSecretName := "" -}}
            {{- $selectedSecretValue := "" -}}
            {{- $first := true -}}

            {{- range $secretName, $secretValue := . }}
              {{- if or $first (lt $secretName $selectedSecretName) }}
                {{- $selectedSecretName  = $secretName }}
                {{- $selectedSecretValue = $secretValue }}
                {{- $first = false }}
              {{- end }}
            {{- end }}

            {{- $secretValueJson := fromJson $selectedSecretValue }}

            KUBELET_BOOTSTRAP_TOKEN: {{ printf "%s.%s" (index $secretValueJson "token-id") (index $secretValueJson "token-secret") | quote }}
          target: Data
```
