### ISSUE TITLE
Missing Region error when authenticating to AWS with IRSA ServiceAccount in 0.18.0

### ISSUE THREAD

**Issue by spiarh** [external-secrets/external-secrets#4934]
**Describe the bug**

We are testing `0.18.0` and facing an issue with an AWS `ClusterSecretStore` (auth with IRSA ServiceAccount) that is not being synced due to authentication errors. This issue does not occur with `0.17.0`.

This shows up in the logs:

> could not validate provider: failed to refresh cached credentials, failed to retrieve credentials, operation error STS: AssumeRoleWithWebIdentity, failed to resolve service endpoint, endpoint rule error, Invalid Configuration: Missing Region

I think this is due to the migration to AWS go sdk v2 where `spec.provider.region` is somehow not being used.

A workaround for `0.18.0` is to set `AWS_REGION=eu-central-1` environment variable in the external-secrets pods:

```yaml
env:                 
- name: AWS_REGION   
  value: eu-central-1
```

**To Reproduce**

1. Create the following 

```yaml
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aws-secretstore
spec:
  provider:
    aws:
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-aws-sm
            namespace: external-secrets
      region: eu-central-1
      service: SecretsManager
```

2. The ClusterSecretStore uses the following `ServiceAccount`

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::1111111111111111:role/external-secrets
  name: external-secrets-aws-sm
  namespace: external-secrets
```

The AWS Role can have broad IAM permissions:

```yaml
{
    "Statement": [
        {
            "Action": [
                "secretsmanager:ListSecretVersionIds",
                "secretsmanager:GetSecretValue",
                "secretsmanager:GetResourcePolicy",
                "secretsmanager:DescribeSecret"
            ],
            "Effect": "Allow",
            "Resource": "*"
        }
    ],
    "Version": "2012-10-17"
}
```

3. The AWS `ClusterSecretStore` now shows as not valid and can't sync secrets.

**Expected behavior**
The `ClusterSecretStore` should be successfully validated.
