### ISSUE TITLE
ExternalSecret that refer ECRAuthorizationToken not work in 0.18.0

### ISSUE THREAD

**Issue by maodahua** [external-secrets/external-secrets#4935]
**Describe the bug**
After we upgrade the external-secrets version to 0.18.0, the externalsecret that refer the ECRAuthorizationToken report the error, but it works with version 0.17.0(refer the manifest below, it works). 
looks like it will not use the IRSA permission to perform the `ECR: GetAuthorizationToken`. The logs find in controller:

```
{"level":"error","ts":1750228541.0351596,"msg":"Reconciler error","controller":"externalsecret","controllerGroup":"external-secrets.io","controllerKind":"ExternalSecret","ExternalSecret":{"name":"repository-ecr","namespace":"argocd"},"namespace":"argocd","name":"repository-ecr","reconcileID":"xxxxxxxxx","error":"error processing spec.dataFrom[0].sourceRef.generatorRef, err: error using generator: unable to get authorization token: operation error ECR: GetAuthorizationToken, https response error StatusCode: 400, RequestID: xxxxxxxxx, api error MissingAuthenticationTokenException: Missing Authentication Token","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.21.0/pkg/internal/controller/controller.go:353\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.21.0/pkg/internal/controller/controller.go:300\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.1\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.21.0/pkg/internal/controller/controller.go:202"}
```

**To Reproduce**
1. The ECRAuthorizationToken manifest

```yaml
apiVersion: generators.external-secrets.io/v1alpha1
kind: ECRAuthorizationToken
metadata:
  name: ecr-auth-token
  namespace: argocd
spec:
  region: ap-southeast-2
```

2. The ExternalSecret manifest

```yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: repository-ecr
  namespace: argocd
spec:
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: ECRAuthorizationToken
        name: ecr-auth-token
  refreshInterval: 30m
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      data:
        enableOCI: "true"
        password: "{{ .password }}"
        type: helm
        url: 11111111111.dkr.ecr.ap-southeast-2.amazonaws.com
        username: "{{ .username }}"
      engineVersion: v2
      mergePolicy: Replace
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repo-creds
      type: Opaque
```

The AWS role permission:

<img width="873" alt="Image" src="https://github.com/user-attachments/assets/60162520-bbe3-4a6f-8172-fa8b3a086620" />

Kubernetes version: 1.31(EKS)
ESO version: 0.18.0

**Expected behavior**
The `ExternalSecret` should works fine with ECRAuthorizationToken. I know there are some refactor of AWS, but from the [docs](https://external-secrets.io/latest/api/generator/ecr/), not mention the manifest need some change(diff the old version with the latest).

**Comment by probitaille-axso** [comment]
we're in the same boat, also experiencing this issue..

**Comment by gusfcarvalho** [comment]
can you all try to add a `AWS_REGION` environment variable to your external-secrets pod to see if it works as a workaround? I think this might be related with #4934

**Comment by gazal-k** [comment]
> can you all try to add a `AWS_REGION` environment variable to your external-secrets pod to see if it works as a workaround? I think this might be related with [#4934](https://github.com/external-secrets/external-secrets/issues/4934)

I suppose we should have mentioned, we already use IRSA for the controller. As in, not fine grained IRSA associated with each SecretStore.

So, due to how IRSA works, the controller Pods already have `AWS_REGION` env var. The env section for controller Pods look like:

```yaml
    env:
    - name: AWS_STS_REGIONAL_ENDPOINTS
      value: regional
    - name: AWS_DEFAULT_REGION
      value: ap-southeast-2
    - name: AWS_REGION
      value: ap-southeast-2
    - name: AWS_ROLE_ARN
      value: arn:aws:iam::{accountId}:role/{role-name}
    - name: AWS_WEB_IDENTITY_TOKEN_FILE
      value: /var/run/secrets/eks.amazonaws.com/serviceaccount/token
```

**Comment by Skarlso** [comment]
Ugh, most likely something with AWS SDK v2. @Ilhan-Personal any ideas? 🙇

**Comment by karloscarrijozup** [comment]
Same issue here, for context we use Pod Identity, and this is the error I get on the daemonset:

```
eks-pod-identity-agent-tvscr eks-pod-identity-agent {"association-id":"a-1tlv7jypxfjslotbc","client-addr":"10.144.2.172:36220","cluster-name":"test1","from":"renewal-thread","level":"info","msg":"Removing credentials from cache, got non recoverable error: error getting credentials to cache: unable to fetch credentials from EKS Auth: operation error EKS Auth: AssumeRoleForPodIdentity, https response error StatusCode: 400, RequestID: e8233c5e-5d65-4355-bb64-39d6158b4eef, ExpiredTokenException: The token included in the request is expired: current date/time 2025-06-18T21:20:55.347735677Z must be before the expiration date/time 2025-06-18T20:45:00Z.","time":"2025-06-18T21:20:55Z"}
```

**Comment by Ilhan-Personal** [comment]
Looking

**Comment by Skarlso** [comment]
Thanks! :) Maybe it's scope related? Maybe try setting public scope? 🤔

**Comment by Ilhan-Personal** [comment]
Heyy @Skarlso why do you think it would be scope related?

also QQ, I noticed that the function to return webidentityroleprovider accepts an argument for region but it looks like I probably missed to include the region while setting up the config, But yes I'm not 100% sure I thought the credential chain would handle this since we're specifying the env var anyway 

https://github.com/external-secrets/external-secrets/pull/4940/files#diff-7716174091c7f7fad44cb0df854f13815330251a6d5bb610fc6966c74dcc9789R301

EDIT: 

The above is probably not related to the current issue but it could be a fix for a different issue 
https://github.com/external-secrets/external-secrets/issues/4934

**Comment by estevaofay** [comment]
Got the same issue:

```yaml
apiVersion: generators.external-secrets.io/v1alpha1
kind: ECRAuthorizationToken
metadata:
  name: ecr-gen
spec:
  region: sa-east-1
  auth:
    secretRef:
      accessKeyIDSecretRef:
        name: "ecr-creds"
        key: "AWS_ACCESS_KEY_ID"
      secretAccessKeySecretRef:
        name: "ecr-creds"
        key: "AWS_SECRET_ACCESS_KEY"
```

```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ecr-creds
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: ecr-creds
    creationPolicy: Owner
  data:
  - secretKey: AWS_ACCESS_KEY_ID
    remoteRef:
      key: ecr-auth
      property: AWS_ACCESS_KEY_ID
  - secretKey: AWS_SECRET_ACCESS_KEY
    remoteRef:
      key: ecr-auth
      property: AWS_SECRET_ACCESS_KEY
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "ecr-auth"
spec:
  refreshInterval: "1h"
  target:
    name: ecr-auth
    template:
      type: kubernetes.io/dockerconfigjson
      metadata:
        annotations:
          expiresAt: "{{ .expires_at }}"
      data:
        .dockerconfigjson: |
          {
            "auths": {
             {{ "{{ .proxy_endpoint | replace \"https://\" \"\" }}" }}: {
                "username": "{{ .username }}",
                "password": "{{ .password }}",
                "auth": "{{ printf "%s:%s" .username .password | b64enc }}"
              }
            }
          }
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ECRAuthorizationToken
          name: "ecr-gen"
```

This is the error I get
```
Secret "ecr-auth" is invalid: data[.dockerconfigjson]: Invalid value: "<secret contents redacted>": invalid character '9' looking for beginning of object key string
```


This is the live manifest I see in argocd

```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"external-secrets.io/v1beta1","kind":"ExternalSecret","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"nw-backend"},"name":"ecr-auth","namespace":"nw"},"spec":{"dataFrom":[{"sourceRef":{"generatorRef":{"apiVersion":"generators.external-secrets.io/v1alpha1","kind":"ECRAuthorizationToken","name":"ecr-gen"}}}],"refreshInterval":"1h","target":{"name":"ecr-auth","template":{"data":{".dockerconfigjson":"{\n 
      \"auths\": {\n   {{ .proxy_endpoint | replace \"https://\" \"\" }}:
      {\n      \"username\": \"\",\n      \"password\": \"\",\n      \"auth\":
      \"JSFzKDxuaWw+KTolIXMoPG5pbD4p\"\n    }\n 
      }\n}\n"},"metadata":{"annotations":{"expiresAt":""}},"type":"kubernetes.io/dockerconfigjson"}}}}
  creationTimestamp: '2025-06-21T21:25:48Z'
  generation: 4
  labels:
    app.kubernetes.io/instance: nw-backend
  name: ecr-auth
  namespace: nw
  resourceVersion: '4481308'
  uid: aeaec56c-1e28-4e17-b891-13de213fedd0
spec:
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ECRAuthorizationToken
          name: ecr-gen
  refreshInterval: 1h
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: ecr-auth
    template:
      data:
        .dockerconfigjson: |
          {
            "auths": {
             {{ .proxy_endpoint | replace "https://" "" }}: {
                "username": "",
                "password": "",
                "auth": "JSFzKDxuaWw+KTolIXMoPG5pbD4p"
              }
            }
          }
      engineVersion: v2
      mergePolicy: Replace
      metadata:
        annotations:
          expiresAt: ''
      type: kubernetes.io/dockerconfigjson
status:
  binding:
    name: ''
  conditions:
    - lastTransitionTime: '2025-06-21T21:25:48Z'
      message: could not update secret
      reason: SecretSyncedError
      status: 'False'
      type: Ready
  refreshTime: null
```

And if we decode `JSFzKDxuaWw+KTolIXMoPG5pbD4p` we get `!s(<nil>):%!s(<nil>)` which is the same thing I see in logs

to me it just looks like it didn't work at all and documentation has no examples (and one example with bad quotes that took me forever to debug)
