### ISSUE TITLE
Support for CAProvider field in gitlab provider

### ISSUE THREAD

**Issue by letajmal** [external-secrets/external-secrets#4938]
**Is your feature request related to a problem? Please describe.**
I have a self-hosted internal gitlab instance, the certificate is self-signed. I am not able to use the gitlab provider.

**Describe the solution you'd like**
Hashicorp vault and few others have a field called "CAProvider" to specify a custom CA certificate. It would be great if we have a similar feature for the gitlab provider

**Describe alternatives you've considered**
Using any other provider can save my day. I am currently using gitlab.com as an alternative. But thats not ideal for an on-prem environment.

**Additional context**

secret store
```yaml
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: gitlab-secret-store
spec:
  provider:
    # provider type: gitlab
    gitlab:
      url: https://gitlab.xxxx.com/
      auth:
        SecretRef:
          accessToken:
            name: gitlab-secret
            key: token
      projectID: "xxxx"
```

TLS verification is failing
```bash
Warning  ValidationFailed  16s (x5 over 29s)  secret-store  could not verify whether the gitlabClient is valid: Get "https://gitlab.xxxx.com/api/v4/projects/xxxx/variables": tls: failed to verify certificate: x509: certificate signed by unknown authority
```
