### ISSUE TITLE
AWS EKS v0.18 - Invalid Configuration: Missing Region

### ISSUE THREAD

**Issue by OliverRC** [external-secrets/external-secrets#4952]
**Describe the bug**
Upgraded from v0.14.3 -> v0.18.0 in AWS EKS but now I am getting errors:

```
could not validate provider: failed to refresh cached credentials, failed to retrieve credentials, operation error STS: AssumeRoleWithWebIdentity, failed to resolve service endpoint, endpoint rule error, Invalid Configuration: Missing Region
```

Example secret store:

```
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: my-app-secrets
  namespace: my-app
spec:
  provider:
    aws:
      auth:
        jwt:
          serviceAccountRef:
            name: my-app-account
      region: af-south-1
      service: SecretsManager
```

**To Reproduce**
1. Upgrade from 0.14.3 -> 0.18

**Expected behavior**
Either a upgrade doc with breaking changes so i can update some misconfiguration or it should work

**Additional Context**

* AWS EKS v1.30
* Service Accounts for Secret Store
* Checked IAM Policy
* Checked IAM Role and Trust Relationship
* STS endpoints are set to regional
