### ISSUE TITLE
1password SA token too long for the onepasswordSDK provider

### ISSUE THREAD

**Issue by alexis974** [external-secrets/external-secrets#4966]
**Describe the bug**

Passing the token for the 1passord service account result in a error because of its length
>  The SecretStore "1password" is invalid: spec.provider.onepasswordSDK.auth.serviceAccountSecretRef.key: Too long: may not be more than 253 bytes

**To Reproduce**

Kubernetes: 1.33
ES Chart version: 0.18.1

1. Follow 1password documentation to create a service account: https://developer.1password.com/docs/service-accounts/get-started/
2. Create the following manifest (this token is a totally randon string matching the exact length of the token provided by 1password)
```
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: 1password
spec:
  provider:
    onepasswordSDK:
      vault: k8s-talos
      auth:
        serviceAccountSecretRef:
          name: k8s-talos
          key: "ops_3wY7ckBe7Lqw6BUYyRpzZ4bYewyaU63yELfbtxhgLgEAJczEDpVHgHHEwWU8xD68bhkAupjjgja6sLNeoKyg3yW4ujt2Tb9seHvf3wY7ckBe7Lqw6BUYyRpzZ4bYewyaU63yELfbtxhgLgEAJczEDpVHgHHEwWU8xD68bhkAupjjgja6sLNeoKyg3yW4ujt2Tb9seHvf3wY7ckBe7Lqw6BUYyRpzZ4bYewyaU63yELfbtxhgLgEAJczEDpVHgHHEwWU8xD68bhkAupjjgja6sLNeoKyg3yW4ujt2Tb9seHvf3wY7ckBe7Lqw6BUYyRpzZ4bYewyaU63yELfbtxhgLgEAJczEDpVHgHHEwWU8xD68bhkAupjjgja6sLNeoKyg3yW4ujt2Tb9seHvf3wY7ckBe7Lqw6BUYyRpzZ4bYewyaU63yELfbtxhgLgEAJczEDpVHgHHEwWU8xD68bhkAupjjgja6sLNeoKyg3yW4ujt2Tb9seHvf3wY7ckBe7Lqw6BUYyRpzZ4bYewyaU63yELfbtxhgLgEAJczEDpVHgHHEwWU8xD68bhkAupjjgja6sLNeoKyg3yW4ujt2Tb9seHvf3wY7ckBe7Lqw6BUYyRpzZ4bYewyaU63yELfbtxhgLgEAJczEDpVHgHHEwWU8xD68bhkAupjjgja6sLNeoKyg3yW4ujt2Tb9seHvf3wY7ckBe7Lqw6BUYyRpzZ4bYewyaU63yELfbtxhgLgEAJczEDpVHgHHEwWU8xD68bhkAupjjgja6sLNeoKyg3yW4ujt2Tb9seHvf3wY7ckBe7Lqw6BUYyRpzZ4bYewyaU63yELfbtxhgLgEAJce"
```
3. You should now have an error about key length

**Expected behavior**A clear and concise description of what you expected to happen.

**Screenshots**

![Image](https://github.com/user-attachments/assets/39abcbd7-5359-4b21-be52-691df70487b5)
