### ISSUE TITLE
Error while try to create a SecretStore using Azure Key Vault with Managed Identity

### ISSUE THREAD

**Issue by smsilva** [external-secrets/external-secrets#520]
**Describe the solution you'd like**

I'd like to complete the `SecretStore` configuration using **Azure Managed Identity** as described [here](https://external-secrets.io/provider-azure-key-vault/#managed-identity-authentication) in the docs.

**Give us examples of the outcome**

After  installed the **ExternalSecrets** using Helm method, I have tryed to create a `SecretStore` following the docs using **Managed Identity**.

```bash
helm repo add external-secrets https://charts.external-secrets.io

helm install external-secrets \
   external-secrets/external-secrets \
    --create-namespace \
    --namespace external-secrets \
    --set installCRDs=true
```

I confirmed that the CRDs are present but I note that there's no field "authType" there:

```bash
kubectl api-resources | grep -E "NAME|SecretStore"

NAME                              SHORTNAMES   APIVERSION                             NAMESPACED   KIND
clustersecretstores               css          external-secrets.io/v1alpha1           false        ClusterSecretStore
secretstores                      ss           external-secrets.io/v1alpha1           true         SecretStore
```

```bash
kubectl explain SecretStore.spec.provider.azurekv

KIND:     SecretStore
VERSION:  external-secrets.io/v1alpha1

RESOURCE: azurekv <Object>

DESCRIPTION:
     AzureKV configures this store to sync secrets using Azure Key Vault
     provider

FIELDS:
   authSecretRef        <Object> -required-
     Auth configures how the operator authenticates with Azure.

   tenantId     <string> -required-
     TenantID configures the Azure Tenant to send requests to.

   vaultUrl     <string> -required-
     Vault Url from which the secrets to be fetched from.
```

Here is the context of `example-secret-store.yaml` file:

```yaml
apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: example-secret-store
spec:
  provider:
    azurekv:
      authType: ManagedIdentity
      tenantId: "a267367d-d04d-4a6b-84ef-0cc227ed6e9f"
      identityId: "c13f3be6-b665-4743-aafa-77544cbfb5e8"
      vaultUrl: "https://silvioswaspsandbox1.vault.azure.net"
```

```bash
kubectl apply -f example-secret-store.yaml
```

Result:

```bash
error: error validating "example-secret-store.yaml": error validating data: [ValidationError(SecretStore.spec.provider.azurekv): unknown field "authType" in io.external-secrets.v1alpha1.SecretStore.spec.provider.azurekv, ValidationError(SecretStore.spec.provider.azurekv): unknown field "identityId" in io.external-secrets.v1alpha1.SecretStore.spec.provider.azurekv, ValidationError(SecretStore.spec.provider.azurekv): missing required field "authSecretRef" in io.external-secrets.v1alpha1.SecretStore.spec.provider.azurekv]; if you choose to ignore these errors, turn validation off with --validate=false
```
