### ISSUE TITLE
"Skipping unmanaged store" when trying ESO on EKS + Secrets Manager

### ISSUE THREAD

**Issue by gdlx** [external-secrets/external-secrets#521]
Hello !
I'm trying to apply the EKS setup for SecretsManager with ESO `0.3.9` as explained here: https://external-secrets.io/provider-aws-secrets-manager/#eks-service-account-credentials

But I'm getting the following error in the ESO deployment log:

```
{"level":"info","ts":1639143362.4271448,"logger":"controllers.ExternalSecret","msg":"skipping unmanaged store","ExternalSecret":"demo/eso-test","SecretStore":"demo/aws-secrets-manager"}
```

Here is my `ServiceAccount` 

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::XXXXXXXXXXXX:role/my-service-manager-allowed-role
  name: aws-external-secrets
  namespace: demo
```

The `SecretStore`:
```yaml
apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: demo
spec:
  controller: external-secrets
  provider:
    aws:
      region: eu-west-3
      service: SecretsManager
      auth:
        jwt:
          serviceAccountRef:
            name: aws-external-secrets
```

The `ExternalSecret`:
```yaml
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: eso-test
  namespace: demo
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: eso-test
    creationPolicy: Owner
  data:
  - secretKey: eso-test
    remoteRef:
      key: my-test-secret
      property: foo
```

I'm wondering if the `auth.jwt.serviceAccountRef` syntax is actually managed since it's not in the `SecretStore` api doc: https://external-secrets.io/api-secretstore/
