### ISSUE TITLE
Add other k8s secret types to the docs

### ISSUE THREAD

**Issue by CayoM** [external-secrets/external-secrets#522]
**Describe the solution you'd like**
I would like to create Kubernetes Secrets type: kubernetes.io/basic-auth from the External-Secret.

**What is the added value?**
Secret refreshing will make internal secrets up to date with external secrets

**Give us examples of the outcome**
While trying to Sync the Secret in order to create a new Secret, data could not be fetched from IBM Secrets-Manager.

```
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: external-secret-test
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: test-secretstore
    kind: SecretStore
  target:
    name: test-credentials2
    creationPolicy: Owner
  data:
  - secretKey: test
    remoteRef:
      key: username_password/014a0b71-8da6-6827-2e10-ce3434df4133
```

This is the output i get when describing the ExternalSecret

```
Status:
  Conditions:
    Last Transition Time:  2021-12-10T19:32:36Z
    Message:               could not get secret data from provider: key "username_password/014a0b71-8da6-6827-2e10-ce3434df4133" from ExternalSecret "external-secret-test": remoteRef.property required for secret type username_password
    Reason:                SecretSyncedError
    Status:                False
    Type:                  Ready
Events:                    <none>
```

**Observations (Constraints, Context, etc):**
When trying with an arbitrary secret it works. The issue seems to be with "username_password".

**Comment by CayoM** [comment]
just found out i was missing "property: username".

Now im struggling on how to build a Basic-Auth secret around this using the username AND password.

**Comment by CayoM** [comment]
figured it out and leaving it here in case someone come across the same struggle:

```
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: external-secret-test
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: test-secretstore
    kind: SecretStore
  target:
    name: test-credentials2
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      data:
        username: "{{ .user | toString }}"
        password: "{{ .password | toString }}"
  data:
  - secretKey: user
    remoteRef:
      property: username
      key: "username_password/014a0b71-8da6-6827-2e10-ce3434df4133"
  - secretKey: password
    remoteRef:
      property: password
      key: "username_password/014a0b71-8da6-6827-2e10-ce3434df4133"
```

**Comment by knelasevero** [comment]
Reopening it so we leave an issue up for people to add other k8s secret types to this doc :)

https://external-secrets.io/guides-common-k8s-secret-types/

**Comment by xadereq** [comment]
I would add two examples for Hashicorp Vault (for others who may struggling with setup from docs on site):

for creating dockerconfigjson:

create file `registry.json` with dockerconfig e.g.

```json
{
    "auths": {
        "example.registry.com": {
            "auth": "ZXhhbXBsZTpleGFtcGxl"
        }
    }
}
```
then pass it to Vault using CLI:
```bash
vault kv put secret/registry dockerconfigjson=@registry.json
```
finally create and apply ExternalSecret kind
```yaml
---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: external-secret-test
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: test-secretstore
    kind: SecretStore
  target:
    name: test-registry
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ .dockerconfig | toString }}"
  data:
  - secretKey: dockerconfig
    remoteRef:
      key: hitduck/dev/registry
      property: dockerconfigjson
```

---
for TLS, i couldn't get it working using method with packing both crt and key into PKCS bundle, instead I've chosen to use pretty same approach as above:

```bash
vault kv put secret/tls cert=@tls.crt key=@tls.key
```

then

```yaml
---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: test-tls
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: test-backend
    kind: ClusterSecretStore
  target:
    name: test-tls
    template:
      type: kubernetes.io/tls
      data:
        tls.crt: "{{ .tlscert | toString }}"
        tls.key: "{{ .tlskey | toString }}"
  data:
  - secretKey: tlscert
    remoteRef:
      key: tls
      property: cert
  - secretKey: tlskey
    remoteRef:
      key: tls
      property: key
```

hope someone may find it useful

**Comment by xadereq** [comment]
I would add two examples for Hashicorp Vault (for others who may struggling with setup from docs on site):

for creating dockerconfigjson:

create file `registry.json` with dockerconfig e.g.

```json
{
    "auths": {
        "example.registry.com": {
            "auth": "ZXhhbXBsZTpleGFtcGxl"
        }
    }
}
```
then pass it to Vault using CLI:
```bash
vault kv put secret/registry dockerconfigjson=@registry.json
```
finally create and apply ExternalSecret kind
```yaml
---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: external-secret-test
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: test-secretstore
    kind: SecretStore
  target:
    name: test-registry
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ .dockerconfig | toString }}"
  data:
  - secretKey: dockerconfig
    remoteRef:
      key: registry
      property: dockerconfigjson
```

---
for TLS, i couldn't get it working using method with packing both crt and key into PKCS bundle, instead I've chosen to use pretty same approach as above:

```bash
vault kv put secret/tls cert=@tls.crt key=@tls.key
```

then

```yaml
---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: test-tls
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: test-backend
    kind: ClusterSecretStore
  target:
    name: test-tls
    template:
      type: kubernetes.io/tls
      data:
        tls.crt: "{{ .tlscert | toString }}"
        tls.key: "{{ .tlskey | toString }}"
  data:
  - secretKey: tlscert
    remoteRef:
      key: tls
      property: cert
  - secretKey: tlskey
    remoteRef:
      key: tls
      property: key
```

hope someone may find it useful
