### ISSUE TITLE
Fetch and store plaintext from AWS Secrets Manager without attempting to parse it 

### ISSUE THREAD

**Issue by nickpetrovic** [external-secrets/external-secrets#526]
**Describe the solution you'd like**
The ability to fetch and store plaintext from AWS Secrets Manager without attempting to parse it into JSON or anything else.

**What is the added value?**
We may have different formats for our secrets. My use case is using a simple dot env file format.

**Give us examples of the outcome**
I was thinking the `dataFrom` attribute would take the entire content of the AWS Secret and write it to some top level key in a K8s Secret. 

An example of the plaintext secret
```
DB_ENGINE=something
DB_HOST=something
DB_USER=something
DB_PASS=something
```

Then the ExternalSecret
```yaml
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: backend
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: external-secrets
  target:
    name: backend
  dataFrom:
  - key: backend
```

Which would look something like this secret
```yaml
apiVersion: v1
kind: Secret
type: Opaque
data:
  # name of the key under dataFrom
  backend: REJfRU5HSU5FPXNvbWV0aGluZwpEQl9IT1NUPXNvbWV0aGluZwpEQl9VU0VSPXNvbWV0aGluZwpEQl9QQVNTPXNvbWV0aGluZwo=
```

But instead, it looks like its always trying to parse the plain text.
```json
{"level":"error","ts":1639407180.8585856,"logger":"controllers.ExternalSecret","msg":"could not reconcile ExternalSecret","ExternalSecret":"external-secrets/backend","SecretStore":"/external-secrets","error":"could not get secret data from provider: key \"backend\" from ExternalSecret \"backend\": unable to unmarshal secret backend: invalid character 'D' looking for beginning of value","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.3/pkg/internal/controller/controller.go:298\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.3/pkg/internal/controller/controller.go:253\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.3/pkg/internal/controller/controller.go:214"}
```

I've tried using an inline template, but it still seems to want to parse the plaintext.
```yaml
kind: ExternalSecret
spec:
  target:
    template:
      type: Opaque
      data:
        backend: |
          {{ . | toString }}
```

**Observations (Constraints, Context, etc):**
Chart version: 0.3.9
Kubernetes version: 1.21 on EKS

**Comment by knelasevero** [comment]
You don't need to use the templating functionality. Also no need to use the dataFrom functionality. You can use the data field.
```
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: backend
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: external-secrets
  target:
    name: backend                                          # this is the name of the 'Kind: Secret' in the cluster
  data:
  - secretKey: backend                                   # this is the key inside the new 'Kind: Secret' in the cluster
    remoteRef:
      key: backend                                            # this is the name of the secret in the external provider
  ```

**Comment by knelasevero** [comment]
Closing this one, feel free to reopen if you still find issues with it :)

**Comment by gempesaw** [comment]
this can certainly be chalked up to me failing at reading comprehension, but i spent a while browsing the existing ESO documentation and couldn't figure out how to accomplish this (just dump whatever is in AWS SecretsManager into a secret, without having to parse JSON)

perhaps there's somewhere in that the example could go in the docs to make it easier to find? :)

----

regardless, thanks very much for your ESO contribs and especially those comments describing on `target.name`, `data[].secretKey`, and `data[].remoteRef.key`, i finally understand what's going on :)

**Comment by gusfcarvalho** [comment]
hi @gempesaw ! There are two ways to "dump whatever".

First one, for one and only secret, with data operation:
```
data:
- secretKey: your-target-k8s-secret-key
  remoteRef:
    key: your-aws-sm-secret-name
```
This will fetch the content of `your-aws-sm-secret-name` as is and put it into a k8s secret key.
So if you have a secret like
```
{"foo":"bar"}
```
and you set this block like this example:
```
data:
- secretKey: a-json
  remoteRef:
    key: my-secret #with {"foo":"bar"}
```
will generate:
```
apiVersion: v1
Kind: Secret
...
data: 
  a-json: '{"foo":"bar"}'
  ```
 The other way is with `dataFrom.find` which will fetch secrets matching a given name:
 ```
 dataFrom:
 - find:
     name:
       regex: "path/to/ssm/*
 ```
 will put every secret content in a k8s secret with the key being the origina lsecret name:
 ```
 apiVersion: v1
 kind: Secret
 ...
 data:
   path_to_secret_1: contents-of-secret-1
   path_to_secret_2: contents-of-secret-2
   path_to_secret_but_this_one_is_nested: contents-of-nested-secret
   ```
   
In order to do more advanced stuff like matching the k8s secret Keys to your awssm secret keys, you would need to do some sort of templating. Also, IIRC, ESO only supports YAML or JSON parsing as of right now.
