### ISSUE TITLE
Disambiguate Vault namespaces for auth and secret retrieval 

### ISSUE THREAD

**Issue by cnmcavoy** [external-secrets/external-secrets#537]
**Describe the solution you'd like**
The current `SecretStore` and `ClusterSecretStore` CRD specification for the Vault provider has a `namespace` field at the top-level. This field is overloaded, it is used both for authenticating with the cluster, as well as the location of the secret fetched and retrieved into kubernetes. However, if secrets are stored in a namespace in Vault, but the auth backend is configured on the root namespace, then secrets can not be fetched. External Secrets will try and authenticate with the namespace, which inherits the auth method of the root, but does not have it mounted at the namespace level. See the [Vault namespace architecture](https://www.vaultproject.io/docs/enterprise/namespaces#architecture) for details.

Ideally, the SecretStore of ClusterSecretStore spec would contain an additional optional field, `vaultAuthNamespace` (or perhaps `vaultNamespace` if that is too wordy), which when not empty, would be used as the authentication mount for vault. 

Note: Because `""` represents the root namespace, we need to note in the docs to use "root" instead to indicate that the root namespace is intended. Using the empty string `""` is problematic and confusing for users (empty strings usually indicate an unused or unset field and could be stripped). Instead, [Vault special-cases the namespace name "root" and redirects it to the root namespace.](https://github.com/hashicorp/vault/issues/5987)

**What is the added value?**
Vault Enterprise users will no longer need to explicitly configure auth backends for each Vault namespace in use with External Secrets. Auth backends can be defined at the root namespace and configured only once if desired.

**Give us examples of the outcome**

Example `SecretStore` spec for Vault:

```yaml
apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: example
  namespace: example-ns
spec:
  provider:
    vault:
      server: "https://vault.acme.org"
      path: "secret"
      version: "v2"
      namespace: "a-team"
      vaultAuthNamespace: "root"
```

**Comment by cnmcavoy** [comment]
After discussing some with @mbillow he suggested a `SecretStore` in this format:
```yaml
apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: example
  namespace: example-ns
spec:
  provider:
    vault:
      server: "https://vault.acme.org"
      path: "a-team/secret"
      version: "v2"
      namespace: "root"
```

Which I tested and was able to successfully auth External Secrets against the root namespace and populated the secret from the target namespace by setting the namespace as a prefix in the path + root namespace in the `SecretStore` crd. So we can follow that pattern for Vault Enterprise and won't need this.
