### ISSUE TITLE
Creating Dockerconfigjson from ExternalSecrets leads to parsing error

### ISSUE THREAD

**Issue by CayoM** [external-secrets/external-secrets#543]
**Describe the solution you'd like**
I would like to be able to prepare a Dockerconfig string, store it on IBM-Cloud Secrets Manager and then Build a Docker Pull Secret from an ExternalSecret.

**What is the added value?**
Doing so, i will be able to store pullsecrets on a git repo and even sync it with my cluster via gitops.

**Give us examples of the outcome**
1) Im preparing the string as following:
```
kubectl create secret docker-registry regcred \
        --docker-server="test.test.com" --docker-username="testuser" \
        --docker-password="testpass" \
        --docker-email="testmail@local.com" --output=json \
        --dry-run=client | jq '.data.".dockerconfigjson"' | sed 's/"//g'

OUTPUT: eyJhdXRocyI6eyJ0ZXN0LnRlc3QuY29tIjp7InVzZXJuYW1lIjoidGVzdHVzZXIiLCJwYXNzd29yZCI6InRlc3RwYXNzIiwiZW1haWwiOiJ0ZXN0bWFpbEBsb2NhbC5jb20iLCJhdXRoIjoiZEdWemRIVnpaWEk2ZEdWemRIQmhjM009In19fQ==
```

2) Then im storing it on a simple arbitrary secret on Secrets Manager (IBM Cloud).

3) Create an ExternalSecret to build me the dockerpull secret:
```
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: external-secret-docker-pull
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: cayo-test-secretstore
    kind: SecretStore
  target:
    name: docker-pull-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ .dockerpullsecret | toString }}"
  data:
  - secretKey: dockerpullsecret
    remoteRef:
      key: "05f113a2-e12c-45a7-096c-a11d336a1d5b"
```

This leads to following error:
```
{"level":"error","ts":1640079079.8139832,"logger":"controllers.ExternalSecret","msg":"could not reconcile ExternalSecret","ExternalSecret":"cayo-test-dev/external-secret-docker-pull","SecretStore":"cayo-test-dev/cayo-test-secretstore","error":"Secret \"docker-pull-secret\" is invalid: data[.dockerconfigjson]: Invalid value: \"<secret contents redacted>\": invalid character 'e' looking for beginning of value","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.3/pkg/internal/controller/controller.go:298\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.3/pkg/internal/controller/controller.go:253\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.3/pkg/internal/controller/controller.go:214"}
```

**Observations (Constraints, Context, etc):**

I have googled a bit about this error and even found about it on the official kubernetes documentation (https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/)

_If you get the error message error: no objects passed to create, it may mean the base64 encoded string is invalid. If you get an error message like Secret "myregistrykey" is invalid: data[.dockerconfigjson]: invalid value ..., it means the base64 encoded string in the data was successfully decoded, but could not be parsed as a .docker/config.json file._

However, once i just use the above command to create the secret without the --dry-run option, it works. If i manually create a secret using the string, it works also:
```
apiVersion: v1
kind: Secret
metadata:
  name: myregistrykey
data:
  .dockerconfigjson: eyJhdXRocyI6eyJ0ZXN0LnRlc3QuY29tIjp7InVzZXJuYW1lIjoidGVzdHVzZXIiLCJwYXNzd29yZCI6InRlc3RwYXNzIiwiZW1haWwiOiJ0ZXN0bWFpbEBsb2NhbC5jb20iLCJhdXRoIjoiZEdWemRIVnpaWEk2ZEdWemRIQmhjM009In19fQ==
type: kubernetes.io/dockerconfigjson
```

As soon as i try to create this secret via ExternalSecret, it fails with the error above.

Any help is highly appreciated.

**Comment by knelasevero** [comment]
You don't need to prepare it. What you put in the secret in the external provider will be the contents of the dkconfigjson with no manipulation. 

When we pass it to the ES with .dockerconfigjson: "{{ .dockerpullsecret | toString }}", it will receive the value, but when kubernetes API creates the secret, it will base64 encode it, you don't need to do it.

You can check an example here: https://external-secrets.io/guides-common-k8s-secret-types/

It goes through it with GCPsm, but it will be the same for any provider.

**Comment by knelasevero** [comment]
I am closing this issue, feel free to re-open! :)

**Comment by CayoM** [comment]
@knelasevero thanks for the hint. I was aware of this piece of documentation, however i was exploring the possibilities to create the secret and was wondering why i can create a "normal" Secret with the encrypted string, but can't create a ExternalSecret with the same encrypted string (apparently due the Operator trying to encrypt the string again).

Since im trying to achieve some sort of full automation around this, im using the IBM Cloud API to create the secrets and tbh it will be a pita to come around the escaping in order to deliver the correct payload to the api, that is why the encrypted string would be a much better option for me.

However, is this in any form a bug or a feature request, since the operator does not check if the string is encrypted? I would expect a check to validate if an encryption is needed to work in the same way a kubectl apply/create does (as mentioned, a normal secret could be created without issues).

**Comment by CayoM** [comment]
i could work around this by chaining the helper functions. Basically decoding the bytes and then transforming to a string. Did take some time to try different things out, but its working. This is the final result if someone come across the same issue:

```
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: external-secret-docker-pull
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: {{ project_name }}-secretstore
    kind: SecretStore
  target:
    name: docker-pull-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
{% raw %}
        .dockerconfigjson: "{{ .dockerpullsecret | base64decode | toString }}"
{% endraw %}
  data:
  - secretKey: dockerpullsecret
    remoteRef:
      key: "xxxxxxxxxxxxxxxxxxxxx"
```
