### ISSUE TITLE
GCP Workload Identity on SecretStore not working

### ISSUE THREAD

**Issue by nokernel** [external-secrets/external-secrets#546]
**Describe the solution you'd like**
GCP Workload Identity on SecretStore not working. Using helm chart version 0.3.10 to install.

Following the [doc here](https://external-secrets.io/provider-google-secrets-manager/#using-service-accounts-directly)

**Give us examples of the outcome**

Ability to reference Google service account on SecretStore.

**Observations (Constraints, Context, etc):**

This manifest fails to deploy
```
apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: mystore
spec:
  provider:
    gcpsm:
      projectID: my-project-id
      auth:
        workloadIdentity:
          clusterLocation: us-central1-a
          clusterName: myCluster
          serviceAccountRef:
            name: service-account-name
```

With error
```
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(SecretStore.spec.provider.gcpsm.auth): unknown field "workloadIdentity" in io.external-secrets.v1alpha1.SecretStore.spec.provider.gcpsm.auth, ValidationError(SecretStore.spec.provider.gcpsm.auth): missing required field "secretRef" in io.external-secrets.v1alpha1.SecretStore.spec.provider.gcpsm.auth]
```
