### ISSUE TITLE
OLM OperatorConfig fails to install

### ISSUE THREAD

**Issue by trevor-viljoen** [external-secrets/external-secrets#563]
This issue would be better created in the `external-secrets-helm-operator `repo, but Issues don't seem to be enabled over there. I am trying to install External Secrets via the Operator Hub in OpenShift 4.8.24. I am able to create a subscription and install the operator. However, when trying to create an `OperatorConfig` using the sample provided in `external-secrets/external-secrets-helm-operator`, it fails with this error.

```
failed to install release: rendered manifests contain a resource that already exists. Unable to continue with install: CustomResourceDefinition "clustersecretstores.external-secrets.io" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "sample"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "external-secrets-operator"
```
This `OperatorConfig` fails with the same error as above.
```
apiVersion: operator.external-secrets.io/v1alpha1
kind: OperatorConfig
metadata:
  annotations:
    meta.helm.sh/release-name: external-secrets
    meta.helm.sh/release-namespace: external-secrets-operator
  name: external-secrets
  namespace: external-secrets-operator
  labels:
    app.kubernetes.io/managed-by: Helm
spec:
  nodeSelector: {}
  imagePullSecrets: []
  podLabels:
    app.kubernetes.io/managed-by: Helm
  resources: {}
  leaderElect: false
  fullnameOverride: ''
  affinity: {}
  prometheus:
    enabled: true
    service:
      port: 8080
  podSecurityContext: {}
  scopedNamespace: ''
  extraArgs: {}
  securityContext: {}
  rbac:
    create: true
  replicaCount: 1
  nameOverride: ''
  serviceAccount:
    annotations: {}
    create: true
    name: ''
  installCRDs: false
  image:
    pullPolicy: IfNotPresent
    repository: ghcr.io/external-secrets/external-secrets
    tag: ''
  tolerations: []
  extraEnv: []
  priorityClassName: ''
  podAnnotations:
    meta.helm.sh/release-name: external-secrets
    meta.helm.sh/release-namespace: external-secrets-operator
```
