### ISSUE TITLE
Support CyberArk Conjur as backend vault provider

### ISSUE THREAD

**Issue by 250788** [external-secrets/external-secrets#588]
**Describe the solution you'd like**
Add CyberArk Conjur as additional vault provider

**What is the added value?**
Enlarge the supported provider list for external-secrets 

**Give us examples of the outcome**
```
apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      CONJUR_APPLIANCE_URL: "https://conjur-server.svc.cluster.local/api"
      CONJUR_AUTHN_URL: "https://conjur-server.svc.cluster.local/api/authn-k8s/ocp"
      CONJUR_ACCOUNT: "cyberark"
      CONJUR_AUTHN_LOGIN: "host/conjur/authn-k8s/ocp/apps/testapp/service_account/testapp"
      CONJUR_SSL_CERTIFICATE: "ssl-certificate"
      CONJUR_SECRET: "/etc/secret/secret.yaml
```

_Secret.yaml_
DBAddress: mysql.cyberarkdemo.com
DBName: hello-world
DBPort: 3306
DBUsername: !var vault/testapp/testapp/Database-MySQL-mysql-testapp/username
DBPassword: !var vault/testapp/testapp/Database-MySQL-mysql-testapp/password
