### ISSUE TITLE
Add a Mock/Fake provider to make it easier to develop locally

### ISSUE THREAD

**Issue by knelasevero** [external-secrets/external-secrets#605]
Right now it is possible to spin up vault or localstack to develop locally without a Cloud dependency, but this could also be a bit of a hassle for a quick change to the controller or something like that.

A Mock/Fake provider would be nice here. I see some options:

1- Always responds a default value on a specific key name.

2- Reads values from file/volume 

3- Maybe this is unnecessary when we have https://github.com/external-secrets/external-secrets/issues/547? You can have the whole loop just reading from stuff in your cluster with the k8s provider.

Leaving this up for discussion.

**Comment by knelasevero** [comment]
If this is added, we need to add proper docs in the developer guide. Even if we think mock provider is not needed, we need to add something to the dev guides regarding local setup for the whole control loop to happen without big dependencies. We can close this issue based on those assumptions

**Comment by willemm** [comment]
I think you should be able to do this with #559 and httpbin?

**Comment by knelasevero** [comment]
Yeah, also possible :) we discussed this here: https://kubernetes.slack.com/archives/C017BF84G2Y/p1642156165083800

But maybe a fake provider still makes sense? Like fewer steps and something right away ready to see the whole control loop?

**Comment by moolen** [comment]
The use-case is to just test out e.g. the template engine, `creationPolicy` or value precedence, or is there something else?
IMO the user should be in control of the values (instead of having pre-defined mock values).
I imagine something stupidly simple like this, this should be really easy to implement:

```yaml
apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: example
  namespace: example-ns
spec:
  provider:
    fake:

    # simple key/value pairs
    - key: "/foo/bar"
      value: "shazaam"

     # something that can be used with dataFrom to extract via property field
    - key: "foo/example.json"
      value: {"nested":{"foo": "bar"}}

     # potentially add more fields for metadata if needed, see #613
    - key: "foo/example.json"
      value: {"nested":{"foo": "bar"}}
      tags: [one, two]

    # we can only use base64 encoded binary values, tho
    - key: "foo/binary"
      value: "MTIzNAo=" # base64 value

```
