### ISSUE TITLE
Azure Workload Identity (Service Account auth)

### ISSUE THREAD

**Issue by moolen** [external-secrets/external-secrets#611]
MS just announced a new Azure Workload Identity feature: https://cloudblogs.microsoft.com/opensource/2022/01/18/announcing-azure-active-directory-azure-ad-workload-identity-for-kubernetes/

repo: https://github.com/Azure/azure-workload-identity
docs: https://azure.github.io/azure-workload-identity/docs/quick-start.html

It provides authentication based on annotated service accounts. We want to use that from a SecretStore similarly to our AWS and GCP providers.
This feature is currently being implemented in `csi-secret-store` [azure provider](https://github.com/Azure/secrets-store-csi-driver-provider-azure) in \#778

Proposed SecretStore:

```yaml
apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: az-store
spec:
  provider:
    azurekv:
    # WorkloadIdentity requires as ClientID and a Service Account Token.
      authType: WorkloadIdentity
      tenantId: "d3bc2180-xxxx-xxxx-xxxx-154105743342"
      vaultUrl: "https://my-keyvault-name.vault.azure.net"
      serviceAccountRef:
        name: my-serviceaccount
        namespace: "..." # only valid for Kind=ClusterSecretStore
      authSecretRef:
        clientId:
          name: azure-secret-sp
          key: ClientID

```

Service Account Tokens must have a specific aud set: `api://AzureADTokenExchange` ([see here](https://azure.github.io/azure-workload-identity/docs/quick-start.html))
