### ISSUE TITLE
Add missing rbac to helm chart when using HCP vault

### ISSUE THREAD

**Issue by ops-hummus** [external-secrets/external-secrets#619]
When trying to setup external-secrets (basically migrating from KES to ESO) with vault enterprise using the helm chart, it's simply impossible to understand why we are getting 403 permission denied. After a bit of digging I understand that the operator's service account can't function without `system:auth-delegator` clusterrole, which isn’t included in the chart. The operator wasn’t helpful since the only error I saw was 

```{"level":"error","ts":1642804754.8685496,"logger":"controllers.ExternalSecret","msg":"could not get provider client","ExternalSecret":"external-secrets/vault-example","SecretStore":"external-secrets/vault-backend","error":"error from Vault request: Error making API request.\n\nURL: POST <URL>:8200/v1/auth/kubernetes/login\nCode: 403. Errors:\n\n* permission denied","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.3/pkg/internal/controller/controller.go:298\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.3/pkg/internal/controller/controller.go:253\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.3/pkg/internal/controller/controller.go:214"}```

and from the ExternalSecret all I got was error 403 permission denied to /auth/kubernetes/login.

My secretstore yaml is this:

```
apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: external-secrets
spec:
  provider:
    vault:
      server: url
      path: secret
      version: v2
      namespace: admin/kubernetes
      auth:
        kubernetes:
          mountPath: kubernetes
          role: test
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
```

I added the host url and ca, and the sa jwt token.

Adding this ClusterRoleBinding fix the issue
```apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: role-tokenreview-binding
  namespace: external-secrets
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: external-secrets
  namespace: external-secrets
