### ISSUE TITLE
Secret Data in unexpected format - Hashicorp Vault SecretStore

### ISSUE THREAD

**Issue by derekwilliamsliquidx** [external-secrets/external-secrets#649]
When using Hashicorp Vault as my backend secret store, if a secret is json data only, and not key/value, the external secrets api returns an error trying to read the secret `could not get secret data from provider: key "<VAULT_KEY>" from ExternalSecret : secret data not in expected format'`

K8s Version: 1.21.2
External Secret Version: v0.3.8

When JSON is the format of the secret, the external secrets api should accept that secret data.

**Comment by gusfcarvalho** [comment]
Hi @derekwilliamsliquidx ! Can you provide more details on how your HashiVault is configured, and your `ExternalSecrets` manifest, please?

Are you trying to use `key/value` secret engine on Vault, is this correct?

**Comment by derekwilliamsliquidx** [comment]
Yes of course, We have a folder in vault named the application. Inside the folder are two secrets: `env` and `config`. In our containers, config gets mounted as a volume to our container. In the `config` secret the data is formatted as json rather than key/value. I cannot find a documented api that supports this condition.

```
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: {{ template "name" . }}-config-files
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: {{ template "name" . }}-config-files
  dataFrom:
  - key: {{ template "environmentName" . }}/{{ template "name" . }}/config
```
