### ISSUE TITLE
Support Regional AWS STS VPC Endpoints for EKS Service Account credentials

### ISSUE THREAD

**Issue by IanTurtle** [external-secrets/external-secrets#651]
**Describe the solution you'd like**
Use the regional STS VPC endpoint when creating a SecretStore/ExternalSecret using EKS Service Account credentials.

**What is the added value?**
Allow External Secrets to be created in a private AWS environment

**Observations (Constraints, Context, etc):**

The particular error we are receiving:
`
Message:               could not get secret data from provider: key "secret1" from ExternalSecret "example2": WebIdentityErr: failed to retrieve credentials
caused by: RequestError: send request failed
caused by: Post "https://sts.amazonaws.com/": dial tcp: i/o timeout
    Reason:  SecretSyncedError
`
ServiceAccount:
```
kubectl describe serviceaccount/my-serviceaccount 
Name:                my-serviceaccount
Namespace:           default
Labels:              <none>
Annotations:         eks.amazonaws.com/role-arn: <role>
                     eks.amazonaws.com/sts-regional-endpoints: true
Image pull secrets:  <none>
Mountable secrets:   my-serviceaccount-token-9g9v4
Tokens:              my-serviceaccount-token-9g9v4
Events:              <none>
```

SecretStore:
```
apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: secretstore-service-account
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-west-1
      auth:
        jwt:
          serviceAccountRef:
            name: my-serviceaccount
```
ExternalSecret
```
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: example2
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secretstore-service-account
    kind: SecretStore
  target:
    name: my-secret
    creationPolicy: Owner
  data:
  - secretKey: secret1
    remoteRef:
      key: secret1
```

**Comment by moolen** [comment]
Would it work for you to define that on a per-controller level (i.e. all aws SecretStores will use that endpoint?)? Or do you require it per service-account?

**Comment by IanTurtle** [comment]
Yes, having all secret stores point to a single endpoint should be good - so looks like above should be sufficient.

Do I set these when installing the operator?

**Comment by moolen** [comment]
When you use helm you can set them with using `extraEnv` like here:
 https://github.com/external-secrets/external-secrets/blob/40ff991e17127dca39c92d9e8b82238863bdc79d/e2e/k8s/eso.values.yaml#L5-L11

**Comment by IanTurtle** [comment]
I have set those and the pod is running with the environment variable set and I can see it is using the regional endpoint - but it I can see it is still failing:

`
    Message:               could not get secret data from provider: key "secret1" from ExternalSecret "example2": WebIdentityErr: failed to retrieve credentials
caused by: RequestError: send request failed
caused by: Post "https://sts.eu-west-1.amazonaws.com/": dial tcp: i/o timeout
`

I have logged onto one of the underlying ec2 instances and can see that the endpoint is resolvable and i can access it on 443:
```
telnet sts.eu-west-1.amazonaws.com 443
Trying XXX.XXX.XXX.XXX...
Connected to sts.eu-west-1.amazonaws.com.
Escape character is '^]'.
```

Are there any other parameters I need to set?

**Comment by moolen** [comment]
Please try to debug the connectivity issue from inside the pod. Could be that you have `vpc-cni` (and a SG that prevents outgoing traffic) or you have a NetworkPolicy that denies traffic to that endpoint.

**Comment by IanTurtle** [comment]
I have done some digging and looks like it is potentially DNS related. I have tried telnetting to the IP of our VPC endpoint from within the a pod in our cluster on port 443 and it resolves successfully. However when I do an nslookup it fails saying connection timed out; no servers could be reached. 

I wasn't able to successfully exec into the external-secrets operator pod, so I am using a simple image to test (the RedHat UBI image with telnet, nslookup and ping) - so not sure if this is the actual cause, or if it is just because of the test image I am using.

Is there a way to test what the endpoint name in the external-secrets operator pod is resolving to?

**Comment by moolen** [comment]
There is a way. But you have to use the latest/main image and CRDs. We have a [guide here](https://external-secrets.io/guides-using-latest-image/).

Then you can do the following:

```yaml
apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: webhook
spec:
  provider:
    webhook:
      url: "http://example.foo/"
      result:
        jsonPath: ""
---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: webhook
  target:
    name: example-sec
  data:
  - secretKey: example
    remoteRef:
      key: tmp.json
```

That will issue a HTTP request to `example.foo`. We expect it to fail. With `kubectl describe es secret` we can see:

```
could not get secret data from provider: key "tmp.json" from ExternalSecret "secret": 
failed to call endpoint: Get "http://example.foo/": dial tcp 10.83.183.31:80: i/o timeout
``` 
Here you can see the IP address that was resolved by the pod.
