### ISSUE TITLE
Is there any equivalent param as POLLER_INTERVAL_MILLISECONDS?

### ISSUE THREAD

**Issue by inductor** [external-secrets/external-secrets#699]
**Describe the solution you'd like**

In KES, we have the following params to reduce AWS Secrets Manager cost.

```yaml
      - name: env.POLLER_INTERVAL_MILLISECONDS # This parameter defines the frequency of API calls to AWS Secrets Manager. Modify this if necessary.
        value: "120000" # By default this was 10000 but it was too expensive
      - name: env.WATCH_TIMEOUT # This parameter defines timeout value to restart control loop not to hang up in Node.js environment ref. https://github.com/external-secrets/kubernetes-external-secrets/issues/362
        value: "150000"
```

What is available parameter that works similarly for this operator?

**What is the added value?**
Explain the value that it adds. e.g. "Secret refreshing will make internal secrets up to date with external secrets".

**Give us examples of the outcome**

Provide templates if you are proposing changes in the CRD. Provide example workflows or code snippets if they make sense to present.

**Observations (Constraints, Context, etc):**

Give here all extra information that could be interesting. Such as Golang version and Kubernetes version if you are reporting a bug/problem. You can also foresee technical constrains like "this could only be implementing using this specific technology or approach, because of this and that".
