### ISSUE TITLE
Can't create Secret with custom `target/template/data` values and values retrieved from AWS Secrets Manager Plaintext

### ISSUE THREAD

**Issue by leppez** [external-secrets/external-secrets#710]
**Be able to create a a secret with both AWS Secrets Manager Plaintext and set custom `target/template/data`**
Right now, it seems I can't create a secret with a combination and key/values retrieves from AWS Secrets Manager Plaintext secret and custom values set in `target/template/data`.

**What is the added value?**
Explain the value that it adds. e.g. "Secret refreshing will make internal secrets up to date with external secrets".
Gives more flexibility when creating secrets to be able to specify additional fields than what's being retrieved from AWS Secrets Manager.

**Give us examples of the outcome**
```
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: bitbucket-project-credentials-template
  namespace: argocd
spec:
  data:
  - remoteRef:
      key: <AWS Secrets Manager Secret name>
    secretKey: <key to set in Kind: Secret>
  refreshInterval: 10m
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secretstore-aws
  target:
    creationPolicy: Owner
    name: <name of Kind: Secret> 
    template:
      data:
        type: .....
        url: .....
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repo-creds
```

With the above template, external-secrets can't set the appropriate value retrieved from AWS Secret Manager but if I remove the `target/template/data` portion of the declaration, external-secrets is able to set and retrieve the value. It seems that there's a limitation that's preventing it from setting both custom values and values retrieves from AWS Secrets Manager.

**Comment by gusfcarvalho** [comment]
Hi @leppez! I didn’t quite understand your issue.
You are trying to add more information to a secret using the template, is that it?

Have you tried adding your secret keys with
```
data:
   type: “fixed string”
   my-secret-key: “{{.my-key | toString }}”
``
?

**Comment by leppez** [comment]
yes, I want to create a secret with multiple keys. one of those keys are arbitrary values that I set in the `external-secret` YAML itself the other needs to be retrieves from AWS Secrets Manager.

**Comment by moolen** [comment]
If i understand you correctly, you would expect the keys `type`, `url` **and** `mysecret` to be present from this example?
What you actually get is `type` and `url`.

```yaml
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: bitbucket-project-credentials-template
spec:
  data:
  - remoteRef:
      key: foo/bar/baz
    secretKey: mysecret # from here
  # ...
  target:
    template:
      data:
        type: "mytype" # here
        url: "http://example.com" # and here
```

This was implemented intentionally: when you define a template the controller will use that exact template to construct a `Kind=Secret`. You can't mix both "inputs": data/dataFrom *and* template.data. 
If you want to have the values you need to define them in the `template.data` map.

```yaml
spec:
  target:
    template:
      data:
        mysecret: "{{ .mysecret | toString }}"
        type: "mytype"
        url: "http://example.com"
```

I totally understand that it didn't do what you expect - i'm wondering if this should actually be the desired behavior..
