### ISSUE TITLE
Support binary/Base64-encoded secret values

### ISSUE THREAD

**Issue by stephen-dexda** [external-secrets/external-secrets#712]
**Describe the solution you'd like**

I have binary secret data, which I am storing in an external secret provider in Base64-encoded form. I want to be able to inject this Base64 data directly as a Secret value.

This isn't currently possible as ExternalSecrets template values are expected to be strings, which are then Base64-encoded into the K8s Secret values.

**What is the added value?**
Syncing of K8s Secret values that are binary data are supported.

**Observations (Constraints, Context, etc):**

* Before the "fix" for https://github.com/external-secrets/external-secrets/issues/125 was applied, it looks like this would have been possible.
* Previously discussed (by others) at https://github.com/external-secrets/external-secrets/discussions/581.
* A key like `.spec.target.template.valueType`, defaulting to `string` could be used, and if its value is instead `base64`, then the value output by the template would be would be assumed to be Base64-encoded already, and would then not be Base64-encoded a second time before creating the Secret.

**Comment by stephen-dexda** [comment]
To clarify, this is for secrets stored on the provider backend as JSON, e.g.:

```
{
  "foo": "[b64-encoded binary data]",
  "bar": "[b64-encoded string data]"
}
```

It's possible to work around this, at least on AWS Secrets Manager, by storing the secret as a binary blob (`SecretBinary` on AWS) and then specifying all of the K8s Secret keys in the ExternalSecret via the `data` key (see below), but this prevents for example being able to use`dataFrom`, which would be possible with the above provider secret data, and means that a separate secret has to be created on the provider for at least each of the binary data values.

```
  data:
  - secretKey: foo
    remoteRef:
      key: aws-binary-secret-key
...

**Comment by moolen** [comment]
Hey! If i understand your issue correctly it boils down to not being able to extract base64-encoded properties from a secret value.

So you have the following value in AWS SM with key `dev/example`:
```json
{
  "foo": "[b64-encoded binary data]",
  "bar": "[b64-encoded string data]"
}
```

and you want to create a secret with:

```
foo: [binary value]
bar: [binary value]
```

**Comment by stephen-dexda** [comment]
No, that's not correct.

For example, I have the following:

```json
{
  "foo": "[Base-64-encoded binary data]", # Cannot be decoded to a string.
  "bar": "NTY3OAo=" # b64enc 5678
}
```

And I want to create a secret with the following (as output by `kubectl get secret -o yaml`, i.e. values are Base64-encoded):

```yaml
data:
  foo: [Base-64-encoded binary data]
  bar: NTY3OAo=
```

`dataFrom` doesn't work, because it assumes that the values from the provider JSON are the actual secret value, not the secret value that's been Base64-encoded.

I can iterate over the data keys with`template`, but the values resulting from a template are then Base64-encoded, so if I pass an already Base64-encode value, it's then Base64-encoded a second time into the K8s secret, resulting in a double-encoded value.

**Comment by gusfcarvalho** [comment]
Hey! I was able to reproduce this issue, and gladly #701 already fixes it:

setup ran here:
```
pingenc=$(base64 /bin/ping | tr -d '\n')  #Binary file as base64enc
vault kv put secret/bar my-enc-value=$pingenc
```
Created the external secret below:
```
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: template-v2
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: secret-v2
    # this is how the Kind=Secret will look like
    template:
      engineVersion: v2
      data:
        file: "{{ .file | b64dec }}"
  data:
  - secretKey: file
    remoteRef:
      key: secret/bar
      property: my-enc-value
 ```
 Got the `file` key from the secret `secret-v2`, saved into a new file and tried to run:
 ```
 t=$(kubectl get secret secret-v2 -o jsonpath='{.data.file}')
echo $t | base64 -d > anewping
chmod u+x anewping
./anewping 8.8.8.8

PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
./anewping: sendmsg: Operation not permitted
./anewping: sendmsg: Operation not permitted
^C
--- 8.8.8.8 ping statistics ---
2 packets transmitted, 0 received, 100% packet loss, time 1008ms
 ```
