### ISSUE TITLE
Don't Encode ExternalSecrets

### ISSUE THREAD

**Issue by MazenElzanaty** [external-secrets/external-secrets#728]
**Describe the solution you'd like**
I'm trying to use the value from Hashicorp vault as is, without external secrets encoding it to base64.

**What is the added value?**
In case you want to mount an encrypted file as is.

**Give us examples of the outcome**
Add Encoded data in Vault or anything External, then external secrets creates a secret with the same values.

**Comment by moolen** [comment]
Hey, @MazenElzanaty can you please provide us example manifests and an example secret from vault?

**Comment by MazenElzanaty** [comment]
For Example If I'm have a secret in Hashicorp vault as below name db:

Key             
cwallet.sso  

Value (base64 encoded file)
ofhONgAAAAYAAAAhBvpEOodw0Yf6csA85BeoIxXzGLKNZxmZxrWB+a5GnaRwMIIZ1AIBAzCCGZoGCSqGSIb3DQEHAaCCGYsEghmHMIIZgzCCGX8GCSqGSIb3DQEHBqCCGXAwghlsAgEAMIIZZQYJKoZIhvcNAQcBMBwGCiqGSIb3DQEMAQMwDgQI1Q6VyzWCaU8CAicQgIIZOOlaL6dmQPUlpwpNL18kzVI1A6WOhZ+UBkx0K/ju5oPhz7xelP9N/pw4SO6bqEcNBSR3KyVIN7ClEA1ltc8aFkJ3rkisdEFRcV/Wew0aABz8b8SYUvSBSRer+JIXnKQzUhQY8IaWzorAvbD9Imc/

Creating an external secret
```
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: db
spec:
  backendType: vault
  vaultMountPoint: cluster
  vaultRole: cluster-role
  dataFrom:
    - kv/data/cluster/db
```

This re-encodes the already encoded value and creates a secret, so it there a way not to encode it?

**Comment by gusfcarvalho** [comment]
Hi @MazenElzanaty ! I noticed your YAML is for KES (https://github.com/external-secrets/kubernetes-external-secrets). You should consider upgrading to ESO(https://external-secrets.io) as KES is deprecated(https://github.com/external-secrets/kubernetes-external-secrets/issues/864).

This issue would still happen in ESO (I think #712 is what you want, please check that and confirm to us). It is already being addressed.

**Comment by MazenElzanaty** [comment]
I tried the operator, but i'm having an issue with the secret path
It always appends `secret/` before the path

For example I have a secret at kv/cluster/db-secret

So the ExternalSecret looks like this
```
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: vault-example
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: example-sync
  data:
  - secretKey: foobar
    remoteRef:
      key: kv/cluster/db-secret
      property: my-value
```

When I describe the externalsecret I get that It can't find http://ip:8200/v1/secret/data/kv/cluster/db-secret
