### ISSUE TITLE
Oracle external secret : SecretSyncedError,  invalid header

### ISSUE THREAD

**Issue by julioo** [external-secrets/external-secrets#733]
**Describe the solution you'd like**
Describe the end goal of this proposal. What is this new functionality or the new behaviour (or what problem does it fix)? 

Hello team,
Using external-secret last version 0.4.2 and applied the change of specification for Oracle vault provider.

SecretStore is valid
$ kubectl get ss
NAME          AGE   STATUS
vault   8h    Valid

But externalsecret reports SecretSyncedError. I invalid header filed value.
Warning  UpdateFailed  3m42s (x990 over 8h)  external-secrets  (combined from similar events): could not get secret data from provider: key "ocid1.vaultsecret.oc1.eu-frankfurt-1.idxxx" from ExternalSecret "example": Post "https://secrets.vaults.eu-frankfurt-1.oci.oraclecloud.com/20190301/secretbundles/actions/getByName?secretName=ocid1.vaultsecret.oc1.eu-frankfurt-1.idxxx&vaultId=ocid1.vault.oc1.eu-frankfurt-1.cbravbrraaaua.idxx": net/http: **invalid header field value** "Signature version=\"1\",headers=\"date (request-target) host content-length content-type x-content-sha256\",keyId=\"ocid1.tenancy.oc1..iddd/ocid1.user.oc1..iddd/bc:13:5b:b9:bf:38:db:ec:84:b5:4a:65:c3:1d:3e:90\n\",algorithm=\"rsa-sha256\",signature=\"idddddA==\"" for key Authorization

Did several attempts, using instance principal or account service with the same result, unfortunately.
Can it be related to the new version?

**Comment by gusfcarvalho** [comment]
Hi @julioo ! Can you provide your SecretStore and ExternalSecrets manifest? We did have a breaking change in Oracle Vault provider. But it should not have altered the way the code work, only a reorganization of the spec.

**Comment by gusfcarvalho** [comment]
Can you also format your yaml? You can do it by pasting inside with the code block tool.

But I think I know what the issue is:  Right now you are using `dataFrom`, which expects the key to provide a json format. In your case, `username` is just a simple string, right? I think you can use `data` in your use case, like this:

```
target:
  name: the-name-of-the-kubernetes-secret # Name for the secret on the cluster
  creationPolicy: Owner
data:
- secretKey: the-key-in-kubernetes-secret
  remoteRef:
     key: username
```

**Comment by julioo** [comment]
@gusfcarvalho I modified my IAM policy and dynamic group. Instance principal is ok
Here is my configuration

```
apiVersion: v1
items:
- apiVersion: external-secrets.io/v1alpha1
  kind: SecretStore
  metadata:
    creationTimestamp: "2022-02-16T23:41:54Z"
    generation: 2
    name: julienvault
    namespace: default
    resourceVersion: "167576"
    uid: 91916471-2381-4816-95cc-1f6405c0a9de
  spec:
    provider:
      oracle:
        region: eu-frankfurt-1
        vault: ocid1.vault.oc1.eu-frankfurt-1.....
  status:
    conditions:
    - lastTransitionTime: "2022-02-16T23:44:39Z"
      message: store validated
      reason: Valid
      status: "True"
      type: Ready
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

```
apiVersion: v1
items:
- apiVersion: external-secrets.io/v1alpha1
  kind: ExternalSecret
  metadata:
    name: example
  spec:
    dataFrom:
    - key: julien
    refreshInterval: 0.03m
    secretStoreRef:
      kind: SecretStore
      name: julienvault
    target:
      creationPolicy: Owner
      name: example
```
