### ISSUE TITLE
Labels and annotations not propagated to target Secret if using template for non Opaque Secret types

### ISSUE THREAD

**Issue by slopezz** [external-secrets/external-secrets#755]
**Describe the solution you'd like**

Some tools like argoCD, tekton pipelines... sometimes need to use `Secrets` with specific labels or annotations.

When using standard `Opaque` `Secret` types, labels and annotations from the `ExternalSecret` are propagated to the target `Secret` created by ESO without any issue.

However, when using the **template** feature, because it is needed for example a `Secret` type  `kubernetes.io/ssh-auth`, then labels and annotations are **not** propagated to the target `Secret` created by ESO, example:

```yaml
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: github-ssh-key
  annotations:
    tekton.dev/git-0: github.com
spec:
  refreshInterval: 60s
  secretStoreRef:
    name: vault-mgmt
    kind: ClusterSecretStore
  target:
    name: github-ssh-key
    template:
      type: kubernetes.io/ssh-auth
      data:
        ssh-privatekey: "{{ .sshprivatekey | toString }}"
        known_hosts: "{{ .knownhosts | toString }}"
  data:
  - secretKey: sshprivatekey
    remoteRef:
      key: path-to/github-ssh-key
      property: private_key
  - secretKey: knownhosts
    remoteRef:
      key: path-to/github-ssh-key
      property: known_hosts
```

I guess it will happen the same with any `Secret` type using the **template** feature (like dockerconfigs, tls...).

**What is the added value?**

You use ESO to have `Secrets` managed by `ExternalSecret` custom resources without harcoding sensitive data, so you expect to not worry about labels and annotations being propagated only on certain scenarios.

**Give us examples of the outcome**

You don't need to manage manually labels or annotations on **non-Opaque** `Secrets` created by ESO.

**Observations (Constraints, Context, etc):**

N/A

**Comment by slopezz** [comment]
I have checked the ESO code
https://github.com/external-secrets/external-secrets/blob/ab4a1f3d056161b5bc2eb3e2893cb46702580cd6/pkg/controllers/externalsecret/externalsecret_controller_template.go#L80-L96

And I see that in case of a **template**, you need to add the annotations/labels in the `template.metadata`, and it works:

```yaml
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: github-ssh-key
spec:
  refreshInterval: 60s
  secretStoreRef:
    name: vault-mgmt
    kind: ClusterSecretStore
  target:
    name: github-ssh-key
    template:
      type: kubernetes.io/ssh-auth
      data:
        ssh-privatekey: "{{ .sshprivatekey | toString }}"
        known_hosts: "{{ .knownhosts | toString }}"
spec:
  data:
    - remoteRef:
        key: path-to/github-ssh-key
        property: private_key
      secretKey: sshprivatekey
    - remoteRef:
        key: path-to/github-ssh-key
        property: known_hosts
      secretKey: known_hosts
  refreshInterval: 60s
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-mgmt
  target:
    creationPolicy: Owner
    name: 3scale-saas-github-ssh-key-test
    template:
      data:
        known_hosts: '{{ .known_hosts | toString }}'
        ssh-privatekey: '{{ .sshprivatekey | toString }}'
      metadata:
        annotations:
          tekton.dev/git-0: github.com
        labels:
          whatever: value
      type: kubernetes.io/ssh-auth
```

So it works as expected.

However, before closing the issue, I would like to know if this desing is intended, or maybe the way to propagate annotations/labels should be the same on all cases?
