### ISSUE TITLE
GCP Workload Identity - Secret Manager in different project than GKE cluster

### ISSUE THREAD

**Issue by tenczardavid** [external-secrets/external-secrets#772]
**Describe the solution you'd like**
Currently, the Workload Identity implementation assumes that Google Secret Manager will be used in the same project where the GKE cluster is located. This limitation is not documented anywhere and I had to dig up the code to find it.

[link to code](https://github.com/external-secrets/external-secrets/blob/178e26f048e0d70928c7e425cba0df00e53ca672/pkg/provider/gcp/secretmanager/secretsmanager_workload_identity.go#L123)
```golang
	idProvider := fmt.Sprintf("https://container.googleapis.com/v1/projects/%s/locations/%s/clusters/%s",
		spec.Provider.GCPSM.ProjectID,
		wi.ClusterLocation,
		wi.ClusterName)
	idPool := fmt.Sprintf("%s.svc.id.goog", spec.Provider.GCPSM.ProjectID)
```

This is not true in most Enterprise setup, using GCP Organisations. In our use-case GKE clusters are managed separately in a different GCP project than the projects where Google Secret Manager is used. 

**What is the added value?**
The External Secrets service can be used in a more distributed GCP project setup which is widely used in Google Cloud Landing Zones.

**Give us examples of the outcome**

I propose the addition of `spec.provider.gcpsm.auth.workloadIdentity.clusterProjectID` field

```yaml
kind: ClusterSecretStore
metadata:
  name: example
spec:
  provider:
    gcpsm:
      projectID: my-project
      auth:
        workloadIdentity:
          # the projectID where the GKE cluster resides
          clusterProjectID: example-project-id
          # name of the cluster region
          clusterLocation: europe-central2
          # name of the GKE cluster
          clusterName: example-workload-identity
          # reference the sa from above
          serviceAccountRef:
            name: team-a
            namespace: team-a
```
