### ISSUE TITLE
Utilized to call an external API for OAuth token?

### ISSUE THREAD

**Issue by nmajin** [external-secrets/external-secrets#806]
**Describe the solution you'd like**
I simply would like to call an external API endpoint for an OAuth token and then have a secret created

**What is the added value?**
Not having to store the token in a vault, simply grab it from the source.

**Give us examples of the outcome**

Something similar to the webook provider, but just calling an API endpoint instead

**Observations (Constraints, Context, etc):**

Maybe we can use the webhook provider for this? Or would this need to be a new feature developed?

**Comment by gusfcarvalho** [comment]
Hi @nmajin ! If you have the necessary information to get the OAuth token, I believe webhook provider would already work =)

**Comment by nmajin** [comment]
After installing the Operator, I've configured a `SecretStore` and `ExternalSecret` and applied them both. I am not seeing any activity, including anything in the `external-secrets-operator-controller-manager` pod. I was expecting to at least see a call out to the remote endpoint at least using.

```
apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: example-webhook-secretstore
spec:
  provider:
    webhook:
      url: "https://api/oauth"
      method: POST
      timeout: 1m
      result:
        jsonPath: "$.token"
      headers:
        Content-Type: application/json
        Accept: application/json
      body: '{"username": "<user>", "password": "<pass>"}'
```
```
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: example-webhook-externalsecret
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: example-webhook-secretstore
    kind: SecretStore
  target:
    name: example-sync
  data:
  - secretKey: foobar
    remoteRef:
      key: secret
```
