### ISSUE TITLE
How to use webhook provider with variables?

### ISSUE THREAD

**Issue by nmajin** [external-secrets/external-secrets#809]
For the most part I got this working, but I would like to use a referenced secrets for the username and password to pass to the body of the webhook, but it seems like the variables are not interpolating:

```
apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: webhook-test
spec:
  provider:
    webhook:
      url: "<API endpoint>"
      method: POST
      timeout: 1m
      result:
        jsonPath: "$.token"
      headers:
        Content-Type: application/json
        Accept: application/json
      body: "{\"username\": {{ .auth.username }}, \"password\": {{ .auth.password }}}"
      secrets:
      - name: auth
        secretRef:
          name: my-secret
```
kubectl get secretstore webhook-test -o yaml
```
spec:
  provider:
    webhook:
      body: '{"username": {{ .auth.username }}, "password": {{ .auth.password }}}'
```
This is tripping me up due to the fact that the body needs to be a string and the string being passed is JSON, so I am not quite sure how to format the syntax.

Hardcoding the values works and as you can see after the `SecretStore` has been applied, it's not interpolating the values from the referenced secret.

Any help would be appreciated.

**Comment by moolen** [comment]
Hey, your template expressions `{{ .auth.username }}` are missing quotes. It should be:

```yaml
spec:
  provider:
    webhook:
      body: |
        {"username": "{{ .auth.username }}", "password": "{{ .auth.password }}"}

```

Here's a complete round-trip with httpbin using POST and json:
```yaml
apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: webhook-backend
spec:
  provider:
    webhook:
      url: "http://httpbin.org/post"
      result:
        jsonPath: "$.json.ref"
      method: POST
      headers:
        Content-Type: application/json
        Authorization: Basic {{ print .auth.username ":" .auth.password | b64enc }}
      body: |
        {"ref": "ref from httpbin response: {{ .remoteRef.key }}"}
      secrets:
      - name: auth
        secretRef:
          name: webhook-credentials
---
apiVersion: v1
kind: Secret
metadata:
  name: webhook-credentials
data:
  username: dGVzdA== # "test"
  password: dGVzdA== # "test"
---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: webhook-example
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: webhook-backend
    kind: SecretStore
  target:
    name: example-sync
  data:
  - secretKey: foobar
    remoteRef:
      key: secret
```

**Comment by nmajin** [comment]
I tried the quotes and many different variation, I feel like it is honestly not interpolating, assuming what I am spitting out from the applied object showing that it is literally a quoted string around `"{{ .auth.username }}"` for example. And if I hardcode those values then the connection works and I am able to get the secret created.
```
{"level":"error","ts":1646837392.986987,"logger":"controllers.ExternalSecret","msg":"could not update Secret","ExternalSecret":"cert-manager/test-webhook-externalsecret","SecretStore":"cert-manager/test-webhook-secretstore","error":"could not get secret data from provider: key \"secret\" from ExternalSecret \"test-webhook-externalsecret\": endpoint gave error 400 Bad Request","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:114\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:311\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:227"}
```
```
kubectl get secretstore
NAME                       AGE   STATUS
test-webhook-secretstore   77s   Valid
```
```
kubectl get secretstore test-webhook-secretstore -o yaml
apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"external-secrets.io/v1alpha1","kind":"SecretStore","metadata":{"annotations":{},"name":"test-webhook-secretstore","namespace":"cert-manager"},"spec":{"provider":{"webhook":{"body":"{\"username\": \"{{ .auth.username }}\", \"password\": \"{{ .auth.password }}\"}\n","headers":{"Accept":"application/json","Content-Type":"application/json"},"method":"POST","result":{"jsonPath":"$.access_token"},"secrets":[{"name":"auth","secretRef":{"name":"test-service-account"}}],"timeout":"1m","url":"<API endpoint>"}}}}
  creationTimestamp: "2022-03-09T14:49:16Z"
  generation: 1
  name: test-webhook-secretstore
  namespace: cert-manager
  resourceVersion: "429610025"
  uid: b8a0a1e5-bace-4409-ba63-bfea31d58f08
spec:
  provider:
    webhook:
      body: |
        {"username": "{{ .auth.username }}", "password": "{{ .auth.password }}"}
      headers:
        Accept: application/json
        Content-Type: application/json
      method: POST
      result:
        jsonPath: $.access_token
      secrets:
      - name: auth
        secretRef:
          name: test-service-account
      timeout: 1m
      url: <API endpoint>
status:
  conditions:
  - lastTransitionTime: "2022-03-09T14:49:16Z"
    message: store validated
    reason: Valid
    status: "True"
    type: Ready
```
```
kubectl get secret test-service-account -o yaml
apiVersion: v1
data:
  password: ...
  username: ...
kind: Secret
...
```

**Comment by nmajin** [comment]
Any other ideas? What you posted there was the example in the documentation, but has that actually been tested, especially with the latest version of external-secrets (v0.4.4)? Is there a better way I can debug this to determine the values are actually coming through from the secret? The fact that I see `"{{ .auth.username }}"` for example after I apply the `SecretStore` and output the yaml makes me thing that the variables are not getting interpolated, but I could be wrong here.

Either way, still not working and would like to avoid dropping the creds in raw into the `body` string.

**Comment by gusfcarvalho** [comment]
I believe the `SecretStore` itself would never render the content. If it would, it would be quite of the same issue as having to hard code the credentials (since then any user could simply `kubectl describe ss`). I'll try to investigate this issue a little bit better, but since this is a community maintained provider, you might as well reach the original contributor as well.

**Comment by gusfcarvalho** [comment]
Hi @nmajin. I created a mock api to test your issue. Indeed, it was just add the extra " and the response works.
Example of a good SecretStore:
```
apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: webhook-test
spec:
  provider:
    webhook:
      url: "https://6229c973be12fc4538a7d6ae.mockapi.io/api/v1/token"
      method: POST
      timeout: 1m
      result:
        jsonPath: "$.access_token"
      headers: 
        Content-Type: application/json
        Accept: application/json
      body: "{\"username\": \"{{ .auth.username }}\", \"password\": \"{{ .auth.password }}\"}"
      secrets:
      - name: auth
        secretRef:
          name: auth
EOF
```
please note that `\"{{.auth.username}}\"` now has a double-quotes around it. The same applies for `\"{{.auth.password}}\"`. Template is being rendered correctly, and it is the expected output not to see any Secret information in the SecretStore.

**Comment by gusfcarvalho** [comment]
Also, thank you for your interest in using the project!

**Comment by willemm** [comment]
Oh I was going to add that it might have been something like a quote character or backslash inside the password, which means you'd have to do something like (untested)

```
apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: webhook-test
spec:
  provider:
    webhook:
      url: "https://6229c973be12fc4538a7d6ae.mockapi.io/api/v1/token"
      method: POST
      timeout: 1m
      result:
        jsonPath: "$.access_token"
      headers: 
        Content-Type: application/json
        Accept: application/json
      body: "{\"username\": {{ .auth.username | toJson }}, \"password\": {{ .auth.password | toJson }} }"
      secrets:
      - name: auth
        secretRef:
          name: auth
```

Or maybe even: `body: "{ {{ .auth | toJson }} }"
