### ISSUE TITLE
failed to parse response json: yaml: found unknown escape character

### ISSUE THREAD

**Issue by nmajin** [external-secrets/external-secrets#810]
I am again using the webhook provider and I am seeing this error when creating the secret for the first time and when renewing:
```
{"level":"error","ts":1646794528.9436297,"logger":"controllers.ExternalSecret","msg":"could not update Secret","ExternalSecret":"openshift-operators/webhook-externalsecret","SecretStore":"openshift-operators/webhook-secretstore","error":"could not get secret data from provider: key \"secret\" from ExternalSecret \"webhook-externalsecret\": failed to parse response json: yaml: found unknown escape character","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:114\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:311\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:227"}
{"level":"info","ts":1646794832.2976162,"logger":"controllers.ExternalSecret","msg":"reconciled secret","ExternalSecret":"openshift-operators/webhook-externalsecret","SecretStore":"openshift-operators/webhook-secretstore"}
```
However, the secret does actually get updated, so is this actually a bug?

The contents of the API return the following for example:
```
{
  "token": "abc123",
  "refresh_token: "xyz123",
  ...
}
```
And my `SecretStore` is parsing the value like so:
```
apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: webhook-secretstore 
spec:
  provider:
    webhook:
      url: "<API endpoint>"
      method: POST
      timeout: 1m
      result:
        jsonPath: "$.token"
...
```
And here is my ExternalSecret:
```
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: webhook-externalsecret
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: webhook-secretstore
    kind: SecretStore
  target:
    name: my-secret
  data:
  - secretKey: token
    remoteRef:
      key: secret
```
