### ISSUE TITLE
High pod memory consumption

### ISSUE THREAD

**Issue by roymartinezblanco** [external-secrets/external-secrets#834]
# Problem 

We recently started using ESO with GKE in my organization. I’ve been monitoring the memory consumption that the pods have and, I’ve noticed that it continuously increases its consumption without a reason.  Due to this I’ve started to limit how much memory it can consume but this causes the pod to restart when it reaches the memory limit and restarts the whole process again.
![image](https://user-images.githubusercontent.com/41208646/158557320-55e48a3f-3b00-4ff1-b31e-b93ff4df43cf.png)

I wanted to see if someone could help me understand this behavior since at least from a logs perspective nothing seems to be happening.

```logs
{"level":"info","ts":1647279723.910821,"logger":"controller.secretstore","msg":"Starting EventSource","reconciler group":"external-secrets.io","reconciler kind":"SecretStore","source":"kind source: *v1alpha1.SecretStore"}
{"level":"info","ts":1647279723.910864,"logger":"controller.secretstore","msg":"Starting Controller","reconciler group":"external-secrets.io","reconciler kind":"SecretStore"}
{"level":"info","ts":1647279723.9109325,"logger":"controller.externalsecret","msg":"Starting EventSource","reconciler group":"external-secrets.io","reconciler kind":"ExternalSecret","source":"kind source: *v1alpha1.ExternalSecret"}
{"level":"info","ts":1647279723.9109786,"logger":"controller.externalsecret","msg":"Starting EventSource","reconciler group":"external-secrets.io","reconciler kind":"ExternalSecret","source":"kind source: *v1.Secret"}
{"level":"info","ts":1647279723.9109404,"logger":"controller.clustersecretstore","msg":"Starting EventSource","reconciler group":"external-secrets.io","reconciler kind":"ClusterSecretStore","source":"kind source: *v1alpha1.ClusterSecretStore"}
{"level":"info","ts":1647279723.9110146,"logger":"controller.clustersecretstore","msg":"Starting Controller","reconciler group":"external-secrets.io","reconciler kind":"ClusterSecretStore"}
{"level":"info","ts":1647279723.910985,"logger":"controller.externalsecret","msg":"Starting Controller","reconciler group":"external-secrets.io","reconciler kind":"ExternalSecret"}
{"level":"info","ts":1647279724.0114942,"logger":"controller.secretstore","msg":"Starting workers","reconciler group":"external-secrets.io","reconciler kind":"SecretStore","worker count":1}
{"level":"info","ts":1647279724.0116224,"logger":"controller.clustersecretstore","msg":"Starting workers","reconciler group":"external-secrets.io","reconciler kind":"ClusterSecretStore","worker count":1}
{"level":"info","ts":1647279724.0117655,"logger":"controller.externalsecret","msg":"Starting workers","reconciler group":"external-secrets.io","reconciler kind":"ExternalSecret","worker count":1}
```

Initially, we thought that the `refreshInterval` could be a cause for all of those but we have changed our settings to use a specific version and with a `refreshInterval: "0"` to avoid refresh but no luck.

## Environment
- GKE: `1.21.9-gke.1001`
- ESO:  `0.3.11`, `0.4.2`, `0.4.4`  <- We have used these versions to see if it is fixed but the behavior is present on all.
- Workload Identity
- GCP Secret Manager 

## Deployment

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-secrets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: externalsecrets
  template:
    spec:
    metadata:
      labels:
        app: externalsecrets
      serviceAccountName: external-secrets
      containers:
        - name: external-secrets
          image: ghcr.io/external-secrets/external-secrets:v0.4.2
          imagePullPolicy: IfNotPresent
          args:
          - --concurrent=1
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
```
