### ISSUE TITLE
Fail to template the secret

### ISSUE THREAD

**Issue by MalulDekel** [external-secrets/external-secrets#836]
Hey, I went throw the docs and went throw the issues. 
I can't figure out why I am failing to deploy my external secret. 

```
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: cloud-api-secrets
  namespace: api
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secret-store
  target:
    name: cloud-api-secrets
    creationPolicy: Owner
    template:
      data:
        MONGOCON: "{{ .MONGOCON | toString }}"-cloud-api
  data:
  - remoteRef:
      key: mongo-secret
    secretKey: MONGOCON  
 ```
 
 When running:
```
kubectl apply -f test.yaml
```

I am getting the following error
```
error: error parsing test.yaml: error converting YAML to JSON: yaml: line 15: did not find expected key
```

Take into account that the secret exist and the secret store works

**Comment by moolen** [comment]
The issue is this line, the last quotation mark ends the string and breaks the yaml document:

```
        MONGOCON: "{{ .MONGOCON | toString }}"-cloud-api
```

It should be like this:
```
        MONGOCON: "{{ .MONGOCON | toString }}-cloud-api"
```

here's a full example:

```yaml
apiVersion: external-secrets.io/v1alpha1
kind: ClusterSecretStore
metadata:
  name: fake
spec:
  provider:
    fake:
      data:
      - key: "mongo-secret"
        value: "foobar"
        version: ""
---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: cloud-api-secrets
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: fake
  target:
    name: cloud-api-secrets
    creationPolicy: Owner
    template:
      data:
        MONGOCON: "{{ .MONGOCON | toString }}-cloud-api"
  data:
  - remoteRef:
      key: mongo-secret
    secretKey: MONGOCON

```
