### ISSUE TITLE
ExternalSecret templating not merging data field

### ISSUE THREAD

**Issue by vitorfhc** [external-secrets/external-secrets#871]
Hello, I am not sure if I am doing something wrong here, but looks like the `.spec.target.data` field is overriding the fields defined by `.spec.data`.

I created this:

```yaml
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: argocd-ghcr-creds
spec:
  secretStoreRef:
    name: argocd-store
    kind: SecretStore
  refreshInterval: 1h
  target:
    name: ghcr-creds
    template:
      data:
        type: aGVsbQ== # helm
        url: b2NpOi8vZ2hjci5pbw== # oci://ghcr.io
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repo-creds
  data:
  - secretKey: password
    remoteRef:
      key: services/argocd/ghcr-token
  - secretKey: username
    remoteRef:
      key: services/argocd/ghcr-user
```

And this is the resulting Secret kind:

```yaml
apiVersion: v1
data:
  type: YUdWc2JRPT0=
  url: YjJOcE9pOHZaMmhqY2k1cGJ3PT0=
immutable: false
kind: Secret
metadata:
  annotations:
    reconcile.external-secrets.io/data-hash: 738f482ee3464cc84ed210fca86c4d7e
  labels:
    argocd.argoproj.io/secret-type: repo-creds
  name: ghcr-creds
  namespace: argocd
  ownerReferences:
  - apiVersion: external-secrets.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: ExternalSecret
    name: ghcr-creds
    uid: 6f2d13c6-6e19-4e33-8aa6-c85c83b971a0
  resourceVersion: "2707257"
  uid: b51090cc-073e-479b-ba26-af2d1c96e9a7
type: Opaque
```

This is pretty weird, I thought the default behavior would be to have data as

```yaml
data:
  type: YUdWc2JRPT0=
  url: YjJOcE9pOHZaMmhqY2k1cGJ3PT0=
  password: ...
  username: ...
```

Isn't there a way to do merge instead of overwrite?

**Comment by moolen** [comment]
Hey, this is intentional behavior. The `template.data` map should take precedence, see: https://github.com/external-secrets/external-secrets/issues/755#issuecomment-1050228391

There's no merge option. However, you can basically copy over the `username` / `password` fields if needed:

```yaml
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: argocd-ghcr-creds
spec:
  # ...
  target:
    name: ghcr-creds
    template:
      engineVersion: v2
      data:
        type: aGVsbQ== # helm
        url: b2NpOi8vZ2hjci5pbw== # oci://ghcr.io
        username: "{{ .username }}"
        password: "{{ .password }}"

```
