### ISSUE TITLE
ClusterExternalSecret Inactive/Not Working

### ISSUE THREAD

**Issue by cazter** [external-secrets/external-secrets#882]
After creating the ClusterExternalSecret, nothing happens. No change in status to the ClusterExternalSecret. No creation of an ExternalSecret. No creation of a K8S secret. No noticeable response from the controller pod logs.

```yaml
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: runtime-config
spec:
  externalSecretName: "runtime-config-es"
  refreshTime: 5s
  namespaceSelector:
    matchLabels:
      externalsecrets: enabled
  externalSecretSpec:
    secretStoreRef:
      name: cluster-secretstore-aws
      kind: ClusterSecretStore
    refreshInterval: 5s
    target:
      name: runtime-config
      creationPolicy: Owner
    data:
      - secretKey: COMMON_FREETRIAL_API_KEY
        remoteRef:
          key: common/COMMON_FREETRIAL_API_KEY
```

```shell
$ ku get ClusterExternalSecret
NAME                  AGE
runtime-config   22m
```

```shell
$ ku describe ClusterExternalSecret runtime-config
Name:         runtime-config
Namespace:
Labels:       <none>
Annotations:  <none>
API Version:  external-secrets.io/v1beta1
Kind:         ClusterExternalSecret
Metadata:
  Generation:          1
  Managed Fields:
    API Version:  external-secrets.io/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:externalSecretName:
        f:externalSecretSpec:
          .:
          f:data:
          f:refreshInterval:
          f:secretStoreRef:
            .:
            f:kind:
            f:name:
          f:target:
            .:
            f:creationPolicy:
            f:deletionPolicy:
            f:name:
        f:namespaceSelector:
          .:
          f:matchLabels:
            .:
            f:es:
        f:refreshTime:
    Manager:         kubectl-client-side-apply
    Operation:       Update
    Time:            2022-03-23T23:04:09Z
  Resource Version:  355091728
  UID:               159c762e-4201-421d-a626-3b8bc7154ad2
Spec:
  External Secret Name:  runtime-config-es
  External Secret Spec:
    Data:
      Remote Ref:
        Conversion Strategy:  Default
        Key:                  common/COMMON_FREETRIAL_API_KEY
      Secret Key:             COMMON_FREETRIAL_API_KEY
    Refresh Interval:         5s
    Secret Store Ref:
      Kind:  ClusterSecretStore
      Name:  cluster-secretstore-aws
    Target:
      Creation Policy:  Owner
      Deletion Policy:  None
      Name:             runtime-config
  Namespace Selector:
    Match Labels:
      externalsecrets:        enabled
  Refresh Time:  5s
Events:          <none>
```
