### ISSUE TITLE
`SecretStore`: `serviceAccountRef` in `vault` provider `auth` section does not see `ServiceAccount` from another namespace

### ISSUE THREAD

**Issue by eugene-marchanka** [external-secrets/external-secrets#897]
**Describe the solution you'd like**
Describe the end goal of this proposal. What is this new functionality or the new behaviour (or what problem does it fix)?

`SecretStore`: `serviceAccountRef` in `vault` provider `auth` section does not see `ServiceAccount` from another namespace

**What is the added value?**
Intended behavior is not working

**Give us examples of the outcome**

`serviceaccounts` in `external-secrets` namespace:
```
$ k get serviceaccounts -n external-secrets
NAME                                  SECRETS   AGE
default                               1         15h
k8s-sa                                1         15h
release-kubernetes-external-secrets   1         15h
```

`serviceaccounts` in `elastic` namespace:
```
$ k get serviceaccounts -n elastic
NAME      SECRETS   AGE
default   1         12m
```

`SecretStore` deployed in `external-secrets` namespace:
```
---
apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: external-secrets-store
  namespace: external-secrets
spec:
  provider:
    vault:
      server: "https://vault.aws.test.io"
      path: "secrets"
      version: "v2"
      caBundle: xxxxxRUdJTiBxxxx
      auth:
        kubernetes:
          mountPath: "mic102-auth"
          role: "vault-secrets"
          serviceAccountRef:
            name: release-kubernetes-external-secrets
            namespace: external-secrets
```

Status:
```
$ k get secretstores.external-secrets.io -n external-secrets
NAME                     AGE   STATUS
external-secrets-store   81s   Valid
```

The same `SecretStore` but deployed to `elastic` namespace got issues:
```
Name:         external-secrets-store
Namespace:    elastic
Labels:       <none>
Annotations:  <none>
API Version:  external-secrets.io/v1alpha1
Kind:         SecretStore
Metadata:
  Creation Timestamp:  2022-03-25T15:04:17Z
  Generation:          1
  Managed Fields:
    API Version:  external-secrets.io/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:provider:
          .:
          f:vault:
            .:
            f:auth:
              .:
              f:kubernetes:
                .:
                f:mountPath:
                f:role:
                f:serviceAccountRef:
                  .:
                  f:name:
                  f:namespace:
            f:caBundle:
            f:path:
            f:server:
            f:version:
    Manager:      kubectl-client-side-apply
    Operation:    Update
    Time:         2022-03-25T15:04:17Z
    API Version:  external-secrets.io/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        .:
        f:conditions:
    Manager:         external-secrets
    Operation:       Update
    Subresource:     status
    Time:            2022-03-25T15:04:18Z
  Resource Version:  7893853
  UID:               fced15ab-05c3-4c91-ad5d-3d6977e0db05
Spec:
  Provider:
    Vault:
      Auth:
        Kubernetes:
          Mount Path: mic102-auth
          Role:        vault-secrets
          Service Account Ref:
            Name:       release-kubernetes-external-secrets
            Namespace:  external-secrets
      Ca Bundle:        xxxx1CRUdxxx
      Path:             secrets
      Server:           https://vault.aws.test.io
      Version:          v2
Status:
  Conditions:
    Last Transition Time:  2022-03-25T15:04:18Z
    Message:               unable to create client
    Reason:                InvalidProviderConfig
    Status:                False
    Type:                  Ready
Events:
  Type     Reason                 Age                From          Message
  ----     ------                 ----               ----          -------
  Warning  InvalidProviderConfig  1s (x13 over 21s)  secret-store  cannot get Kubernetes service account "release-kubernetes-external-secrets": ServiceAccount "release-kubernetes-external-secrets" not found

```

**Observations (Constraints, Context, etc):**

I'm running
k8s version: `v1.22.3`
containerd: `containerd://1.4.11`
provisioned by Kubespray.

Give here all extra information that could be interesting. Such as Golang version and Kubernetes version if you are reporting a bug/problem. You can also foresee technical constrains like "this could only be implementing using this specific technology or approach, because of this and that".
