### ISSUE TITLE
Allow to get parameters by path for AWS Systems Manager Parameter Store provider

### ISSUE THREAD

**Issue by jacekpuczko** [external-secrets/external-secrets#915]
I'm looking into migrating from deprecated Kubernetes External Secrets but I found out that the functionality of fetching all parameters by the path from AWS Systems Manager Parameter Store, available in Kubernetes External Secrets, is missing in the External Secrets Operator. It was already reported in:

https://github.com/external-secrets/external-secrets/issues/431

Currently, I'm using the path prefix in the parameter store to identify all secrets keys owned by a single service and use `kubernetes-client.io/ExternalSecret` resource to create a k8s secret with multiple keys without a need to specify every key or need to update any k8s resources when I add a new parameter. Because there is a lot of keys per secret and many services it's a huge overhead having to declare every key in the external secret resource.

Instead of having to specify every parameter:
```
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: service-name
spec:
  # [omitted for brevity]
  data:
    - secretKey: PASSWORD1
      remoteRef:
        key: /service-name/PASSWORD1
    - secretKey: PASSWORD2
      remoteRef:
        key: /service-name/PASSWORD2
    # Followed by more
  target:
    name: service-name
```

I'd like to use the path prefix to fetch all keys for the service (not sure if `dataFrom` was intended for this purpose)
```
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: service-name
spec:
  # [omitted for brevity]
  dataFrom:
    - key: /service-name/
  target:
    name: service-name
```

Example of the current usage with Kubernetes external secrets:
```
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: service-name
  namespace: namespace
spec:
  backendType: systemManager
  data:
    - path: /service-name/
      recursive: false
```

The proposed alternative solution using a JSON string to store multiple keys wouldn't work for me for 2 reasons:

1. AWS Systems Manager Parameter Store has a value limit of 4 KB in the free tier, 8 KB for the advanced option, this will be not enough to store all the keys for some of the services.
2. A JSON, especially a big one, won't be readable in the AWS Web console.

Is there a plan to implement this functionality?
If not, Could you please provide some direction on how to contribute to adding this feature?
Is it possible to implement one using the current `externalsecret.external-secrets.io` resource, `dataFrom` element or it would require changes to CRDs? Would the changes be limited to the Parameter store provider adapter (`parameterstore.go` file)?

**Comment by gusfcarvalho** [comment]
Hi @jacekpuczko! We already addressed this functionality on #820. It should be available on our next release, 0.5.0, although it will work in a different manner then path referencing. I believe, for instance, we cannot currently specify recursiveness (by default all calls are recursive).
To use the preview feature, you would need to define the `ExternalSecrets` using `dataFrom.find`:

```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: service-name
spec:
  # [omitted for brevity]
  dataFrom:
    - find:
        name:
          regexp: /service-name/.*$ # you can try a regexp that blocks recursiveness if you need to.
  target:
    name: service-name
```

You can try this preview feature by [installing external-secrets using the latest image](https://external-secrets.io/v0.4.4/guides-using-latest-image/). Just remember you need to use the helm charts available at `deploy/charts/external-secrets`, and not the released ones.

After trying it out, then we can see if this feature needs any adjustment for your specific use case =)

**Comment by jacekpuczko** [comment]
Hi @gusfcarvalho, it works for me :) Is there a way to translate parameters that the secret keys have no path prefixes? 
Now I get:
```
data:
  _service-name_PASSWORD1: cGFzc3dvcmQ=
  _service-name_PASSWORD2: cGFzc3dvcmQ=
```
and would be great to have:
```
data:
  PASSWORD1: cGFzc3dvcmQ=
  PASSWORD2: cGFzc3dvcmQ=
```
That way migration from Kubernetes External Secrets would be easier because I wouldn't have to update the environment variables injected in deployments.
I've tried to change the regex to `/service-name/(.*)$`, but the result is the same. 
Thanks!

**Comment by moolen** [comment]
hey @jacekpuczko, thank you for bringing this up!
Your problem with rewriting the keys is yet an open issue. While looking at your regexp i noticed the capture group and i think that would actually be a pretty neat way of adding that. Tho i think we still need to support multiple ways of rewriting keys. We should create a design document for that as this is a very common use-case.

**Comment by gusfcarvalho** [comment]
@moolen specifically for this use case, in vault provider I used the Path to allow filtering out “the root path” from the secrets. (i.e. searching regexp dev/.*would lead to different results to secret key names than searching path dev/ regexp .*) Maybe this can be done in AWS provider as well (and generally speaking, making Path useful for any provider)

**Comment by moolen** [comment]
That's covered, i added that feature that when you added the field in the vault provider :sun_with_face: 

https://github.com/external-secrets/external-secrets/blob/56c69a106386d61730cf222c85945dd407026484/pkg/provider/aws/parameterstore/parameterstore.go#L76-L82

**Comment by gusfcarvalho** [comment]
In this case @jacekpuczko if you try passing your main path in `find.Path` and use a general regexp, it might already filter out for you!

**Comment by jacekpuczko** [comment]
Hi @gusfcarvalho, I've just tried:
```
  dataFrom:
    - find:
        name:
          regexp: /service-name/.*$
        path: /service-name/
```
and it gives the same result with prefixes:
```
data:
  _service-name_PASSWORD1: cGFzc3dvcmQ=
  _service-name_PASSWORD2: cGFzc3dvcmQ=
```
Using the `find.path` without `name.regex` fails with an error.
