### ISSUE TITLE
"Merge" creationPolicy behavior with multiple external secrets targeting the same secret

### ISSUE THREAD

**Issue by nicolas-vivot** [external-secrets/external-secrets#918]
I'm trying to figure about the behavior of the merge creation policy in different use cases.

The documentation does not say anything special about it, so my assumption is that is simply merge the remote secret key/values into the target secret when specified keys already exist in the secret.

If this is the behavior with one external secret in Merge mode, the behavior with two external secret in merge mode targeting the same secret object is not the one i was expecting.

**Test scenario**

Having the following secret definition

```

apiVersion: v1
kind: Secret
metadata:
  name: nico-uber-secret
data:
  original-prop: Y291Y291
  testkey: Y291Y291
  testkey2: Y291Y291

```
And the following two external secrets

```
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: external-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: nico-uber-secret
    creationPolicy: Merge
  data:
    - secretKey: testkey
      remoteRef:
        key: demo/testsecret
        property: testkey
```
```

apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: external-secret2
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: nico-uber-secret
    creationPolicy: Merge
  data:
    - secretKey: testkey2
      remoteRef:
        key: demo/testsecret2
        property: testkey2
```

And two secrets in an AWS secret manager called _demo/testsecret_ and _demo/testsecret2_ with their respectives keys _testkey_ and _testkey2_

Do the following:

1. Apply the secret
2. Apply the first external secret "external-secret"
3. Apply the second external secret "external-secret2"

**Result**

After applying the first external secret, the value of the secret is the product of the merge of the already existing key/values and the remote secret value as show in the screen below
![image](https://user-images.githubusercontent.com/79290619/161019371-49d14458-170a-4a9e-8761-063d909f2ce5.png)

But after applying the second external secret, the key _testkey_ is gone
![image](https://user-images.githubusercontent.com/79290619/161019689-07012e1e-588e-4228-a53c-0688c98fb513.png)

**Expected behavior**

I would expect to have all three key/value pairs in the secret, the first one with the original value since no remote secret override it, and the two other remaining one having their values overridden with the value of the remote secrets.

**Question**

Is that the expected behavior ? 

- no: well then i guess it should be fixed.
- yes: can you please point me to the documentation explaining the exact behavior of the merge, or that currently having two external secret targeting the same secret is not supported.
