### ISSUE TITLE
Access nested JSON keys in secrets

### ISSUE THREAD

**Issue by norman-zon** [external-secrets/external-secrets#919]
**Describe the solution you'd like**
I want to be able to access nested keys in JSON-formatted secrets from Hashicorp Vault.

**What is the added value?**
The template syntax will be conciser.

**Give us examples of the outcome**

my vault secret (path: secrets/test):
```json
{
  "keys": {
    "key1": "secretkey1",
    "key2": "secretkey2"
  },
  "users": {
    "admin": {
      "password": "secretpassword"
    }
  }
}
```

my ExternalSecret
```yaml
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: example-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: mysecretstore
    kind: SecretStore
  target:
    creationPolicy: Owner
    template:
      data:
        config.ini: |
          auth_key = {{ .data.keys.key1  | toString }}
          admin_pw = {{ .data.users.admin.password | toString }}
         

  data:
  - secretKey: data
    remoteRef:
      key: secrets/test
```

**Observations (Constraints, Context, etc):**

When trying to use the example above the `ExternalSecret` fails to update:

```
Warning  UpdateFailed  69s (x10 over 5m12s)  external-secrets  could not apply template: could not execute template: unable to execute template at key config.ini: unable to execute template at key config.ini: template: config.ini: │
│ 1:15: executing "config.ini" at <.data.keys.key1>: can't evaluate field keys in type []uint8
```

**Comment by norman-zon** [comment]
I also tried with `dataFrom:` same result:

apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: example-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: mysecretstore
    kind: SecretStore
  target:
    creationPolicy: Owner
    template:
      data:
        config.ini: |
          auth_key = {{ .keys.key1  | toString }}
          admin_pw = {{ .users.admin.password | toString }}
         
  dataFrom:
  - key: zon/v1/pypicloud/pypicloud-server

**Comment by gusfcarvalho** [comment]
Hi @norman-zon ! If you want to use the information from the key value itself, you would need to first parse it `fromJson`, as vault provider loads the values as string if no other parameter applies.

What you can do to solve this issue without meddling with templating too much (as it can be quite hard to troubleshoot and understand what's going on) is the following (assuming you are using eso `v0.4.4`):

```
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: example-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: mysecretstore
    kind: SecretStore
  target:
    creationPolicy: Owner
    engineVersion: v2 # you could not configure this, but v1 is going to be deprecated.
    template:
      data:
        config.ini: |
          auth_key = {{ .authkey }}
          admin_pw = {{ .adminpw }}
  data:
  - secretKey: authkey
    remoteRef:
      key: secrets/test
      property: keys.key1
  - secretKey: adminpw
    remoteRef:
      key: secrets/test
      property: users.admin.password
```

PS: the following example was written on the top of my head, so there might be still few adjustments needed. I'll get back to it if you're still in trouble with it =).

**Comment by norman-zon** [comment]
Hi @gusfcarvalho, thanks for the suggestion. Sorry, if this was not clear enough in my first post, but I know that I can use it the way you described. 
But I find this adds quite a lot of code and using JSON dot-notation directly in the template would be much conciser. In my opinion, having `.data.x.y.z` 10 times, in the template is much more readable and easier to understand than having 10 `secretKey` blocks.

**Comment by norman-zon** [comment]
Could you give an example for your first suggestion using `fromJSON`?
I thought it would work like this:
```
   auth_key = {{ .keys.key1 | fromJSON  | toString }}
```
But this seems to be the wrong idea.

**Comment by norman-zon** [comment]
This works, thanks for the example.

As you say, it is a matter of taste. Therefore I would like to request this as a switchable **feature**.

For example as property of `dataFrom`:

```yaml
template:
   data:
     config.ini: |
          auth_key = {{ .keys.key1  | toString }}
          admin_pw = {{ .users.admin.password | toString }}
         
  dataFrom:
  - key: secrets/test
    asJson: true
```

Thanks again for the help so far.
