### ISSUE TITLE
Helm CRDs Install causing issue

### ISSUE THREAD

**Issue by corinz** [external-secrets/external-secrets#923]
I am encountering a strange bug in the latest helm chart. Here is my Chart.yaml dependencies section
```
dependencies:
- name: external-secrets
  version: 0.4.4
  repository: https://charts.external-secrets.io
```
When executing a bare-bones helm chart with a dependency on the eso chart I get this error:
``` 
Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "ClusterSecretStore" in version "external-secrets.io/v1alpha1"
```

However, when `installCRDs: false` and I download the CRDs into `crds` directory and perform a helm install, I have no issues. Can someone help determine what may be causing this issue? Is anyone else experiencing?

Thanks!
