### ISSUE TITLE
Strict templating of values

### ISSUE THREAD

**Issue by adinhodovic** [external-secrets/external-secrets#925]
**Describe the solution you'd like**
Is there any way to enforce strict templating of values? For example currently I'd like to template an Alertmanager configuration. However this is a template that has other templated values that should not be templated by External Secrets - these are templated by Alertmanager itself.

Secret: 
```
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  labels:
    argocd.argoproj.io/instance: monitoring
    tanka.dev/environment: ac01f6e2b7516fbe884c27716a1be2e96137a278ac0bbbdc
  name: alertmanager-config
  namespace: monitoring
spec:
  data:
  - remoteRef:
      key: kv/data/monitoring/alertmanager
      property: slackApiUrl
    secretKey: slackApiUrl
  dataFrom: []
  refreshInterval: 60s
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: alertmanager-config
    template:
      templateFrom:
      - configMap:
          items:
          - key: template.yaml
          name: alertmanager-config-template
 ```

The template referenced:

```
apiVersion: v1                                                                                                                                                                           [0/71]
data:
  template.yaml: |
    global:
      resolve_timeout: 5m
      slack_api_url: >-
        {{ .slackApiUrl | toString }}
...
    receivers:
      - name: "null"
      - name: slack
        slack_configs:
          - color: '{{ template "slack.color" . }}'
            title: '{{ template "slack.title" . }}'
            text: '{{ template "slack.text" . }}'
...
 ```

**Give us examples of the outcome**

```
could not apply template: could not execute template: unable to execute template at key template.yaml: unable to execute template at key template.yaml: template: template.yaml:26:28: executing "template.yaml" at <{{template "slack.color" .}}>: template "slack.color" not defined
```

I'd expect it to only template the slackApiUrl that's set in the external secret and not all fields.
