### ISSUE TITLE
BUG: `panic: assignment to entry in nil map`

### ISSUE THREAD

**Issue by nazarewk** [external-secrets/external-secrets#936]
I'm just starting to debug the issue, but i observed External Secrets `v0.4.4` crashing with with following stacktrace:
```
/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:223 +0x357
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:227 +0x85
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:266 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc00034fb80, {0x319add8, 0xc0009ab2c0})
/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:311 +0x33e
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc00034fb80, {0x319add8, 0xc0009ab2c0}, {0x282c9c0, 0xc00013c9c0})
/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:114 +0x26f
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0xc00034fb80, {0x319ae80, 0xc0049f16b0}, {{{0xc00064e280, 0x2ae2c40}, {0xc00064e270, 0x413c54}}})
/home/runner/work/external-secrets/external-secrets/pkg/controllers/externalsecret/externalsecret_controller.go:237 +0xeca
github.com/external-secrets/external-secrets/pkg/controllers/externalsecret.(*Reconciler).Reconcile(0xc0009b0180, {0x319ae80, 0xc0049f1740}, {{{0xc00064e280, 0xb}, {0xc00064e270, 0x6}}})
/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/controller/controllerutil/controllerutil.go:211 +0x250
sigs.k8s.io/controller-runtime/pkg/controller/controllerutil.CreateOrUpdate({0x319ae80, 0xc0049f1740}, {0x31de960, 0xc000ccd770}, {0x3217158, 0xc004070780}, 0x0)
/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/controller/controllerutil/controllerutil.go:339 +0x4f
sigs.k8s.io/controller-runtime/pkg/controller/controllerutil.mutate(0xc004070780, {{0xc00064e280, 0xc0049f1740}, {0xc00064e2e0, 0x10000d074ca8a68}}, {0x3217158, 0xc004070780})
/home/runner/work/external-secrets/external-secrets/pkg/controllers/externalsecret/externalsecret_controller.go:221 +0x1ca
github.com/external-secrets/external-secrets/pkg/controllers/externalsecret.(*Reconciler).Reconcile.func3()
/home/runner/work/external-secrets/external-secrets/pkg/controllers/externalsecret/externalsecret_controller_template.go:63 +0x3aa
github.com/external-secrets/external-secrets/pkg/controllers/externalsecret.(*Reconciler).applyTemplate(0xc0009b0180, {0x319ae80, 0xc0049f1740}, 0xc0043da000, 0xc004070780, 0xc0045c4180)
/home/runner/work/external-secrets/external-secrets/pkg/template/v2/template.go:72 +0x125
github.com/external-secrets/external-secrets/pkg/template/v2.Execute(0x31bb828, 0xc001011590, 0xc004070780)
goroutine 407 [running]:
panic: assignment to entry in nil map
```

seems to be caused by this assignment https://github.com/external-secrets/external-secrets/blob/80545f4f183795ef193747fc959558c761b51c99/pkg/template/v2/template.go#L72-L72

**Comment by gusfcarvalho** [comment]
Hi @nazarewk ! Can you provide your ExternalSecrets definition?

**Comment by nazarewk** [comment]
I don't know which one is it, we've 233 entries on the cluster

**Comment by nazarewk** [comment]
By the looks of it this line:
https://github.com/external-secrets/external-secrets/blob/80545f4f183795ef193747fc959558c761b51c99/pkg/controllers/externalsecret/externalsecret_controller_template.go#L42-L42
could cause `secret.Data` to be `nil` in case `dataMap` is nil (TBD: why?), then the execution of https://github.com/external-secrets/external-secrets/blob/80545f4f183795ef193747fc959558c761b51c99/pkg/controllers/externalsecret/externalsecret_controller_template.go#L63-L63
could cause 
https://github.com/external-secrets/external-secrets/blob/80545f4f183795ef193747fc959558c761b51c99/pkg/template/v2/template.go#L72-L72
to try to set a value on `nil`

**Comment by nazarewk** [comment]
While https://github.com/external-secrets/external-secrets/blob/80545f4f183795ef193747fc959558c761b51c99/pkg/controllers/externalsecret/externalsecret_controller.go#L397-L397 sets the `dataMap` to non-nil value, seems like https://github.com/external-secrets/external-secrets/blob/80545f4f183795ef193747fc959558c761b51c99/pkg/controllers/externalsecret/externalsecret_controller.go#L405-L405 could cause it to be `nil`

**Comment by nazarewk** [comment]
I've identified the externalsecret that was crashing controller:

<details>
<summary>Manifest</summary>
redacted some values out

```yaml
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  labels:
    app.kubernetes.io/instance: XXXXX
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: git-81....8742
    argocd.argoproj.io/instance: YYYYY-env-pr-12345-ns-app-XXXXX
    helm.sh/chart: app-18.5.2
  name: XXXXX
  namespace: pr-12345-ns
spec:
  data:
    - remoteRef:
        key: /YYYYY/database/pr-12345-ns/XXXXX
      secretKey: XXXXX_database
    - remoteRef:
        key: /YYYYY/kafka/default
      secretKey: default_kafka_cluster
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: default
  target:
    creationPolicy: Owner
    name: XXXXX
    template:
      data:
        KAFKA_BOOTSTRAP_BROKERS_TLS: '{{ get (mustFromJson .default_kafka_cluster) "bootstrapBrokersTls" }}'
        XXXXX_DATABASE_URL: '{{ get (mustFromJson .XXXXX_database) "readWriteUrl" }}'
        XXXXX_SUPERUSER_DATABASE_URL: '{{ get (mustFromJson .XXXXX_database) "superuserUrl" }}'
      engineVersion: v2
      metadata:
        annotations:
          reloader.stakater.com/match: 'true'
        labels:
          app.kubernetes.io/instance: XXXXX
          app.kubernetes.io/managed-by: Helm
          app.kubernetes.io/version: git-81....8742
          helm.sh/chart: app-18.5.2
```

</details>

But removing it and re-adding with same manifest fixed the issue for whatever reason. I guess it must have been some wild race condition across different systems?
