### ISSUE TITLE
Sync of keys with dots fails with "key xxx.yyy does not exist in secret"

### ISSUE THREAD

**Issue by nielsdemoen** [external-secrets/external-secrets#941]
Migrating from kes to eso, secrets with keys with a dot in the name fails.
For example:

```
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  annotations: {}
  labels:
    argocd.argoproj.io/instance: external-secrets-operator
  name: ssl-client-cert
  namespace: dev
spec:
  data:
    - remoteRef:
        key: gke-dev_ssl-client-cert
        property: client.crt
        version: latest
      secretKey: client.crt
    - remoteRef:
        key: gke-dev_ssl-client-cert
        property: client.key
        version: latest
      secretKey: client.key
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp
  target:
    creationPolicy: Owner
    name: ssl-client-cert
```

Generates an error: `Warning  UpdateFailed  2m5s (x242 over 122m)  external-secrets  could not get secret data from provider: key "gke-dev_ssl-client-cert" from ExternalSecret "ssl-client-cert": key client.crt does not exist in secret gke-dev_ssl-client-cert`

The key does exist since the secret was unchanged since it was used with kes and synced correctly using the same key names.
