### ISSUE TITLE
Fetching property key with a period in the key

### ISSUE THREAD

**Issue by kollektiv** [external-secrets/external-secrets#963]
When I have a AWS SM Secret with the contents

```json
{"foo.bar": "value"}
```

And the ExternalSecret .spec.data is like such

```
data:
    - secretKey: secret-key-to-be-managed
      remoteRef:
        key: provider-key
        property: "foo.bar"
```

There is an error that `foo.bar` does not exist. I assume ESO is expecting a JSON object like `{"foo": { "bar": "value" } }`. Please correct me if I'm wrong about this assumption. Is there a way to have the property interpreted literally?
