### ISSUE TITLE
external secret template for aws secrets manager variable is always nil

### ISSUE THREAD

**Issue by CodechArtium** [external-secrets/external-secrets#972]
When attempting to sync my docker config json from aws secrets manager following the [docs](https://external-secrets.io/v0.5.1/guides-common-k8s-secret-types/), I always get the error

```
Secret "docker-registry" is invalid: data[.dockerconfigjson]: Invalid value: "<secret contents redacted>": invalid character '<' looking for beginning of value
```

The external secret:

```
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: docker-registry
  namespace: default
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: docker-registry
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ .mysecret | toString }}"
  data:
    - secretKey: mysecret
      remoteRef:
        key: docker-registry
```

It appears that the variable `mysecret` is always nil as shown in the described output of the failing external secret:

```
  Target:
    Creation Policy:  Owner
    Name:             docker-registry
    Template:
      Data:
        .dockerconfigjson:  <nil>
      Engine Version:       v1
      Type:                 kubernetes.io/dockerconfigjson
```

I have checked my secret in aws secrets manager many times to confirm it is in the expected form of the docker config json:

```
{
  "auths": {
    "https://index.docker.io/v1/": {
      "auth": "base64 encoded string"
    }
  }
}
```

**Comment by gusfcarvalho** [comment]
Hi @CodechArtium ! When you try to create an ExternalSecret without the Templating, do you get the expected outcome?
i.e. does `mysecret` gets populated with 
```
{
  "auths": {
    "https://index.docker.io/v1/": {
      "auth": "base64 encoded string"
    }
  }
}
``` ?

**Comment by gusfcarvalho** [comment]
Can you also try `engineVersion: v2` as well?

```
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: docker-registry
  namespace: default
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: docker-registry
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      engineVersion: v2
      data:
        .dockerconfigjson: "{{ .mysecret }}"
  data:
    - secretKey: mysecret
      remoteRef:
        key: docker-registry
```

**Comment by gusfcarvalho** [comment]
Yes, but I think I failed to express myself. What is the output of `kubectl get secrets docker-registry -o jsonpath='{.data.mysecret}' | base64 -d` when you apply this ExternalSecret?

```
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: docker-registry
  namespace: default
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: docker-registry
    creationPolicy: Owner
  data:
    - secretKey: mysecret
      remoteRef:
        key: docker-registry
```

**Comment by CodechArtium** [comment]
That syncs the secret successfully. The output:

```
{"auths":{"https://index.docker.io/v1/":{"auth":"<credentials>"}}}
```

**Comment by gusfcarvalho** [comment]
Hi @CodechArtium! I could not reproduce your error on ESO v0.5.0. Here are the manifests that I used:
Secret Store
```
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secretstore-sample
spec:
  provider:
    fake:
      data:
      - key: "/foo/bar"
        value: '{"auths":{"https://index.docker.io/v1/":{"auth":"<credentials>"}}}'
```
ExternalSecrets
```
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: docker-registry
  namespace: default
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: secretstore-sample
    kind: SecretStore
  target:
    name: docker-registry
    creationPolicy: Owner
  data:
    - secretKey: mysecret
      remoteRef:
        key: /foo/bar
---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: docker-registry-template
  namespace: default
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: secretstore-sample
    kind: SecretStore
  target:
    name: docker-registry-templated
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      engineVersion: v2
      data:
        .dockerconfigjson: "{{ .mysecret }}"
  data:
    - secretKey: mysecret
      remoteRef:
        key: /foo/bar
```
Both of them get synced:
```
kubectl get es
NAME                       STORE                REFRESH INTERVAL   STATUS
docker-registry            secretstore-sample   1m0s               SecretSynced
docker-registry-template   secretstore-sample   1m0s               SecretSynced
```
And if I look at docker-registry-template content:
```
kubectl get secrets docker-registry2 -o jsonpath='{.data.\.dockerconfigjson}' | base64 -d
{"auths":{"https://index.docker.io/v1/":{"auth":"<credentials>"}}}%
```

Which seems to me things are working as expected. Can you share your ESO version and the external-secrets controller log?

**Comment by CodechArtium** [comment]
@gusfcarvalho I think a better test here would be to use aws secrets manager as a ClusterSecretStore instead of a fake secretstore. Would you mind trying that?

**Comment by gusfcarvalho** [comment]
It really wouldn't make a difference. Templating is applied After the provider returns a `map[string][]byte` which you already showed it worked.

But since you asked:

my secret at AWS SM:
```
aws secretsmanager get-secret-value --secret-id=foo/bar
    "Name": "foo/bar",
    "SecretString": "{\"auths\":{\"https://index.docker.io/v1/\":{\"auth\":\"<credentials>\"}}}",
    "CreatedDate": 1649699147.427
}
```
My ClusterSecretStore and my ExternalSecret
```
apiVersion: external-secrets.io/v1beta1   
kind: ClusterSecretStore
metadata:
  name: secretstore-sample
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-secret
            key: key
            namespace: default
          secretAccessKeySecretRef:
            name: aws-secret
            key: secret
            namespace: default
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: docker-registry-template
  namespace: default
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: secretstore-sample
    kind: ClusterSecretStore
  target:
    name: docker-registry
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      engineVersion: v2
      data:
        .dockerconfigjson: "{{ .mysecret }}"
  data:
    - secretKey: mysecret
      remoteRef:
        key: foo/bar
```

**Comment by gusfcarvalho** [comment]
Closed by accident :sweat: already reopened

**Comment by CodechArtium** [comment]
I see.

I was running ESO version 0.4.4 but just upgraded to 0.5.1 using the new `external-secrets.io/v1beta1` apiVersion and retested but came back with the same errors.

I'm able to sync all secrets. The only thing that isn't working here is templating so I believe that rules out permissioning or region misconfiguration. For the record, the correct region is being set on the clustersecretstore, which is `us-gov-east-1`.

```Is .dockerconfigjson available at your AWS Secret Manager instance```
Are you asking if I have confirmed that the secret exists in aws secrets manager? If so, I've checked many times for formatting and typos. It definitely exists under the secret name `docker-registry`.

Here are the logs:

```
{"level":"info","ts":1649699127.5781238,"logger":"provider.aws.secretsmanager","msg":"fetching secret value","key":"docker-registry","version":"AWSCURRENT"}
{"level":"error","ts":1649699127.6751986,"logger":"controllers.ExternalSecret","msg":"could not update Secret","ExternalSecret":"default/docker-registry","SecretStore":"/aws-secrets-manager","error":"Secret \"docker-registry-templated\" is invalid: data[.dockerconfigjson]: Invalid value: \"<secret contents redacted>\": unexpected end of JSON input","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:114\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:311\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:227"}
{"level":"error","ts":1649699127.685137,"logger":"controller.externalsecret","msg":"Reconciler error","reconciler group":"external-secrets.io","reconciler kind":"ExternalSecret","name":"docker-registry","namespace":"default","error":"Secret \"docker-registry-templated\" is invalid: data[.dockerconfigjson]: Invalid value: \"<secret contents redacted>\": unexpected end of JSON input","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:227"}

```

**Comment by gusfcarvalho** [comment]
This log message tells me that maybe the content from docker-registry is missing an ending `}`.

For instance, when I'm using this secret here:
```
{ "A": {"T": {"foo":"bar"}}
```
I am actually getting the same error message as you are.

this is due to the fact the kubernetes expect `.dockerconfigjson` to be a JSON value, and performs coherence checks on it. I'd recommend you get the secret from AWS secret manager and try to do `echo <my-secret> | jq` to see if it is actually a valid json.. You can confirm that on your premises by temporarily removing the type from the template spec:

```
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: docker-registry
  namespace: default
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: docker-registry
    creationPolicy: Owner
    template:
      # type: kubernetes.io/dockerconfigjson #commenting this line should make a secret with .dockerconfigjson appears, but it wouldn't be valid for kubernetes.
      engineVersion: v2
      data:
        .dockerconfigjson: "{{ .mysecret }}"
  data:
    - secretKey: mysecret
      remoteRef:
        key: docker-registry
```

**Comment by degibenz** [comment]
i have also reproduced this problem. But I used Vault as backend

```
{"level":"error","ts":1649709140.9053004,"logger":"controller.externalsecret","msg":"Reconciler error","reconciler group":"external-secret ││ s.io","reconciler kind":"ExternalSecret","name":"vault-docker","namespace":"yarus-io","error":"Secret \"regcred\" is invalid: data[.dockerconfigjson]: Invalid value: \"<secret contents redacted>\": invalid character '<' looking for beginning of value","stacktrace":"sigs.k8s.i ││ o/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v ││ 0.11.2/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/h ││ ome/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:227"}
```

ESO - 0.5.1

```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecretName }}-docker
spec:
  refreshInterval: 5s
  secretStoreRef:
    name: {{ .Values.secretStoreName }}
    kind: SecretStore
  target:
    name: "regcred"
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      engineVersion: v2
      data:
        .dockerconfigjson: '{{ .auth | toString }}'
  data:
  - secretKey: auth
    remoteRef:
      key: kubernetes/docker
```

**Comment by CodechArtium** [comment]
@gusfcarvalho I'm afraid it is indeed valid json. I've done validation on it about a dozen times at this point and have now confirmed passes the jq test.

Removing the `type` from the external secret shows as a successful sync but when inspecting the secret, the value actually comes up empty.

```
data:
  .dockerconfigjson: ""
```

**Comment by gusfcarvalho** [comment]
So, to summarize:

1) `aws secretsmanager get-secret-value --region us-gov-east-1 --secret-id docker-registry | jq ` is returning a valid JSON

2) the following manifest is returning the same valid JSON with the creds:
```
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: docker-registry
  namespace: default
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: docker-registry
    creationPolicy: Owner
  data:
    - secretKey: mysecret
      remoteRef:
        key: docker-registry
```
3) this manifest produces an empty value:
```
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: docker-registry
  namespace: default
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: docker-registry
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        .dockerconfigjson: "{{ .mysecret }}"
  data:
    - secretKey: mysecret
      remoteRef:
        key: docker-registry
```

Is this correct?

**Comment by gusfcarvalho** [comment]
Hi @degibenz ! `engineVersion: v2` there is no more `toString`. Can you try the following manifest?

```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecretName }}-docker
spec:
  refreshInterval: 5s
  secretStoreRef:
    name: {{ .Values.secretStoreName }}
    kind: SecretStore
  target:
    name: "regcred"
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      engineVersion: v2
      data:
        .dockerconfigjson: '{{ .auth}}'
  data:
  - secretKey: auth
    remoteRef:
      key: kubernetes/docker
```

Can you also try removing the ` type: kubernetes.io/dockerconfigjson` and see what is the generated secret contents?

**Comment by degibenz** [comment]
@gusfcarvalho Thank you. Unfortunately, I get this errors

Without `toString`
```
Warning  UpdateFailed     1s (x9 over 2s)  external-secrets  Secret "regcred" is invalid: data[.dockerconfgjson[]: Invalid value: "<secret contents redacted>": unexpected end of JSON input
````

Without `type: kubernetes.io/dockerconfigjson` generated empty secret-file with follow content
```
.dockerconfigjson: ""
```

**Comment by gusfcarvalho** [comment]
@degibenz can you confirm that the following manifest is also producing the right json?
```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecretName }}-docker
spec:
  refreshInterval: 5s
  secretStoreRef:
    name: {{ .Values.secretStoreName }}
    kind: SecretStore
  target:
    name: "regcred"
    creationPolicy: Owner
  data:
  - secretKey: auth
    remoteRef:
      key: kubernetes/docker
      ```
      
does `kubectl get secret regcred -o jsonpath='{.data.auth}' | base64 -d` returns the good json?

**Comment by degibenz** [comment]
@gusfcarvalho Yes, with this manifest I successfully create k8s-secret with type Opaque

**Comment by gusfcarvalho** [comment]
@degibenz can you share your `SecretStore` configuration, and as well where is your `docker` secret stored? please feel free to redact it.

**Comment by gusfcarvalho** [comment]
@degibenz @CodechArtium how are you deploying ESO? are you using one single controller or are you using multiple controllers? Are you setting leader election? Are you setting concurrency?

**Comment by gusfcarvalho** [comment]
I'm still not being able to reproduce this issue. Can you install ESO with the following additional arguments?

```
extraArgs:
   loglevel: debug
```

and get the logs one more time?  @moolen do you happen to have an idea what this issue might be?

**Comment by gusfcarvalho** [comment]
As a workaround, can you try to get the whole JSON and save it to your SecretStore as base64-encoded, and try to use the following manifest to see if the output is no longer empty?
```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecretName }}-docker
spec:
  refreshInterval: 5s
  secretStoreRef:
    name: {{ .Values.secretStoreName }}
    kind: SecretStore
  target:
    name: "regcred"
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      engineVersion: v2
      data:
        .dockerconfigjson: '{{ .auth | b64dec }}'
  data:
  - secretKey: auth
    remoteRef:
      key: kubernetes/docker
```

**Comment by degibenz** [comment]
@gusfcarvalho ESO deployed in single controller mode

For both manifest 
```
Error: template: serive/templates/external-secrets.yaml:32:39: executing "service/templates/external-secrets.yaml" at <b64dec>: invalid value; expected string
```

**Comment by degibenz** [comment]
@moolen yes, it's work correctly. Thank you 👍

**Comment by degibenz** [comment]
@moolen @gusfcarvalho Maybe your should at it to official documentation as workaround?

And @CodechArtium, Can you check this example manifest in your case?

**Comment by moolen** [comment]
Glad to hear that, closing this issue then. Feel free to reopen.

I don't see the need to add that explicitly to the docs as this is a helm-specific issue.

**Comment by gusfcarvalho** [comment]
I am going just to rewrite the title so other users can find out this issue a little bit faster.

**Comment by CodechArtium** [comment]
I think putting this in the docs would be wise. With how widely used helm is, seems like this is going to happen to a lot of people and it would save others lots of time. Either way appreciate the help on this. The templating feature is very nice.

**Comment by yodamad** [comment]
> ```yaml
> "{{ `{{ .auth }}` }}"
> ```

Facing same error, tried to escape as suggested but i got the error

```bash
Secret "my-secret" is invalid: data[.dockerconfigjson]: Invalid value: "<secret contents redacted>": invalid character '{' looking for beginning of object key string
```

What is stored in `auth` in your example : the JSON format or the base64 encode value ?

Thank you

**Comment by gotoweb** [comment]
@juliuszjaksa Thanks! you save me my life.

**Comment by stafot** [comment]
@juliuszjaksa You saved us tones of time

**Comment by angeloskyratzakos** [comment]
> I had the same issue as described. Problem was related to argocd. When you use argocd you must escape `{{`
> 
> My external secret template that worked: `data: .dockerconfigjson: '{{ "{{" }}.mysecret{{ "}}" }}'`

Thank you @juliuszjaksa.
For any future reference, as we are using Helm with custom charts and ArgoCD to deploy, the syntax below worked for us to setup dockerconfigjson:

```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "example-name.fullname" . }}-registry-aws-secret
  labels:
    {{- toYaml .Values.extraLabels | nindent 4 }}
spec:
  refreshInterval: {{ .Values.registryExternalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.registryExternalSecrets.secretStore }}
    kind: ClusterSecretStore
  target:
    name: {{ include "example-name.fullname" . }}-git-registry
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: '{"auths":{"registry.example.com":{"username":"{{ "{{" }}.username{{ "}}" }}","password":"{{ "{{" }}.password{{ "}}" }}","email":"{{ "{{" }}.email{{ "}}" }}","auth":"{{ "{{" }} printf "%s:%s" .username .password | b64enc{{ "}}" }}"}}}'
  data:
    - secretKey: username
      remoteRef:
        key: secret-stored-in-aws
        property: username
    - secretKey: password
      remoteRef:
        key: secret-stored-in-aws
        property: password
    - secretKey: email
      remoteRef:
        key: secret-stored-in-aws
        property: email
```

**Comment by nkreiger** [comment]
for my scenario, it was a GCP registry so it was a `_json` login, and needed to pass in the GCP service account key. I also ran into numerous issues, not sure if I did something wrong pasting into AWS Secret Manager. But ended up doing this:

1. echo 'GCP Key' | base64
2. Create secret in AWS Secret Manager Key/Value Pair: .dockerconfigjson = <base64 encoded value>

Create externalsecret and deploy with helm:

```
  data:
    - remoteRef:
        decodingStrategy: Base64
        key: fianu-dev/docker-registry-secret
        property: .dockerconfigjson
      secretKey: .dockerconfigjson
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: docker-registry-secret
    template:
      engineVersion: v2
      type: kubernetes.io/dockerconfigjson
```

key here was setting:

`type: kubernetes.io/dockerconfigjson`

and 

`decodingStrategy: Base64`

for me.

Trying any templating kept resulting in errors, removing it all, worked.
