### ISSUE TITLE
Advanced templating not working as expected

### ISSUE THREAD

**Issue by calebwoofenden** [external-secrets/external-secrets#990]
I'm following the first example in [this documentation page](https://external-secrets.io/guides-templating/). I am trying to template values from an AWS secret into a custom secret template that will ultimately be mounted onto a pod as a json file. Here is a snippet:
```
---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: example
spec:
  secretStoreRef:
    name: example-secretstore
    kind: SecretStore
  target:
    creationPolicy: Owner
    template:
      data:
        example.json: |
          [{"password":"{{ .password | toString }}","user":"{{ .user | toString }}"}]
  data:
    - secretKey: user
      remoteRef:
        key: my_aws_secret
        property: username_in_aws_secret
    - secretKey: password
      remoteRef:
        key: my_aws_secret
        property: password_in_aws_secret
```
Based on the documentation, I expect that `.user` and `.password` will be available as variables to reference in the secret template, but they both don't evaluate to anything. Is there something I'm missing?

**Comment by moolen** [comment]
> Based on the documentation, I expect that .user and .password will be available as variables

That is correct. If you are on a new-enough version i suggest using `apiVersion: external-secrets.io/v1beta1`, see [docs](https://external-secrets.io/v0.5.1/guides-templating/). That offers a better API from a UX perspective.

I assume that either the `property=(password|username)_in_aws_secret` is the issue or the SecretStore (e.g. wrong region).

Did you try to sync the whole secret without `property` and `template`, does that work?

```yaml
[...]
spec:
  data:
    - secretKey: user
      remoteRef:
        key: my_aws_secret
```

**Comment by calebwoofenden** [comment]
Thanks for the response. I spent some more time trying different things and realized that my issue was trying to use this example while also using Helm. Helm turns kube manifests into golang templates and this advanced templating engine is also using golang templates. Helm happens first, so Helm was trying to interpret these variables and they were not defined as Helm variables. The solution is to have Helm print the string literal value of `{{ .password }}` which looks something like this: `{{ printf "{{ .password }}" }}`

**Comment by michaelswierszcz** [comment]
this was the fix for me

```
  target:
    creationPolicy: 'Owner'
    template:
      data:
        password: "{{ printf "{{ .password | toString }}" }}"
```
