### ISSUE TITLE
ExternalSecretSpec target field should be optional

### ISSUE THREAD

**Issue by EricHorst** [external-secrets/external-secrets#996]
**Describe the solution you'd like**
According to the API ExternalSecretSpec.target is required.
However, all fields in ExternalSecretTarget are optional and have reasonable defaults.
I propose that ExternalSecretSpec.target should also be optional.

This will allow a minimal ExternalSecret such as
```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mysecret
spec:
  secretStoreRef:
    kind: SecretStore
    name: myvault
  dataFrom:
  - extract:
      key: something
```

As it stands now, we must provide some value in target: (name, creationPolicy, template or immutable) which simply re-states a default value in order to satisfy the requirement that target: exist.

**What is the added value?**

This makes the API less confusing by correcting a nonsense API setting where all fields under target are optional but target is required.

It makes ExternalSecret definitions simpler allowing one to accept defaults.

**Give us examples of the outcome**

Change CRD for ClusterExternalSecret and ExternalSecret so that target is not required.
